### ISSUE TITLE
IronPython support for `Dialogs` library

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1235]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1235) by @pekkaklarck on 18 Sep 2012*

<a href="https://code.google.com/p/robotframework/wiki/DialogsLibrary" title="A standard library providing dialogs for interacting with users.">DialogsLibrary</a> currently only works with Python and Jython. Implementing IronPython support using Winforms ought to be relatively simple.

**Comment by moto-timo** [comment]
I have two proposed solutions to this:

* The first one using WinForms, with its inherent flow limitations:
  - https://github.com/moto-timo/robotframework/tree/dialogs_ipy
* The second uses Windows Presentation Framework (WPF), with improved flow capabilities:
  - https://github.com/moto-timo/robotframework/tree/dialogs_ipy_WPF

Please test, for instance with:
```
ipy .\atest\run_atests.py ipy .\atest\robot\standard_libraries\dialogs
```
and give feedback. I will cleanup, remove IronPython caveat in Dialogs.py, and create a PR after a reasonable amount of time has passed.

**Comment by pekkaklarck** [comment]
Cool! I doubt I have time to look at this more closely today but I'll surely take a look at this soonish. I don't know what you mean with "flow limitations", but if they are bad the WPF version is probably better. It would be great if you could create a PR based on whichever you prefer (or both) because it's easier to test, review and comment them than your own branches. If you decide to do that, please also take a look at CONTRIBUTING.rst for general contribution guidelines.

**Comment by pekkaklarck** [comment]
PR #2126 looks so good that this will definitely be in the next release.
