### ISSUE TITLE
Possibility to use custom parser for test data

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1283]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1283) by jussi.vastimo on 21 Nov 2012_

We have many test cases defined for different framework. test cases are defined via xml file. 

I have made my own reader and added it to populators READERS dictionary. This works for me. Is it possible add this kind of parameter for Framework class?
from .xmlreader import XmlReader

READERS = {'html': HtmlReader, 'htm': HtmlReader, 'xhtml': HtmlReader,
           'tsv': TsvReader , 'rst': RestReader, 'rest': RestReader,
           'txt': TxtReader, 'xml': XmlReader}

**Comment by rjsmith** [comment]
Hi,
Is there any prospect of this ever getting added to the robot framework core? The hard work has already been done for you by Chris Prinos ...... I would really find it useful so that I can run RF tests directly from Microsoft Office files (using my bolt-on docx and xlsx parser)

**Comment by pekkaklarck** [comment]
The situation with this is very much open. On one hand we can see that supporting new test data formats would be useful, but on the other hand they do add maintenance burden and can also limit syntax choices in the future.

I would prefer alternative formats to be supported via an interface so that they could be developed independently similarly as test libraries, listeners and other tools. Obviously you can already now convert data in any format to format supported by Robot before running tests, but I would prefer it to be possible to use a programmatic API. Ideally you should be able to specify something like `--dataparser xsl:ExcelParser` to register a custom parser for `.xsl` files.

A twist in this planning is that we have been thinking could we in RF 3.0 drop HTML test data support and support only the plain text format (+ TSV which is nearly 100% compatible with it). Having a way to register custom parsers would make that change less backwards-incompatible and thus more doable.

Both supporting alternative parsers and possibly dropping built-in support for HTML format are something we need to ask community opinion about. Sending an email about the latter to robotframework-users is already on my to-do-after-RF-2.9-alpha-1 list and I can ask opinions about the former at the same time. We obviously can continue discussion here already before that.

**Comment by rjsmith** [comment]
Hi,
Thanks for replying, much appreciated!
The patch that Chris Prinos does exactly that: provides a hook for you to bolt on your own parsers. So, the only thing needed to be maintained in the RF core would be this patch.  Applied to my own ooxml parser library, users just have to invoke the new `--parser` RF argument: [see here](https://github.com/rjsmith/robot-ooxml/blob/master/README.rst#usage).

I, for one, would be happy to separately maintain the actual docx / xlsx parser in my own repo.  I guess if it then got sufficient traction in the community, it could be added to the core in the future.  I'll look out for the email on robotframework-users....

**Comment by pekkaklarck** [comment]
Thanks for clarification. Had forgotten that Chris had already implemented that. I'll take a closer look at this when I have more time. I'll tentatively assign this to RF 2.9 scope, but cannot make any promises will it actually make it yet.

**Comment by pekkaklarck** [comment]
Would someone be interested in creating a pull request with the proposed changes? It would make reviewing much easier?

By the way, does anyone know is Chris himself still interested in this topic? Is he on GitHub?

**Comment by rjsmith** [comment]
I've pinged him on a post to the original issue thread on google to see if he responds, else I would be willing to have a go... do you have any guidelines for PRs?  Thankfully, he had already included some acceptance tests in his patch.

**Comment by cprinos** [comment]
Hi all, I'm here :)

I'll take a look at changing the original patch over to a PR sometime in the next week or so

**Comment by pekkaklarck** [comment]
Hi @cprinos! Good to year you can convert the patch to a PR. There shouldn't have been too much changes to the related parsing code, so it shouldn't be that big a task.

**Comment by zephraph** [comment]
@cprinos, have you made any traction on this? I'd be willing to step in and assist if you don't have time.

**Comment by boakley** [comment]
Maybe with this change, *all* parsers could be external libraries, including all of the built-in ones. This would guarantee that the interface is fully functioning, and all parsers are on equal footing. There wouldn't be any special features that only built-in parsers can take advantage of.

**Comment by pekkaklarck** [comment]
`robot.running.TestSuite` objects that also Robot's parsers create can be programmatically constructed and executed simply by using `TestSuite.run()` method. This basically allows creating custom parsers that construct these objects based on external files in XLS, XML, or whatever format. A problem with this approach is that such a parser cannot be hooked up with Robot Framework and it could only work as a standalone tool that needs to handle command line options, creating logs/reports, and so on.

We could enhance the situation by making it possible to register such custom parsers from the command line. The usage could be something like `--parser xls:RobotExcelParser` and then in Robot's parsing modules we'd import `RobotExcelParser` and then use it like `suite = RobotExcepParser().parse(path)` with each `*.xls` file we encounter. The parser should then return `robot.running.TestSuite` object that we can add to our suite structure when executing a directory or just run on its own when running a single file.

This kind of change would have been hard to implement with the old parser, but the new parser (#3076) in RF 3.2 will make it pretty easy. If there's enough interest, I could possibly take care of that myself, but at least if someone would be interested to help we ought to be able to get this into RF 3.2 as well. One possible use case would be https://github.com/Snooz82/robotframework-datadriver by @Snooz82.

**Comment by boakley** [comment]
I think this is a great way to do it. I hope that the code allows us to specify our own parser for the built-in ones too. For example, `--parser robot:MyCustomRobotParser`. 

If the new parser was to be implemented in this way (ie: as a standalone module), it would serve as an example of how to create a parser. Plus, this would make it easy to subclass the built-in parser to add new functionality without having to modify the core.

**Comment by pekkaklarck** [comment]
We decided to add this to RF 3.2 scope. Partly because this is a generally useful feature and partly because it forces us to make APIs of the new parser good. At the moment (and in alpha 1) APIs aren't yet in that level but it won't be too much work to enhance them.

The built-in parser won't be a standalone module but it will be part of the public API and thus safe to be extended or used otherwise. We'll also make it possible to override the built-in parser with `--parser robot:MyCustomRobotParser`.

**Comment by pekkaklarck** [comment]
@d-biehl and @Snooz82 have been working with a new API to register custom parsers and hope to get it included in RF 6.1. Apparently in their implementation the parser itself has a list of supported extensions instead of the parser being registered to a certain extension. That sounds like a good idea to me.

**Comment by pekkaklarck** [comment]
Time to get this issue done. As the PR #4614 demonstrates, implementing this isn't too hard, but there are some important design decisions we need to do before the implementation can be finalized. I'll write separate comments about each decision and include also my personal opinion whenever If you have opinions yourself, you can use  :+1: and :-1: reactions or write your own comments.

**Comment by pekkaklarck** [comment]
**Decision 2: Should external parsers support suite initialization files?**

Suite initialization files (`__init__.robot`) are used for configuring suites created from directories. I believe external parsers should be able to do that as well. Handling initialization files isn't exactly the same as handling "normal" suite files and I believe the parser should have separate methods for them. I also believe the method for parsing initialization files should be optional.

**Comment by pekkaklarck** [comment]
**Decision 3: Parser API**

As already mentioned, the parser API in the PR uses the existing [BaseParser](https://github.com/robotframework/robotframework/blob/8fb2d0edfd350cce2f83400c350a492ce97c8372/src/robot/running/builder/parsers.py#L26). If we agree that external parsers cannot support resource files, using exactly that API isn't possible. I believe the API should be like this:

```python
class Parser:
    # File extension that this parser supports. Normally a string, but if
    # a parser supports multiple extensions it can be a list or tuple.
    EXTENSION: str|Sequence[str] = ''

    # Mandatory method for parsing suite files. `Defaults` contains default
    # values for test tags etc. got from suite initialization files.
    def parse(self, source: Path, defaults: Defaults) -> TestSuite:
        raise NotImplementedError

    # Optional method for parsing initialization files. If not implemented,
    # possible suite initialization files cause an error.
    def parse_init(self, source: Path, defaults: Defaults) -> TestSuite:
        raise TypeError('Parsing suite initialization files is not supported.')
```

I believe we shouldn't require parsers to extend any concrete base class and we can just check that parsers have mandatory `EXTENSION` and `parse` attributes. In simplest cases parsers could be implemented as modules:

```python
EXTENSION = 'example'

def parse(path, defaults):
    ...
```

Even if we wouldn't require parsers to extend a certain base class, we should expose an optional typed and documented base class `robot.api.interfaces` similarly as we've recently done with listeners (#4568) and the dynamic library API (#4567).

**Comment by pekkaklarck** [comment]
**Decision 4: How to initialize parser?**

With similar extensions like listeners and model modifiers it's possible to pass initialization arguments from the command line like `--listener ExampleListener:arg1:arg2`. I believe we should support that also with parsers simply because it can be useful and also for consistency reasons.

The PR initializes external parsers the same way the standard parser is initialized: parsers `lang` (a `Languages` instance containing language configuration like available setting names) and `process_curdir` (Boolean controlling should `${CURDIR}` be resolved or not). The latter is pretty much an implementation detail of the standard parser and shouldn't be relevant with other parsers, but the former can be useful in some cases.

Although passing language configuration to parsers could be useful, I believe we should only pass them configuration arguments given from the command line like we do with other similar extensions. We could consider passing `lang` in addition to given arguments, but would mean parsers should always have `__init__` that accepts `lang`. It would be annoying with class based parsers not needing language info and would make it impossible implement parsers as modules.

I believe just passing explicit configuration arguments is best now, but we can consider making it possible to receive language configuration and possibly other info later. We could, for example, look does a parser have an `__init__` that accepts a keyword-only argument `lang` to see should language info be passed to the parser or not. The same approach could be used also with other extensions.

**Comment by pekkaklarck** [comment]
There were no comments to the design decisions I asked a week ago, so I decided to go with the design I proposed. Initial implementation is now ready (d973fb86b34f7290ccc2377889415698d527f3c6) and the API looks and feels pretty good to me. There is, however, plenty of work still:

- [ ] Acceptance tests. My initial tests work well, but they need to be converted to proper acceptance tests.
- [ ] Documentation in source (--help, API docs, ...). I added initial API docs, but there are some holes and the --help text is completely missing. I added FIXMEs to places where more docs are needed.
- [ ] User Guide documentation.
- [ ] `Defaults` API. We pass `Defaults` as the second argument to `parse` and `parse_init` methods, but that class itself doesn't have too good API. It needs to be enhanced and then documented and typed properly. The class could possibly also get a better name and it needs to be exposes directly via `robot.running`.

I hope @d-biehl and others interested in the new parser API can give this a try. I won't be able to do any coding during the coming weekend, but I return to this next Monday.

**Comment by pekkaklarck** [comment]
I knew getting the `Defaults` API good isn't easy, but it required even more work than I anticipated. It's now done in above commits and here's a summary:

- `Defaults` was renamed to `TestDefaults`.
- It has `setup`, `teardown`, `tags` and `timeout` attributes. `setup` and `teardown` are `Keyword` objects or `None`, `tags` are `Tags`.
- It has types and documentation.
- Because not all parsers are interested in defaults, it's possible to implement `parse` and `parse_init` so that they only accept `source`.

Now that defaults ought to be ready (testing and comments appreciated!), this functionality ought to be fully implemented and tested. There's still some documentation to do, but I should be able to get it written tomorrow.

**Comment by pekkaklarck** [comment]
The new parser API has now been documented and there have also been few smallish enhancements. I consider this issue done. Testing and all kind of comments are highly appreciated!

**Comment by pekkaklarck** [comment]
@d-biehl commented on Slack that it would be good if the parser API supported multi-part extensions like `.feature.md`. That's a good idea so I'll add that support still. It's not trivial but shouldn't be overly complicated. Thanks for feedback!
