### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1506]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1506) by sabbir.shafi on 18 Aug 2013_

Later versions of Python 2.7 does not support robot framework...

**Comment by spikergit1** [comment]
Word on the street (https://github.com/robotframework/robotframework/issues/1912#issuecomment-73610630) is that RF 2.9 will drop j/python 2.5 support.  Does that mean that the python3 support can be / will be integrated in RF 2.9?

**Comment by pekkaklarck** [comment]
I doubt we have time for that. The main goal of dropping 2.5 support is making it easier to add 3.x support later. If required changes are not too big, we can consider that already in RF 2.9, though.

**Comment by userzimmermann** [comment]
### Status update :)

The latest release of my [Python 3 compatibility port](https://github.com/userzimmermann/robotframework/tree/python3) is __2.8.7__:

https://github.com/userzimmermann/robotframework/releases/tag/python3-2.8.7
https://pypi.python.org/pypi/robotframework-python3/2.8.7

Complete diff to original __2.7.8__:

https://github.com/userzimmermann/robotframework/compare/2.8.7...python3-2.8.7

Further I merged with recent commit https://github.com/robotframework/robotframework/commit/3a7571d23030166244c8dd1785346b41680dadbf which already contains many Python 2.5 incompatible code updates as discussed in #1928 and lots of code restructuring.
I got a lot of merge conflicts :D but they are solved.
There are only a few new __utests__ and __atests__ which need some more compatibility adaptions.

You can always get the latest complete code diff at:

https://github.com/userzimmermann/robotframework/compare/master...python3

I also started to create issues for __atests__ FAILing on Python 3:

https://github.com/userzimmermann/robotframework/issues

So anyone can participate in solving them. They generally only need workarounds in the __atests__ themselves.

And the best thing is... actually not the best but very close ;)
__It is still running on Python 2.6!!!__ (At least with Python 2.6.8)
I remember there were some issues with Python 2.6 in the beginning of my fork. I can't remember exactly. But I declared my fork incompatible with Python 2.6 because of them and defined 2.7 as the only compatible Python 2 version. I was just curious and ran the tests of the current code with Python 2.6 and it worked. Maybe the earlier issues were only related to older Python 2.6.x versions or somehow resolved by using __six__.
I would appreciate if someone could run the tests with some older Python 2.6 version.

**Comment by pekkaklarck** [comment]
Great progress! I browsed through parts of the diff and here are some comments:

1. Wow, lot of changes! Luckily changes under `src` seem to be mostly pretty simple.

2. There are a lot of changes related to `print` and `1 / 2` that could be easily merged to master. We can either add `from __future__ import print_function, division` to relevant files or just use `print('hi')` and `1 // 2` formats without them. The former is probably better under `src`, but the latter ought to be adequate in tests. Additionally, using `print` for logging could be replaced with `robot.api.logger` in many places to avoid `print` altogether.

3. In general I hope we could get started with this work by getting more and more Python 3 compatibility in as smallish pull requests. Massing PR with all changes is just way too much to review. Smallish PRs fixing individual topics, like print or division, would be much easier to handle for everyone involved.

4. We need to think what to do with `six`. I would not like to make it a required dependency for people wanting to run Robot on Python 2 (nor on Python 3 if possible). Currently Robot has no external dependencies, and it definitely eases installing it on environments without network access. We'll see later do we actually need it or could we live without. It's anyway best to start from easier changes that don't require it.

**Comment by pekkaklarck** [comment]
I browsed through the diff a little longer and I'm fairly convinced we don't eventually need six. Things to do instead:

1. Add utility functions `is_string`, `is_unicode`, `is_integer` to avoid `isinstance` checks against `basestring`, `unicode` and `(int, long)` that have all changed. Natural home for these is `utils.robottypes`. Current `is_str_like` should be renamed to `is_string_like` to be consistent with `is_string` (I don't want `is_str` because it would be misleading). All this could be done in master right away!

2. Add `PYTHON3` and `PYTHON2` flags to `utils` next to newly added `JYTHON`, `WINDOWS`, etc. I prefer that spelling instead of `PY2/3` because it is consistent with our other flags.

**Comment by userzimmermann** [comment]
I basically agree that most of my six use can be handled with some simple custom compatibility layer.
I also used only a small fraction of all the six features.
However, there are some features like `six.moves`,` with_metaclass` and `reraise` which need some more effort to reimplement and which end up in reinventing the wheel to some degree.
Anyway, I started adding `PYTHON2/3` vars and `is_<type>/<type>_like` functions and some common type definitions and imports to `robot.utils` and opened  pull request #1937 for this.

**Comment by pekkaklarck** [comment]
I know there are cases where `six` would really help us, but I'm not yet convinced we need it so much that having an additional dependency is worth it. Handling differences between str/unicode/int/long types ought to be easy as PR #1937 indicates. Do you have an idea how many places we have where `six.moves`, `with_metaclass` or `reraise` are needed? If there are only few, special casing them shouldn't be a big problem.

**Comment by userzimmermann** [comment]
It took a while... I was quite busy the last weeks... but: __2.9a1__ !

https://github.com/userzimmermann/robotframework/releases/tag/python3-2.9a1
https://pypi.python.org/pypi/robotframework-python3/2.9a1

Complete diff to original 2.9a1:

https://github.com/userzimmermann/robotframework/compare/2.9a1...python3-2.9a1

Now I will continue with #1937

**Comment by userzimmermann** [comment]
It's been a while... again ;)

I merged with **2.9rc1** and things are still working very well!
Lots of merging conflicts due to #1990 but nice to see how the diff is slowly shrinking... ;)

https://github.com/userzimmermann/robotframework/compare/master...python3

I will do some some further cleanup and resolve an additional **atest** issue and then make a **robotframework-python3-2.9rc1** release... trying to get it done this evening

**Comment by userzimmermann** [comment]
No need for a **robotframework-python-2.9rc1** release:

https://pypi.python.org/pypi/robotframework-python3/2.9
https://github.com/userzimmermann/robotframework/releases/tag/python3-2.9

Right on time! :)

**Comment by userzimmermann** [comment]
@pekkaklarck After applying `is_<type>` checks from #1990 to the test code, I would like to introduce `__future__.print_function` to the standard code base as next migration step. What do you think?

**Comment by pekkaklarck** [comment]
`print_function` sounds fine. In many places it would be a good idea to avoid `print` in favor of `robot.api.logger` or `sys.stdout.write`, depending on the context.

**Comment by pekkaklarck** [comment]
Official Python 3 support is very close. All acceptance tests pass on Linux, OSX and Windows, and installation with Python 3 seems to work fine. Final tasks to do before this issue can be considered done:

- [ ] setup.py must be updated to list Python 3 as a supported version.
- [ ] Go through TODOs and FIXMEs in code and see is there anything Python 3 related.
- [ ] Document supported Python versions (2.6, 2.7, 3.3->) in User Guide, README.rst, and INSTALL.rst.
- [ ] Decide do we want to create `pybot3` script to avoid overwriting `pybot` script created by Python 2. Alternatively we could start using generic `robot` script with all interpreters. That requires a separate issue, though.

**Comment by pekkaklarck** [comment]
Final tasks listed in my previous comment are all either done or handed by other issues. I guess we can consider this issued finally done! Go Python 3!!!!!!!!!!!!!!!!!!
