### ISSUE TITLE
Keyword's source information to log file

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1708]
> *Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1708) by @Tattoo on 14 May 2014*

It would be nice to see the source information in the log file ie. which file the keyword is coming from.

This is a request from NSN.

**Comment by pekkaklarck** [comment]
We decided not to implement this at this point.

The main reason is that adding the source information to all keywords would increase output.xml size considerably. If same keyword would be used multiple times, its source would also be included there multiple times. A solution for that would be storing information about each keyword separately so that source (and also doc) would be there just once, but that would be quite a bit of work and would also make parsing output.xml more complicated.

Another reason we decided to to implement this is that we don't know what was the original motivation to get the source into output.xml in the first place. It might be better to get that information, for example, via the listener interface. Increasing output.xml size, or spending a lot of time to avoid increasing it when source would be added, is not a good idea when we aren't even sure is the functionality actually useful.
