### ISSUE TITLE
Support setting child suite variables with `Set Suite Variable`

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1728]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1728) by saku.chydenius on 5 Jun 2014_
### Example 1.

Consider a suite hierarchy as follows:

```
test
test/__init__.robot
test/1
test/1/__init__.robot
test/1/a
test/1/a/__init__.robot
test/1/a/test_a.robot
```

Currently only way for `test_a.robot` to get variables for parent initializations, is that the parents set the variables as global. Same stands even for the upmost `test/1/a/__init__.robot` file which is at the same level as the `test/1/a/test_a.robot` suite.
### Example 2.

Consider another hierarchy:

```
test
test/1
test/1/a
test/1/a/__init__.robot
test/1/a/test_a.robot
test/1/b
test/1/b/test_b.robot
```

Now that only way for `test/1/a/test_a.robot` to get the initialization data from `test/1/a/__init__.robot` is by global variables, those are visible also in the b suite `test/1/b/test_b.robot`. This brings further problems like: the `***Variables***` table in the test suite B cannot override any of the global variables set by suite A.
### Possible solution

There would be a need for a new variable scope, called e.g. "Child Suite Variable" that would expose the variables only to the child suites. In practice it would mean that

in example 1.:

Any variable set as "Child Suite Variable" in any of the 3 `__init__` files would be visible in the actual tests in the `test/1/a/test_a.robot`.

in example 2.:

The variables set in suite A `__init__` would not be visible to suite B in any way.

Attached an example using pybot.

BR.
-sac-

**Comment by pekkaklarck** [comment]
We decided to implement this so that `Set Suite Variable' can optionally set variables so that they affect also child suites. This functionality can be enabled by using `children=<value>` as the last argument to the keyword and having anything considered true as the `<value>`.  Possible variables set like this will override variables in the variable table.

It would also be possible to enhance `Set Suite Variable` so that it could update parent suite variables. We decided to to implement that because the original description didn't mention it and we weren't  certain what would be the best syntax to specify which parent to update. This can be added later if needed.
