### ISSUE TITLE
Make keyword prefix (library name) less visible than keywords in HTML reports

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#1743]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=1743) by sylvain.hellegouarch on 28 Jun 2014_

When a test case is large, the HTML report can become very busy, actually noisy. It would be useful I think if you were making the prefix of keywords slightly less visible. This would make the keywords stand out. Perhaps by making the prefix being grey or pale?

**Comment by pekkaklarck** [comment]
Issue #1967 underlined some problems in `name` passed to listeners related to this issue and #1611. Assuming we separate library/resource name and keyword name (this issue) and also drop variable assignment from the name (#1611), we need to decide what information pass to listeners. I think we should do this:

1. Change `name` so that it contains only keyword name. This is backwards incompatible, but having current `${var} = library.Keyword` just doesn't make sense to me. If we drop assignment, we should drop library/resource name too.

2. Add new `assignment` (or similar) attribute that contains the assignment part (this is only related to #1611).

3. Add new attribute that can be used to construct the whole keyword name. There are several options:

    - Add new `longname` attribute that contains library/resource name and keyword name. This would be close to the current `name`, but I don't think it should contain assignment. Drawbacks include duplicate information  (`longname` contains also `name`) and library/resource name not being readily available.
    - Add new `parent` attribute that contains library/resource name (or None or an empty string when keyword is in a test case file). This would make it easy to construct the current `name` with or without assignment if needed.
    - Add separate `resource` and `library` attributes that contain resource/library name. At least one of them would always be empty. Would have a benefit that listeners know did the keyword originate from a resource or a library, but would make constructing full name a bit more complicated.

Comments about this from people writing listeners are highly appreciated.

**Comment by aaltat** [comment]
1&2) Sounds good to me
3) I would go for the last option, because then it would be easy to deside the whole name. If last option is too hard to implement, then second option is also good to go. But I wouldn't go for the first option.

Should the core dev also post the question to the user group too? To get a wider coverage to question

**Comment by pekkaklarck** [comment]
Wouldn't it actually be a little easier to create the full name with 3.ii than 3.iii? The only benefit of 3.iii is that you would know is the keyword from a library or from a resource, but I'm not sure is that worth adding separate attributes.

Yeah, we need to send a mail about this and possible other related changes in alpha 2. I'm currently on holiday and will start looking at alpha 2 more next week. If you want, you can start a discussion on users list about this also yourself before that.

**Comment by aaltat** [comment]
Yes, 3.ii would be easier but not better. At least for me, all keywords from resources have unique name but library keywords have conflicts. Therefore separating the the prefix with resources and library parts would be most useful for me. Then I could easily decide, based on where the keyword is coming, do I want to keep the prefix or not.

**Comment by jussimalinen** [comment]
Above commits already implemented needed changes in internal model and log. Log file looks considerably better than earlier with these changes and not including variable assignment in name (#1611). It is still possible to enhance related styles if needed, though.

We decided to open a separate issue #1998 about listener interface changes.
