### ISSUE TITLE
Embedded arguments in keywords defined in test libraries

### ISSUE THREAD

**Issue by frishberg** [robotframework/robotframework#1818]
Following up on this:
https://groups.google.com/forum/#!msg/robotframework-users/J56wzoWU89I/Jxi3pL3G0-UJ
and this:
https://groups.google.com/forum/#!topic/robotframework-users/__rHImRK4aE

I think support can be added using the syntax proposed in the first thread.

Regarding this problem:
> A bigger problem would be how to support this with the static library
API. It's not possible to have a method with name like
"high_${number}" in the code so we needed to figure out some other
syntax. Any ideas?

Could we separate argument names with two underscores?
```
def method_with_argument__foo__:
    ...
```

----------
Note by @pekkaklarck: We have decided to implement this based on a custom name given to keywords using `robot_name` attribute that was implemented as #1835.

**Comment by hellmanj** [comment]
@pekkaklarck, I spent some time trying to understand the inner workings I'd need to change but I think I could use that chat on IRC you offered if you have the time.  Can you let me know a few times that would be good for you?

**Comment by pekkaklarck** [comment]
@hellmanj, like earlier, after 10pm my time (UTC+2) is probably best but before 4pm is often good too. If you don't have anything today or later this week, just try to ping me on IRC. Or should we agree some time beforehand so that others can also join?

I can understand that figuring out what's the best place to implement this functionality is not easy. The related code is old and bad in many ways. Luckily it's now good time to refactor it before a new major release.

**Comment by hellmanj** [comment]
Others are certainly welcomed and encouraged, can we plan on Wednesday @ 10PM (UTC+2), 3PM (UTC-5) then?  It will give people time to ask us to reschedule.   Should we invite some people or is commenting here enough to draw attention?

**Comment by pekkaklarck** [comment]
Wed 20:00 UTC sounds great. Not that many people is following this issue, so let's spread the word in case someone else is interested. Can you send a mail to robotframework-users and tell about the plan? I can mention it on IRC right away.

**Comment by hellmanj** [comment]
Sure, will do.

**Comment by pekkaklarck** [comment]
Yesterday's chat didn't go too well due to IRC problems @hellmanj had. Should we try again today same time?

**Comment by hellmanj** [comment]
Yes, sorry again about that.  Let's do the same time today.

**Comment by pekkaklarck** [comment]
Thanks for discussion today @hellmanj! Logs can be found from here:
http://koti.kapsi.fi/~peke/irclogs/robotframework/2015-01-29.log.html

**Comment by pekkaklarck** [comment]
@hellmanj: Above commits ought to make embedded arguments stuff more generic and easier to reuse. Hopefully they help your work. Let me know if you have any questions.

**Comment by hellmanj** [comment]
@pekkaklarck , I haven't tested it extensively yet, but it would be great to get feedback on my first cut at this:  https://github.com/hellmanj/robotframework/commit/89eb06cf298d8b9a1020ddb4b0d5b08a54d8ba5a

**Comment by pekkaklarck** [comment]
@hellmanj Do those tests already pass? That would be awesome!

I added some comments. Didn't have time to go the code through that thoroughly nor actually test it, though. Comments may thus be totally invalid.

**Comment by hellmanj** [comment]
Yep, all critical tests pass including the new one.  

Thanks for the feedback.  Maintaining the factory/inheritance pattern already in place made sense to me, but I'll give a composition solution a shot too.  I think I understand how to do it now.

**Comment by hellmanj** [comment]
Okay, please check out https://github.com/hellmanj/robotframework/commit/d109bdfbce913b96ed84e425d27a07f581b85f3b

**Comment by pekkaklarck** [comment]
PR #1917 has been merged and few smallish enhancements done. Thanks a lot for your hard work @hellmanj and @frishberg!!

**Comment by pekkaklarck** [comment]
Tests using this functionality with Given/When/Then prefixes are failing on IronPython due to this bug: https://github.com/IronLanguages/main/issues/1192

I have been working with a workaround, but I'm too tired to finish it tonight and may be too busy with other tasks tomorrow. I also want to enhance related tests a little to make sure embedded args really work correctly with Given/When/Then. Unfortunately this may postpone alpha 1 a little, but I'm sure we get it out latest on Monday.
