### ISSUE TITLE
String: Support partial match with `Get Lines Matching RegExp`

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#1834]
Current regular expression is using '^%s$' and re.match, this is not what the user pretend, although the name of the Keyword may lead to confusion (if so we need a Get Lines Containing RegExp).
Below is my proposed patch, based in BuiltIn.Should Contain RegExp:
--- C:\Python27\Lib\site-packages\robot\libraries\String_orig.py
+++ C:\Python27\Lib\site-packages\robot\libraries\String.py
@@ -250,8 +250,8 @@
         String` if you do not need full regular expression powers (and
         complexity).
         """
-        regexp = re.compile('^%s$' % pattern)
-        return self._get_matching_lines(string, regexp.match)
+        regexp = re.compile('%s' % pattern)
+        return self._get_matching_lines(string, regexp.search)

```
 def _get_matching_lines(self, string, matches):
     lines = string.splitlines()
```

**Comment by HelioGuilherme66** [comment]
The PR #1836 is now ready for final review. Added option ``exact_match`` True by default to ``Get Lines Matching RegExp``. Could not write a better example, because RIDE was altering ``[`` ``]`` to a link marker.

**Comment by pekkaklarck** [comment]
`exact_match=True` is a good solution. It can be added to other regexp keywords later if there's a need. PR #1836 also looks good (except that it contains 21 commits most of which are merges).

If you @HelioGuilherme66 are willing to fix the issues I pointed out in the PR, we can still get this into RF 2.9. Our plan is to get beta 2 our already on Wednesday and have all code changes done this week so that we could have first release candidate already early next week.

**Comment by pekkaklarck** [comment]
This looks useful and ready enough to be added tentatively to RF 2.9 scope.

**Comment by pekkaklarck** [comment]
I'm currently merging PR #1836. While reviewing it for the last time, I started to think it would be better to use `partial_match=False` than `exact_match=True`. It is generally easier to pass true values than false values, and it is also a bit easier to explain that partial matching can be enabled with `partial_match` argument. I'll change the behavior after I've merged the PR locally.

**Comment by pekkaklarck** [comment]
I manually squashes PR #1836 in 4c178d399c39aa35d0bfefbf96a9aba26a52ac76 and did some enhancements in 02fe31f6fd0fc4fc73dbcfeaf706121804eb97b9. I'll reopen this issue so that @jussimalinen can review the final implementation, especially docs, of the enhanced `Get Lines Matching Regexp` keyword.

Thanks for the issue and the PR @HelioGuilherme66! I hope you can also review the changes and comment here if you think something could still be improved.

**Comment by jussimalinen** [comment]
Looks good!
