### ISSUE TITLE
Variable errors should not exit `Wait Until Keyword Succeeds`, `Run Keyword And Expect Error`, etc.

### ISSUE THREAD

**Issue by bjornfor** [robotframework/robotframework#1869]
I realize that whether or not this is considered a bug depends on how the documentation for "Wait Until Keyword Succeeds" is interpreted:

```
All normal failures are caught by this keyword. Errors caused by invalid syntax,
test or keyword timeouts, or fatal exceptions (caused e.g. by Fatal Error) are not caught.
```

(Is AttributeError a fatal exception?) But even if the behaviour is currently documented, I think it is really unfortunate that AttributeError is not a normal error.

Imagine that you have a test library that retrieves some object. On error, an exception is raised and None is returned instead. And if this is in a Teardown context, errors are ignored and robot continues to the next keyword. This keyword then runs into the AttributeError because a None object was received instead of the real/expected object. Now the "Wait Until ..." is stopped before the timeout.

How to get out of the above situation, unless AttributeError is handled like a normal error?

Here are two test cases to play around with (at least for my own reference):

```
*** Test Cases ***
"Wait until ..." with normal error
    # Keyword is run multiple times, until timeout. Each run gives an exception
    # traceback.
    Wait Until Keyword Succeeds    1 sec    0.5    Keyword With Normal Error

"Wait until ..." with AttributeError
    # Keyword is run only once, even if there is time left until the timeout.
    # There is no exception traceback like above.
    Wait Until Keyword Succeeds    1 sec    0.5    Keyword With AttributeError

*** Keywords ***
Keyword With Normal Error
    ${obj} =    Evaluate    "foo"
    Should Be Equal As Strings    ${obj}    "bar"

Keyword With AttributeError
    # In real life, this would get an object and use some of its (valid) attributes.
    # In case of an error, and in Teardown context (continue-on-failure), a None object
    # is returned instead causing the next keyword to create an AttributeError.
    ${obj} =    Evaluate    "foo"
    Should Be Equal As Strings    ${obj.bad_attr}    "foo"
```

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I don't think changing the type of variable related errors is worth the effort. DataErrors are raised and handled in so many places that changing them, and making sure nothing breaks, would just be too big a task.

We could consider changing WUKS so that it catches also DataErrors, though. What do you think? As discussed above, WUKS will eventually fail anyway, even if the error would be caused by a syntax error. Timeouts definitely should be uncatchable also in the future.

**Comment by pekkaklarck** [comment]
This issue came up again as #2024. I initially though we should change variable related errors not to use `DataError`, but now that I read my previous comment here, I remember that it would be quite a big task to change all code excepting them when handling variables.

A better solution would be creating a new exception like `VariableError` or `NonExistingVariable` that is based on `DataError`. This way all code excepting `DataError` would work like earlier, but but it would be also possible to differentiate variable related errors in WUKS and possibly in other places. Would someone be interested to prototype that? There's still a little time to get it into RF 2.9.

**Comment by jcdevil** [comment]
@pekkaklarck : i'm interested in prototyping this ! ... currently studying the code / tests. Cheers

**Comment by pekkaklarck** [comment]
@jcdevil, great! Any progress? Changing all errors about variable missing to a special exception that's based on `DataError`, like I proposed in my previous comment, shouldn't be too complicated.

**Comment by jcdevil** [comment]
@pekkaklarck : yep I aim to send my PR this end of week :)
As I understood your previous comment, you suggest to create a new class : `VariableError(DataError)`
But in that case this error will still be treated as a syntax_error because `syntax = isinstance(details.error, DataError)` will be `True`. And in that case, WUKS will exit on the first attempt. Am I misleading ?
Thx for your feedback.

**Comment by pekkaklarck** [comment]
You seem to be right. I thought WUKS would itself catch `DataError` in which case it could catch `VariableError` separately but apparently lower level exceptions are handled elsewhere and WUKS only sess `ExecutionFailed'.

One possibility would be changing the logic that determines is something a syntax error e.g. like `syntax = isinstance(details.error, DataError) and not isinstance(details.error, VariableError)`. That's a bit ugly, but it would be interesting to know does it work.

**Comment by jcdevil** [comment]
This is indeed what I'm currently testing and it does the job ;) although not so nice... as you said ;)
BTW. I'll check all other tests are still working fine... and the new ones are OK.
Thx for your quick feedback ! Cheers

**Comment by pekkaklarck** [comment]
Great to hear that approach works. Separating `VariableError` and `DataError` would probably be cleaner, but it would most likely require much more changes. It would be great if you could investigate that too so that we can decide what's the best approach. If you are interested in creating a pull request with fixes and tests, we still ought to have enough time to get this into RF 2.9.

**Comment by pekkaklarck** [comment]
Keywords that currently let variable related errors to go through are:

- Wait Until Keyword Succeeds
- Run Keyword And Expect Error
- Run Keyword And Ignore Error
- Run Keyword And Continue On Failure

**Comment by pekkaklarck** [comment]
PR #2057 has been merge and tests and docs enhanced slightly in a04008f317f92945774449bc6bef6259b3b9b281. This issue is done. Thanks a lot for a great PR @jcdevil!

**Comment by bjornfor** [comment]
Thanks!

**Comment by laurentbristiel** [comment]
Thanks @pekkaklarck and @jcdevil!! Very useful feature for me!
