### ISSUE TITLE
Tidy should split lines longer than n characters

### ISSUE THREAD

**Issue by guykisel** [robotframework/robotframework#1891]
It's pretty common in most languages to have a style convention limiting line length to something like 80 or 100 characters. Currently Tidy will split rows that have more than 8 cells, but if individual cells are long, then rows can get very long and hard to read. It would be nice if Tidy could split lines longer than some configurable value (with a reasonable default).

**Comment by pekkaklarck** [comment]
I agree this would be nice feature in plain text mode. Tidy could be changed to split lines based on length in plain text mode and based on cell count in HTML and TSV modes.

**Comment by wojciechtanski** [comment]
I am taking it for implementation

**Comment by pekkaklarck** [comment]
@wojciechtanski, there's already pr #1894 by @guykisel about this. It just was a bit too complicated/clever, mainly because the related Tidy code was too complicated/clever. We agreed Tidy's original code should be refactored first, but that is a pretty big task considering that this isn't such a high priority issue.

If you @wojciechtanski found this issue important, please at least take a look #1894 first. We can then discuss how Tidy should be changed to make it easier to implement this feature. If you are only looking for issues to implement, it might be a better idea to look is there something else than requires less work compared to benefits.

**Comment by richcocoa** [comment]
@pekkaklarck Could you please review my PR #2771 and let me know if you think it is alright?

**Comment by fabo-at-noona** [comment]
I've got interest in this issue and 2 PRs has been proposed. I believe the contributor lost patience waiting for a review on PR#2771 and moved one.
@pekkaklarck any chance to have a look at PR#2771 ?
I'm willing to take over the PR and get it fixed/merged but we still need a reviewer...

**Comment by pekkaklarck** [comment]
Yeah, this has been lingering too long. Sorry for that. However, right now is not a good time to implemented this or merge PRs. We are currently reimplementing the test data parser and it totally changes APIs that Tidy uses. How those APIs will look like isn't clear yet. Good news is that the new parsing API is going to be a lot better than the old one. It will, for example, be possible to preserve old formatting except in places we explicitly want to change. That makes it possible to add new features to Tidy. At that point one possibility is making Tidy a separate project to allow it being developed further without thinking RF release schedules.

**Comment by guykisel** [comment]
Sorry I never finished that PR :( I haven't gotten to work with Robot Framework or Tidy in a few years :(

**Comment by fabo-at-noona** [comment]
@guykisel no worries. @pekkaklarck ack, then we need the test data reimplementation to happen, adjust tidy to its new API. I assume the work is happening in https://github.com/robotframework/robotframework/tree/newparser-squashed

**Comment by pekkaklarck** [comment]
Yeah, that's the right branch. Due to holiday season starting here in Finland and RoboCon 2020 planning taking some time there hasn't been too much activity lately. I plan to do something during summer, but work will resume more actively in late August.

Are you @fabo-at-noona possibly interested to help with Tidy? If yes, we can take a look at how related code looks like now. We can continue discussion on the #devel channel on our Slack.

**Comment by pekkaklarck** [comment]
The new parser branch mentioned above has been merged to master. At the time of this writing Tidy is still broken, but @yanne is working hard to get it fixed (i.e. re-implemented). One big change is that nowadays line continuations (`...`) are preserved and Tidy won't anymore split *any* lines. Having an option to split long lines would be very nice.

Are you @fabo-at-noona still interested in enhancing Tidy?

**Comment by pekkaklarck** [comment]
If some kind splitting is implemented, then handling `Run Keyword If` with `ELSE IF/ELSE` and `Run Keywords` with `AND` should also be taken into account. Tidy used to handle them separately (#1272), but now when original line continuations are preserved we decided it's better not to change line splitting at all. Making this functionality configurable would be nice. Not sure is it best to do that automatically if a maximum line length is given or should we instead have a separate option for that.

**Comment by fabo-at-noona** [comment]
@pekkaklarck yes, still interested. I'll have a look at the new code that landed on master.

**Comment by pekkaklarck** [comment]
Great! Tidy code is currently totally broken at the moment but hopefully it will be fixed soon.

**Comment by MrMino** [comment]
@fabo-at-noona @pekkaklarck any updates?

I'm willing to take a look on this too, I've just implemented a line-length check in a repository with over 1.5k tests, and the angry mob is honing the pitchforks while conspicuously gaping in my general direction.

**Comment by pekkaklarck** [comment]
Great that you are interested to help @MrMino! Instead of enhancing the built-in Tidy tool, it might be better to concentrate on the new [external Tidy](https://github.com/MarketSquare/robotframework-tidy) that is going to replace it. I'm sure @bhirsz and others would appreciate contributions!

**Comment by bhirsz** [comment]
@MrMino 
Feel free to reach us in the slack channel https://join.slack.com/share/zt-l1373k02-5IRDCzkYUKPSr4lV7YjJsQ

You might be also interested in our other tool (since you mentioned automated source code checks): https://github.com/MarketSquare/robotframework-robocop

I should finish most important tasks for core features of new tidy in this week and we will be able to focus on code transformers - and every help is very apreciated :)

**Comment by pekkaklarck** [comment]
The new Tidy has robotframework-tidy#14 that covers this issue. I don't think it makes sense to enhance the old Tidy related to this (or in general) anymore.
