### ISSUE TITLE
Log messages are unsorted by timestamp

### ISSUE THREAD

**Issue by serj1408** [robotframework/robotframework#1893]
Preconditions:
     I have a code
           _print_message('Wait until removed path: {0}, timeout: {1}'.format(file_path, timeout))
           OperatingSystem().wait_until_removed(file_path, timeout)
or 
        _print_message('Wait until created reference path: {0}, timeout: {1}'.format(file_path, timeout))
        OperatingSystem().wait_until_created(file_path, timeout)

def _print_message(body, level='DEBUG'):
    mes = '*' + level + ':%d* ' % (time.time() * 1000)
    print mes + body

Expected result:
    All log messages should be sorted by timestamp
Actual result:
    Messages are unsorted by timestamp

Log's fragment:
![message_wrong_place_timing](https://cloud.githubusercontent.com/assets/8637864/5708839/72666066-9a49-11e4-90c4-8df0d48dca13.PNG)

**Comment by pekkaklarck** [comment]
This happens because OperatingSystem uses `robot.api.logger` [programmatic logging API](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#programmatic-logging-apis) and your library logs messages using `print`. The former messages are logged (and written to outout.xml) already when the logger is called, but former only after the whole keyword is executed.

Because some of the messages are already written to disk, sorting them isn't possible without bigger changes to the logging system. Sorting wouldn't really make sense either, because timestamps of the printed messages are got only after the keyword finishes and thus they are generally wrong. A much simpler solution is you changing your library to use the programmatic logging APIs too.

**Comment by serj1408** [comment]
I got it..thanks
