### ISSUE TITLE
Move `Create Dictionary` to BuiltIn and enhance to preserver order etc.

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#1913]
RF 2.9 will have new dictionary variable type (#1450) making dictionaries much more useful and thus also most likely much more used in RF test data. It thus makes sense to move `Create Dictionary` keyword from Collections to BuiltIn to have it always available. Notice that we already have `Create List` in BuiltIn.

`Create Dictionary` should also be enhanced to allow creating dictionaries similarly as `&{dicts}` are created in variable table. This includes:

- Making returned dictionary dot-accessible (e.g. `${dict.key}`).
- Making returned dictionary ordered.
- Preserving order of given items.
- Allow non-strings in keys when using `key=value` syntax.

The last two points mean that we cannot use `**kwargs` in signature because they are not ordered and cannot contain non-string keys. Accepting just `*items` in format `key=value` and parsing them using same logic (and same code) that parses variable table values ought to be easy, though. After that we probably should deprecate the currently supported functionality to give keys and values separately like `| Create Dictionary | key1 | value1 | key2 | value 2 |`.

This change is not fully backwards compatible, but we don't expect these issues to consider too much problems:

- Using the keyword like `Collections.Create Dictionary` won't work anymore. Just dropping the library name ought to be enough as a fix.
- Returned dictionary won't be "normal" Python `dict` but its subclass. Shouldn't matter in real life, but we can add keyword like `Create Normal Dictionary` to Collections if needed.
- Giving keys and values separately will be depracated. Using `key=value` syntax works (except for non-string keys) already in RF 2.8, so this shouldn't be a problem. If giving keys and values separately turns out to be an actually useful feature, we can consider keeping it and removing deprecation.

**Comment by boakley** [comment]
We use dictionaries a lot on our team. We have created a variable file that lets us initialize dictionaries from YAML files. My testers love this. For example, I can define the variable ${LoginPage.user_details.username} with this yaml file: 

    # LoginPage.yaml
    user_details:
      username: id=usernameField
      password: id=passwordField

Right now we load this up as a variable file like this:

    *** Settings ***
    | Variables | YamlVariables.py | LoginPage.yaml

I would love for the yaml file to be a first class object in robot so that I could do this:

    *** Settings ***
    | Variables | LoginPage.yaml

Would you be interested in supporting this in robot since you're already improving dictionary support? It's a pretty simple block of code, about 70 lines long (not counting documentation). That includes both the yaml loader plus a dict subclass that supports the dot notion. 

If I made a pull requestion, would you consider adding this to robot? I will gladly provide the code, and could make an attempt at some acceptance tests and documentation, too.

**Comment by boakley** [comment]
I would hate to lose the ability to give keys and values separately. I find it makes code easier to read and write when creating dictionaries with more than one or two values

    | | ${foo}= | create dictionary 
    | | ... | one   | 1 
    | | ... | two   | 2
    | | ... | three | 3
    ...

**Comment by pekkaklarck** [comment]
@boakley, could you submit a separate issue about yaml variable files? Sounds pretty good on the first thought.

Do others also prefer giving dict keys and values separately like `key | value` and not like `key=value`? The latter is same syntax as when creating dict vars in the variable table, but keeping also the former isn't a problem if it is found useful.

**Comment by boakley** [comment]
@pekkaklarck : done. https://github.com/robotframework/robotframework/issues/1965

**Comment by aaltat** [comment]
I like ```key=value``` better than the ```key | value```, specially when creating dictionaries in test data, because it makes it more easier to read and understand which is the key and where is the value.
