### ISSUE TITLE
Java dependencies cannot be passed to Libdoc using `--pythonpath (-P)` option

### ISSUE THREAD

**Issue by diakula** [robotframework/robotframework#1933]
I tried on the command line with `java -jar robot.jar libdoc file.java file.html`, where the Java file depends on some Java classes from a `dependency.jar`. 

I could only get it to work when supplying -Xbootclasspath/a:tools.jar:dependency.jar, the -P did not work for Java dependencies. For the tools.jar, I understand. 

Can we perhaps make the -P also work for Java class path, when passing the control to `javadoc`? Or will it be cleaner to add a new parameters -C?

Btw, the Maven plugin does not work either - passing dependencies to the plugin seems ignored.

**Comment by pekkaklarck** [comment]
I thought -P would work also with jar files. Could you check does that work when running tests?

**Comment by diakula** [comment]
Ok, I tested a bit more. `libdoc` worked fine with `tools.jar` in `-P path/tools.jar`. However, the custom jar where I have dependency still does not work with `-P`. It only works in bootclasspath. This hints to properly using `-P` for finding where to run javadoc, but then not using it to pass javadoc any dependencies. So, `libdoc` not usable for Java with dependencies in 3rd parties (except for the horrendous boothclasspath workaround).

**Comment by pekkaklarck** [comment]
Did you try running tests with your dependencies set using `-P`? In other words, is this only a Libdoc issue or a general problem with `-P'?

**Comment by diakula** [comment]
`-P` seems to work for 'run', I could execute my tests passing .jars. This hints to a `libdoc` deficiency, particularly that it does not delegate `-P` classpath entries to `javadoc` properly.

**Comment by pekkaklarck** [comment]
The difference how `-P` is handled when running tests and when using Libdoc is most likely due to the former actually executing code and the latter using the [Javadoc API](http://docs.oracle.com/javase/7/docs/jdk/api/javadoc/doclet/). When `-P` is used, values are added to Python's `sys.path` in both cases, but apparently that is not enough in the latter case.

Do you have a simple example to reproduce the problem that you could share? I could try to reproduce the problem myself and see is there a simple fix available. Even better if you are interested to investigate this yourself.

**Comment by diakula** [comment]
The example:
# Part I
Define a simple module class:
```
package hellomodule;
public class HelloSayer {
	public void sayHello() {
		System.out.println("Hello!");
	}
}
```
Compile and jar it with the package path into `hellomodule.jar`.

# Part II
Define a simple library class:
```
package hellotests;
import hellomodule.HelloSayer;
public class HelloLibrary {
	public void sayHello() {
		HelloSayer hs = new HelloSayer();
		hs.sayHello();
	}
}
```
# Part III
Observe that this produces proper html:
`java -Xbootclasspath/a:tools.jar;hellomodule.jar -jar robotframework-2.8.7.jar libdoc HelloLibrary.java HelloLibrary.html`

Observe that this does *not* produce proper html:
`java -Xbootclasspath/a:tools.jar -jar robotframework-2.8.7.jar libdoc -P hellomodule.jar HelloLibrary.java HelloLibrary.html`

**Comment by pekkaklarck** [comment]
I don't have time to test this right now. Could you elaborate how results are broken when using `-P hellomodulejar`? Was it so that `-P tools.jar` worked fine?

**Comment by diakula** [comment]
When the error appears, I get a partial html file - I see the table with the keyword, but missing Javadoc, which probably means an interrupted execution via exception.
I look briefly at the python files and what I understood with my limited knowledge, I see a 2 phase approach: 1) the instantiation of a compiler, 2) the invocation of the Javadoc compiler. I see that the `tools.jar` provides the compiler, so phase 1 sees the `-P` elements properly. If missing, we get a specific message of the missing compiler dependency `tools.jar`. When the code executes the Javadoc compiler in phase 2 however, somehow the code does not deliver the additional jars from `-P` declaration. Unfortunately I don't see how to easily patch this, as I don't have time for the learning curve of quality Python coding.
We are not in a big hurry with this, so I can wait for a fix.

**Comment by pekkaklarck** [comment]
This is clearly a bug, no need to close. I'll take a look at this when I have time.

**Comment by pekkaklarck** [comment]
It seems Javadoc wants dependencies to be in classpath. It's annoying you cannot use `CLASSPATH` environment variable or `-cp` option with `-jar`, but using `-Xbootclasspath/a:` is nevertheless a good workaround. Because a workaround exists, I'm not going to debug this more. If someone else is interested and there's a way to enhance Robot/Libdoc to make `--pythonpath` work, I'm more than happy to review PRs.
