### ISSUE TITLE
Neither the parent suite Setup nor the parent suite TearDown were executed when giving the files with the test cases through command line

### ISSUE THREAD

**Issue by carlosadsuara** [robotframework/robotframework#1942]
Neither the parent suite Setup nor the parent suite TearDown were executed when giving the files with the test cases through command line.

We are looking for way to change the execution order of the test cases easily in each test run, including the execution of the parent test suite Setup/TearDown.

It seems to me that the possibilities that offers robot on 2.8.1 (our production
version) or 2.8.7 (last available version at the time of writing this issue) does
*NOT* allow a solution for our needs.

* We tried using tags (with '--include') and the whole 'data_source', but this option
  executes the test in alphabetical order (as specified)

* We tried using the option '--test' and the whole 'data_source', but this seems to
  ignore the order of the arguments and the test are executed alphabetically too.

* We tried using a subset of all the data sources restricted by suite, but this
  does not execute the Setup/Teardown of any high level suite.

* Are we missing something?

**Comment by carlosadsuara** [comment]
Explanation of our needs (and implementation of our test framework):

Lets suppose that a product has several components and that each TestSuite contains
the test cases for certain component, as seen below:

```
tests/
`-- ComponentTestSuite
    |-- __init__.txt            <- Contains SetupComponentTestSuite and TeardownComponentTestSuite
    |-- TestSuite1.txt          <- Contains SetupTestSuite1 and TeardownTestSuite1 / TestSuite for Component1
    |   |-- TestCase1-1
    |   `-- TestCase1-2
    |-- TestSuite2.txt          <- Contains SetupTestSuite2 and TeardownTestSuite2 / TestSuite for Component2
    |   |-- TestCase2-1
    |   `-- TestCase2-2
    `-- TestSuite3              
        |-- __init__.txt        <- Contains SetupTestSuite3 and TeardownTestSuite3 / TestSuite for Component3
        |-- TestSuite3-A.txt
        |   |-- TestCase3-A-1
        |   `-- TestCase3-A-2
        `-- TestSuite3-B.txt
            |-- TestCase3-B-1
            `-- TestCase3-B-2
```
* SetupComponentTestSuite is something **VERY COSTLY** that I need to do *BEFORE*
  executing any test case of this _component_ suite (ie, start some machines)
* TeardownComponentTestSuite is something **VERY COSTLY** that I need to do *AFTER*
  executing any test case of this _globlal_ suite (ie, shutdown some machines)
* SetupTestSuite1 is something **COSTLY** that I need to do *BEFORE* executing any 
  test case of this suite (ie, install some server 1)
* TeardownTestSuite1 is something **COSTLY** that I need to do *AFTER* executing any
  test case of this suite (ie, uninstall some server 1)
* And so on ...

In our integration process, we want that a test run will be triggered by a change
in *certain* component. Hence I would like to run **FIRST** the test cases related
with that component in order to rapidly detect any possible regression and revert
that particular change. (Using --exitonfailure).

For instance, a change in *Component2* will trigger a run where *TestSuite2* shall
be executed first. I still want to run Testsuite1 and TestSuite3 (order not relevant).
The solution shall cover the possibility of running also the test cases in different
order. This is due to that fact that some changes are known to affect only certain
parts that are covered by a single test case, so I want to execute first that one.

With the previous structure, if I try 
```
pybot --name Regression --TimeStampOutputs --ExitOnFailure tests/sandbox/TestSuite3/TestSuite3-A.txt tests/sandbox/TestSuite1.txt
```
It does *NOT* execute the SetupComponentTestSuite nor TeardownComponentTestSuite

**Comment by laurentbristiel** [comment]
1) About your setup/teardown issue when you run a nested suite/test.

If you use this syntax:
```
pybot --name Regression --TimeStampOutputs --ExitOnFailure tests/sandbox/TestSuite3/TestSuite3-A.txt tests/sandbox/TestSuite1.txt
```
Robot Framework will indeed just execute TestSuite1.txt and it does not have a way to know that there are upper level suite setup/teardown to execute. Robot could try to look for those but how would he know up where to go.

So, in order to target a given test/suite and execute all the layers of setup/teardown from a given root, you have to use the --suite argument. User Guide section [Selecting tes cases by test suite and test case names](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#by-test-suite-and-test-case-names) explains: "Using the --suite option is more or less the same as executing only the appropriate test case file or directory. One major benefit is the possibility to select the suite based on its parent suite. The syntax for this is specifying both the parent and child suite names separated with a dot. In this case, the possible setup and teardown of the parent suite are executed."

Hence, to run only TestSuite3-A your syntax should be:
```
pybot --name Regression --TimeStampOutputs --ExitOnFailure --suite tests.sandbox.TestSuite3 --test TestSuite3-A  tests
```
or
```
pybot --name Regression --TimeStampOutputs --ExitOnFailure --test tests.sandbox.TestSuite3.TestSuite3-A  tests
```

2) About the execution order, you can not specify custom execution order with Robot. It is either alphabetical order or randomized (with option to filter with --test and --suite). If you want to run first a given test and then the whole portfolio, then you would have to script that I guess. Maybe using Jenkins you could have a "targeted smoke test" jobs that launched a shell script that launch a given test depending on what changed in the source, and another job (triggered by success of smoke test) that launched the whole portfolio.

**Comment by carlosadsuara** [comment]
Thanks for you notes and suggestions laurentbristiel.

I just want to confirm what I found and know if there is any plan for a change that will support test execution order. I omit the example that you suggest in 1) because it does not meet our requirement of changing test case order
```
pybot --name Regression --test TestCase3-A-1 --test TestCase1-1 --TimeStampOutputs --ExitOnFailure tests/
```

As explained above, we are looking to execute some "targeted smoke tests" and the major part of our portfolio together because of the overhead in the setup. We try to perform the test in the most possible environment, so as part of the setup our test case prototypes are reset, the new software is installed and much more.

If it is completely impossible to select the execution order, probably we should re-think our approach of using directly robot for that matter and may be implement the intelligence in Jenkins and change the setup procedure.

**Comment by laurentbristiel** [comment]
As far as I know, it is not possible to select the execution order like you would like to do. So yes, I would implement the intelligence in Jenkins.

**Comment by pekkaklarck** [comment]
Laurent is absolutely right both about setups/teardowns and execution order. Having a way to configure the execution order would be nice, but nobody has been able to come up with a good way to do it. If you have ideas, please submit a new issue about that.
