### ISSUE TITLE
New syntax: FOR ... IN ENUMERATE

### ISSUE THREAD

**Issue by edbrannin** [robotframework/robotframework#1954]
Suggested in the comments on #1952

It would be nice if Robot could use Python's `enumerate()` in for loops.

**Comment by edbrannin** [comment]
About how long to I have to make a PR for this to get it considered for 2.9a2?

**Comment by pekkaklarck** [comment]
Could you please elaborate the question?

**Comment by edbrannin** [comment]
I meant: Obviously sooner is better, but I'm curious how soon I'd have to complete any pull-requests that make it into the next 2.9 alpha release.

**Comment by pekkaklarck** [comment]
We don't have any hard deadline for alpha 2. Basically we'll create a release when all issues with alpha 2 label have been closed or postponed. I hope that would happen already this month because we'd like to get the final release ready in June. Missing alpha 2 shouldn't be a huge problem, though, because we'll continue with alpha 2 or beta 1 right after it.

**Comment by pekkaklarck** [comment]
Now that PR #1989 is implementing also `FOR ... IN ENUMERATE`, should we merge this issue with #1952?

**Comment by pekkaklarck** [comment]
Changed #1952 to cover both ZIP and ENUMERATE flavors. This can now be closed as its duplicate.
