### ISSUE TITLE
rebot should use file timestamps for ordering

### ISSUE THREAD

**Issue by boakley** [robotframework/robotframework#1963]
I discovered today that merging results with rebot is dependent on the order of the input files on the command line. The documentation doesn't seem very clear on this point. If I run a test twice, I get different results depending on which order I provide the files to rebot.

It would be nice if rebot could look at the testcase timestamp when merging, so that it always starts with the earliest test and then merging in the later test. That way I could run a bunch of times and then do something like "rebot --merge *.xml", and the expected thing would happen.

**Comment by pekkaklarck** [comment]
First of all, do you mean file timestamps as returned by the operating system or some specific timestamp inside output.xml?

Regardless the timestamp, I don't think we can change the current behavior simply because the change would be backwards incompatible. Adding a separate command line option to change the behavior could be considered. Are you interested to implement it?

**Comment by boakley** [comment]
I initially had file timestamps in my head, but then I realized that each
testcase has a timestamp. I think the latter might make more sense.

I won't implement it until I know there's a chance it might be accepted.
Even then, I don't know if I have the time or not. Maybe, since I'm working
on trying to combine a bunch of results now and this might help me out.

**Comment by pekkaklarck** [comment]
Please explain how you think this would work in practice, including what the command line option should be. If it looks good, we can give you green light based on that.

**Comment by pekkaklarck** [comment]
Have you @boakley been thinking how this would work in practice?

**Comment by boakley** [comment]
No, I haven't. I think how it would work would be pretty straight-forward. Personally I think the default should be to use the timestamps of the test rather than the order on the command line. If you're worried about backward compatibility in case someone depends on the old behavior, something like 'rebot --usetimestamps' or "--mergeorder timestamps" might be good enough.

**Comment by pekkaklarck** [comment]
1. I highly disagree that timestamps should override the order. If I say `rebot out1.xml out2.xml`, I definitely want to have them in that order regardless that timestamps those files have.

2. A problem with using suite/test timestamps is that you might be combining already combined outputs where the top-level suite by default has no timestamp and timestamps of combined suites can be arbitrary. One suite could be executed today, another last month. This is one more reason this behavior should not be the default.

3. The newly added `--prerebotmodifier` functionality makes it easy to programmatically modify results before generating logs an reports. Creating a custom modifier that sorts suites based on timestamps would be pretty easy.

4. I don't have anything against adding an option to sort outputs by timestamps but I consider it very low priority enhancement. Unless you are interest to work with it in the near future, I'll close this issue for now. It can be reopened if you or someone else needs it badly enough to actually implement it.

**Comment by tarand** [comment]
"Regardless the timestamp, I don't think we can change the current behavior simply because the change would be backwards incompatible"
Please note that the current behavior is already a change in behavior. Were are currently migrating from Robot 2.5.7 to Robot 2.8.6. We are used to run the component's tests calling robot several times, each of them resulting in an *output.xml file. After that we call rebot <more args> *output.xml.
With Robot 2.5.7, the final log-html file was ordered reflecting the test execution order - what certainly is expected usually (and is the complain of boakley).
Now (Robot 2.8.6) uses a random order (which is obviously the order in which the OS resolves *output.xml). This makes the log hard to read.

**Comment by pekkaklarck** [comment]
@tarand, I don't remember Rebot ever sorting outputs based on execution order. I also tested that at least on my Linux machine I get same sorting both with RF 2.5.7 as with the latest code.

**Comment by pekkaklarck** [comment]
We cannot change the default sort order and nobody seems to be interested to implement a way to customize the order. Closing.
