### ISSUE TITLE
The name argument in listener interface is not always the same

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#1967]
Ugh

On the _start_keyword and _end_keyword methods, the name argument is not same in all scenarios. 

If suite looks like this: 
```
*** Setting ***
Library          MyListener.py

*** Test Cases ***
Example
    Log    1234
    My Keyword
    ${arg}=    Keyword With Return Value

*** Keyword ***
My Keyword
    Log    0123

Keyword With Return Value
    Log    0123
    [Return]    0123
```
Then the name argument contains this: ```My Keyword``` and ```${arg} = Keyword With Return Value```

But if my test suite and resource files look like this: 
```
*** Setting ***
Resource         resource/resource.robot
Library          MyListener.py

*** Test Cases ***
Example
    Log    1234
    My Keyword
    ${arg}=    Keyword With Return Value
```
```
*** Keyword ***
My Keyword
    Log    0123

Keyword With Return Value
    Log    0123
    [Return]    0123
```
Then the name argument contains this: ```resource.My Keyword``` and ```${arg} = resource.Keyword With Return Value```

I did expect the name argument to always contain the library/resource/test suite name. This also demonstrates the bug reported #1951 and #1611 but because it is already reported, I just hope that it gets fixed.

**Comment by pekkaklarck** [comment]
I'm not sure did I understand this correctly. Could you please clarify? What did you expect to and what did you get?

**Comment by aaltat** [comment]
My listener looks like this:
```
from robot.api import logger

class MyLibrary(object):

ROBOT_LISTENER_API_VERSION = 2
    ROBOT_LIBRARY_SCOPE = "GLOBAL"

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self
    
    def _end_keyword(self, name, attrs):
        logger.info(name)
....
```
When my test data looks like this:
```
*** Setting ***
Resource         resource/resource.robot
Library          MyListener.py

*** Test Cases ***
Example
    My Keyword
```

```
*** Keyword ***
My Keyword
    Log    0123
```
Then on the _start_keyword and _end_keyword methods, the name argument contains this: ```resource.My Keyword```.

If my test data looks like this: 
```
*** Setting ***
Library          MyListener.py

*** Test Cases ***
Example
    My Keyword

*** Keyword ***
My Keyword
    Log    0123
```
Then on the _start_keyword and _end_keyword methods, the name argument contains this: ```My Keyword```. But I did expect it to contain ```suite.My Keyword```

The name argument is not prefixed with the name of suite, when the keywords are coming from the test suite keyword table. Because in all other cases name argument is prefixed with the library/resource name, this is a deviation from all other cases.

**Comment by pekkaklarck** [comment]
This is actually the expected and designed behavior. Names you get to listeners are exactly same name you see in log file. With keywords in a resource or a library this name consists of the resource/library name and actual keyword name, and with keywords in a test case file it is just the keyword name. I don't think it is a good idea to change this so that the suite name would be included. If you are interested in the suite name, you can get it to `start_suite` method along with the suite source.

Notice that we are planning to change keyword names so that library/resource name and keyword name would be separate (#1743). Need to consider what information is passed to listeners after that change. I'll add a comment to #1743 about that.
