### ISSUE TITLE
User Guide: Switch examples to use plain text format instead of HTML format

### ISSUE THREAD

**Issue by laurentbristiel** [robotframework/robotframework#1972]
Shouldn't we switch code samples in the User Guide from HTML format to Plain text format? I have the feeling that more and more people are using Plain Text Format (version control friendly, and today who is not using VC?) and basically the community is not pushing for HTML format as far as I can see. So User Guide should adapt and use syntax that people really use.

Not only the reader would have an easier time comparing his code and the guide, but in addition he could copy/paste from the guide more easily (and today, who is not copy/pasting ;-)

Final note: we would have to choose between pipe and space separated (and I know they are partisans of both). Could be a good opportunity to troll.

What do you people think of that?

**Comment by pekkaklarck** [comment]
Yes, this would be a good idea. Main reason it hasn't been done is that it's quite a big task. Perhaps it could be at least partly automated using Tidy.

In my opinion we should use space separated format because it is more widely used than pipe separated.

**Comment by laurentbristiel** [comment]
I can give it a try.
Would it be something [like that](https://github.com/laurentbristiel/robotframework/commit/1bd88b6abd4b6b6a40fc5d6abf8afb24367236aa)?
couple of questions:
- shall I use 4 spaces between keywords and arguments?
- do you see anything else special I should be aware of?

**Comment by pekkaklarck** [comment]
Yes, four spaces between keywords and arguments, and also between settings and values in the test case and keyword tables. In the setting and variable tables and with data-driven tests values should probably be aligned.

The formatting produced by Tidy is typically pretty good. Creating a script that converts format using Tidy might be a good idea. Examples should still be manually reviewed to fix possible changes to escaping, handling `...`, and so on.

**Comment by pekkaklarck** [comment]
I also prefer using an explicit `=` when assigning a variable and having a space between it and the variable like `${var} =    Keyword`.

Now that we are discussing about style here, should we actually list recommendations explicitly somewhere similarly as PEP-8 does for Python code? Should it be a separate document in the project root, appendix to the User Guide, a wiki page, or part of contribution guidelines (#1805)?

**Comment by guykisel** [comment]
You could develop a recommended style guide as a document similar to an RFC or PEP - an RFEP? 

Since it would probably be a pretty general purpose document, I don't think it belongs in the contribution guidelines, which are specific to contributing to this repo (unless you only want to describe style specifically for this repo, in which case the contribution guidelines do seem like a good place).

**Comment by laurentbristiel** [comment]
I started to work on that issue. Thought it would be nice to have it done for 2.9 release.
Couple of questions arose in the process:

1) should we change the terminology used in many places when describing test cases: tables (test case table, keyword table etc.), column, row, and cell. I felt like changing "table" by "section" or "block", but then I could not find right terms for the 3 other words, so I did not change anything yet. Thoughts?

2) dictionary variable are not formatted properly because they are brand new. Has anyone started to update [pygments](https://bitbucket.org/birkenfeld/pygments-main) library to handle this new variable type?

3) do we still need some test cases screenshot in the [screenshot section](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#screenshots). I was about to change those HTML test cases by TXT one, but screenshoting TXT does not seem relevant.

**Comment by pekkaklarck** [comment]
Yes, it would be awesome to get this into RF 2.9. Answers to your questions below.

1. I agree talking about tables in the plain text format is a bit weird, and also that coming up with good alternative terminology is hard. Tables could be called sections, rows could be lines (or rows), but I don't know what to call a cell. This definitely shouldn't block updating example format, though.

2. Nope, haven't yet added support for dictionary variables to Pygments. I don't remember how strict it is, but it is possible that new keyword `[Tags]` won't be handled correctly either. This is definitely something that should be done ASAP. It would be good first to upgrade the [separate lexer](https://bitbucket.org/robotframework/pygmentslexer/wiki/Home), then merge those changes to Pygments itself.

3. The Screenshot section can be changed to Examples. I'm not certain is the whole section needed now that we have http://robotframework.org/#examples. What do you think, should we just remove it altogether?

**Comment by laurentbristiel** [comment]
Some news about this issue
a) I proposed a PL for the test case format (see #2035)
b) I worked on support for dictionary variables to Pygments (see [pull request](https://bitbucket.org/birkenfeld/pygments-main/pull-request/480/robot-framework-lexer-handle-new/diff))

**Comment by pekkaklarck** [comment]
Thanks @laurentbristiel for creating a PR for Pygments! Did you tests how it handles keyword `[Tags]`?

**Comment by laurentbristiel** [comment]
I did not test the [Tags] in Keywords because I saw that it was not (yet) used in our code sample in the User Guide (ok, and because I was lazy!). I gave it another look and it was indeed not working. So I included the fix in the PL.

I would like to work on the terminology now (tables, rows, cells etc.). Could you check/merge the first PL so that I can re-start from the new merged version for my new set of modifications?

**Comment by pekkaklarck** [comment]
Thanks for your lexer PRs! As you may have noticed, I merged the one you did for the separate project and already created a new release out of it. I'm not entirely sure will Pygments use that version or the version built-in, though. Let us know how you get User Guide compiled with the new lexer so that we can use the same approach when generating new releases.

Unfortunately I don't have time to review the PR today. I hope I have other things done so that I could do it tomorrow but I cannot make promises. This thus won't make it to the first beta, but I definitely want to get this into the final 2.9 release.

What do you want to talk about terminology? I would be happy with this issue (and especially the PR) to cover just updating the example format.

**Comment by boakley** [comment]
Pekka wrote _"In my opinion we should use space separated format because it is more widely used than pipe separated."_

Just to add another perspective (even though it may be too late), I think the pipe-separated format is superior for documentation and examples. It can be hard to see whitespace, even when it's four spaces. Using the pipe format makes the division between cells crystal clear. Above all, I think the #1 goal for documentation should be clarity. 

Though, to make really steller documentation, both could be supported. There's a site for tkinter documentation (tkdocs.com) that solved this problem nicely -- it shows examples in tcl, python, perl and ruby, and the user can pick the format they want to see. It makes for really nice documentation.

**Comment by laurentbristiel** [comment]
@boakley ah! I was surprised to not see you chime in this issue :-) I will tell you the main reason why pipe separated format is not appropriate for me: it is hell to type it on my [Mac french keyboard](https://support.apple.com/library/content/dam/edam/applecare/images/en_US/keyboards/french_notebook.png)! I know I could map it to another keyboard or use an IDE that type pipe easily though..

@pekkaklarck 
"Let us know how you get User Guide compiled with the new lexer"
I just installed the new version on my laptop (`python setup.py install`) and then compiled the doc (`python ug2html.py cr`)

"What do you want to talk about terminology"
See your former message: "I agree talking about tables in the plain text format is a bit weird, and also that coming up with good alternative terminology is hard. Tables could be called sections, rows could be lines (or rows), but I don't know what to call a cell. This definitely shouldn't block updating example format, though." => I can raise a separate issue for this specific work.

**Comment by boakley** [comment]
>
> re: "What do you want to talk about terminology"
> See your former message: "I agree talking about tables in the plain text
> format is a bit weird, and also that coming up with good alternative
> terminology is hard. Tables could be called sections, rows could be lines
> (or rows), but I don't know what to call a cell. This definitely shouldn't
> block updating example format, though." => I can raise a separate issue for
> this specific work.


FWIW, in my own parser I call a single cell a Cell, a single physical line
a Row, and one or more rows where all but the first has a continuation as a
Statement. Each major section I call a Table (eg: the settings table, the
test case table, etc). I also use the abstraction of a "Robot File" to
represent a file that could be either a resource file or a suite, since the
only syntactic difference is the absence or presence of a test case table.

This terminology has worked well for me.

**Comment by pekkaklarck** [comment]
PR #2035 has been merged, new plain text examples cleaned up and some problems fixed in 647040372b924cc843a265513e534de8e3a36fd7, and examples added after the PR converted in 7ef3f4805e1c253c592d818117457958f4a5d2e2. I consider this issue done.

Thanks again for the PR @laurentbristiel. It would be great if you could still review my changes. If you want to change the terminology related to tables, rows, etc., we can do that in the future releases. Also, I hope you don't mind me adding you to AUTHORS.

**Comment by laurentbristiel** [comment]
Thanks for all that work @pekkaklarck! I will review your changes and give feedback if relevant. I will see if another issue for terminology is still needed while re-reading the sections I thought were not fitting great with the plain text examples.

And thanks for adding me to the authors list!
