### ISSUE TITLE
How can i  hide the log 

### ISSUE THREAD

**Issue by henrysos** [robotframework/robotframework#1978]
hi
i think the log is too much ,how can i hide the result log, and the log include only what i want 
ex: i want to hide below log
KEYWORD: @{allresult} = BuiltIn.Getallresult ${casecode}, ${caseid} Expand All
KEYWORD: ${scheme} = BuiltIn.Set Variable @{allresult}[0] Expand All
KEYWORD: ${host} = BuiltIn.Set Variable @{allresult}[1] Expand All
KEYWORD: ${path} = BuiltIn.Set Variable @{allresult}[2] Expand All
KEYWORD: ${casemethod} = BuiltIn.Set Variable @{allresult}[3] Expand All ¶
KEYWORD: ${paralist} = BuiltIn.Set Variable @{allresult}[4] Expand All
KEYWORD: @{resultparalist} = BuiltIn.Set Variable @{allresult}[5] Expand All
KEYWORD: @{resultvaluelist} = BuiltIn.Set Variable @{allresult}[6] Expand All
KEYWORD: ${rescount} = BuiltIn.Set Variable @{allresult}[7] Expand All
KEYWORD: ${postvalue} = BuiltIn.Set Variable @{allresult}[9] Expand All
KEYWORD: ${role} = BuiltIn.Set Variable @{allresult}[10] Expand All
KEYWORD: ${referer} = BuiltIn.Set Variable @{allresult}[11] Expand All
KEYWORD: ${cookies} = BuiltIn.Set Variable @{allresult}[12]

thanks a lot

**Comment by laurentbristiel** [comment]
Hi,

for questions about the product, please use the [Robot Framework Mailing List](https://groups.google.com/forum/#!forum/robotframework-users) rather than the Issues of GitHub.

Now for your question, all the answers are in the User Guide. Check the ["Created Output" section](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#created-outputs) and maybe give a special look to the ["Removing and flattening keywords" section](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#removing-and-flattening-keywords) where you will see how can you can remove the "Set Variable" (for example) that you don't want to see in the log.

**Comment by henrysos** [comment]
thanks
