### ISSUE TITLE
Add robot framework backslash switch keyword. ( To use backslash in 'path' and 'regex' naturally )

### ISSUE THREAD

**Issue by MoonSungHoon** [robotframework/robotframework#1984]
I know that robot framework have a rule to use backslash as a documentation.

"""
Because the backslash character is an escape character in reST, specifying a backslash so that Robot Framework will see it requires escaping it with an other backslash like \\. For example, a new line character must be written like \\n. Because the backslash is used for escaping also in Robot Framework data, specifying a literal backslash when using reST tables requires double escaping like c:\\\\temp.
"""

Totally understand the above problem but I think it is too weird using backslash twice in 'path' and 'regex'.
So I suggest three ways to resolve this problem.
First, make a global keyword to switch robot framework like
```
"Robotfrmaework escape | off
```
Second, give hidden parameter globally(or not) like
```
Any keyword | Any params | robot_escape=on
```
Last, make a new keyword to make changed string to satisfy above rule automatically like
```
${encoded_string}= | Encode Escape String | string
```

I don't know what is the best way, but it is needed because I think readability of test case is very important. If there are more good solution, please let me know about this problem.

Thank you.

**Comment by pekkaklarck** [comment]
I do understand that using backslashes in test data is somewhat complicated because you need to double them Having a keyword or some other way to globally change how backslashes are handled would be problematic, though. The main problem would be that any usage of a keyword that uses backslashes normally would fail after changing backslash handling. The worst part would be that it would be very hard to understand why such a keyword fails if you don't know that backslash handling has been changed.

A better solution would be having a way to explicitly specify that backslashes are handled differently in a certain string. Python uses `r"raw strings"` and something similar could be considered also in Robot data. I just don't know what would be a suitable syntax in this context.

I close this issue because I don't think the original idea is feasible. If you think Robot's own "raw strings" would be a good idea, please submit a new issue about it.

**Comment by MoonSungHoon** [comment]
I understand what you mean. Robot's own "raw strings" would be a good solution. I'll think about that.
Thanks.
