### ISSUE TITLE
Display multi-line keyword documentation in log.html

### ISSUE THREAD

**Issue by bjornfor** [robotframework/robotframework#1994]
Some of my (user) keywords have multi-line [Documentation] fields. The resulting log.html file only shows the first line. It would be nice to see all lines.

I see that multi-line documentation is shown in full for test suite level documentation. So I guess this only affects (user) keywords.

**Comment by pekkaklarck** [comment]
The current behavior is by design. There are several reasons why only the first row of the documentation is included:

- Especially with library keywords, the documentation can be very long. Including full documentation of every keyword would increase the size of the output.xml and also log.html considerably.

- First row of the doc [should contain a summary](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings). The summary along with the keyword name ought to give enough information what the keyword does.

- The doc would often be distracting. We probably should have a way hide them somehow.

Due to the above reasons the default behavior won't change. I'm not entirely against having a way to somehow specify that a certain doc should be included fully. If you think it would be very important, please propose a way how to configure the behavior and we can discuss it further.

**Comment by bjornfor** [comment]
Thanks for the info. I wasn't aware that RobotFramework had the same policy to multi-line docstrings as Python.

You may consider closing the issue, as I don't have immediate plans to start working on this myself. (I should probably work on my own docstrings instead ;-))
