### ISSUE TITLE
DateTime library does not support dates in distant past (hard limit 1900, on Windows 1970)

### ISSUE THREAD

**Issue by jrkoiter** [robotframework/robotframework#1996]
The following:

`Convert Date  |  1901-01-01 | date_format=%Y-%m-%d`

results in "OverflowError: mktime argument out of range".

And this:

`Convert Date   | 1880-01-01 | date_format=%Y-%m-%d`

results in "ValueError: year out of range".

It works without error starting from year 1902, is seems. This for example works as expected:

`Convert Date  |  1902-01-01 | date_format=%Y-%m-%d`

**Comment by pekkaklarck** [comment]
I can reproduce the latter error but not the former on my environment. `Convert Date` uses [time.mktime](https://docs.python.org/2/library/time.html#time.mktime) internaly to first convert the given time to seconds, and its docs explain both why these errors occur and why we get different results:

> If the input value cannot be represented as a valid time, either OverflowError or ValueError will be raised (which depends on whether the invalid value is caught by Python or the underlying C libraries). The earliest date for which it can generate a time is platform-dependent.

It seems [calendar.timegm](https://docs.python.org/2/library/calendar.html#calendar.timegm) doesn't have same limitation as `time.mktime`. This would require also other changes to the code, though, because `time.mktime` expects local time but `calendar.timegm` expects UTC.

Would @jrkoiter or someone else be interested to investigate could the actual problem here be fixed using `calendar.timegm` or some other solution? If not, I probably will just document the current limitation.

**Comment by jrkoiter** [comment]
Interested yes, but unfortunately I'm short on time at the moment. Thanks for clearing it up, we'll live with it for now!

**Comment by pekkaklarck** [comment]
I wanted to add a note to the docs about this and for that wanted to test this a bit more thoroughly. My findings below.

On my Linux machine 1900 was still OK but 1899 failed with `ValueError: year out of range`. Apparently this limitation is by design to avoid [Y2K problems](https://docs.python.org/2/library/time.html#time-y2kissues). The docs mention that behavior could be changed by setting `time.accept2dyear` to 0, but in my testing that only changed the error to `ValueError: year >= 1900 required`. Anyway, dates older than 1900 aren't that often needed so this limitation wouldn't be too bad.

On my Windows virtual machine I get `OverflowError: mktime argument out of range` with all dates before the UNIX Epoch (1970-01-01 UTC). This is much worse than on Linux and definitely something that would be great to be fixed.

Unfortunately I don't have time to look at this more closely now, but I'll nevertheless re-open this issue and label it as a valid bug. I'll also add a note to DateTime docs about the limitation.

**Comment by pekkaklarck** [comment]
Storing dates internally as `datetime` objects instead of converting them epoch seconds using `time.mktime`, as discusses in #2018, seems to mostly fix this problem. Based on my prototypes dates since 1900-01-01 work fine regardless of the operating system and even older dates are supported when returning dates as `datetime` objects.
