### ISSUE TITLE
Checking is stdout/stderr stream terminal causes exception if stream's buffer is detached

### ISSUE THREAD

**Issue by userzimmermann** [robotframework/robotframework#2003]
If the `.buffer` of an `io` module based stream was detached, the `stream.isatty()` method called in `utils.misc.isatty()` will raise an exception. #1948 fixes it.

**Comment by pekkaklarck** [comment]
The problem can demonstrated like this on Python 2.7:

```python
>>> from io import TextIOWrapper, BytesIO
>>> stream = TextIOWrapper(BytesIO())
>>> stream.isatty()
False
>>> stream.detach()
<_io.BytesIO object at 0x7f4de4f4ba70>
>>> stream.isatty()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: underlying buffer has been detached
```

Actually using `io` based streams as stdout/stderr in Python 2 with Robot Framework doesn't seem to be possible. The reason is that these streams only accept Unicode or bytes and Robot's output contains both. This is worth fixing to ease porting to Python 3, though.

**Comment by pekkaklarck** [comment]
PR #1948 was merged. This issue is done.
