### ISSUE TITLE
DateTime: DST problems when calculating with dates

### ISSUE THREAD

**Issue by jrkoiter** [robotframework/robotframework#2018]
When adding days using Add Time To Date keyword, the result is not as expected if a DST boundary is crossed:

```
*** Settings ***
Library           DateTime

*** Test Cases ***

Adding Days That Cross DST Boundaries
    ${date}=                Convert Date            2015-10-25 00:00:00.000
    ${tomorrow}=            Add Time To Date        ${date}     1 days
    Should Be Equal         ${tomorrow}             2015-10-26 00:00:00.000
```

Output (CET timezone, robot v2.7.8):

```
==============================================================================
TC DATE TIME                                                                  
==============================================================================
Adding Days That Cross DST Boundaries                                 | FAIL |
2015-10-25 23:00:00.000 != 2015-10-26 00:00:00.000
------------------------------------------------------------------------------
TC DATE TIME                                                          | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

**Comment by pekkaklarck** [comment]
DST sucks!!

**Comment by pekkaklarck** [comment]
But I guess we need to live with DST....

This problem seems to caused by DateTime library storing dates as seconds since epoch internally and doing calculations using them. The problem can be demonstrated using Python's `datetime` module too:

```python
>>> from datetime import datetime, timedelta
>>> dt = datetime(2015, 10, 25)
>>> d = timedelta(days=1)
>>> dt + d
datetime.datetime(2015, 10, 26, 0, 0)
>>> from time import mktime
>>> secs = mktime(dt.timetuple()) + d.total_seconds()
>>> datetime.fromtimestamp(secs)
datetime.datetime(2015, 10, 25, 23, 0)
```

It ought to be easy to fix this by using `datetime` objects for calculation. Should consider also using them as the internal representation instead of seconds.

**Comment by pekkaklarck** [comment]
I guess this could even cause backwards incompatibility issues. Adding `bwic` label.

**Comment by pekkaklarck** [comment]
Same problem also with `Subtract Time From Date` and `Subtract Date From Date`.

**Comment by huuhtaneno** [comment]
When converting a date and time which is exactly the time of the DST switch in Europe/Helsinki. It automatically subtracts one hour and returns a different time.

Testing
    ${date}=    Convert Date    2015-03-29 03:00:00.000

${date} = DateTime . Convert Date 2015-03-29 03:00:00.000
Documentation:	
Converts between supported `date formats`.
Start / End / Elapsed:	20150903 09:17:44.264 / 20150903 09:17:44.269 / 00:00:00.005
09:17:44.265	TRACE	Arguments: [ '2015-03-29 03:00:00.000' ]	
09:17:44.268	TRACE	Return: b'2015-03-29 02:00:00.000'	
09:17:44.268	INFO	${date} = 2015-03-29 02:00:00.000

**Comment by pekkaklarck** [comment]
Which version did you use? The current behavior ought to be the same as with Python's `datetime` module in this regard but cannot verify it right now.

**Comment by huuhtaneno** [comment]
I used version 2.9.0.

**Comment by pekkaklarck** [comment]
This is pretty strange. On my Linux machine

    ${date} =    Convert Date    2015-03-29 03:00

returns `2015-03-29 04:00` which I think is OK. On the Windows virtual machine running on that Linux host the result is `2015-03-29 02:00` like you got. I don't know is that due to different OS, configuration, or Python. If you think this is important enough to be investigated further, please submit a separate issue.

Also, DTS sucks.

**Comment by huuhtaneno** [comment]
So it's an almighty Windows problem! How surprising. 

I guess it's not that important, I will leave it here.

And yes DST sucks and can't say much about Windows either.

**Comment by pekkaklarck** [comment]
I was able to reproduce the same problem using Python only. When I run

    python -c "import time, datetime; print time.mktime(datetime.datetime(2015, 3, 29, 3).timetuple())"

on Linux I get `1427590800.0` but on Windows I get `1427587200.0`. I'm not sure is it Windows to blame, though, because apparently `time.mktime` can be platform dependent related to timezones and DST:
http://stackoverflow.com/questions/2956886/python-calendar-timegm-vs-time-mktime

DateTime library uses `time.mktime` heavily because it converts all dates to seconds since epoch internally. It should, instead, store everything as `datetime` objects and only use `time.mktime` if someone wants the result as epoch seconds. I prototyped this and it seems to fix the problem and, as a big bonus, also mostly fixes #1996.

The problem @huuhtaneno reported is thus both fixable and worth fixing. Depending on how big changes actually are needed, it may need to wait for RF 3.0 instead of 2.9, though. Could you anyway submit a separate issue?

**Comment by pekkaklarck** [comment]
I submitted #2130 about the DST issues noticed and reported by @huuhtaneno.

**Comment by huuhtaneno** [comment]
Sorry, did not see your comment until now. Thanks for submitting the issue and fixing it already!
