### ISSUE TITLE
Do not write empty elements or attributes to output.xml

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2020]
Robot's output contains a lot of empty elements like `<doc></doc>` or `timeout=""`. The output size can be squashed a lot if we just don't write them. 

As a special case, all keywords have a type-attributes which is in most cases "kw". This can be a default value, so that if the attribute is omitted, the value is assumed to be "kw".

This is backwards incompatible for any tools that process robot's output.xml, but it should not be too difficult to make the necessary changes to support this new format.

**Comment by pekkaklarck** [comment]
It seems this change has broken Jenkins plugin (#2054), which indicates that the backwards incompatibility risk is real. We still think this change was a good idea simply because it reduced output.xml size up to 10% in our tests.

**Comment by simplyviks** [comment]
i still see this issue with RF 3.12 and jenkins robot plugin 1.6.5


`11:18:53  Failed!
11:18:53  java.io.IOException: Parsing of output xml failed!
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.setRobotResult(RobotParser.java:151)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:82)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.invoke(RobotParser.java:58)
11:18:53  	at hudson.FilePath$FileCallableWrapper.call(FilePath.java:3052)
11:18:53  	at hudson.remoting.UserRequest.perform(UserRequest.java:212)
11:18:53  	at hudson.remoting.UserRequest.perform(UserRequest.java:54)
11:18:53  	at hudson.remoting.Request$2.run(Request.java:369)
11:18:53  	at hudson.remoting.InterceptingExecutorService$1.call(InterceptingExecutorService.java:72)
11:18:53  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:18:53  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
11:18:53  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
11:18:53  	at java.lang.Thread.run(Thread.java:748)
11:18:53  	Suppressed: hudson.remoting.Channel$CallSiteStackTrace: Remote call to 10.133.166.10 - Finland-Cloud1
11:18:53  		at hudson.remoting.Channel.attachCallSiteStackTrace(Channel.java:1743)
11:18:53  		at hudson.remoting.UserRequest$ExceptionResponse.retrieve(UserRequest.java:357)
11:18:53  		at hudson.remoting.Channel.call(Channel.java:957)
11:18:53  		at hudson.FilePath.act(FilePath.java:1072)
11:18:53  		at hudson.FilePath.act(FilePath.java:1061)
11:18:53  		at hudson.plugins.robot.RobotParser.parse(RobotParser.java:53)
11:18:53  		at hudson.plugins.robot.RobotPublisher.parse(RobotPublisher.java:223)
11:18:53  		at hudson.plugins.robot.RobotPublisher.perform(RobotPublisher.java:247)
11:18:53  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:80)
11:18:53  		at org.jenkinsci.plugins.workflow.steps.CoreStep$Execution.run(CoreStep.java:67)
11:18:53  		at org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.lambda$start$0(SynchronousNonBlockingStepExecution.java:47)
11:18:53  		at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
11:18:53  		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
11:18:53  		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
11:18:53  		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
11:18:53  		at java.lang.Thread.run(Thread.java:745)
11:18:53  Caused by: javax.xml.stream.XMLStreamException: Could not find elements [doc] (at line: 110165 column: 1)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.xmlException(RobotParser.java:254)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.ignoreUntilStarts(RobotParser.java:292)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processTest(RobotParser.java:351)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:213)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.processSuite(RobotParser.java:211)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.parseResult(RobotParser.java:169)
11:18:53  	at hudson.plugins.robot.RobotParser$RobotParserCallable.setRobotResult(RobotParser.java:145)
11:18:53  	... 11 more`
