### ISSUE TITLE
Support for 'IDEOGRAPHIC SPACE' (U+3000) in test data on IronPython

### ISSUE THREAD

**Issue by title** [robotframework/robotframework#2071]
While using IronPython to execute robot framework, ideographic space (U+3000) in test data will be replaced by white space (U+0020).
( `robot.parsing.datarow.DataRow._collapse_whitespace` ).
BTW, ideographic space won't be replaced in CPython.

Example:
`${v1} | Set Variable | 1 2`
`${v2} | Set Variable | 1　2`
`Should Be Equal | ${v1} | ${v2}`

This case will:
    **PASS** in IronPython
    **FAIL** in CPython

**Comment by pekkaklarck** [comment]
Yeah, it seems that `re.match(r'\s', u'\u3000')` doesn't match with Python but matches with IronPython. That is a bug in IronPython and should be reported to its tracker. I don't think it makes sense for us to try adding a workaround.

Instead I could consider changing the behavior so that also ideographic space is always considered a normal space, similarly as non-breaking space is (#1264). That would make space handling more consistent, but would also potentially cause backwards incompatibility problems. I don't want to do that anymore in RF 2.9, but could be considered in RF 3.0 later this year.

A good workaround for the problem you encountered is using escape sequences, e.g. `\u3000` in Robot data. Alternatively you could create more complicated variables in variable files.

**Comment by title** [comment]
Thanks! Seems using escape sequences is the best solution for now.

**Comment by pekkaklarck** [comment]
There's a good workaround for the problem. Changing the behavior when not using IronPython is probably not a good idea. Closing.
