### ISSUE TITLE
Cleanup acceptance tests

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2091]
The Robot Framework's own acceptance need some cleanup. Different platforms and requirements are handled sometimes by tags, sometimes by setting test non critical. The names for these tags are inconsistent as well. Also the keyword names are not written in consistent style. There is probably much more... It would be great to clean this stuff up along with the Python 3.0 support.

- [x] Change `pybot`, `jybot`, and `x-fails-on-ipy` tags to `no-jython`, `only-jython`, `no-ipy` etc
- [x] Get rid of `regression` tag if possible
- [x] If possible, change the non critical tests to be critical and just don't run them on a platform where they don't work
- [x] Add tags `require-lxml`, `require-docutils`, `require-yaml`, and `screenshot` and make all of these tests to be always critical.
- [x] Add `no-ci` tag or similar, which would skip manual and telnet tests (all other could then be critical on ci?)
- [x] Keyword names should be written in consistent style
- [x] Cleanup and streamline the test running system and `atest/run_atest.py` in general. Perhaps rename it to `atest/run.py`.
- [x] Update `atets/README.rst`.

**Comment by pekkaklarck** [comment]
This task turned out to be much bigger than we expected but we are also happy with the end results. Remaining tasks:

1. Resolve TODOs in `atest_resource.robot` added in dd3fc16.
  - Mainly keyword cleanup.
  - Some may not be good idea (generally contain `?` at the end)

2. Update `atest/README.rst`
  - Explain using `no-ci`.
  - Update section about required modules.
    - Add a link to `requirements.txt`. 
    - Explain how to avoid running tests if modules not available

**Comment by jussimalinen** [comment]
Thats it for now I think.
