### ISSUE TITLE
Make a log file after force stop

### ISSUE THREAD

**Issue by MoonSungHoon** [robotframework/robotframework#2094]
When I run pybot, expect Report and Log after end of the test.

But if it stopped in running unfortunately, I couldn't get anything. This make me harder to get why the test is not run well or not end. ( especially when include thread logic )

I want get a log file after stopped a execution.

**Comment by pekkaklarck** [comment]
If you press Ctrl-C once or send INT or TERM signal, Robot exists gracefully and generates logs and reports. If you stop it otherwise, it will exit immediately and won't finish output.xml nor spend time generating logs/reports. Could you clarify how would you like this to be enhanced? More information in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#stopping-test-execution-gracefully

Notice also that broken output.xml can be fixed with separate [fixml tool](https://bitbucket.org/robotframework/fixml) and logs/reports generated afterwards with Rebot.

**Comment by MoonSungHoon** [comment]
I have a keyword what waiting for a specific log as a thread.
It is not end until log found. Stop execution gracefully it impossible.
( That's a hang like a race condition. )
But I want know what happen until that error. Is it possible?

**Comment by pekkaklarck** [comment]
If you forcefully stop a process, there's no way the process could still do something like generate logs and reports. You need to use some other mechanism for communication. This issue tracker is not the right place to discuss about alternatives.

**Comment by putaodoudou** [comment]
i met the same problem
