### ISSUE TITLE
Embedded arguments do not work anymore if keyword name is same but regexp is different

### ISSUE THREAD

**Issue by nao921** [robotframework/robotframework#2095]
Posted on [robotframework-users](https://groups.google.com/forum/#!topic/robotframework-users/r_oWoQcNBGM), with confirmation from @pekkaklarck that this is a bug.

```
*** Keywords ***
It is a ${noun:(car|ship)}
   Log    first keyword: ${noun}

It is a ${noun:(dog|cat)}
   Log    second keyword: ${noun}

*** Test Cases ***
Test1
   It is a car
   It is a dog
```

with RF 2.8.6:
```
It is a car
Log      first keyword: car
It is a mouse
Log      second keyword: mouse
```

with RF 2.9:
```
ERROR    No keyword with name 'It is a car' found.
| FAIL |
No keyword with name 'It is a car' found.
```

**Comment by pekkaklarck** [comment]
This is caused by a bug in code checking are there duplicate user keywords. It uses the same check as when checking does a keyword exist.

Doesn't occur with newly added embedded args with library keywords because they don't check are there duplicates in the first place. That is itself a bug and I submitted #2097 about it.

**Comment by nao921** [comment]
Thanks @pekkaklarck! that was speedy!

**Comment by pekkaklarck** [comment]
Thanks for thanks and for a bug report with a very good example @nao921! We try to get 2.9.1 released already this week, but it may slip to next week if we don't get everything planned for it done soonish.
