### ISSUE TITLE
rebot discards warning messages in merge mode

### ISSUE THREAD

**Issue by mwalle** [robotframework/robotframework#2133]
We run our test suites individually and merge the resulting output-*.xml files with rebot into one common output.xml.

We've noticed that only the warning messages of the first xml file are listed in the "Test Execution Errors".

Steps to reproduce:
- Create two test suites root.ts1 and root.ts2, see below.
- pybot -o ts1.xml -s ts1 root-ts/
- pybot -o ts2.xml -s ts2 root-ts/
- rebot --merge *.xml

The resulting log.html only contains one warning message, which is the one of the first xml file. If you swap the rebot arguments, ie "rebot --merge ts2.xml ts1.xml", only the warnings of the TS2 test suite are shown.

The contents of root/ts1.txt

    *** Test Cases ***
    Test
        Log  This is TS1  WARN

The contents of root/ts2.txt

    *** Test Cases ***
    Test
        Log  This is TS2  WARN

**Comment by pekkaklarck** [comment]
Warnings and errors probably weren't taken into account when designing the merge functionality. It probably wouldn't be hard to copy all warnings and errors from the merged outputs into the generated one. There would be some problems, though:

1. Same error/warning occurring in all files would be listed multiple times. I guess this isn't such a big issue because you generally shouldn't have errors or warnings.

2. Linking from warnings/errors to keywords causing them would probably be broken. Such links simply cannot work if keywords causing problems wouldn't even be in the final result. I guess thisisn't such a big issue either, especially if we can detect that the keyword doesn't exist anymore and don't create a link at all in that case.

After thinking this a bit more, the above problems look pretty minor compared to the current behavior of totally ignoring errors and failures in the merged outputs.

**Comment by pekkaklarck** [comment]
The problem has been fixed. Linking to keywords works if keywords still exist but all warnings are preserved.
