### ISSUE TITLE
Suite Teardown failure fails all the suite test cases

### ISSUE THREAD

**Issue by jjjnovak** [robotframework/robotframework#2134]
Hi,
When running the Robot Framework tests, the really annoying feature is that a suite teardown
fails all the test cases even when they actually passed.
Is there a way to disable this behaviour please ??
A simple network glitch after several hours of testing just wrecks all the results ...

Tx, Jan

**Comment by laurentbristiel** [comment]
There is no way to disable this behaviour.
I would suggest you two keywords to workaround your problem:
* [Wait until keyword succeeds](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Wait%20Until%20Keyword%20Succeeds): this keyword can workaround intermittent problem (like network glitch) by trying the same keyword several times
* [Run Keyword and Ignore Error](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Run%20Keyword%20And%20Ignore%20Error): if your statement is optional somehow, then just ignore the error  

Hope this helps.

**Comment by pekkaklarck** [comment]
@laurentbristiel is right and there's no way to generally disable this behavior. We could consider something like `--IgnoreTeardownFailures`, but as a global setting affecting all teardowns it would be somewhat risky. Explicitly ignoring failures with `Run Keyword And Ignore Error` where needed is much safer. Even better solution would be enhancing the lower level keywords so that they can handle these problems.

I'll close this issue because it is more like a question than an enhancement request or a bug report. If you have a concrete enhancement idea, please submit a separate issue. For questions and general discussions we recommend `robotframework-users` mailing list or the Slack channel.

**Comment by jjjnovak** [comment]
Ok, thanks for looking at it. Sorry, did not realise this was for enhancements requests or bug reports.
I would like still to capture the Teardown failure but don't want to fail all of the testcases.
Couldn't there be a switch or an option somewhere to do so - like "on_teardown_failure_fail_only_teardown" :-) ???

**Comment by pekkaklarck** [comment]
You submitted #2135 about the option to disable teardown failures. Let's continue discussion there.
