### ISSUE TITLE
Enhancement - suite teardown failure

### ISSUE THREAD

**Issue by jjjnovak** [robotframework/robotframework#2135]
Please consider adding an option to Robot which would allow the user to say to Robot:
"When suite teardown fails, fail ONLY the teardown, not all the test cases".

Tx, Jan

**Comment by pekkaklarck** [comment]
As I already commended in #2134, a global option to change this behavior sounds pretty risky. It would very easily hide problems that shouldn't be hidden when applied to all suite teardowns. Is there a reason you couldn't use `Run Keyword And Ignore Error` in those individual places where it is needed?

**Comment by jjjnovak** [comment]
I don't understand what is risky about not failing the testcases when Teardown fails ?? It is just an administrative decision - to me - I know nothing about Robot internals, I just execute it.
I don't want to ignore Teardown failures - I want Teardown to fail if there is a failure in Teardown itself but I don't want to get also all the testcases to fail when there is ONLY teardown failure and nothing else during the whole execution failed ?? I am not sure if we understand each other with this.

**Comment by pekkaklarck** [comment]
The main problem is that you wouldn't see these teardown failures anymore. They wouldn't be visible in reports at all and they wouldn't affect the overall test execution status. You would only see them if you would look at the log file and find that teardown there.

**Comment by jjjnovak** [comment]
Ok, did not know that - and what about failing just the suite last testcase just before the teardown only then ??

**Comment by pekkaklarck** [comment]
I think that it would be a bit weird to fail only the last test when we don't know what actually caused the problem. The current behavior is also consistent with suite setup failures that also fail all test in the suite.

**Comment by jjjnovak** [comment]
When setup fails, it is perfectly valid - I don't want to execute any tests.
When teardown fails, I don't really care, I want to see my test results and not a failure all over the place.

**Comment by pekkaklarck** [comment]
Do you have better ideas how to show suite teardown failures? We have been thinking about that earlier but haven't figured out any better solution than the current. My general recommendation is construction teardowns so that they don't fail except in _very_ special cases where you really want to see the failure.

Notice that if you want a custom solution, you can pretty easily modify output.xml after execution and make sure all suite teardowns have `status="PASS"`.

**Comment by aharrisuk** [comment]
One possibility that I used in a previous test framework was a pseudo test suite - its sole job was to catch the results of the log scanner testcase for each suite (log scanner was run as last testcase in each suite).  This was the report would show PASS/FAIL for each suite while the pseudo suite would show PASS/FAIL for all the suites log scanner (and looking in the log file for the pseudo suite would list the suites and associated output).

This was good because we could say that functionally the suite had passed or failed, but that we picked up an unexpected log message (before the log message would have failed whole suite even though it had functionally passed - and the log message was safe). The bad side is you have disconnected one part of the test from the rest of the test (so its a little easier to ignore a failure in the pseudo suite)

In this model the teardown results would be redirected to the pseudo suite - and the main suite would not be affected by a teardown PASS/FAIL.

**Comment by jjjnovak** [comment]
Ok, thanks for the suggestion of just parsing output.xml - might do that to see my results at least.
I don't know enough about Robot internals to suggest a solution. In the test machinery Alastair
mentions above (we have been colleagues working on the same thing last about 10 years) we used
before we had a testcase for example for "DUT Stability" or something automatically added to 
each test suite to capture general errors (tracebacks in the logs and such) which might not have been
related to the tested functionality but which could fail all the test cases so we failed just one instead
but still captured a failure.
Otherwise short term at the moment I would prefer just not know about teardown failure  than fail
2-3 hours worth of passing testing.
Thanks for looking at this and for the discussion !!!

**Comment by jussimalinen** [comment]
You still have the option of using `Run keyword and ignore error`, which you can alias to a shorter form if you please (for example `Ignore Errors`). So Instead of this:

```robotframework
*** Settings ***
Suite setup    My teardown   foo
```

You just would do this:

```robotframework
*** Settings ***
Suite setup    Ignore Errors    My teardown   foo
```

**Comment by menonprasad1** [comment]
When using a listener, the end_test gets called before any of the failures. Getting the result at that stage will give only the test case status, the setup could fail and this wouldnt effect the result captured at this stage.

**Comment by bijua** [comment]
I guess this has been an Issue with lot of the Test Case Executors of Robot Framework :-)

I completely agree that you cannot and may not want to ignore all tear down failures. But since the tear down failures (ideally) does not effect results any of the tests that are passed, the tear downs should not fail the test cases. Instead it should PASS the test case with a warning. Let that be the case with Test/Suite Tear downs.

Would that make sense?

A warning can be shown in a different color (may be back ground changes to yellow or something like that) so that it will be looked at in the reports.

**Comment by jjjnovak** [comment]
Hi,


Anything is better than failing all the testcases. If just the teardown itself failed and was reported

as a failure on its own, it would be ideal.


Tx, Jan


The climate of Edinburgh is such that the weak succumb young ... and the strong envy them.

                                    Dr. Johnson


________________________________

**Comment by bijua** [comment]
A different method would be giving an option to specify how a teardown failure has to be treated as. By default it can be "WARN" and with other options to "FAIL" to fail the test case.

Just a thought.

**Comment by pekkaklarck** [comment]
The problem of just failing the teardown is that you cannot see that in report and it doesn't affect the overall test execution status. It would thus be *very* easy to accidentally miss teardown failures. The same problem applies also for warnings because they are only visible in log files.

It would obviously be possible to try coming up with a way to show suite teardown failures in reports, but at least I don't consider it important enough considering how much work it would be. I don't like the idea to show all warnings in reports either, but having a notification that there are warnings/errors might be a good idea. It wouldn't be enough to make sure teardown failures aren't accidentally ignored, though.

In general I think the current situation is pretty good. By default you will be very visibly notified about failures in suite teardowns. If you want to dismiss such warnings, you can easily wrap your suite setup with `Run Keyword And Ignore Error`:

```robotframework
*** Settings ***
Suite Setup        Run Keyword And Expect Error    My Setup

*** Keywords ***
My Setup
    # ...
```

There's also been discussion about adding `Run Keyword And Warn On Failure` (#2294) what would turn the behavior to what @bijua proposed above.

**Comment by jjjnovak** [comment]
Hi,


Ok, thanks for looking at it in detail.

Funny, for me the current status when something uninteresting happens at the teardown

and fails 100 test cases worth of 5 hours of testing is quite unacceptable/unusable.

Yes, thanks for the workaround, I think I will implement the "Ignore error" option.


Jan


The climate of Edinburgh is such that the weak succumb young ... and the strong envy them.

                                    Dr. Johnson


________________________________

**Comment by pranavp007** [comment]
So whats the final verdict here? We should just ignore errors in teardown to make the test cases marked as passed in the report / log? Or there's an alternate way of ignoring the impact of suite teardown failure on individual tests?
I am using "Run Keyword and continue on failure", because I want all my teardown commands to run regardless of any failure. However, I don't want to "ignore error" because I should know the failures.
I concur with jjjnovak here that its really annoying to see all the test cases failed just because the teardown failed. Teardown failures should not be treated in the same way as Startup failures.

**Comment by pekkaklarck** [comment]
The verdict is that the current functionality is not going to changed. That's the reason this issue is closed.

Notice that all teardowns are always executed fully even if some keywords in them would fail. Using `Run Keyword And Continue On Failure` is thus not needed. If you want to prevent possible failures in suite teardowns failing tests in that suite, you can wrap the whole teardown into `Run Keyword And Ignore Error` as explained in earlier comments. The problem with that approach is that you don't see these errors unless you explicitly look at that teardown in log. It's possible to create a generic user keyword that uses `Run Keyword And Ignore Error` internally and turns possible failure into a warning. We also have issue #2294 about adding such `Run Keyword And Warn On Failure` keyword into the BuiltIn library but nobody has implemented it yet.

A problem with turning failures in teardowns into warnings is that warnings are not shown in reports at all and they are thus easy to miss unless you look at the log file. Having an indication in the report that there have been failures would probably be a good idea in general but I don't think we even have an issue about that yet. With that enhancement and the aforementioned `Run Keyword And Warn On Failure` keyword implemented, there would be an easy way to turn failures in teardowns into warnings that aren't easily missed. As already mentioned, the default behavior is not going to change.

**Comment by pekkaklarck** [comment]
I'm not sure does machinery I don't understand refer to this issue or skipping, but here's my quick take on both:

- My opinion about this issue is that the current behavior is good. I understand you disagree but in general user seem to be fine with it. If majority of users would prefer the other approach, I'd be fine changing the design but even then we needed to take backwards compatibility into account. Adding `Run Keyword And Warn On Failure` would make it trivial to get the behavior you apparently want, but nobody has yet needed it enough to implement it. If you'd like to see it in RF 3.1, see #2294.

- Skipping tests is such a huge change in Robot's functionality that I want to be 100% sure it works well before it is added. The main problem is how skipping should work with the current criticality functionality, but the change would touch so many parts of the frameworks that implementation work is big too. Unfortunately I haven't been able to work even part time with Robot lately, so nothing big like this has proceeded. Such a big feature can also be added in a major release. Luckily I now have time (and sponsor) for RF development, but it's unlikely there's enough time to get this in RF 3.1. Anyway, this discussion should continue in comments of #2087.

**Comment by valdemarpavesi** [comment]
good!   there are cases that we do want to use it just to clear all.

Suite Teardown         Run Keyword And Ignore Error    Close all Connection Execute Teardown


from:

77 critical tests, 0 passed, 77 failed
77 tests total, 0 passed, 77 failed


to:

77 critical tests, 66 passed, 11 failed
77 tests total, 66 passed, 11 failed
