### ISSUE TITLE
'Log' doesn't give any output in combination with 'should be empty'

### ISSUE THREAD

**Issue by rynstone** [robotframework/robotframework#2139]
Works fine when I remove the 'should be Empty'

```
Check DB
    Connect To Database Using Custom Params    cx_Oracle    user=${rep_dbuser},password=${rep_dbpw},dsn=${rep_dbdsn}
    ${check}    Query    select 1 from dual
    Disconnect From Database
    should be Empty    ${check}
    log    I found this: ${check}    error
```

**Comment by pekkaklarck** [comment]
Please clarify.

**Comment by rynstone** [comment]
The above example never logs any message, whenever using 'should be empty' in a testcase 'log' never works for me.

**Comment by jussimalinen** [comment]
So is the `Should be Empty` above failing? The test execution stops to first failure.

**Comment by rynstone** [comment]
no, ``` should be empty ``` seems to be working fine
Output for the example above:

```Starting test: Test.Check DB
20150914 14:40:32.404 :  INFO : ${check} = [(1,)]
20150914 14:40:32.498 :  INFO : Length is 1
20150914 14:40:32.499 :  FAIL : '[(1,)]' should be empty.
Ending test:   Test.Check DB```

**Comment by pekkaklarck** [comment]
Your example output shows that `Should Be Empty` fails with message `'[(1,)]' should be empty.`. As Jussi commented above, subsequent keywords aren't executed after that. Everything works as designed.

Move `Log` before `Should Be Empty` if you always want to get the value logged. I don't see why you would want that, though, because the error message of `Should Be Empty` contains the value by default.
