### ISSUE TITLE
`Given' is not removed at the beginning of keyword when preceded by variable

### ISSUE THREAD

**Issue by uilianries** [robotframework/robotframework#2150]
Following this scenario:

In the file MyTest.rst (as test case file), I have the step:

Given foo process is running

In the file MyTest.py (as library), I have the follow method:

@keyword(name='Given ${process_name} process is ${status}')
def process_is_running(self, process_name, status):

Okay, this works fine. My variable ${process_name} is 'foo' and ${status} is 'running'

However, if I remove `Given', from the keyword, the variable ${process} will be 'Given foo'. 
@keyword(name='${process_name} process is ${status}')
def process_is_running(self, process_name, status):

Given is a Gherkin keyword, should not be interpreted for the keyword.

I created a basic test to prove this issue, please see:
https://github.com/uilianries/robotframework-issue

I'm using pybot, Robot Framework 2.9.1 (Python 2.7.6 on linux2)

**Comment by pekkaklarck** [comment]
I tested your example and both tests fail in `When I verify the service bar status` keyword for `NotImplementedError`. Looking at the test and the library, that seems to be the expected behavior. Did I understand something wrong? Could you clarify what should be the expected outcome and what results you get?

**Comment by pekkaklarck** [comment]
Oh, now I got it. The log message of the first keyword of the second example contains `Given foo` when you expect it to contain just `foo`. That's actually and unfortunately the expected behavior. I'll explain that in a separate comment.

**Comment by pekkaklarck** [comment]
First of all, the problem is that when there is a keyword like `${foo} bar` and it is used like `Given foo bar`, the value of variable `${foo}` will be `Given foo` and not `foo`. This happens because Robot first checks does the used keyword `Given foo bar` match any defined keyword using the full name. In this case `Given foo bar` matches `${foo} bar` so that `Given foo` matches `${foo}`. If it wouldn't match, then Robot would notice that `Given foo bar` starts with `Given ` and check does `foo bar` match any defined keyword.

We cannot change the behavior because it would be backwards incompatible, but luckily it isn't too complicated to fix this issue. The simplest solution is to always surround embedded arguments with quotes like `"${foo}" bar`. `Given "foo" bar` wouldn't match that and Robot would then try `"foo" bar` that matches. 

Alternatively you could specify a custom regular expression when defining the keyword. If you, for example, know that the given value is at least one character long and never contains spaces, you could use something like `${foo:\S+}`.

Yet another possibility is explicitly matching all gherkin prefixes like `${prefix:(Given|When|Then|And|But)} ${foo} bar`. That adds quite a bit of noise and also requires you to change your library keyword to accept that additional `prefix` argument.

**Comment by pekkaklarck** [comment]
I hope the explanation in the above comment makes the situation clear and you can use some of the explained workarounds. The User Guide already now recommends using quotes around embedded arguments and also explains using custom regexps. It has some examples where they especially useful or absolutely needed, but I don't think it has anything about this exact situation with gherkin prefixes. Would you @uilianries be interested to check what the User Guide has and check could the documentation and/or examples be enhanced?

**Comment by pekkaklarck** [comment]
Here's a link to the section explaining embedded arguments syntax:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#embedding-arguments-into-keyword-name

**Comment by uilianries** [comment]
@pekkaklarck, thank you!

Now I got the point. I will use the regex to solve this question in my case.

Thanks again!
