### ISSUE TITLE
Error in test library 'KeywordLibraryName' : Creating keyword 'keywordname' failed: Keyword with same name defined multiple times. When calling a component keyword through a page object keyword 

### ISSUE THREAD

**Issue by ZiedWD** [robotframework/robotframework#2161]
Hello All,

I am facing a very strange issue with my robot framework tests.
I have created some user libraries and added some keywords.
my tests were working fine.
Once without making changes to my code (at least I am not aware I did), i am facing the following error for all my keywords of all my libraries.

Error in test library 'ReservationPage': Creating keyword 'Add Message To Hotel' failed: Keyword with same name defined multiple times.

Any help would be appreciated

**Comment by laurentbristiel** [comment]
Somehow you must have the same keywords defined twice...
Though this is not an issue and should not be raised in GitHub. 
You should ask the question in the [user mailing list](https://groups.google.com/forum/#!forum/robotframework-users)).
And try to give more information about the failure (maybe try to give some informations how to reproduce your issue with a small config/dataset)

**Comment by pekkaklarck** [comment]
This is most likely caused by a fix for #2097 in RF 2.9.1. Do you have a static library (i.e. Python or Java code that directly implements library methods, the most common case) or a hybrid or dynamic library (i.e. library that uses `get_keyword_names` to tell which keywords it contains)?

Notice that the fix for #2097 has already caused issues as it broke compatibility with the AutoItLibrary (#2147). That problem was fixed with a small change to how dynamic and hybrid libraries are handled, but the fix hasn't yet been released.

**Comment by ZiedWD** [comment]
Thanks Pek, yes I do have user defined python libraries and I am using the page object library. After some debugging I found out that this error is caused by a page object library calling a component library keyword. So this is a kind of embedded argument keyword. I guess I have to wait for the 3.0 version for a fix. Do you know when will be the release date for 3.0?

**Comment by pekkaklarck** [comment]
This error is not related to keywords with embedded arguments. Because what they match depends on the actual embedded arguments used, conflicts with them are only detected at runtime.

The PageObjects library you use is a dynamic library that returns keywords it contains from `get_keyword_arguments`. It seems the list it returns contains duplicates and Robot, since 2.9.1, doesn't like that. Hopefully they are exact duplicates (e.g. `my_name` and `my_name`), because in the forthcoming 2.9.2 that is OK (this was the fix for AutoItLibrary in #2097). If they are not exact duplicates but are normalized to same keyword name (e.g. `my_name' and `myName`), they won't work in the future either.

It would be great if you could clone the latest Robot sources, install it, and test does the problem go away or not. If it goes away, then #2097 has fixed it too. If not, we can still try to investigate this further to make sure we understand the root cause.

**Comment by pekkaklarck** [comment]
Any new information about this @ZiedWD? We've just released RF 2.9.2 which contains the fix for #2147. Could you test do you still get errors with it?

**Comment by ZiedWD** [comment]
I have upgraded my robot framework version to 2.9.2 and I confirm that the issue is resolved,  am not getting the error anymore.

**Comment by pekkaklarck** [comment]
Great! The root cause apparently was the same as in #2147.
