### ISSUE TITLE
Variables containing file objects should not be considered list-like

### ISSUE THREAD

**Issue by PeterMichalko** [robotframework/robotframework#2162]
I experience issue originally reported to Selenium2Library
https://github.com/robotframework/Selenium2Library/issues/516 - which contains more details and log
(comment from Tatu Aalto):
This can be also reproduced without Selenium2Library. When I have this test suite:

``` robotframework
*** Settings ***
Variables    test_variables.py

*** Test Cases ***
Example
    BuiltIn.Get Variables
```

And test_variables.py contains this:

``` python
out = open('outputdir.tmp', 'w')
out.write('write something to file')
out.close()
```

Then I also get ValueError: I/O operation on closed file

The reason why this also manifest by using Selenium2Library is that the discovery of the ${OUTPUT_DIR} and few other things was changed in Selenium2Library 1.7.1 to support Robot Framework 2.9 series. Instead of using Robot Framework internal and not public API, we now use the public API (for few things).

**Comment by pekkaklarck** [comment]
Interesting bug. The reason it occurs is this:

- Your variable file creates variable `${out}` that is assigned to a closed file object. 
- `Get Variables` inspects is a variable list-like by using `is_list_like` method that uses `iter(item)` internally. It handles possible `TypeError` that occurs if the item is not iterable, but all other exceptions go through.
- Files are iterable, but `iter()` on a closed file causes `ValueError`.

We will fix this in RF 2.9.2 either by special casing files not to be considered lists in `is_list_like` or by changing the logic so that any exception that occurs due to `iter()` is considered to mean that the item is not list-like.

My guess is that you don't mean your `out` to create variable `${out}` and simple fix for your variable file is avoiding that. You can either prefix it with `_`, add `__all__` where it is not listed, or add `get_variables()` that explicitly returns needed variables. See the User Guide for more details about this options.

**Comment by PeterMichalko** [comment]
Thank you very much for your analysis.
As I did not want to create ${out} as variable, I just deleted it in test_variables.py with command:
del out

**Comment by jussimalinen** [comment]
We decided to make files not list like. This can be backwards incompatible, if someone has used files as lists. Fix should be rather easy though `@{file}` -> `@{file.readlines()}`

**Comment by jussimalinen** [comment]
As part of this issue we also made it so that objects that raise an exception in __iter__ are not lists and the exception is silently ignored.
