### ISSUE TITLE
OperatingSystem: `Get File` and `Create File` should support native encodings

### ISSUE THREAD

**Issue by jussimalinen** [robotframework/robotframework#2196]
In python io.open will open files using system encoding if no encoding is given. It would be useful to be able to tell `OperatingSystem.Get File` to use this system encoding. It could be done for example by giving value `encoding=native`.

**Comment by pekkaklarck** [comment]
Probably should support `SYSTEM` and `CONSOLE` similarly as Process nowadays does. See #2198 for details.

**Comment by jussimalinen** [comment]
`Create File` should support this too for symmetry

**Comment by pekkaklarck** [comment]
Good catch with `Create File`. I'm not sure are there use cases for creating files with the console encoding, but probably it's better to support same special encodings with both keywords. Obviously reading files in console encoding is rather rare too (there is no legit reason to create them IMHO), but we happen to need that functionality in our atests due to IronPython bugs. Because we have already worked around that in our tests, we could still consider just adding support for `NATIVE` encoding.

**Comment by pekkaklarck** [comment]
Looks good. Little cleanup in 05c2e3d.
