### ISSUE TITLE
using the keyword  input text is invalid in robot frameworkIDE

### ISSUE THREAD

**Issue by dengee** [robotframework/robotframework#2220]
I need create a virtual disk in a project,then ,I use the key word ,input text disk1 and succeed,.then,i remove the virtual  disk disk1,and repeat above manipulate,is not work,why? Help me,thanks!

**Comment by pekkaklarck** [comment]
This tracker is for bug reports and enhancements related to Robot Framework itself. This issue is a question and seems to be about Selenium2Library and/or RIDE. Questions are best asked on robotframework-users mailing list and other similar forums.

You may also want to explain the problem a bit more clearly if you expect others to spend their time to help you. This great article explains why and how: http://www.catb.org/esr/faqs/smart-questions.html
