### ISSUE TITLE
Parsing massive test case file takes lot of time

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2231]
Hello,

We are auto generating robot framework testcase through some automation scripts the generated robot framework testcase size approximately 50 MB, while i used to 

``` bat
pybot.bat -b test_log.log -L DEBUG:INFO --noncritical SKIP test_map_1.robot
```

It took around 30 minutes to analyse the testcase after that it started actual execution and completed in 4 minutes

The number of lines in testcase approximately 4,00,000

Is there any methods to find why it took so much time analyse the testcase?

If not are there any methods to solve this issue?

Thanks
Malli

**Comment by jussimalinen** [comment]
Interesting. It is a very big file, but then again 30 minutes is a surprisingly long time for parsing.

If you could attach a version of the script where you anonymize the content (for example get just change all actual library keyword calls to `BuiltIn.No Operation` and rename the variables and keywords to something you can share publicly) we could then analyze it here.

**Comment by pekkaklarck** [comment]
I have been doing performance profiling lately and would be interested to see where the time is spent in this case. Any change you @vkosuri could provide a version of the script that we could use like @jussimalinen already asked? We cannot do much else than recommend getting more RAM and better processor if we cannot reproduce the problem ourselves.

**Comment by vkosuri** [comment]
Thanks pekkaklarck and jussimalinen

Due to anonymization the file reduced to 30MB, however i still observed same analyses time. Please find the file located at https://drive.google.com/file/d/0B_cUPwVRE2oUWTBQdWlndW9DYlk/view?usp=sharing

Could you please let me know root of this issue. 

Thanks
Malli

**Comment by pekkaklarck** [comment]
First of all, the real problem with this test case file is the file itself. It is simply massive with close to 400k lines of data. there were only 37 tests so each test had about 10k keywords. On a quick look the data seems to be very repetitive, and by using few simple higher level keywords you ought to be able to make the file a lot smaller. Having some of the logic in libraries would also make the resulting log file smaller.

The above said, spending half an hour to parse this kind of a file is not ideal. Good news is that simple performance analysis with `cProfile` reveled a place where building this kind of big tests was very ineffective and it was easy to change the code to make it work better. After these changes your reference file now runs in less than half a minute on my machine.

Although the savings are massive (30min vs 30s) in this particular case, I don't consider this issue critical or even high priority in general. The reason is that normal tests or keywords don't benefit from the change at all.

**Comment by vkosuri** [comment]
If possible can i get fix available code, so that we can use it.

**Comment by pekkaklarck** [comment]
I have now committed and pushed the code. You can clone the repository and get the code that way or wait until RF 3.0 alpha 2 in few weeks.

**Comment by vkosuri** [comment]
@pekkaklarck Thank you very much it's working.

**Comment by pekkaklarck** [comment]
Great! I would anyway see could test generation be enhanced to make the file and the resulting log file smaller.

**Comment by mkorpela** [comment]
So seems that parsing dryrun xml file for this will also consume a lot of time.

**Comment by mkorpela** [comment]
.. assuming the test referenced in pabot project was executed against new robot framework with the fix in place. But that IMHO has to be verified from vkosuri
