### ISSUE TITLE
Using list variable as user keyword argument default value does not work

### ISSUE THREAD

**Issue by mwalle** [robotframework/robotframework#2243]
There seems to be no predefined variable for an empty list/tuple. Consider the following code

    *** Keywords ***
    My Keyword 1
        [Arguments]  ${myList}=@{EMPTY}
        Log  ${myList}

    My Keyword 2
        [Arguments]  ${myDict}=&{EMPTY}
        Log  ${myDict}

`My Keyword 1` does not work, because @{EMPTY} appears like there is just nothing (a better name would have been @{VOID} IMHO), although i don't know why the variable ${myList} does not exist.

`My Keyword 2` instead works like expected.

So at the moment we have the following clunky workaround:

    My Keyword
        [Arguments]   ${myList} = ${None}
        ${emptyList}=  Create List
        ${myList}=  Set Variable If  "${myList}" is "${None}"  ${emptyList}  ${myList}

**Comment by pekkaklarck** [comment]
Interesting. The first keyword failing with `Variable '${myList}' not found.` is definitely not right. I need to check what's causing it and see could we change it to work as expected.

**Comment by pekkaklarck** [comment]
The problem is that it isn't generally possible to use list variables as user keyword default values. Things would also go wrong if you would have a non-empty list variable as a default value.

There is a pretty easy workaround to use a scalar variable containing list as a default instead of using a list variable. The problem with an empty list is that you cannot use `${EMPTY}` because `EMPTY` variables are special and that one maps to an empty string. Instead you can do this:

```robotframework
*** Variables ***
@{EMPTY LIST}

*** Keywords ***
My Keyword
    [Arguments]    ${my list}=${EMPTY LIST}
    Log    ${my list}
```

The above will, however, work slightly differently than if a list variable could be used instead. The difference is that with a list variable the created variable would be a copy of the original list (or list-like object) but with a scalar variable you actually get the original object. In practice it means that possible modifications actually modify the original list. That problem can be avoided by creating a new list:

```robotframework
*** Keywords ***
My Keyword
    [Arguments]    ${my list}=${EMPTY LIST}
    ${my list} =    Create List    @{my list}
    Log    ${my list}
```

**Comment by pekkaklarck** [comment]
Luckily fixing this on Robot side is also pretty easy.
