### ISSUE TITLE
library path to file consistence behavior 

### ISSUE THREAD

**Issue by KrzysztofJozefowicz** [robotframework/robotframework#2250]
There is inconsistency of handling library names when refereeing to lib filenames when using filename without lib extension.

Let me use robot calculator demo for example : https://bitbucket.org/robotframework/robotdemo/downloads   

In local folder we have testcase and library ( eg. keyword_driven.robot and CalculatorLibrary.py ).
Following entries in Settings are supported:
- with file extension 
Library           CalculatorLibrary.py
- without file extension 
Library           CalculatorLibrary
- referencing to Python path
Library           CalculatorLibrary

Whenever user wants to move lib to different folder, referencing lib without file extension will fail testcase therefore there are 2 possibilities to reference to library file. One is universal (file extension), other is special case and works when lib is in the same place as TC.

I don't know how commonly special usage is but it does not improve test debug, maybe it is time to evaluate whether lib linking should follow strict rules (if file extensions present than look for files otherwise check python path).
This issue was discovered and discussed during RED development, outcome was that fixing this will, at least, reduce logic on robot lib discovery mechanism and RF reference manual.

**Comment by pekkaklarck** [comment]
There are actually only two ways to import a library:

- With just the module/class name (i.e. without an extension). In this case importing is done fully by Python and the library must naturally be in `sys.path`.
- With a relative or absolute path to the library (including the extension or a trailing `/` if the library is a directory). When using this approach, Robot puts the directory containing the library into `sys.path` temporarily, but otherwise importing is done by Python.In this case the path could also be relative to a directory in `sys.path` similarly as resource and variable files can.

Unfortunately this is complicated by two more things:

- Prior to RF 2.9 the current execution directory (`.`) was added to `sys.path` automatically (#2019). This meant that it was possible to import a library without the extension if it was in the same directory where tests were executed. This actually broke the normal usage of the referred Robot calculator demo, but it has since been fixed:
https://bitbucket.org/robotframework/robotdemo/commits/fc7814413c6390f93e56ed19f0a49c01176eb46f
- When importing a library with a path (i.e. including the extension or `/`) so that the path is relative, Robot also searches the file from all directories in `sys.path`. It wouldn't really be necessary with libraries because they could be imported also without the extension, but this is exactly same logic that is used when importing resource and variable files. I have been thinking that we should never look to `sys.path` in Robot in general, though, and we should have some other way to specify global places where to search resources and variables files. It could perhaps be configured with `ROBOTPATH` environment variable and `--robotpath` command line option. So far we haven't had enough time to implement this (and using `sys.path` hasn't been such a big issue).

Based on the above information, do you @KrzysztofJozefowicz have concrete ideas what should be done for imports? Notice that due to backwards compatibility concerns, we cannot do any (bigger) changes without deprecating the old behavior first.

**Comment by pekkaklarck** [comment]
Any comments about this @KrzysztofJozefowicz? I

**Comment by pekkaklarck** [comment]
Closing due to lack of new information.
