### ISSUE TITLE
<space> in lib name and alias pitfalls

### ISSUE THREAD

**Issue by KrzysztofJozefowicz** [robotframework/robotframework#2260]
Following cases are possible while linking library in testcase file:
Library    OperatingSystem
Library    Operating System
Library    O p e r a t i n g S y s t e m
All those notations are also possible while referring to keyword by lib name thus this creates maintenance headache when user mixes those notations around testcases or test repository (difficult to mass rename/refactor lib name and tests without user intervention). Also libdoc returns lib names without spaces, this can lead to confusion.

Interesting case is with aliases where spaces are also ignored. What happens when we assign aliases to libs but aliases names without spaces are the same ?
Eg:
*** Settings ***
Library    OperatingSystem  with name  al ias  
Library    Dialogs  with name  alias

*** Test Cases ***
t1
    alias.Get Value From User  text
    alias.List Directory    .
It is a way of combining libs together but is it really preferable approach ?
 

What is the reason to allow to use spaces in lib names after all as python or java classes are used underneath where spaces are not allowed?  

From RED editor perspective spaces adds additional logic for parsing and validating testcase.

**Comment by pekkaklarck** [comment]
1. I would be fine removing the possibility to have a space in a library name when importing. The name must be otherwise written correctly anyway because otherwise Python cannot import it. It would be more consistent to require the name to be exactly the module/class name. Due to backwards compatibility reasons we cannot just change this behavior, though, and we first need to deprecate it. Deprecation ought to be easy enough to be done still in RF 3.0, but it definitely must be done before beta 1 (i.e. during this week).

2. Library and resource names used when referring to keywords (e.g. `library.Keyword`) are currently case, space and also underscore insensitive. It can be confusing and can lead to strange behavior like you discovered with aliases, but I don't think changing that is worth the effort. Also matching keyword names is similarly case, space and underscore insensitive, and I consider it consistent that we use the same rules also with library/resource names. In general I consider this very similar issue that using dot in library/resource and keyword names (#2258). Benefits of the change in Robot way are too small compared to the efforts, but RED and other tools can decide to have more strict rules if they want.

**Comment by pekkaklarck** [comment]
I submitted #2264 about deprecating imports with extra spaces and I close this issue as its duplicate. As I commented above, I don't think changes to how keywords are used are worth the effort.

Notice that you may want to implement a separate utility functions/classes to handle normalized comparisons. You can see Robot's own and very widely used `normalize` and `NormalizedDict` are implemented here:
https://github.com/robotframework/robotframework/blob/master/src/robot/utils/normalizing.py

See also somewhat related #2263 that was inspired by your requests to make the syntax simpler. We already deprecated some table and setting names in RF 3.0a1 and that ought to ease your work too.
