### ISSUE TITLE
"OperatingSystem" Library keywords "Copy Directory" has some unpredictable problems.

### ISSUE THREAD

**Issue by wywincl** [robotframework/robotframework#2278]
Here is an example:

*** Settings ***
Library    OperatingSystem

*** Test Cases ***
demo
    Copy Directory    dir1/subdir1    dir2/

when dir2 is not exists. "Copy Directory" will first create dir2  but will no longer copy subdir1 to the dir2.

I hope it can create dir2 first when dir2 is not exists, and then copy subdir1 to the dir2.

**Comment by HelioGuilherme66** [comment]
I think that there is no bug here, or that there is room for improvement (at least in docs with examples). 
If you ```Copy Directory    dir1/subdir1    dir2/``` it will create ```dir2/``` and copy the contents of ```subdir1``` into it (and also any subdirs and files it contains). To do what you want you must ```Copy Directory    dir1/    dir2/```. Of course, that there is the inconvenience of also copying any files inside ```dir1```.
I have also tried ```Copy Directory    dir1/subdir1    dir2/subdir1``` and got ```dir2/subdir2``` with ```dir1/subdir1``` files at this level.
I finally achieved what you wanted, with:
```Copy Directory    dir1/subdir1/    dir2/subdir1/```
(notice the trailing / in directory names)
(tested in Linux x64 with RF 3.0b1)

**Comment by wywincl** [comment]
Test Environment:
Robot Framework 3.0.dev20151119 (Python 2.7.4 on linux2)

copy.robot
*** Settings ***
Library    OperatingSystem

*** Test Cases ***
demo
    Copy Directory    ./dir1/subdir1    ./dir2

subdir1 is empty. and dir2 is not exist
before run: 
.
├── copy.robot
└── dir1
    └── subdir1

after run pybot copy.robot
.
├── copy.robot
├── dir1
│   └── subdir1
└── dir2

......
Which I hope dir2 has subdir subdir1.

**Comment by pekkaklarck** [comment]
This cannot be changed for various reasons:

- `Copy Directory` behaves exactly like `cp` command in this regard, and I assume `copy` on Windows works the same way. This is by design.
- The behavior is even documented: "If the destination exists, the source is copied under it. Otherwise the destination directory and the possible missing intermediate  directories are created."
- Even if we agreed that the behavior should be changed, the change would be backwards incompatible and would require a deprecation period. That would add a lot of extra work.

There is also a simple workaround to create needed intermediate directories first:

```robotframework
*** Test Cases ***
Demo
    Create Directory    dir2
    Copy Directory    dir1/subdir1    dir2
```
