### ISSUE TITLE
Internationalizing support

### ISSUE THREAD

**Issue by teemuvesala** [robotframework/robotframework#2282]
This is enhancement idea and I'm ready to implement this. 

At web applications we often have to test different language versions of web application. During test we also might have to make sure that e.g. things done at Finnish version of application are properly displayed at Swedish version. This requires good internationalization support so that we don't have to have different keywords for each languages. So I'm suggesting following:

We add special marking _{String to be translated} for Robot. At code side I would use gettext library of Python. Also this would need two new keywords to BuiltIn library: "Set translation domain" which describes what dictionary file to be loaded, and "Set Langue" which would set the language. Name of those could be reworked. 

_{String to be translated} would return "String to be translated" if the string is not found from the dictionary file. 

This would keep our tests much cleaner than using the variable style &{_}[String to be translated] and also variable approach fails if the string is not at the dictionary.

**Comment by pekkaklarck** [comment]
This issue is about being able to test apps with different UI depending on the language, right? And not about using other than English with settings (e.g. `*** Testit ***`), in logs and reports, and elsewhere?

For the former purpose the general solution is using variables. If you import them from variable files, you can easily create them dynamically in Python using, for example, `gettext`. Is there a reason this wouldn't work in your context?

Actual i18n of the whole framework is a different thing. Being able to use, for example, Finnish in Finnish projects would sometimes be useful.

**Comment by pekkaklarck** [comment]
Any new info about this?

**Comment by teemuvesala** [comment]
After thinking this, we can close this. We can use hash-style approach and it is not much worse than using my approach at the first post. Instead of _{....} we can use &{_}[Hello world]. It adds a bit more text, but not that much.

**Comment by pekkaklarck** [comment]
Why not just `${HELLO WORLD}`?
