### ISSUE TITLE
Timeout custom message needs to also indicate that it was a timeout event

### ISSUE THREAD

**Issue by dimanhsb** [robotframework/robotframework#2288]
Hello,

In a user keyword, if a [Timeout] is added with a custom message, then the error produced in case of failure does not include the fact that it is a timeout (as is down in the case of other keywords, such as "Should Contain". 

So something like:

```robotframework
*** Keywords ***
My KW
    [Timeout]  5 sec    error
    sleep  10s
```

would produce just "error" as failure reason and not something like "error - timeout in keyword 'My KW'", which would be very easier to debug.

So I propose to either append the fact that it is a timeout, or even remove the custom message feature altogether, if not many people are using it.

**Comment by pekkaklarck** [comment]
It is true that the resulting error message isn't too clear in this case. Obviously the user could have specified a better error message, but the end result is that debugging is problematic for others. This is problem was originally encountered in this kind of situation where there was extra spaces before `min`:

```robotframework
*** Keywords ***
My KW
    [Timeout]  2    min
    sleep  10s
```

**Comment by pekkaklarck** [comment]
The above examples make it clear that something must be done. We have two options:

1. Add the real timeout to the custom message as proposed in the original description.

2. Remove the support for specifying a custom timeout message altogether. I'm personally in favor of this solution because I don't see any good use cases for specifying a custom message and because it would simplify Robot's internal timeout implementation a bit. This would be backwards incompatible and thus should be deprecated first. Should also ask from users do they actually have valid uses cases for the message first.

**Comment by pekkaklarck** [comment]
I will target this issue for RF 3.0.1, but hope we can instead remove custom timeout messages altogether (#2291). In that case this issue will be closed and we need a new one about deprecating custom messages.

**Comment by pekkaklarck** [comment]
Nobody has objected removing custom timeout messages altogether. It seems it is better to deprecate them in RF 3.0.1 instead of enhancing them. See #2291 for details.

**Comment by pekkaklarck** [comment]
I submitted separate issue #2387 about deprecating custom timeout messages in RF 3.0.1. This issue can be closed.
