### ISSUE TITLE
Keyword-argument matching is case-sensitive, not documented as such

### ISSUE THREAD

**Issue by edbrannin** [robotframework/robotframework#2310]
I noticed today that both of the following are true:

1. Keyword argument matching is case-sensitive
2. The User Guide [does not mention this](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#named-argument-syntax-with-dynamic-libraries) ("case-sensitive" appears 5 times in the entire document, and none of them relate to this).

I'm not sure which of these should be changed, but because variable names are case-insensitive everywhere else I'm inclined towards parsing arguments case-insensitive except where that would cause a collision.

(I noticed this because I violated PEP 8 with a library where all the keyword arguments are `UPPER_CASE` named after database columns, but some callers were written like `upper_case=Value` and got unexpected results.)

Thoughts?

Test case:
```
*** Test Cases ***
Test Uppercase Keyword Matching
    Uppercase Keyword    BAR=1

Test Uppercase Keyword Different
    Uppercase Keyword    bar=1

Test Uppercase Keyword Camel
    Uppercase Keyword    Bar=1

Test Lowercase Keyword Matching
    Lowercase Keyword    bar=1

Test Lowercase Keyword Different
    Lowercase Keyword    BAR=1

Test Lowercase Keyword Camel
    Lowercase Keyword    Bar=1


*** Keywords ***
Uppercase Keyword
    [Arguments]    ${FOO}=${None}    ${BAR}=${None}
    Should be Equal    ${FOO}    ${None}
    Should Not Be Equal    ${BAR}    ${None}

Lowercase Keyword
    [Arguments]    ${foo}=${None}    ${bar}=${None}
    Should be Equal    ${foo}    ${None}
    Should Not Be Equal    ${bar}    ${None}
```

**Comment by pekkaklarck** [comment]
Named argument syntax is case-sensitive by design. I'm surprised if it isn't documented in the User Guide. The main reason for case-sensitiveness is the problem with a literal value like `FOO=BAR` colliding with an argument `foo`. Such collisions are possible also otherwise, but making the situation worse probably wouldn't be a good idea. This definitely needs to be documented better.

A collision can obviously occur also with a literal value `foo=bar` and an argument `foo`. A team at Nokia recently had this problem, and we agreed that it would be better if `=` would always indicate the named argument syntax and escaping like `foo\=bar` would be required when a literal value is needed. Such a change would be massively backwards incompatible, though, so it would require a very long deprecation period and probably a command line option to control the behavior during the transition time. I need to submit a separate issue about that.

**Comment by WojtekKowaluk** [comment]
Actually it is documented.

>The named argument syntax is both case and space sensitive. The former means that if you have an argument arg, you must use it like `arg=value`, and neither `Arg=value` nor `ARG=value` works. The latter means that spaces are not allowed before the = sign, and possible spaces after it are considered part of the given value.

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#named-arguments

**Comment by edbrannin** [comment]
@WojtekKowaluk Whoops, that's what I get for mainly searching "case sensitive" and "case-sensitive".  Thanks for pointing that out!
