### ISSUE TITLE
Allow templetizing a Keyword within Test Case than whole of test case

### ISSUE THREAD

**Issue by vikubel** [robotframework/robotframework#2312]
There should be a provision to  templatize a Robot Keyword than a whole test case using [Template] 
syntax.
As there are test steps which need to be repeated with arguments, but not the whole test case.

Example:

A resource file creates a Keyword in keywords.robot :

```
*** Keywords ***
Do Something
  [Arguments]    ${arg1}   ${arg2}
  Print args    ${arg1}   ${arg2}

```
A Robot test case file imports this resource and uses above keyword as:
```
*** Settings ***
Resource keywords.robot
*** Test cases ***
Some test case
   Execute test step 1
   Execute test step 2
   Execute test step 3
   #Now use the Keyword defined in resource file with [Template]
   Do Something
   [Template]
    1   2
    3   4

   Execute test step 4

```

This way, I can use Keyword "Do Something" with data driven arguments in other test cases as well.

This is a requirement arised when I was automating a UI flow, where UI allows creating a user and allows him multiple Admin Roles like System admin, Role Admin, User Admin etc. which needs to be selected differently for different users.

Having above feature would ease the programming in RF.

Thanks
Vivek

**Comment by pekkaklarck** [comment]
I don't see much benefits in having tests that contain both workflow and data-driven parts. In your example it would be easy to create a test setup that does the needed pre-condition steps and use the currently supported data-driven approach to define the actual test case. If you'd rather want to use the workflow approach, you could just call the needed keyword few times explicitly like

    Do Something    1    2
    Do Something    3    4

Another problem with this proposal is that it would either require some new syntax or would change the current template usage in backwards incompatible manner. Both can only be considered if there are really big benefits otherwise.
