### ISSUE TITLE
`robot` and `rebot` scripts cannot be used with multiprocessing module

### ISSUE THREAD

**Issue by cleopold** [robotframework/robotframework#2315]
If you use the multiprocessing module in a library, and set it to use the spawn method instead of fork, the entrypoints get re-executed.  Entry scripts need the entry point to be wrapped with:

`if __name__ == '__main__':`

Pull request submitted #2314

**Comment by pekkaklarck** [comment]
Sounds reasonable. We have added similar guards, for example, to `robot.run` and `robot.rebot` modules that can also be executed as scripts. By the way, have you tried using these modules instead of `robot` and `rebot` start-up scripts?

**Comment by cleopold** [comment]
Only as a by product of running it on windows platforms where the .bat entry scripts call the `robot.run `and `robot.rebot` modules.  And it works fine on those platforms because of those guards.

**Comment by pekkaklarck** [comment]
Is there a reason you don't use those modules everywhere? They provide the main programmatic interface to run tests and use Robot otherwise. `robot` and `rebot` scripts are targeted for command line execution.

**Comment by cleopold** [comment]
Mostly because we do execute from the command line a fair amount.  Either from Jenkins or sometimes manually.

**Comment by pekkaklarck** [comment]
Oh, I thought you'd distribute Python functions with multiprocessing. Anyway, adding these guards is so simple that I don't see harm adding them.

I do think we should add them only to `robot` and `rebot` scripts, though. Others will be removed in the future anyway, and if someone needs these guards they must use a version that contains the new `robot` script anyway. Even better if this is a reason for someone to switch to use `robot` instead of `pybot`.

**Comment by cleopold** [comment]
yea we have multiprocessing stuff in libraries.  Thanks!
