### ISSUE TITLE
`Exit/Continue For Loop` does not work with continuable failures in user keywords

### ISSUE THREAD

**Issue by gliviu** [robotframework/robotframework#2318]
Consider this example
```robot
*** Test Cases ***
Test1
    ${list}    Create List    k21    k22    k23
    k2    ${list}

*** Keywords ***
k2
    [Arguments]    ${list}
    ${length}    Get Length    ${list}
    :FOR    ${i}    IN RANGE   0    ${length}
    \    ${val}    Set Variable    ${list[${i}]}
    \    ${res}    Exit for loop if errors    Run Keyword If    '${val}'=='k22'    Fail   This is a failure

Exit for loop if errors
    [Arguments]    ${name}    @{args}
    ${error}    ${res}    Run Keyword And Ignore Error    ${name}    @{args}
    Run Keyword If    '${error}'=='FAIL'    Run Keyword And Continue On Failure    Fail    ${res}
    Exit For Loop If    '${error}'=='FAIL'
    [Return]    ${res}
```

It is supposed to exit the the iteration once the second item (k22) is processed. It doesn't:
![image](https://cloud.githubusercontent.com/assets/8597812/13216646/b9226318-d965-11e5-9eaf-570f27dbace6.png)

If I comment line 'Run Keyword If    '${error}'=='FAIL'    Run Keyword And Continue On Failure    Fail    ${res}' the loop exits properly:
![image](https://cloud.githubusercontent.com/assets/8597812/13216657/c768f0ea-d965-11e5-9d63-b839c426c503.png)

The same issue is valid for Continue For Loop If

**Comment by gliviu** [comment]
Seems to work fine if Exit For is not nested within another keyword:
```
*** Keywords ***
k2
    [Arguments]    ${list}
    ${length}    Get Length    ${list}
    :FOR    ${i}    IN RANGE   0    ${length}
    \    ${val}    Set Variable    ${list[${i}]}
    \    ${error}    ${res}    Run Keyword And Ignore Error    Run Keyword If    '${val}'=='k22'    Fail   This is a failure
    \    Run Keyword If    '${error}'=='FAIL'    Run Keyword And Continue On Failure    Fail    ${res}
    \    Exit For Loop If    '${error}'=='FAIL'
```

**Comment by pekkaklarck** [comment]
Which RF version? If not 3.0, could you test with it?

**Comment by gliviu** [comment]
tested with robotframework-3.0.jar

**Comment by pekkaklarck** [comment]
I can reproduce the problem and after a little investigation also found the root cause. As @gliviu already noticed, the problem only occurs if `Exit/Continue For Loop` is used in a user keyword so that there is a continuable failure before.

In practice this code basically ignores the occurred `Exi/ContinueForLoop` error:
https://github.com/robotframework/robotframework/blob/master/src/robot/running/userkeywordrunner.py#L145

It ought to be enough to add this before the line referenced above:

```python
        except (ExitForLoop, ContinueForLoop) as exception:
            pass_ = exception
```

I don't want to commit these changes without writing some tests and I don't have time for that right now.
