### ISSUE TITLE
robot.libdoc does not work correctly with Python classes

### ISSUE THREAD

**Issue by pdjouob** [robotframework/robotframework#2324]
The generation of HTML documentation of a python library containing classes no longer works.
The fields (Keywords, Arguments, Documentation) in the descriptor table are empty.

> Nevertheless, it works for Python libraries that do not contain classes

**Context :**
- Version of robotframework used: **2.9.2**
- Executed command: _python -m **robot.libdoc** /example of url below/ **mytestdoc.html_**
- Example: https://robotframework.googlecode.com/svn/trunk/tools/libdoc/doc/libdoc.html#python-libraries

**Comment by pekkaklarck** [comment]
First of all, that doc you referred is totally outdated. See the User Guide for up-to-date Libdoc docs. Second, without you telling what you actually did it is impossible to help you.

**Comment by pdjouob** [comment]
Thank you for your reply.
Sorry, as much for me.
There was a mistake in my command. :-)

Here is my example code (TestLibrary.py):
           
         class MyTestLibrary:
                 """My Library .
                 = Table of contents =
                 - `content one`
                 - `content two`

                 = content one =
                 = content two =
                 """
             def fonction_one():
                    """Documentation
                    """
                    pass
             def fonction_two(arg):
                      """ Documentation and usage of this fonction
                      Examples:
                      | =Setting= |     =Value=    | =Value= |          =Comment=  |
                      """
                      pass
             def fonction_three(arg):
                     """ Documentation and usage of this fonction
                     Examples:
                     | =Setting= |     =Value=    | =Value= |          =Comment= |
                     """
                     pass

The command I executed was:
**python -m robot.libdoc TestLibrary.py TestLibrary.html**
Here my doc generated was empty
In fact the name of the class was not passed as a parameter.

The following command works correctly:
**python -m robot.libdoc TestLibrary.MyTestLibrary TestLibrary.html**

**Comment by pekkaklarck** [comment]
This is the expected behavior. In the former case Libdoc considers TestLibrary module to be a library exactly like when Robot does when running tests. If you change the class name to match the module name also the former works. This is discussed in more detail in the User Guide. Could you check is the documentation adequate or could it be enhanced?

It is obviously a small limitation that class name and modume name must match when importing libraries using a path. So far nobody has needed it that badly nor come up with a syntax to specify the class name as part of the path.
