### ISSUE TITLE
Why should I import sub modules of variables in Library file?

### ISSUE THREAD

**Issue by frostming** [robotframework/robotframework#2331]
I am using robotframework 2.8.5 on python2.6. I defined my variables in a python module **UserVar** with several sub modules and Import the **UserVar** in Variables, but when I try to use a variable under sub module it throws an error Non-existing variable. I have to import the submodule in Library file.
**MyLibrary.py**
```python
from UserVar import SubVar

class MyLibrary:
    pass
```
**TestCase.txt**
```robot
*** Settings ***
Library        MyLibrary
Variables      UserVar

*** Test Cases ***
TestCase
    My Keyword    ${SubVar.my_var}
```
I didn't find it in documents, any help is appreciated.

**Comment by frostming** [comment]
The order of Library and Variables makes difference, if I put Variables before Library, it throws the same error.

**Comment by pekkaklarck** [comment]
Can you provide an executable example demonstrating this problem?

**Comment by frostming** [comment]
I have `MyLibrary.py` to store my keywords, and a `UserVar` module which contains multiple `.py` files together with `__init__.py`, both `MyLibrary.py` and `UserVar` are under my PYTHONPATH.

It doesn't work until I put `from UserVar import xxx` in `MyLibrary.py`.

**Comment by pekkaklarck** [comment]
I still don't understand what you are trying to do. Unless you provide a simple executable example demonstrating the problem, I cannot really help. See http://sscce.org/.

**Comment by frostming** [comment]
[Here](https://gist.github.com/frostming/2f66506c03d782837922cea61741f7be) is the code snippet to reproduce this issue, hope this is clear.

**Comment by pekkaklarck** [comment]
This problem is caused by how Python imports packages. When you have `Variables    UIVariables` in your test data, it is equivalent to `import UIVariables` in Python which *does not* import the `MainFrame` submodule and thus `UIVariables` doesn't have `MainFrame` attribute. When you add `from UIVariables import MainFrame` to your library, it imports the `UIVariables` module and its `MainFrame` submodule. Although you don't get `UIVariables` into the importing namespace, already elsewhere imported `UIVariables` package gets `MainFrame` attribute too. This can be reproduces in the Python interpreter:

```python
>>> import UIVariables
>>> UIVariables.MainFrame
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'MainFrame'
>>> from UIVariables import MainFrame
>>> UIVariables.MainFrame.title
'Main Window'
```

How to avoid problems caused by this somewhat weird behavior? Just add `from . import MainFrame` into your `UIVariables/__init__.py`.
