### ISSUE TITLE
RobotFramework 2.9.2 timing issues

### ISSUE THREAD

**Issue by niravsh** [robotframework/robotframework#2334]
Hi,
I have a test which is time sensitive as it is used to spoof button presses (100ms resolution). My keyword resources work fine with RobotFramework 2.8.5 but when I upgrade to Robotframework 2.9.2 I have seen that the keyword takes 250ms to execute instead of 100ms. Looking at the logs it seems that parent keyword's time taken (250ms) is not the sum of execution time of all child keywords (actual sum is 120ms). I also noticed that before child keyword was called within 10ms of calling the parent keyword but with new framework version it takes the parent keyword 45ms to call the child keyword with no other operation to perform. 

Why is that Framework takes so much time to call/start the child keyword ? 

This discrepancy breaks my tests as button presses are no longer replicated.

Thanks.

**Comment by niravsh** [comment]
Has something changed from robotframework 2.8.5 and 2.9 w.r.t. the way framework handles resource imports ? Can that be a reason that delay is because of getting keywords access ?

**Comment by pekkaklarck** [comment]
There were performance regressions in RF 2.9. Lot of improvements then in RF 3.0. Please test with that version and see how it behaves in your case.

**Comment by niravsh** [comment]
I upgraded to RF 3.0 and yet cannot get around the timing mistmatches. I have a keyword which have 13 if else conditions with Run keyword IF builtin keyword. This operation earlier use to take less than 50ms but now it take almost 300 ms. Any idea? I have python 2.7.10 on win32 and am checking to see if win 64 python would improve performance here.

**Comment by niravsh** [comment]
Attaching log files in pdf format here. With old robotframework version BuiltIn keyword operation took almost no time while now they take around 200ms extra. This is one of the instances I am posting.  I do have keywords taking much longer to call child keywords (~30ms per call) which induces over 100ms delay when having a 3 layer call. Unable to spoof button presses with this additional delay of 300ms 

[LOG_RB2_8_5.pdf](https://github.com/robotframework/robotframework/files/166199/LOG_RB2_8_5.pdf)
[LOG_RB3_0.pdf](https://github.com/robotframework/robotframework/files/166198/LOG_RB3_0.pdf)

**Comment by pekkaklarck** [comment]
I don't have time to look at the logs or to study this otherwise at the moment, but I can believe that later RF versions are slower that older in certain cases. It is very unfortunate that such a case causes problems for you. What you can do include the following:

- Keep using the older versions that are faster in your use case.
- Move complex logic like 13 if else conditions to a library.
- Investigate why later versions are slower and try enhancing the speed.
- Pay me or someone else to do the aforementioned investigation.

**Comment by pekkaklarck** [comment]
I tested this myself and noticed that `Run Keyword If` is, indeed, about three times slower in RF 3.0 than in RF 2.8.x. This slowdown seems to be caused by enhancements to evaluating expressions (#2040), 
and looking at the code I couldn't find any easy way to enhance the performance.

It is unfortunate that performance has got worse in this regard, but the aforementioned enhancements are, in my opinion, much bigger than the caused problems. I'm still able to run `Run Keyword If` with about 250 `ELSE IF` conditions in 0.1 seconds on my machine so the performance is not that bad. If you must have better performance, I recommend you to move the logic to  a custom test library.

**Comment by pekkaklarck** [comment]
This was important for a paying customer later and was investigated and fixed in RF 3.0.2 (#2523).
