### ISSUE TITLE
Getting Started guide has broken images

### ISSUE THREAD

**Issue by codemedic** [robotframework/robotframework#2337]
It seems they have broken links.

PS: Logging an issue so that I can have a hack at fixing them.

**Comment by codemedic** [comment]
Before I make a fool of myself; are these broken because of the requirement to be able to generate rendered documentation using another tool of some kind ?
If so; is it at all possible to make it compatible with the rendering on github?

**Comment by pekkaklarck** [comment]
Could you please clarify? Which guide? Which images?

**Comment by codemedic** [comment]
@pekkaklarck I did see a few while browsing around within the repo.
For example, the [images here](https://github.com/robotframework/robotframework/blob/master/doc/userguide/src/ExecutingTestCases/OutputFiles.rst#log-file)

**Comment by pekkaklarck** [comment]
You are looking at the reST source files of the User Guide. I think images there are relative to the `ug2html.py` script that is used to generate the User Guide. You can find the generated version online here:
http://robotframework.org/robotframework/#user-guide

In general it would be a good idea to convert the User Guide to use [Sphinx](http://www.sphinx-doc.org) instead of our custom doc generator, but that's definitely a topic for a separate issue.
