### ISSUE TITLE
Extend Libdoc to contains information about line and source, where keyword is defined

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2350]
It will be very useful to get in libdoc generated by `robot.libdoc` information about files and lines, where library keyword is defined.

**Comment by pekkaklarck** [comment]
Could you clarify use cases for this kind of functionality? I doubt normal users are so much interested in the source code in general, and adding this kind of information for every keyword would take quite a bit of space.

Adding a link to the library code into the header along with library version and other generic information would be OK, but linking to the local library wouldn't help much docs are hosted online. For example, [BuiltIn](http://robotframework.org/robotframework/latest/libraries/BuiltIn.html) containing a link to the local library version on the machine where the docs were generated wouldn't be useful. Having a link to the [source code online](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/BuiltIn.py) would be nice, but I don't think there's any way to add it automatically. Libdoc accepting free metadata in name:value format would make that possible, though.

**Comment by adam-wypych** [comment]
Hello Pekka,

Originally the request was made by testers, which are more or less experience with Python. Currently in the RED we are supporting for source code libraries just jump to library file without move just to line, where keyword exists, so I wonder if is possible to extend current libdoc generated to have information `file_as_URI:line_number` per keyword. Mostly users interested in got information about own libraries and I do not see such requests for RF or `Remote` libraries.

Thanks in advance!

**Comment by pekkaklarck** [comment]
I still don't see how this would work in practice. If you have a better idea, please try implementing it and providing a PR. Things to take into account:

- Where to show the information in HTML without wasting too much space?
- How to enhance internal model to contain this information?
- Should this information be written also to XML files produces by Libdoc? If not, Libdoc cannot anymore use those XML files as inputs like it can nowadays.
- How to handle libraries using the dynamic API?
- How to handle libraries implemented using Java?

Finally, this functionality should not be on by default to avoid adding information that may not be useful and will only work if the relative path to the library source code doesn't change.

Notice also that instead of enhancing Libdoc, you could consider using normal Python API doc generators like Sphinx or Epydoc. They ought to support linking to source out-of-the-box or via plugins already.

**Comment by adam-wypych** [comment]
Thanks for Your point. The request was made for libraries means Java classes or Python files, so I agree that made it for resource files is not economical and waste of time (since even RED support it nowdays). The output should be only for libspec made in XML as I see even RIDE only supports description made in XML format. 

About other tools I am not sure, if they will works with dynamic libraries and keywords with decorators (`robot.api.deco`).

Anyway if You see any misunderstanding in this concept I am open for Your valueable opinion to decrease possibility to waste of time sth which will be completly out of RF concept.

**Comment by pekkaklarck** [comment]
I still don't fully understand the use case for this functionality nor how it should actually work. Would you @adam-wypych be interested to implement a prototype so that we can see it practice? If we then agree about the functionality, then we can start thinking how the issues I listed above can be taken into account.

**Comment by adam-wypych** [comment]
@pekkaklarck Yes I am interested to implement some kind of prototype.

**Comment by pekkaklarck** [comment]
Do I get it right that in your use case you'd just want line numbers in XML to enable navigating to correct line in the library and aren't even interested in HTML? In that case I seriously think implementing a custom tool for your needs is a better solution that trying to enhance Libdoc. Libdoc's main output is HTML and I'm not too interested to add complex functionality that doesn't benefit HTML output at all. I would like Libdoc also to work similarly with different library types, but this functionality could only be supported by some library types.

Do you have reasons why a custom tool wouldn't work for you? Such a custom tool could obviously use Libdoc's APIs, and we could expose more APIs for you if needed.

**Comment by adam-wypych** [comment]
@pekkaklarck I get Your point regarding output, but as I remember in the Libdoc tool is not so big deal to implement different type of output to be produce. Both XML and HTML use the same data model and only needs is to extend HTML output producing builder (called writer) - event types are similar because HTML is kind of XML.  

I do not fully get Your point regarding: _"I would like Libdoc also to work similarly with different library types, but this functionality could only be supported by some library types."_ I tried to cover all types of library including these with decorators, hybrid and dynamic. I tried to focus on Java and Python language of course maybe IronPython developers will be a little bit confuse, but dealing with C# DLL unmanaged code is horrible thing, if event RF can handle them.

I raise this ticket, because I see that RF has pretty good libdoc generator and You as RF developers knows what exactly is keyword and the name of them. Additionally You are able to build correct paths, which will be used during execution time. I am open for API points to put some kind of extender of model build during Libdoc is running, but the question is if it will beneficiary for everybody to it for himself?

If You decide to go with API, I also see that is possible to have some kind of extender, which will be called during `KeywordDoc` model building, basically during call of `javabuilder.py -> def _keyword_doc(self, method):` and `robotbuilder.py -> def build_keyword(self, kw):`. With possibility to store what he want in `KeywordDoc` and then during write process to HTML, XML will happen those additional fields to be stored.

**Comment by pekkaklarck** [comment]
The main problems I see are these:

1. I don't know where in HTML docs the line numbers should be shown. Perhaps even more importantly, I doubt anyone reading HTML docs would be interested.

2. Implementation is too complicated and uses too much Robot's internal APIs that are going to change in the future. I have zero interest to maintain this code when that happens.

3. It isn't in general possible to get actual line numbers from dynamic methods unless we add a separate dynamic method for that purpose into the dynamic library API. What you can get is the location of the `run_keyword` method, but linking all keywords to that makes no sense.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I decided I don't want to add this functionality into Libdoc. As I commented above, it's not a feature normal Libdoc users would need, implementation is complex, and it isn't possible to implement this in generic manner with all supported library types.

I propose you implement a custom tool that provides what information you need. Then you don't need to care about HTML output or supporting all library types. As I've already commented, you can use Libdoc's APIs in your tool, and new public APIs can be added to Libdoc and Robot if needed (and if that isn't too complicated). In addition to Libdoc, or perhaps instead of it, you could use Python's `inspect` module which provides means to [get source lines and line numbers](https://docs.python.org/2/library/inspect.html#retrieving-source-code). I'm fairly sure Javadoc has similar functionality you could then use with Java based libraries if needed.
