### ISSUE TITLE
robotframework error installation on python 3.4

### ISSUE THREAD

**Issue by vkosuri** [robotframework/robotframework#2372]
I am trying install robotframework on Python 3.4 it produces some errors, Please find below stack trace

However it said the **installation completed successfully**.  When i am trying to execute my testcase, i am seeing many errors with ```NameError: name 'unicode' is not defined```

``` Shell
(myenv) mkosuri@evolet:~/yang_gen/robotframework-requests$ pip install robotframework
Downloading/unpacking robotframework
  Downloading robotframework-3.0.tar.gz (430kB): 430kB downloaded
  Running setup.py (path:/home/mkosuri/yang_gen/myenv/build/robotframework/setup.py) egg_info for package robotframework

    no previously-included directories found matching 'src/robot/htmldata/testdata'
Installing collected packages: robotframework
  Running setup.py install for robotframework
    changing mode of build/scripts-3.4/pybot from 664 to 775
    changing mode of build/scripts-3.4/robot from 664 to 775
    changing mode of build/scripts-3.4/rebot from 664 to 775
      File "/home/mkosuri/yang_gen/myenv/lib/python3.4/site-packages/robot/running/timeouts/ironpython.py", line 57
        raise self._error[0], self._error[1], self._error[2]
                            ^
    SyntaxError: invalid syntax

      File "/home/mkosuri/yang_gen/myenv/lib/python3.4/site-packages/robot/running/timeouts/jython.py", line 56
        raise self._error[0], self._error[1], self._error[2]
                            ^
    SyntaxError: invalid syntax


    no previously-included directories found matching 'src/robot/htmldata/testdata'
    changing mode of /home/mkosuri/yang_gen/myenv/bin/pybot to 775
    changing mode of /home/mkosuri/yang_gen/myenv/bin/robot to 775
    changing mode of /home/mkosuri/yang_gen/myenv/bin/rebot to 775
Successfully installed robotframework
Cleaning up...
```

After running my testcase it says ```NameError: name 'unicode' is not defined```
Here is my testcase

``` Robot
Delete Request With Data
    [Tags]  delete
    Create Session  httpbin  http://httpbin.org    debug=3
    &{data}=  Create Dictionary  name=bulkan  surname=evcimen
    ${resp}=  Delete Request  httpbin  /delete  data=${data}
    Should Be Equal As Strings  ${resp.status_code}  200
    Log  ${resp.content}
    Comment  Dictionary Should Contain Value  ${resp.json()['data']}  bulkan
    Comment  Dictionary Should Contain Value  ${resp.json()['data']}  evcimen
```

Are there anything we are missing/needs to change our testcase.

**Comment by pekkaklarck** [comment]
This is a weird problem. I got no problems when using Python 3.4 directly on Linux (`sudo python3.4 -m pip install robotframework`) but I get the exact same problem when trying to install into a virtual environment created using Python 3.4. Need to investigate why that happens.

**Comment by pekkaklarck** [comment]
I'm able to reproduce your installation problem when using a virtual environment created with Python 3.4 on Linux. It seems that all of the code is byte compiled and some code that only should be run with Python 2 causes issues. Interestingly I got no problems whatsoever when using Python 3.4 directly without virtual environments. I'll investigate the venv installation issue a bit more and report findings here.

Actually running tests seems to work fine also after I got those errors during installation. Could it be that the library you are trying to use is not Python 3 compatible?

**Comment by pekkaklarck** [comment]
The installation problem really seems to be caused by pip byte compiling all `*.py` files to `*.pyc` automatically as part of installation. Luckily we don't need to care about it too much:

- These errors don't cause any problems when running tests. When you run Robot on Python 3 these files containing Python 2 syntax are never imported.

- If you want to avoid the errors anyway, you can simply use `--no-compile` option to avoid byte compilation altogether. In this case byte compilation occurs automatically when you run Robot for the first time.

- The actual problem in pip seems to be already fixed. I didn't get this error when testing a virtual environment created with Python 3.5 (it has a newer pip) and after upgrading pip in Python 3.4 venv the problems disappeared too.

I'm also fairly certain that the problem you encountered when running tests is caused by Python 3 incompatibility in the library you use. If you think it is not, please submit a new issue with an example demonstrating the problem.
