### ISSUE TITLE
pybot doesn't see libraries in virtualenv

### ISSUE THREAD

**Issue by cristovaopoland** [robotframework/robotframework#2395]
Hi,
I'm using virtualenv. All of my python modules (libraries for robot) are visible in sys.path.
While trying to use those modules I recive that I cannot import module.
The only help is when I put sys. paths into PYTHONPATH - from this point everything works.

**Comment by pekkaklarck** [comment]
This sounds like a configuration problem in your virtualenv. Are those modules available in the venv when not using Robot?

**Comment by cristovaopoland** [comment]
Yes. When my virtualenv is active all of the modules are available thru command line and pycharm.  
I could not find an information. Do rf only look on pythonpath when imports modules? Sys path is not taking into account?

**Comment by pekkaklarck** [comment]
Robot uses Python's `__import__` function for importing libraries. It ought to look from `sys.path` similarly as any other import. Notice that `PYTHONPATH` just specifies extra locations that Python adds to `sys.path` automatically.

I'm still fairly convinced that the issues is in your venv configuration. I know others are using Robot with venvs so that support cannot be totally broken. If you are certain that the problem is in Robot, you need to provide us detailed instructions how to reproduce the problem.

**Comment by cristovaopoland** [comment]
Ok, so thank you for info that this should works. In this case I will close this issue and investigate it more - in case I will be sure it is issue with robot I will reopen it. Thank you for your information.
