### ISSUE TITLE
Times in xUnit outputs should be floats not integers

### ISSUE THREAD

**Issue by mverma-va** [robotframework/robotframework#2397]
I noticed that the current xunit xml report file only shows time in seconds and does not have milliseconds component to it. So for some of the testcase which just finishes in say 330ms it shows 0; 660ms shows 1 (not sure about the rounding off), but it just shows seconds.
example: 

<testcase classname="Tests.User" name="Read Single User" time="1"> </testcase>

It would be useful if we shows the time in milliseconds or in seconds with fractions ms, like time="1.182"
See attached report.xml file generated using --xunit flag (i have to change the file to .txt for attaching)
[report_xml.txt](https://github.com/robotframework/robotframework/files/314919/report_xml.txt)

**Comment by pekkaklarck** [comment]
This definitely sounds reasonable. I guess the reason we have used integers earlier is that the files we used as examples when designing out xunit format used integers. As discussed in #2292, it is highly annoying that there is no official xunit/junit format specification available. Based on your knowledge, do other tools write times as integers or as floats?

The main problem with changing the time format is backwards compatibility. It is possible that some external tools or custom utilities parse times as integers and changing them to floats causes problems. If other tools already produce xunit files with floats, the problem with external tools ought to be pretty small, and fixing custom tools to parse times as floats isn't a big problem either.

My current thinking is that the behavior should be changed, but because of the backwards compatibility concerns we cannot do that in RF 3.0.x releases but need to wait for RF 3.1. We allow backwards incompatible changes in major releases, and doing this early in the RF 3.1 development cycle allows getting feedback from users during alpha and beta period.
