### ISSUE TITLE
Underscores should not be replaced with spaces in values given from command line

### ISSUE THREAD

**Issue by florentaumaitre** [robotframework/robotframework#2399]
Robot Framework 3.0 (Python 2.7.10 on win32)

When adding metadata with rebot, underscore in URL are replaced by space :

`rebot -M mymetadata:http://path_with_underscore output.xml`

In report, i have:
mymetadata:     [http://path](http://path) with underscore

**Comment by pekkaklarck** [comment]
It's a [designed and documented feature](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#setting-metadata) underscores are converted to spaces when setting documentation and metadata with `--doc` and  `--metadata` options. I'm first to admit the design is not good, though.

The motivation has been making it easier to use spaces in these values, but that added convenience is not worth making it impossible to use actual underscore in values. If spaces are needed, it is possible to quote values (e.g. `--doc "Hello, world!"`) or use the `--escape` option (e.g. `--escape space:_ --doc Hello_world!`.

Although I think this should be changed, we cannot change it in RF 3.0.x releases due to backwards compatibility concerns. Changing it in RF 3.1 is possible, though.

**Comment by pekkaklarck** [comment]
This seems to affect even more command line options than I thought. This ought to be a full list:

- `--name`
- `--doc`
- `--metadata`
- `--tagdoc`
- `--tagstatcombine`
- `--logtitle`
- `--reporttitle`
