### ISSUE TITLE
Namespace is not removed when parse xml with lxml library

### ISSUE THREAD

**Issue by Felys** [robotframework/robotframework#2409]
Original discussion in https://groups.google.com/forum/#!topic/robotframework-users/pNdU51HXnQc

When using lxml library and parse xml, namespaces are included when you `get element` from specific xpath. This does not occur when use standard ElementTree module (aka. `use_lxml=False`)

Can be reproduce by following data

``` xml
<feed xmlns:verr="http://www.xyz.com/error" xmlns:vaext="http://www.xyz.com/atom-ext" xmlns="http://www.w3.org/2005/Atom">
<example>
  <first id="1">text</first>
</example>
</feed>
```

This is test case

```
*** Setting ***
Library  XML  use_lxml=True

*** Variables ***
${xml}  test.xml

*** Test Cases ***
test 1
   ${root}=  parse xml  ${xml}
   ${elem}=  get element  ${root}  example/first
   log element  ${elem}
```

When `log element` is executed, result is

``` xml
<first xmlns:verr="http://www.xyz.com/error" xmlns:vaext="http://www.xyz.com/atom-ext" xmlns="http://www.w3.org/2005/Atom" id="1">text</first>
```

instead of

``` xml
<first id="1">text</first>
```

Output of `parse xml` on lxml and ElementTree library should be the same.

Version information
- Robot Framework 3.0
- Python 2.7.11
- Windows 7

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

Including namespace information in child elements seems to be a feature in lxml and avoiding that doesn't seem to be easy. Instead of that, I think it is better to add new `strip_namespaces` argument to `Parse XML` to allow stripping namespaces altogether and I already submitted #2534 about that.

With #2534 implemented, the problem in this issue can be avoided easily and I think this issue can be closed. Comment here if you disagreee and have use cases where the new functionality wouldn't work.
