### ISSUE TITLE
"Wait Until Text is not visible" or "Wait Until Page Does Not Contain"

### ISSUE THREAD

**Issue by Alexey-Stepanov** [robotframework/robotframework#2410]
When I am using the Selenium2Library keyword Wait Until Page Does Not Contain  ${text}
I get the error:
Text 'You don't see this text' did not disappear in 5 seconds
Yes, it is present but not visible

`<section id="blablabla" style="display: none;">You don't see this text</section>`

What do you mean by "Page Does Not Contain"?
Is it possible to add new keyword  "Wait Until TEXT is not visible"?

**Comment by CCallanBase2** [comment]
It is "possible" to create a new keyword that would encapsulate that functionality, but since the API has gotten along this long without it then the case could be made that this functionality isn't in high demand.
A possible workaround I can see for this is to create your own user-defined keyword that wraps the "Wait Until Page Contains" immediately followed by "Element Should Not Be Visible".  Like: 
_**Wait Until Page Text Is Not Visible    ${inputtext}
    Wait Until Page Contains    ${inputtext}    5 seconds
    Element Should Not Be Visible    //section[text()=$inputtext]**_
I'm not sure I got the above syntax 100%, but it should be close enough to get the idea.

**Comment by pekkaklarck** [comment]
Selenium2Library issues belong to its own tracker. Questions are best sent to robotframework-users or other such forums.
