### ISSUE TITLE
rebot combined report using multiple output*.xml failing with ParseError: mismatched tag: line 169, column 66

### ISSUE THREAD

**Issue by sivassrr** [robotframework/robotframework#2414]
Had 10 output xml file named as follows:
output0.xml
output1.xml
output2.xml
output3.xml
output4.xml
output5.xml
output6.xml
output7.xml
output8.xml
output9.xml

When I tried to run following rebot command, I get below error
rebot --name  barreleyeCombinedReport  output?.xml
[ ERROR ] Reading XML source 'output5.xml' failed: ParseError: mismatched tag: line 169, column 66

Try --help for usage information.

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

The problem isn't related to using multiple output files. As the error you included says, parsing output5.xml fails because it has mismatched tag. With this information alone it's impossible to know why that output file is corrupted, but often this kind of failures are somehow related to using threads.

If this error still occurs, please submit a new issue. Without having an example that I can use to reproduce this on my own machine debugging the problem is pretty hard, though.
