### ISSUE TITLE
robot 2.9.1 variable issue

### ISSUE THREAD

**Issue by emilyfcj** [robotframework/robotframework#2424]
case run in 2.8.6 OK
but failed in 2.9.1 for variable can't distinguish with wireshardserverinfo and WIRESHARKSERVER_INFO

case content:
*** Settings ***
Variables         Variable.py

*** Variables ***
@{wiresharkserverinfo}    1    2    3

*** Test Cases ***
test
    log    ${WIRESHARKSERVER_INFO.IP}

Varialbe.py content:

WIRESHARK_INFO = {"IP" : "10.69.24.114",
                        "PORT" : "23",
                        "USERNAME" : "root",
                        "PASSWORD" : "111",
                        "LOGNAME" : "Wireshark_log_Test"}

**Comment by pekkaklarck** [comment]
This problem is due to list and scalar variables being stored in the same namespace since RF 2.9. Variable names are case, space and underscore insensitive and thus `@{wiresharkserverinfo}` and `${WIRESHARKSERVER_INFO}` collide. For more details see issue #1905 and RF 2.9 release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-2.9.rst#list-and-scalar-variables-stored-in-same-namespace
