### ISSUE TITLE
Ensure `args` passed to `start/end_keyword` listener methods are always strings

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2428]
It was found by bugs: https://github.com/nokia/RED/issues/32 and https://github.com/robotframework/Selenium2Library/issues/542 that parameter `args` defined inside `start_keyword` and `end_keyword` is not really list of string (like it is stated in http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id760), but list of object in some cases. 

For prove this You can just use my example here: https://github.com/nokia/RED/issues/32#issuecomment-240936833 .

**Comment by pekkaklarck** [comment]
First of all, sorry for ignoring this issue for so long. It was buried under a pile of other issues during summer time when I didn't have much time to follow this tracker.

Arguments passed to `start/end_keyword` are strings with possible variables not being resolved when keywords are used normally in the test data. As you example demonstrates, arguments can be any objects if you use `BuiltIn.run_keyword` internally in your keyword. Instead of updating the docs, I would say it's better to convert these arguments into strings before calling the listener method.
