### ISSUE TITLE
OperatingSystem: Run keyword can't handle doublequoted string correctly

### ISSUE THREAD

**Issue by lushiwei** [robotframework/robotframework#2441]
Robot Framework version: 2.9.2
Java: 1.7.0_45
Operating System: Windows 7

I tried to run the following test case with standalone JAR distribution robotframework-2.9.2.jar, but got some errors in the output. 
This test case works on older version 2.8.6 correctly, could you help to have a look?

```
${rc}     ${output} =     Run and Return RC and Output     echo "a|b"


Starting test: Test.T2
20160906 13:42:04.618 :  INFO : Running command 'echo "a|b" 2>&1'.
20160906 13:42:04.655 :  INFO : ${rc} = 255
20160906 13:42:04.657 :  INFO : 
${output} = 'b' is not recognized as an internal or external command,
operable program or batch file.
Ending test:   Test.T2
```

**Comment by pekkaklarck** [comment]
I can reproduce this on Windows with Jython using RF 3.0. Works fine with Python on Windows and both with Python and Jython on Linux. Interestingly I also get the same error with RF 2.8.6 when using Jython 2.7. This indicates that the problem is caused by Jython 2.7 and not by changes to Robot Framework itself. `robotframework-2.8.6.jar` still contains Jython 2.5 while `robotframework-2.9.jar` and newer contain Jython 2.7.

I can investigate this a bit more when I have time and see if we could workaround the issue somehow. I'd also like to reproduce the problem with Jython alone to be able to report it to http://bugs.jython.org.

**Comment by pekkaklarck** [comment]
Unfortunately don't have time to investigate this before 3.0.1.

**Comment by pekkaklarck** [comment]
Jython clearly doesn't handle quoting exactly right when running this command on the command line. Part of the problem is the Windows command line itself, where the quoting rules are pretty strange. This particular problem has a workaround to escape the problematic pipe character with a caret like `a^|b`. This is explained, for example, here http://stackoverflow.com/questions/1200235/how-to-pass-a-quoted-pipe-character-to-cmd-exe

This problem only occurs when running commands on a Windows shell and apparently only if using shell commands like `echo`. The problem is on Jython, and I don't think it makes sense to try adding a workaround for it on Robot side. You may want to consider submitting an issue to http://bugs.jython.org, though. This is how it can be reproduced:

```
C:\Users\peke>python
Python 2.7.10 (default, May 23 2015, 09:44:00) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.popen('echo "foo|bar"').read()
'"foo|bar"\n'
>>> ^Z


C:\Users\peke>jython
Jython 2.7.0 (default:9987c746f838, Apr 29 2015, 02:25:11)
[Java HotSpot(TM) Client VM (Oracle Corporation)] on java1.8.0_121
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.popen('echo "foo|bar"').read()
'bar' is not recognized as an internal or external command,
operable program or batch file.
''
>>>
```
