### ISSUE TITLE
Keywords with &{arguments} should collect required arguments before keyword-arguments

### ISSUE THREAD

**Issue by edbrannin** [robotframework/robotframework#2463]
For keywords that accept keyword-arguments, Robot (2.9.2 & 3.0) currently gobbles up any keywords with un-escaped `=` _before_ assigning any left-over variables to the positional arguments.  I think it should account for the number of mandatory positional arguments before splitting the remaining arguments on `=`.

This mostly matters when the positional argument is an xpath or SQL query.

I realize:
- The current workaround is to escape any `=` like `\=`.
- This could be a breaking change for any test suites that are already doing the workaround.

...but I still think the benefits could outweigh the cost.  I'm guessing this doesn't come up very often yet, but it will be an issue for my team once we start using [a database library that supports named bind-variables](https://github.com/edbrannin/Robotframework-SQLAlchemy-Library/).

Reproducing test case:

``` robot
* Test Cases *
Should Process Required Arguments Before Keyword args
    Print SQL    select name from users where id=:id    id=1

* Keywords *
Print SQL
    [Arguments]    ${sql}    &{bind_vars}
    Log Many    ${sql}    &{bind_vars}
```

Output:

```
==============================================================================
Test                                                                          
==============================================================================
Should Process Required Arguments Before Keyword args                 | FAIL |
Keyword 'Print SQL' expected 1 non-keyword argument, got 0.
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```

**Comment by pekkaklarck** [comment]
I don't think this would be a good idea because it would prevent using the named argument syntax with mandatory positional arguments like `sql=select name from users where id=:id`. The syntax actually worked somewhat like this, but it caused problems and the logic was changed. Changing it back would be backwards incompatible and remove a generally useful functionality.

In general it is very unfortunate that `=` can mean both a literal equal sign character or named argument syntax. I've actually been thinking that `=` should be changed to always mean the latter and require using `\=` if you want the literal value. That would obviously be a big backwards incompatible change require long deprecation period.
