### ISSUE TITLE
Specify supported Python variants in project metadata (i.e. in `setup.py`)

### ISSUE THREAD

**Issue by gforcada** [robotframework/robotframework#2470]
Hi,

I noticed that on setup.py there are the generic trove classifiers for python 2 and python 3 but there is no specific version set.

I guess 2.7 is supported, but what about python 3? 3.2/3.3/3.4/3.5? And pypy?

It would be great if these details could be added on setup.py. I would create the pull request myself but I failed to see where to gather that information.

**Comment by pekkaklarck** [comment]
Supported versions are listed on README.rst and/or INSTALL.rst. Specifying them explicitly on setup.py would be nice, but it should be done so that future versions like the forthcoming Python 3.6 are included without changes.

**Comment by pekkaklarck** [comment]
Don't want to add explicit versions as long as it is not possible to use something like "Python 3.3+" to mean that all newer versions work too. Needing to create a new release just to add new Python/Jython/IronPython/PyPy versions into setup.py wouldn't be nice. That said, we should document which interpreter variants we support by adding these:

    Programming Language :: Python :: Implementation :: CPython
    Programming Language :: Python :: Implementation :: IronPython
    Programming Language :: Python :: Implementation :: Jython
    Programming Language :: Python :: Implementation :: PyPy

**Comment by gforcada** [comment]
I get the maintainer overhead side of your comments, but on the other hand, there's a new python version yearly *at most*? Given that this project has quite some more commits than just a handful during that time frame, a single commit just for adding a single number doesn't seem that worrisome to me.

But anyway, I'm not the project maintainer, so I'm fine with whatever decision is taken. My goal here was to get classifiers so that automated tools could know which specific versions of python are supported rather than just a global python2/python3.

**Comment by pekkaklarck** [comment]
The problem is not creating a single commit when there's a new Python version but the fact that we actually needed to create a new release. We cannot retroactively update metadata of existing release packages.

Do you have *concrete* examples of problems if we just declare to support Python 2 and Python 3 like we do nowadays? Is there some tool that doesn't allow installation in that case? Or do you mean that someone would accidentally install to Python version we don't actually support (e.g. 2.5 or 3.2 nowadays)? Personally I don't consider that too severe because we support all the generally supported Python versions.

Also, do you know what installation tools do if we say we support only, for example, Python 3.3-3.5 and you try to install on Python 3.6? If that won't work, I would consider that a severe problem.

**Comment by pekkaklarck** [comment]
We'll go with the current classifiers for now. Can consider adding more detailed version specifiers if there are concrete benefits from them (and not too much concrete problems).

**Comment by pekkaklarck** [comment]
Decided to remove PyPy classifier because there were some failures in acceptance tests and could really claim we support it until they are analyzed and fixed. Many/most of them are likely to be bugs in the acceptance tests themselves. Want to support PyPY officially and submitted #2513 to track that.

**Comment by pekkaklarck** [comment]
It turned out we mostly supported PyPy already and adding remaining support was easy. PyPy will be officially supported since RF 3.0.1. See #2513 for details.
