### ISSUE TITLE
Support `[...]` syntax with glob patterns

### ISSUE THREAD

**Issue by nottyo** [robotframework/robotframework#2471]
According to the robotframework documentation, there is an option "--test" which I can specify my test cases name to be run. The document also told me that I can use the glob-like pattern to specify my test case name. For an example
My Test Case Name
1. TestCase1
2. TestCase2
3. TestCase3

And I want to run the test only 'TestCase1' and 'TestCase2' I want to specify the command line using a glob-like range pattern.

    pybot -d result --test TestCase[1-2] MyTest.robot

But it seems like the robotframework support only simple pattern with '**\***' (matching any string) and '**?**' (matching any single character)

I want to request for support more glob-like pattern refer to the basic glob-like pattern here https://en.wikipedia.org/wiki/Glob_(programming) including range pattern e.g. [a-z][0-9]

**Comment by pekkaklarck** [comment]
I'd be fine with this addition. Should also support listing possible characters like `[ax1]` in addition to requested ranges, though. The main reason these weren't added initially is that most of the use cases are covered by the currently supported `?` and `*` and nobody needed `[...]` badly enough for implementation to be worth the effort.

The place where this should be implemented is `u

**Comment by nottyo** [comment]
@pekkaklarck Thanks for your comment. I've summited my contribution with the pull requests #2560. So please review and if you have any concern, feel free to let me know.

**Comment by pekkaklarck** [comment]
One a very quick look the PR looks good. The main problem merging it is that this change is not fully backwards compatible, and I thus don't want to include it in RF 3.0.x minor releases. My plan is to start RF 3.1 development pretty soon (hopefully in April), but there's still a chance that there are enough fixes to warrant 3.0.3 release before that. I try to do a full review for the PR still this week so that we get it into 100%-ready-to-be-merged state.

**Comment by pekkaklarck** [comment]
PR #2560 has been merged some cleanup/fixes done afterwards. This issue can be considered done, but I'm slightly worried how much backwards compatibility issues this is going to create. 

The reason the change is backwards incompatible is that pattern matching where the pattern happens to have `[whatever]` will fail afterwards. Earlier that `[whatever]` has matched a literal string, but after this change that will match a single character from `whatever`.

The same `utils.Matcher` that has been enhanced is used in many places that are thus all affected:
- Various command line options like `--test` mentioned in the description.
- BuiltIn keywords `Should Match`, `Should Not Match` and `Run Keyword And Expect Error`.
- Various `Match` keywords in XML and Collections libraries.

In Robot's own acceptance tests there were surprisingly many failures after the change. That is at least partly due to us validating errors like `[ ERROR ] Some error: details we cannot control` in the stderr with patterns like `[ ERROR ] Some error: *`. These failures were fixed by avoiding pattern matching where it wasn't necessary, using regexps in same places, and replacing `[` and `]` with `?` like `? ERROR ? Some error: *` when glob patterns otherwise worked well.

Similar fixes like we've done can be done also elsewhere if problems occur after this change. If there turn out to be log of problems, we can still consider should we revert the change or make it somehow configurable.
