### ISSUE TITLE
Libdoc markdown

### ISSUE THREAD

**Issue by claytonneal** [robotframework/robotframework#2476]
Would be great if the libdoc tool could also generate markdown format so that library documentation is easy to put up on GitHub, thanks

**Comment by pekkaklarck** [comment]
This would be very hard to implement as it basically would require implementing HTML to Markdown converter or would only work if you write library docs using Markdown too. In that case it would probably be better to implement a separate tool instead of enhancing Libdoc. Personally I fail to see the benefits of Markdown *output* because you can so easily host HTML files on GitHub (via GitHub pages) and elsewhere. Do you @claytonneal have some more use cases for this functionality? Would you be interested to implement this yourself if the idea itself is accepted?

Notice that Markdown as an *input* format for Libdoc wouldn't be too complicated to implement. It would also have a clear use case to allow writing library docs using Markdown.

**Comment by claytonneal** [comment]
Ok read a bit about GitHub pages, seems nice! Will give it a go!

**Comment by pekkaklarck** [comment]
Libdoc producing Markdown is not going to happen.
