### ISSUE TITLE
Test Case keyword override keywords from resource currently executed

### ISSUE THREAD

**Issue by adam-wypych** [robotframework/robotframework#2485]
I have been created test suite file `scope_test.robot` like below:
```robotframework
*** Settings ***
Resource  scope_test_res.robot

*** Test Cases ***
Test
  key
  key_from_resource

*** Keywords ***
key
  Log  internal_test_case_keyword
```

And resource file `scope_test_res.robot` like below:
```robotframework
*** Keywords ***
key_from_resource
  key

key
  Log  call_keyword_from_resource
```

What I found is that when `key_from_resource` is executed the keyword from `scope_test.robot` is executed instead of local keyword `key`. When I change resource file (by adding file prefix to call the `key` keyword) to be like:
```robotframework
*** Keywords ***
key_from_resource
  scope_test_res.key

key
  Log  call_keyword_from_resource
```
everything works perfectly.

The question is, if this behaviour is something expected?

**Comment by pekkaklarck** [comment]
This is by design. The idea is that test case files can override parts of the functionality provided by resource files. I agree it can be surprising, though, and I'm not sure how useful this functionality really is. It's good that it is possible to prefix the keyword with the resource file name also in this case if you want to be sure exactly that keyword is called.

**Comment by adam-wypych** [comment]
Thanks for update Pekka.
