### ISSUE TITLE
Error: contains no tests in suite despite of the fact I have Test Case section

### ISSUE THREAD

**Issue by docian** [robotframework/robotframework#2498]
I'm getting:
[ ERROR ] Suite 'Ecomm-Test-Sit' contains no tests in suite 'Ecomm-test-sit.Tests.PaymentTests.PaymentStatistics'.
despite the fact i have *** Test Cases *** section. Here is the main part of the content:
*** Settings ***  
Library  RestKw    https://xxx
Library  Collections
Library  PaymentApiTemplates
Library  PaymentRequest
Library  NewPayments
Library  BrowserSupport
Library  paymentsKeywords
Resource    ../../keywords/generalKeywords/generalKeywords.robot
Resource    ../../keywords/setVariablesKeywords/setupKeywords.robot
Resource    ../../keywords/functionalKeywords/functionalKeywords.robot
Resource    ../../tests/paymentTests/NewPaymentsTests.robot
Resource    ../../tests/paymentTests/PaymentActionsTests.robot

Suite Setup    Set Suite Variables

Suite Teardown    Close Browser

*** Variables ***
${webdriver}

*** Test Cases ***
Show Statistics Depending on Payment Type - Add a New Card Payment - Sunshine Scenario
    [Tags]  253
    Open Payments Page 
    Wait Until Element Is Enabled    id=totalPaymentsNumber  20s 
    Sleep  2s     
    ...
    ...
    ${number}=  Convert To Integer    ${card_payments}
    ${number1}=  Convert To Integer    ${card_payments1}
    ${number1}=  Evaluate  ${number1} - 1 
    Should Be Equal As Integers    ${number}    ${number1}

**Comment by docian** [comment]
command line is:
Command: C:\Python27\python.exe -m robot.run -P C:\tst_work\ecomm-test-sit\pythonFiles\generalIdentifiers:C:\tst_work\ecomm-test-sit\pythonFiles\generalMethods:C:\tst_work\ecomm-test-sit\pythonFiles\paymentAPI:C:\tst_work\ecomm-test-sit\pythonFiles\paymentsModule:C:\tst_work\ecomm-test-sit\pythonFiles\mySQL --listener C:\Users\docia\AppData\Local\Temp\RobotTempDir2336261068914325885\TestRunnerAgent.py:57545:False -s Ecomm-test-sit.Tests.PaymentTests.PaymentStatistics --variable ENV:ST_URL --variable URL:https://st.portal.dibspayment.nets.no --variable CHECKOUT:https://st.checkout.dibspayment.eu/app/sdk/checkout.js C:\tst_work\ecomm-test-sit

**Comment by docian** [comment]
I've tried even a trivial file and... the same result. I'm wondering why!?

**Comment by HelioGuilherme66** [comment]
I suspect bad formatting of the file.
What kind of spacing are you using? Four or Two spaces? Do you use any syntax validator Editor?
I recommend to use RIDE.

**Comment by docian** [comment]
I'm using RED pluhin for Eclipse... It works for many files...

**Comment by docian** [comment]
I've isolated the problem:
Should Be Equal As Strings    ${consumer_name_new}    Eva Marianne
This is the keyword that i'm putting in and is issuing the error. Why?

**Comment by docian** [comment]
The weirdest thing is that even whether i am getting a comment over this line then the result is the same

**Comment by docian** [comment]
Eva Marianne Sandström from the string is the problem... how could i solve this problem?

**Comment by HelioGuilherme66** [comment]
To better *identify* the problem you could, create a simple test file with the steps: 
```
    ${consumer_name_new}=    Set Variable    Eva Marianne Sandström
    Should Be Equal As Strings    ${consumer_name_new}    Eva Marianne Sandström
```

Make sure the file is encoded UTF-8. Use a simple text editor to exclude RED issues.

(I have already done that test and it passes. Be prepared to close this issue, since the problem should be on your test file)

**Comment by pekkaklarck** [comment]
You get this error if you use `--suite (-s)` option and in there are no tests that match this criteria. Your command line includes `-s`, so most likely it just doesn't match any suite. It's impossible to tell for sure because the provided example is both complex (has unrelated information) and lacks valuable information like describing the suite structure you are actually running.

If you are sure this isn't a user error and you have actually found a bug, please submit a new issue with a [short, self contained, correct example (SSCCE)](http://sscce.org).

**Comment by docian** [comment]
changed the encoding in UTF-8 and it is working... closed

**Comment by pekkaklarck** [comment]
You had non-ASCII characters in a file that was not UTF-8 encoded? That definitely explains the problem. If you try executing such a file only, you'd get an exception because Robot cannot parse the file. When you execute a directory, such errors are silently ignored.

The reason errors are ignored is that Robot doesn't know does the file contain test data for it to parse or is it just random file in that directory. This behavior made/makes sense with html, tsv and txt files because they *can* contain whatever data, but with files having `.robot' extension we should show an error always. In the future we plan to support only `.robot` files and then can show errors with all parsing failures, but I guess we should start showing them with `.robot` files already now.

**Comment by stryker2k2** [comment]
Topic is old and closed but was helpful. And since it is one of the only topics on the web that is addressing the `Suite '<Suite>' contains no tests...` error, I though I would add in my issue and resolution.

> @HelioGuilherme66 on Dec 21, 2016
> What kind of spacing are you using? Four or Two spaces?

@docian issue was with the word `Sandström` where as my issue was with spaces. Here is an example (I am using . to show spaces as seen when using Visual Studio Code)

```
Perform Kill Process
    Kill Process . . . program.exe
```
-> Gives ``Suite '<Suite>' contains no tests matching name...`` error

```
Perform Kill Process
    Kill Process . . program.exe
```
 -> Runs perfectly

Having an incorrect spacing ANYWHERE in your *.robot file will cause the entire file to not parse properly.

My issue was a simple error but resulted in hours lost. Hopefully this can help someone else out.
