### ISSUE TITLE
Special characters in strings break splicing/other functionality

### ISSUE THREAD

**Issue by Brian-Williams** [robotframework/robotframework#2520]
When you use a character outside of a normal identifier `(letter|"_") (letter | digit | "_")*` it functions normally, until you try to slice or do another operation against it.

This is likely because period can be used to access members of a dictionary so it is nebulous if ${thing.thang} is dictionary 'thing' with key 'thang' or a variable 'thing.thang'.

Is there any way to resolve this ambiguity when a variable has a period in it? 

Example suite:
```
*** Variables ***
${thing.string}     too
@{thing.list}       much  for  zblock
${thing_list}       ${thing.list}


*** Test Cases ***
Maintain variable type
    [Documentation]  Replace the character(s) between thing and list with your delimiter to test if slicing works.
    log to console  \n${thing.string}
    log to console  ${thing_list[:]}
    log to console  ${thing.list}
    log to console  ${thing.list[:]}
```

Output:
```
==============================================================================
Use Apps List                                                                 
==============================================================================
Maintain variable type :: Replace the character(s) between thing a... 
too
.[u'much', u'for', u'zblock']
.[u'much', u'for', u'zblock']
Maintain variable type :: Replace the character(s) between thing a... | FAIL |
Resolving variable '${thing.list[:]}' failed: Variable '${thing}' not found. Did you mean:
    ${thing_list}
    ${thing.list}
------------------------------------------------------------------------------
Use Apps List                                                         | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
Output:  /home/testing/robot/output.xml
Log:     /home/testing/robot/log.html
Report:  /home/testing/robot/report.html
```

**Comment by chriscallan** [comment]
After taking a look at this, I don't think the issue is the dot but rather that the extended variable naming (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id522) is looking for an attribute "list[:]".  You can see that a simple '.' doesn't have an ill effect in your Test Case, nor does the slicing introduce an issue after you've assigned the extended variable to a "normal" variable (both those tests pass in your example).
In these cases you're probably best off assigning your attribute to another variable and slice from there, as you did with ${thing_list}.  
Possibly this could be seen as an enhancement request for a future RF release to allow for Python-style slicing on extended variables?

**Comment by Brian-Williams** [comment]
Ah thanks for pointing me in the right direction.

While this does seem slightly inconsistent to me as the docs as they claim 'The variable is searched using the full variable name. The extended variable syntax is evaluated only if no matching variable is found.' To me that means the format `${thing.list[:]}` should work.

It's worth noting if you are reading this and simply want a simple value that is functional:

input:
`log to console @{thing.list}[0]`

output:
`much`

But you can't do real slicing like that:

input:
`log to console  @{thing.list}[0:1]`

output:
`List variable '@{thing.list}' used with invalid index '0:1'.`

I will look into this further when I have more time.

**Comment by pekkaklarck** [comment]
@chriscallan is right that the problem is about variable naming. You need to use only alpha-numeric characters and underscrore in the variable name if you plan to use it as the base in extended variable syntax. This is also [documented in the User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-types):

> Variable names can basically have any characters between the curly braces. However, using only alphabetic characters from a to z, numbers, underscore and space is recommended, and it is even a requirement for using the extended variable syntax.
