### ISSUE TITLE
DLL load failed:  sp\xe9cifi\xe9 not find

### ISSUE THREAD

**Issue by sarahaf** [robotframework/robotframework#2524]
Hi, 
I had a problem to connect to the database with my computer and RobotFramework. 
Python : 2.7 
RobotFramework :  robotframework-2.9.2.win-amd64
RobotFramework Ride: robotframework-ride-1.5.2.1.win-amd64.exe
Libraries : Database (robotframework_databaselibrary-0.8.1) / String / OperatingSystem / Collections
Module : cx_Oracle-5.1.3-11g.win-amd64-py2.7

Steps : 
1st Line : Connect To Database Using Custom Params // cx_Oracle //user='****rc4', password='*****', dsn='(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=*******-******)(PORT=******)))(CONNECT_DATA=(SID=********)))'
2nd Line : Disconnect From Database 

Observed : 
FAIL : ImportError: DLL load failed: Le module sp\xe9cifi\xe9 est introuvable.

Expected: 
I should succeed to connect to the database. 

If somebody can help me it could be awesome... 

Thanks

**Comment by HelioGuilherme66** [comment]
First your problem is with robotframework-databaselibrary not in this project. Second, you are not reporting an issue but asking for help. This should be done on the google groups or Slack channels.

The error message is clear; it did not find the database driver. Try to install the driver from `cx_Oracle-5.1.3-11g.win-amd64-py2.7` and put in a directory that is listed on the %PATH% variable.

**Comment by pekkaklarck** [comment]
Yeah, this problem isn't related to RF core. Questions are best sent to robotframework-users or other such forums anyway.

**Comment by sarahaf** [comment]
Ok sorry , I thought it was linked. Thanks for your help .
