### ISSUE TITLE
rebot crashing python

### ISSUE THREAD

**Issue by akshaykochar** [robotframework/robotframework#2536]
I had about 100 outputSOMENAME.xml files which totaled 2.6GB. When I ran the command in windows command line "rebot --escape space:__ --name LT *.xml". it crashed the python process it opens

**Comment by pekkaklarck** [comment]
It would help if you could give some more details about the failure.

**Comment by akshaykochar** [comment]
When I ran the command from command line the script would run or hang for five minutes and then a python error dialog box would open saying python 2.7.0 instance crashed. There was no output printed on the command line and the output.xml file did not get generated. The pc has 16 gb of ram and no heavy application was open on it. I was able to reproduce the issue on another similar pc. Also i was able to rebot the 100 files in smaller batches. I tried rebotting the first 45 and then the next 45 and then 10. When i did it in batches the rebot worked. Let me know if u need more specifics. Thanks

**Comment by akshaykochar** [comment]
I also was able to rebot 200 output.xlm files which were relatively smaller in size than the one which crashed python.

**Comment by pekkaklarck** [comment]
You seem to be running out of memory. Processing outputs is highly performance optimized, but with large enough outputs memory will always run out.

Do you have large keyword structures created using for loops or otherwise in your outputs? If yes, you should try moving some of the logic into test libraries where they don't cause so many keyword calls and output file size stays small. As a quick fix you can also try using `--flattenkeywords` option to flatten keywords without processing them fully.

I don't think there's anything we can do to this on Robot/Rebot side. If you have interest, you could do some performance and memory profiling while running Rebot against your outputs to see is there anything that could still be enhanced, though.
