### ISSUE TITLE
XML logging hangs

### ISSUE THREAD

**Issue by jpeltonen** [robotframework/robotframework#2544]
I have case where RF (Iron Python) XML logging hangs forever. The output look like this when it hangs (last lines in log): 

![upload2](https://cloud.githubusercontent.com/assets/22810621/22920511/0fb4cffc-f29e-11e6-899a-ea69b3949cd8.png)

This is what it should look like:
![upload](https://cloud.githubusercontent.com/assets/22810621/22920479/e53d6810-f29d-11e6-8b93-0ac84302fefa.png)

Found this warning also when calling ipybot.bat

>  c:\IronPython27\Lib\xmllib.py:1: DeprecationWarning: The xmllib module is obsolete.  Use xml.sax > instead.
  """A parser for XML, using the derived class as static DTD."""

Versions:
Robot Framework 3.0 (IronPython 2.7.6 on cli)
Windows Server 2008 R2 Standard SP 1

**Comment by pekkaklarck** [comment]
Did you install the external elementree module as the installation instructions mandate?
https://github.com/robotframework/robotframework/blob/master/INSTALL.rst#ironpython-installation

If you did, you need to provide more information for others to be able to investigate the problem. It would be best if you could provide a *simple* example demonstrating the problem that others could also run to reproduce the issue.

**Comment by jpeltonen** [comment]
I did install it elementtree following the instructions and everything works fine most of the time. This hang is quite rare and very difficult to reproduce. Is there any way to dig in to this if I get this situation again. I already checked Windows Event Viewer but found no errors there.

**Comment by pekkaklarck** [comment]
Do your libraries use threads? If they do, the problem could be a deadlock in them. 

Knowing does it always hang in the same place would be interesting. You cannot see that from the output.xml that is currently been written because it is not flushed and it depends on IronPython/.net/OS when the text is actually written there. You could monitor using listeners, but the output you get with `--debugfile` ought to be enough too. Debug files are flushed to disk and thus contain the latest information.

You could also try adding some print statements to the code to pinpoint the place where the problem occurs. Even better if you could somehow run the code in a debugger, but I don't know too much about using them.

**Comment by jpeltonen** [comment]
Yes it hanged again today to same place as described above. The static method 'Get Target IP' is called from .NET DLL and it doesn't use any threads. It just reads IP address from a file. It has been working ok before.

How should I use --debugfile option? In ipybot --debugfile?

**Comment by jpeltonen** [comment]
I checked from Wireshark capture that actually 'Get Target IP' keyword has returned correct IP address, because it was shown in the capture. So it is the next keyword that hangs not the last in log.

**Comment by pekkaklarck** [comment]
Did you get the problem sorted out?

**Comment by jpeltonen** [comment]
No, but I just closed this, because I am not sure if it is a Robot Framework issue.
