### ISSUE TITLE
No one uses batch files anymore

### ISSUE THREAD

**Issue by nicholasbailey** [robotframework/robotframework#2546]
Windows Powershell was introduced in 2006 and has been built into the OS since Windows 7. It's been the _de facto_ default shell for Windows development ever since. 

A lot of cross-platform projects that are not primarily targeted at Windows haven't kept up with this transition, but it's really time to switch off a scripting language that's been all but deprecated in the Windows development world for years.

Incidentally, Powershell is also a full-scripting language with a feature set comparable to Bash, not a clunky command runner. Using it would mean we didn't need to lean on install-time replacement of the path the python executable, making robot play much nicer with virtualenv.

**Comment by pekkaklarck** [comment]
We've been actually thinking about starting to use `.exe`s instead of `.bat`s in RF 3.1 (#2415). Would Powershell scripts have some benefits compared to them? Do they work with Win7 and newer out-of-the-box or do you need to install something? The only good thing about batch files is that they are ubiquitous.

**Comment by nicholasbailey** [comment]
There's nothing you could do with a ps script you couldn't do with an exe. The main benefit is transparent readability (like a shell script). But exes might be a nice alternative!

**Comment by pekkaklarck** [comment]
These exes would be automatically created by setuptools. The problem is that I'm not sure do all the supported Python interpreters (incl. Jython and IronPython) support creating them.

Could ps scripts somehow avoid the current problem with batch file?

**Comment by Tattoo** [comment]
Throwing my two cents into the ring, in my personal experience batch files are still widely used. I also feel moving to PS is not as clear-cut; I have witnessed some exotic installations of Windows 7 without Powershell ie. some large companies deliberately remove it from their employees' laptops during installation. Batch, due to nature of Windows' backwards compatibility, will probably work forever instead. 

Granted, if PS is chosen, it is trivial to write a batch wrapper for it. However I would personally much prefer exe's.

**Comment by vokiput** [comment]
No Powershell please. It is restricted to use in many companies due to security issues.

**Comment by pekkaklarck** [comment]
`robot.exe` is the way to go. Closing in favor of #2415.
