### ISSUE TITLE
`rebot --merge` doesn't work correctly if test messages contain HTML

### ISSUE THREAD

**Issue by yahman72** [robotframework/robotframework#2548]
looks like the same root cause as in #2360 i.e. the "Re-executed test has been merged." comes before the \*HTML\* marker

Assume `dummy.robot`:
```
*** Settings ***
Test Teardown    TcTeardown
*** Test Cases ***
TC
    Fail Execution    this fails
*** Keywords ***
TcTeardown
    Set Test Message   *HTML*<a href="http://robotframework.org/">rf</a>
```
Run:
`pybot -o o1.xml dummy.robot` --> parsed as HTML in report.html
`pybot -R o1.xml -o o2.xml dummy.robot` --> parsed as HTML in report.html
`rebot --merge o1.xml o2.xml` --> no parsing i.e. report shows the raw HTML tags

**Comment by pekkaklarck** [comment]
This is definitely annoying. Shouldn't be too complicated to enhance merging logic to preserve HTML formatting. It might actually make sense to always use HTML formatting when constructing the "re-executed tests have been merged" message. The current `-  -  -` marker could be replaced with `<hr>` or perhaps individual messages could be put into `<div>`s with light borders. Interested to provide a PR?

**Comment by yahman72** [comment]
I was thinking about this a bit: is the current approach (i.e. that `*HTML*` marker in the beginning) really a good one? 

Looks like a workaround, any ideas why it was done like that? Instead of something more "programmatic" e.g. `html=False` argument? Like we have it in the `Log` KW i.e. `def log(self, message, level='INFO', html=False, console=False, repr=False)` 

same comment/question applies to #2549

**Comment by pekkaklarck** [comment]
Error messages are primarily got from exceptions:

```python
if result != expected:
    raise AssertionError('*HTML* We got <b>severe</b> failure!!')
```

Do you have ideas how else could it be specified that the exception should be interpreted as HTML? Notice also that the current approach works also with Java based test libraries and over the remote library interface.

**Comment by yahman72** [comment]
oh, okay - need to think about this a bit more, first thing that comes to my mind (a bit ugly though) is:
```
ex = AssertionError('We got <b>severe</b> failure!!')
ex.html = True
raise ex
```

**Comment by pekkaklarck** [comment]
This could be done. The attribute should be named with `ROBOT_` prefix, though. I fail to see how that would really be better than the current approach and, more importantly, how it would help fixing this issue.

**Comment by yahman72** [comment]
To be honest, I have not looked at code at all but the idea would be:
- raise exception with `html=True`
- the logic handling the exceptions would need know how to handle those `html=True` e.g. add `html` attribute to the xml element in output.xml, for example `<doc html="yes">some documentation</doc>` 
- report generation logic would handle those `html=true` attributes in the output XML i.e. parse them as HTML

But as said, I haven't looked at the code i.e. no idea what this would mean in practice: major refactoring? backwards compatibility issues? etc.

**Comment by pekkaklarck** [comment]
Some comments about the possibility to specify that message is HTML using an attribute in the exception itself:

- Removing the current possibility to specify that the message is HTML by prefixing it with `*HTML*` would be badly backwards compatible. It would be possible only with a deprecation cycle spanning multiple releases. This would only be worth the effort if the benefits would be *really* big.

- I fail to see any benefits to in using an attribute that I need to separately set to just using `raise Exception('*HTML* <b>Hi!</b>')`. Turning this one-liner into three lines certainly would be inconvenient. You obviously could create your own exception that does this automatically, but you could create such custom exception already now:

   ```python
    class Example(AssertionError):

- That would be a backwards incompatibility change without any practical benefits. Even if we would remove that possibility and would only use special attributes with exceptions, that would do absolutely nothing to help fixing the problem with `--merge` and messages containing HTML. I seriously doubt there would be any benefits with using

**Comment by yahman72** [comment]
This would fix the `--merge` issue, because when the report generation logic handles those `html=true` attributes it would parse them always as HTML i.e. the original problem with the `*HTML*` not being anymore in the beginning would also be solved.
However this doesn't seem justifiable as it causes quite much refactoring in different components.

When sticking to the `*HTML*` design, then - as far as I understand - this is "just" a report-generator/parser issue: the `*HTML*`'s are always in the output XML --> they just need special treatment in the `--merge` scenario.
This shouldn't be that complicated to do, maybe just that `*HTML*` before the `Re-executed test has been merged` if one of the old messages starts with `*HTML*`
I could give it a go and try to come up with an PR

**Comment by pekkaklarck** [comment]
No, changing how uses can specify is the message HTML or wouldn't fix how HTML messages are internally handled. At the moment messages internally are just strings with possible `*HTML*` prefix, but we could already now change that regardless how users specify the message. Test and suite objects that have the `message` attribute could get a separate `message_is_html` attribute or, probably better, we could change the `message` to a custom object that has a `html` attribute in addition to the actual message. Additionally needed to change `output.xml` so that `<message>` elements get `html` attribute. None of this would require any changes to how users specify the message. Additionally, these changes wouldn't fix the underlying problem with `--merge`.

**Comment by pekkaklarck** [comment]
The actual problem is in the logic related to `--merge`. It should take it into account that old or new messages could be HTML and format the final message accordingly. The related code is here:
https://github.com/robotframework/robotframework/blob/master/src/robot/result/merger.py#L63

I think the best way to fix this would be always constructing a HTML message when merging messages. The current approach to use `-  -  -` between messages isn't that good in general. Using HTML would allow separating different statuses and messages from each others much better. Coming up with a good design is probably harder than actually fixing this problem.

**Comment by yahman72** [comment]
I had a look the code and made a couple of tests: Changing that merge message generation https://github.com/robotframework/robotframework/blob/master/src/robot/result/merger.py#L80 to be HTML should be quite simple 
before:
![image](https://cloud.githubusercontent.com/assets/8724383/23618879/25336308-0292-11e7-9c1a-9eb409268344.png)

after (using `<hr>`):
![image](https://cloud.githubusercontent.com/assets/8724383/23618906/30537a70-0292-11e7-8628-f0677a899952.png)

If this (i.e. using `<hr>`) is okay I'll finish the code and create a CR.

**Comment by pekkaklarck** [comment]
If we change the message to be HTML always, I'd like to add some additional formatting. Could at least change `PASS` and `FAIL` texts to use same green and red colors as rest of the report. It ought to be enough to use `<span class="pass">PASS</span>`. This and other tuning can be done after fixing the actual issue, though. Starting with a PR containing just the fix is thus probably a good idea.

**Comment by yahman72** [comment]
I still need to update the tests for the fix. I can probably include that PASS/FAIL thing too. doesn't look that complicated.
I'm busy with something else now, probably for the rest of this week --> I'll  submit the PR next week.

**Comment by pekkaklarck** [comment]
Sounds great! If formatting changes get complicated, better to first create a PR that just fixes the actual problem. Tests definitely are needed.

**Comment by yahman72** [comment]
PR #2562

**Comment by yahman72** [comment]
what's the status here? The PR seems to be still open...

**Comment by pekkaklarck** [comment]
I haven't had time for Robot Framework coding for long time. I don't have too much time for that in general, and getting SL 3.0 out and now RoboCon are eating it. This issue is in RF 3.0.3 scope already, so as soon as I have more time for RF I'll look at this too. I hope to get 3.0.3 out fairly soon after RoboCon sprints next week. Can you by the way make it there?

**Comment by yahman72** [comment]
yeah. I'll be there too - see you there!

**Comment by pekkaklarck** [comment]
Awesome! Hopefully we can get the PR merged already there, but at least we should have time to look at it together.
