### ISSUE TITLE
RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour

### ISSUE THREAD

**Issue by ldiary** [robotframework/robotframework#2552]
I am running tests like this:
```
(py36env) c:\data\ohmyhardwork\ens\ensqacode>robot --pythonpath lib tests\Configuration.robot
c:\program files\python36\Lib\runpy.py:125: RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
==============================================================================
Configuration
==============================================================================
FTP Server settings are manageable via configuration file        ..c:\program files\python36\Lib\runpy.py:125: RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
FTP Server settings are manageable via configuration file        | PASS |
------------------------------------------------------------------------------
Configuration                                                         | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
Output:  c:\data\ohmyhardwork\ens\ensqacode\output.xml
Log:     c:\data\ohmyhardwork\ens\ensqacode\log.html
Report:  c:\data\ohmyhardwork\ens\ensqacode\report.html
```

And I keep on getting this warning:
```
RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
```

This is the only link I can find through Google:
https://bugs.python.org/issue27487

But I don't know any workaround to get this warning disappear in Robot Framework... I just started learning how to use robot framework today. How can I suppress this warning?

**Comment by pekkaklarck** [comment]
Thanks for the report. Some findings:

- I can reproduce the problem with Python 3.6 both on Linux and on Windows by running `python -m robot.run` but luckily `python -m robot` works without warnings. 

- The problem manifests itself using the `robot` command on Windows because there we use `robot.bat` with content like `python -m robot.run`. We hopefully get rid of the batch files in favor of exe files in RF 3.1 (#2415) but can at least change the code to `python -m robot`. Using `python -m robot` instead of `robot` is also an OK workaround.

- Same problem occurs with `python -m robot.rebot`, `python -m robot.libdoc`, etc.

- Need to investigate what's actually causing the warning. Hopefully we can refactor code to avoid it.

**Comment by osde8info** [comment]
C:\>robot --version still gives "RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot'" error

`C:\>python -m robot --version
Robot Framework 3.0.2 (Python 3.6.4 on win32)

C:\>robot --version
c:\program files (x86)\python36-32\lib\runpy.py:125: RuntimeWarning: 'robot.run' found in sys.modules after import of package 'robot', but prior to execution of 'robot.run'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
Robot Framework 3.0.2 (Python 3.6.4 on win32)
`

**Comment by Accuratelli** [comment]
Hi,  
are there plans to fix this one in the next release please?  
We trigger our RobotFramework tests from Jenkins which unfortunately treats all test runs as a failure when this warning occurs.

**Comment by pekkaklarck** [comment]
This SO question is about the exact same issue that we have:
https://stackoverflow.com/questions/43393764/python-3-6-project-structure-leads-to-runtimewarning

The root cause for the issue is that in `robot/__init__.py` we do `from robot.run import run, run_cli` which imports `robot.run` module *before* it is imported by `-m robot.run`. An [answer to the question](https://stackoverflow.com/a/45070583/38083) explains why the warning is emitted more thoroughly and also proposes some possible fixes. It seems what we could do is this:

1. Rename `robot/run.py` to `runmod.py` or something similar.
2. Change `robot/__init__.py` to import `run` and `run_cli` methods from `runmod.py`.
3. Create new `robot/run.py` that imports everything from `runmod.py`.
4. Repeat steps 1-3 with `robot/rebot.py`.

The above ought to be fully backwards incompatible still supporting `python -m robot.run`, `python -c 'import robot; robot.run_cli(...)` and also `from robot.run import AnyEntryPoint`. The main problem is that creating extra modules just to avoid the warning is annoying. This is especially annoying because, AFAIK, the warning is not really relevant for us and our code works fine.

An alternative to the above would be silencing RuntimeWarnings emitted by Python's `runpy` module that implements the `-m` functionality. This can be done by adding this into `robot/__init__.py`:

```python
import warnings
warnings.filterwarnings('ignore', category=RuntimeWarning, module='runpy')
```

The main problem with the above solution is that it may hide future RuntimeWarnings that actually are relevant for us. We could make it more script by adding `lineno=125`, but then the workaround wouldn't anymore work if `runpy` module would be modified and lines adder or removed.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, decided to take the easy route and just disable RuntimeWarnings by the `runpy` module. Decided to use this variant of the code to allow using `-W` (or `PYTHONWARNINGS`) to enable warnings:

```python
import sys
import warnings

if not sys.warnoptions:
    warnings.filterwarnings('ignore', category=RuntimeWarning, module='runpy')
```
