### ISSUE TITLE
Calling method 'end_suite' of listener 'LibraryListener' failed: IndexError: pop from empty list

### ISSUE THREAD

**Issue by nrbalajimca** [robotframework/robotframework#2566]
Calling method 'end_suite' of listener 'LibraryListener' failed: IndexError: pop from empty list. Getting this error while execute the script via ALM. Anyhow it is not affecting the test execution but it shows a warning message so pls fix it. Please find below the console log.

Changelog
====================================================================
Changelog                                                             | PASS |
------------------------------------------------------------------------------
[ ERROR ] Calling method 'end_suite' of listener 'LibraryListener' failed: IndexError: pop from empty list
Changelog                                                             | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed

**Comment by pekkaklarck** [comment]
Your listener seems to be buggy. Cannot comment more about it without more information about the listener and your setup in general. If you cannot figure out where the bug is, please send further questions to robotframework-users mailing list or other such support forums. This issue tracker is for bug reports and enhancement requests.
