### ISSUE TITLE
`Collections` keywords fail with bad error message when used with invalid input

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2580]
When I have this: 
```
*** Settings ***
Library    Collections
*** Variables ***
${foo}    a=1   b=2

*** Text Cases ***
Example
    ${value} = Collections.Get From Dictionary    ${foo}    a
```
Then I get error: `TypeError: string indices must be integer`, which is little bit confusing. I understand that error comes directly from Python side, but spotting the error is quite difficult. Because the dictionary is declared in wrong way, in variables section, but it is used correctly in the keyword.

**Comment by pekkaklarck** [comment]
The problem apparently is that this keyword doesn't validate that the given item is a dictionary. I would assume most other Collections keywords have the same problem and should be fixed at the same time. Two fixing approaches:

- Validate that the item is a dictionary (or a list with list related keywords). We have `utils.is_dict_like` that handles also special cases like `UserDict` which isn't instance of `dict` or `collections.Mapping` on Python 2. There's a very small risk that someone would be using these keywords with their own custom dictionaries which don't extend `dict`, `UserDict` or `Mapping`. I consider that risk so small that adding validation in a major release would be fine and probably it would be safe also in a minor release.

- Validate that the item is not a string. That ought to catch most of the invalid usages without any backwards compatibility risks.

Any comments which approach should we use? I'd use the former and wait until a major release.

**Comment by aaltat** [comment]
I like the first one too and wait for major release.

**Comment by juusoi** [comment]
Hi!
I will start working with this issue today.

**Comment by pekkaklarck** [comment]
This issue is backwards incompatible because earlier it was possible to have

    Lists Should Be Equal    string    string

and that worked because strings are iterable in Python and there were no argument checking. Now that we validate that arguments actually are list-like, and our `utils.is_list_like` doesn't consider strings list-like, the above is going to fail. In my opinion that's fine, because using `Lists Should Be Equal` is clearly wrong keyword for comparing strings and should be replaced with normal `Should Be Equal`.
