### ISSUE TITLE
Keyword decorator gets exposed as a library keyword

### ISSUE THREAD

**Issue by ombre42** [robotframework/robotframework#2588]
Using the `@keyword` decorator as [in the example](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-decorators) leads to `keyword` being exposed as a library keyword.

![image](https://cloud.githubusercontent.com/assets/1576672/25645999/6ec10bb0-2f79-11e7-9819-b019c7123542.png)

This is not specific to RED, as the keyword `Keyword` also shows up when using `libdoc`.

Workarounds:

- Put at the bottom of the library file: `del keyword` (easy to forget)
- Alias with an leading underscore (clunky):
```
from robot.api.deco import keyword as _keyword

@_keyword('Add ${quantity:\d+} Copies Of ${item} To Cart')
def add_copies_to_cart(quantity, item):
    # ...
```

**Comment by woodwo** [comment]
This lead to misbehave at  [robotframework-hub](https://github.com/boakley/robotframework-hub) project: it use LibraryDocumentation() class for obtain list of keywords and it returns just instance of Keyword decorator instead.

**Comment by pekkaklarck** [comment]
The reason for this behavior is that Robot considers all callable objects in the module to be keywords. You could have library architecture where you are implementing keywords in various modules and imported them to your main library like `from module import example_keyword`. It's not possible to separate such keywords from other callables that shouldn't be considered keywords.

I guess Robot could special case it's own `keyword` decorator, but the same problem occurs with all other callables so I'm not sure is it worth the effort. The problem is also documented in the User Guide:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#what-methods-are-considered-keywords

The User Guide also explains you can use `__all__` to specify which callables are keywords explicitly. Yet another workaround in this particular case would be changing the code to:

```python
from robot.api import deco

@deco.keyword
def example():
    pass
```
