### ISSUE TITLE
`Run Keyword And Return` not returning in teardown context if executed test fails

### ISSUE THREAD

**Issue by juhamkilpinen** [robotframework/robotframework#2594]
"Run And Return" keywords do not return when they should in teardown. If executed keyword fails the execution continues. Example:

```
*** Test Cases ***
TEST_001
    [Teardown]    Test Teardown
    Log    Testing

*** Keywords ***
Test Teardown
    Do Some Teardown

Do Some Teardown
    Run Keyword And Return If    True    Fail    Should return from keyword now
    Run Keyword And Return    Fail   This should also return now
    Log    This should never happen    console=yes
```

Robot Framework 3.0.2, Python 2.7.13

**Comment by pekkaklarck** [comment]
Could you please modify your example so that it can be just copied to a file and executed? It would make investigating the problem faster. Even better if you can put it into a highlighted code block to make reading the example easier here too.

**Comment by ombre42** [comment]
The problem is that `Run Keyword And Return If`, `Run Keyword If`, and `Run Keyword And Return` are all failing because the keywords they called failed. In this scenario, the teardown behavior by design is to continue executing the next keyword. In order to get the behavior you desire, you need to use a `Run Keyword` variant that will not fail. I suggest `Run Keyword And Return Status` or `Run Keyword And Ignore Error`. These keywords will not fail, and so you can return early if you desire.

```
*** Test Cases ***
Teardown 1
    [Teardown]    My Teardown 1
    Log    Testing
Teardown 2
    [Teardown]    My Teardown 2
    Log    Testing
*** Keywords ***
My Teardown 1
    Some Keyword 1
Some Keyword 1
    ${passed}    Run Keyword And Return Status    Fail    Should return from keyword now
    Return From Keyword If    not $passed
    Log    Some Keyword 1 still executing    console=yes
My Teardown 2
    Some Keyword 2
Some Keyword 2
    ${status}    ${ret val}    Run Keyword And Ignore Error    Fail    Should return from keyword now
    Return From Keyword If    $status != 'PASSED'
    Log    Some Keyword 2 still executing    console=yes
```

**Comment by juhamkilpinen** [comment]
Those two keywords (Run Keyword And Return & Run Keyword And Return If) have two tasks: 1) Run given keyword 2) Return. I do understand the logic of teardown: Do not return from the keyword if some keyword in it fails but continue to execute the rest of the teardown steps. However, this is a different case. Return functionality is part of the keyword tasks and should not depended on given keyword execution status. At least the documentation should be fixed if not the keywords. E.g. Run Keyword And Return documentation says:
```
Run Keyword And Return    My Keyword   arg1   arg2
# Above is equivalent to:
${result} =    My Keyword    arg1    arg2
Return From Keyword    ${result}
```
That is clearly not true. They are not interchangeable since they behave differently in teardown.

**Comment by pekkaklarck** [comment]
Thanks for the updated example. Interesting corner case. @ombre42 is correct in his analysis that these keywords don't return because the keywords they run fail and that failure bubbles up. Normally that is the expected behavior and keyword execution stops nevertheless, but in teardowns things work differently.

I'm fine fixing the behavior if that isn't overly complicated. Do you @juhamkilpinen have time and interest to look at it? If fixing turns out to be too hard, updating documentation is in order.

**Comment by juhamkilpinen** [comment]
Yes, I can look at it.

**Comment by pekkaklarck** [comment]
I consider this quite low priority issue but decided to look at it nevertheless. Good news is that fixing seems to be pretty easy.

**Comment by juhamkilpinen** [comment]
Did you notice my pull request 2608 on this? Any comments for that?
