### ISSUE TITLE
How to remove the arguements passed for keywords in logfile.

### ISSUE THREAD

**Issue by UmaShanmuga** [robotframework/robotframework#2643]
EX:
Login  username  password
 where login is a keyword , username and password are the arguements passed for it. In log file keyword along with arguements are printed. How to remove this arguements in logfile during execution ?

**Comment by bkhouri** [comment]
Why do you want to remove arguments from the log file?  This will make it more difficult to troubleshoot should a test fails.   If you are concerned about having the password in plain text, consider using test accounts instead of real accounts.

**Comment by bkhouri** [comment]
Alternatively, you can investigate the `--removekeywords` robot argument

```
   --removekeywords all|passed|for|wuks|name:<pattern>|tag:<pattern> *
                          Remove keyword data from the generated log file.
                          Keywords containing warnings are not removed except
                          in `all` mode.
                          all:     remove data from all keywords
                          passed:  remove data only from keywords in passed
                                   test cases and suites
                          for:     remove passed iterations from for loops
                          wuks:    remove all but the last failing keyword
                                   inside `BuiltIn.Wait Until Keyword Succeeds`
                          name:<pattern>:  remove data from keywords that match
                                   the given pattern. The pattern is matched
                                   against the full name of the keyword (e.g.
                                   'MyLib.Keyword', 'resource.Second Keyword'),
                                   is case, space, and underscore insensitive,
                                   and may contain `*` and `?` as wildcards.
                                   Examples: --removekeywords name:Lib.HugeKw
                                             --removekeywords name:myresource.*
                          tag:<pattern>:  remove data from keywords that match
                                   the given pattern. Tags are case and space
                                   insensitive and it is possible to use
                                   patterns with `*` and `?` as wildcards.
                                   Tags and patterns can also be combined
                                   together with `AND`, `OR`, and `NOT`
                                   operators.
                                   Examples: --removekeywords foo
                                             --removekeywords fooANDbar*
```

**Comment by UmaShanmuga** [comment]
Hi bkhouri. Thanks for your comments. For one of our application, We dont have or can't create a test account . That's the reason using real account credentials for login. I tried the above methods of removekeywords. But does'nt suffice our need. It only removes the data of the specified keyword not the arguments from log. Let me know if there is any other alternative way.

**Comment by pekkaklarck** [comment]
There's no built-in functionality for exactly this use case, but there are several possible solutions:

1. Use `--removekeywords` as already proposed by @bkhouri. Notice that you need to remove keywords starting from the parent keyword like `--removekeywords name:InitializeTestcase`.

2. Use `--flattenkeywords` instead of `--removekeywords`. This option leaves all internal keyword messages into the log file and thus isn't as destructive as `--removekeywords`. See the User Guide for more information about these options.

3. Specify secret data using variables like `${USERNAME}` and `${PASSWORD}`. When used as arguments for keywords, the log only shows the variable name, not the value, but you need to be careful that your keywords don't log the actual value. If you need to, you can even omit the real values from the test data, and pass variables from the command line by using `--variable USERNAME:umsomasu --variable PASSWORD:asdf` or, if there are more variables, by using the `--variablefile` option. See the User Guide for details. 

4. Use `--prerebotmodifier` to remove or mangle data you want. This requires custom coding (see the User Guide again) but ought to be pretty easy.

5. Try to avoid this problem altogether by using test systems with know passwords or test accounts in real systems. I know this isn't always possible, but in general I'd consider this the best option.

If this functionality would turn out to commonly needed, we could consider adding a functionality to remove/mangle arguments of certain keywords. Implementation could be pretty much the same as in the option 4. above and ought to be simple. The main objection I have is adding yet-another-command-line-option like `--removearguments`. The `--rerebotmodifier` option already exists to allow custom modifications, and I got a feeling this isn't common need enough to require anything more. What do others think?

**Comment by pekkaklarck** [comment]
Apparently no further interest. Closing.

**Comment by karthikcat** [comment]
@pekkaklarck 

Hi ,
Do you have any custom modified code for --rerebotmodifier , not to display all the values in the  log file for --variablefile ?
