### ISSUE TITLE
Using "Set Tags <tag>" Then --rerunfailed -e <tag> Still Includes Tests With Set Tag

### ISSUE THREAD

**Issue by f0zz** [robotframework/robotframework#2645]
During some of our tests, we don't want the test to be included in the rerun when using --rerunfailed because it will always fail. For example, when a test case successfully executes a "Delete Object" keyword, we don't want to include that test in the rerun because the object has already been deleted, which means the test will always fail. 

Thus, after the "Delete Object" keyword, we use "Set Tags" to add the "NoRerun" tag to the test. However, when calling "--rerunfailed" with "-e NoRerun", the tests that had that tag added via "Set Tags" are still included in the rerun.

When using the -e argument with tests that have tags set via the [Tags] section, it works as expected and doesn't include those tests even if they failed.

Robot Framework version 3.0
Python version 2.7.13

Steps to Reproduce:

1. Create a new test case with 2 keywords: "Set tags      NoRerun" followed by "Fail"
2. Execute the test case and note the location of its output file.
3. Execute a "--rerunfailed" with the option "-e NoRerun" against the output file created by step 2
4. Note that the test still gets rerun.

**Comment by pekkaklarck** [comment]
You are right, when using `--exclude`, tags are only read from the source data and additional data provided using `--rerunfailed` is not considered. We can consider changing this, but I'm not sure are the benefits big enough compared to the possible problems.

The main problem I see is deciding what data to read from the data provided using `--rerunfailed`. You can dynamically during execution alter at least tests tags and documentation, and if we start looking at dynamically modified tags, the most logical solution would be copying all tags and the doc from the executed test to the original test. This may not always be desirable, though, and at least the change wouldn't be fully backwards compatible. Just using the tags of the executed test to decided is a test included or not is safer, but it would be somewhat strange if test that gets included when using `--include sometag` doesn't actually have `sometag` after execution.

Because of the possible problems I'm not too eager to add this feature but I'm not totally against it either. You could say that on a scale from `-1` to `+1` I'm `-0`. Getting the enhancement in would, first of all, require someone interested to provide a pull request with the code changes, tests, and documentation updates. This person should then ask general consensus about the change from the community at least on robotframework-users mailing list.

Notice also that you can implement this functionality yourself by using the `--prerunmodifier` functionality. That might be the easiest solution for this kind of a somewhat special case.

**Comment by f0zz** [comment]
Thanks for the quick response. I'll talk to my team to see how we want to proceed. Is it ok for me to leave this open?

**Comment by pekkaklarck** [comment]
Any new insight about this?

Notice that you could workaround this problem by using `rebot` between executions to remove tests from the output.xml file:

    robot tests.robot
    rebot --exclude NoRerun --output rerun.xml --log NONE --report NONE output.xml
    robot --rerunfailed rerun.xml tests.xml

**Comment by f0zz** [comment]
I used what you suggest with `rebot` and it worked just fine. Thanks.

**Comment by pekkaklarck** [comment]
Great!
