### ISSUE TITLE
Acceptance tests don't work in py3

### ISSUE THREAD

**Issue by Brian-Williams** [robotframework/robotframework#2675]
# Summary
The atest structures were never converted to be py3 compatible.

## Immediate fix
Replace mix of bytes and string comparisons with all strings. Replace all print keywords with print function calls. Fix unichr calls.

## Long term fix
Setup CI against py3.x, so that these issues can be caught.

**Comment by Brian-Williams** [comment]
I have some of the fixes above in [this](https://github.com/Brian-Williams/robotframework/tree/testing) branch.

**Comment by pekkaklarck** [comment]
Acceptance tests runner side working only with Python 2 is actually by design. There are no real benefits in supporting both Python 2 and Python 3 when you anyway must have both available to be able to test the framework itself on both of them. More importantly, there are absolutely no benefits in spending time testing that such code works with both Python 2 and Python 3.

Instead of changing the code to work both with Python 2 and Python 3, we should make it Python 3 only. This avoids all the annoyances required when writing Python 2 and 3 compatible code, removes the need to test on both variants, and makes it possible for us to use all the goodies Python 3 has. I'd actually go as far as saying that we can make the runner side Python 3.6+ only to be able to use the great `f'string'` syntax. That's what I already did with https://github.com/robotframework/rellu/.

The CI issue is important. We used to have comprehensive CI but it was maintained by a company not involved with Robot Framework anymore. Back then we executed tests with Python (2.6-3.5), Jython and IronPython on Linux and Windows, and AFAIK this is not something Travis can provide. I'm fairly certain we get CI organized somehow via [Robot Framework Foundation](http://robotframework.org/foundation/), but I've got other more important tasks and haven't spent time with that. I hopefully have time to start RF 3.1 development this autumn and then working CI is a must.

**Comment by Brian-Williams** [comment]
Ah, that makes a lot of sense.

I wasn't aware robot was planning on dropping py2 support with more than a year left of py2 support. Glad to hear it though!

Travis only supports linux and osx. I don't know of a free to open-source CI tool that currently includes windows as an os option. I've only used gitlab ci, travis and shippable and know that shippable has windows support on their roadmap.

```
os:
  - linux
  - osx
```

I will close this issue as it is invalid. Would you like me to leave the [pull](https://github.com/robotframework/robotframework/pull/2676) open as a half-measure until a more comprehensive Robot Framework Foundation guided implementation can be added?

**Comment by pekkaklarck** [comment]
We aren't planning to drop Py2 support! From dev point of view it would be awesome, but from community perspective it would be a disaster.

It just doesn't matter what language we use with development tools and utilities. At the moment our own stuff is mainly Python 2, but we could (and should) use Python 3 too. They could as well be written using Ruby, Perl, or anything else, but I can assure you that's not going to happen. :)

If you are interested, run_atest.py could be converted to Python 3(.6). What I don't like is these tools to get any more complicated in order to support both Py 2 and 3, and to lose the ability to use Py 3(.6) goodies.

CI is something I'd like to discuss more. Can we do it on Slack?
