### ISSUE TITLE
Keyword varargs doesn't work properly with named arguments

### ISSUE THREAD

**Issue by laurioikarinen** [robotframework/robotframework#2683]
Keyword varargs don't seem to work properly with named arguments. Even after reading the documentation ( http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#variable-number-of-arguments) I'm not sure if this is a bug or a feature in current version, but improving this would allow making the code more readable.
Using Robot Framework 3.0.2 with Python 2.7.12 in Ubuntu 16.04 LTS

Example code to test this:
```
*** Settings ***
Documentation    Test varargs with named arguments

*** Test Cases ***
Test Varargs
    Keyword With Varargs    Keyword With Named Arguments   value1   value2   value3
    Keyword With Varargs    Keyword With Named Arguments   value1   arg2=value2   arg3=value3
    Keyword With Varargs    Keyword With Named Arguments   valueA   arg3=valueC   arg2=valueB

*** Keywords ***

Keyword With Varargs
    [Arguments]    ${keyword}   @{varargs}
    Run Keyword    ${keyword}   @{varargs}

Keyword With Named Arguments
    [Arguments]     ${arg1}=    ${arg2}=value2    ${arg3}=value3
    Log              ${arg1} ${arg2} ${arg3}
    Log To Console   ${arg1} ${arg2} ${arg3}
```

When executed, I get the following
```
==============================================================================
Varargs :: Test varargs with named arguments                                  
==============================================================================
Test Varargs                                                          value1 - value2 - value3
.value1 - arg2=value2 - arg3=value3
.valueA - arg3=valueC - arg2=valueB
Test Varargs                                                          | PASS |
------------------------------------------------------------------------------
Varargs :: Test varargs with named arguments                          | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================
```

What I expect to be printed to the console from the log to console keywords is
```
value1 - value2 - value3
value1 - value2 - value3
valueA - valueB - valueC
```
So it looks like varargs doesn't set named arguments as one might assume. Of course workaround is to always give arguments positional, but that makes the code less readable and all arguments must always be given since default values can't be used.

**Comment by pekkaklarck** [comment]
Everything seems to be as currently designed. When you use keyword with arguments like `arg2=value2   arg3=value3` and the keyword doesn't have argument matching them (i.e. `arg2` and `arg3`) or doesn't support free keyword arguments, those arguments you use are passed as literal strings. In your case ` @{varargs}` will thus contain strings `arg2=valu2` and `arg3=value3`. When you use this variable, the strings it contain are sent as normal positional arguments. If you want to accept and pass forward free keyword arguments, you should use `&{kwargs}` syntax instead of `@{varargs}`.

The example does actually show one bug or bad design in the framework. When you the name `name=value` syntax and you don't have arguments matching `name`, the framework should actually consider that a failure. The current approach to pass arguments as literal stings in that case causes annoying problems if there are typos in data, argument names change, and so on. We should consider `name=value` to always mean named argument syntax and require using `name\=value` when the whole value is a literal string. We've already decided that we'd like to change the syntax, but the change is so badly backwards incompatible that it cannot be done overnight.

**Comment by laurioikarinen** [comment]
Thank you for the extremely quick response. Your proposal works perfectly!
