### ISSUE TITLE
Possibility to automatically expand certain keywords in log file

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#2698]
When opening a *log.html* file, all failed suites and keywords are shown directly (auto expanded).

I suggest a new **rebot** cli argument **--autoexpand keyword**
in order to auto expand all matching keywords when opening a **log.html** file (e.g. **Take Screenshot** or SelemiumLibrary.**Capture Page Screenshot**).

**Comment by pekkaklarck** [comment]
Sounds useful but would probably be somewhat complicated to implement. The main complexity is due to the fact that logs are dynamically created while you open keywords, and automatically opening some of the keywords would likely take a lot of time with larger log files. Most likely the list of keywords to open should be collected already when generating the log file so that unnecessary keywords wouldn't need to be opened. If this would be implemented, I'd like to support keyword tags as well as names similarly as e.g. `--removekeywords`.

Are you interested to implement this yourself?

**Comment by DirkRichter** [comment]
I tried, but run into trouble.

The problem is: The expandDecider do not know anything about child's and keywords inside. Scanning all child's and subchild's is not an option. But: expanding nodes with status=FAIL works, because the status is propagated to mother nodes. A similar **expandStatus* is needed in stored data, which is a complex change.

Currently we have a workaround: we make screenshots in teardown when tests fails and apply a postprocessing to replace the default expandDecider with a more powerfull custom version, which is a kind of hack and not suited for a pull request. Thus: this topic is not urgent :-)

**Comment by pekkaklarck** [comment]
Are you @DirkRichter still interested in this enhancement? As I commented above, this could be implemented by collecting ids of keywords to be opened, writing that to the log file, and log file then opening the listed keywords.

**Comment by DirkRichter** [comment]
Hi. Thanks for your hints. Yes we are still interested in this (on my todo list). But currently the topic is not top priority due to the workaround.

**Comment by pekkaklarck** [comment]
PR #3118 looks so promising (and safe) that I'll add this to RF 3.1.2 scope.

**Comment by pekkaklarck** [comment]
Talked with @DirkRichter on Slack and he doesn't have time to finalize PR #3118 in time for RF 3.1.2. Moving to RF 3.2 scope.

**Comment by pekkaklarck** [comment]
Are you @DirkRichter still interested in this issue? RF 3.2 is getting ready and if we want this in, PR #3118 should somewhat soon be finalized.

**Comment by jura84** [comment]
I would like to know the reason behind this.

IMHO, this feature would not bring much value.
When having +1000 tests and some might use common keyword and expanding all of them might cause intresting HTML view.

How we solved the reporting challenge is that we established DB which stores all results and if we are instested on certain things then we just query DB or create a view based on needs.
I know, kind of heavy solution but still..

Instead of doing tweaks to HTML view, I would spend more time to redesign HTML view to have more functionality using CSS, Javascript etc.

Any comments from @pekkaklarck ? :)

**Comment by pekkaklarck** [comment]
This obviously doesn't solve all reporting problems, but I can see it being useful in many cases. Incidentally someone just yesterday asked about exactly this functionality on our Slack.

This issue doesn't mean that external reporting solutions wouldn't still be useful, especially if you have lot of test, nor that logs/reports couldn't be enhanced otherwise. If you @jura84 have concrete ideas related to the latter, please submit an issue.

**Comment by pekkaklarck** [comment]
Thanks to PR #3118 by @DirkRichter this issue is done!
