### ISSUE TITLE
Tags using variables does not work

### ISSUE THREAD

**Issue by sushengwang** [robotframework/robotframework#2702]
I need to update the tags real-time by scene on suit setup.
The testcase show that ${HOST} in tags decoded as a string but variables :

root@vm:/home/temp# robot --version
Robot Framework 3.0 (Python 2.7.6 on linux2)
root@vm:/home/temp# 
root@vm:/home/temp# cat testTag.txt 
*** Settings ***
Force Tags      req-42
Default Tags    owner-john    smoke

*** Variables ***
${HOST}         10.0.1.42

*** Test Cases ***
Own tags with variables
    [Documentation]    This test has tags host-10.0.1.42 and req-42.
    [Tags]    host-${HOST}
    No Operation
root@vm:/home/temp# 
root@vm:/home/temp# robot  -i 'host-10.0.1.42' testTag.txt
[ ERROR ] Suite 'testTag' contains no tests with tag 'host-10.0.1.42'.

Try --help for usage information.
root@vm:/home/temp# 
root@vm:/home/temp# 
root@vm:/home/temp# robot  -i 'host-${HOST}' testTag.txt
==============================================================================
testTag                                                                       
==============================================================================
Own tags with variables :: This test has tags host-10.0.1.42 and r... | PASS |
------------------------------------------------------------------------------
testTag                                                               | PASS |
1 critical test, 1 passed, 0 failed
1 test total, 1 passed, 0 failed
==============================================================================

**Comment by pekkaklarck** [comment]
Variables in tags are resolved only after test execution starts and thus you cannot use `--include` and `--exclude` with variable values. This behavior won't change because variables cannot be fully resolved before execution and I don't think it makes sense to resolve them in two phases. As you've already tested, you can use `-i 'host-${HOST}'`, though. Logs and reports will show tags with variables resolved.

You mention something about suite setups but your example doesn't have any. If you would change variable value there, it should affect the actual value tag has.
