### ISSUE TITLE
Power function "**" not working as in Python - incorrect result

### ISSUE THREAD

**Issue by eniemela3** [robotframework/robotframework#2708]
I recently posted this on the RIDE page (https://github.com/robotframework/RIDE/issues/1729) but it seems to be a Robot Framework bug instead.

Here is what I do in Robot Framework. I try to square -3 stored in a variable, to result in 9:
~~~~
Calculation
    ${value}= Set Variable -3
    ${result}= Evaluate ${value}**2
    Log To Console ${result}
~~~~
This results in -9, which is incorrect:
~~~~
Starting test: Power Monitor.Calculation
20171108 10:17:44.663 :  INFO : ${value} = -3
20171108 10:17:44.663 :  INFO : ${result} = -9
Ending test:   Power Monitor.Calculation
~~~~
Trying this out in python:
~~~~
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> var = -3
>>> var**2
9
~~~~
It seems that Robot Framework does not recognize a negative value stored in a _variable_ when squaring it with "\**", but instead treats the calculation as -3**2 = -9. Whereas Python computes it as (-3)**2 = 9.

**Comment by pekkaklarck** [comment]
No, this is not Robot Framework bug, the behavior comes directly from Python:

```python
Python 3.6.2 (default, Jul 29 2017, 00:00:00) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> -3**2
-9
```

The reason you got 9 is that you assigned `-3` to a variable first. Why that matters is that the reason for this seemingly strange behavior is operator precedence. Python evaluates `-3 ** 2` as `-(3 ** 2)`. As I already commented the RIDE issue you submitted, you need to use `(-3) ** 2` to get the result you want.

I agree it's odd that `-3 ** 2` yields `-9` but because this is how Python behaves there's nothing `Evaluate` keyword can do about it. The point of that keyword is that evaluate Python expressions, and it behaving differently than Python does would be a bug. If you feel strongly about this, you can submit an issue to Python's issue tracker. I'm fairly certain there's some good reason behind this behavior, though, and even if there wasn't I doubt they wouldn't be ready to do such a backwards incompatible change.

The best solution for this problem would be implementing a separate keyword (or perhaps a library) for handling calculations.

**Comment by eniemela3** [comment]
My point is, I am also assigning the value into _a variable_ first in Robot Framework:
~~~~
${value}= Set Variable -3
~~~~
Or am I incorrect in assuming that Set variable creates a variable and assigns it a certain value? If so, is there another keyword that would 1) create a variable and 2) assign a value to it.
Or is there a problem with the Evaluate statement? If so, is there a better way to correctly evaluate mathematical expressions of values stored into variables?

I completely understand your point about operator precedence, and your examples follow the rules I am familiar with. What I am trying to show that when a value is first stored into _a variable_, it is treated differently in Robot Framework vs Python.

**Comment by trogdor259** [comment]
What he's saying is to wrap your variable in parentheses for your Evaluate function.  

> Calculation
    ${value}= Set Variable -3
    ${result}= Evaluate ${value}**2
    Log To Console ${result}

Becomes
> Calculation
    ${value}= Set Variable -3
    ${result}= Evaluate (${value})**2
    Log To Console ${result}

**Comment by pekkaklarck** [comment]
The problem is that you are assigning it into Robot's variable that is resolved *before* the expression is evaluated. This is explained at http://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Evaluating%20expressions
