### ISSUE TITLE
Execute step-by-step from command line

### ISSUE THREAD

**Issue by bnccg** [robotframework/robotframework#2737]
It would be fantastic to have the possibility to execute step-by-step a test case from command line. 

Although the main usage is fully automatic, when we need to execute the test case in front of clients, in some tests, the client requests to 'go slower' and see the execution step by step. 

Thanks!

Bruno

**Comment by pekkaklarck** [comment]
This can be pretty easily implemented by using the [listener interface](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#listener-interface). Just implement the `start_keyword` method so that it stops until the user presses enter or implement a GUI if you want to be fancy. Such a tool could be generic, but I think it would be best to have it outside Robot Framework core.

**Comment by bnccg** [comment]
Thanks, I'll take a look on this.

**Comment by pekkaklarck** [comment]
Listener implementing this could be as simple as this:

```python
ROBOT_LISTENER_API_VERSION = 2

def start_keyword(name, attrs):
    raw_input('Keyword "%s" starting. Press enter to continue.' % name)
```
