### ISSUE TITLE
Log/Report generation during execution

### ISSUE THREAD

**Issue by bnccg** [robotframework/robotframework#2738]
When the list of tests and/or the test duration is high, there is no easy way to see the current status. 

We can add a full set of console messages to try to get the status, but would be nice if the report & log is generated after some predefined time (ex: 1 minute), with the status of the executed tests/keywords.
Each log/report generation would overwrite the previous, allowing to easily see the advance.

Many thanks!

Bruno

**Comment by pekkaklarck** [comment]
I can see your problem, but implementing this in the framework would be a really big task. The current logic to generate logs/reports excepts execution to be done, and the logic is also highly optimized both to be as fast as possible and, even more importantly, to generate as small log files as possible. I personally have no interest to rewrite all that, and I doubt anyone else would be willing to do it either.

This logic should also be somehow configurable, because in most cases you wouldn't want execution to be slowed down to generate intermediate logs. This makes the usage more complicated, as you needed to somehow be able to tell when to create logs, should new logs contain all information or only info not in earlier logs, should logs be overwritten, and so one. A lot simpler solution is splitting long execution to smaller pieces and having a script to run these pieces in a sequence. This way you have full control when to create logs etc. It might be possible to create a generic  tool to handle this, but such tool should be implemented as an external project.

**Comment by bnccg** [comment]
In my (naive & simplistic) understanding of robot, the results are being gathered constantly, and 'just' the trigger of the XML/HTML generation is to be done. 

I thought about the options:
- The framework is not used for real-time testing, therefore there is no big deal in slowing down during generation (the beneffit of having the information is higher than the cost)
- The trigger by time is the easiest way, there is no need to add other options. This solution works for all scenarios: multiple & quick tests , veeeery long tests (more tan 1 day), etc. Just at a periodic time, trigger the generation of the XML/HTML.
- The information is just the same as the log/report. No need to generate an aditional report.

Maybe after this explanation the approach is clearer/simpler? 

Since I don't have knowledge of the internals, I can understand the reasons :-). 

Thanks!

**Comment by pekkaklarck** [comment]
Some of the information is collected into memory, but details needed to create log files are only in output.xml files. This causes the following problems in addition to the issue I already explained:

- The output.xml file is not finished. Not sure how XML parsing modules handle such files.
- Due to buffering, all the content that has been written to the file is likely not even written to the disk yet. We could force flushing but that makes execution IO bound.

Also, there are *a lot* usages where test execution speed is *very* important. We've spent a lot of time to speed it and definitely aren't interested to do changes that slow it down considerably. Most of the users running reasonable long test runs on CI aren't interested in full intermediate results either. If your test runs get overly long, splitting them into smaller batches is a good idea anyway. For following test execution live, you can also implement solutions using the listener interface.
