### ISSUE TITLE
Custom string subclasses not always handled correctly (e.g. `Convert To Integer`)

### ISSUE THREAD

**Issue by pkomarov** [robotframework/robotframework#2739]
Hi,

Starting from robot 3.0.1 we are facing an issue using Convert To Integer keyword. Test case is constructed in the following way:

```
${result}=  SOAP Get Some Entity ${entity_id}
${val}=  Conver To Integer  ${result.entityAttr9}

```
Conver To Integer keyword fails with error: "'0' cannot be converted to an integer: AttributeError: 'NoneType' object has no attribute 'join'"

${result} looks like this:
```
(entity){
   id = 129988.0
   entityAttr1= "Some Text"
   entityAttr2= 1.0
   entityAttr3= 224.0
   entityAtt4= 0.0
   entityAttr5= 0.0
   entityAttr6= 0.0
   entityAttr7= 2.0
   entityAttr8= 2015-04-29 11:07:43
   entityAttr9= "0"
   entityAttr10= 8.0
   entityAttr11= "0"
   entityAttr12= 0.0
 }

```
An exeptions comes from normalize function of utils module of robot libraries. In new versions of robot framework some new constructions was added. 

```
empty = type(string)()
if spaceless:
        string = empty.join(string.split())
```
In case of our test string is not of type string but class 'suds.sax.text.Text', which `__new__()` operator returns None in case no arguments (or first argument is None) were passed into it, so the exception is thrown on joining. Since there is no explicit prohibition on returning None from a `__new__()` operator creating an issue on robot. Please handle this case in your function. Something like 

```
tmp = type(string)()
empty = tmp if tmp is not None else ''
if spaceless:
        string = empty.join(string.split())
```

Thanks in advance, Pavel.

**Comment by pekkaklarck** [comment]
The change that caused this problem was done to handle both bytes and Unicode with Python 3, but it didn't take into account custom string types that cannot be initialized without arguments. I would say `suds.sax.text.Text` inheriting `unicode` but having incompatible `__init__` is a bug in itself, but we can also fix this easily by using this instead:

```python
empty = u'' if is_unicode(string) else b''
```

Need to add a unit test as well, but don't want to depend on `suds.sax.text.Text` when creating that. Perhaps could use this kind of a class instead:

```python
class BrokenString(str):
    def __init__(self, value):
        str.__init__(self, value)
```
