### ISSUE TITLE
There should be generic way to get library version (remote, local)

### ISSUE THREAD

**Issue by sampeson** [robotframework/robotframework#2773]
there should be generic way to get library version (ROBOT_LIBRARY_VERSION) over remote library. For local Python libraries there is  __version__ way for python libraries that are local. 

Would be good if we could have generic keyword 'Get Library Version' in BuiltIn that could be used against what ever library type (remote, local) and then support for this in remote interface.

My need is to to make check in test data side that library versions are new enough (and remote library connection is OK) for user convenience.

**Comment by pekkaklarck** [comment]
There are actually two separate proposals here:

1. Add a keyword to get the library version.
2. Make it possible to get the version of the remote library.

I don't like the first proposal too much because in the test data you shouldn't anymore care about library versions. Checking them is something that should be done already before execution. Also, the library version ought to be available via the library itself that you can get using `Get Library Instance` keyword.

The second proposal has much more merit because at the moment there's no generic way to get the library version over the remote connection. Adding such functionality means that we need enhancements to the Remote library interface itself. That means we need to be careful with the design and also that this is quite a lot of work.

**Comment by pekkaklarck** [comment]
Is this still relevant for you @sampeson?

**Comment by sampeson** [comment]
Not at the moment. We implemented the keyword to (remote)library.

**Comment by pekkaklarck** [comment]
Not important. Closing. As I commented earlier, the second part of the proposal could be considered. Please submit a new issue if that becomes relevant again.
