### ISSUE TITLE
How do I stop a long-running test prematurely, but continue with other tests

### ISSUE THREAD

**Issue by abhaybhargav** [robotframework/robotframework#2775]
I have a test that is a long running test, that I may need to stop prematurely. However, when I click on Ctrl + C, I end up stopping all other tests as well. Is there a way out? Is there another signal that would led me stop this and skip to the next test?

**Comment by bkhouri** [comment]
Your issue is a support question,band those should be directed  to a support forum as this issue list reflect problems) enhancement requests to the core robotframwork.Have a look at robotframwork.org and go to the Support section to find various ways of asking your question.Bassam                                                                                                                                                                        Sent via the BlackBerry Hub for Android                                                                                                                                                                           From: notifications@github.comSent: February 15, 2018 3:41 AMTo: robotframework@noreply.github.comReply-to: reply@reply.github.comCc: subscribed@noreply.github.comSubject: [robotframework/robotframework] How do I stop a long-running test prematurely, but continue with other tests (#2775)  I have a test that is a long running test, that I may need to stop prematurely. However, when I click on Ctrl + C, I end up stopping all other tests as well. Is there a way out? Is there another signal that would led me stop this and skip to the next test?

**Comment by pekkaklarck** [comment]
No, there's no other signal but test and keyword timeouts can used instead. See the User Guide for details.

Separate signal could perhaps be nice too, but it wouldn't work on Windows and depending on where the test is hanging couldn't always stop the test. If someone considers it important enough to be interested to implement it, please comment here and we can reopen the issue.

**Comment by abhaybhargav** [comment]
My apologies. I had seen similar questions on here so I asked. I have kinda-sorta solved the problem with `[Timeout]`
