### ISSUE TITLE
Collections Keywords for Dictionary objects requires Scalar Variable Syntax

### ISSUE THREAD

**Issue by endqwerty** [robotframework/robotframework#2780]
# Version information
Robot Framework version: `3.0.2`
Python interpreter: `Python3`
Operating system: `OSX 10.13.3`

# Issue
The keywords for interacting with dictionary variables require passing the dictionary using scalar syntax instead of the dictionary syntax.

# Expected
    &{dictionary}    name=arg
    Dictionary Should Contain Key    &{dictionary}    key   message

# Actual Working
    &{dictionary}    name=arg
    Dictionary Should Contain Key    ${dictionary}    key   message

**Comment by pekkaklarck** [comment]
This is by design. If you use a variable like `&{var}`, then it's items are passed as individual arguments as `name=value`. To pass the value as a dictionary, you need to use `${var}`. This is explained in the User Guide but I'm sure the docs could be enhanced:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#dictionary-variables

Let us know if you have ideas how to enhance the docs.
