### ISSUE TITLE
Dynamic index should be supported in Collections

### ISSUE THREAD

**Issue by lusheldon** [robotframework/robotframework#2786]
Thank you for your working firstly.
Recently, I was try to use Collections in this way:
```
@{b}  create list    1    2    3    4    5
:For     ${i}    in range    100
    ${a}    set variable    @{b}[${i}%5]
```
Above is just a simplified example. But I can't get the correct items in @{b} because Collections seems do not accept the dynamic index [${i}%5].

So will this feature be supported in the future? Any reply would be appriciated.

**Comment by VVasyaev** [comment]
how about
`${b[${i}%5]}`
?

**Comment by lusheldon** [comment]
@VVasyaev No, this does not work. 
`Resolving variable '${cust_info_list[0/2][0]}' failed: TypeError: 'NoneType' object has no attribute '__getitem__'`

**Comment by VVasyaev** [comment]
@lusheldon there are at least two workarounds:
the frist one:
```
${j}    Set Variable    ${i}%5
${value}    Collections.Get From List    ${b}    ${j}
```

the second one:
```
${value}    Evaluate    $b[${i}%5]
#pls see that there are no braces near the b-variable
```

**Comment by lusheldon** [comment]
Following your code, I found these code also works for me
```
${a}    evaluate    ${b[${i}%5]}
log    ${b[${i%5}]}
```

**Comment by pekkaklarck** [comment]
List indices being automatically evaluated in Python is itself a good idea. The problem is that same syntax is used also with dictionaries like `&{dict}[key]` and the change would require quoting keys like `&{dict}["key"]`. Adding quotes is extra work and, more importantly, the change would be backwards incompatible. As discussed above, there are already ways to evaluate keys, so the benefits wouldn't be that big. Due to smallish benefits and big backwards incompatibility reasons, I agree this issue should be closed.
