### ISSUE TITLE
Enhancement Request:start_keyword/end_keyword api can access nested keywords information by name or tag,etc

### ISSUE THREAD

**Issue by toniah** [robotframework/robotframework#2811]
in start_suite/test, kws can contains keyword names of keywords in this suite/test
but in start_keyword, using the same method, we get empty result when accessing  names of keyword invoked by this keyword
We use prerun modifier to filter keywords by keyword name since keyword tags do not have filtering function during test run

**Comment by pekkaklarck** [comment]
There are various interfaces with `start/end_keyword` methods, but because you are using pre-run modifiers you seem to be using the visitor interface with the executable test suite model. In this case `start/end_keyword` methods no nothing about the child keywords simply because Robot hasn't yet resolved what these keywords are going to be. If your test has a keyword like `My Keyword`, Robot doesn't at this point know where it is coming from. It hasn't, in fact, even imported any libraries or resources. Because keyword resolution is done dynamically depending on the exact execution context at that point, this cannot be changed.

Notice that if you were using the visitor interface with the result objects, child keywords would be available.
