### ISSUE TITLE
`pip install -I` corrupts `robot.bat` if Robot Framework is already installed

### ISSUE THREAD

**Issue by AnttiPohjonen** [robotframework/robotframework#2817]
When re-installing Robotframework with pip option -I, pip doesn't uninstall old version first. This causes setup.py script line 83 cause problems, if Python is installed on directory which name includes python.
e.g.
default c:\Python27\

Running 'pip install -I robotframework' causes recursive path declaration in robot.bat,
_c:\c:\python27\python.exe27\c:\python27\python.exe.exe -m robot.run %*_ 
This should be quite easy to fix in setup.py

**Comment by pekkaklarck** [comment]
This problem occurs only on Windows where our installation system modifies created `robot.bat` and `rebot.bat` scripts. That's going to change in RF 3.1 (#2415) when we switch to `robot.exe` and `rebot.exe` files and this issue will be fixed as well. The problem could also be fixed in the current installation system, but this isn't severe enough to warrant one more RF 3.0.x minor release.
