### ISSUE TITLE
log.info can't work in class __init__ function

### ISSUE THREAD

**Issue by wangliyao518** [robotframework/robotframework#2844]
from robot.output import LOGGER

class ta_user_lib(object):

    VERSION = '1.5.2'
    def __init__(self):
         ....
         LOGGER.info('talib name:{} version:{}'.format('ta_user_lib', ta_user_lib.VERSION ))
         # the above log will not show in log.html and output.xml, only we change info to warn or error this information then can display in the output.xml and log.html
   def user_keyword(self):
         LOGGER.info('this log can display in the log.html and output.xml')

the LOGGER.info in __init__ function can't output the message to output.xml and log.html, but when we change info to error or warn then it can work, meanwhile the LOGGER.info in user_keyword function can output message to output.xml and log.html

**Comment by pekkaklarck** [comment]
This is the expected and documented behavior: http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#logging-during-library-initialization

Notice also that  you shouldn't use `robot.output.LOGGER` because it's not part of the public API and is very likely going to change in the future. The public API is documented at http://robot-framework.readthedocs.io/.
