### ISSUE TITLE
Support true copies (i.e. `deepcopy`) with `Copy List` and `Copy Dictionary`

### ISSUE THREAD

**Issue by scathaig** [robotframework/robotframework#2850]
copy_list and copy_dictionary return shallow copies allowing the given lists/dicts to be altered by modifying the copies (in contrast to the documentation)

```
*** Settings ***
Library           Collections

*** Test Cases ***
nested dict
    ${x2}    Create Dictionary    x2    1
    ${a}    Create Dictionary    x1    ${x2}
    ${b}    Evaluate    copy.deepcopy(${a})    copy
    ${c}    Copy Dictionary    ${a}
    Set To Dictionary    ${b['x1']}    x2    2    # modify copy
    Set To Dictionary    ${c['x1']}    x2    3    # modify copy
    Should Not Be Equal    ${a['x1']['x2']}    ${b['x1']['x2']}    # deepcopy works
    Should Not Be Equal    ${a['x1']['x2']}    ${c['x1']['x2']}    # copy_dict does not

lists
    ${dict}    Create Dictionary    a    1
    ${a}    Create List    ${dict}
    ${b}    Evaluate    copy.deepcopy(${a})    copy
    ${c}    Copy List    ${a}
    Set To Dictionary    ${b[0]}    a    2    # modify copy
    Set To Dictionary    ${c[0]}    a    3    # modify copy
    Should Not Be Equal    ${a[0]['a']}    ${b[0]['a']}    # deepcopy works
    Should Not Be Equal    ${a[0]['a']}    ${c[0]['a']}    # copy_list does not
```

using copy.deepcopy() fixes this and should be used in the keywords.

**Comment by chriscallan** [comment]
While it is nice to have deep copies of everything all the time that process is more memory intensive and slower than the default shallow copies.  If you require deep copies for your tests, you can always wrap that method in a user-defined method and you're off to the races.
IMO, opting for a shallow copy to save time & resources is the safer option for the 80%, where performance is of more concern than deeply copied lists/dicts.  Certainly could be added via a PR, probably call them "Deep Copy List|Dictionary" or something else, but I think the user-defined keywords is the better way to go.  Modifying the core methods would introduce breaking changes to existing code in order to handle your cases.
Heck, we all have a library of useful stuff from previous projects that we've come to rely on.

**Comment by pekkaklarck** [comment]
Good catch that 'copy.deepcopy` would be safer, and match keyword documentation better, than `copy.copy`. As @chriscallan commented, the former is more resource hungry which may be a problem in some cases.

What about making in configurable which approach to use? For backwards compatibility reasons we could keep the current behavior as the default, and add an argument like `deepcopy=False` to control the behavior.

**Comment by HelioGuilherme66** [comment]
I agree on having the option `deepcopy=False` by default, and allowing to control the behavior. This is also an advanced feature, that could be set by some environment variable or robot user preferences (thinking about having some configuration file for robot defaults).

**Comment by pekkaklarck** [comment]
This is a valid enhancement. Anyone interested to implement it?

**Comment by pekkaklarck** [comment]
Implemented at [RoboCon 2018](http://robocon.io) sprints.
