### ISSUE TITLE
Document RPA functionality

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#2855]
Issue #2788 added support for RPA but there's no time to document the functionality in the User Guide and elsewhere before RF 3.1 alpha 1. Because the User Guide is not generated with preview releases, this doesn't matter much, but this issue acts as a reminder to do it before the final release.
Documentation to add/update include:

- [x] New User Guide section about the RPA functionality in general:
  - [x] Using `*** Tasks ***` header instead of `*** Test Cases ***`
  - [x] Using `--rpa` both with Robot and Rebot
  - [x] Using `--task` instead of `--test`
  - [x] Using `Task Setup/Teardown/Template/Timeout` settings instead of `Test Setup/Teardown/Template/Timeout`
  - [x] Using `Set Task Variable` keyword instead of `Set Test Variable`
- [x] Update User Guide introduction to mention RPA and talk about automation, not test automation.
- [x] Note to section about creating tests about possibility to using `*** Tasks ***`
- [x] Note to section about test data tables about the Task table.
- [x] List `--rpa` and `--task` in the appendix about all command line options
- [x] Update project README and metadata (`setup.py`) to mention RPA and to talk about "automation", not "test automation" in general

**Comment by laurentbristiel** [comment]
coming late to the party, and read the discussion in #2788, but I still don't understand what is the difference between a "Task" and a "Test". Is it just a name difference because the goal is different (automating anything versus automating a test)? If so, then a "Task" would be written and executed the same way as a test, right? (failing if there is a failing keyword).

**Comment by pekkaklarck** [comment]
Yeah, this is just terminology. No real functional difference.
