### ISSUE TITLE
Rounding problem with `Should Be Equal As Numbers` (and elsewhere)

### ISSUE THREAD

**Issue by skhomuti** [robotframework/robotframework#2872]
`roundup` function is used in the keyword Should Be Equal As Numbers. Due to incorrect rounding, there is an incorrect comparison of two numbers
`Should Be Equal As Numbers      ${59.850000000000364}    ${59.85}    precision=1` gives error:
`59.900000000000006 != 59.800000000000004`

```
from robot.utils.misc import roundup
roundup(59.850000000000364, 1)
59.900000000000006
roundup(59.85, 1)
59.800000000000004
```
Python3.4
RF 3.0.3

**Comment by pekkaklarck** [comment]
The problem is due to rounding errors in the `roundup()` function that we've added to avoid problems with different `round()` behavior in Python 2 and 3. Unfortunately rounding errors cannot really be avoided when working with floating point numbers, and at least I cannot figure out how to change the algorithm to detect the error.

Probably the best solution is changing `roundup` to use the [decimal module](https://docs.python.org/3/library/decimal.html) which also allows controlling the rounding behavior as shown by the answer to [this SO question](https://stackoverflow.com/questions/10825926/python-3-x-rounding-behavior). Unfortunately that solution doesn't seem to work when rounding to negative digits (e.g. `roundup(6, -1)` should yield `10`), but I guess we can use the current implementation in that case.

Related to this, we should look could `Should Be Equal As Numbers` and possibly other keywords working with non-integer numbers use the `decimal` module as well. That would avoid the problem of floating point numbers generally not being able to represent decimal numbers exactly.

**Comment by pekkaklarck** [comment]
Due to `Decimal` not supporting rounding to negative digits I looked at other solutions. I now have a solution that works like this:

1. On Python 2 use the built-in `round()`.
2. On Python 3 check is the number exactly between the values it could be rounded to. If it is, add a little to it (or subtract if the number is negative). Finally use the built-in `round`.

This ought to work fine and in my tests I get same results both when using Python 2 and Python 3.

The problem is that due to the [quirks of floating point math](https://docs.python.org/2.7/tutorial/floatingpoint.html), we may still get wrong or at least unexpected results. For example, `round(2.675, 2)` yields `2.67` both on Python 2 and Python 3 due to `1.15` actually being represented as `2.67499999999999982236431605997495353221893310546875
` which is closer to `2.67` than `2.68`. For the user this problem is pretty much the same as the originally reported problem that `roundup(59.85, 1)` yields `59.8` except that `round(59.85, 1)` actually yields `59.9`.

If wanted to, we could enhance rounding by using `Decimal` instead of the built-in `round()`. We'd still be losing precision if the original number is a float, so I'm not sure is that worth the effort. Those who need to do work with exact number should use the [decimal](https://docs.python.org/3/library/decimal.html or the [fractions](https://docs.python.org/3/library/fractions.html) module in their custom keywords. `Should Be Equal As Numbers` already mentions problems working with floating point numbers, but we could add references to the aforementioned documentation there as well.

**Comment by pekkaklarck** [comment]
Changing priority to low because we may still get "wrong" results in the future as well.

**Comment by pekkaklarck** [comment]
My changes have now been committed. If someone is worried about `round(2.675, 2)` and other similar problems with floating point math, please submit a separate issue about switching to use the decimal module in suitable places. Those interested to learn more about floating point math, can study this excellent post referenced also in the docs of `Should Be Equal As Numbers` and `Convert To Number`:
https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/

**Comment by randomascii** [comment]
Shouldn't the comparison work by subtracting the numbers and only then doing comparisons or rounding? i.e.; subtract and then round the difference or just see if it is less than pow(10, -precision) (or whatever the desired epsilon is)? Doing the rounding before the comparisons seems to add some unnecessary extra stability.

Disclaimer: I'm not familiar with this code base, but I did write the blog post linked above.

**Comment by pekkaklarck** [comment]
Very good idea. That's not exactly related to this particular issue, but I'll submit a new one about it.

Thanks a lot about that insightful article. It went partly above my head, but I certainly learned the key point that floating point math is hard.
