### ISSUE TITLE
`result.errors` is not populated when running suite through `robot.api`

### ISSUE THREAD

**Issue by Tattoo** [robotframework/robotframework#2883]
If one creates a test suite completely programmatically or from a source file and runs it, `result.errors` is not populated:

```python
>>> from robot.api import TestSuite

>>> suite = TestSuite('My suite')
>>> suite.resource.imports.library('Nonexistent')     # causes error
>>> t = suite.tests.create('My test case')
>>> t.keywords.create('No operation')
>>> result = suite.run()
>>> list(result.errors)
[]
>>>
```
or:
```python
### my_suite.robot
*** Settings ***
Library     Nonexistent    # causes error

*** Test cases ***
My test case
     No operation

### python
>>> from robot.api import TestSuiteBuilder

>>> suite = TestSuiteBuilder().build('my_suite.robot')
>>> result = suite.run()
>>> list(result.errors)
[]
>>>
```
Where as if I execute `my_suite.robot`:
`$ robot my_suite.robot`

Then:
``` python 
>>> from robot.api import ExecutionResult

>>> result = ExecutionResult('output.xml')
>>> list(result.errors)
["Error in file 'C:\\Users\\tkairi\\my_suite.robot': Importing test library 'Nonexistent' failed: ImportError: No module named Nonexistent\nTraceback (most recent call last):\n  None\n <redacted>]
```

**Comment by pekkaklarck** [comment]
After a quick look at the code, my somewhat educated guess is that during execution errors are written only to output.xml file. During normal execution that doesn't matter, because output.xml is read if log.html is created and `result.errors` populated then. Similarly, `result` returned by `suite.run` doesn't contain any information about keywords or their messages. That is done to save memory, but that's not a good reason to not store errors. Are you @Tattoo interested to look could `result.errors` be populated already during execution?

A workaround for this problem is parsing output.xml. Basically that would require changing

```python
result = suite.run()
```

to

```python
suite.run(output='output.xml')
result = ExecutionResult('output.xml')
```
