### ISSUE TITLE
How can I get failed suites from output.xml

### ISSUE THREAD

**Issue by PavlovNik** [robotframework/robotframework#2899]
Hi!

Tell me please, does RobotFramefork API have interface for getting informaiton from output.xml? Such as list of failed suites and their source.
Either should I get this information by external Python molules such as xml.etree.ElementTree?
Can you advise me onother Python modules for more quickly reading big output.xml?

Thanks in advance.

**Comment by Tattoo** [comment]
You don't need to parse the `output.xml` yourself. Robot Framework has [programmatic API](http://robot-framework.readthedocs.io/en/latest/autodoc/robot.result.html#example) to do this for you.

Also, this is issue tracker and not a support forum. This kinds of questions should be asked, for example, in the [mailing list](http://groups.google.com/group/robotframework-users) rather than here.
