### ISSUE TITLE
Clarify documentation related to specifying test setup/teardown in initialization files

### ISSUE THREAD

**Issue by weisenic** [robotframework/robotframework#2913]
According to the docs it is possible to define keywords in init files. But somehow this doesnt work in my case. Here is a simple example to reproduce the issue:
content of file 'test.robot':
```
*** Test Cases ***
My Test
    Sleep   1s
    Should Be Equal  1  1
```
and '\_\_init\_\_.robot' in the same directory:
```
*** Settings ***
Documentation    Example suite
Test Teardown      Do Something    ${MESSAGE}
 
*** Variables ***
${MESSAGE}       Hello, world!
 
*** Keywords ***
Do Something
    [Arguments]    ${args}
    Log     ${args}
```
When I'm now running `robot ./` in that directory, the test case failes with a message, that no keyword with name 'Do Something' could be found.
`robot --version` outputs: Robot Framework 3.0.4 (Python 2.7.12 on linux2)
Did I miss something or is this a bug?

**Comment by HelioGuilherme66** [comment]
If your directory is named, for example `testdir` and you step back with `cd ..` and then run the test with `robot testdir`, will it work?

**Comment by pekkaklarck** [comment]
This is somewhat confusing situation caused by these two points:

- As the [documentation explicitly states](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#initialization-files), _variables and keywords created or imported in initialization files are not available in the lower level test suites_.
- `Test Setup/Teardown` are supported and work as default values for setup/teardown for tests in this suite.

The confusing part is that the keyword used as setup/teardown must be available in the test case file where the test is created and, as noted above, keywords created in initialization files are not available there. The keyword thus must be created in the test case file itself or imported to it from a library or a resource file.

I don't think changing the functionality is worth the effort, especially because suddenly making keywords/variables defined in initialization files available in lower level suites would be backwards incompatible change. The docs should be updated, though, to mention that defined test setup/teardown must be available in the test case file. How does that sound for you?

**Comment by weisenic** [comment]
@pekkaklarck ok this makes sense. Moving the keyword to a resource file was the solution that i used in the end. Which is fine since it works and is not such a big deal in the end. 
But it still was very confusing (a coworker of mine spend some time on the same issue aswell).
So yes, updating the docs should to be an approriate solution for this problem.

**Comment by pekkaklarck** [comment]
OK, let's clarify the docs.
