### ISSUE TITLE
robot.utils.plural_or_not does not work correctly with empty lists.

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#2951]
If I have this:
```
from robot.utils import plural_or_not

print('Argument%s:' % plural_or_not([])
```
Then it will print `Arguments` but I was excepting `Argument` 

Was my assumption correct and the [line](https://github.com/robotframework/robotframework/blob/master/src/robot/utils/misc.py#L108): `return '' if count == 1 else 's'` be fixed by changing to: `return '' if count >= 1 else 's'`

**Comment by pekkaklarck** [comment]
This is by design. My understanding is that in English you use the plural form when you have zero items like  `zero dogs` and not `zero dog`.  If you think it's otherwise, please provide a reference.

When logging or constructing error messages, it often makes sense to handle zero/empty case separately. In this case it might be better to have `No arguments.` or just not to mention arguments at all if there are none.

**Comment by aaltat** [comment]
I see. Closing as invalid.
