### ISSUE TITLE
Signal handler registered outside Python causes error

### ISSUE THREAD

**Issue by JonKoser** [robotframework/robotframework#2952]
I am using robot.run in a script of mine, which I execute from another open application, to run some robot tests. Trouble is, I keep getting the following TypeError when I try and execute my script.

![image](https://user-images.githubusercontent.com/9324338/45095799-94c87f80-b0e4-11e8-931e-4db70e86aac5.png)

This is preventing my tests from finishing and tearing down properly.

Upon some inspection, it looks like self._orig_sigint and self._orig_sigterm are getting set to "None" from signal.getsignal()
![image](https://user-images.githubusercontent.com/9324338/45096004-1ddfb680-b0e5-11e8-8aa8-93c28894bf34.png)

Oddly enough, this only happens when I first run my script. If I re-run the script again, it works fine.

I can edit some things myself in signalhandler.py to get it to work, but I'd rather any changes like that come from the official robotframework folks :)

**Comment by pekkaklarck** [comment]
According to the docs of [signal.getsignal](https://docs.python.org/2/library/signal.html#signal.getsignal), it returns `None` if the signal handler has been defined outside Python. In that case we shouldn't try to restore the old value because that won't work. We don't want to leave our signal handler registered either, so I guess we need to either register `SIG_IGN` or `SIG_DFL` when we exit. Probably the latter is better.

It's pretty easy to fix this, but It would be great to be able to create a test for it also. Does anyone know how can we register a signal handler so that `signal.getsignal()` returns `None`? If that's not easy, we can obviously mock it.
