### ISSUE TITLE
New Automatic variable for column names present in data driven test case header

### ISSUE THREAD

**Issue by iamsanjeet** [robotframework/robotframework#2958]
Lets refer below example which is also given in robot framework guidelines:

```
*** Settings ***
Test Template    Login with invalid credentials should fail

*** Test Cases ***                USERNAME         PASSWORD
Invalid User Name                 invalid          ${VALID PASSWORD}
Invalid Password                  ${VALID USER}    invalid
Invalid User Name and Password    invalid          invalid
Empty User Name                   ${EMPTY}         ${VALID PASSWORD}
Empty Password                    ${VALID USER}    ${EMPTY}
Empty User Name and Password      ${EMPTY}         ${EMPTY}
```

If robot can create automatic variable having name same as columns 'USERNAME' and 'PASSWORD'  and value as par each iteration, then it will be very useful in writing test setup and test teardown. For e.g i can write below test setup/teardown:

```
* Settings *
Test Setup  TestSetup
Test Teardown  TestTeardown

* Keywords *
TestSetup
  Create User  ${USERNAME}
TestTeardown
  Delete User  ${USERNAME}
```

Though there are many ways to do this, but as par me this should be the right way.

**Comment by pekkaklarck** [comment]
If I understood this proposal correctly, the idea is to make the values used in data-driven tests accessible in test setup and teardown. That works nicely if a test only contains one iteration or you only want to run setup/teardown once even if there are multiple iterations. It won't, however, work if a test contains multiple iterations like this:

```
*** Settings ***
Test Template    Login with invalid credentials should fail

*** Test Cases ***    USERNAME         PASSWORD
Invalid Login         invalid          ${VALID PASSWORD}
                      ${VALID USER}    invalid
                      invalid          invalid
                      ${EMPTY}         ${VALID PASSWORD}
                      ${VALID USER}    ${EMPTY}
                      ${EMPTY}         ${EMPTY}
```

A solution to the problem with the above test is to run setup/teardown as part of the template keyword like

```
*** Keywords ***
Login with invalid credentials should fail
    [Arguments]    ${username}    ${password}
    Create User    ${username}
    # ...
    [Teardown]    Delete User    ${username}
```

Because the above approach works already today and is more flexible than what's proposed by this issue I don't think the proposal that useful. It would work nicely in some cases, but I don't think it is worth spending much time to implement, test and document it. A highly related problem is that implementing this would be a *really* big task requiring changes in various places. Because there's already more generic solution for the same use case I don't think that makes sense.

I close this issue because I don't think the proposed feature is useful enough compared to the work related to implement it. If someone disagrees and is interested to implement this, the issue can be easily reopened.
