### ISSUE TITLE
dryrun checks keyword in Test Setup/Teardown of Settings table repeatedly

### ISSUE THREAD

**Issue by elginpeteza** [robotframework/robotframework#2980]
Since dryrun only checks for possible syntax errors, missing keywords, and incorrect keyword usage, it should only check the keyword defined in **Test Setup/Teardown** of **Settings** table only once.

```
*** Settings ***
Test Setup  Keyword1
Test Teardown  Keyword2

*** Test Cases ***
My first test
    Keyword 3

My second test
    Keyword 4
```

Dryrun result:
```
SUITE  Name of suite
    TEST  My first test
        SETUP  Keyword1
        KEYWORD  Keyword3
        TEARDOWN  Keyword2
    TEST  My second test
        SETUP  Keyword1
        KEYWORD  Keyword4
        TEARDOWN  Keyword2
```

The keywords in SETUPs and TEARDOWNs are repeatedly checked, which then consumes time and resources, and eventually have the same results.

**Comment by pekkaklarck** [comment]
I don't think this is a good idea because:
- Dry-run uses mostly the same logic as normal execution and making exceptions like this is very hard. 
- Dry-run is typically so fast that checking setup/teardown multiple times isn't a major issue.
- We already have a way to avoid executing certain keywords in dry-run using `robot:no-dry-run` keyword tag.

I'm not totally against the idea, though, so if you are interested to implement this I'm fine reviewing pull request. If not, this issue will be closed.
