### ISSUE TITLE
GET /wd/hub/screenshot request includes request body

### ISSUE THREAD

**Issue by crummy** [robotframework/robotframework#3002]
Hello,

I work for a company called Sauce Labs that provides an Appium hosting services for our customers. We have an Appium proxy that does some parsing of requests, e.g. intercepting screenshot requests to extract images.

One thing we noticed recently with some customers was screenshot requests including a request body (a JSON encoded session ID). As far as I can tell reading the JSONWire spec this should not be the case: https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol#sessionsessionidscreenshot

The customer was using Robot framework 3.0.3.

Thank you.

**Comment by pekkaklarck** [comment]
Do I get it right that these screenshot requests are invalid? Are they causing a problem for you or is the problem that users don't get the information they expect? Either way, it's certain that Robot Framework itself isn't sending these requests because it in general doesn't directly interact with any tested system.

The culprit must be one of the test libraries used with it or possibly a tool such a library uses internally. The most used library for web testing with Robot Framework is [SeleniumLibrary](https://github.com/robotframework/SeleniumLibrary), but if this problem is related to Appium then the problem is likely elsewhere. The problem is that there are various libraries that use Appium and I don't personally have much experience with them. Do you got any more information about this issue that we could use to track down the library/tool that's causing the problem?

**Comment by crummy** [comment]
Thanks, I've looked into this further and discovered the customer is using this library: https://pythonhosted.org/robotframework-sofrecomappiumlibrary/

I'll file the bug there instead.

**Comment by pekkaklarck** [comment]
OK! There are also other Appium libraries out there, though.
