### ISSUE TITLE
Problems with variable declaration inside other variables (worked before RF 3.1b1)

### ISSUE THREAD

**Issue by zastress** [robotframework/robotframework#3004]
Hello,

Since upgrading to RF 3.1b1 I get this error when RF tries to decode a variable that contains another variable inside. As a result, all Keywords using these variables are Failed.
Example:

`[ ERROR ] Error in file 'Mobile\Resources\Resource-Android.robot': Setting variable '${APP-TAB-FAVORITES-HEADER}' failed: Variable '${ANDROID-TEXT-VIEW}' is string, not list or dictionary, and thus accessing item 'contains(@resource-id,'title') and @text="Favorites"' from it is not possible.`

Here is how my variables are declared:

```
*** Variables ***
${ANDROID-TEXT-VIEW}                           //android.widget.TextView
${APP-TAB-FAVORITES-HEADER}              ${ANDROID-TEXT-VIEW}[contains(@resource-id,'title') and @text="Favorites"]
```

Is this some new feature? If so, how do you bypass this?

Thanks

**Comment by pekkaklarck** [comment]
This issue is caused by #2601 similarly as #2996. The fix is escaping the opening square bracket after the variable like `${ANDROID-TEXT-VIEW}\[contains(...)]`.

This is already mentioned in release notes as a [backwards incompatible change](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.1b1.rst#other-issues-possibly-causing-backwards-incompatibility-problems), but because this is already the second report we probably should make it more visible.

**Comment by zastress** [comment]
Thanks for all the info. I will modify my variables according to your explanation.

**Comment by pekkaklarck** [comment]
Great! The good news is that the escaping syntax is fully compatible with earlier versions. As you may have noticed, I already made this change more visible in RF 3.1 beta 1 release notes. Hopefully the beta works well for you otherwise.
