### ISSUE TITLE
Libdoc with Java libraries without source code adds extra `*` and `**` to varargs and kwargs

### ISSUE THREAD

**Issue by michalanglart** [robotframework/robotframework#3006]
Hi,

This issue/question originates in RED issue: https://github.com/nokia/RED/issues/256

I have some doubts and questions about `libdoc` running for Java static libraries when library is specified by name and only binaries are available. 

Lets say I'm not interested in the docs actually (they require javadocs so sources are needed) but rather in valid arguments descriptors.

The user guide (http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#general-usage) only lists by-path-to-source possibility:

> A Java test library implemented using the static library API **can** be specified by giving the path

however in next paragraph about resources files we read:

> Resource files **must** always be specified using a path

So stressing **can**/**must** difference - should `libdoc` report valid descriptors when running on static Java library imported by name or not?

As an example I have library:
```
public class Library {

    public void doSomething(final String... args) {
        Stream.of(args).forEach(System.out::println);
    }

    public void doSomethingDifferent(final Map<String, String> kwargs) {
        kwargs.forEach((k, v) -> System.out.println(k + " -> " + v));
    }
}
```

which I compile and pack into `com.example.Library.jar` file.

Now trying to run libdoc in two different ways:

1. by-path-to-source: `jython.exe -J-cp ".;c:\Program Files\Java\jdk_1.8.0_191\lib\tools.jar" -m robot.libdoc c:\com.example\src\com\example\Library.java show`

gives me:
```
Do Something
------------
Arguments:  [*args]

Do Something Different
----------------------
Arguments:  [**kwargs]
```
2. by-name-with-jar: `jython.exe -J-cp ".;c:\com.example.Library.jar" -m robot.libdoc com.example.Library show`

gives me:
```
Do Something
------------
Arguments:  [**varargs]

Do Something Different
----------------------
Arguments:  [****kwargs]
```

Where the asterisks in descriptors are wrongly doubled (4 instead of 2 and 2 instead of 1).

Is it possible to make (2) option work the same as (1) with regard to descriptors or should we avoid using by-name imports with `libdoc`? If we're left with only by-path import then we must require users to have sources of the library but it seems that if we're only interested in arguments descriptors the binaries ought to be sufficient. Or not?

**Comment by pekkaklarck** [comment]
I can reproduce the problem and the fix is also easy.

Notice, though, that even after the fix the result won't be exactly same. In the former case you construct the doc using the source file, and in that case Robot can read Javadocs from the file and you see correct argument names `args` and `kwargs`. In the latter case docs are generated using the imported Java class, and in that case Robot cannot see the argument names at all. It sees your keywords support varargs and kwargs, though, and thus gives placeholder names `varargs` and `kwargs` to these arguments. Or it should give them these names, it currently gives them names `*varargs*  and `**kwargs`, and Libdoc then adds additional `*` and `**` to them, respectively.
