### ISSUE TITLE
Document that `Set Global Variable` overrides variable table also in subsequent suites

### ISSUE THREAD

**Issue by inandasram** [robotframework/robotframework#3011]
Version information: 
Robot Framework 3.0 (Python 2.7.10 on win32)

The below structure would help to reproduce the issue.
tests
```
  |-Folder1
      |- _ init _.robot 
       Suite setup       Set Global variable    ${VARIABLE1}    1
       Suite Teardown       Set Global variable    ${VARIABLE1}    None
     |- test_file1.robot < some test cases inside>
  |-Folder2
       |- _ init _.robot
        *** Settings ***
        Suite setup       Setup keyword
        Suite Teardown       Teardown keyword
        *** Variables ***
        ${VARIABLE1}    A
        *** Keywords ***
        Setup keyword
        Log    ${VARIABLE1}
        Teardown keyword
        Log    "Test end"
```
When I log the "${VARIABLE1}" it is holding value None, not the locally assigned value "A".
The local variable scope is not incurred. 
For better view: 
![rfissue](https://user-images.githubusercontent.com/10071722/48900609-d44b7000-ee78-11e8-959a-15b1eb242e21.JPG)

**Comment by pekkaklarck** [comment]
First of all, it would be good make sure formatting in bug reports is not messed up. I did a quick fix to make the description readable, but please click that `Styling with Markdown is supported` next time to learn how to do it yourself.

**Comment by pekkaklarck** [comment]
The reported issue is that if you define a variable in a variable table and use `Set Global Variable` to set the same variable in some earlier suite, the value defined in the variable table is overridden by the explicitly set global value. It can be argued that because the variable table is evaluated after `Set Global Variable` is used, the value defined there should be used in that suite. The current behavior is, however, consistent with how variables set in the command line override variables in variable tables. Additionally, it can be actually useful to be able to override values like this. Because this functionality can be useful, I'm sure there are cases where it also is used and changing the behavior would cause backwards incompatibility problems.

There are pros and cons with allowing `Set Global Variable` to override variable tables in subsequent suites and with not allowing that. Due to the backwards incompatible concerns the latter needed to have lot of benefits compared to the former to make changing the functionality worth it. I don't think that's the case and thus don't think it's a good idea to change this. In other words, I consider the current behavior a feature rather than bug.

Instead of changing the functionality, I want to make sure the current behavior is adequately documented and also tested. I'll update the title of this issue accordingly.
