### ISSUE TITLE
rebot [ERROR]: failed: Incompatible XML element 'msg'

### ISSUE THREAD

**Issue by deeplymore** [robotframework/robotframework#3016]
hi,
   i fix one broken output.xml by tool "fixml("output.xml",'fixed_1_output.xml')", but have error "[ ERROR ] Reading XML source '.\fixed_1_output.xml' failed: Incompatible XML element 'msg'." when run cmd "rebot fixed_1_output.xml"
fixed_1_output.xml file content head "<?xml version='1.0' encoding='utf-8'?>
<robot rpa="false" generated="20181124 03:30:05.952" generator="robotfixml.py">"
broken output.xml file content head "<?xml version="1.0" encoding="UTF-8"?>
<robot rpa="false" generated="20181124 03:30:05.952" generator="Robot 3.1 (Python 2.7.12 on linux2)">"

**Comment by pekkaklarck** [comment]
It seems fixml wasn't able to fix the XML properly. Either it is buggy or your output.xml is so badly broken it cannot be fixed. Anyway, this would belong to fixml issue tracker rather than to Robot's. I won't have time to look at fixml in the near future, but if you have a simple example demonstrating a case where it doesn't work correctly please explain that in its tracker.
