### ISSUE TITLE
Traceback is not displayed if keyword fails in .robot file

### ISSUE THREAD

**Issue by skhomuti** [robotframework/robotframework#3020]
Hello

With loglevel DEBUG is displayed Traceback message. It useful if Assert-keyword raises in python libraries, but for raises in .robot files Traceback is empty. 

How normal is that? Maybe it is worth writing the line number for the .robot file?

![image](https://user-images.githubusercontent.com/31664571/49372903-0339cf80-f71e-11e8-9d0f-0c0ac0fb61f4.png)

**Comment by pekkaklarck** [comment]
There are various reasons why implementing what you propose is very hard:

- We don't currently even preserve the line numbers (#549). This is likely to change in the future if/when we re-implement test data parsing.

- The logged traceback is directly from Python. Adding new Robot specific information into it would be hard and potentially confuse people who are used to normal Python tracebacks.

Also, the reason you get `None` as traceback in the latter case is not because `Should Be Equal` would be in a `.robot` file because it's actually in `BuiltIn.py`. The real reason you don't see real traceback is that Robot automatically filters away traces referring to Robot's own code (you can actually control that with environment variable `ROBOT_INTERNAL_TRACES`) because they are only interesting if there are bugs in Robot itself. When you use BuildIn keywords, the implementation is fully inside Robot and no traces are left after filtering.

I guess we could somehow log file and row where the executed user keywords are defined, but that cannot be done until #549 is implemented. I'll close this issue now, but we can return to that later if such information still feels like a good idea.

**Comment by zmunro** [comment]
Any update on this?
