### ISSUE TITLE
RF 3.0.4 nested dictionary syntax error if first key is number, dot notation doesn't work

### ISSUE THREAD

**Issue by kaamos91** [robotframework/robotframework#3023]
I am using rf 3.0.4. I upgraded because of the dot notation upgrade (before I was using rf 2.9). My problem is when I want to access a nested dictionary item and the first key (it is an id from db) is a number, I got a syntax error.

I have a nested dictionary: &{Attributes}

So what I want to do:

${Attributes.1000.name}
The syntax error I get:

Resolving variable '${Attributes.1000.name}' failed: SyntaxError: invalid syntax (<string>, line 1)

And what is working:

${Attributes["1000"]["name"]}
I'd like to use the dot notation, because it is more readable.

**Comment by pekkaklarck** [comment]
The reason is that `Attributes.1000.name` is evaluated in Python and `1000` is [not a valid identifier](https://docs.python.org/3/reference/lexical_analysis.html#identifiers). I guess we could try parsing this expression ourselves, but I'm afraid it would be rather complicated and still wouldn't solve the problem accessing items that match dictionary methods like `${example.items}`. Is someone interested to try implementing that?

Good news is that RF 3.1 made it possible to access nested items in dicts and lists like `${Atrributes}[1000][name]` (#2601). It's quite a bit nicer thatn `${Attributes["1000"]["name"]}` and also handles cases like `${example}[items]`.
