### ISSUE TITLE
Regression when using `BuiltIn.run_keyword` internally in keyword with timeouts

### ISSUE THREAD

**Issue by kormbrek-rally** [robotframework/robotframework#3025]
Have 3.1 a spin and a test failed in capturing the logging.
Likely cause: https://github.com/robotframework/robotframework/commit/7ba429e5c34b41de345b8564a6e417b6f243d294#diff-b9a858723d69f7d98e980cf4a2e6d4ba
```
FAIL | TypeError: 'NoneType' object is not iterable

Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/kevinormbrek/PythonVMs/RISC-Automated-Tests/lib/python2.7/site-packages/robot/output/logger.py", line 171, in delayed_logging
    for msg in messages:
```
* robotframework 3.1, py 2.7.10, macOS 10.13.2 (17C88)
* there was a test timeout in effect, but not a keyword timeout
* the keyword that failed uses Python's logging API. RF captured that and it shows in log.html

I reduced this down to a simple reproduction:
```
*** Settings ***
Library    mylib.py
Test Timeout    10 minutes
*** Test Cases ***
delayed_logging bug
    My Keyword
```

mylib.py:
```
from robot.libraries.BuiltIn import BuiltIn

def my_keyword():
    BuiltIn().run_keyword("Should Be True", True)

```

Note that the failure goes away if you either:
* comment out Test Timeout
* remove call to `run_keyword`

**Comment by pekkaklarck** [comment]
Yeah, this is caused by the fix for #2839. On a quick look this problem can only occur when using `BuiltIn.run_keyword` (or some other `run_keyword` variant) in a library when timeouts are active. Ought to be easy to fix. Also other problems with RF 3.1 have been reported, so there's going to be RF 3.1.1 somewhat soon, most likely still this year.

Do you need to use `BuiltIn.run_keyword()`? If not, removing it would be a simple way to avoid the problem.

**Comment by pekkaklarck** [comment]
Fixing this issue was a bit more complicated than I initially thought but it's now done in commit 2783f85f76f2126638944c5f61efd5946cb3ad50. One effect of the fix is that the fix for intermittent output file corruption with timeouts that was provided by #2839 is not in effect when using `BuiltIn.run_keyword` internally in a keyword. That's still better than such usage not working at all, and in practice the behavior is the same as with RF 3.0.4 and earlier.

**Comment by kormbrek-rally** [comment]
Thanks for the info! I was long aware of the registration bit, but thought it was only if you did not want args to be processed.

**Comment by pekkaklarck** [comment]
It affects few other things as well, including timeouts. In worst case timeout occurring when you wrapper kw ia executing can cause corrupted output.xml file. If you register your kw to be "run kw", timeouts can only occur when a library kw you execute is running.
