### ISSUE TITLE
New FOR loop syntax doubts

### ISSUE THREAD

**Issue by michalanglart** [robotframework/robotframework#3026]
Hi,

I'm not sure if this is an issue at all but we've found rather surprising behavior which I think requires some explanation. We're adjusting [RED Robot Editor](https://github.com/nokia/RED) to handle new `FOR` loops syntax. There are two symmetrical cases we've found which seem to work differently than we expected.

#### First
```
old for test
    :FOR    ${i}    IN RANGE    5
    Log    ${i}
    END
```

This is what I was expecting:
- the first row defines old style loop
- the second row defines call to `Log` outside of loop body, because of missing indentation with `\`
- given those facts, the last one is a call to `Reserved.End` keyword
- when running there should be and error that the loop is empty (and of course call to `Reserved.End` would eventually fail if not the first error)

The test actually passes without problems and `Log` keyword is executed 5 times which suggests that Robot sees that as new-syntax loop although `:FOR` is used.

#### Second
```
new_for
    FOR    ${i}    IN RANGE    5
        \    Log    ${i}
        Log    5
    END
```

This is what I was expecting:
- the first row defines new style loop matched by `END` in last row
- the second row is inside the loop body, but the keyword names is empty (denoted by `\`)
- the third row is inside the loop body as it is before `END` row
- when running there should be an error that the name of keyword is empty, but besides that I would expect than that rows 2 and 3 are inside the loop 

The test however passes without problems printing the numbers 0,1,2,3,4,5 which means that Robot executes 2nd row 5 times in a loop and 3rd row 1 time outside of it which suggests that Robot sees that as old-syntax loop although `FOR`-`END` is used.

#### The setting inside loop body

There is also 3rd thing of different kind. Although you guys are working towards making the Robot syntax more and more strict we've found an example which shows that with new `FOR` the syntax became more looser. Previously it was not possible to have settings inside a loop, but with new `FOR` it became possible. I don't know if that's good or bad but it's good to know that fact. The following example shows that:

```
old loop
    :FOR    ${i}    IN RANGE    5
    \    Log    ${i}
    [Setup]    Log    hello from old loop
    \    Log    ${i}

new loop
    FOR    ${i}    IN RANGE    5
        Log    ${i}
        [Setup]    Log    hello from new loop
        Log    ${i}
    END
```

In `old loop` the line with `[Setup]` setting ends the loop, so only 2nd row is inside the loop body, this of course results in error being reported that the name cannot be empty in last row as it is outside of loop. However in `new loop` the `[Setup]` is placed inside the loop body and everything passes with setup call being logged as well as repeated double logs from rows 2 and 4.

Overall it seems to me that Robot treats both `:FOR` and `FOR` as some kind of synonyms which leads to surprising behavior when new and old syntax is getting mangled together. I think this also means that there are some nasty edge cases like those above which would make it harder to write e.g. a tool to convert old syntax to new one. Additionally it complicates parsing logic for any tool with own parser.

**Comment by pekkaklarck** [comment]
First of all, you are right that `:FOR` and `FOR` are synonyms. The former will be deprecated in RF 3.2 and removed later. You can use `END` with both and in that case you can omit the indentation with `\`. I explain the issues you encountered below.

= First =

```
old for test
    :FOR    ${i}    IN RANGE    5
    Log    ${i}
    END
```

As I mentioned above, `END` works both with `:FOR` and `FOR`. The loop doesn't have any indented body, so `END` marker is considered to mean the end of the loop and `Log  ${i}` becomes the body. Notice that with earlier versions this would fail due to the loop not having a body, so I don't consider this a backwards incompatible change. Notice also that the amount of indentation with whitespace doesn't matter, so the above is 100% equivalent to this:

```
old for test
    :FOR    ${i}    IN RANGE    5
        Log    ${i}
    END
```

= Second =

```
new_for
    FOR    ${i}    IN RANGE    5
        \    Log    ${i}
        Log    5
    END
```

Now the loop has a body indented with `\` so the `END` marker has no meaning. The amount of whitespace doesn't matter so this one is equivalent to:

```
new_for
    FOR    ${i}    IN RANGE    5
    \    Log    ${i}
    Log    5
    END
```

Because `END` is not considered a marker, this one fails for `End` being a reserved keyword. Earlier it would have failed already for `For` being a reserved keyword. Don't consider this a backwards incompatible change either.

= The setting inside loop body =

I don't see any reason why anyone would have settings inside loops. They working with the `END` marker but not when body is indented with `\` is just due to how the marker is handled. This may change in the future releases.

**Comment by pekkaklarck** [comment]
I agree that the current parsing rules are somewhat complex and confusing. The reason is that we try to introduce the changes with as little backwards incompatibility issues as possible. That means that RF 3.1 ought to still support the old syntax, without even deprecation warnings, and also the new syntax. The old syntax will be deprecated in RF 3.2 and removed later.

Is there something concrete you'd like to change at the moment?

**Comment by michalanglart** [comment]
Thanks for explanation. The issue we have with `:FOR` and `FOR` being synonyms is that we opted differently in our parser for https://github.com/nokia/RED editor hence we're having issues like described above, so we have to change this behavior to see the code the same way Robot does.

> I don't see any reason why anyone would have settings inside loops

Well me too, but as a editor developer I have a bit different angle. When user is editing the file the parser is reparsing everything in background when changes are made. This is not that uncommon scenario where user do this for example (this the scenario in which I've found that setting in body loop case):

- Write a keyword:
```
keyword
  Log  1
  FOR  ${x}  IN  @{l}
    Log  ${x}
    Log  something different
    Maybe call this keyword too
  END
``` 
- Decide that keyword requires arguments, so add `[Arguments]` setting but the caret was there at the bottom, so it's added below `END`
- Decides that this setting should be the first row of a keyword
- Moves whole [Arguments] line up row by row via some nice keyboard shortcut
- Stop for a second with this setting inside body loop
- Now everything was reparsed and some unexpected errors from validation are popping up

> The reason is that we try to introduce the changes with as little backwards incompatibility issues as possible. That means that RF 3.1 ought to still support the old syntax, without even deprecation warnings, and also the new syntax. The old syntax will be deprecated in RF 3.2 and removed later.

Totally understandable and natural. Notice that from IDE maintainer perspective it's working a little bit differently. Currently we support 2.9.x, 3.0.x and now will support 3.1. I haven't checked now but 2.8.x should also work. Of course we will be dropping support for older versions as time progresses but there is a big gap between RF release date and the moment we will drop support for previous version. I would say that with current RF release cycle we will probably drop support for 3.1 somewhere in 2021 or 2022 or so and maybe drop 2.9.x support next year.

> Is there something concrete you'd like to change at the moment?

No, just wanted to make sure that it works as designed and there is no bugs. We'll adapt to this to be compatible. Feel free to close and thank you!

**Comment by pekkaklarck** [comment]
I totally understand IDE developers need to know all the details about the syntax and think about all possible corner cases. It's especially difficult when you need to support multiple variants of the same syntax, but on the other hand IDEs can help a lot when migrating from the old syntax to new one. Might even make sense to add a setting to tell which format to use and convert automatically.

Anyway, let's close this issue now. If you got further questions, you can also use Slack or email.
