### ISSUE TITLE
Read signature (argument names, defaults, types) from "wrapped" keywords correctly

### ISSUE THREAD

**Issue by rainmanwy** [robotframework/robotframework#3027]
As discussed in #3024 , when keyword use user defined decorator and decorator may mask arguments of origin function/method, and Type Information Validation will report error.

Only solution is get origin function from "`__wrapped__`" attribute(if user use "functools.wraps"), so that could get origin arguments. This only works with *python3* and *"functools.wraps" is used in decorator*.

I guess this should be documented in User Guide or somewhere.

**Comment by rainmanwy** [comment]
@pekkaklarck , it is ok to me.
Thanks for the information.

**Comment by pekkaklarck** [comment]
After thinking this a bit more, decided to move it to 3.1.2 scope. Feature is very useful, shouldn't cause problems, and is easy to implement by using [inspect.unwrap](https://docs.python.org/3/library/inspect.html#inspect.unwrap). Decided to add `backwards incompatible` because the keyword signature that Robot sees changes and there's a tiny possibility for backwards incompatible problems. In general seeing correct signature should obviously be useful.

**Comment by pekkaklarck** [comment]
Moved back to 3.2 scope. Want to to have 3.1.2 ready ASAP and avoid all unnecessary backwards compatibility problems.
