### ISSUE TITLE
Pygments robotframework lexer does not recognize RPA keywords

### ISSUE THREAD

**Issue by datakurre** [robotframework/robotframework#3037]
All "Task" variants seem to be still missing from Pygments lexer. Probably the biggest issue is ``*** Tasks ***`` table header not being recognized.

https://bitbucket.org/birkenfeld/pygments-main/src/23886cb7f295543c91bf11ebd70fba56ac1ea9dc/pygments/lexers/robotframework.py

I assume https://bitbucket.org/robotframework/pygmentslexer has left unmaintained since the lexer was included into Pygments itself.

**Comment by pekkaklarck** [comment]
Yeah, updating Lexer is on my todo list. There are also other changes introduced by RF 3.1 that need to be done. Unfortunately I need to update my laptop before I can do that due to SSL modules being too old for Mercurial....

I try to get all that done soonish. If you want to help, I can merge PRs already before.

**Comment by pekkaklarck** [comment]
I've started working with updating the lexer to support RF 3.1 (and Python 3). The first step was moving the project to https://github.com/robotframework/pygmentslexer/. This issue can be closed.
