### ISSUE TITLE
Proper way of accessing object variables?

### ISSUE THREAD

**Issue by 1dziubo1** [robotframework/robotframework#3039]
Google coudn't help.
```
class MyClass(object):
    A = {'aaa':'aaa', 'bbb':'bbb', 'ccc':'ccc'}
    B = {'aaa':'aaa', 'bbb':'bbb', 'ccc':'ccc'}
    C = {'aaa':'aaa', 'bbb':'bbb', 'ccc':'ccc'}
    D = {'aaa':'aaa', 'bbb':'bbb', 'ccc':'ccc'}
    E = {'aaa':'aaa', 'bbb':'bbb', 'ccc':'ccc'}
    ...
    ZZZZZ = {'aaa':'aaa', 'bbb':'bbb', 'ccc':'ccc'}

   def abc(self):
       return None
```
How in RF should I access 'A' without interference in code?

To get robot access to abc method, i have to import lib:
```
Library  MyClass

*** Keyword ***
aaa
    MyClass.abc
```
But to have access also to variable, i need smth like this (and this looks extremely stupid to me, as i have to create instance)
```
Library  MyClass

*** Keyword ***
aaa
    MyClass.abc
    ${myclass}=  Get Library Instance MainClass
    Do Smth  ${myclass.aaa}
```

**Comment by 1dziubo1** [comment]
I didn't pint any real example here, just to clarify the issue, but in selenium, you prefer to have your example locators in one dictionary and make them available to bunch of test suites, because in case locator changes (and that happens relatively often), you have just one place to change that.

**Comment by pekkaklarck** [comment]
If it's just data you want to access, you should use variables instead of libraries. Variables can be given from the command line, created in resource files, created possibly dynamically in variable files, and returned by keywords. The last two allow using Python objects as variables and you can then access their properties using so called extended variable syntax:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#extended-variable-syntax
