### ISSUE TITLE
Literal `=` needs to be escaped if keyword accepts named-only arguments

### ISSUE THREAD

**Issue by robedthomas** [robotframework/robotframework#3047]
### Example Suite
```robot
*** Test Cases ***
Test Named Arguments
    Named Arg Test    First arg    Second arg    Maybe a third    named=Actually, correct!
    Named Arg Test    Let's try this again    1    <\=    2    named=Correct again!
    Named Arg Test    One more time    1    <=    2    named=This part fails

*** Keywords ***
Named Arg Test
    [Arguments]    @{list}    ${named}=Wrong!
    Log    list: @{list}
    Log    named: ${named}
```

### Problem Statement
I have created a keyword, some of whose arguments will be logical operators such as <= and !=. Robot interprets these operators as named arguments, despite this section in the Robot Framework documentation claiming that arguments will only be interpreted as named if the purported name matches the named arguments in the keyword's definition. 

![image](https://user-images.githubusercontent.com/16617569/50848322-97104400-1339-11e9-8e83-777a0020fc1e.png)
(Note: the \\= notation does work correctly, but I would prefer not to use it as it reduces readability)

As you can see, my example keyword **Named Arg Test** has no argument named "<", yet when I run this test, Robot reports receiving a positional argument after a named one. The documentation's statement above suggests to me that this is erroneous behavior, and that Robot should be treating "<=" as a positional argument.

If I'm making some silly mistake or there is an easy way to achieve this, I'd be happy to hear of it.

Log file: [named_args_log.zip](https://github.com/robotframework/robotframework/files/2737891/named_args_log.zip)

### System Info
Robot version: 3.1
Installation tool: pip v18.1
Interpreter: Python 3.5
OS: Windows 10.0 Build 16299

**Comment by pekkaklarck** [comment]
It seems the new named-only arguments support is buggy in this regard. When you use them, all arguments with `=` are considered to be named. That's a correct assumption with `**kwargs` but not in this case.

Good news is that the bug seems to be easy to fix. Bad news is that RF 3.1.1 has just been released and it will take some time before RF 3.1.2 is released.

**Comment by pekkaklarck** [comment]
The bug is in [argumentresolver.py](https://github.com/robotframework/robotframework/blob/master/src/robot/running/arguments/argumentresolver.py#L72). New tests are obviously needed and based on a little prototyping it seems existing tests need to be update as well.

This shouldn't be overly complicated to fix and thus adding adding `good first issue` label. Perhaps someone can take a look at this in RoboCon sprints.

**Comment by pekkaklarck** [comment]
I've started to think is fixing this actually a good idea or not. It is nowadays pretty annoying that you cannot know should argument `foo=bar` be evaluated as a positional argument with literal value `foo=bar` or does it mean name argument `foo` with value `bar`. There have been some discussions about changing the syntax so that `foo=bar` would *always* be considered named argument syntax and literal value would require escaping like `foo\=bar`. That would be a big backwards incompatible change requiring long deprecation period and it may not be worth it. If we ever consider doing that, allowing `foo=bar` as a literal value with named-only-arguments doesn't make much sense, though.

I need to think about this a bit more. If the decision is not to fix this, then related documentation should be updated.

**Comment by pekkaklarck** [comment]
Notice that you could actually use `≤` in test data instead of `<=` as long as you save the file as UTF-8. It's not easiest to type but looks good and avoids problems with `=`. Same obviously goes with all other characters in the Unicode Mathematical Operator block: https://www.compart.com/en/unicode/block/U+2200

**Comment by pekkaklarck** [comment]
After thinking this a bit more, I consider fixing this to be a good idea. It's true that using positional arguments with `=` in them may in the future require escaping, but named-only arguments now working inconsistently compared to other arguments would be strange.

**Comment by pekkaklarck** [comment]
Thanks for PR @yamatoRT!
