### ISSUE TITLE
Tidy doesn't handle new for loop syntax correctly

### ISSUE THREAD

**Issue by hello-ming** [robotframework/robotframework#3064]
when using tidy, it convert new FOR loop style to old style, and the result is incorrect with ${EMPTY}

robot version: Robot Framework 3.1 (Python 2.7.15 on darwin)

command `python -m robot.tidy --recursive  suites`

below is output of git diff  (the useless ${EMPTY} line has no indention, which will cause parse error)
```
-    FOR    ${index}    IN RANGE    10
-        ${resp}=    Post Request with proxy
-        Should Be Equal As Integers    ${resp.status_code}    200
-    END
+    : FOR    ${index}    IN RANGE    10
+    \    ${resp}=    Post Request with proxy
+    \    Should Be Equal As Integers    ${resp.status_code}    200
+${EMPTY}
```

hope tidy module may handle 'for loop' correctly, or there are some methods to exclude partial content.

**Comment by pekkaklarck** [comment]
It was decided to keep using the old for loop syntax in RF 3.1 with Tidy for backwards compatibility reasons and switch to the new one in RF 3.2. Looking at that now, it may not have been that good decision and should perhaps be reverted already in RF 3.1.2. Even better if it could be controlled by a command line option, but I'm not sure is that worth the effort.

Adding extra `${EMPTY}` is definitely a bug and at least that needs to be fixed in RF 3.1.2.
