### ISSUE TITLE
Generating documentation on user libs with Robot API calls fail with RobotNotRunningError

### ISSUE THREAD

**Issue by pfunk1978** [robotframework/robotframework#3066]
### Details
Robot Framework 3.1.1 (Python 3.6.7 on linux)
Ubuntu 18.04
### Issue

I am attempting to generate keyword documentation from our custom libraries for our QA department and I have some issues.

When generating documentation on a method that has Robot Api calls as below `BuiltIn().get_library_instance('FXRobot.comms')` I get the following error:
```
Initializing test library 'HSMTools' with no arguments failed: RobotNotRunningError: Cannot access execution context
Traceback (most recent call last):
  File "/home/pmoore/Dev_Projects/FXQA/lib/FXQA/comms/RobotConnections.py", line 23, in __init__
    self.suite_connection = self._get_conn_lib()
  File "/home/pmoore/Dev_Projects/FXQA/lib/FXQA/comms/RobotConnections.py", line 19, in _get_conn_lib
    return BuiltIn().get_library_instance('FXRobot.comms')
  File "/home/pmoore/.virtualenvs/FXRobot/lib/python3.6/site-packages/robot/libraries/BuiltIn.py", line 3256, in get_library_instance
    return self._namespace.get_library_instance(name)
  File "/home/pmoore/.virtualenvs/FXRobot/lib/python3.6/site-packages/robot/libraries/BuiltIn.py", line 71, in _namespace
    return self._get_context().namespace
  File "/home/pmoore/.virtualenvs/FXRobot/lib/python3.6/site-packages/robot/libraries/BuiltIn.py", line 66, in _get_context
    raise RobotNotRunningError('Cannot access execution context')
```
### Workaround
I can comment out the offending line to generate doccumentaion by hand, but I would rather build the documentation in our CI pipeline making that workaround out of the question.

Am I doing something wrong, or is this a legit issue?

**Comment by p74** [comment]
i have a situation like that as well and i solve it with listeners,

ROBOT_LIBRARY_SCOPE = 'TEST SUITE'
ROBOT_LISTENER_API_VERSION = 2

def start_suite(self, data, result):  # @UnusedVariable
    self.instance = BuiltIn().get_library_instance('FXRobot.comms')

but 1 one case i cant do this  so i use then a try except exception .. 

Greetings Ruud.

**Comment by pfunk1978** [comment]
@p74 

I didn't think about try/except...

Tell me more about this listener use. Where is there documentation?

**Comment by pekkaklarck** [comment]
When generating documentation for a library implemented as a class, Robot needs to create an instance of it exactly like when the library imported during execution. This means that library's `__init__` is called and code there executed. In this case the `__init__` tries to use Robot's API that can only be used during execution.

A simple fix is changing the code so that `__init__` doesn't execute code that needs Robot to be running. This is easy to do by using a property so that instead having something like

```python
    self.comms = BuiltIn().get_library_instance('FXRobot.comms')
```

in `__init__` you have

```python
@property
def comms(self):
    return BuiltIn().get_library_instance('FXRobot.comms')
```

This also has a benefit that `self.comms` will always return the instance used by Robot at that time, not possibly an instance it used earlier.

Finally, it is in general not a good idea to have code in `__init__` that uses external dependencies you cannot directly control or that has other side-effects. Avoiding such code eases, for example, unit testing.

**Comment by mcoderr** [comment]
How to get robot framework instance with loading robot ?
