### ISSUE TITLE
Built In > Is True raises if string is number starting with 0

### ISSUE THREAD

**Issue by joaonc** [robotframework/robotframework#3069]
BuiltIn's [`_is_true(condition)`](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/BuiltIn.py#L82) fails (raises) if the condition is a string that represents a number and starts with a 0.

This goes in accordance to `eval`:
```
>>> eval('0')
0
>>> eval('1')
1
>>> eval('01')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "<string>", line 1
    01
     ^
SyntaxError: invalid token
```

However, in the Robot Framework world, it's not unusual to have strings representing numbers, including those starting with `0`. For example, when holding a two digit month (`01` for January) and we're checking that the number is defined (as opposed to being an empty string or `None`).

**Suggestion:** Add logic in `_is_true(condition)` to evaluate that if the string starts with `0` and the rest of the string are all digits and at least one is not `0`, then `lstrip('0')` and then evaluate. If starts with `0` and the rest of the characters are all `0`, then it already evaluates to `0`.

While this is a deviation from Python's `eval`, IMO this goes more into how Robot Framework is used.

**Comment by joaonc** [comment]
PS: I created my own `is_true(condition)` where I check if it's a number and returns false if `0`, even if `0.0`, as it's also not unusual to have strings representing floats..

```
try:
    return bool(float(condition))
except ValueError:
    pass
return eval(condition)
```

**Comment by pekkaklarck** [comment]
In my opinion the current behavior is OK because the keyword is documented to evaluate the expression on Python and thus it's natural that evaluation is subject to Python evaluation rules. That said I've been bitten by numbers with leading zeros causing problems myself and understand avoiding such issues would be nice.

I agree that the current situation with Python is pretty confusing. With Python 2 the `0` prefix denotes octal number and thus numbers up to `07` work, `08` or `09` cause syntax errors, `010` is actually `8`, and so on. I guess this strange behavior was the reason `0` prefix now always causes a syntax error with Python 3 and '0o` prefix (also supported by Python 2.7) is needed with octal numbers. It's also pretty strange that `int('07')` and also `int('010')` work regardless the Python version and also return the value you'd expect (i.e. `7` and `10`) and that `00` is fine with all Python versions as well.

A problem fixing the problem is that stripping possible leading spaces wouldn't handle expressions like `1 > 08`. Instead the expression needed to be tokenized and possible error tokens in format like `07` handled specially. Because we already tokenize the expression if it possibly contains embedded variable, implementation wouldn't be overly complicated. If someone is interested to look at that and would provide a PR containing also tests and documentation changes I'd be happy to review and merge it.

One think to decide would be how to handle possible leading zeros with Python 2. Possibilities include:
- Handle all error tokens with leading zeros. This would cause strange results because `08` would be considered `8` but also `010` would be `8` because Python 2 considers it octal and no error occurs. I don't think that's a good idea.
- Handle *all* tokens with leading zeros. This would be backwards incompatible change causing problems with Python 2 users with octal numbers in their expressions. Cannot be done without a deprecation period during which users could switch to `0o` prefix. I don't think that's worth the effort.
- Only handle leading zeros with Python 3. Won't help Python 2 users but they need to migrate soon anyway and this would be one more reason.

**Comment by joaonc** [comment]
Wow, best answer ever.  Thanks for the lesson in how Python deals with string starting with `0` and thanks for taking the time to write it.

Indeed, which Robot Framework supports Python 2, fixing this may be fighting fire with fire, causing bigger problems..   Maybe something that can be revisited then if it comes up again. Closing for now.

**Comment by pekkaklarck** [comment]
I'd be fine this being fixed only with Python 3 but I'm not sure is it worth the effort.
