### ISSUE TITLE
Type conversion fails in dry-run if value contains variable

### ISSUE THREAD

**Issue by AleksandrKE** [robotframework/robotframework#3090]
Hello.
I've got an issue while running tests in dry run mode after the Robot Framework update.
The problem connected with the automatic conversion of arguments if the method has annotations.
My test:
```
(venv) aleksandr@work-pc:~/my_project$ cat my_test.robot 
*** Settings ***
Library    library.py

*** Test Cases ***
My Test
    ${list}=    Create List    one    two    three

    library.Custom Keyword     ${list}
```
My method:
```
(venv) aleksandr@work-pc:~/my_project$ cat library.py 
# -*- coding: utf-8 -*-

def custom_keyword(lst: list):
    pass
```
I get the error message:
```
(venv) aleksandr@work-pc:~/my_project$ robot --dryrun my_test.robot 
==============================================================================
My Test                                                                       
==============================================================================
My Test                                                               | FAIL |
ValueError: Argument 'lst' got value '${list}' that cannot be converted to list: Invalid expression.
------------------------------------------------------------------------------
My Test                                                               | FAIL |
1 critical test, 0 passed, 1 failed
1 test total, 0 passed, 1 failed
==============================================================================
```
However, the test runs successfully if it runs without the '--dry run' option.
It looks like the robot tries to convert into the list the name of the variable, not value.

My environment:
```
(venv) aleksandr@work-pc:~/my_project$ robot --version
Robot Framework 3.1.1 (Python 3.6.7 on linux)
```

**Comment by pekkaklarck** [comment]
Good catch. This is due to Robot nowadays trying to convert arguments automatically but variables not being resolved in dry-run. It would be best to resolve variables (we got #2322 about that), but that would be a huge task and not likely to happen in the near future. At the moment the best solution is not doing argument conversion in dry-run if the argument contains variable.

Alternatively we could disable automatic argument conversion in dry-run altogether, but what would remove a useful validation. Instead we should add tests for argument validation in dry-run (when not using variables).

A workaround for this problem is moving the logic into a user keyword and adding `robot:no-dry-run` to it.

**Comment by AleksandrKE** [comment]
Thanks for the quick answer.
> At the moment the best solution is not doing argument conversion in dry-run if the argument contains variable.
I think this is a good solution.

**Comment by pekkaklarck** [comment]
Thanks for PR #3126 @aleskarovadi! Hopefully you can it update based on my comments.
