### ISSUE TITLE
Document that `Create Dictionary` returns custom `DotDict` and `Convert To Dictionary` can convert it to normal `dict`

### ISSUE THREAD

**Issue by Caos-Maker89** [robotframework/robotframework#3098]
Robotframwork "create dictionary" key always create a dotDict dictionary.
Sometimes this features create litte tricky problem, for example I'm ready to test Kafka, but full content schema expect a normal dict, not a dot dict.

I suggest to build a key to create a normal dict or allow "create dictionary key" to create normal dict (with a overridable argument for example).

Example:
Create Dictionary  |   dictionary_name  |  dictionary type (default dotDict)

**Comment by pekkaklarck** [comment]
Because `DotDict` is based on `OrderedDict` which is based on `dict`, I consider it a bug if some code doesn't support it. That said, I'm fine making it possible to create "normal" dictionaries but it would probably need a separate keyword like `Convert To Dictionary` because it would be hard to make `Create Dictionary` configurable. That keyword would belong to `Collections` rather than to `BuiltIn`. Are you @acaovilla interested to implement it?

**Comment by acaovilla** [comment]
Yep, 
I can implement Convert To Dictionary keyword!

**Comment by pekkaklarck** [comment]
Cool! I guess it can be just

```
def convert_to_dictionary(item):
    return dict(item)
```

which works with any mapping and also with stuff like `[('key', 'value'), ('k2', 'v2')]`. More work in writing documentation and some tests. See CONTRIBUTING.rst in the project root for details about them.

**Comment by pekkaklarck** [comment]
Heh, we actually already have [Convert To Dictionary](http://robotframework.org/robotframework/latest/libraries/Collections.html#Convert%20To%20Dictionary) in the Collections library that behaves exactly like discussed above. There was a similar issue discussed on our Slack few days ago and as a result I enhanced the docs of `Create Dictionary` and `Convert To Dictionary` to make it explicit that the former returns `DotDict` and the latter can be used to convert it to `dict` if needed. I guess we can consider this issue an enhancement request that was fixed by 40f0d19b00349c4dadd86d1ea90060eaabf2aff7.
