### ISSUE TITLE
Multiline with pipe separators

### ISSUE THREAD

**Issue by nefethael** [robotframework/robotframework#3101]
Hi,

Is is possible to split keyword in multiple lines with pipe separator?

Here is my attempt:
```
| TU
|      | ${msg}= | Run Keyword And Expect Error | *
| ...  | Modbus.Open Connection | ${DUT_ERR} | "DUT_ERR" | 1503
```
And I obtain following error:
```
Keyword 'BuiltIn.Run Keyword And Expect Error' expected at least 2 arguments, got 1.
```
Note that same test with 4-space separator works fine in multiline.

**Comment by pekkaklarck** [comment]
The problem is that `...` becomes a test case name when it's in the first column. This variation works:

```
| TU
|      | ${msg}= | Run Keyword And Expect Error | *
|      | ... | Modbus.Open Connection | ${DUT_ERR} | "DUT_ERR" | 1503
```

Notice that without pipes 

```
TU
    ${msg}=    Run Keyword And Expect Error    *
...    Modbus.Open Connection    ${DUT_ERR}    "DUT_ERR"    1503
```

wouldn't work either and you needed to use

```
TU
    ${msg}=    Run Keyword And Expect Error    *
    ...    Modbus.Open Connection    ${DUT_ERR}    "DUT_ERR"    1503
```

Notice also that the new test data parser in RF 3.2 (#3076) may actually change this because `...` is probably going to be handled so early that it's context isn't known. Anyway, the syntax that currently works will definitely also work in the future.
