### ISSUE TITLE
Add execute times tag at case level

### ISSUE THREAD

**Issue by zhouqiang1985** [robotframework/robotframework#3104]
We usually encounter the issue that execute case failed for first time but run passed for next time at same test environment.    And these failed cases may depend the previous case at a suite, so we must rerun the whole test suite  that waste many time.   So we have the requirement set execute times for the case, if the case run failed, robot can continue to run the failed case at the same context with  execute times util that is passed.   The issue happens with high frequency, please consider it.

**Comment by bkhouri** [comment]
Robot framework already supports timeouts at the test case level.

http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-case-timeout

**Comment by pekkaklarck** [comment]
@bkhouri, I think the request is for automatically re-executing a test if it fails. There are various problems with it:

- In general tests should pass. Automatically re-executing them until they succeed is always a bit questionable.
- The above said, there are valid reasons for re-running a failed test and we already have `--rerunfailed` option to make it possible. It's requires a second test run, though.
- Automatically running a test as part of a normal run would require some new syntax and would in general be pretty big task to implement.
- I feel that re-execution is generally something that's is best handled by external orchestration solution.

I'm not totally against this idea but know I won't have time or much interest to implement it in the foreseeable future. If someone else finds it very important and is willing to provide a PR, this issue can be left open. Otherwise I'll close it and it can be reopened if someone is going to actually implement it.

**Comment by wxq666216** [comment]
Hi, we also have the same requirements. For example, 10 test cases in the same test suite, may be 8pass/2fail , it's inconvenient to rerun the failed ones. If we can set a tag such as rerun times =1 , then if the test case is failed robot will rerun the case again ,and even though the 2nd is also failed , robot will continue to run the next one.
Is there any available methods to do that? Please share to us, thanks!

**Comment by zhouqiang1985** [comment]
@pekkaklarck 
That is a common pain point for many test teams.
1. Sometimes we just test the feature functions not test stability, so we just need run test case passed for one time. And the case is depend on the previous test cases.  so it's cost many efforts to re-setup test context.   For the test efficiency,  we have requirement that can run the case for multiple times at framework .
2. Due to have dependency between test cases in a suite, so that cannot be  simple to use  --rerunfailed.


And i think that is a good feature for robotframework.

**Comment by galaxy24** [comment]
@pekkaklarck 
Hi, I also have the same requirement.
Please consider it.Thanks

**Comment by pekkaklarck** [comment]
I can consider this, but someone needs to first propose how it should work in practice. If we agree on the design, then someone should either provide pull request implementing the feature or consider paying someone to do it.

**Comment by zhouqiang1985** [comment]
@pekkaklarck
I think the tags can be designed like this

[MaxRunTimes]    ${MAX_RUN_TIME}   #set max run times,default is 1
[RunType]   NORMAL                 # The is tag can be set as NORMAL or PASS_GO_NEXT,default is NORMAL 

1. if   MaxRunTimes tag  is not added , or  MaxRunTimes tag's value  is not set, MaxRunTimes  is set as one. Robot will run case for one time.

2.if MaxRunTimes  tag is set as > 1, 
  a. if RunType tag is not added or RunType tag's value  is not set, RunType is set as Normal, robot will run case for MaxRunTimes   times 
  b. if   RunType tag's value set as PASS_GO_NEXT, robot will try to run the case for MaxRunTimes   times util the case is passed. But once  the case is passed, robot will skip the case and continue run next case.

**Comment by pekkaklarck** [comment]
Are you sure this would cover all the use cases? What if, for example, someone wanted to decide should the test be re-run based on the occurred error? How should re-executed tests be shown in logs/reports? Also, what's the point in skipping a test case once it has passed?

**Comment by zhouqiang1985** [comment]
Actually the test setup can recover the basic test context that depend on the case designer how to design the case step. I have draft change the robot function to repeat run test case, may
be report will show  as below.
![image](https://user-images.githubusercontent.com/48048512/53638842-8e196000-3c62-11e9-8be9-25d4265a4135.png)

For robot will skip the case, i mean once robot run the case passed,  robot can continue to run next case even that run times don't reach the MaxRunTimes.

**Comment by zhouqiang1985** [comment]
![image](https://user-images.githubusercontent.com/48048512/53639473-4eec0e80-3c64-11e9-95d7-a89502d02a9e.png)
![image](https://user-images.githubusercontent.com/48048512/53639535-780c9f00-3c64-11e9-931b-61d704b47d43.png)

**Comment by zhouqiang1985** [comment]
@pekkaklarck Would you show me more details for scenario that someone want to decide should the test be re-run based on    the occurred error?

**Comment by pekkaklarck** [comment]
What's the difference compared to normal statistics or console output in your examples?

I don't have details how someone would possibly like to use feature like this. And that's the problem. If we start implement something like this, we needed to know how to implement it so that it works in generic manner and doesn't only solve one particular use case. Adding new syntax like you propose is always a huge change that affects all editors and many other supporting tools in the ecosystem. Once something like that's added, it cannot be changed without deprecation period to avoid backwards incompatibility problems. That's the reason I prefer stuff like this implemented outside the core at least in the beginning.

**Comment by zhouqiang1985** [comment]
@pekkaklarck 
I reviewed the history issues list, i found many similar requirements, they all have same pain point that  need to rerun the cases if run failed  or run one cases for multiple times . We have some external tool to help implement the function.  But all these tools must repeatedly setup and release test context.
For the efficiency, to run these cases at same test context is a better way. 

https://github.com/robotframework/robotframework/issues/1847
https://github.com/robotframework/robotframework/issues/1886
https://github.com/robotframework/robotframework/issues/2789

That is a tiny change for the robot framework, but consider other supporting tools in the ecosystem, which maybe is a big project. So maybe the feature need a experienced leader to design the whole feature.  But as a user for robotframework, i look forward to that can cover more common test  scenarios. And many test frameworks already have similar functions, just like junit use @RepeatedTest to  repeatedly run the cases with setting times.

How about you think?

**Comment by yahman72** [comment]
I agree that there's a need for this kind of stuff. 

In my case the `--rerunfailed` is expensive, because at the end of a run the "state" of SUT is lost and to get it back to a predefined state takes sometimes up to 20 minutes. 

At minimum it would good to maintain the execution context  (e.g. global variables, and libraries) which could be used to store the "state" of the SUT.  The rest could remain the same e.g. one output-file per rerun etc. In short: `--rerunfailed` automatically within the same execution context as the original suite.

But any further features (how many retries, etc.) will have the problem that Pekka mentioned (here and in the other issues): how to make it so generic that it works for everybody.

There's a good comment from Pekka in #1886 which applies IMHO here too:
> In my opinion it would be better to implement this functionality as a separate project similarly to Pabot. If that would require new public APIs, we definitely can add them. A separate project could be changed more easily than RF itself, and its development process and release schedule could also be independent. Once the functionality gets mature, we could then later consider incorporating it with the core.

That new project could use the RF API's:
- to keep the execution context alive
- start a rerun
- parse the suite and e.g. evaluate tags to decide whether to include a test in rerun or not

**Comment by pekkaklarck** [comment]
Some general comments:
- I'm not against adding this kind of a feature.
- It could be a built-in feature an API that external tools could use.
- Either way, implementation is a big task. The especially hard part is designing the feature/API so that it actually works in generic manner.
- I won't have time to implement this in the foreseeable future. At the moment I'm busy with writing new parser for Robot's tests data and then there are big and long waited features like IF/ELSE support waiting. This work is sponsored by the [Robot Framework Foundation](http://robotframework.org/foundation/).
- If someone wants to see this feature in Robot, they need to do something about it. This can mean providing a pull request (but we still need to agree on the design) or paying someone for the development. It's possible to pay directly to some developer or join Robot Framework Foundation and try to get their money directed into this work.

**Comment by pekkaklarck** [comment]
Anyone interested to drive this forward?

**Comment by yahman72** [comment]
I definitely have a need for those minimum requirements i.e. this
> At minimum it would good to maintain the execution context (e.g. global variables, and libraries) which could be used to store the "state" of the SUT. The rest could remain the same e.g. one output-file per rerun etc. In short: --rerunfailed automatically within the same execution context as the original suite.

but I won't have time for this in the near future = we could keep this issue open as placeholder. Or we can also close this, if you don't want to have issues hanging with no progress for months .... and reopen or create a new one when there's new activitiy on this.

**Comment by pekkaklarck** [comment]
I don't want to have issue lingering here if nobody is going to look at them in the foreseeable future. It's easy to re-open issues or create new ones.

**Comment by schinckel** [comment]
For anyone who comes across this for the same reason I did (sometimes some tests fail, and then pass on a subsequent run), if you don't care about your results files other than for examining failures, you can implement this in a tox environment:

    [testenv:robot]
    commands=
      - robot --exclude skip --outputdir robot_results
      robot --rerunfailed robot_results/output.xml \
            --runemptysuite \
            --outputdir robot_results

You could even store the results in a different file or directory if you want.

In tox, the leading `-` means don't count this as a fail if the command fails.

**Comment by mermaidcodes** [comment]
I think it's a very useful feature and needed based on projects. We have some Rooms(six currently) where the same tests and outputs are expected - each room is randomly selected on every room. It so may happen that Room 1 did not have data and the test failed while the 2nd run it may pass.
Also for other purposes rerunning of failed test cases for a minor timeout or data issue would be helpful. 
Something like Retry Analyser in Selenium.

**Comment by fbt045** [comment]
a workaround is using [Template], you can write a test case level keyword, the call it in [Template] and add a for loop in body
