### ISSUE TITLE
Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: ) No matching distribution found for Pywin32 (from robotframework-ride) in ubuntu16.04

### ISSUE THREAD

**Issue by jayapr** [robotframework/robotframework#3115]
Hi, 
I am facing this error when installing robot-framework ride on a mchine installed with ubuntu-16.

root@ubuntu:~# sudo pip install robotframework-ride
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting robotframework-ride
  Downloading https://files.pythonhosted.org/packages/4e/a6/1835a17fa566b19c166735a9a75d55101e53b68566771ddb0b690dd4be83/robotframework_ride-1.7.3.1-py2.py3-none-any.whl (926kB)
    100% |████████████████████████████████| 931kB 10.0MB/s 
Collecting Pywin32 (from robotframework-ride)
  Could not find a version that satisfies the requirement Pywin32 (from robotframework-ride) (from versions: )
No matching distribution found for Pywin32 (from robotframework-ride)

**Comment by aaltat** [comment]
Although RIDE is part of the Robot Framework ecosystem, RIDE is separate tool and it is hosted in the different project. Please raise an issue to the RIDE issue tracker https://github.com/robotframework/RIDE/issues if it does not already exist. 

Because this is RIDE issue and not Robot Framework core issue, I am closing this issue.
