### ISSUE TITLE
Run Keyword If  <condition.. Keyword> Else  <Keyword> not working

### ISSUE THREAD

**Issue by sivassrr** [robotframework/robotframework#3134]
![image](https://user-images.githubusercontent.com/19144129/55217954-bd51cb80-5226-11e9-9e17-a69fc4aace6c.png)

This is related to Run Keyword If ... Else ...  recently encountered. 
https://github.com/openbmc/openbmc-test-automation/issues/1709

Looks like robot frame work expects "Else" to be all capitalize.

**Comment by pekkaklarck** [comment]
As the documentation you referred to says, it must be exactly "ELSE".

**Comment by sivassrr** [comment]
See, User who follow "Run Keyword If ... Tend to remember as "Else" instead of "ELSE"

So you may need to reconsider your view. Part of Keyword is not case sensitive and others are case sensitive. It is generally not an acceptable statement.

**Comment by sivassrr** [comment]
Or come up with a statement or document that small "Else" within the Robot Keyword If is not supported.

**Comment by pekkaklarck** [comment]
The syntax is like it is by design and won't be changed. Instead we've lately turned all markers like this to be case-sensitive. This includes the forthcoming `IF/ELSE` (#3074) once that syntax lands in RF 3.3.

In my opinion the documentation of `Run Keyword If` is pretty explicit about the syntax already now. If you got concrete ideas how to improve it, please submit a pull request.
