### ISSUE TITLE
Using abstract base classes directly from `collections` causes deprecation warning

### ISSUE THREAD

**Issue by ddiminnie** [robotframework/robotframework#3213]
This is not a high-priority item (for reasons to follow), but:

The module "robottypes3.py" (part of the robot.utils package) currently triggers the warning (in python 3.3 and up) "DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working"

According to the [draft python 3.8 changelog](https://docs.python.org/3.8/whatsnew/changelog.html#changelog) the removal of abstract base classes from the 'collections' package has been delayed until python 3.9, so this issue does not require immediate attention...

... but it will need to be addressed eventually.

**Comment by pekkaklarck** [comment]
Thanks, good catch! This is trivial to fix and should be done in the next release which ought to be RF 3.2. Need to also check do we import ABCs directly from collections somewhere else and also see do we get deprecation warnings elsewhere. Should actually consider running tests so that such warnings are reported as errors.

**Comment by ddiminnie** [comment]
I've run into the same problem in my own code... but the same code has to run on both python 2 and 3, so the changes are (slightly) more ugly on my side... :-P  

Glad to help.

Cheers!
