### ISSUE TITLE
Document that the position of the `[Return]` setting does not affect its usage

### ISSUE THREAD

**Issue by rajakarthikeya** [robotframework/robotframework#3214]
Set of instructions which are written after [Return] statement are getting executed. Robot Framework should through an error or should not consider the keywords written after [Return] keyword

Ex:
```robotframework
***Keywords***
Custom Keyword
    [Return]    hyyyy
    Return From Keyword    hyyyy2222    

***Test Cases***
Test1  
   ${var_rt_ky2}=    Custom Keyword
   Log To Console    ${var_rt_ky2}
```
Output:
hyyyy2222 

In other case
```robotframework
***Keywords***
Custom Keyword
    Return From Keyword    hyyyy2222    
    [Return]    hyyyy

***Test Cases***
Test1  
   ${var_rt_ky2}=    Custom Keyword
   Log To Console    ${var_rt_ky2}
```
Output:
hyyyy

In second case working as expected. Where as in the first case it is working wrong. Please give explanation if I missed something

**Comment by pekkaklarck** [comment]
The `[Return]` setting just defines what the keyword should return after all keywords it contains have been executed. It doesn't work the same way as the `return` statement in languages like Python or Java. Settings can, in fact, be in whatever order in Robot Framework data.

Because `[Return]` works like it does, separate `Return From Keyword` has been added to BuiltIn. It or its `Return From Keyword If` variant should be used if there's a need to return without executing the whole keyword.

Now that we are planning to add more programmatic functionality such as `IF/ELSE` (#3074) and `TRY/EXCEPT` (#3075), it would be good to add also separate `RETURN` functionality that would work like the `return` statement in other languages. We could submit an issue about it, but I don't think it's as important as the aforementioned features.

So, the `[Return]` statement works as designed and instead of changing the design we could add separate `RETURN` functionality in the future. At the moment the only thing that could be changed is making sure that `[Return]` is documented adequately in the User Guide. Could someone check that?

**Comment by rajakarthikeya** [comment]
Thank you for getting back. Is documentation updates by Robot Framework official team members?

**Comment by pekkaklarck** [comment]
Could you @rajakarthikeya clarify what you mean? If the question is who can update documentation, the answer is "anyone" via pull requests.

**Comment by eternalconcert** [comment]
It is documented in the: [User Guide - Using [Return] setting](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-return-setting)

I will add some code documentation as well (maybe during the next days) and send a pull request.

**Comment by eternalconcert** [comment]
I think it would be a good idea to clarify it explicitly in the user guide. I will update it.

**Comment by rajakarthikeya** [comment]
Thank you @pekkaklarck - answered my question.

Thank you @eternalconcert for giving update on this, yes we need to update the user guide.
