### ISSUE TITLE
XML library does not work with non-ASCII bytes on Python 2 or any bytes on Python 3

### ISSUE THREAD

**Issue by y2j44** [robotframework/robotframework#3226]
Hey All:

I have some robot framework code that fails when calling the Get Element Text keyword with this error
AttributeError: 'bytes' object has no attribute 'findall'
I'm running it on a Win10 machine with Python 3.

When I pull the code on my WinXP using Python 2.x, it passes perfectly fine.

Hoping if someone can help?

thanks

**Comment by pekkaklarck** [comment]
Our XML library tests work fine both with Python 2 and 3. You need to provide some more information for others to be able to help you. A simple example demonstrating the problem and the exact Python version where the problem occurs would be good. Also, testing on some other machine and/or some other Python 3 version would be a good idea.

**Comment by y2j44** [comment]
Here's the python and Robot version
Windows 10
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 21:26:53) [MSC v.1916 32 bit (Intel)] on win32
robotframework                 3.1.2

Here's the error
${xmlElementValue} = XML . Get Element Text ${soap_response.content}, /contractId

AttributeError: 'bytes' object has no attribute 'findall'

let me know if you need more info, thanks for replying. Correction, the version it works on is 
Win 7
Python 2.7.14
robotframework                 3.1.2

**Comment by pekkaklarck** [comment]
The reason for the failure is that `${soap_response.content}` is bytes and XML library only works with strings. It works in Python 2 because there's no clear separate between bytes and text, but even there it would fail if bytes would contain non-ASCII characters. If the response comes from `request`, then you probably can you `${soap_response.text}` instead. Otherwise you need to decode bytes to text yourself.

The real question is, what should XML library do when it's used with bytes in Python 3 or with bytes containing non-ASCII characters in Python 2. Failing like this isn't good, so at least we should provide a better error and tell the user that text should be used instead of bytes. Because XML content should have encoding defined, we might be able to use that information to automatically decode bytes. Not sure what would be the best way to do that, though.

**Comment by pekkaklarck** [comment]
This seems to be pretty simple to fix by wrapping possible byte input into a `BytesIO` object. Then the underlying XML modules consider the input to be an opened file object and they apparently handle decoding themselves based on encoding specified in the content itself.

I'll add this to RF 3.2 scope but still recommend using `response.text` instead of `response.content` with `requests` responses.

**Comment by pekkaklarck** [comment]
This is also somewhat related to #3194. Need to merge PR fixing that first.

**Comment by pekkaklarck** [comment]
This was even more related to #3194 than I thought. After fixing that, this issue only required a trivial change in XML library itself.
