### ISSUE TITLE
Telnet: Global Library Scope or Cleanup

### ISSUE THREAD

**Issue by bbara** [robotframework/robotframework#3232]
Hey guys,

I just realized that the scope of the Telnet Library is not set to GLOBAL but to TEST_SUITE.
As explained [here](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-library-scope), it might be useful for connection-based tests, as there might be multiple test suites and test cases that require the same connection and "re-connecting" for each test introduces quite some overhead.

If this is not possible, I would suggest something like adding an implicit closing of connections into the "destructor" of the library, so something like:

```
def __exit__(self, exc_type, exc_value, traceback):
    self.close_all_connections()
```

which could also be option-based to keep backward-compatibility.

What do you think about it?

Cheers,
BB

**Comment by pekkaklarck** [comment]
I don't remember why we've used the test suite scope and not global and don't see why it couldn't be changed. I need to run tests with Telnet anyway before RF 3.2 rc 1 and can test the PR at the same time.If there are no problems, I'll merge the PR and let users test it during the release candidate period.

**Comment by pekkaklarck** [comment]
I have also been thinking that Telnet should be turned to an external library. It would allow developing it further without being tied to Robot Framework's release schedule.

**Comment by pekkaklarck** [comment]
Unfortunately PR #3250 had problems making it impossible to merge it now before RF 3.2.

I have also decided it's better to make the Telnet library an external library and submitted #3537 about that. As the result I'm closing all Telnet related issues and PRs (including this one) and linking them from #3537 as a reference. If you are interested in becoming maintainer of the new library and adding this functionality there, please comment #3537 or contact me otherwise.
