### ISSUE TITLE
Promote library stacktraces to ERROR channel

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#3244]
Use case: When developing a library, it is a bit unhelpful to receive errors like e.g. `KeyError: xyz` and nothing more.

While there are diagnostics that live on the DEBUG level, I believe that it's not their rightful place to be there.

Considering also better UX, I would add the stacktrace directly on the error itself like so:

```python
KeyError: 'xyz'

Traceback (most recent call last):
[...]
```

I am not sure if there is some other reason that this happens like that; I'd like to at least debate the possibility to, at least conditionally, raise their level.

I have already read #1916, https://robotframework.org/robotframework/2.1.2/RobotFrameworkUserGuide.html#reporting-keyword-status ; I am thinking that, for CI/CD pipelines (where people attempt to be always-green), it will not change much; on failing executions, the error can be passed directly to the developer.

**Comment by pekkaklarck** [comment]
Tracebacks aren't shown by default because they are confusing for non-programmers and provide no valuable information when a keyword fails unless there's a bug in the library itself. It's already easy to use `--loglevel debug` if you want to see tracebacks and that's generally a good idea during library development. Is this not enough?

**Comment by stdedos** [comment]
[1] I already use `--loglevel trace:info` just in case there is something I need.

* It just feels bad that something so important (an uncaught exception), would be dug deep in DEBUG level (which, by definition, can be too chatty).
* It can be also disappointing that you might need to rerun a test (potentially more than once), to capture your original error; apart from the time spent in doing that.

The above (and maybe a couple of more arguments) lead to behavior [1]; which I am not sure if it's the best course of action for everyday testing.

**Comment by rainydew** [comment]
I used this way to decorate my function, but not convenient as debug (old version of RIDE needs --loglevel debug pattern to work)
```python
import traceback
def trier(func):
    def infunc(*args, **kwargs)
        try:
            return func(*args, **kwargs)
        except:
            print(traceback.format_exc())
            raise


and then
@trier
def yourkeyword(...):
    ...
```

**Comment by pekkaklarck** [comment]
As I already wrote, tracebacks aren't shown by default because they are confusing for non-programmers and also because the provide no valuable information when the library works correctly. I know they are valuable when the library has a bug, but the problem is there's no way to reliably differentiate exceptions that are caused by bugs from exceptions that are explicitly raised by a keyword to signal a failure. And even if there was, showing bug tracebacks for non-technical users wouldn't be too helpful.

We are not going to change the behavior and tracebacks will be logged on debug level also in the future. If you want to make them more visible, you can easily create a listener that logs an error whenever there's a failure.

**Comment by suiluj** [comment]
> We are not going to change the behavior and tracebacks will be logged on debug level also in the future. If you want to make them more visible, you can easily create a listener that logs an error whenever there's a failure.

@pekkaklarck This makes sense.

I implemented a small listener that allows you keep the general log level at info or above but still log the full traceback of an error with a custom log level (defined as argument for the listener).

In case someone is interested:
- [example code: ExceptionTracebackListener.py (link to file in github example repo repo)](https://github.com/juliusunscripted/python-ideas/blob/30b3934b518ac7814a95fcfe298db7f66018cabd/robotframework-tips/robotframework_tips/utils/robot_listeners/ExceptionTracebackListener.py)
- [blog post with detailed explanations](https://www.juliusunscripted.com/posts/robotframework-logging-full-traceback-of-errors-and-exceptions/)
