### ISSUE TITLE
ResultWriter doesn't generate proper log.html file (no info about keywords)

### ISSUE THREAD

**Issue by jurgenwigg** [robotframework/robotframework#3247]
**Name of the tool**
 Robot 

**Description** 
In log.html there are no information about used keywords, even with TRACE log level set. 

**Source**
from robot.api import ResultWriter 
from robot.api import TestSuite 
from robot.conf import RobotSettings 
suite = TestSuite('Activate Skynet') 
settings = RobotSettings() 
RobotSettings.log_level = 'TRACE' 
suite.configure() 
print(settings.log_level) 
suite = TestSuite('Activate Skynet') 
suite.set_tags('smoke', persist=True) 
suite.resource.imports.library('OperatingSystem') 
test = suite.tests.create('setting log level') 
test.keywords.create('Set Log Level', args=['TRACE']) 
result = suite.run(settings) 
write = ResultWriter(result) 
print(settings.get_rebot_settings()) 
write.write_results(settings.get_rebot_settings()) 
write.write_results(report="Test.html", xunit="xunit.xml", log="log.html")

**Comment by pekkaklarck** [comment]
The reason is that the result object returned by `suite.run()` doesn't contain any information related to keywords. It's enough to create report or xUnit output, but for functional log you need to pass the output.xml to `ResultWriter` instead.

I'm not sure where you got this example, but least here in the API docs the need for output.xml file when generating logs is briefly mentioned:
https://robot-framework.readthedocs.io/en/v3.1.2/autodoc/robot.running.html#examples

Please let us know if you have ideas how the docs could be enhanced. The best way to do that is via a PR, but comments here are fine as well.
