### ISSUE TITLE
Use keyword 'should contain' , raise error:a bytes-like object is required, not 'str'

### ISSUE THREAD

**Issue by ding-jing** [robotframework/robotframework#3254]
It works in python2
> Should Contain Any	${res.content}	cdmtest

but in python3:
> FAIL : TypeError: a bytes-like object is required, not 'str'

**Comment by ding-jing** [comment]
the Requests library has changed.
r.content is 'bytes'  instead of 'str', if i change it to r.text , the bug can be avoided.

**Comment by pekkaklarck** [comment]
This isn't really a bug. It's just that in Python 3 text and bytes are not compatible with each others at all. In Python 2 you can mix and match to some extend, but if bytes contain non-ASCII characters you get an exception. With request, you should use `response.text` if the content is text both in Python 2 and 3.

**Comment by Durgeshhukla** [comment]
I understand this issue is closed but I am facing this problem now, When I execute my code without using robot framework trying to read windows network interfaces the API reads it as string and works as expected, but when I run the python code with robot framework then there is same TypeError Byte-like object is required not str. I am not sure how to overcome this?
