### ISSUE TITLE
Why no automated testing? Travis CI, CircleCI, AppVeyor, Azure Pipelines, etc?

### ISSUE THREAD

**Issue by cclauss** [robotframework/robotframework#3275]
It would be cool to see robotframework use one of these free software testing environments.

https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems

**Comment by pekkaklarck** [comment]
The main reason is that free options typically support only Python on Linux (haven't checked lately), but we'd also need Windows, Jython, IronPython and PyPy. Without them CI doesn't really give much benefits because Python/Linux combination I can run on my own laptop faster than on CI. I can run everything else as well (I have Windows virtual machine) but that takes time and there CI would help.

Another reason is that I don't want to maintain a CI system myself. We've been talking that Robot Framework Foundation should take care of it, but it hasn't been done yet. Need to discuss about that again. If someone from the community would be interested to help, that would definitely be appreciated. The foundation can take care of possible hosting fees.

**Comment by cclauss** [comment]
Script for testing every code change on Linux, macOS, and Windows on Travis CI: https://docs.travis-ci.com/user/languages/python/#running-python-tests-on-multiple-operating-systems  Similar things can be done on the others or natively with GitHub Actions CI.

**Comment by MaciejWiczk** [comment]
Github actions seems like a good, cross platform choice. Currently there is a need to signup for beta, but it's going to be public at november. I could give it a try, when possible.

**Comment by bollwyvl** [comment]
On #3045, @rasjani (_hej, Jani!_) demonstrated the whole matrix listed [above](https://github.com/robotframework/robotframework/issues/3275#issuecomment-523659647) quite robustly with azure pipelines, i believe. Open source projects are only limited by [10 parallel jobs](https://azure.microsoft.com/en-us/blog/announcing-azure-pipelines-with-unlimited-ci-cd-minutes-for-open-source/), so that PR (14 jobs) would saturate it for a good amount of time, but it would no doubt be worth it vs future contributor review time (and, presumably, platform-specific edge case regression issues) saved.

If queue wait times become a problem, it can certainly make sense to "gate" the big matrix with high-impact, low-cost jobs like linting/static analysis and a "fail fast" reference configuration, e.g. Linux with cpython37, and then proceed. Those are pretty micro-optimizations, and might not even be necessary... :euro: can't buy happiness, but it sure can buy additional CI assets.

**Comment by rasjani** [comment]
patch is still available: http://www.pcuf.fi/~rasjani/robot_ci.patch and it was made by request of @IsNoGood  due to nobody willing to do it.

Patch has *all* the cpython/jython/pypy combinations across windows and linux (and osx which wasnt requested initially) and even some bugfixes to allow things to run more smootly on certain ci envs. 

Catching warnings shouldnt be too big thing to add - this was mentioned in some issue some tije ago that it would be nice to catch deprecated api usage within rf.. 

And if Pekka needs to reports to be uploaded to somewhere where they can be viewed, they could be uploaded somewhere with some help but this wasn't really a requirement nor mentioned when i made the pipeline.

**Comment by cclauss** [comment]
Sounds AWESOME.  I hope this gets landed.

**Comment by bollwyvl** [comment]
@rasjani how might we proceed? Just get a demo on a fork spun back up and show it working? happy to help!

> Patch has all the cpython/jython/pypy combinations across windows and linux (and osx which wasnt requested initially) 

but will it run on a [dead badger](http://strangehorizons.com/non-fiction/articles/installing-linux-on-a-dead-badger-users-notes/)? but seriously, it's very impressive stuff. Having a good pattern would probably help for non-core (but still first-party) stuff like https://github.com/robotframework/SeleniumLibrary/issues/1451.

> reports to be uploaded to somewhere

yeah, for those that haven't dug into it: like travis, azure can connect to near anything, but much like jenkins can also hold onto reports, binaries, whatever as part of the build, or in a "channel", or a few other things. heck, just pushing to named branches on a(nother) repo is a fine way to go. And perhaps one of the test management services has an open source tier, and has integrated any outputs these runs would create.

> Github actions seems like a good, cross platform choice.

Indeed, this will be fine, too, but things are still moving pretty fast over there. But it might be very compelling indeed to write actions _with_ Robot i the future :thinking:

**Comment by MaciejWiczk** [comment]
> And perhaps one of the test management services has an open source tier, and has integrated any outputs these runs would create.

There is [ReportPortal.io](https://github.com/marketplace/reportportal-io-ai-powered-test-automation-reporting/plan/MDIyOk1hcmtldHBsYWNlTGlzdGluZ1BsYW4zMTQw#pricing-and-setup) that can load the runs of robotframework and pytests testcases from listener, but it's a biggie and You need a place to set it up and grant accesses etc. Robotframework testcases can by run by pytest, more [here](https://github.com/pytest-dev/pytest/issues/2530).
It would also be nice to collect coverage from tests with [CodeCov](https://github.com/marketplace/codecov), or [Coveralls](https://github.com/marketplace/coveralls)

**Comment by bollwyvl** [comment]
of course, the built-in azure test views are just fine. it's just that
while _convenient_ to have your ci be all-singing, if free, it might not be
there tomorrow! This is fine for compute, but not storage!

**Comment by tysonite** [comment]
I've tried Github Actions to achieve this topic. Please see PR above.

**Comment by pekkaklarck** [comment]
GitHub actions looks really cool! I also submitted issue #3420 about setting up CI in general. It explains some of the background, different solutions, and so on. Let's use that for further discussion.
