### ISSUE TITLE
Since chromedriver v 76 my tests getting StaleElementReferenceException

### ISSUE THREAD

**Issue by bednaJedna** [robotframework/robotframework#3281]
Chromedriver v. 76.x used with Chrome version 76.x produces exception when trying to return datalayer via "execute_javascript" method.

**However, when I use Chromedriver v. 75x with Chrome v. 76x, everything is ok, no exceptions are thrown.**

Unfortunately I cannot provide concrete code example, project I have been working on is not open source.
 
**Steps to reproduce:**

I am using up-to-date versions of RobotFramework with seleniumLibrary and custom libraries written in Python to test datalayer.

1. After needed actions on website (like click on some element) are done, I try to get datalayer content using the way specified in RobotFramework documentation:

```
 def _get_datalayer(self):
        selenium = BuiltIn().get_library_instance("SeleniumLibrary")
        return selenium.execute_javascript("return dataLayer;")
```

This leads to an exception:

```
ID 5: Button Click Is Tracked                                         | FAIL |
StaleElementReferenceException: Message: stale element reference: stale element not found
  (Session info: chrome=76.0.3809.100)
```
Update: according to chromedriver Support this happens, because previous versions were not W3C compliant. 
However, I am at loss, how to update my tests now, since I am returning datalayer And not working with any element. All previous Steps in test before returning datalayer Are working fine. This exception Is thrown when executing JavaScript.

**Comment by HelioGuilherme66** [comment]
This does not seem related with Robot Framework.

**Comment by pekkaklarck** [comment]
This is definitely related to RF but not to RF core and thus doesn't belong here. The underlying issue seems to be in chromedriver or in the tested application.

**Comment by affinage** [comment]
@bednaJedna did you manage to handle this?

**Comment by bednaJedna** [comment]
@affinage hi, yes. The problem was that some elements were pushed to the datalayer. After filtering out those events via simple JavaScript function, I was able return what I needed.

**Comment by affinage** [comment]
@bednaJedna 
thanks. 
i've also figured out hot to handle it.

if needed, it's just: 
`return json.loads(selenium.execute_script("return JSON.stringify(dataLayer);"))`

**Comment by VadimKirilchuk** [comment]
That was the only thread I could find over the whole internet about this issue. Sorry for necroposting into the closed thread, but here is the explanation of the issue or at least what happened with me:

Sometimes somebody can put the whole DOM element into DataLayer:
21: {event: "event.click", event.element: **span.radio**, event.elementClasses: "radio", event.elementId: "", event.target: "", …}
22: {event: "event.click", event.element: **input#inpu**t, event.elementClasses: "input", event.elementId: "my_input", ...}

So, when you execute a javascript to return the dataLayer, WebDriver has to locate those elements and guess what happens if they were clicked before but then dissapeared from the DOM?

Exactly, you'll get a StaleElementReferenceException. Surprisingly enough that doesn't have any impact on the Chrome DevTools and that's because it doesn't need to transfer anything over the wire, it simply returns you the whole javascript object.

Two ways to fix that:

1. return dataLayer but filter out all events which contain DOM elements

1. Don't put elements into dataLayer!

I think JSON.stringify is a poor solution as it returns you a plain String instead if object, but it will also work.
