### ISSUE TITLE
How do I use the - S parameter?Error reporting authority denied

### ISSUE THREAD

**Issue by clclclclclclcl** [robotframework/robotframework#3289]
![image](https://user-images.githubusercontent.com/49467409/63987452-dbd82d80-cb0a-11e9-8938-a083a2a509cb.png)

**Comment by HelioGuilherme66** [comment]
@clclclclclclcl The image you posted shows that you are using RIDE. To make sure the  issue is not because of RIDE, please run robot from the command window, and check if the error occurs.

In RIDE, there have been some issues related with permissions on Windows, and they are fixed in current Beta version. Go to RIDE project to see how to install v1.7.4b.

**Comment by pekkaklarck** [comment]
I don't really understand the problem and it seems it's related to RIDE, not to RF itself.
