### ISSUE TITLE
Document making .robot files executable

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3291]
It is possible to run *.robot files directly in shell by changing access rights to +x and adding:
```#!/usr/local/bin/robot``` as first line, but such execution way is not documented.

**Comment by eternalconcert** [comment]
This is not a Robot Specific behaviour: https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by sebastianciupinski** [comment]
Lists, loops, returns aren't to, however they are documented. For me,
documenting this is quick win, but I may be wrong and this should be kept
as a secret.

wt., 3 wrz 2019, 15:22 użytkownik eternalconcert <notifications@github.com>
napisał:

**Comment by eternalconcert** [comment]
Don't wanted to be offensive, but I think there is a major difference between lists/loops and a Shebang: 

The list and loop syntax is Robot specific, the Shebang is not.
And it only works on Unix/Linux systems.

**Comment by pekkaklarck** [comment]
Yeah, this trick isn't Robot specific but oddly enough it never occurred to me it works also with Robot! I don't see any harm documenting it, on the contrary, so lets do it. Have you @sebastianciupinski looked where in the User Guide would be a suitable place? Interested to provide a PR?

Notice that instead of using `#!/usr/local/bin/robot`, it's probably better to use `#!/usr/bin/env robot` to make the shebang independent on the exact installation location. That's the recommended approach with Python as well.

**Comment by eternalconcert** [comment]
I think, the right place would be somewhere around [executing-robot-framework](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#executing-robot-framework)

**Comment by eternalconcert** [comment]
I updated my previous PR accordingly: https://github.com/robotframework/robotframework/pull/3294

**Comment by pekkaklarck** [comment]
I don't think this is so important that it should be explained as part of installation instructions. I proposed a better place, and gave some other comments, in by review to #3294.

**Comment by pekkaklarck** [comment]
Have you @eternalconcert had time to look at my comments to your PR?

**Comment by pekkaklarck** [comment]
I wanted to get this issue closed and added a section to the User Guide about this in 3ba2d3776e5205d9ed5ec5a0d0edaae1c4c3ab17 myself.
