### ISSUE TITLE
Feaure Request: Execute Test Setup/Teardown from Suite level and Test level

### ISSUE THREAD

**Issue by JaPyR** [robotframework/robotframework#3303]
Hello,
currently Test Setup/Teardown from Test level overrides one from Suite level.
I think it would be useful to have ability to execute both Setup/Teardown from both levels.

I have the following use case:
On Suite Level in Test Teardown I have keyword that submits result to external system, make screenshot if test case failed and if test case passed removes all screenshots that were made.
In case I want to perform some addition steps before/after execution of particular test case I have to wrap whole test case in keyword like "Execute TCXXX" and add preparation step as first step in keyword and put clean up in keyword teardown

**Comment by pekkaklarck** [comment]
I'm not 100% sure do you mean you'd like a setup/teardown executed once per test suite or that you could specify multiple setups/teardowns for each test. The former is possible by using suite setups/teardowns, but my guess is that you mean the latter. That isn't possible, every test can have max one setup/teardown, and won't be changed for the following reasons:

- Possibility to override setup/teardown set on Settings is an important feature. Changing that so that test would get multiple setup/teardown would both remove a useful feature and be massively backwards incompatible change.
- We could add some new syntax to allow tests to have multiple setups/teardowns, but that would be a huge task.
- Setup/teardown can already now be specified as a higher level keyword doing multpile actions. Additionally it's possible to use `Run Keywords` to execute multiple keywords without creating a separate higher level keywords.
- In my opinion the current design with max one setup/teardown is good.
- If you want to report status to external systems, it's a lot better idea to use listeners instead.

**Comment by pekkaklarck** [comment]
This feature has been discussed before. The aforementioned `Run Keywords` (#572) was actually added after this mailing list discussion:
https://groups.google.com/forum/#!topic/robotframework-users/SKgu-1iw_qc
