### ISSUE TITLE
[DateTime] Get Current Date with epoch format and timezone UTC return non UTC timestamp

### ISSUE THREAD

**Issue by ByJacob** [robotframework/robotframework#3306]
Keyword:
`${date}=	Get Current Date	time_zone=UTC	result_format=epoch`
used in another time zones don't return current UTC timestamp, because in python code time is processed 2 times:
- first from local to UTC - [DateTime.py:352](https://github.com/robotframework/robotframework/blob/960c129cf1b182cdde8ef3de0f0a39f3e157ba5a/src/robot/libraries/DateTime.py#L352)
- second time from local to UTC - [Datetime.py:614](https://github.com/robotframework/robotframework/blob/960c129cf1b182cdde8ef3de0f0a39f3e157ba5a/src/robot/libraries/DateTime.py#L614) - [mktime doc](https://docs.python.org/3/library/time.html#time.mktime)

In second step we have utc time, so we don't want convert it from local to utc.

**Comment by pekkaklarck** [comment]
Thanks, need to look this more closely.

**Comment by pekkaklarck** [comment]
You are definitely right, we shouldn't use [time.mktime](https://docs.python.org/3/library/time.html#time.mktime) when converting UTC datatime object to epoch seconds, instead we should use [calendar.timegm](https://docs.python.org/3/library/calendar.html#calendar.timegm). The problem is that because we use naive datatime objects, we cannot know is the converted `dt` in UTC or not.

**Comment by pekkaklarck** [comment]
Because the epoch time is same everywhere, regardless timezones or DST, one option would be using `datetime.now()`, not `datetime.utcnow()` if timezone is UTC _and_ result format is epoch. 

Proof:
```python
>>> time.mktime(datetime.now().timetuple()) - calendar.timegm(datetime.utcnow().timetuple())
0.0
```

**Comment by pekkaklarck** [comment]
This ought to be now fixed. The easiest way to avoid this problem is always using local time when getting the current date as epoch time.
