### ISSUE TITLE
Get output as JSON rather than writing to XML

### ISSUE THREAD

**Issue by ramgesg** [robotframework/robotframework#3307]
Is it possible to get the result as a JSON object rather than writing to XML?

I am using RF for RPA and the result has to be provided as a JSON response. The resultwriter.py has option to only write to an XML file. 

```python
def _write_output(self, result, path):
        self._write('Output', result.save, path)
```

**Comment by pekkaklarck** [comment]
It's not possible but could be useful. Would also require changing Rebot to understand such output.json files in addition to output.xml, documenting that format, and so on. Are you interested to help implementing that?

**Comment by pekkaklarck** [comment]
No interest so closing. I'm fairly certain we'll at some point add support for storing results as JSON in addition to XML. That alone wouldn't be enough to solve this issue, though, because our possible `output.json` obviously wouldn't be compatible with all external services accepting JSON. They'd most likely expect certain kind of JSON, and that needed to be created based on our `output.json`. And that's naturally possible already today based on our `output.xml`.
