### ISSUE TITLE
Problems reporting errors when library import fails on Python 2 and import path contains non-ASCII characters

### ISSUE THREAD

**Issue by kenifanying** [robotframework/robotframework#3338]
Hi,

I find libdoc will throw UnicodeDecodeError exception if generate xml file failed and the python file path contain Chinese character . The error message is not accurate enough.

```
C:\Users\tony\Downloads>python -m robot.libdoc test测试\random.py test.xml
Building library 'test测试\random.py' failed: UnicodeDecodeError: 'ascii' codec
can't decode byte 0xb2 in position 71: ordinal not in range(128)

Try --help for usage information.
```

I expected this ressult:
```
C:\Users\tony\Downloads>python -m robot.libdoc test\random.py test.xml
Importing test library 'C:\Users\tony\Downloads\test\random.py' failed: ImportEr
ror: cannot import name is_native_int
Traceback (most recent call last):
  File "C:\Users\tony\Downloads\test\random.py", line 29, in <module>
    from Cryptodome.Util.py3compat import is_native_int
PYTHONPATH:
  C:\Windows\system32\python27.zip
  C:\Python27\DLLs
  C:\Python27\lib
  C:\Python27\lib\plat-win
  C:\Python27\lib\lib-tk
  C:\Python27
  C:\Python27\lib\site-packages
  C:\Python27\lib\site-packages\win32
  C:\Python27\lib\site-packages\win32\lib
  C:\Python27\lib\site-packages\Pythonwin
  C:\Python27\lib\site-packages\wx-2.8-msw-unicode

Try --help for usage information.
```
I upload the simple demo project 
[test测试.zip](https://github.com/robotframework/robotframework/files/3727368/test.zip)

Python 2.7.16
pycryptodome 3.6.4
Robot Framework 3.1.1 (Python 2.7.16 on win32)
System: Windows 7 SP1 X86_64

**Comment by pekkaklarck** [comment]
I was able to reproduce this problem on my Windows virtual machine with Python 2 but everything worked fine with Python 3. Also on Linux both Python 2 and 3 worked fine.

Interestingly on my Windows machine I was able to use non-ASCII characters like `ä` in directory names just fine. That may be due to my system using cp1252 and my console using cp850 which both support `ä` but don't support Chinese.

Could you @kenifanying test does this work with Python 3 on your environment? If it does, I'd highly recommend migrating there because it supports non-ASCII characters in general so much better than Python 2. Python 2 EOL is also very close, so everyone should be migrating to Python 3 also for that reason.

I can still try debugging this a bit more, but because this may be environment config specific it can be hard. Could you @kenifanying tell what encoding your system uses?

**Comment by kenifanying** [comment]
> 
> 
> I was able to reproduce this problem on my Windows virtual machine with Python 2 but everything worked fine with Python 3. Also on Linux both Python 2 and 3 worked fine.
> 
> Interestingly on my Windows machine I was able to use non-ASCII characters like `ä` in directory names just fine. That may be due to my system using cp1252 and my console using cp850 which both support `ä` but don't support Chinese.
> 
> Could you @kenifanying test does this work with Python 3 on your environment? If it does, I'd highly recommend migrating there because it supports non-ASCII characters in general so much better than Python 2. Python 2 EOL is also very close, so everyone should be migrating to Python 3 also for that reason.

Thank you for your reply. It works with python 3 on my current environment.  I know python 2 EOL is so close, but I can't decide the migration on my company's project.
> 
> I can still try debugging this a bit more, but because this may be environment config specific it can be hard. Could you @kenifanying tell what encoding your system uses?

I think the encoding is gbk(or called cp936) in Simplified Chinese Windows environment.

**Comment by pekkaklarck** [comment]
Seems I cannot set cp936:

```
E:\robotframework>chcp 936
Invalid code page
```

**Comment by pekkaklarck** [comment]
When you import something like `my/path/mylib.py` with Robot, what Robot does is adding that `my/path` to Python's `sys.path` before importing module `mylib`. Based on my investigation that happens also in this case, but for some reason that doesn't work with Python 2 on Windows when the path contains Chinese characters (and possibly other non-ASCII characters). My guess is that this is due to the path that's added to `sys.path` being Unicode while Python 2 in general apparently expects `sys.path` to be bytes (i.e. `str`). It's somewhat strange there are no problems when I use a path like `hyvä/polku`, but that might be due to my Windows system having Western encoding supporting `ä` in general.

One thing to try is encoding the Unicode path to bytes before adding it to `sys.path`. The problem is that we needed to know what's the correct encoding is and, annoyingly, the correct encoding depends on the operating system. Windows interestingly also has a different system encoding and console encoding, and both of them depend on the system configuration. Linux (and OSX) nowadays using UTF-8 everywhere is probably the reason this particular problem doesn't occur on Linux even with Python 2.

We have some pretty advanced utilities that try to sniff what the correct encoding is and they could possibly be used to encode the Unicode path to bytes. My understanding is that on Windows `sys.path` is encoded using the system encoding, so we could use our `system_encode` utility. It should be used in [robot/utils.importer.py](https://github.com/robotframework/robotframework/blob/af38bd5a7d93289ba6f3ab5c758c1b1ce7cea375/src/robot/utils/importer.py#L242) as shown by the diff below:

```diff
diff --git a/src/robot/utils/importer.py b/src/robot/utils/importer.py
index 1b0a47f..c76dd82 100644
--- a/src/robot/utils/importer.py
+++ b/src/robot/utils/importer.py
@@ -19,7 +19,7 @@ import inspect
 
 from robot.errors import DataError
 
-from .encoding import system_decode
+from .encoding import system_decode, system_encode
 from .error import get_error_details
 from .platform import JYTHON, IRONPYTHON, PY3
 from .robotpath import abspath, normpath
@@ -239,6 +239,7 @@ class ByPathImporter(_Importer):
 
     def _import_by_path(self, path):
         module_dir, module_name = self._split_path_to_module(path)
+        module_dir = system_encode(module_dir)
         sys.path.insert(0, module_dir)
         try:
             return self._import(module_name)
```

I tested the above changes but they had no effect on my machine. That's not really a surprise, though, because `system_encode` uses cp1250 on my environment and it cannot encode `test测试` correct. The fix _could_ work on environments where the system encoding actually supports that string, so it would be great if you @kenifanying could test this.

**Comment by pekkaklarck** [comment]
A possible workaround for this problem is importing the library by name, not by path. In practice that means not importing like `my/path/mylib.py`, but instead adding `my/path` to `PYTHONPATH` _before_ execution and then importing just `mylib`.

**Comment by kenifanying** [comment]
> 
> 
> When you import something like `my/path/mylib.py` with Robot, what Robot does is adding that `my/path` to Python's `sys.path` before importing module `mylib`. Based on my investigation that happens also in this case, but for some reason that doesn't work with Python 2 on Windows when the path contains Chinese characters (and possibly other non-ASCII characters). My guess is that this is due to the path that's added to `sys.path` being Unicode while Python 2 in general apparently expects `sys.path` to be bytes (i.e. `str`). It's somewhat strange there are no problems when I use a path like `hyvä/polku`, but that might be due to my Windows system having Western encoding supporting `ä` in general.
> 
> One thing to try is encoding the Unicode path to bytes before adding it to `sys.path`. The problem is that we needed to know what's the correct encoding is and, annoyingly, the correct encoding depends on the operating system. Windows interestingly also has a different system encoding and console encoding, and both of them depend on the system configuration. Linux (and OSX) nowadays using UTF-8 everywhere is probably the reason this particular problem doesn't occur on Linux even with Python 2.
> 
> We have some pretty advanced utilities that try to sniff what the correct encoding is and they could possibly be used to encode the Unicode path to bytes. My understanding is that on Windows `sys.path` is encoded using the system encoding, so we could use our `system_encode` utility. It should be used in [robot/utils.importer.py](https://github.com/robotframework/robotframework/blob/af38bd5a7d93289ba6f3ab5c758c1b1ce7cea375/src/robot/utils/importer.py#L242) as shown by the diff below:
> 
> ```diff
> diff --git a/src/robot/utils/importer.py b/src/robot/utils/importer.py
> index 1b0a47f..c76dd82 100644
> --- a/src/robot/utils/importer.py
> +++ b/src/robot/utils/importer.py
> @@ -19,7 +19,7 @@ import inspect
>  
>  from robot.errors import DataError
>  
> -from .encoding import system_decode
> +from .encoding import system_decode, system_encode
>  from .error import get_error_details
>  from .platform import JYTHON, IRONPYTHON, PY3
>  from .robotpath import abspath, normpath
> @@ -239,6 +239,7 @@ class ByPathImporter(_Importer):
>  
>      def _import_by_path(self, path):
>          module_dir, module_name = self._split_path_to_module(path)
> +        module_dir = system_encode(module_dir)
>          sys.path.insert(0, module_dir)
>          try:
>              return self._import(module_name)
> ```
> 
> I tested the above changes but they had no effect on my machine. That's not really a surprise, though, because `system_encode` uses cp1250 on my environment and it cannot encode `test测试` correct. The fix _could_ work on environments where the system encoding actually supports that string, so it would be great if you @kenifanying could test this.

I test the robot/utils.importer.py code changes, but it still throw same UnicodeDecodeError exception.

**Comment by pekkaklarck** [comment]
This problem affected also library imports during execution, and in that case the whole execution crashed making the problem a lot more severe than I initially thought. Luckily it only occurs if there's an error importing the library, the path contains non-ASCII characters, and you are on Python 2.

The same problem also caused failure traceback (logged on DEBUG level when a keyword fails) to have non-ASCII paths printed wrong. In that case non-ASCII characters like `ä` were shown like `\xc3\xa4` so this wasn't too severe.

Fixing all this was also a bit more complicated than I though. With Python 2 traceback entries are bytes, and as I had noticed earlier, paths were encoded using the system encoding. Entries also contain the line where the error occurs, and its encoding depends on the source encoding of the file where that line is located. In Python 2 the source encoding is ASCII by default, but you can set it to something else with a magic comment like `# coding=UTF-8`. As a result entries can contain items with different encoding and we cannot even know what encoding the text actually uses. I decided to handle this so that paths are decoded using the system encoding, but text is decoded using UTF-8 (an ASCII compatible guess) so that error handler is set to 'replace'. That ought to avoid all UnicodeDecodeErrors and tracebacks ought to be shown correctly in over 99,9% of cases.
