### ISSUE TITLE
How to support new status "WARN" for tests

### ISSUE THREAD

**Issue by itshaya** [robotframework/robotframework#3342]
I know the robot framework has only two test statuses PASS or FAIL. I need to have another test status "WARN".

This status should be set after a test is executed and contains warning messages. 

Any idea?

**Comment by pekkaklarck** [comment]
There's no such status nor are the plans to add it. We probably will add explicit SKIP status at some point, but because we haven't been able to agree on the design (#2087) and there are many other high priority issues to be implemented, I cannot promise when. Even if/when the SKIP status is implemented, I don't think it would be a good idea to mark tests emitting warnings skipped or at least it wouldn't be done automatically.

The main problem I see with warnings and errors is that you cannot see them in report at all. Tests getting WARN (or SKIP) status wouldn't actually fully fix that, because you can get warnings and errors also outside tests (e.g. imports). I've been thinking it would be a good idea to show warnings and errors somehow in the report, possibly with only a small text like "3 warnings and 2 errors occurred" which would then link to the log file.

Because no WARN level will be implemented, I close this issue. If you think showing warnings and errors in the report, like I proposed above, would be a good idea, please submit a separate issue about it.
