### ISSUE TITLE
permission denied when executing python script

### ISSUE THREAD

**Issue by rfsch** [robotframework/robotframework#3348]
Hi 

I have tried the example from the Process docs 

(http://robotframework.org/robotframework/latest/libraries/Process.html#Example) 

for running script.py

`*** Settings ***`
`Library           Process`
`Suite Teardown    Terminate All Processes    kill=True`

`*** Test Cases ***`
`Example`
`    ${result} =    Run Process    ${CURDIR}/script.py`

I am getting `PermissionError: [Errno 13] Permission denied: '/home/rs/script.py'`

My script.py code:

`print('Hello World')`

Why does the Example for executing script.py not work ?

I am on Ubuntu 18.04
I tried setting u+x on script.py but then I get
`OSError: [Errno 8] Exec format error: '/home/rs/script.py'`

**Comment by villelaitila** [comment]
Please add `#!/usr/bin/env python` into the beginning of your script.py

Btw, your above Robot syntax has issues with spaces, e.g.   instead of `Suite Teardown Terminate All Processes kill=True`  it should be  `Suite Teardown  Terminate All Processes  kill=True`
(single space is not enough). And same applies also for some other rows you have there.

**Comment by pekkaklarck** [comment]
Yeah, it sounds like the shebang line would be missing. Alternatively it would be possible to use

```
${result} =    Run Process    python    ${CURDIR}/script.py
```
