### ISSUE TITLE
Tidy should have option to leave whitespaces as they are

### ISSUE THREAD

**Issue by mnojek** [robotframework/robotframework#3353]
I have my robot files formatted in a way that they are easy to read (I aligned code in columns). 
I need now to update the files (migration from 3.0.2 to 3.1.1 RF version) to include new FOR loop syntax but when I use tidy, all my custom spaces between the cells (keywords, vars etc.) are getting unified and the whole code is difficult to read. It would be great to have a switch in tidy for turning off the making off whitespaces so that I can preserve the ones I have. I didn't find solution for that. Maybe there is another script that does that (updates the code to the new syntax)?

**Comment by pekkaklarck** [comment]
Unifying whitespace usage is one of Tidy's main features, but I can see disabling that and letting Tidy handle other cleanup could sometimes be useful. Tidy has been basically rewritten for RF 3.2 because the new parser (#3076) broke the old implementation totally. With the new Tidy implementation it shouldn't be too complicated to add this functionality, but at least I don't have time for that. Are you interested to look at that yourself?

There would be some some things to agree related to design:
- Should all whitespace be preserved or only whitespace inside settings, variables, test cases and keywords?
- How to enable that? One possibility is using the existing `--spacecount` like `--spacecount preserve`.

**Comment by nojas10** [comment]
Thanks for the response, @pekkaklarck .
I can look into that but I cannot ensure that I will succeed.
Regarding your questions I will try to answer them when I will have time to investigate it and think about which approach to use it is the best.

**Comment by pekkaklarck** [comment]
Great! It's probably best to start by looking at the current Tidy code. It will probably still be modified in the near future, but the overall design shouldn't change. We can also discuss this further on `#devel` channel on our Slack.

**Comment by mnojek** [comment]
@pekkaklarck I finally found some time and created PR #3612 that implements this change. Please feel free to review it :)

**Comment by pekkaklarck** [comment]
I finally had time to fully review PR #3612, including testing it locally. I like the functionality in general but there are some problems that still need to be addressed as I explain in my [comment to the PR](https://github.com/robotframework/robotframework/pull/3612#issuecomment-681829998).

**Comment by pekkaklarck** [comment]
There are still [some problems with the PR](https://github.com/robotframework/robotframework/pull/3612#issuecomment-748620030) that should be addressed. It would be a lot simpler if spaces just weren't touched at all when they ought to be preserved.

A new [external Tidy project](https://github.com/MarketSquare/robotframework-tidy) has recently been started. Instead of enhancing the current built-in Tidy, we might want to concentrate on the new project and add this functionality into it.

**Comment by pekkaklarck** [comment]
It was agreed that all further Tidy development happens in the new project and that the built-in Tidy is now in maintenance mode meaning we only do bug fixing.

Thanks @mnojek for submitting this issue and the PR. The resulted discussion was the main spark to create the new external Tidy project!
