### ISSUE TITLE
Libdoc timeout and no rc

### ISSUE THREAD

**Issue by axi92** [robotframework/robotframework#3358]
I tied to generate an html documentation with libdoc and the command never returns.
```
$ python -m robot.libdoc /home/user/.local/lib/python2.7/site-packages/PyTridentor ~/PyTridentor.html
/home/user/PyTridentor.html
```
The html output is fine but there is never a return.
Unfortunately I can't share the library ;( that somebody could reproduce this.

Version: Version:  3.1.2 (Python 2.7.15+ on linux2)

**Comment by axi92** [comment]
We found maybe the cause of the problem:
```
        while self._is_listening:
            pass
```
The var is changed by another thread. Is there a way libdoc can handle this?

**Comment by pekkaklarck** [comment]
No, Libdoc cannot do anything to this issue. You should construct the library so that Libdoc can create an instance of it without this kind of side effects. It's typically best if instantiating the library without arguments works that way, but you can also add an optional argument to `__init__` that Libdoc can use to tell that side effects aren't allowed.
