### ISSUE TITLE
Add support for Java 11

### ISSUE THREAD

**Issue by respenica** [robotframework/robotframework#3359]
When running with Java 11 (OpenJDK Runtime Environment Corretto-11.0.5.10.1):
java robotframework-3.1.2.jar ...

The below warning is shown:

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.python.core.PySystemState (file:/robotframework-3.1.2.jar) to method java.io.Console.encoding()
WARNING: Please consider reporting this to the maintainers of org.python.core.PySystemState
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

**Comment by pekkaklarck** [comment]
This seems to be due to Jython using some private Java API via reflection but with this information only it's not possible to know where. It might be that this occurs always with Jython with Java 11, or it could be that we use some Python API that Jython implements so that it causes that warning. In the latter case we could avoid calling that API, but it might remove some important functionality. Can you investigate this further so that we'd know where/why the problem really happens? Have you tested does this happen also with normal Jython or only when using the JAR distribution?

Jython team is pretty close to get Jython 2.7.2 beta out. I think it contains some fixes to this kind of issues and would be good to test it once the beta is released.

**Comment by respenica** [comment]
Hello,
you are right when you say this is a problem with jython. It's not  a issue of Robot Framework
I did not realize that the  jar distribution of robot framework is in fact jython with robot framework inside.
You may close the issue.
Roberto

**Comment by pekkaklarck** [comment]
OK, I'll close this issue. Notice that although the underlying reason is likely Jython accessing some private API, it could be that it does it only because we use a certain Jython feature and we possibly could avoid that in our code base. If you have interest to study this further and find out why exactly this warning is emitted, please comment this issue or open a new one.

Another thing to test would be checking does Jython 2.7.2 fix any of these warnings. Beta 2 has been just released and you can find an installer here:
https://repo1.maven.org/maven2/org/python/jython-installer/2.7.2b2/

**Comment by respenica** [comment]
Hello,
I've tested Jython 2.7.2 Beta 1 and Beta 2 and both have the warning.
I've opened and issue for Jython: https://github.com/jythontools/jython/issues/158

Roberto

**Comment by pekkaklarck** [comment]
Great that you've tested this. I think the Jython project still mainly uses https://bugs.jython.org, not the issue tracker on GitHub, though.

**Comment by respenica** [comment]
Done: https://bugs.jython.org/issue2822
