### ISSUE TITLE
Robotframework not detecting 2 different keywords what are different

### ISSUE THREAD

**Issue by vkrishnan** [robotframework/robotframework#3393]
```
    Resource file 'Staff.robot' contains multiple keywords matching name 'Login as 'Leader' Who 
    Belongs to the Group 'Manager' on the 'Home Device'':
        Login as '${staff_type}' Who Belongs to the Group '${staff_group}' on the '${device_type}'
        Login as '${staff_type}' on the '${device_type}'
```

Robotframework 3.1.2 reports these two keywords are conflicting. It seems like it is matching the first and last blocks. However it works if I change the "on" to "to" on one of the keyword like
`Login as '${staff_type}' Who Belongs to the Group '${staff_group}' **to** the '${device_type}'`

**Comment by pekkaklarck** [comment]
It seems to me the keyword you used really matches both of these definitions. You can verify that by commenting/renaming/removing the first keyword definition and seeing does the same keyword you used earlier match the latter definition. If it matches, check what the `${staff_type}` variable contains.

If I'm right, the solution is specifying a custom pattern to `${staff_type}`, for example, so that it matches anything but `'` (i.e. `[^']*`). See the User Guide for details.

**Comment by pekkaklarck** [comment]
Now new info. Closing.
