### ISSUE TITLE
Consider adding an option to not embed JS/CSS into the report

### ISSUE THREAD

**Issue by php-coder** [robotframework/robotframework#3394]
Jenkins serves static content with [Content Security Policy enabled](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy). By default, it doesn't allow to execute inlined CSS/JavaScript code and [this prevents users to open Robot Framework reports](https://stackoverflow.com/questions/36607394/error-opening-robot-framework-log-failed) when they were published during a build.

There is known workaround that people have documented: https://issues.jenkins-ci.org/browse/JENKINS-32118 but the only way to make it fixed properly is to modify the generated report to create separate files with JS/CSS code.

I suggest to add an option that will do that.

**Comment by php-coder** [comment]
P.S. I've just realized that as part of this, we also need to decide on how to eliminate `eval` usage.

**Comment by pekkaklarck** [comment]
Having an option to save Javascript and CSS files into external files sounds good to me. But there are some design decisions to be made:

1. Should all JS content be written to a single file and all CSS to another, or should we just save the same JS/CSS files we normally embed to log/report on disk?

2. Should we allow disabling writing JS/CSS files? They don't change between runs (may change between releases) so old files can be reused.

3. Would the location where JS/CSS files are read by log/report be configurable? At least 2. doesn't make much sense otherwise.

Anyone interest to think about the design and, once we can agree on it, implement this enhancement?

**Comment by php-coder** [comment]
@pekkaklarck Thank you for the quick feedback!

> Should all JS content be written to a single file and all CSS to another, or should we just save the same JS/CSS files we normally embed to log/report on disk?

From CSP point of view, it doesn't matter because it only cares about the source (location) of the code and not about the number of files. So, I'd say this decision is more about maintenance and developers comfort.

> Should we allow disabling writing JS/CSS files? They don't change between runs (may change between releases) so old files can be reused.

This looks like a minor optimization that affects only generation report time. I see that this procedure is performed often only when developers run Robot Framework locally. Is my understanding correct?

If yes, then we can start without this option and always overwrite generated files. This reduces a chance to have stale resources and violate of [the least astonishment principle](https://en.wikipedia.org/wiki/Principle_of_least_astonishment). Later, if we see a demand, we can implement it.

> Should the location where JS/CSS files are read by log/report be configurable? At least 2. doesn't make much sense otherwise.

What the use cases are covered by this? I couldn't make up any, so I'd suggest to wait until we will get some.

**Comment by pekkaklarck** [comment]
I thought the problem with CSP was that Javascript originated from the workspace, not that it was embedded into the same file. If that's not the case, then just splitting JS to separate files ought to be enough. I'd be somewhat surprised about this because it would make avoiding CSP super easy in general.

**Comment by php-coder** [comment]
> I thought the problem with CSP was that Javascript originated from the workspace, not that it was embedded into the same file.

I looked at the page https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy again and I see that you're right -- Jenkis doesn't allow JavaScript in any forms :-(

So, in fact, we can't fully fix the issue on Robot side, only reduce a number of violations by not embedding CSS/images.

**Comment by pekkaklarck** [comment]
Closing this as the proposed change doesn't fix the CSP problem.
