### ISSUE TITLE
`--help` text related to disabling output has outdated information

### ISSUE THREAD

**Issue by tysonite** [robotframework/robotframework#3422]
The `robot --help` states that if `-o NONE` is specified both log and report are disabled:

```
 -o --output file         XML output file. Given path, similarly as paths given
                          to --log, --report, --xunit, and --debugfile, is
                          relative to --outputdir unless given as an absolute
                          path. Other output files are created based on XML
                          output files after the test execution and XML outputs
                          can also be further processed with Rebot tool. Can be
                          disabled by giving a special value `NONE`. In this
                          case, also log and report are automatically disabled.
                          Default: output.xml
```

However, report is still generated while log is absent. Tested on Robot 3.1.2.

**Comment by pekkaklarck** [comment]
The behavior is actually correct but this documentation is outdated. It used to be so that using `--output none` disabled also log and report, but that was changed already in RF 2.8 (#1444) so that report is created. Apparently only the [User Guide section](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#output-file) was updated then but not the `--help` text. Interesting that nobody has noticed that since the changes was done in May 2013. Great catch!
