### ISSUE TITLE
Isolate test case

### ISSUE THREAD

**Issue by LikHait** [robotframework/robotframework#3447]
As I understood - `Set Environment Variable` will set variable for main robot process.
As a user, I think this is unexpected behavior because expected by isolation between tests/suites.

**Comment by mkorpela** [comment]
Set Environment Variable has worked as it does for about a decade and it is used as is by at least thousands of users.
Environment Variables as a concept do preserve their values as long as the machine/terminal is running.
How would you expect them to work?
How could this change be achieved so that people that are already expecting current way of working would be ok with the change?

**Comment by LikHait** [comment]
> Set Environment Variable has worked as it does for about a decade and it is used as is by at least thousands of users.
> Environment Variables as a concept do preserve their values as long as the machine/terminal is running.
> How would you expect them to work?
> How could this change be achieved so that people that are already expecting current way of working would be ok with the change?

I assumed that each test runs as a subprocess, and changing environment variables does not affect the parent process.
This mechanism can be as a command line option, for example: `--isolate_tests`

**Comment by mkorpela** [comment]
Try pabot —testlevelsplir

**Comment by pekkaklarck** [comment]
Yes, tests and suites executed in one run share same environment variables. They also share the same file system, so if you use e.g. `Create File' in one test, other tests see that file. I don't think isolation on this level would make sense in Robot Framework itself. If you want total isolation, you can run individual tests with `--test` option or by using an external tool like Pabot.
