### ISSUE TITLE
Add a section "Test Execution Messages" at the top of the report

### ISSUE THREAD

**Issue by chache35** [robotframework/robotframework#3471]
Currently, when I want to display important messages of test executions, I use the log level "warning", so that, the messages are displayed in a dedicaced frame "Test Execution Errors" and easily visible.

It works, but it is not really correct because these messages are not really warnings messages.

It could be great to have another frame, named like "Test Execution messages" where all the Log with a specific level are displayed. 
For example log level "MESSAGE".

Mockup : 
![image](https://user-images.githubusercontent.com/56358900/74454802-b5be0400-4e84-11ea-9e7f-acb084f8a1da.png)

**Comment by apallier** [comment]
Hi, related discussion: https://groups.google.com/forum/#!searchin/robotframework-users/new$20log$20level$20global%7Csort:date/robotframework-users/R1fW_GfxS8Y/37QHuSDoCwAJ

**Comment by pekkaklarck** [comment]
What would be the concrete benefit of this compared to adding information to the top level test suite metadata or possibly documentation? Both can be set in test data, given from cli, set dynamically by keywords, and modified by listeners. Such metadata (and documentation) is also already very clearly visible at the top of the report.

If this functionality would be implemented, what different ways there would be to set these messages?

**Comment by pekkaklarck** [comment]
If this was to be implemented, I wouldn't like to add a new section for these messages but instead rename the current "Test Execution Errors" to something more generic like. Then getting messages there could be implemented so that `robot.api.logger` methods (and `BuiltIn.Log` that uses it) get a new optional argument telling should a message should be added there. This argument could be used with all log levels and would be automatically on with warnings and errors.

The above ought to be pretty simple to implement, but I'd still like to hear concrete use cases where this functionality would work better than the current features that Robot has. Then we'd also need someone to implement it and provide a PR.

**Comment by chache35** [comment]
Thank you. You're right. The suite metadata does the job. I didn't realized that.

I would like to display some complementary tests results (more than just Passed/failed) like Benchmarks values, duration of specifically steps, important messages.
I'm going to use the METADATA mechanism for that.

I will close the issue.

**Comment by pekkaklarck** [comment]
Sounds good. Metadata has several benefits like being visible in both log and report, having many different ways to set it, and working already now. We can later consider changing Test Execution Errors to Test Execution Messages and allowing other than error and warning messages there. We have many higher priority issues here already, though, so better to keep this closed. It can be reopened, or a new issue submitted, if needed.
