### ISSUE TITLE
ModuleNotFound when install Robot Framework with Python3.8

### ISSUE THREAD

**Issue by qlvivian** [robotframework/robotframework#3472]
Hi,

The below error was happend when I  try to install the robot-framework by setup.py, under Python 3.8.1.

[root@csspc-d robotframework-master]# python setup.py install
Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import find_packages, setup
  File "/usr/local/python3/lib/python3.8/site-packages/setuptools/__init__.py", line 20, in <module>
    from setuptools.dist import Distribution, Feature
  File "/usr/local/python3/lib/python3.8/site-packages/setuptools/dist.py", line 35, in <module>
    from setuptools import windows_support
  File "/usr/local/python3/lib/python3.8/site-packages/setuptools/windows_support.py", line 2, in <module>
    import ctypes
  File "/usr/local/python3/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'

Thanks for your help

**Comment by pekkaklarck** [comment]
Based on the traceback this is what happens:

- Our `setup.py` runs `from setuptools import find_packages, setup`.
- `setuptools` indirectly imports something from its `windows_support.py` that needs the `ctypes` module.
- Importing `ctypes` fails because your system doesn't have the lower level `_ctypes` module installed. The `ctypes` module is optional and I think `_ctypes` module implements the native OS specific parts. Most likely you don't have them installed.

What the above means:

- We cannot really fix this on our side without dropping `setuptools` usage altogether. I'll thus close this issue.
- The real bug seems to be in `setuptools`. It shouldn't import anything Windows specific when not running on Windows. Or at least it should handle the optional `ctypes` module not being installed. You could try upgrading your `setuptools` installation to see has the problem been fixed. If not, please check does `setuptools` have a bug related to this and submit one if it doesn't.
- You may be able to get the issue resolved by installing the `ctypes` module properly. How to do that depends on your OS.
