### ISSUE TITLE
Native `&{dict}` iteration with FOR loops

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#3485]
It is possible to extract the keys and values in a python for loop. This is not possible in Robot Framework (or we need to use a more complicated strategy to obtain the same result).

In python we can do:
```python
dict = { 'a':'one', 'b':'two'}
for key, value in dict.items():
    print(key, value)
```
It is requested to implement:
```robot
&{dict}=  Create Dictionary  a=one  b=two
FOR    ${key}    ${value}    IN    &{dict}
  LOG  ${key} ${value}
END
```

**Comment by pekkaklarck** [comment]
I think this is a good idea and shouldn't be overly complicated to implement either. Some design decisions should be made, though, and I go through them in separate comments.

**Comment by pekkaklarck** [comment]
Should we require dict iteration to always use two variables like in

    FOR    ${key}    ${value}    IN    &{dict}

or should we also allow using just one variable like

    FOR    ${item}    IN    &{dict}

In the latter case `${item}` would be a tuple. Key and value could be accessed from it like `${item}[0]` and `${item}[1]`, respectively, and it could be also used as `@{item}` to expand the value. This isn't as useful or convenient as `${key}    ${value}    IN    &{dict}` iteration but I guess it could sometimes be useful. On the other hand, someone needing an item with a key and a value could also do

    ${item} =    Create List    ${key}    ${value}

as the first step inside the loop. Not supporting `${item}    IN    &{dict}` wouldn't thus be a big issue.

**Comment by pekkaklarck** [comment]
Should we also allow using `key=value` syntax in FOR loop values? For example:

    FOR    ${key}    ${value}    IN    &{dict}    key=value

This syntax is supported when creating `&{dict}` variables in the Variables section and with the `Create Dictionary` keyword, and supporting it here would be consistent and convenient. If we support it, should it work also if there aren't any `&{dict}` variables?

    FOR    ${key}    ${value}    IN    key=value    foo=bar

In the above case the change would be backwards incompatible because nowadays this same syntax works so that the loop is run once with `${key}` being `key=value` and `${value}` being `foo=bar`. Using [several loop variables](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-several-loop-variables) is pretty rare, though, and there would only be a conflict if all values use `name=value` syntax. There's also an easy workaround to escape the `=` like `foo\=bar` to avoid this. My current thinking is that backwards incompatibility problems are so small compared to benefits that it would be ok.

**Comment by pekkaklarck** [comment]
Currently the best way to iterate over dictionaries is using

    FOR    ${key}    IN    @{dict}

end then accessing values like `${dict}[${key}]` when needed. This is pretty convenient but the proposed syntax would still enhance this quite a bit.

**Comment by pekkaklarck** [comment]
Based on little prototyping this is simple enough to be done still in RF 3.2.

**Comment by pekkaklarck** [comment]
I got implementation and tests ready. Docs are still missing but I'll commit code/test changes soon to let others try this if they are interested. Did following design decisions:

1. Dict iteration works with normal FOR IN loops and with FOR IN ENUMERATE loops. It doesn't work with FOR IN RANGE or FOR IN ZIP loops.

2. It is possible to use separate loop variables for key and value or just one that gets key and value as a tuple. With FOR IN ENUMERATE you have one extra variable for the index. In other words, all these are valid:
   ```
   FOR    ${key}    ${value}    IN    &{dict}
   FOR    ${item}    IN    &{dict}
   FOR    ${index}    ${key}    ${value}    IN ENUMERATE    &{dict}
   FOR    ${index}    ${item}    IN ENUMERATE    &{dict}
   FOR    ${index and item}    IN ENUMERATE    &{dict}
   ```

3. Dict iteration is used if _any_ of the loop values is a `&{dict}` variable. It is possible to use multiple dict variables and also have individual values in `key=value` format. All these are valid:
   ```
    FOR    ${key}    ${value}    IN    &{dict}
    FOR    ${key}    ${value}    IN    &{d1}    &{d2}    &{d3}    
    FOR    ${key}    ${value}    IN    &{dict}    key=value
    ```
   This is invalid and causes an error:
   ```
   FOR    ${key}    ${value}    IN    &{dict}    ooops
   ```

4. Dict iteration is used also if all values use `key=value` syntax even if there were no `&{dict}` variables:
   ```
   FOR    ${key}    ${value}    IN    key1=value1    key2=value2
   ```
   If some values use `key=value` syntax and some don't, dict iteration is not used. For example, this is normal for loops over values `foo=bar` and `normal`:
   ```
   FOR    ${item}    IN    foo=bar    normal
   ```

5. If same key gets multiple value, the last value wins but items are iterated in the definition order. For example, in the following case iterated items will be `a=1`, `b=2` and `c=3`.
   ```
   &{dict} =    Create Dictionary    a=1    b=override
   FOR    ${key}    ${value}    IN    a=override    &{dict}    c=3    b=2 
   ```

**Comment by pekkaklarck** [comment]
This change is mostly backwards compatible, but there are two cases that may cause problems:

1. If there's an iteration over values that are _all_ happen to be in `name=value` format, it will be considered dict iteration, not normal iteration. This can be avoided by escaping like `name\=value` and it is enough to escape just one of the values.

2. Earlier it has been possible to use `&{dict}` in FOR loop values and it has worked exactly as using `${dict}`. After this change using `&{dict}` variables will always initiate dict iteration. The problem can be avoided by using `${dict}`.

**Comment by Snooz82** [comment]
Dear Pekka,

Works fine!
I have one thing regarding the backwards incompatibility.

Incompatibility 2 is absolutely understandable!
This is just now changing behavior. but its logical!

Incompatibility 1:
i am afraid that this could cause real strange situations and could be hard to understand and keep in mind.

```
*** Variables ***
${one}=     key=value                 #assigning a string to var
${two}=     key2=value2
@{list}=    key=value   key2=value2   #assigning two strings to an exp list
&{dict}=    key=value   key2=value2   #assigning two strings to a DotDict


*** Test Cases ***
Test
    # case 1
    FOR    ${item}    IN    @{list}     #exp. list of two strings
        Log    ${item}    # 'key=value'
    END
    # case 2
    FOR    ${item}    IN    ${one}    ${two}    #two strings
        Log    ${item}    # 'key=value'
    END
    # case 3 OK
    FOR    ${item}    IN    &{dict}    #DotDict with two key/value pairs
        Log    ${item}    # ('key', 'value')
    END
    # case 3a OK
    FOR    ${key}   ${value}    IN    &{dict}    #DotDict with two key/value pairs
        Log    ${key} : ${value}    # 'key : value'
    END
    # case 4 OK
    FOR    ${item}    IN    &{dict}    key3=value3    #DotDict with two key/value pairs + one additional
        Log    ${item}    # ('key', 'value')
    END
    # case 5 STRANGE
    FOR    ${item}    IN    key=value   key2=value2    key3=value3    #Little strange
        Log    ${item}    # ('key', 'value')
    END
    # case 5a STRANGE
    FOR    ${key}   ${value}    IN    key=value   key2=value2    key3=value3    #Little strange
        Log    ${key} : ${value}    # 'key : value'
    END
    # case 6 OK
    FOR    ${item}    IN    key=value   key2=value2    key3    #now a list
        Log    ${item}    # 'key=value'
    END
```

Case 5 ist strange because:
Normally FOR (IN, IN ENUMERATE) loops by default are expecting lists.
Now in the case i have a multiple strings that have equal sign in them, it behaves competely different.
i think it is easy to understand, that if the first element is a &{dict} the FOR Loop switches its behaviour,
but it starts to getting more complicaten than it needs to be if you have 'key=value' as arguments.
Then imo "magic" happens


I think you can compare it with this situation:
By default for accepts lists, like in variable when you create lists.
Would also be weird if the first line would be magically a dictionary.
```
*** Variables ***
@{list}=    key=value   key2=value2   #assigning two strings to an exp list
&{dict}=    key=value   key2=value2   #assigning two strings to a DotDict
```


There is a easy work arrount to have key and value in lists by setting strings.
```
    FOR    ${key}   ${value}    IN    key  value   key2  value2    key3  value3    #Little strange
        Log    ${key} : ${value}    # 'key : value'
    END
```
So imo no need for the magic.

But thanks for the superb rest of the features ;-)

**Comment by pekkaklarck** [comment]
Thanks for comments @Snooz82. I agree it is a bit questionable to change the meaning of

    FOR    ${x}    ${y}    IN    foo=bar    xxx=yyy

and also

    FOR    ${item}    IN    foo=bar    xxx=yyy

to mean dictionary item iteration without a warning.

What we can do include:

1. Remove the support using `name=value` syntax in the dict iteration context altogether. I personally like

        FOR    ${key}   ${value}    IN    &{dict}    extra=value

   quite a bit, though, especially because these extra values can also override earlier values. Because there's that `&{dict}`, there's no backwards incompatibility problem supporting `name=value` here.

2. Support `name=value` only if there are `&{dict}` variables in values as well. That covers the above case, but disallows simple name/value iteration like this:

        FOR    ${english}    ${finnish}    IN    one=yksi    two=kaksi    three=kolme

   We do have a built-in `&{EMPTY}` variable, though, so this awkward workaround could still be used:

        FOR    ${english}    ${finnish}    IN    &{EMPTY}    one=yksi    two=kaksi    three=kolme

   As already mentioned, the existing [multi variable loop syntax](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#using-several-loop-variables) could be used here instead, but I prefer the `name=value` syntax over it especially when there are more items. For example, this one is already getting a bit complicated:

        FOR    ${english}    ${finnish}    IN    one    yksi    two    kaksi    three    kolme

3. Leave the current behavior that a single `&{dict}` variable in values or _all_ values using the `name=value` syntax initiate dict iteration. This means that usages like

       FOR    ${item}    IN    foo=bar    xxx=yyy

   will behave differently than earlier. It's unlikely such usages are that common and it's easy to escape at least one of the values like `foo\=bar`, but this is still a backwards incompatible change. The main problem I see is that in this case the for loop itself won't directly fail, loop variables will just have different values than earlier, and thus understanding the root cause may be hard.

4. Support dict iteration only if one of the values is `&{dict}`, but deprecate normal iteration over values in `name=value` format. This basically means behaving like the option 2. above in RF 3.2 (with deprecation). Then in RF 3.3 (or 4.0, whichever is first) we could move to the option 3. The big benefit of this approach over directly going to the option 3 is that deprecation makes it explicit where the problem is and it also gives time to update the data. We'd still get the "real" dict iteration in RF 3.2 and it would be still made a bit more generic later.

I'm starting to think the option 4. is the best one. It obviously requires some extra work compared to just sticking with the current behavior, but I guess less surprises to users are worth it.

**Comment by pekkaklarck** [comment]
Do you @Snooz82 have any comments about the above? The more I think about this, the better deprecating `FOR ${x} IN a=1 b=2` in RF 3.2 and making also that dict iteration in the next release feels.

**Comment by Snooz82** [comment]
i do not really get the usecase of this:
`FOR  ${x}  IN  a=1  b=2` 
And having ${x} beeing a tuple. 

I see the point in iterating over a dictionary plus some additional key=value pairs.

I would choose variant 2, because the change does not really add value, but adds complexity and backwards incompatibility.

But if you want to do it, i think Variant 4 is good.

**Comment by pekkaklarck** [comment]
Ok, let's go with the option 4. I agree `FOR ${x} IN a=1 b=2` isn't that useful but it's a special case of a lot more useful `FOR ${k} ${v} IN a=1 b=2`.

**Comment by pekkaklarck** [comment]
The above commits changed to logic to match the option 4. discussed earlier and added documentation. This issue is done.

After the latest changes this feature causes backwards incompatible issues _only_ if one of the iterated values is a `&{dict}` variable. Supporting them in this context has never been intentional and `${dict}` should be used instead. If all values are in `name=value` format, there's a deprecation warning about that syntax in the future initiating dict iteration.
