### ISSUE TITLE
Libdoc could better handle keywords deprecation info

### ISSUE THREAD

**Issue by michalanglart** [robotframework/robotframework#3498]
When keyword is deprecated it's documentation needs to start from `*DEPRECATED*`. This is useful information for IDEs because it can emit a warning for usages of such keywords or it can flag those keywords in the GUI parts which somehow displays deprecated keyword. In the end this is useful for users to be able to quickly spot which part of their codebase became deprecated thus allowing cleaning the code earlier and be ready for newer releases.

Currently this information in XML library specification file is not written anywhere - the tools need to read the documentation text to look for a `*DEPRECATED*` flag. It would be better not to read it but have such information explicitely written in the specification file for example by having `<deprecated>true</deprecated>` element under `<kw>` .

It is also worth considering having such element required (also written when `<deprecated>false</deprecated>`) because this would allow the tools to handle both ways during transition period when both formats would be supported. Without it the tool would have to look anyway into the documentation text if `*DEPRECATED*` is there because not having `<deprecated>` could mean that specification file was generated with RF <3.2 or that it was generated with 3.2+ but it is not deprecated hence no element was written.

This issue is reported after discussion here: https://github.com/robotframework/robotframework/issues/3491#issuecomment-596484623

**Comment by pekkaklarck** [comment]
Sounds good to me. Better to have this information explicitly in the Libdoc spec than require tools to parse keyword docs.

Instead of adding `<deprecated>true</deprecated>` element I'd rather add `<kw deprecated='true'`> attribute, though. Do you see any problems with that? I was thinking about adding the attribute only if the keyword is deprecated, but I see the point that the absence of the attribute could be used by tools as an indication that docs must still be parsed.

Another benefit of always having the attribute is that it makes this functionality more visible even if there weren't any deprecated keywords. This is especially important because we don't have a schema for the spec files. Perhaps it would be a good idea to create one.

**Comment by michalanglart** [comment]
> Instead of adding <deprecated>true</deprecated> element I'd rather add <kw deprecated='true'> attribute, though. Do you see any problems with that?

No, sounds fine to me. Having it in attribute would be less verbose. This flag is not a structured data which could be possibly extended in future (in that case it would be better to have element than attribute). 

Another way of avaioding problem with the tools not being sure how to read the data (look for attribute/element or parse documentation) would be to have some libspec versioning - here schema would be useful and once the schema would change the version could change and tools can adapt their behaviour depending on version of the document.

**Comment by pekkaklarck** [comment]
Cool, let's use an attribute then. I'll make it so that it's set always.

Schema versioning would be good but we'd first need a schema. Do you @michalanglart have experience creating them and would you have time to help? We have schema for output.xml under `doc/schema`  in XSD 1.0 and 1.1 formats and adding Libdoc schema in same format (one would probably be enough) would be great. Anyway, this is something that needs yet another issue.

**Comment by michalanglart** [comment]
Thanks for adding the flag!

I'm sorry for not answering your question but I somehow overlooked it in my inbox. I have rather limited experience with XSDs but if I find some time this week I could have a look.

**Comment by pekkaklarck** [comment]
A schema has been added by #3520. It marks the `deprecated` attribute optional and I'll change our implementation so that it will be written only when it is true.
