### ISSUE TITLE
Rerun functionality fails if test contains `[x]` 

### ISSUE THREAD

**Issue by thekaizokuou** [robotframework/robotframework#3500]
I found this problem when upgrade robotframework from 3.0.2 to 3.1, when I try to rerun test cases failed.
If in test case name have special character '[' or ']', script rerun cannot find test cases.

![Screen Shot 2563-03-11 at 10 15 26](https://user-images.githubusercontent.com/13466836/76379139-e14be580-6381-11ea-8f3b-a1f85e46ae3b.png)

**Comment by pekkaklarck** [comment]
Confirmed. The reason this bug occurs:

1. The rerun functionality internally uses the `--test` option to select tests to be run.
2. The `--test` option supports glob patterns.
3. RF 3.1 added support for `[seq]` patterns when using globs (#2471).

The bug has been there since the rerun functionality was introduced, but the support for the `[seq]` pattern made it worse. The best way to fix this would be changing the rerun functionality to use some other approach, but it is so much easier to escape glob meta characters in test names that I'll do that instead.

The same problem occurs also with `--rerunfailedsuites`, but suite names are very unlikely to contain glob meta characters.
