### ISSUE TITLE
Only one line of documentation in keyword is printed to report

### ISSUE THREAD

**Issue by amitdec26** [robotframework/robotframework#3511]
Only the first line of the keyword doc is shown on the logs by design, Any workaround/solution to overcome on this this issue.

Documentation part should not be limited with 1 line, Its only the place where user provide info about the keyword and let it be lengthy not be harmful.
But actually it looks good when documentation part printed in the logs which can be more than 1 line.

**Comment by pekkaklarck** [comment]
This is by design. Many keywords have really long documentation and showing them fully would increase log file size and make it harder to read. There have been requests changing this earlier (see e.g. #621 from 2010), but problems have always been considered bigger than benefits.

Notice that this functionality was recently changed a bit and now the first logical line (i.e. the first paragraph) of the documentation is included (#2491).
