### ISSUE TITLE
Consider reading PIPE buffer to avoid deadlock

### ISSUE THREAD

**Issue by xbreak** [robotframework/robotframework#3513]
When subprocess PIPE buffers run out it will usually leads to a blocked write, which deadlocks the subprocess trying to write and robot waiting for the process (if e.g. started with `Run Process`).  

To avoid this it would be nice if, while [waiting for the subprocess to complete](https://github.com/robotframework/robotframework/blob/e428e47c821808316e47cc654e3333bf96ad46c2/src/robot/libraries/Process.py#L475), robot use [`communicate()`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen.communicate) or maybe the [context manager](https://docs.python.org/3/library/subprocess.html#popen-constructor):
```py
with Popen(["ifconfig"], stdout=PIPE) as proc:
    log.write(proc.stdout.read())
```
to copy from PIPE to local buffer.

Although this is a known issue. Here's a small test case that blocks on my CentOS 7.4 (`3.10.0-957.21.3.el7.x86_64 #1 SMP Tue Jun 18 16:35:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`) using `Robot Framework 3.1.1 (Python 3.5.3 on linux)`. Results may of course vary depending on the system buffer sizes. On mine the PIPE buffer appears to be 65536 bytes.
```robot
*** Settings ***
Library  Process

*** Test Cases ***

Write Ok

        Run Process  dd   if\=/dev/zero  of\=/dev/stdout  bs\=1  count\=65536

Write Blocks

        Run Process  dd   if\=/dev/zero  of\=/dev/stdout  bs\=1  count\=65537
```

**Comment by pekkaklarck** [comment]
How could this be implemented in practice? Can you provide a pr with tests that fail without the fix and pass with it?

Notice that it's easy to avoid this problem by redirecting stdout/stderr to a file. This is also explained in the library docs.

**Comment by xbreak** [comment]
I'll see what I can do.

Yes I'm aware of the workaround.

**Comment by TheSkiGeek** [comment]
I just spent a whole bunch of time trying to figure out why my tests were flaking out when I tried to run them on a QNX embedded system, and it turned out to be this.  The platform I was trying to use this on only has a 4KB pipe buffer by default, so even a relatively small amount of output from a child process started with the default "Start Process" keyword hangs (and hangs the parent test if you "Wait For Process" without a timeout/kill).

At the very least this needs a MUCH bigger warning/explanation on it:

> By default processes are run so that their standard output and standard error streams are kept in the memory. This works fine normally, but if there is a lot of output, the output buffers may get full and the program can hang.

This makes it sound like you'll have problems if you try to write more data than will fit in memory, NOT that it will hang your process after writing somewhere between 4K-64K of data to stdout.

The problem with "just redirect it to a file and it'll be fine" is that if ANYONE writing tests forgets to do this then things randomly flake out (or, worse, hang the test suite indefinitely).  It's not really usable for multiprocess testing with this as the default behavior.  And there doesn't seem to be a great way to (for example) have "Start Process" automatically create a temporary output file for each spawned process.

**Comment by pekkaklarck** [comment]
Making the note about streams possibly getting full a bit more visible is a good idea. Could also mention that depending on the platform streams can get full _very_ easily. Do you @TheSkiGeek have a concrete idea how to do that? PR would be easiest but if you just write the updated text here I can edit the docs myself.

We have thought about making it automatic to create a temp file for output streams but so far haven't done it. The main reason is that it's not clear when those temp files should be deleted. Now when you explicitly need to tell where to write outputs (you often can use something like `${TEMPDIR}/stdout.txt`) you can then decided when to delete it with `Remove File` as well. Ideas how an automatic temporary file mechanism could work are definitely welcome.

**Comment by pekkaklarck** [comment]
Have you @xbreak had any success with automatically reading date from buffers?

**Comment by pekkaklarck** [comment]
No updates lately. Closing.
