### ISSUE TITLE
Update LibDoc XML_Schema to typed Schema 

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3525]
Hi Pekka,

i reviewed you schema file and decided to rewrite it as typed schema.
it is not as deep nested and easier to maintain.
I also added enumerations for some values.
These should be reviewed.

your original schema had some bugs.

- `agruments` tags could only have one `arg` tag
- `tags` tags could only have one `tag` tag
-  `init` was not supported

i also added two schema files.
one for Libdocs until 3.1.2 (libdoc.01.xsd) and one for 3.2 (libdoc.02.xsd)

please check the enums and if i missed anything.

i was not sure if `init` could also have a `source` like you defined in keywords or only a `lineno`

Cheers

**Comment by Snooz82** [comment]
This should fix issues with #3523

**Comment by pekkaklarck** [comment]
Great that we have schema expert here! My knowledge about them is somewhat limited and I just created the original schema with some online tool and edited it. Due to my limited knowledge I'm not going to review your versions and just trust they are good (and then blame you if someone reports bugs later :smiling_imp:).

Good catches with those bugs. Also `init` can have `source`. The code writing the spec files is here: https://github.com/robotframework/robotframework/blob/master/src/robot/libdocpkg/xmlwriter.py

I'll re-open #3523 and close this one. Could you @Snooz82 create a PR with your updates?
