### ISSUE TITLE
`Log Variables` fails is variable value is iterable but iteration fails

### ISSUE THREAD

**Issue by boakley** [robotframework/robotframework#3540]
Under a specific scenario, the built-in keyword `log_variables` is crashing with the error `AttributeError: 'int' object has no attribute 'replace'`.

I  haven't completely nailed down the cause of the crash. I can reproduce it by creating a library that uses the [Faker library](https://faker.readthedocs.io/en/master/), however. I just haven't figured out what it is about that library that is causing the problem. I've tried with some very simple objects in place of `faker.Faker()` and am not seeing the problem. 

Start with this keyword library (keywords.py):

```
from robot.libraries.BuiltIn import BuiltIn
import faker
class keywords:
    def __init__(self):
        self._faker = faker.Faker()
        BuiltIn().set_global_variable("${faker}", self._faker)
```
 When I run this test case, I get the `AttributeError`:

```
*** Settings ***
Library  keywords.py

*** Test cases ***
Example
    log variables

```

Oddly, if I set a breakpoint inside the `log_variables` keyword and print out the list of variables, the internal name of the variable is `@{faker}` rather than `${faker}`. So, even though I explicitly set the variable name as `${faker}`, it's getting stored as `@{faker}`, and that seems to break `log variables`. If I manually reset the name to `${faker}`, `log_variables` is able to continue without error.

So, it seems that the root cause is that robot renames my variable to an array for some reason.

**Comment by pekkaklarck** [comment]
Do you get a traceback from the error?

**Comment by pekkaklarck** [comment]
Ok, I was able to reproduce the error and for most parts understand why it occurs. I don't have time to explain that right now. The problem can be pretty easily and safely fixed, and I think we can include the fix to RF 3.2 and don't necessarily even need a new release candidate only because of this issue.

**Comment by pekkaklarck** [comment]
Here's the explanation why this happens:

1. Internally Robot stores all variables without `${}`, `@{}` or `&{}` decoration. In this case there's thus just variable `faker` with a `Faker` instance as its value.

2. `BuiltIn.log_variables` internally uses `BuiltIn.get_variables` and asks it to return variables so that names contain the decoration. As you can see [from the code](https://github.com/robotframework/robotframework/blob/master/src/robot/variables/store.py#L112), the decoreaton is added using this logic:

    - If the variable is dict-like, it gets `&{}` decoration.
    - If the variable is list-like, it gets `@{}`.
    - Otherwise it gets `${}`.

3. Checking is something list-like is implemented ([see code](https://github.com/robotframework/robotframework/blob/master/src/robot/variables/store.py#L112)) by running `iter(item)` and checking does it raise an exception. There are some special cases like strings, though.

4. Somewhat surprisingly, `iter(Faker())` doesn't raise an exception but instead returns an iterator. The reason this happens is that `Faker` has `__getitem__` and due to Python's duck-typing nature that alone is enough. Python thinks `Faker` instances can be iterated like lists by using indices. That's not the case, though, and trying to do that causes an exception. This can be easily demonstrated by running `list(Faker())` which causes this familiar error:

    ```
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/.../site-packages/faker/proxy.py", line 59, in __getitem__
        return self._factory_map[locale.replace('-', '_')]
    AttributeError: 'int' object has no attribute 'replace'
    ```

**Comment by pekkaklarck** [comment]
So, how can this be fixed? There are multiple solutions:

1. In my opinion `Faker` itself should actually be fixed because `list(Faker())` failing with this strange error isn't good. It ought to be enough to add this code there:

    ```python
    def __iter__(self):
        raise TypeError('%s object is not iterable' % type(self))
    ```

    We cannot really expect this fix to happen (someone needed to submit an issue first) and even if it did, we needed to handle old Faker versions and all other objects that behave the same way.

2. We could try enhancing our `is_list_like`. Unfortunately at least I'm not familiar with any better way to check is an object iterable than using `iter()`, and changing this logic could also affect lot of other code and I'm not sure is that a good idea anymore in the release candidate phase. This isn't the first time objects with only `__getitem__` being considered iterable causes problems for us, so at least in the longer run this would be the best fix.

3. We could safely special case `Faker` objects like we special case e.g. strings, but that would require adding Faker imports wrapped with `try/except ImportError` to our code base. I don't think that's a good idea because this would only fix it with Faker and such imports always slow down starting execution a bit.

4. We could simply enhance `BuiltIn.log_variables` so that if logging a variable that has been considered list-like fails, we just log it as a scalar. This would be easy and 100% safe.

**Comment by pekkaklarck** [comment]
I studied detecting is an object iterable a bit more. As I remembered, the collective wisdom (see e.g. [this StackOverflow question](https://stackoverflow.com/questions/1952464/in-python-how-do-i-determine-if-an-object-is-iterable)) is to use something like this:

```python
def is_iterable(thing):
    try:
        iter(thing)
     except TypeError:
        return False
    else:
        return True
```

The above is basically what we already use, but it has the problem that objects that only have `__getitem__` are considered iterable. In the answers to the aforementioned SO question that behavior was considered good, but I start to disagree. It could be that there used to be more iterable objects in Python that only had `__getitem__` and old Python version didn't have `collections.abc.Iterable` either.

Based on my testing with Python 2.7 and 3.4+ `isinstance(thing, Iterable)` seems to work just fine. It works with lists, dicts, etc. and also with strings. The only differences with it compared to using `iter(thing)` like in the example above I noticed are:

- Objects that have `__iter__` that doesn't return a valid iterator are considered iterables by `isinstance()` but not if we use `iter()`. The former apparently just checks that `__iter__` exists while the latter actually runs it and validates result. I don't think this really matters as the code clearly is buggy.

- With Python 2 `UserDict` is not considered `Iterable` but that's easy to special case by using `isinstance(thing, (Iterable, UserDict))`.

**Comment by pekkaklarck** [comment]
I really wanted to fix this by changing our `is_list_like` as discussed above, but after careful consideration decided not to do it. The main reasons are:

- It would be a very subtle change possibly causing problems with existing code. It would require rc2 and would still be somewhat risky. Better to leave it for next RF major version.
- It would still be possible that `Log Variables` fails if there's a custom sequence that fails during iteration.

I still think the originally reported issue with `Log Variables` is worth fixing and fixing only that keyword is safe. I'll do that and won't create rc2 unless other problems are reported.

**Comment by boakley** [comment]
I agree - `log variables` just needs to catch errors and log the repr or
string value.

**Comment by pekkaklarck** [comment]
I added a new answer to the StackOverflow question about detecting iterable objects I mentioned earlier. My recommendation is to use `isinstance()`, not `iter()`:
https://stackoverflow.com/questions/1952464/in-python-how-do-i-determine-if-an-object-is-iterable/61139278#61139278

Need to still open an issue about changing our code in RF 3.3 or 4.0, whichever comes first. The separete fix to `Log Variables` I already committed above is valid even after that change.
