### ISSUE TITLE
ImportError: cannot import name 'TestDataDirectory' from 'robot.api'

### ISSUE THREAD

**Issue by arghajit** [robotframework/robotframework#3550]
Using `robotframework-3.2rc1`

While running tests from a bash script wrapper following error appears. 
```
from robot.api import TestDataDirectory
ImportError: cannot import name 'TestDataDirectory' from 'robot.api' 
```

Fix: Downgrading to last stable version `3.1.2` fixed it.

**Comment by pekkaklarck** [comment]
The reason is that RF 3.2 has new and totally rewritten test data parser (#3076) and the whole parsing API has changed. I noticed this isn't explicitly mentioned in [RF 3.2 rc 1 release notes](https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.2rc1.rst) but I'll write something there soon. 

Good news is that the new parsing API is a lot better than the old one. I recommend studying the [new API docs](https://robot-framework.readthedocs.io/en/master/autodoc/robot.parsing.html#module-robot.parsing) and starting to think how/when to migrate.

**Comment by pekkaklarck** [comment]
This is now explicitly mentioned in RF 3.2 rc 1 release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-3.2rc1.rst#parsing-apis-have-been-rewritten

**Comment by arghajit** [comment]
Thanks @pekkaklarck . This helps.
