### ISSUE TITLE
Running Robot Framework in a web browser

### ISSUE THREAD

**Issue by mardukbp** [robotframework/robotframework#3563]
[Mozilla Pyodide](https://github.com/iodide-project/pyodide) compiles CPython to WebAssembly, thus allowing to run any Python module in a web browser and also enables seamless interaction with JavaScript. For example, here is a small test with Robot Framework (you can try it pasting the code below into https://alpha.iodide.io/notebooks/300/):

```
%% js

var message = "Skynet is online";

%% py

import micropip
micropip.install('robotframework')

%% py

from js import message
from robot.api import TestSuite

suite = TestSuite('Activate Skynet')
suite.resource.imports.library('BuiltIn')

test = suite.tests.create('Should Activate Skynet')
test.keywords.create('Log to Console', args=[message])

result = suite.run()
result.return_code  # 0
```

As I see it, this opens the possibility to interactively design test suites for web applications. That way the Selenium Library would no longer need the WebDriver server for communicating with web browsers. Instead one could use the JS implementation of the WebDriver specification from WebDriverIO.

I hope this idea attracts some interest from the dev team.

**Comment by pekkaklarck** [comment]
This looks super interesting and I like WASM in general! If you have ideas/demos/whatever to share with others, I recommend you start discussion on our Slack, mailing list, or other such forum listed at robotframework.org.

I'll close this issue because this issue tracker is for Robot Framework core, though, and this kind of integration would need a separate project. If some changes would be needed to RF to support this kind of usage better, separate more concrete issues can be submitted.
