### ISSUE TITLE
Error generating documentation for decorated keyword methods on python 2.7

### ISSUE THREAD

**Issue by JockeJarre** [robotframework/robotframework#3587]
When you decorate your keyword functions using the [decorator module](https://github.com/micheles/decorator) you get errors while generating the documentation.

```
from __future__ import print_function
from decorator import decorator

@decorator
def failingDecorator(fn, *args, **kwargs):
    return fn(*args, **kwargs)

def workingDecorator(fn):
    def decorator_inner(*args, **kwargs):
        return fn(*args, **kwargs)

    return decorator_inner


class KeywordLibrary(object):

    @failingDecorator
    def MyDecoratedFunction(self, firstParameter, secondParameter):
        print("%s called"%(__name__) )

    @workingDecorator
    def MyFunction(self, firstParameter, secondParameter):
        print("%s called"%(__name__) )
```

When you run the documentation generation on the command line:
```
C:\temp\DecoratorTest>python -m robot.libdoc KeywordLibrary KeywordLibrary.html
Building library 'KeywordLibrary' failed: AttributeError: 'NoneType' object has no attribute 'decode'

Try --help for usage information.
```

The reason for using [decorator module](https://github.com/micheles/decorator) is that it correctly keeps your function signature for the documentation.

An different example using [decorator module](https://github.com/micheles/decorator) VS standard python decorator:

Keyword | Arguments | Documentation
-- | -- | --
My Decorated Function | firstParameter, secondParameter |  Here the function signature is kept |
My Function | *args, **kwargs |  Here we see the signature of the decorator |

**Comment by JockeJarre** [comment]
The solution I found to be simple is to modify “robot\running\handlers.py”:

```
class _PythonHandler(_RunnableHandler):
    ...
    @property
    def source(self):
        handler = self.current_handler()
        try:
            return normpath(inspect.getsourcefile(unwrap(handler)) or self.library.source) # also handle None for decorator.decorator decorated function/method/keywords
        except TypeError:
            return self.library.source
    ...
```

**Comment by pekkaklarck** [comment]
Which RF version are you using? If not RF 3.2.1 can you test with that?

**Comment by JockeJarre** [comment]
Yes RF 3.2.1 and python 2.7

**Comment by pekkaklarck** [comment]
Ok. This is definitely something we can fix in RF 3.2.2. It's currently scheduled for early July and I don't consider this so severe that it needed to be released earlier. Hopefully you can generate docs using Python 3 until that.

**Comment by JockeJarre** [comment]
yes of course!

**Comment by pekkaklarck** [comment]
I studied the [source code](https://github.com/python/cpython/blob/3.8/Lib/inspect.py#L692) of [inspect.getsourcefile](https://docs.python.org/3/library/inspect.html#inspect.getsourcefile) and sure enough it can return `None`. Apparently that happens if the path got from [inspect.getfile](https://docs.python.org/3/library/inspect.html#inspect.getfile) cannot mapped to an actual source file but unfortunately this behavior isn't documented.

Luckily fixing this is easy. We have three alternatives:
- Just return the original source of the library if `inspect.getsourcefile` returns `None`.
- Use `inspect.getfile` if `inspect.getsourcefile` returns `None`.
- Use [inspect.getabsfile](https://github.com/python/cpython/blob/3.8/Lib/inspect.py#L714) that does the above automatically. Oddly enough that function isn't included in [inspect module documentation](https://docs.python.org/3/library/inspect.html) so using it feels a bit risky.

I decided to go with the first alternative. It's a bit easier than the second and safer than the third. If the keyword source points to a file that `inspect.getsourcefile` cannot handle, it's probably best to return the original library source anyway.

**Comment by pekkaklarck** [comment]
Notice also that nowadays you don't need to use the `decorator` module anymore if you want to preserve arguments of a decorated keyword. Assuming you use Python 3 (as you should) you can just use the standard [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps) instead. Support for "unwrapping" such keywords was implemented in RF 3.2 (#3027) and a related regression fixed in RF 3.2.1 (#3561).

**Comment by pekkaklarck** [comment]
Decided to still check what `inspect.getfile` returns with these decorated keywords when `inspect.getsourcefile` returns `None`. I got `</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-2>` which obviously isn't the correct source of the keyword. The decision to return the original library source in this case is definitely the right one.

**Comment by JockeJarre** [comment]
Just FYI, tested your change here, and it works well! Thanks

**Comment by JockeJarre** [comment]
> Decided to still check what `inspect.getfile` returns with these decorated keywords when `inspect.getsourcefile` returns `None`. I got `</usr/local/lib/python2.7/dist-packages/decorator.pyc:decorator-gen-2>` which obviously isn't the correct source of the keyword. The decision to return the original library source in this case is definitely the right one.

Just FYI, tested your change with our project, and it works well! Thanks
