### ISSUE TITLE
order of searching library is incorrect in this case

### ISSUE THREAD

**Issue by jcyrss** [robotframework/robotframework#3590]
say we have test cases folder structure as the following

```
cases
    │- delclass.py
    │- delclass.robot
    │
    └─function_1
            delclass.py
            delclass.robot
```

the content of cases/function_1/delclass.robot is as following

```
*** Settings ***

Library  delclass.py   WITH NAME  F    

Library  delclass.c1   WITH NAME  c1


*** Test Cases ***

tc000001

  c1.teststeps
```

the weired thing is, during robot executing, it will call `c1.teststeps` in delclass.py of `uplevel folder` instead of `current folder`.

![image](https://user-images.githubusercontent.com/10496014/83746110-305b9b00-a691-11ea-97ac-95a7447efb77.png)

That behavior seems contradict with user guide.

![image](https://user-images.githubusercontent.com/10496014/83746531-cabbde80-a691-11ea-9eaf-0ad6f803ecb3.png)

The testcases file is attched as following, just unzip it and run `robot cases`, the issues will be reproduced.

[cases.zip](https://github.com/robotframework/robotframework/files/4729283/cases.zip)

**Comment by pekkaklarck** [comment]
When you use `c1.teststeps`, you use the library you import like `Library  delclass.c1   WITH NAME  c1`, right? That library is imported from PYTHONPATH and what gets imported depends on how it is set. The easiest solution to avoid problems like this is to have unique library names.

**Comment by jcyrss** [comment]
We didn't set environment var PYTHONPATH.

what confused me is why RF use the library in parent folder, instead of the library in current folder of the test file

**Comment by pekkaklarck** [comment]
When you import a library by using its name, not by path, RF just passes the name to Python's import machinery. Where it imports the module depends on `sys.path` which you can configure by using the PYTHONPATH environment variable.

**Comment by jcyrss** [comment]
why the up level folder of current executing robot file is in sys.path?

**Comment by pekkaklarck** [comment]
Another thing affecting this is `sys.modules`. When importing `delclass.py` for the first time, the `delclass` module is added to `sys.modules` and the second `delclass.c1` most likely gets the `delclass` module from there. We potentially could change our import machinery to remove modules from `sys.modules`, but that's not too easy because imported modules may import other modules that all go to `sys.modules` but we don't know about them. The easiest and best solution is not using same library name in multiple places.
