### ISSUE TITLE
Performance of Keywords

### ISSUE THREAD

**Issue by gitCWS** [robotframework/robotframework#3601]
Hello,
is there a solution to improve performance when using resource files?
When I execute a keyword using a resource, it takes about twice or more time to execute as I execute it directly in a Python library.
Example:
Run Keyword From Library
```
    FOR ${range} IN RANGE 10000
        Lib Keyword  # Running  "BuiltIn().set_suite_variable" in Library file.
    END
```
Execution time for "Run Keyword From Library": 0.39 sec
Run Keyword From Resource
```
   FOR ${range} IN RANGE 10000
       resource keyword  # Keyword "Set Suite Variable" in Resource File.
   END
```
Execution Time for "Run Keyword From Ressource": 9.3831828 sec
And Last...
Run Keyword From Library that includes Keywords from Resource
```
   FOR ${range} IN RANGE 10000
       Lib keyword From Resource 
   END
```
Execution Time for "Run Keyword From Ressource": 23 sec

All test cases execute the keyword "Set Suite Variable" 10000 times.

**Comment by gitCWS** [comment]
@pekkaklarck have you an idea, how I can speed up the execution in ressource files?

**Comment by pekkaklarck** [comment]
Library keywords are faster to execute than Robot's user keywords for various reasons:

- Library keywords are run directly on Python while user keywords have overhead caused by the framework.
- Each keyword call is logged to output.xml file and resulting disk IO can slow execution. This is especially true when running several keywords and even more so if you have nested keywords.

We've been running performance tests for Robot now and then and have been trying to make everything as fast as possible without making the code (too much) harder to maintain. I did performance tuning the last time pretty recently while finalizing RF 3.2. I'm sure there are still ways to enhance the execution speed, but at least I don't have time or much interest to look at it in the foreseeable future. If someone else is willing to do profiling and propose changes, that would be great.

Although execution speed could be enhanced, it will remain a fact that library keywords running directly on Python will be faster than user keywords. If speed is important, moving logic to libraries is thus a very good idea. If Python speed isn't fast enough, you can then decide to go from Python to C.

**Comment by gitCWS** [comment]
Thanks for the answer.
We will try to run library keywords directly in Python.
