### ISSUE TITLE
Keyword Return Value in Rebot Logs

### ISSUE THREAD

**Issue by willemvanoort** [robotframework/robotframework#3613]
Currently, the return value of a keyword is not logged by default. However, for some use cases we have come across this would be a quality improvement. For our needs, we have applied some changes to Robot to enable return value logging and through this issue I wanted to gauge whether this would be an extension that could benefit Robot as a whole.

In short, the changes will have the following result. In the first image, the changes are not applied. In the second image, the changes are applied and as can be seen, the return value of the keyword is logged.

Before changes:
![Before changes](https://user-images.githubusercontent.com/5758725/87285584-f4b9b980-c4f7-11ea-9631-116a59d5c470.jpg)

After changes:
![After changes](https://user-images.githubusercontent.com/5758725/87285615-fe432180-c4f7-11ea-88e8-e93a185458e7.jpg)

An assign statement (e.g. `${variable_name}= | ....`) does log the return value as INFO. However, the return value of a keyword can in other cases be relevant as well, we found. For instance, in the example above, `Controller is running` is invoked by calling `BuildIn().run_keyword(...)`, and its result is used in a Python if-statement. Hence, the returned value is not logged automatically. Another use case would be when keywords are used as an argument (this is not default robot yet (https://github.com/robotframework/robotframework/issues/3187)), this addition would allow you to see the actual parameter values.

We have a first working implementation of this addition. Before continuing I would like to have some feedback on the idea.

**Comment by yo-ga** [comment]
I remember that the return value shows when the log level is TRACE.

**Comment by willemvanoort** [comment]
Yes I was aware, however, the suggestion I made here was to give the return value a more prominent place in the logs (see image 'After changes' in original post). 

Would there be interest in such a (possibly optional) feature?

**Comment by pekkaklarck** [comment]
I don't think this is a good idea. I'm doubt there would be that many benefits but there would be problems.

Why I think there aren't that many benefits:

- I doubt wanting to see the return value is such a common need in general.
- If keyword wants some information to be shown in logs, it can easily log it.
- If you cannot control the behavior of the keyword (i.e. cannot add logging), you can assign the return value to a variable and then log it yourself. If the return value isn't long, it's actually already automatically logged in this case.

What problems there would be:

- Logging values like this clutters the log file. This is especially true if you aren't interested in the return value in the first place.
- Return values can be really, really big (e.g. contents of a huge binary file) meaning automatically logging them would make log files impossible to open.

This certainly couldn't be the default behavior. We could consider making it configurable, but a single command line option changing the behavior would cause all the same problems I mentioned above. Controlling this with individual keywords would avoid such problems, but because keywords can already log values there wouldn't be concrete benefits.

Do you @willemvanoort have counter arguments for my concerns listed above?

**Comment by pekkaklarck** [comment]
No comments since August. Closing.
