### ISSUE TITLE
Test filtering (--test) does not work as expected when using "test" search argument along with wildcards

### ISSUE THREAD

**Issue by eduardhc** [robotframework/robotframework#3614]
Just reporting a weird issue: when using "--test" argument with RF in order to filter the test sequences to execute, just realized that if a search argument such as "test*" is used (which should execute only those test sequences whose name starts with "test"), RF actually executes ALL the tests in the file, no matter how they are named. 

However, this behaviour seems to occur only when specifically using "test", along with a wildcard as the search string, as AFAIK in any other case the filtering behaves as expected.

Included as an attachment a very simple example RF test file, containing two test cases, named "case_1" and "case_2" (which actually do nothing). The following situations occur:
`robot --test "case_1" test_filter.robot`
Executes only "case_1" test - **OK**
`robot --test "case*" test_filter.robot`
Executes both "case_1" and "case_2" - **OK**
`robot --test "test" test_filter.robot`
Gives an error, as no test case is named "test" - **OK**
`robot --test "test*" test_filter.robot`
Executes both "case_1" and "case_2" tests, even if none of them has "test" in its name - **WRONG**

[test_filter.robot.txt](https://github.com/robotframework/robotframework/files/4918199/test_filter.robot.txt)

Tested on Windows 10, using RF v3.2.1 on Python 3.7.3 (win32 edition).

**Comment by pekkaklarck** [comment]
The reason is that `--test` matches both using tests real name, "case_1" or "case_2" in your case, and also using test's so called long name that contains also test suite name in format like "Suite Name.Test Name". In your case these long names are "test_filter.case_1" and "test_filter.case_2" and thus running `--test test*` matches them both. You can avoid this by adding the suite name to the call yourself like `--test test_filter.test*` and depending on the suite structure using just `--test *.test*` can work as well.

**Comment by eduardhc** [comment]
Understood, thank you!
