### ISSUE TITLE
Libdoc split arguments over multiple lines

### ISSUE THREAD

**Issue by xylix** [robotframework/robotframework#3639]
This issue was created based on discussion at https://github.com/robotframework/robotframework/issues/3586 and a proposed modification at https://github.com/robotframework/robotframework/pull/3638 

We (team of Robot Framework Browser library) thought that significant readability gains in libdoc could be achieved with some basic templating changes to the libdoc output.

One thing that was requested by @pekkaklarck was that before we go forward with merging this we should generate some library docs with the changed HTML and see how it looks, including the Robot builtin libraries and SeleniumLibrary. I generated SL and builtin docs, see attached zip for the HTML files. I personally think they look most of the time a bit better and sometimes significantly better. @aaltat @Snooz82 please also see the attached HTML files and give your opinion.

[multilined_sl_and_builtin_docs.zip](https://github.com/robotframework/robotframework/files/5116241/multilined_sl_and_builtin_docs.zip)

**Comment by pekkaklarck** [comment]
I took a brief look on some of the docs and was surprised how big improvement this is. Readability is improved and the argument list doesn't take any more vertical space when keywords have documentation spanning multiple lines. Probably docs end up using less space because the argument column is narrower.

Situation could be a bit different if a keyword had a very short documentation or no documentation at all, but at least with all bigger libraries that's not the case. I'll merge #3638 because enhancements in the common case are so big. That will also make it easier to test this with other libs.

**Comment by pekkaklarck** [comment]
Tested how arguments look with this enhancement when keyword has no documentation and liked also these results. Trying to somehow configure this isn't worth the effort in my opinion. We can, however, return to this after RF 3.2.2 once we see the new style live more widely.

**Comment by pekkaklarck** [comment]
While testing this, noticed also the following related topics we should discuss. If we decide to do something to them, that can be done as part of this issue.

- Should tags be split like arguments? In my opinion that would make sense but what do others think? Change would be trivial.

- Should we fine-tune column widths in the keyword table? After this change the argument column requires less horizontal space and can get even too narrow. While playing with styles a bit, I noticed these current styles don't have any effect:

    ```css
    .kw, .args, .tags {
        min-width: 100px;
        max-width: 20%;
    }
    ```

    I changed the above and liked the results:
    ```css
    .kw, .tags {
        width: 10%;
    }
    .args {
        width: 20%;
    }
    .doc {
        width: 60%;
    }
    ```

    If there are no tags, widths don't add up to 100%. We either can let browsers handle that or set widths dynamically. Someone knowing CSS and especially styling tables better than I can probably come up with something better.

**Comment by pekkaklarck** [comment]
Ping @Snooz82 and @aaltat.

**Comment by aaltat** [comment]
I don't have a clear opinion, but I think consistency would be good.

**Comment by Snooz82** [comment]
@pekkaklarck 

Yes the tags should be in multiple lines as well.
i didn’t realize that they are not at the moment because of the narrow width the most are with break lines.

see: https://marketsquare.github.io/robotframework-browser/Browser.html

Browser has tags and the PR of Kerkko is applied, but here and there you can see a tag that is not in a new line.

@mkorpela Do you have interest to do a bit of fancy CSS to Libdoc? Pekka asked for it ;-)

**Comment by pekkaklarck** [comment]
Here's an example showing how splitting arguments to own rows works well even in a pathological case with many arguments and no documentation. It also shows that tags should be split too.

![enums](https://user-images.githubusercontent.com/114985/91153990-96bcec00-e6c9-11ea-925b-03a36f3e3de0.png)

The example has the column width tweaks mentioned above and also contains enum members as discussed in #3637.

**Comment by pekkaklarck** [comment]
52f8dfe8caf9d9ffe554d9797cef6fc9e288de84 split also tags to multiple lines. Column widths were changed in 4e0cee13cd3b6bdc66790a813f06c99610bc2078 and can be fine-tuned still later if needed.
