### ISSUE TITLE
Time out setting is useless

### ISSUE THREAD

**Issue by ken-qi** [robotframework/robotframework#3646]
When i execute some cases, some keywords always hangs(no failed, no message, nothing to do until stop it manually) due to some reason (I don't would like clarify it at here), now i just want to set a time out when a keyword hangs more than 2 minutes, but it doesn't work. i check some article. The hangs reason is the keyword is still executing, but the time out seems like only useful between with keywords. Not sure if have some background to set some setting when the test case run more than 20 minutes than failed it, run next case.

**Comment by ken-qi** [comment]
My Robot framework version is 3.1.2 and Python is 3.7.3

**Comment by pekkaklarck** [comment]
Robot's timeouts typically can stop keywords but unfortunately that's not always possible. This depends on the executed code and to some extend the operating system. Because you didn't tell anything more about your scenario, it's impossible to know why timeouts don't work in your case. There are two ways to get something done to this issue:

1. You create a simple example demonstrating the problem that we can use to debug the problem.
2. You study the problem yourself and propose a solution as PR or otherwise.

**Comment by ken-qi** [comment]
Hi pekkaklarck,
Thanks for your reply. I can explain some more detail.
The scenarios is a combo box, when i select a value from combo box, a popup dialog display, then i would like to click Yes button in the dialog, my code as below:
	Select From Combo Box    identifier    test    
	Select Dialog    Confirm dialog
	Push Button    Yes
when i run it, the Robot hang on step 1, No error, no message, just hang on forever. 
But if i use "Run Keyword In Separate Thread    Select From Combo Box    identifier    test   " it could be passed.  

Now my confuse is i don't know when such situation can be appear, so i want to set a Timeout, if it is hang on, the Robot can stop this case and run the next case.

**Comment by pekkaklarck** [comment]
As I already wrote, there are cases where Robot's timeouts cannot stop keyword execution. It's pretty much impossible for anyone but you and others in your team/project to investigate why that happens in this particular case and could something be done. It's great that you at least have a workaround and can you `Run Keyword In Separate Thread`.

**Comment by pekkaklarck** [comment]
Closing due to lack of information.
