### ISSUE TITLE
Enhance error reporting when using markers like `FOR` in wrong case like `for`

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/robotframework#3648]
When using for loop with incorrect lower case:
```
for    ${i}    IN RANGE    10
        log    ${i}
end
```

the output will be:

`Variable '${i}' not found.`

Expected error msg: `'for' is a reserved keyword.` or `No keyword with name 'for' found.`

**Comment by pekkaklarck** [comment]
We have a keyword `For` that is used if you don't use exactly `FOR` (or old `:FOR`)  to start the for loop. When you use it, you should get the `'For' is a reserved keyword.` message you expected. The reason that doesn't happen is that in this case Robot tries to evaluate arguments passed to the keyword and `${i}` used in arguments doesn't exist. This ought to be easy to fix be special casing these `Reserved` keywords so that their arguments are never evaluated. It would then resolve the same problem with forthcoming `IF/ELSE` syntax as well.

**Comment by pekkaklarck** [comment]
There are actually two ways how to enhance error reporting:

1. Report the error regardless are variables used or not. That's what this issue was about initially.

2. Instruct user to use e.g. `FOR` instead `for`. We actually already do that with `ELSE` and `ELSE IF` that can be currently used as markers with `Run Keyword If` but we should do that all markers we currently support as well as with `IF` that will be supported soon.
