### ISSUE TITLE
Improving libdoc HTML output for mobile

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3656]
Current libdoc html output does not work very well with mobile.
Here is an example from [Robot Framework Browser library docs](https://marketsquare.github.io/robotframework-browser/Browser.html).

I propose the following changes: [proof of concept docs](https://resonant-rake.surge.sh/)

1. Fitting page width with the content
2. Adding horizontal scrolls to code examples, to prevent them from growing width of the page
3. Replacing keywords table with bordered boxes.

The reasoning behind the third change is that information in the current table layout tends to go to right side of the table. This makes most of the page uninformative - most focus should be on the Documentation part. Also headers of columns are hidden when scrolling.
<img width="800" alt="Screenshot 2020-09-09 at 9 54 07" src="https://user-images.githubusercontent.com/136885/92564794-6a38d080-f282-11ea-9982-bb9934911c7e.png">

Here is the example in proposed format:
<img width="802" alt="Screenshot 2020-09-09 at 9 58 59" src="https://user-images.githubusercontent.com/136885/92565310-1b3f6b00-f283-11ea-9972-0fcda433c202.png">

**Comment by pekkaklarck** [comment]
I'm in general in favor of enhancing all out HTML outputs on mobile and otherwise. The proposed changes themselves sound pretty good too, although I'm not so certain about scrollbars. Do you propose doing these changes so that they affect all usages or only mobile or otherwise narrow layout? Do you have examples showing the differences?

A problem with this issue is that there are many different enhancements and there could be even more. It could be that we only want to include some of the enhancements and thus examples should also show only one change (unless changes are highly related). Especially with bigger changes we could also wait until we, hopefully, soon see face-to-face.

**Comment by mkorpela** [comment]
Sorry I meant Horizontal and not Vertical..

Anyway they are present in the example:
![scrollbar](https://user-images.githubusercontent.com/136885/92601083-0e3b6f80-f2b5-11ea-884f-03a05956fc28.gif)

**Comment by mkorpela** [comment]
Pull request https://github.com/robotframework/robotframework/pull/3675

**Comment by boakley** [comment]
It would be nice if the css was all in a file that could be swapped out with a command-line option. For example, `robot -m libdoc --css my-libdoc-styles.css`This might make it easier for the community to contribute other styles, and make it easier for larger organizations to customize the look of their keyword documentation.

**Comment by mkorpela** [comment]
@boakley css controls now most of the look and feel of an html page. This means that it mostly builts what you see where as html only has some nodes of data.
Most of the work I have done so far is css.
I think we need to think carefully how this custom styling should actually happen. For instance overwriting colors might be easy or using company font or adding logo, but changing menu locations or link or list styles globally might have unwanted consequences.

**Comment by pekkaklarck** [comment]
Injecting css would be a very powerful feature and something I've been thinking would be a good idea also with logs and reports. Instead of replacing the existing css fully, it might be better to add new styles after it so that there's no need to recreate all styles but anything can be overwritten.

The main problem with this is that it would make the currently internal Libdoc/log/report HTML code part of the public API. Possible changes to HTML structure, ids, classes, etc. could break custom css badly.

Although that's a pretty big problem, the feature would be so powerful that I believe it would be worth it. We basically needed to decide and document which parts of the HTML code are concidered stable and in general avoid breaking changes outside major versions where they needed to be explicitly documented.

This enhancement would need its own issue where to discuss the design more. It ought to be pretty easy to implement and thus could be a possible addition to RF 4 scope.

**Comment by mkorpela** [comment]
I'll close this issue in favor of a better one related to LibDoc output html improvements

**Comment by stdedos** [comment]
Um, do you have such ticket? I cannot find anything with https://github.com/robotframework/robotframework/issues?q=LibDoc+output+html+improvements

**Comment by pekkaklarck** [comment]
I think it's #3687.
