### ISSUE TITLE
Is there any implementation to run  parallelly two or multiple independent keywords in a single test case in robot framework?

### ISSUE THREAD

**Issue by AlldreenDev** [robotframework/robotframework#3658]

**Comment by pekkaklarck** [comment]
Unfortunately not. This is a recognized missing feature, see #1791 and #1792, but due to the shared internal state implementing it isn't possible at the moment. Hopefully internal changes in RF 4.0 will make that easier in the future, but I cannot give any estimation when this feature would be supported. At the moment the way to run keywords in parallel is handling that on library level.

**Comment by pekkaklarck** [comment]
Notice also that this issue tracker is for bug reports and concrete enhancement requests. Questions should be sent to other forums such as mailing lists or Slack.

**Comment by rajeshkumartv** [comment]
We use Robotframework in my organization and we need support to run ROBOT keywords to run in parallel with multithreading or any other way in a single test case.
