### ISSUE TITLE
Include exception type in error message

### ISSUE THREAD

**Issue by adiralashiva8** [robotframework/robotframework#3674]
**Why**: In our organization we are trying to automate failure analysis, it will be like based on few keys in error message will mark test case as Automation or Application Issue.

Example: Let us assume test case consist keyword `Should Be True "Demo" != "Demo1"` and it got failed, we will get error message like `"Demo" != "Demo1"`

In above error message **=!** is my key and I update testcase analysis comment that its application issue since validation got failed.

Accuracy of this approach is around or less than 50% and we want to improve accuracy of automation analysis.

**What**: If robotframework provide exception type as prefix in error message this helps us to understand more about issue and mark test case accordingly.

Example:

1. Robotframework: If any `Should *` keyword got failed error message should be like `ValidationException: <actual error>`
2. Selenium: If any `Wait *` keyword got failed error message should be `ElementException: <actual selenium throwed exception & error>`

We believe this approach improve our auto failure analysis accuracy upto 80% or more

**Comment by pekkaklarck** [comment]
When Robot constructs an error message based on an exception from a keyword, it omits the exception type with generic errors like `AssertionError` and `RuntimeError` to make the message less technical. It is, however, included with non-generic errors like `ValueError`. It would be easy to change the logic so that the type is included always, but I don't see how `AssertionError: "Demo" != "Demo1"` would be better than `"Demo" != "Demo1"` or how it would help with failure analysis. If you are really interested in the the exception type, it is also visible in the traceback that's logged on the DEBUG level.

A part of this proposal was that Robot and SeleniumLibrary would use different exception types. That sounds like a strange requirement to me in general, and we absolutely don't want to coordinate what exceptions various libraries would use.

All the above said, I do agree that `"Demo" != "Demo1"` isn't a great error message, but there's not much `Should Be Equal` can do to enhance it if you just pass it two values. That's the primary reason this keyword, and many other `Should *` keyword, makes it possible to configure the error message. If you use it like
```
Should Be Equal    Demo    Demo1    msg=ValidationError
```
the error you get is `ValidationError: Demo != Demo1` and if you use
```
Should Be Equal    Demo    Demo1    msg=Totally custom message    values=False
```
you get `Totally custom message`. If this is important for you, you probably could create a linter rule for RoboCop to require `Should *` keywords to always have a message or possibly create a listener that adds it automatically.

**Comment by pekkaklarck** [comment]
One additional problem in always including the exception type in the error message is that such changes to messages would cause problems if someone handles them with `TRY/EXCEPT` structures. That makes the change backwards incompatible and means that there would need to be really strong reasons to do it.
