### ISSUE TITLE
Implicit type conversion should ensure type or raise an exception

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3680]
When implementing Browser library, we heavily used enum conversion feature as we thought that this offloads type checking to Robot Framework side. Unfortunately this is not the case and now there are some leaky ways of invalid types getting in to library function parameters.

Basically two things have been discovered so far:

1. If an argument object is not a string, it will be passed to library keyword without checking the type against required type.
2. None is expected to be part of all types and strings (and objects) that can be converted to none are passed as None.  

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#implicit-argument-types-based-on-default-values

Example case
```
from enum import Enum

class Fruit(Enum):
    APPLE = 1
    ORANGE = 2
    STRAWBERRY = 3


def eat_fruit(fruit: Fruit):
      print(type(fruit))
```

```
*** Settings ***
Library  fruits.py

*** Test cases ***
Testing
     Eat fruit   APPLE     # OK
     Eat fruit   Orange   # OK
     Eat fruit   None       # Is converted to None => Should raise an exception as the type is not optional
     Eat fruit   ${32}      # Type is ignored => Should check type and raise an exception
```

Now it seems that the type conversion leaks invalid objects. This implies that library should then doublecheck the types anyway.
In my opinion Robot Framework should ensure valid types when they are explicitly given in the library code.

**Comment by pekkaklarck** [comment]
Converting to `None` certainly feels strange in this particular case. There was some reasoning for `None` conversion and it makes sense e.g. when the argument has `None` as a default value, but this should be thought a bit more. Most likely it should be disabled at least with enums.

Not doing anything to non-string objects is a separate question. This behavior is by design but this design can obviously be discussed. There are basically three alternatives:

1. Pass non-string objects as-is. This is what we do now.
2. Try conversion. For example, if an argument like  `x: float` gets value as an integer we could convert it to a float. This would also allow conversion to string with arguments like `x: str`.

**Comment by mkorpela** [comment]
I would prefer option 3. incase the type is defined explicitly.
Python is in my opinion going towards JS world and TypeScript typing system. Types should fail fast. Preferably before execution, but execution time typecheck is also ok. 

If it is inferred from default value only, then I would assume type as Any and allow all..

**Comment by Snooz82** [comment]
As we have at the moment automatic conversion already, but it is limited to string inputs, i would extend this behavior.

If i expect an int and the given type is a string, it can be converted. If this conversion fail, Error. That is the same behavior we have with string inputs and int type at the moment.

If a conversion is not possible independent of the actual value type it should fail. 


Regarding the None.
For me it feels weird to automatically convert the string  `None` to a NoneType without having the possibility to escape that behavior. Specially NoneType should be strict in Robot because it is an important type. So i would prefer never convert string None! Default values with `None` should be shown and used in Robot Framework as `${None}` (that is imho independent of the question if we should do that as well with int,float and booleans)

**Comment by mkorpela** [comment]
After some thought there are two things happening here:

1. Automatic type conversion (from string to what the converter thinks should be ok for the receiving end)
2. Me as a library developer assuming that this is also a type guard that will fail when user gives an enumeration value that is not allowed.

I propose that we add the type guard that will raise an exception if the receiving end expects a specific type and one is not given. Expectation must be explicit and not inferred from a default value.

**Comment by pekkaklarck** [comment]
Forcing given arguments to match specified type hints would be pretty badly backwards incompatible change and in my opinion not worth the benefits. For example, you could have a keyword like

```python
def example(arg: MyClass):
    if isinstance(arg, str):
        arg = MyClass.fromstring(arg)
    ...
```

that automatically handles conversion from string to some custom type. We raising an error when this keyword is called with a string would break its usage without a way to fix that other other removing the type hint. It can be argued this keyword should have a type hint like `Union[MyClass, str]` but we don't currently support `Union` (that would be a good feature) and the change would be backwards incompatible even if we did.

As far as I can see, the benefit of strict type validation would be that keywords called with invalid arguments wouldn't fail with AttributeError or TypeError that can be hard for users to understand but instead there would be an explicit error saying the argument type isn't compatible. Although that would sometimes be useful, I haven't heard normal users complaining about this and don't consider this too important. On the other hand, I'm _very_ careful with backwards compatibility in general and breaking useful features (see the example above) in particular.

Due to the reasons above, I don't want to add general strict type validation to Robot. We can, however, make type validation with certain types more strict. We could, for example, explicitly forbid calling a keyword accepting an enum or a list with an integer (but needed to think about IntEnums with the former case). In many cases we could also do conversion ourselves like if a keyword accepting a float is called with an int, we can convert it safely.

Very highly related to the above is converting non-string arguments to string in cases like `arg: str`. I think that would be a good idea and it would automatically fix robotframework/SeleniumLibrary#1021.

**Comment by mkorpela** [comment]
The major benefit in static types is static type checking.
Robot Framework <-> Python interface is a border.
I've seen this happen with several languages: Objective-C <-> Swift, Java <-> Kotlin and JavaScript <-> Typescript for instance.
Type hint based type checking starts from the expectation that the type hint holds. When it does not, it results in very ugly and hard to debug bugs.

None is the basic example of this problem. Objective-C and Java let null be part of every type, and Swift and Kotlin do not. This means that in pure Swift or Kotlin world there are no nullpointer problems. That is solved completely by the static type checking in Swift and Kotlin.

JavaScript as with RF the problem is a bit larger (although I would still argue that most likely problem is still the nullpointer case) as you can completely miss the type. Again hard to debug bugs and code (Python with type hints or TypeScript) that kind of tells that things should be ok.

Making a border that lets invalid types through will generally then mean that responsibility will be on the library side and Robot Framework facing keywords should not be typed. As the types can not be guaranteed.

**Comment by mkorpela** [comment]
Closing this as I've split it to two issues
