### ISSUE TITLE
Evaluate: NameError - variable not recognized

### ISSUE THREAD

**Issue by blomqsu1** [robotframework/robotframework#3681]
When I use this robot code: 
```
Sort List Specific Order
    [Arguments]    ${input_list}  ${alphabet}=${SPACE}_0123456789aAbBcCdDeEfFgGhHiIjJkKlLmMnNoOpPqQrRsStTuUvVwWxXyYzZåÅäÄöÖ()
    ${ns}    Create Dictionary    alphabet=${alphabet}    input_list=${input_list}
    ${sorted}    Evaluate     sorted(input_list, key=lambda word: [alphabet.find(c) for c in word])     namespace=${ns}
    [Return]    ${sorted}
```
It brings this error
```
Evaluating expression 'sorted(input_list, key=lambda word: [alphabet.find(c) for c in word])' failed: NameError: name 'alphabet' is not defined
```

In 3.1.2 it works, in 3.22 not.

**Comment by pekkaklarck** [comment]
This is an unfortunate regression caused by changes to the evaluation logic behind the `Evaluate` keyword and the new inline evaluation syntax in RF 3.2. We use Python's [eval()](https://docs.python.org/3/library/functions.html#eval) for evaluation the expression and pass the explicitly given namespace, explicitly imported modules, and Robot's active variables to it as global and local namespace. In RF 3.1 both the explicit namespace and modules were passed in as a global namespace but this was changed in RF 3.2 and now the explicit namespace is passed as a local namespace. Most evaluated code isn't affected because it sees both the global and the local namespace, but apparently lambda creates a new intermediate scope where locals aren't visible. We actually had a similar problem with imported modules (#3510) but that was detected already during the RF 3.2 beta period and was fixed before the final release.

Good news is that fixing this ought to be easy by just passing the explicit namespace as part of the global namespace. That's how we fixed the issue with modules as well. Should also add a test for this to make sure this functionality isn't broken again by future changes.

Bad news is that RF 3.2.2 was the last planned release in the 3.2.x series and this isn't important enough bug to warrant one more bug fix release. Unfortunate this issue wasn't discovered earlier.

Luckily there's a way to workaround this problem but I don't have time to explain that right now.

**Comment by pekkaklarck** [comment]
The way to workaround this problem is explicitly passing needed values to the lambda. This can be done by using arguments with default values, because the default value is evaluated in the local namespace where the values are seen. With this particular case this means changing

```
Evaluate     sorted(input_list, key=lambda word: [alphabet.find(c) for c in word])     namespace=${ns}
```
to

```
Evaluate     sorted(input_list, key=lambda word, alphabet=alphabet: [alphabet.find(c) for c in word])     namespace=${ns}
```

A further enhancement would be not creating the namespace at all and instead relaying on Robot's variables being available in the evaluation namespace automatically using the `$var` syntax. That would change the example to this:

```
Evaluate     sorted($input_list, key=lambda word, alphabet=$alphabet: [alphabet.find(c) for c in word])
```

Probably the best way to avoid this problem would be converting this keyword to Python. Then the Python code would be evaluated normally, not with `eval()`, and the whole problem with namespaces would disappear. The resulting code would likely be easier to understand and maintain as well.

**Comment by pekkaklarck** [comment]
As I already commented, this can be fixed pretty easily by using the given namespace as the global namespace with `eval()`. Interestingly we need to keep passing the namespace also to our custom local namespace object to make it possible to detect which names (i.e. variables) in the expression aren't found and should be automatically imported. The latter wasn't done with modules (#3510) but I guess it wasn't needed because modules are automatically imported anyway. They are likely some corner cases where there could still be problems with modules so better to pass them to the custom namespace in the future as well.

For another example about problems with namespaces when using `eval()` see #3593. That issue unfortunately cannot be fixed easily because the global namespace must be a real dictionary and automatically importing modules is handled by our custom local namespace object.
