### ISSUE TITLE
Multiline preformatted string values

### ISSUE THREAD

**Issue by mihaiparvu** [robotframework/robotframework#3683]
I found some interesting/useful enhancements that are requested inside my organization. They are somehow linked together that's why I open a single issue request for now.

The first proposal would be support for some kind of preformatted text with preserved whitespaces (`string` argument value in example) that can be used inside a keyword call:

```robotframework
${datastructure}=  Parse YAML
...  string=\
...  | - one
...  | - two:
...  |     three: four
...  |     five: six
...  parse_options=...
```

Lines starting with `|` create one (multiline) cell value with preformatted text. This will work as well for keyword arguments, that's why we need the backslash `\` to indicate that the value of the argument will be on the following line.
 
Note, that this is just an example syntax, there may be better alternatives.

The second feature would be some kind of command expansion (similiar how it's done in Unix shells).

Currently, a Robot keyword call is a line consisting of cells, where the first cell contains the Robot keyword and the remaining cells the arguments.

The proposal would be: if a cell contains the value `${{` then all following cells until a cell with the value `}}` are considered as another Robot keyword call, which will be evaluated first and its return value will be substituted as resulting value for the cell in the outer Robot keyword call. 

For keyword arguments (`param_name=param_value`) this shall also be allowed like this: `param_name=${{`.

Nesting shall be possible.

Example:

```robotframework
Outer Keyword
...    param1=${{    Evaluate    ['one', {'two': {'five': 'six', 'three': 'four'}}, 'seven']    }}
...    param2=${{    Parse YAML
...        string=\
...        | - one
...        | - two:
...        |     three: four
...        |     five: six
...    }}
Set Local Variable    ${var1}    ${{
...    Inner Keyword
...        ${{    Innermost Keyword    innermost argument    }}
...        second inner argument    }}
```

What do you think of these proposals? Do they make sense to be included in Robot (are they Robot-like)? Would it be possbile to implement without huge changes to the parser?

**Comment by pekkaklarck** [comment]
This requests has two independent parts which is a bit problematic. It's easy to discuss and especially implement features if we have one issue for feature. Anyway, I'll comment both of the proposals here.

1. Is the idea to create a multiline argument? Would the syntax work only with strings or would there be some way to construct lists/dicts as the title of this issue suggests? Or would list/dict creating be handled by the existing argument conversion functionality and this syntax only allow multiline string creation?

2. We already have #3187 about inline keyword call syntax i.e. the latter part of the request. It would be very powerful feature but coming up with a syntax that would be simpler than just having separate keyword calls is not easy.

**Comment by mihaiparvu** [comment]
You are right. I was not aware there was already an issue open on this topic, sorry about that. We should focus on the first point here. 

To answer your question, it is the first answer. The idea is only to support the creation of a multiline preformatted string value. I will also rename the issue accordingly.

**Comment by pekkaklarck** [comment]
Being able to specify data blocks would be handy, but the proposed syntax has some problems:

- Needing to use `...    |` is not that convenient.
- Spaces being meaningful on a normal keyword call would be very hard to implement. The reason is that spaces are considered a separator already by the lowest level parsing code and that code isn't aware of the current context.

Notice also that you can already now use
```
*** Variables ***
${YAML}        SEPARATOR=\n
...            - one
...            - two:
...                three: four
...                five: six
```
to get a multiline string and on the test level you can use the `Catenate` keyword to get same effect. Unfortunately indentation would be ignored (same reason as I mentioned above) but you could use `\ \ \ \ three: four` or `${SPACE * 4}three: four` if that's important. With any bigger snippets it's typically better to have the content in a file and then just refer to it by a file path. In that case all spaces in the file would naturally be preserved.

So, I don't think the original proposal is something we could or even should implement. There are, however, some other ideas that would help in this kind of situation:

1. Possibility to create data blocks in some new test data section. I'm not sure is that worth the effort, though, because it's so easy to have data in external files.
2. It would be handy to have a possibility to create variables directly without using a keyword (see #3761) and that syntax could support multiline strings as well.

**Comment by pekkaklarck** [comment]
This issue originally proposed two features. As I commented already earlier, we already have #3187 about the latter. As I just commented above, I agree with the first proposal that having a better way to construct date blocks would be nice. Because the concrete proposal doesn't really work, I think this issue can nevertheless be closed.
