### ISSUE TITLE
Implicit string type conversion None handling

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3689]
Implicit argument conversion can convert string arguments to expected type defined in a library keyword.

None is expected to be part of all types and strings (and objects) that can be converted to none. These are passed as None.

This can result in problems when receiving keyword does not handle None.
Also special case of type Optional[str] handling is non obvious.

[implicit-argument-types-based-on-default-values](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#implicit-argument-types-based-on-default-values)

Related discussion and issue split from https://github.com/robotframework/robotframework/issues/3680

Converter type signature currently seems to be `converter(str) -> Optional[T]` where T is the expected type from keyword type hint OR default value.

When an explicit type hint is given I believe the type signature should be changed to `converter(str) -> T` where T is Optional only when that is explicitly given in the type hint.

The current situation can raise problems for example when working with enumerations.

I believe that the converter should convert string "None" to None _only_ when type is Optional[T] and does not have default value of None (Optional with default value None is special case as it is the cleanest way of making an argument non required).

Concrete detected problems:

1. None converted and passed to keyword when the type hint type is not optional.
2. Making argument with type hint and with default value of None, should not allow None conversion from string. This seems to be from library implementers point of view, the cleanest way of making an argument not required.
3. "None" is currently converted to None for enum that has a matching member (such as NONE) - this is partly related to problem 2. as NullObject would be the other way of defining none in this case.
4. Optional as a special case of Union type should be handled correctly (now assumed to be unknown type unless an explicit default value is given)

**Comment by pekkaklarck** [comment]
I honestly didn't understand everything in the description (e.g. `Optional[T]`) but I explain the current behavior, the problems I see with it, and what I propose we should do to it below.

Current situation:

1. Different types have different converters. For example bytes, enums, and lists.
2. Most of these converters convert string `NONE` (case-insensitively) to Python `None`. Only exceptions are bytes and bytearray because with them we want string like `NONE` to be bytes/bytearray with those bytes.
3. `None` conversion happens before trying out the normal conversion supported by that particular converter.
4. `None` conversion isn't done with argument types we don't explicitly recognize.
5. Conversion to `None´ with enums is clearly a bug as an enum can have a member with that name. This is basically the same situation as with bytes/bytearray.
6. Robot also does `None` conversion if an argument has `None` as a default value regardless the type.

Different alternative to fix the aforementioned bug and possibly change `None` conversion in general:

1. We could keep the old logic otherwise but just disable `None` conversion with enums. This would be trivial change fixing the clear bug we have.

2. We could disable `None` conversion altogether if an argument doesn't have `None` as the default value. That would change the current logic so that, for example, argument like `x: int` called with `NONE` (a string) would cause an error when earlier the keyword would get `None` (Python object). I'm not a big fan of this solution because the change would be backwards incompatible and benefits would, in my opinion, be pretty small. I guess I can be convinced that this is a good idea, though, but then we should also add support for `Union` to be able to use something like `Union[list, None]` to make it explicit that `None` conversion is allowed.

3. We could disable `None` conversion also if an argument has `None` as a default value. I consider this way too badly backwards incompatible compared to benefits.

**Comment by mkorpela** [comment]
I think we should do at least 1. and disable None conversion with enums for now. This allows complete use of enums to explicitly state allowed string values for an argument field. - this is a very cool feature!

Second part needs the union support so I believe we should at least experiment with it.

**Comment by pekkaklarck** [comment]
My current thinking:

1. Enum fix is a must.
2. If we get Union support (that needs an issue), we can stop automatic `None` conversion when the argument doesn't have `None` as a default value. This will fix 1. as well so a separate fix for that may not be worth it.
3. `None` conversion when the argument has `None` as a default should stay. It should be done only if other conversions don't work to make sure enum with `NONE` as a member works also when used like `x: EnumWithNone = None`.

**Comment by mkorpela** [comment]
Enum fix for None: https://github.com/robotframework/robotframework/pull/3698

**Comment by mkorpela** [comment]
Related pull request https://github.com/robotframework/robotframework/pull/3712

-- This is split from union topic branch and related changes will follow

**Comment by pekkaklarck** [comment]
We have  #3729 that covers not doing unnecessary None conversion which also fixes the problem with enums. Other topics discussed in this issue can get their own issue as well.
