### ISSUE TITLE
Type guard when type hint given in library keyword definition

### ISSUE THREAD

**Issue by mkorpela** [robotframework/robotframework#3690]
Robot Framework syntax <-> Library keyword is an interface between two different programming languages.
Currently with type converter for string to expected types (especially for enums), Robot Framework handles some user errors very cleanly. Unfortunately the converter in it current form is not complete and will not handle all type errors.

I propose that we add another layer of automatic guarding: if an explicit type hint is given, Robot Framework should check on runtime that a user given value does match that type definition. This is either an error of the user of the keyword OR an error in the keyword type hint definition.

In python the special case of number types float and int could be implicitly defined to be of same type.

This would allow earlier detection of user errors for instance when argument order changes etc.
Because this only would affect code that is using type hints, the backwards incompatibility should be limited.

This issue is split from  https://github.com/robotframework/robotframework/issues/3680

**Comment by pekkaklarck** [comment]
The current logic we use with argument conversion is this:

- We have separate converters for types we recognize such as int, bool, and list. With other types we do nothing.
- We only convert if the given argument is a string. With other arguments we do nothing.

How this possibly could be changed:

1. Start converting also non-string arguments. For example, if we have an argument `x: float` and it's called with an int, we could convert it to a float. On the other hand, argument like `x: list` called with an int would cause an error because conversion isn't possible. There would be corner cases like `x: int` called with a float and how to handle `x: bool` but I'm sure we can figure out good ways how to handle them.

2. Start type validation with unrecognized types. For example, argument like `x: CustomClass` would cause an error if called with a string or any other value not `isinstance(arg, CustomClass)`.

Option 1. would, in my opinion, be a nice enhancement in general with very small backwards compatibility concerns. It would also make it easy to start doing conversion in the `arg: str`case that we currently ignore. That string conversion should probably have its own issue, though.

Option 2. is, on the other hand, so badly backwards incompatible that I don't think it's a good idea. It would disallow lot of valid use cases like this one:

```python
def example(arg: MyClass):
    if isinstance(arg, str):
        arg = MyClass.from_string(arg)
    ...
```

We possibly could consider option 2. if we had a way for libraries to register custom converters so that RF could automatically convert strings (and possibly other types) to custom objects. Support for `Union` to be able to use something like `Union[MyClass, str]` might be enough as well but it wouldn't be as convenient.

**Comment by mkorpela** [comment]
I would hope for Option 2 but seems that like with the other issue https://github.com/robotframework/robotframework/issues/3689 this is also dependent on Union support - so that needs to be first tested.

**Comment by pekkaklarck** [comment]
I value backwards compatibility _very_ highly especially when breaking it doesn't bring big concrete benefits. I would say option 2. is possible only when we support automatic converters _and_ Union, and even then we should have them in one release along with the current functionality to make transition smooth. I personally don't think converters are super important otherwise right now, but Union support would have lot of other benefits and should be done in RF 4.0. Care to submit an issue about that?

**Comment by pekkaklarck** [comment]
One possibility would be making strict type validation an opt-in feature that could be enabled using the `@library` (set the default for the library) and `@keyword` (set for individual keyword) decorators.

**Comment by pekkaklarck** [comment]
There have been lot of enhancements related to this:
- Conversion with non-string values including failing if conversion isn't possible (#3735)
- Stricter `None` conversion (#3729)
- Union support (#3738)

Especially the first one is very much related this issue. AFAIK the the only remaining part if handling unrecognized types. As I've commented earlier, I don't think it's a good idea to fail conversion in cases like that. Having support for custom converters would be great, but that needs a separate issue.

**Comment by mikkuja** [comment]
I agree with original proposal that all type hinted arguments should be type guarded by default. Currently most arguments are (type) checked by argument conversion (builtin or user defined custom converters). This gives users false sense of security as in most use cases you can rely that arguments are of correct type. However, types without converters are an exception which our team just learned the hard way.

I understand that backwards compatibility is an issue here so some compromises may be needed. For example a library / keywords level switch for enabling type guarding before making it a default state.

As a workaround we were thinking of using something like this
```python
def _typechecked(_):
    raise ValueError()

ROBOT_LIBRARY_CONVERTERS = {
    CustomType1: _typechecked,
    CustomType2: _typechecked
}
```
or an external library like [typeguard](https://github.com/agronholm/typeguard).

**Comment by pekkaklarck** [comment]
I see the benefits of being more strict but the backwards compatibility problem is too big to make it a default. I think using custom converters is a good solution. We could consider making it easier so that just using
```python
ROBOT_LIBRARY_CONVERTERS = {
    CustomType1: None,
    CustomType2: None
}
```
would work. If you think that would be useful, or have some other idea, please submit a new issue.

**Comment by pekkaklarck** [comment]
I quickly tested the idea to use `None` as a special "strict" converter and it worked nicely with only these changes:
```diff
--- a/src/robot/running/arguments/customconverters.py
+++ b/src/robot/running/arguments/customconverters.py
@@ -69,6 +69,9 @@ class ConverterInfo:
         if not isinstance(type_, type):
             raise TypeError(f'Custom converters must be specified using types, '
                             f'got {type_name(type_)} {type_!r}.')
+        if converter is None:
+            def converter(arg):
+                raise ValueError('We are strict!')
         if not callable(converter):
             raise TypeError(f'Custom converters must be callable, converter for '
                             f'{type_name(type_)} is {type_name(converter)}.')
```

Obviously the error message should be a bit better and this would need tests and docs, but clearly this is a possible approach. If you like, submit an issue and I'll implement it properly for RF 5.1. Unless you want to create a PR as well.

**Comment by mikkuja** [comment]
I would probably prefer a toggle for enabling it for whole library as it would be easier to use. However, these None converters should be quite easy to use as well and definitely more flexible.

I will submit a new issue later today.

**Comment by pekkaklarck** [comment]
Separate argument for `@library` to make all conversions strict is possible but more work and I wouldn't like to add too many arguments to `@library`. Easy way to make _some_ conversions strict would nevertheless be handy so let's start from that.
