### ISSUE TITLE
Document omitting files starting with `.` or `_` when running a directory better

### ISSUE THREAD

**Issue by gabrieljunghokim** [robotframework/robotframework#3691]
Hi gurus,

I have a test suite named `__testclass_v1.robot` since `__testclass` is the actual obj name and want to run that test suite. However RF is unable to pick it up for some reason I don't know. I looked around the user guide and some other references, but I can't seem to find any relevant information about this.

```
% robot tests/api/objects 
[ ERROR ] Suite 'Objects' contains no tests or tasks.
```
Is this intentional?

**Comment by pekkaklarck** [comment]
This is by design and documented here:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-suite-directories

This should perhaps be mentioned here as well, though:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#specifying-test-data-to-be-executed

**Comment by pekkaklarck** [comment]
Yet another place in the User Guide where this should be mentioned:
http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#selecting-files-to-parse

**Comment by pekkaklarck** [comment]
I'll update the aforementioned sections in the User Guide to mention that files and directories starting with `.` and `_` are ignored.
