### ISSUE TITLE
Line starting with single space followed by `#` is not considered comment

### ISSUE THREAD

**Issue by tsrinivas7** [robotframework/robotframework#3721]
Hello ,
We're in process of migrating from Robot3.0.4 to 3.2.1, and found the following issues, I did search through the release notes of 3.1 and 3.2.1 I couldn't find any related tickets. So thought report them here and get some insights.
resources files with keywords in it had comments starting '#' character which are being reported as ERRORs with 3.2.1 while they were working fine with 3.0.4.
Error in resource file ‘/abcd/lib_resources.robot': Creating keyword ' ############################' failed: Keyword with same name defined multiple times
Error in resource file /abcd/lib_resources.robot': Creating keyword ' #' failed: Keyword with same name defined multiple times
Duplicate keyword errors!, these were working without errors earlier!, How do I make it to resolve to BuiltIn. I verified earlier logs and newer logs, I noticed it used to get resolved for first findings i.e BuiltIn.Sleep.
Multiple keywords with name 'Sleep' found. Give the full name of the keyword you want to use:
    BuiltIn.Sleep
    mykeywordsLib.Sleep
Any help to address the above would be appreciated. Thanks!
```
*** Keywords ***
###########################
Connect To Device
###########################
  [Documentation]
  ...      PURPOSE :
  ...      This keyword connects to device….
Disconnect
 [Documentation]
  ...      PURPOSE :
  ...      This keyword disconnects…
  # Disconnect keyword
  DISCONNECT TO DEVICE <some args….>
```

**Comment by pekkaklarck** [comment]
I tested the above example but couldn't reproduce the problem. I needed to fix the code a bit and add tests calling these keywords. Could you create a simple example reproducing the problem in your environment so that I could run it locally as-is?

**Comment by bhirsz** [comment]
What I discovered while developing robocop is that if the comment char is in second cell it will be recognised as keyword. Here is an example https://github.com/MarketSquare/robotframework-robocop/blob/master/tests/atest/rules/not-capitalized-keyword-name/test.robot (the last line will be keyword '# special case'. Weird enough if I place # in first cell or third it will be recognised as comment. This could be related to this issue

**Comment by pekkaklarck** [comment]
The reason a space followed by a hash in the beginning of a line isn't considered a comment that it forms a token with exactly that value and it doesn't start with `#`. If you have two spaces and a hash, those two spaces form a separator so you get two tokens. The first token is an empty string and the latter starts with `#` and is thus considered a comment.

Although there are reasons for this behavior, I agree `#`, ` #` and `  #` in the beginning of the line behaving like this is pretty strange. We could trivially change code using `value.startswith('#')` to `value.rstrip().startswith('#')`, but because that's done fore all tokens in early parsing phase I'm worried it may affect performance. Notice that `value.startswith(('#', ' #'))` doesn't work in all cases because we in general consider also non-ASCII spaces like the NBSP separators and that code only detects the ASCII space. Using `re.match(r'\s*#', value, re.UNICODE)` would work but I'm again worried about the performance implication.

**Comment by pekkaklarck** [comment]
I was right that adding `.lstrip()` fixes the problem and also that it has a small but measurable performance penalty. I was able to do other micro optimization to the related code to keep old performance, though, so the fix is good to go. Need to still add tests for it.

**Comment by pekkaklarck** [comment]
This has now been fixed. Obviously a simple way to avoid this problem is removing leading spaces from the commend lines. Because that syntax worked before RF 3.1, I consider this issue severe enough to warrant medium priority.

**Comment by tsrinivas7** [comment]
Thanks for fixing this, will try the suggestion above to remove leading spaces in comment lines.
