### ISSUE TITLE
Update and enhance output.xml schema

### ISSUE THREAD

**Issue by bitcoder** [robotframework/robotframework#3726]
update RF output.xml schema to reflect v4.0 changes (e.g. SKIP status, critical attribute, and other)

https://github.com/robotframework/robotframework/tree/master/doc/schema

**Comment by pekkaklarck** [comment]
I think we've so far only removed the criticality attribute and added SKIP as a valid status but SKIP will probably become a valid log level as well. @yanne knows these changes best and I hope @Snooz82 as our schema guru could take care of updating schemas.

**Comment by pekkaklarck** [comment]
Did you @yanne already add SKIP as message log level?

**Comment by yanne** [comment]
Yes, SKIP is a message log level in the current master

**Comment by pekkaklarck** [comment]
Ok, that should be added so schemas as well then.

**Comment by bitcoder** [comment]
updated the PR

**Comment by pekkaklarck** [comment]
Thanks for PR @bitcoder!

**Comment by bitcoder** [comment]
you're welcome @pekkaklarck . Hope to be able to contribute more (if time & knowledge allows it)

**Comment by pekkaklarck** [comment]
Noticed that new IF/ELSE related keyword types aren't included in the schema. I'll add them shortly.

**Comment by pekkaklarck** [comment]
There are going to be some more changes:
- Part of model changes (#3749) is representing FOR and IF structures using new `<for>` and `<if>` elements instead of `<kw>` elements having appropriate `type` attribute.
- We plan to move Boolean and date/time related values to use standard XSD types (#3829).

I'll reopen this issue to cover also the above changes. @Snooz82 has already promised to look at updating the schema and may also change it otherwise. @bitcoder is likely to be interested in these changes as well.

**Comment by pekkaklarck** [comment]
Plenty of output.xml changes due to model refactoring (#3749) and otherwise. Some of these changes have happened since beta 2.

1. In execution we now can have also `NOT RUN` status. This was introduced originally by IF/ELSE structures for showing unexecuted branches, but nowadays also unexecuted top-level keywords get that status (#3842 ).

1. IF/ELSE is nowadays stored like this:
    ```
    <if>
        <branch type='IF' condition='$x > 0'>
            <kw>...</kw>
            <status status='NOT RUN'/>
        </branch>
        <branch type='ELSEI F' condition='$x < 0'>
            <kw>...</kw>
            <status status='PASS'/>
        </branch>
        <branch type='ELSE'>
            <kw>...</kw>
            <status status='NOT RUN'/>
        </branch>
        <status status='PASS'/>
    </if>
    ```
2. FOR is stored like:
    ```
    <for flavor='IN ENUMERATE'>
        <var>${index}</var>
        <var>${item}</var>
        <value>first</value>
        <value>second</value>
        <value>last</value>
        <iter>
            <var name='${index}'>0</var>
            <var name='${item}'>first</var>
           <kw>...</kw>
           <status status='PASS'/>
        </iter>
        <iter>
            <var name='${index}'>1</var>
            <var name='${item}'>second</var>
            <kw>...</kw>
            <status status='PASS'/>
        </iter>
        <iter>
            ...
        </iter>
        <status status='PASS'/>
     </for>
```
4. `<msg html='yes'>` -> `<msg html='true'>` (#3852)

**Comment by pekkaklarck** [comment]
Planned changes to output.xml ought to be now done so we can start updating the schema. It would be great to get that done for beta 3, but rc 1 is fine as well.

**Comment by bitcoder** [comment]
@pekkaklarck , in terms of new statutes, overall we're going to have "NOT RUN" and "SKIP".
Semantically, and to make sure I've got it right, is this the overall meaning?

- **SKIP**: used when explicitly skipping tests
- **NOT RUN**: when a test doesn't run due to previous failures

Another question, what happens if you use for example the "--skiponfailure" argument? Will those tests & keywords be marked as SKIP or NOTRUN?

**Comment by pekkaklarck** [comment]
`NOT RUN` is only used by keywords (and IFs and FORs), not by tests or suites. It is used in these two cases:

- IF/ELSE branches that are not executed because the condition was not true or an earlier branch was already run.
- Keywords (and IFs and FORs) that are not executed because there was a failure.

**Comment by pekkaklarck** [comment]
One concrete design decision that we can still think is how to handle lists of items. More precisely, should these items be wrapped into a container or just listed directly inside their parent element. For example, FOR loops can have multiple variables and values (e.g. `FOR  ${x}  ${y}  IN  a  1  b  2`) and I decided to represent them with `<var>` and `<value>` elements (see the example in the [earlier comment](https://github.com/robotframework/robotframework/issues/3726#issuecomment-778127450)) directly inside the `<for>` element. Alternatively we could use something like `<variables><var>${x}</var><var>${y}</var></variables>`.

The simple reason I didn't use a container around a list of items with `<for>` is that I didn't see any benefits from them. They don't really harm either, but there's always some work writing something like `<variables></variables>` to output.xml and probably a bit more when parsing it. Do others see big benefits or problems either way?

One thing I consider really important is consistency and that may also affect this decision. At the moment we wrap tests' tags as well as keywords' arguments, assignment and tags into a container like `<arguments><arg>a</arg></argumetns>` and it might be a good idea to use that approach also with `<for>`. We don't, on the other hand, use such a container with `<test>`, `<kw>`, `<if>`, `<for>` and `<msg>` elements but instead just list them directly inside their parent.

We have several possibilities how to handle this situation:

1. Leave it like it is. It's somewhat inconsistent that `<var>` and `<value>` are directly insider `<for>` but e.g. `<arg>` is wrapped into `<arguments>` container instead of having it directly inside `<kw>` but we can live with that.
2. Add `<variables>` and `<values>` containers for `<var>` and `<value>`, respectively. This would make the situation with `<for>` consistent with `<kw>` but it would also output.xml a bit bigger.
3. Add containers for _all_ lists of elements. This includes  `<variables>` and `<values>` but also something like `<tests>` that contains `<test>` elements and `<body>` that contains `<kw>` etc. elements. This would make handling lists fully consistent but it would also add quite a bit new stuff we haven't really needed into output.xml. This change would also be backwards incompatible change and without concrete benefits probably not worth it.
4. Remove _all_ container elements that don't provide concrete benefits. This would mean using e.g. `<arg>a</arg>` instead of `<arguments><arg>a</arg></arguments>` which would _reduce_ output.xml size a bit. Because output.xml typically has lot of `<kw>` elements and keywords often have arguments, the difference might be noticeable. Also this change would naturally be backwards incompatible, but due to it having concrete benefits (consistence, smaller output.xml size) it might very well be worth it.

The more I think about this, the more I like the option 4. above. It's backwards incompatible but I think benefits are big enough and RF 4.0 as a major version makes this kind of changes possible. What do others think about this?

**Comment by pekkaklarck** [comment]
I submitted separate #3853 about removing unnecessary containers. We can continue discussing about that there.

**Comment by pekkaklarck** [comment]
Issue #3762 reports that although our schema currently says that `<test>` can have `<msg>` element directly, RF doesn't actually support that. Need to either change RF or update schema accordingly.

**Comment by bitcoder** [comment]
@pekkaklarck  I had that doubt actually. I was looking at the schema and working on one integration with other tool where we use Robot Framework output.xml as a way to exchange infromation, and I thought: "well, is this the same message as the one contained in the last executed keyword? If not, how can we control it?"

**Comment by pekkaklarck** [comment]
You it be better for you @bitcoder if we allowed `<msg>` directly inside `<test>`? Supporting it would be trivial and I see no problems with it. It shouldn't be allowed directly inside `<suite>`, though.

**Comment by pekkaklarck** [comment]
This won't make it into rc 1. Needs to obviously be done before the final release.

**Comment by pekkaklarck** [comment]
This ought to be now done. The new schema can be found via https://github.com/robotframework/robotframework/tree/master/doc/schema and the README there has also been updated.

Review would be nice! Ping @bitcoder and @Snooz82.

**Comment by bitcoder** [comment]
Yet to be decided, as discussed on Slack with @pekkaklarck 

- add restriction that schemaversion must be 2
- using `version="2"` instead of` schemaversion="2"`.

**Comment by pekkaklarck** [comment]
Adding the restriction is probably a good idea. If that's done, should use the same approach Libdoc schema uses. If we come up with some better way to restrict it, Libdoc schema could obviously be enhanced as well. Just want to be consistent.

In my opinion `schemaversion` is a lot better in output.xml than `version` as the latter could easily be considered Robot Framework version. What we could consider is adding `version` into the schema itself like this:

    <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" version="2">

Having the schema version visible in the schema itself and not only in the file name (`robot.02.xsd`) would be a good idea in my opinion. I'm not sure is this the best (or even valid) solution, but I saw some examples using this approach when searching information about adding schema version. Another problem is that we needed to remember updated this info if/when schema version is updated. Probably would be best to add a test that the current schema `version` matches current output.xml `schemaversion`.

**Comment by pekkaklarck** [comment]
After a bit more investigation it seems `<xs:schema version="2">` is a valid approach. It's not easy to find solid information about this, but at least XSD tooling seems to support it. For example, by editor doesn't complain about it and even autocompletes after just typing `v`. Also Python [xmlschema](https://pypi.org/project/xmlschema/) supports it out-of-the-box. When I add `version="2"`I get this:

**Comment by pekkaklarck** [comment]
The aforementioned Python xmlschema module certainly eases the pain working with schemas!

**Comment by pekkaklarck** [comment]
PR #3876 enhanced specifying status and my commit above made version info stricter. I guess we can now consider this issue done. Further review and comments are obviously appreciated still!
