### ISSUE TITLE
Support messages directly under test in output.xml

### ISSUE THREAD

**Issue by karkusviktor** [robotframework/robotframework#3762]
Running rebot aginst the following xml results in "failed: Incompatible XML element 'msg'." error message

```
<?xml version="1.0" encoding="UTF-8"?>
<robot>
  <suite source="suiteSource" name="suiteName">
        <test id="A" name="test A">
          <msg timestamp="20201116 08:29:45.100" level="WARN">Hi from test - doesn't work</msg>
          <kw name="log">
            <msg timestamp="20201116 08:29:45.100" level="WARN">Hi from keyword - does work</msg>
          </kw>
          <status status="PASS" starttime="20201116 08:29:45.130" endtime="20201116 08:29:45.140"></status>
        </test>
  </suite>
</robot>
```

It only works of the msg under test tag is removed even though it is valid according to the schema:
https://github.com/robotframework/robotframework/blob/6d90c1940ceea2219306d9bcd41e2299b4a86d71/doc/schema/robot-xsd10.xsd#L31-L43
https://github.com/robotframework/robotframework/blob/6d90c1940ceea2219306d9bcd41e2299b4a86d71/doc/schema/robot-xsd11.xsd#L31-L43

**Comment by pekkaklarck** [comment]
The reason for this behavior is that Robot itself cannot create output.xml where `<test>` would directly have `<msg>`. Changing output.xml parsing to support that would be trivial and based on a quick test also log.html would look fine. What kind of use case do you have for this functionality? This could still be change before RF 4.0 rc 1.

The schema  clearly doesn't match the reality at the moment. If we don't change the implementation, then the schema needs to be updated. It needs to be updated in the very near future anyway (#3726).

**Comment by bitcoder** [comment]
Hi @pekkaklarck , I checked on my end and it seems that `<msg>` at the `<test>` element is not used and can be safely removed.
When I read the schema I thought "well, this is probably for an overall placehold for output information related to this test, such as stdout/stderr"... however, that info may be on the `<msg>` element inside the `<kw>` elements.
 If you or anyone doesn't see a use case for it, I would say to remove the support for the element at the `<test>` level.

**Comment by pekkaklarck** [comment]
Certainly nobody currently uses `<msg>` directly under `<test>` because Robot fails to parse output.xml like that. Changing that would be trivial and based on my experiment it seems log.html would also look fine. I'm actually pretty certain that earlier creating log.html would have failed but the order of messages and keywords being preserved (#2086) has changed that.

**Comment by karkusviktor** [comment]
The use case is marginal. We create an output.xml manually and use rebot to create a nice report out of it.
This issue is more of a heads-up that the xsd doesn't match the code parsing the xml in rebot.

**Comment by pekkaklarck** [comment]
Thanks for the update @karkusviktor! I agree the schema being wrong is the bigger problem here. That said, I think supporting messages directly under test is a good idea for these two reasons:
- After #3749 the result side model supports `test.body.create_message('Hi from test')` and Robot not handing it otherwise would be odd.
- Adding the support seems to be trivial.
