### ISSUE TITLE
datetime format %z not working

### ISSUE THREAD

**Issue by KenZhang0024** [robotframework/robotframework#3766]
Hi team,

I found an issue with the Get Current Date function in the DateTime library. The datetime format for utc offset (%z) is not working. 

Here's the code:
    ${date}     Get Current Date   result_format=%Y-%m-%dT%H:%M:%S%z%A
    Log To Console  Show date: ${date}

The expected result should be:
Show date: 2020-11-18T15:08:38+1100Wednesday

The actual result:
Show date: 2020-11-18T15:08:38Wednesday

The system I've tested is Mac and Linux:
Mac:
![image](https://user-images.githubusercontent.com/40461064/99483954-74c6c300-29b3-11eb-9083-5341467003d1.png)
Linux:
Docker Ubuntu latest : 
https://hub.docker.com/layers/ubuntu/library/ubuntu/latest/images/sha256-1d7b639619bdca2d008eca2d5293e3c43ff84cbee597ff76de3b7a7de3e84956?context=explore

Could you please advice that is it a bug or just not supported? Thanks in advance!

Regards,
Ken

**Comment by pekkaklarck** [comment]
According to https://strftime.org `%z` is timezone which can be empty if the object isn't timezone aware. The DataTime library doesn't support timezones because Python hasn't had built-in support for them. I think Python 3.9 actually added some timezone support so perhaps this could enhanced. Are you possibly interested to look at that?
