### ISSUE TITLE
Metadata name overlaps with data when larger than expected in log and report

### ISSUE THREAD

**Issue by lesnake** [robotframework/robotframework#3788]
When a metadata name is longer than the width of the summary table, then, in both the report and log, the metadata name overlaps with the metadata value.

I expect readability at all times. Either cut the name, adapt the colum witdh, shift the data value.

Running the following suite :

> *** test cases **
> 
> dummy
>         log  dummy test

with the command

> robot --metadata I_am_a_very_long_named_metadata:data tst_metadata.robot 

will trigger the issue.

Comments:
I've been hacking around using firefox inspector feature. Unckecking the "width" parameter of the class "details" solves the overlapping problem. But it has side effects.
It might be tricky to find the proper balance in this section that mixes size limited fields (times, status) and user set data, thus random size, like meta data and log file name.

**Comment by pekkaklarck** [comment]
This is a real problem but seems to occur only when the name is over 20 characters long. Surprisingly the name isn't wrapped from spaces. Things we can try:

1. Reserve a bit more space for the name. As you noted, we cannot reserve too much space because other fields are pretty short and they would look strange.
2. Allow wrapping from spaces. Long names without spaces ought to be pretty rare.
3. Force wrapping long names. Probably better than current situation and ought to be easy with CSS nowadays.
4. Set width dynamically. Probably not a good idea because other names are short and this is likely to require more logic.

**Comment by pekkaklarck** [comment]
Turned out just removing `white-space: nowrap;` enabled wrapping both with and without spaces. After that the space reserved to this information in log.html could actually be reduced a bit but in report.html it made sense to increase it slightly. Some fine-tuning can also be done to aligning names and values.

**Comment by lesnake** [comment]
Hello,
I've tested by manually removing `white-space: nowrap`, it gets the job done.
The good new is that wrapping also occurs on hyphens `-` when there are some.
