### ISSUE TITLE
Screenshot library prevents graceful termination of execution if wxPython is installed

### ISSUE THREAD

**Issue by HDwares** [robotframework/robotframework#3798]
With the robot framework upgrade, when user Imports **Screenshot** library, then during execution on pressing Ctrl+C, execution stops without generating log and report files. Earlier it used to terminate execution with log and report files generated which is called as grace full termination of execution.

I have observed this issue since robotframework 3.2.2 upgrade.

Eg. Try below code:
```
***Settings***
Library   Screenshot

***Test Case***
Screenshot library test
   Sleep  30s
```

Press Ctrl+C in command line while waiting.

**Comment by pekkaklarck** [comment]
I don't have problems stopping executing that example with Ctrl+C. Could you tell a bit more about your environment?

- Operating system
- Python version
- Which RF version this used to work?
- What backend do you use with Screenshot? You can get that info by running this command:

          python -m robot.libraries.Screenshot test

**Comment by HDwares** [comment]
Please find my comments

Operating system?
  Windows 10
Python version?
  3.8.2

Which RF version this used to work?
  I have seen it working with 3.1.2

What backend do you use with Screenshot?
  With the command provided it returned:
  Using ''wx" to take screenshot.
  Not taking test screenshot

I suspect this is due to 'wx'.

**Comment by HDwares** [comment]
Any update on this?

**Comment by pekkaklarck** [comment]
Sorry for ignoring this for long time. Because this problem doesn't occur with RF 3.1.2 and wxPython is involved, this could be caused by #3403 (PR #3407) . As I [commented the issue](https://github.com/robotframework/robotframework/issues/3403#issuecomment-598129611), I'm not too happy about the global `wx.App` reference. I thought it wouldn't matter because it's created only if `wx` is installed, but it certainly could be causing this strange problem.

Could you @HDwares debug this a bit further in your system? A simple way to test is wxPython causing this is uninstalling it. If that fixes the problem, then the root cause most likely is the global `wx.App` reference. If you have coding experience, you could also try modifying Screenshot library so that global `wx.App` reference isn't created. You could either revert changes done in PR #3407 or change the code [like I proposed](https://github.com/robotframework/robotframework/pull/3407/files#r355887495). Notice that apparently that proposal didn't fix the original problem reported in #3403, but it would be good to know does it fix this problem.

If not creating the global `wx.App` reference fixes the problem, we need to think how that fix is implemented. Changing code so that #3403 occurs again isn't a great idea, but because that problem was reported to occur only with Python 2.7 and the issue talked only about Linux, we could possibly make the code conditional. Or could you @HelioGuilherme66 test is the fix needed in the first place anymore? It's certainly possible that wxPython itself has changed and we could just revert #3407.

**Comment by HDwares** [comment]
Thanks @pekkaklarck uninstalling wxPython worked.

**Comment by HelioGuilherme66** [comment]
This is a reminder to @HelioGuilherme66 to now forget this issue.

**Comment by pekkaklarck** [comment]
I'll leave this to RF 4.1.

**Comment by pekkaklarck** [comment]
I reverted the change introduced by PR #3407 (more precisely commit 1d8e9a31d8f7a30348dbf2799f62fdc758daa825) in commit 7b8f5aee70dd3d30669685a377d61136c4418a8b.

I couldn't test the effect with Python 2.7 simply because wxPython doesn't seem to be available for it anymore. That means there likely aren't many users who would be affected by this even if reverting the change would introduce the problem reported in #3403 again.
