### ISSUE TITLE
Copy ID / go to ID in log.html

### ISSUE THREAD

**Issue by MrMino** [robotframework/robotframework#3800]
Orthogonally related to #3799.

It's a quite nice feature to be able to browse the RF log by anchors, i.e. URLs that end with `log.html#s1-k1-k2-k4-k1-k3-k5`, obtained by using "Link to this keyword" button.

Sadly, if the logs are downloaded & inspected from a local copy, this feature is far less usable - with a local file the "copy URL" function is meaningless, as everyone will have the file in a different path. Generated link serves merely to obtain the anchor (hashed ID part of the URL).

In my organisation very few people know about the ID anchors, even less use them, and it's cumbersome to explain that "you can add the hash part to the URL in the browser → reload the page to go to the log part mentioned" every time it comes up.

Because of this, many people use screenshots to point to the right part, then instead of attaching the whole log - use screenshots as the sharing tool. It annoys the hell out of the devs when testers do it.

It would be nice to have a dedicated input field for it, so that it is clear that the feature is there. I'm thinking about something akin to this:

![mockup](https://user-images.githubusercontent.com/6691643/102293982-7d75cf00-3f48-11eb-9073-1e23733c4019.png)

The value in this field would update every time user unwraps a part of the log or clicks on "Link to this keyword". Setting it would unwrap the keyword tree and scroll the page to the right anchor. This would make it possible to share a log via an attachment, point directly to the place of interest (or even multiple), then find the place by inserting the right value back to the field in the newly opened log.

This would be a killer usability feature, if combined with a nice left-hand keyword shortcut that would make it seamless to copy / paste these IDs without having to click on the input box.

With a bit of guidance on where to start this (I mean path in the repo), I could even PR this myself. Granted, I'm not a JS guy, but I know how to follow a style guide :).

**Comment by pekkaklarck** [comment]
The general problem with these ids, and the reason they aren't more prominently visible, is that they are generated during execution and thus can change between runs. They main use case for the "Link to this keyword" functionality is making it possible to create an easily copyable link that can be shared when the log file is on a server.

I can see that if you copy the log to your local machine then only the id part of the URL is interesting, but I'm still not certain is making the id more visible really a good idea. The main reason I'm not immediately sold is that I doubt copying files to local machines is too common and in all other cases the id would mainly add confusion.

If there are also other organizations where copying log files to local machines is common and having ids more visible would help, then this functionality certainly can be added. Otherwise I think it's best to train users to copy the id part from the URL. I actually doubt users would understand how to use the proposed "call id" with local files without training (which possibly be provided by built-in help).

**Comment by MrMino** [comment]
> The general problem with these ids, and the reason they aren't more prominently visible, is that they are generated during execution and thus can change between runs.

Could you please give an example? I was of the impression that this was a given, but I have a different background than most of the people that write RF code. Calling the feature differently or putting some kind of a run-id into the selectable text might aid that.

> The main reason I'm not immediately sold is that I doubt copying files to local machines is too common

The argument in the other direction does not work. Standard users, even in large organisations, don't have a way of hosting logs up on a website that would allow for usage of URLs. Cloud services (think OneDrive) would most likely put the html page into an iframe, should it be even possible to preview it, so there's no way of sharing a link to it that way either.

The main issue is that we don't have a streamlined log section pointer that can be used in a conversation over MS Teams / Slack / email. Sifting through timestamps is a chore, people who report bugs don't use IDs. The null state here is a situation that is hard to make worse by adding any such feature.

> and in all other cases the id would mainly add confusion.

It doesn't have to be _that_ prominent. I've made that mockup mainly to make sure that I'm understood correctly. It could be a separate "find keyword" menu. IDs look like a good candidate because a) they are already there b) it doesn't take much to implement them.

> I actually doubt users would understand how to use the proposed "call id" with local files without training (which possibly be provided by built-in help).

This could be aided by input box placeholder, highlighting the clicked keyword (the same way it is highlighted now, when the anchor link is used), adding a "copy id" button next to "copy url", adding a button that will scroll down to the log part, etc.

All in all there's a room to make it idiomatic, I just haven't spent enough time on it.

**Comment by pekkaklarck** [comment]
This functionality has two sides:

1. Making id available. You can already now see it as part of the URI, but it could be available also otherwise. This is pretty rare need, though, and making it visible as prominently as in the example above is probably too much.
2. Search functionality to allow searching by id. We already have #3799 about search in general.

In my opinion making the id at all more visible than it's now doesn't make sense unless we have search. I'll close this until #3799 is implemented.
