### ISSUE TITLE
Rebot should not take into account SKIP status when merging results

### ISSUE THREAD

**Issue by krysalead** [robotframework/robotframework#3818]
The idea is that when we are combining runs where we have set some tests as skipped and some as passed or failed but the skip status is on different test case in each run, it would be good to keep the previous run status as skip is not known status.
Given RUN1
```
TestA -> skip
TestB -> Pass
TestC -> Fail
```
Given RUN2
```
TestA -> Pass
TestB -> Skip
TestC -> Skip
```
Merged result should be
```
TestA -> Pass
TestB -> Pass
TestC -> Fail
```
It could be only my requirement WDYT?

**Comment by pekkaklarck** [comment]
I don't personally have strong opinion about this. I can see that basically ignoring the skip status when merging would be convenient, but the last status always winning also makes sense. If others agree that skip should be ignored in this regard, I'm fine with the change but we'd still need someone to provide a PR. This could possibly be configurable, but I'm not sure is that worth the effort.

Somewhat related to this, we should think how `--rerunfailed` should work with the skip status. Should it rerun also skipped tests? Should that be configurable or should we add `--rerunskipped` instead? This discussion belongs to a separate issue, though.

**Comment by krysalead** [comment]
I am not against contributing to that if we agree on a behavior. It could save me time also if you have pointer to code and coding guidelines :)

**Comment by pekkaklarck** [comment]
Changing this logic probably isn't a big task but we need to first have a consensus that it's a good idea. As I wrote earlier, I don't personally have a strong opinion and can see benefits with both approaches. Could you ask how others feel about this e.g. on our Slack?

**Comment by pekkaklarck** [comment]
No comments about this lately but now that I look at this again myself I like the proposal quite a bit. I'll ask opinion from others on Slack and if the consensus is that this is a good idea we still have time for this before RF 4.0 rc 1. I'll add this tentatively to RF 4.0 scope so we don't forget about it.

**Comment by krysalead** [comment]
I posted the question in the forum to get some feedback as well, no luck.
https://forum.robotframework.org/t/rebot-to-keep-skip-status/1310

Hope this will get included, if so I will have something to present to the next RobotCon ;) (2022)

**Comment by pekkaklarck** [comment]
There hasn't been too many comments about this, but I personally think this would be a good idea. Unfortunately implementation is not as easy as I thought and especially handling situation were merged outputs are merged again requires some thinking. Because I want RF 4.0 to be released _very_ soon, I moved this to RF 4.1 scope.

**Comment by pekkaklarck** [comment]
This is now implemented. Hopefully you @krysalead can test this once we have a beta or release candidate our hopefully next week.

**Comment by krysalead** [comment]
Hi Pekka,

Thanks for the change, I will watch the release and test ASAP. 

regards

Olivier

**Comment by Pakkanen1** [comment]
@krysalead Can you please explain the scenario in more detail? You are running a set of tests A,B,C and 1 of them is skipped (why?), 1 passes and 1 fails. You then rerun all tests, including the one that passed. Why not just rerun the one that failed?

**Comment by krysalead** [comment]
Usually, I am running tests manually on top of automated tests, manual tests are skipped (I am not using the tag segregation because I don't have hand on the automated tests) so I can run only manual ones or all the tests. Manual ones are then skipped during automated run. I am then running the manual ones and aggregate the 2 reports.

**Comment by Pakkanen1** [comment]
I strongly believe that the latest status should override the previous status. Whenever I use skip, it is a planned action. For example when testing across multiple environments I would set certain tests to skip when there are differences in how these environments have been configured. If the assertion that checked whether or not the test should be skipped, is dependent on the UI and there is any flakiness, it might result in the test failing instead of skipping.
This new behavior causes any flaky tests that fail on the first run, but are skipped on the rerun, to show as "failed" in the merged report. Flakiness is a very common issue and one of the ways to deal with them is an automatic rerun. 

To me your scenario sounds like your test suite is not optimized. Having test cases in a suite that need to be manually run makes me think those tests should be separated entirely or at the very least tagged so that they can be excluded.

**Comment by krysalead** [comment]
Skip will remain skip unless you make it run. Your use case will still work, you have a SKIP for a test you will keep it, this change is about merging multiple runs of the same tests, which in your case should not be merged, if you run on certain environment a test it should be a report and on another env another report. You should not merge your report. 
@pekkaklarck it is working perfectly thanks a lot.

**Comment by Pakkanen1** [comment]
You misunderstood me. I am not merging tests across multiple environments. I am running the same tests twice (if the 1st test run failed) in a single environment and then merging those results. Then I move to the next environment and run the tests there. I am not mixing results of different environments together into a single report.
