### ISSUE TITLE
New setting for test parametrization

### ISSUE THREAD

**Issue by ollipa** [robotframework/robotframework#3820]
I'm suggesting a new setting/syntax for parametrizing test cases. As far as I know, there are currently two ways to parametrize tests: using for loops and data-driven style tests.

Using _for loops_ is discouraged in the test cases because they hinder the readability of tests ([example](https://github.com/ollipa/robot-parametrize-poc/blob/master/tests/for_loop.robot)). For loops also reduces the readability of test reports. Furthermore, if one iteration fails in the for loop, rest of the tests (iterations) will not be executed.

_Data-driven style_ is great when a test cases should be executed over many different variables. However, if there are just a few different variables, I think data-driven style can be overly complex, and tests become more difficult to read because you need to see the templates to understand the tests. Also, you might need to repeat the same variable values multiple times for different templates ([example](https://github.com/ollipa/robot-parametrize-poc/blob/master/tests/template.robot)).

My suggestion is to add a new setting `Parametrize` that would allow parametrizing a suite or a single test case with the given values. On suite level it would look like this:

```robot
*** Settings ***
Resource          keywords.resource
Parametrize       MasterCard     Visa

*** Test Cases ***

Complete A Card Payment
    Register A New Transaction
    Open Browser To Input Card Information
    Input Card Information    ${PARAM}
    Process Transaction
    Transaction Status Should Be    successful
```

On test level it would look like this:

```robot
Complete A Card Payment
    [Parametrize]    RoboCard    TestCard
    Register A New Transaction
    Open Browser To Input Card Information
    Input Card Information    ${PARAM}
    Process Transaction
    Transaction Status Should Be    successful
```

Providing `Parametrize` setting in test level would override the suite level setting. This syntax would provide the benefit that tests could be written almost exactly the same way as without parametrization ([example](https://github.com/ollipa/robot-parametrize-poc/blob/master/tests/parametrize.robot)).

In my particular use case I have multiple test suites with about 5-10 test cases. I need to parametrize the tests over two different values. If I use data-driven style, I would need to convert all test cases to templates which feels a bit awkward.

I have implemented a proof of concept solution here: https://github.com/ollipa/robotframework/tree/feature/suite-parametrize. I also made an example repository that uses my fork and has example test cases with different styles to parametrize tests: https://github.com/ollipa/robot-parametrize-poc.

I would like to hear your thoughts about this and I would be happy to open a PR if you like this idea.

**Comment by pekkaklarck** [comment]
Being able to parametrize tests like this would be handy, but the problem with adding support to the core framework is making it generic. Being able to specify values directly in the test data would be enough in simple cases, but at least these important features should also be supported:
- Reading values from external sources. Preferable from different kind of sources (Excel, CSV, XML, JSON, YAML, ...).
- Generating values dynamically.
- Modifications to generated tests. At least simple modifications like setting name, documentation and tags.

The problem with adding something to the core is that changing it is hard due to backwards compatibility concerns and somewhat slow release schedule. This is the reason I suggested @Snooz82 to create an external [DataDriver](https://pypi.org/project/robotframework-datadriver/) project instead of us trying to add built-in support. Have you @ollipa checked does DataDriver support your use cases? If it lacks features, I'm sure @Snooz82 is happy to accept contributions.

Notice that I'm not against adding parameterization into the core in the future. That could mean integrating DataDriver or some other tool to the core or designing new functionality based on the experiences.
