### ISSUE TITLE
extenting CLI options

### ISSUE THREAD

**Issue by sebastianciupinski** [robotframework/robotframework#3831]
I just thought, that CLI arguments of RF could be extended with following options
--executors which accepts integers: having this option set, many instances of robot could be forked/many threads could be spawned to execute the same set of tasks in parallel
--schedule which accepts datetime string: having this option, start of execution could be scheduled to given time

I know there are option already to achieve this, but I think it could be useful to support it natively.

**Comment by pekkaklarck** [comment]
We've made a pretty fundamental design decision to not have this kind of orchestration functionality in the core framework. Reasons include:

- There are lot of ready-made generic tools available. One great example is Jenkins.
- There are also Robot Framework specific tools like Pabot available.
- Having just two options wouldn't be enough for anything more complicated. Better to expose APIs for external tools that can implement features like this.
- Having everything in a single tool would mean that getting new features out would require waiting for new releases of the whole big thing. External tools can have their own release schedules.
- It's unlikely that there would be one good orchestration solution for all usages. Better to have this out from the core so that there can, instead, be different external solutions for different needs.
