### ISSUE TITLE
Convert Date with a string timestamp that has enough decimals causes ValueError

### ISSUE THREAD

**Issue by xylix** [robotframework/robotframework#3834]
Expected behaviour: after converting to a string, a valid epoch timestamp results in a valid output from `Convert Date`

Actual result: `ValueError: time data '1611-30-41 88:20:15.660000' does not match format '%Y-%m-%d %H:%M:%S.%f'` 

Repro:

```
*** Settings ***
Library  DateTime

*** Test Cases ***
DateTime conversion failure
	${epoch}=  Get Current Date    increment=1 day    result_format=epoch
	Log  ${epoch}
	${stringified_epoch}  Convert To String  ${epoch}
	${date}=  Convert Date  ${stringified_epoch}
	Log  ${date}
```

This causes a `ValueError: time data '1611-30-41 88:20:15.660000' does not match format '%Y-%m-%d %H:%M:%S.%f'` error, whereas without the string conversion it works just fine.

**Comment by pekkaklarck** [comment]
This is actually by design and also the [library docs](http://robotframework.org/robotframework/latest/libraries/DateTime.html#Date%20formats) tell that

> Epoch time is the time in seconds since the UNIX epoch i.e. 00:00:00.000 (UTC) 1 January 1970. To give a date in epoch time, it must be given as a number (integer or float), not as a string. To return a date in epoch time, it is possible to use epoch value with result_format argument. Epoch time is returned as a floating point number.

The reason for this design is that `Convert Date` supports dates without any separator so e.g. `20210129` as a string means this particular day but as an integer that same number would be some day in late 1970.
