### ISSUE TITLE
Handling paths with double leading slashes like `//home/test` can cause endless loop

### ISSUE THREAD

**Issue by hab-dad** [robotframework/robotframework#3844]
I want to report a potential endless loop in robotframework.

it is about method _common_path in robot.utils.robotpath.
the endless loop will occure when one of the paths has a double '//' 

for example:
_common_path('//home/test', '/home/user/')

**Comment by pekkaklarck** [comment]
I can reproduce the bug. This helper function is used by `robot.utils.get_link_path` that is used in various places for creating (preferably) relative clickable links.

We definitely need to fix the endless loop, but the question is that what `_common_path('//home/test', '/home/user/')` should return. Double slash in the middle like `/home//test` is already now considered same as a single slash because `os.path.dirname` used by `_common_path` considers them same:

```python
>>> from os.path import dirname
>>> dirname('/home/test')
'/home'
>>> dirname('/home//test')
'/home'
```
Leading double slash is handled differently which is also the reason this bug occurs:
```python
>>> dirname('/home')
'/'
>>> dirname('//home')
'//'
>>> dirname('//')
'//'
```
We could easily change `_common_path` to consider `//home` same as `/home` but I want to first understand why `os.path.dirname` doesn't do that.

**Comment by pekkaklarck** [comment]
It seems that handling leading double slash like that is due to some POSIX quirk not even used on Linux:
https://stackoverflow.com/questions/7816818/why-doesnt-os-normpath-collapse-a-leading-double-slash
https://bugs.python.org/issue636648

I think it's safe we consider `//home` and `/home` same.
