### ISSUE TITLE
Question related to Dictionary in Robot

### ISSUE THREAD

**Issue by FrankHGW** [robotframework/robotframework#3850]
Hi,

I have created the following dictionary:
&{testAncpsPortLogDict}=   Create Dictionary   Msg=up   log-ger=67  Loop-Circuit-id= AccNodeIdGlobal

When I want to modify the element of this, I do the following:
${testAncpsPortLogDict.Msg}=   Set Variable   newValue

After this  I can see the correct modification via 
log    testAncpsPortLogDict=${testAncpsPortLogDict}     console=y
>> testAncpsPortLogDict={'Msg': 'newValue', 'log-ger': '67', 'Loop-Circuit-id': ' AccNodeIdGlobal}

But wenn I will modify the 2rd entry "log-ger" it does not work,  there is also no error message
${testAncpsPortLogDict.log-ger}=   Set Variable   newValue

If I leave out the hyphen, it works.

&{testAncpsPortLogDict}=   Create Dictionary   Msg=up   logger=67  Loop-Circuit-id= AccNodeIdGlobal
${testAncpsPortLogDict.logger}=   Set Variable   newValue

Why is the hyphen a problem ?
How do I get this to work with hyphen ?

Thanks,
Frank

**Comment by pekkaklarck** [comment]
I haven't looked at the code, but my guess is that this doesn't work because in Python you cannot access or assign an attribute with a hyphen in name. We might be able to make that work here, but I'm not sure is there enough time to look at this before RF 4. We could also make it possible to use syntax like

```
${dict}[key] =    Set Variable    value
```
to allow using whatever `key`, but that's certainly out of RF 4 scope.

A solution that will certainly work is using keywords from the Collections library:

```
Set To Dictionary    ${dict}    key    value
```

**Comment by pekkaklarck** [comment]
Took a quick look at the code and my guess above is correct. Due to similar reasons using `${testAncpsPortLogDict.log-ger}` in arguments doesn't work either. We possibly could change assignments to allow hyphens, but in arguments changing extended variable syntax to allow it like this would be pretty much impossible. A good workaround is using keywords from the Collections library as mentioned above. Making it possible to use
```
${dict}[key] =    Set Variable    value
```
could be considered as well but it would need its own issue.

**Comment by FrankHGW** [comment]
Thanks Pekka,
I have solved it with [] instead mit dot with the index inside the Square brackets and it works.
