### ISSUE TITLE
robot framework not recognized as a command

### ISSUE THREAD

**Issue by joaovicenteft** [robotframework/robotframework#3854]
Using windows 10

I've installed python 3.9 and pip
Upgraded pip
And I've used the command 'pip install robotframework'
It installed
But
when I run
'robot --version'
It show up that this command is not recognized

I added python and python script to my enviroment variables

**Comment by pekkaklarck** [comment]
Sounds like a problem in configuring PATH or otherwise setting up the environment. Because we don't have access to your environment, it's pretty much impossible for us to help. You should take a look at Robot's installation instructions related to this. If that doesn't help, study pip documentation. You should also read the message you get from pip carefully. At least the latest versions tell if they install something to a location that's not in PATH.

If nothing else help, you can try asking more help on our Slack or other such support forum listed at robotframework.org. This issue tracker is for bug reports and enhancement requests.
