### ISSUE TITLE
Issues in RF listener V2 with if statement

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#3855]
After the latest changes broke the debugger (as it relied on monkey-patching of the `StepRunner`), I decided to go on and start relying in the line numbers from the V2 listener, but its behavior doesn't seem correct when evaluating an if statement.

i.e.: Given the code (saved in a file: `if_robot.robot`):

```
*** Variables ***  # Line 1
${counter}    2

*** Test Cases ***  # Line 4
Can use resource keywords
    
    IF    ${counter} > 1    # Line 7
        Log    'Call ${counter} > 0'    console=True  # Line 8
    ELSE
        Log    'Call ${counter} < 0'    console=True  # Line 10
    END
``` 

I expected the listener to receive something as the events below for the if statement:
`start_keyword` on `Line 7` with the source: `if_robot.robot`
`start_keyword` on `Line 8` with the source: `if_robot.robot`

yet, it receives something as:
`start_keyword` on `Line 7` with the source: `None` (wrong source)
`start_keyword` on `Line 8` with the source: `if_robot.robot` (ok)
`start_keyword` on `Line 9` with the source: `None` (this should NOT be here as this line was not executed)
`start_keyword` on `Line 10` with the source: `if_robot.robot` (this should NOT be here as this line was not executed)

So, the issues are:
- `None` is passed as the `source` instead of the actual `source`
- Lines which aren't executed are passed to the listener.

Note: that info was extracted with the code below (the `XXX_PATH_TO_SAMPLE_FILE` must be updated to point to the file above):

```
import os.path


class V2Listener(object):
    ROBOT_LISTENER_API_VERSION = 2

    def __init__(self):
        self.level = 0

    def _get_source(self, attributes):
        source = attributes["source"]
        if source is None:
            return "None"
        return os.path.basename(source)

    def start_test(self, name, attributes):
        self._print("---- START TEST: ", name)

    def start_keyword(self, name, attributes):
        self._print(
            "START KEYWORD", name, attributes["lineno"], self._get_source(attributes)
        )
        self.level += 1

    def end_keyword(self, name, attributes):
        self.level -= 1
        self._print("END KEYWORD", name, self._get_source(attributes))

    def _print(self, *args):
        print("   " * self.level, *args)


def main():
    from robot import run_cli

    robot_args = [
        "--listener=__main__.V2Listener",
        "<XXX_PATH_TO_SAMPLE_FILE>",
    ]
    run_cli(robot_args, exit=False)


if __name__ == "__main__":
    main()
```

**Comment by pekkaklarck** [comment]
Have you tested this with beta 3? It wasn't until that when adding source information (#3538) was finalized. It would be awesome if you could test this now so that we'd know does this important API work properly.

In your description you referred to `start_test` but I assume you mean `start_keyword`? Notice that the former also was enhanced in beta 3 and it now gets `source` as well (#3856).

**Comment by pekkaklarck** [comment]
After re-reading the description I noticed one thing that probably doesn't work as you'd like: reporting keywords that are not executed. After #3842 we show keywords that are un-executed due to earlier failures _or_ because they are in an un-executed IF/ELSE branch in the log file. I consider that a great enhancement, but I'm not sure is it a good idea to pass information about these keywords to listeners as well. In the `end_keyword` call you can see that their status is `NOT RUN`, but that's obviously too late if you do something already in `start_keyword`. What we could do:

1. Nothing. There shouldn't even be a situation where you have nested keywords with `NOT RUN` status so it ought to be possible to delay any action now done in `start_keyword` until you see is the next call `start_keyword` (earlier keyword cannot have `NOT RUN` status) or `end_keyword` (you can see status directly). This is obviously not too convenient.
2. Don't pass any information about un-executed keywords, IF/ELSE branches, etc. to listeners. Fixes this particular problem but other listeners might be interested in this info.
3. Pass some information in `start_keyword` to tell this keyword isn't really run. We could, for example, pass `status` also then so that it would have either value `NOT SET` or `NOT RUN`. Could also just add new `notrun` attribute if the keyword isn't executed. Regardless how this would be done, listeners not interested in un-executed steps could easily ignore them while those interested in this info would get it.

**Comment by fabioz** [comment]
I just tested with the current master.

It seems that the source is now available, so, that part of the issue is fixed ;)

So, what's missing as you noticed is knowing that a keyword won't be executed at `start_keyword`. Both `2.` and `3.` work for me (as a note, for `3.`, I think that the same flag should also be passed to `end_keyword`).

p.s.: I don't think `1.` is an option as the debugger needs to stop the execution before the keyword is evaluated. i.e.: Waiting for the next `start_keyword` isn't really possible.

**Comment by pekkaklarck** [comment]
Ok, let's try to go with option 3. Do you see any downsides with using `status` for this information? In `start_keyword` it would either be `NOT SET` or `NOT RUN` and in `end_keyword` it would work as it does now?

**Comment by pekkaklarck** [comment]
I'll go skiing with my kid now but, assuming we can agree on the design, I might have time to look at this later in the evening.

**Comment by fabioz** [comment]
Having it as `status=NOT RUN`  both in `start_keyword` and `end_keyword` does work for me.

Happy skiing ;)

**Comment by pekkaklarck** [comment]
`start_keyword` now gets status and it's either `NOT SET` or `NOT RUN`. Let me know how it works and also if there are more problems! Right now before the first release candidate making this kind of changes is easy.

**Comment by boakley** [comment]
This sounds confusing. Are you saying that the status of a keyword that is about to be run will be "NOT SET"? Wouldn't a value of None or an empty string work just as well? Otherwise, "PENDING" seems like a better value than "NOT SET" since it gives a clue as to why the value isn't set.

**Comment by pekkaklarck** [comment]
I would expect that 99.8% `attrs['status']` is compared to `'NOT RUN'` so the other value doesn't really matter. That said, I prefer something more explicit than an empty string or `None`. `'PENDING'` would be ok but I don't think it's reallybetter than `'NOT SET'`.

**Comment by boakley** [comment]
I agree the wording doesn't matter much, but "NOT SET" doesn't seem to make
any sense at all. Keywords aren't "set", so I'm not even sure what "NOT
SET" is supposed to mean.

<shrug>

**Comment by pekkaklarck** [comment]
In this context `NOT SET` means that the status is not set. I'm fine it being changed to `PENDING` if someone creates a PR.
