### ISSUE TITLE
AttributeError: 'keywords' attribute is read-only and deprecated since Robot Framework 4.0. Use 'body', 'setup' or 'teardown' instead.

### ISSUE THREAD

**Issue by hattaagung** [robotframework/robotframework#3886]
Hi,

What is new structure on Robot Framework 4.0 ?

/usr/local/lib/python3.8/site-packages/pandas/compat/__init__.py:97: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)
/usr/local/lib/python3.8/site-packages/robot/model/keyword.py:97: UserWarning: 'keywords' attribute is read-only and deprecated since Robot Framework 4.0. Use 'body', 'setup' or 'teardown' instead.
  warnings.warn(self.deprecation_message, UserWarning)
[ ERROR ] Calling method '_start_suite' of listener 'DataDriver' failed: AttributeError: 'keywords' attribute is read-only and deprecated since Robot Framework 4.0. Use 'body', 'setup' or 'teardown' instead.

May simulator is failed now if upgrade robot framework.

**Comment by sridharvpmca** [comment]
Please refer the below issue for additional details
https://github.com/robotframework/robotframework/issues/3868

**Comment by pekkaklarck** [comment]
This problem is due to changes to models explained in the release notes:
https://github.com/robotframework/robotframework/blob/master/doc/releasenotes/rf-4.0.rst#running-and-result-models-have-been-changed

The aforementioned #3868 is a variation of the same problem and #3749 explains the changes in detail.

You mentioned DataDriver in the description and it was broken due to these changes. There's now DataDriver preview release that ought to work and I would expect that the final version will be released soon as well.
