### ISSUE TITLE
Visitor and listener interfaces can only access top level keywords

### ISSUE THREAD

**Issue by nicolae-chedea** [robotframework/robotframework#3887]
Problem:
If I use a class that implements SuiteVisitor class and visit_keyword method kw.keywords always comes back as an empty list:
`    def visit_keyword(self, kw):
        print(kw.keywords)`

visit_suite or start_suite behave similarly - they only return the top level keywords for the suites.
Same issue with listener interface with the start_suite method with ROBOT_LISTENER_API_VERSION = 3

Suggestions:
- return at least the first level of depth for keywords. Right now if I create a --prerunmodifier script for keywords it has no effect for keywords with multiple layers - anything that is in a robot resource file for example.
- add one more parameter so the user can choose how deep the script will go
- if any of the above suggestions would not be ok, at least remove the keywords attribute from the keyword class - I can't find a scenario where it could be used right now.

**Comment by pekkaklarck** [comment]
You mentioned using `--prerunmodifier` so I assume you are visiting the data model, not the result model. On the data model keywords don't have any child keywords simply because resolving keywords only occurs during execution. Because of this having `keywords` and `messages` attributes on the data model made no sense and, as you suggested, they were removed in RF 4.0 as part of #3749.

On the result side keywords can have child keywords and there you can access them using a visitor. Notice that RF 4.0 ( #3749) changed `keywords` to `body`, though, and that `body` nowadays also contains messages.
