### ISSUE TITLE
Using `BuiltIn().run_keyword` in listener `start/end_suite` method creates invalid output.xml

### ISSUE THREAD

**Issue by tgoncuoglu** [robotframework/robotframework#3893]
In our system we use a listener class, in which we use several BuiltIn().run_keyword() calls. In versions prior to 4.0, ie 3.2.2, this worked nicely and gave no error. In version 4.0 however, even though the run_keyword() calls succeed and relevant test gets a PASS status we get an error at the bottom of console report:

`[ ERROR ] Reading XML source '/folder/output.xml' failed: AttributeError: 'TestSuite' object has no attribute 'body'`

I feel this is related to the recent <body> tag change of output.xml file. Here is a quick demonstration:

test.robot

```
*** Test Cases ***

NOOP
    Log  Do Nothing.
```

ListenerClass.py
```
from robot.libraries.BuiltIn import BuiltIn

class ListenerClass(object):
    ROBOT_LISTENER_API_VERSION = 3

    def start_suite(self, suite, result):
        BuiltIn().run_keyword("Log", "this is a test", "console=True")
```

When this is run with the command: 
`robot --listener ListenerClass.py test.robot`

The output will be:
```
==============================================================================
Test                                                                          
==============================================================================
this is a test
NOOP                                                                  | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Output:  /home/tuncay/bugdemo/output.xml
[ ERROR ] Reading XML source '/home/tuncay/bugdemo/output.xml' failed: AttributeError: 'TestSuite' object has no attribute 'body'

Try --help for usage information.
```

Note the ERROR on the bottom.

**Comment by pekkaklarck** [comment]
This looks like the same problem @Snooz82 reported with DataDriver. He was able to workaround it with a pretty ugly hack that he possibly can share. Needs to be fixed in RF 4.0.1 anyway.

**Comment by Snooz82** [comment]
Hi Peke,

yes, that is exactly the same issue.
Calling run_keyword on suite start causes a "non-setup/teardown" keyword.

the ugly fix is, to "mute" the StatusReporter...
So it kind of saves the methods of StatusReporter replaces them with empty ones, calls the keyword and replaces the empty ones with the original again.

that does cause that your Keyword does not appear in the logs at all.



```python
class DummyStatusReporter:

    def __init__(self, data, result, context, run=True):
        pass

    def __enter__(self):
        return self

    def __exit__(self, exc_type, exc_val, exc_tb):
        pass
        
        
def _run_silent_keyword(self, name, *args):
        if self._is_new_model():
            from robot.running.statusreporter import StatusReporter
            org__init__ = StatusReporter.__init__
            org__enter__ = StatusReporter.__enter__
            org__exit__ = StatusReporter.__exit__
            StatusReporter.__init__ = DummyStatusReporter.__init__
            StatusReporter.__enter__ = DummyStatusReporter.__enter__
            StatusReporter.__exit__ = DummyStatusReporter.__exit__
        result = BuiltIn().run_keyword(name, *args)
        if self._is_new_model():
            StatusReporter.__init__ = org__init__
            StatusReporter.__enter__ = org__enter__
            StatusReporter.__exit__ = org__exit__
        return result

def _is_new_model(self):
        return hasattr(self.template_test, "body")


```

**Comment by pekkaklarck** [comment]
This problem occurs because `BuiltIn().run_keyword` used in `start_suite` or `end_suite` creates a `<kw>` element directly inside `<suite>` and nowadays (#3749) we accept only setups and teardows on that level. Setups and teardows are also `<kw>` elements, but they have `type` attribute set accordingly and are thus handled differently than normal keywords. During parsing normal keywords are written to `result.body`, but nowadays suites have no `body` which causes the AttributeError.

My plan to handle this special situation is as follows:
1. If we encounter `<kw>` in suite before any tests, add it into setup, otherwise add it into teardown.
2. If setup/teardown doesn't already exist, create one automatically and add the keyword or keywords into its body.
3. If we later encounter a real setup/teardown, let it reset name and other info we have set to the implicit setup/teardown. Actual keywords we've added to its body will be preserved.

How does the above sound @Snooz82 and others? I have a prototype implementation already ready so I know it works. Still need to add real tests before committing the fix, though.
