### ISSUE TITLE
is there any plan to support go?

### ISSUE THREAD

**Issue by caibinxian** [robotframework/robotframework#3900]
wondering if keyword/library development has any plan to support golang?

**Comment by pekkaklarck** [comment]
There are two possibilities:
- Call go from Python. That ought to be possible at least using ctypes, but there could also be easier solutions. In the best case it could be possible to create some kind of a generic wrapper.
- Use [Remote interface](https://github.com/robotframework/RemoteInterface). I'm not aware of any go remote server but creating one shouldn't be too complicated.

Neither of the above are something that are related to Robot Framework core so I close this issue here.
