### ISSUE TITLE
Support `IntEnum` and `IntFlag` in automatic argument conversion

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#3910]
Hi,

I experienced a strange behavior and would assume it is a bug in type conversion ...

When using RF 3.2.2 or 4.0.0 with a python keyword that has an IntEnum as arguments type hint it is not possible to use the enums member name.

Like 
```python
class PowerState(IntEnum):
    On = 0
    Off = 1
```

Rf does document that enum.

When i call that keyword with On it complains, that "On" can not be converted to int...

When i change the enum type to Enum it works. But i am loosing advantage/functionality of IntEnum... 

has to be tested with `IntFlags` and other Enum types as well...

Cheers

**Comment by pekkaklarck** [comment]
My guess is that our argument type detection considers `IntEnum` to be `int`, not `Enum`. Considering it only `Enum` probably would be good either and would be backwards incompatible. I guess there should be special handling for this type so that we try both conversions. Shouldn't be too hard to implement, but as a new feature needs to wait for RF 4.1.

**Comment by pekkaklarck** [comment]
Interested to take a look at this @Snooz82? If not, anyone else interested? I can help getting started if needed.

**Comment by pekkaklarck** [comment]
I think IntEnums should, for most parts, work like normal enums. For example, string `On` should be converted to `PowerState.On` with the example in the description. We probably should handle also integers somehow, though. For example, `1` either as a string or as an integer could also be converted to `PowerState.On` with the example above. That would be a bit inconsistent with normal enums because with them we don't do conversion based on values, but in this context values actually are meaningful and handling them specially is probably a good idea.

If we handle integers like proposed above, we needed to decide what to do if an integer matches multiple values. We could make that an error, but because using same value with enums basically means that values are aliases I'd prefer just returning the first match.

**Comment by pekkaklarck** [comment]
The description pointed out that we need to test also with IntFlag and other special enums. That's certainly true, but possible enhancement related to other enums should get their own issues.

**Comment by pekkaklarck** [comment]
I fixed the original reported problem in the commit above. Still need to add a note to the User Guide about IntEnum support and it would also be good to test IntFlag and other special enums. I would expect them to work now after the above fix.

**Comment by pekkaklarck** [comment]
I started to look at supporting integers with IntEnum so that both `1` and `${1}` would be same as `Off` with the example in the description. The code now mostly works, but due to some corner cases it's big ugly and needs to be cleaned up before committing.

I also started to think should we support enums based on values in general. For example, if I had an enum like
```python
class X(Enum):
    x = 'xxx'
```
we could allow using it with `xxx` (matches value) in addition to `x` (matches name). If name matching has precedence and value matching is attempted only if there are no matches, this ought to be backwards compatible. It would also make it easier to handle integers with IntEnums simply because that's anyway value matching.

Although matching by value shouldn't cause problems and would be easy to implement (if we support integers with IntEnums), I'm still somewhat worried it would be confusing. We basically have three alternatives:

1. No conversion based on value whatsoever, not even with IntEnums.
2. Support IntEnums with values but not normal enums.
3. Support values with all enums.

I'm currently thinking going with option 2 would be best. In that case it can be implemented as part of this issues. Support for values with all enums would need a separate issue.

What do others think about this? Please comment here or on the #devel channel on our Slack where I'll also ask about this.

**Comment by pekkaklarck** [comment]
A big benefit of supporting also integer values with IntEnums is that it would allow changing type hints like `def example(arg: int)` to `def example(arg: PowerState)` without requiring updating all usages like `Example  1` to `Example  Off`. In some cases seeing the integer value could also be beneficial otherwise.

There wouldn't be that much benefits with supporting values with enums. If you have, for example, `def move(arg: str)` that actually only accepts strings `LEFT` and `RIGHT` as arguments, it could be changed to `def move(arg: Direction)` where `Direction` is an enumeration with `LEFT` and `RIGHT` as members without needing to change usages like `Move  LEFT` at all.

**Comment by pekkaklarck** [comment]
Above commits do the following:
- Implement conversion based on values with integer based enums (IntEnum and IntFlag) but not with others.
- Add explicit tests for Flag and IntFlag. The former worked already with earlier releases but the latter needed the fix that was already done as part of this issue.
- Document IntEnum and IntFlag support in the User Guide.
- Test that Libdoc handles IntEnum. No code changes were needed.

I would say this issue is done.
