### ISSUE TITLE
`--exitonfailure` mode is not initiated if test is failed by listener

### ISSUE THREAD

**Issue by VishnuMNair** [robotframework/robotframework#3973]
HI,

I'm having a scenario where I have to check some hardware states after test is completed, I'm doing this in listener. if the status of hardware is not satisfactory I will mark the test as failed from listener itself. this gets tricky when they use --exitonfailure with robot run command. execution still continues even though the last test failed. is there a way around this?

```resp = listener_ext.post_condition(str(data.name), result.status)
  if resp:
      try:
          result.status = 'FAIL'
          cores = ' '.join([x.strip() for x in resp])
          result.message += f'\nFailed from listener:\n {cores}'
      except Exception as e:
          logger.info('setting result failed:' + str(e))
```

even though test status is made fail, execution continues.

**Comment by pekkaklarck** [comment]
I can reproduce the problem. Apparently the exit-on-failure functionality only checks the test status after it has been run and possible status change by listener isn't taken into account. I hope we can change this in RF 4.1. Alternatively we could try to come up with a way to listeners to stop execution gracefully otherwise.
