### ISSUE TITLE
skipteardownonexit does not skip all teardowns on skip exception

### ISSUE THREAD

**Issue by jcdevil** [robotframework/robotframework#3980]
**Environment :** 
- OS : MacOS BigSur 11.3
- Python 3.9.4
- RobotFramework 4.0.2

**Description of the issue**
In the test below, 
```
*** Settings ***
Suite Setup     Run Keywords  Log  this suite setup message should be logged  AND  skip
Suite Teardown  Log  this suite teardown message should not be logged

*** Test Cases ***
Testing_that_when_setup_is_skipped_and_skipteardownonexit_is_enabled_then_teardown_is_not_played
    [Setup]  Log  this test setup message should not be logged
    Log  this test message should not be logged
    [Teardown]  Log  this test teardown message should not be logged
```

when the test is launched with this command line :

```
robot --skipteardownonexit skip_during_setup.robot
```

**Current behaviour**
The Suite teardown is indeed played, as shown in the report/log : 

![image](https://user-images.githubusercontent.com/2634872/119136440-f1f4f280-ba3f-11eb-8c23-2ae2964994f9.png)

**Expected behaviour**
I would expect neither the teardown of the Test, nor the teardown of the Suite to be played, because the documentation states 
```
Handling teardowns
By default teardowns of the tests and suites that have been started are executed even if the test execution is stopped using one of the methods above. This allows clean-up activities to be run regardless how execution ends.
It is also possible to skip teardowns when execution is stopped by using --skipteardownonexit option. This can be useful if, for example, clean-up tasks take a lot of time.
```

Please let me know what you think about this behaviour.
Thx

**Comment by pekkaklarck** [comment]
Although the `--skipteardownonexit` option has word "skip" in it, it isn't actually related the new(ish) skip functionality. It only affects the situation where the whole execution is stopped prematurely (but gracefully). The documentation that you referred is part of the [Stopping test execution gracefully](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#id757) section and "one of the methods above" refers to pressing Ctrl-C, using `--exitonerror`, or otherwise stopping the whole execution.

**Comment by pekkaklarck** [comment]
Could you clarify your use case? Perhaps there's some other feature that could be used to accomplish what you want or perhaps we can find a way how RF could be enhanced to support it.

**Comment by jcdevil** [comment]
Thanks for your reply.

**Here is some more context to explain my use case**.
While entering suite setup, I first check the version of my product, using some custom python code.
Depending on the version I get, I'd like
- either to go on, executing the rest of the setup, the tests and the teardown => expecting tests to have status in (PASS, FAIL)
- or to skip the whole suite (ie skipping the rest of setup, the tests and the teardown) => expecting tests to have the status SKIP

**Current implementation - leading to creation of this issue**
Scenario with suite that should not be played because not relevant for the current version of the product under test :

During setup, a custom exception is raised, as described here : https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#skipping-tests
In that case, the rest of the setup and the tests are skipped. That's fine !
But I then noticed that the teardown is however performed.
I then looked for a way to skip teardown, and expected that using `--skipteardownonexit` could do it, thinking that "skip" was indeed a kind of graceful exit.
Unfortunately, I know understand it is not the case.

Do you see any way to achieve this ATM or does it require a new development ?
Thx for your help !

**Comment by pekkaklarck** [comment]
Ok, now I understand your need: when you skip the suite in its setup, you wouldn't want its teardown to be run. I can see this behavior would often be desired, but I don't think it could be the default because in some other cases it can be important to run the teardown. Somehow making it easily configurable would be nice, but, as discussed above, `--skipteardownonexit` is not the right solution.

What actually works already now is running the teardown only if built-in variable `${SUITE STATUS}` is not `SKIP`. If you want to run some parts of the teardown always, you could use the new `IF/ELSE` structure to avoid running other parts when skipping:

```robotframework
*** Settings ***
Suite Teardown    Teardown keyword

**** Keywords ***
Teardown keyword
    IF    "${SUITE STATUS}" != "SKIP"
        Log    Executed only when not skipping
    END
    Log    Executed always.
```

If you want to avoid running the whole teardown when skipping, it's probably easier to use `Run Keyword If`:

```robotframework
*** Settings ***
Suite Teardown    Run Keyword If    "${SUITE STATUS}" != "SKIP"
...               Teardown keyword

**** Keywords ***
Teardown keyword
    Log    Executed only when not skipping
```

Do you @jcdevil think we should have some move convenient way to control this behavior or are the alternative above enough? If they aren't, what new approach would you propose?

**Comment by jcdevil** [comment]
👍 Thx for your feedback @pekkaklarck.
I'm currently testing your approach, using the current suite status in our python custom code :
```
BuiltIn().get_variable_value('${SUITE_STATUS}', default=default)
```
depending on the returned value (`SKIP`) or not, I may run our suite teardown.
NB : so far, I only need this feature at suite level, and not test level.
... and anyway, your approach allows to work that way for either suites or tests ;)

I will write a comment in few days to let you know if this issue can then be closed from my POV.

**Comment by jcdevil** [comment]
OK then: 👍 everything works fine with that @pekkaklarck.
This issue can be closed ! Thx for your help !
