### ISSUE TITLE
Should __init__.robot be loaded when running .robot in the same folder?

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#3982]
I'm creating this due to the following report on the language server:

https://github.com/robocorp/robotframework-lsp/issues/355

So, I'd like to know if this is a bug (in that the `__init__.robot` really shouldn't be run when a file in the same folder is executed) or not... (and if it's not a bug, would it make sense to actually support that?)

**Comment by pekkaklarck** [comment]
Do I get it right that you mean a situation where you have files like
```
root/
├─ __init__.robot
├─ tests.robot
```
and you run tests like `robot root/tests.robot` (or just `robot tests.robot`, depending on your cwd)?

In this case not parsing `__init__.robot` is by design and not likely to change. There are several reasons for this design and why I wouldn't like to change it:

- It's unclear where documentation, setup/teardown, etc. defined in the `__init__.robot` file should go in the generated model. They cannot really go to the suite generated from the `tests.robot` file because it can have all same information itself and that shouldn't be overridden. Basically we needed to create new root suite from the `root` folder and add this information into it.
- There's already a way to run only the `tests.robot` file so that `__init__.robot` is parsed: `robot --suite tests root`. This approach explicitly creates a root suite from the `root` folder. No special cases needed.
- There could be `__init__.robot` files also on higher level parent folders. Scanning for them doesn't sound like a great idea, but for consistency reasons that should probably be done if we parse the file in the same directory.
- The change would be backwards incompatible.

**Comment by fabioz** [comment]
Ok, I think that running it as `robot --suite tests root` should work for me, so, I'm closing this (I'll change the language server to do that instead of just running the file).
