### ISSUE TITLE
Enhancement Request: Add optional message argument to Return From Keyword and Return From Keyword If

### ISSUE THREAD

**Issue by sparkymartin** [robotframework/robotframework#3986]
I think it would be useful if the Return From Keyword and Return From Keyword If keywords from the BuiltIn library had an optional message argument that one could specify their own custom message as to why the return from keyword is happening. I am finding myself having to add extra keyword calls to support this kind of behavior when I think it should just be built in. Also, it is basically impossible to do with Return From Keyword If, so in that case, I have to use a native IF statement to check my condition and then if the condition is met, do a logging statement and then make a call to Return From Keyword.

**Comment by pekkaklarck** [comment]
This is pretty impossible to implement because this keyword accepts unlimited number of positional arguments:

**Comment by pekkaklarck** [comment]
At the moment returning from a user keyword is a mess because we have `[Return]` setting and `Return From Keyword` and its variants. I've been thinking we should introduce separate `RETURN` statement that could be used like:

```
*** Keywords ***
Example
    ${x} =    Do something
    IF    ${x} > 0
        RETURN    ${x} is positive
    END
    RETURN    ${x} is negative
```

Then later, after a long deprecation period, we could remove both `[Return]` and all `Return From Keyword` variants. If decide to do that, then enhancements to `Return From Keyword` don't really make sense in general.

**Comment by sparkymartin** [comment]
This makes sense Pekka. Thanks for the response.

**Comment by pekkaklarck** [comment]
Ok, let's not add this. Let's add `RETURN` sometime in the future, hopefully somewhat near future, instead.
