### ISSUE TITLE
Skipped tests will have fail status if suite teardown fails

### ISSUE THREAD

**Issue by MininAS** [robotframework/robotframework#3994]
Robot Framework 4.0.3 (Python 3.6.8 on win32)

```
*** Settings ***
Documentation      ...

Library            SeleniumLibrary

Suite Setup        Suite Setup
Suite Teardown     Suite Teardown
Force Tags         example    noncritical

*** Variables ***

*** Test cases ***
Test Cases
    Wait Until Page Contains Element    css:img[alt="Google"]
    Page Should Contain Element         css:img[alt="Gogle"]    #non correct selector intentionally

*** Keywords ***
Suite Setup
    Open Browser    https://google.com    chrome

Suite Teardown
    No existed keyword    #non correct keywordintentionally
    Close All Browsers
```
command line: `robot --skiponfailure noncritical example.robot`

Expected result some thing like this:
![image](https://user-images.githubusercontent.com/48047242/120463652-cc9fa700-c3a4-11eb-813d-0cfad7269618.png)

Really:
![image](https://user-images.githubusercontent.com/48047242/120462632-c78e2800-c3a3-11eb-9a59-c7ae2c07ff41.png)

**Comment by MininAS** [comment]
It may also be worth revising the logic when tests are PASS and teardown is fail.

**Comment by pekkaklarck** [comment]
What to do with skipped tests if a suite teardown fails probably wasn't thought at all when the skip functionality was designed. Failing test teardowns don't change skip status to fail, so it would be logical to handle suite teardowns the same way.

Passed tests being marked failed if suite teardown fails is by design and won't change.

**Comment by MininAS** [comment]
> Passed tests being marked failed if suite teardown fails is by design and won't change.

Sorry, what is positive in that design? In my point of view - suite teardown should not impact to test cases state. What teardown does -  performs some steps for clear testing environment and sets it to default state, may be to create some custom report. Also the teardown is executed after all test cases.
Examples of not comfortable points when all test cases were fail because suite teardown was fail:
 - suite test cases are PASS and situation don't have relation to them (if suite teardown was fail by some outside reason(web testing - browser was closed during ))
 - when we try to findout reason of fail - one of all fail test cases is real reason of fail -  but all test cases look like are fail -  it can hide bug.

Thanks. In any case it my vision of behavior.

**Comment by pekkaklarck** [comment]
If we'd leave tests passed after suite teardown failure, there would be no indication in report about that failure. This could mean that serious problems aren't detected. We obviously could enhance report so that suite teardown failure is reported separately, but I don't thing that's worth the effort and all tests passing could nevertheless mean that the problem is ignored. For wider discussion see #2135.

As discussed in the aforementioned issue, you can wrap the teardown keyword with "Run Keyword And Ignore Error" or with "Run Keyword And Warn On Failure". The latter was actually added partly with this use case in mind (#2294).

**Comment by MininAS** [comment]
I got, thank you. In any case we should know if a suite teardown is fail and see it in report and test statistic table! Doing is in that
 > We obviously could enhance report so that suite teardown failure is reported separately
Yep, I think it is needed :)

May be add some tail to suite progress line 
![image](https://user-images.githubusercontent.com/48047242/120779982-5039cf00-c530-11eb-95c9-a59f73e8e68b.png)
or paint border to red color
![image](https://user-images.githubusercontent.com/48047242/120780124-6cd60700-c530-11eb-8bb5-0c604965d206.png)

It would may to keep real passed test cases statistic

    just thoughts out loud :)

**Comment by pekkaklarck** [comment]
Failing suite teardowns are such a special case that I don't think handling them differently than now is worth the effort. Most importantly, it would be hard to come up with mechanism that would leave tests passed but would make it _explicit_ for users that there is a problem to be fixed. Anyway, discussing about that doesn't belong to this issue. If you think that behavior should be changed, submit a new issue or start discussion on our Slack.
