### ISSUE TITLE
Robot Framework test runs Hangs while run from jenkins and from local machine as well.

### ISSUE THREAD

**Issue by mn431** [robotframework/robotframework#4001]
Hi,

My Robot Framework tests occasionally get stuck waiting for a element to interact with browser page, which causes the tests to hang indefinitely at times. In most of these cases I am experiencing, the browser has loaded 99% of the content and can be interacted with just fine. 

When I have watched the automation tests run and encounter this browser hanging issue, if I manually press anywhere on the browser the automation tests resume as normal. I tried giving TIMEOUT, reducing selenium speed but none of it worked.

Environment :-
robotframework                 3.1.2
selenium                             3.141.0

Any help would be greatly appreciated.

Thank you,
Madhu.

**Comment by pekkaklarck** [comment]
Hard to tell where the problem is without actually running and debugging tests on your environment. It is, however, _very_ unlikely that this kind of problem would be caused by Robot Framework itself. This issue tracker is for bug reports and concrete enhancement requests related to Robot Framework, and I got a feeling you are mainly looking for help investigating your problem. For that kind of purposes we have dedicated forums like a mailing list and Slack that you can find via robotframework.org.
