### ISSUE TITLE
Create top level documentation from external file

### ISSUE THREAD

**Issue by lesnake** [robotframework/robotframework#4008]
I would like to add documentation using -D --doc argument followed with a file rather than a string of text, like
`(rebot|robot) --doc topleveldoc.txt other args`

The content of that file shall be any argument of `--doc `option

This issue replaces the issue #3983.

**Comment by pekkaklarck** [comment]
Sounds good to me. We already have #3860 about making it possible to provide multiline documentation from the command line, but being able to read it from a file would often be even more convenient.

**Comment by pekkaklarck** [comment]
I closed #3860 due to backwards incompatibility problems, it not providing too much benefits, and this issue helping with the same problem in more convenient way. That issue covered both `--doc` and `--metadata` while this issue so far concentrates only on the former, though. We need to extend this issue to cover also the latter.

The problem with reading value from a file when using something like `--metadata example:c:\example.txt` is that the user may want to use `c:\example.txt` as the actual value. That's obviously true also with `--doc c:\example.txt`, but having only a path as a documentation sounds *very* unlikely. With metadata such usage is possible and we need to figure out how to make it possible. Some ideas:
- We should read the value from a file only if the value points to an existing file. If the path doesn't exist, we should just it as the value as-is. This approach easies error handling in general.

**Comment by lesnake** [comment]
How about adding a `--doc-file` and `--metadata-file` arguments ?
`--metadata c:\example.txt` continues working like it already does :  set the meta data `c` to `\example.txt`
`--metadata-file c:\example.txt` would set all meta data contained into file `c:\example.txt`
`--doc` continues working like it already does.
`--doc-file c:\example.txt` would use all the content of `c:\example.txt` file as documentation
In any `-file` use-case, if the file does not exist, an error should be returned.

I think that this would:
- not require risky deduction on the value read (is it a file name ? does it exist ?)
- don't change existing `--doc` and `--metadata` option description
- new arguments documentation simpler to read without bloating the CLI.

**Comment by pekkaklarck** [comment]
I don't think adding new options is worth the effort.
