### ISSUE TITLE
ResultVisitor losing tests criticality info

### ISSUE THREAD

**Issue by VishnuMNair** [robotframework/robotframework#4018]
Facing issue when I load existing output.xml with a result visitor. I want to make some changes to the test comments. After my changes I can see all my non-critical tests are critical.
```
    result = ExecutionResult(paths[2], include_keywords=True)
    result.visit(ExecutionResultScrap()) # also tried with commenting out this portion
    result.save(paths[2])
    writer = ResultWriter(paths[2])
    writer.write_results(log=paths[0])
    temp_path, name = os.path.split(paths[0])

```
I tried without making any changes, just loading and saving the file back. I could see the issue still persisting.
HTML data seq before loading with visitor:
`window.output["suite"] = [1,2,3,0,[],[1,0,76],[],[[4,0,0,5,[6,7],[0,73,2,8],[[0,9,10,0,11,8,0,0,[0,74,1],[],[[75,5,8]]]]]],[],[1,0,0,0]];`
HTML data seq after saving with visitor:
`window.output["suite"] = [1,2,3,0,[],[0,0,76],[],[[4,0,1,5,[6,7],[0,73,2,8],[[0,9,10,0,11,8,0,0,[0,74,1],[],[[75,5,8]]]]]],[],[1,0,1,0]];`

Thanks in advance for the help.

**Comment by pekkaklarck** [comment]
Dropping criticality information when results were read was by design. The reason was that otherwise handling multiple output files with different criticality configuration would have been too complicated. What you need to do is to call `result.suite.set_criticality()` and specify what tags to consider critical and/or non-critical.

Notice that the whole criticality concept was removed in RF 4.0. It won't thus be changed even if we'd agree this functionality wasn't good.
