### ISSUE TITLE
Report all related errors in one go

### ISSUE THREAD

**Issue by stdedos** [robotframework/robotframework#4022]
I have an old test case, which I am trying to "bash in" until it runs successfully.

I am dealing with an error right now that goes along the lines of:

> Resolving argument default values failed: Variable '${x}' not found

Then, after fixing that, I am getting:

> Resolving argument default values failed: Variable '${y}' not found

... and so on and so forth.

Is it possible that, all of "these" errors present themselves at once?

In a trivial robot case, running `robot suite/` can be short, but there are cases where that is not the case (e.g. my cycle right now is about 5 minutes long).

**Comment by pekkaklarck** [comment]
It's pretty much impossible to know which errors are related and should be reported together. The main problem being that we cannot know after one failure is there going to be another soon.

The recently implemented issue #2285 makes it possible to explicitly tell that execution can continue after a failure. I'm actually not sure how it works with errors related to argument default values, but that can possibly be fine-tuned later if needed. Let's anyway see how that enhancement works in practice when RF 4.1 is out.

**Comment by stdedos** [comment]
For this case, the problem is it tries to resolve arguments for ~30 variables (I know, bear with me) - and the "problem" is that the "resolution manager" just `raise`s after the first value.

_In this specific case_, it would've been nicer if the "resolution manager" would instead try to resolve all variables, appending the failed ones, and then raise all at once.

But I see where you are coming from, so I am not going to push further.

**Comment by pekkaklarck** [comment]
Yeah, it would be possible to handle multiple errors in limited scopes. For example, when parsing arguments, we could go through all arguments before raising an error. I closed this issue because _in general_ reporting related errors isn't possible and because #2285 already enhances this situation. Separate issues (and PRs) could be submitted for reporting all errors in specific cases like this one.

**Comment by stdedos** [comment]
I am a bit at a loss here: You'd consider having a new issue for this 

> For this case, the problem is it tries to resolve arguments for ~30 variables (I know, bear with me) - and the "problem" is that the "resolution manager" just `raise`s after the first value.
> 
> _In this specific case_, it would've been nicer if the "resolution manager" would instead try to resolve all variables, appending the failed ones, and then raise all at once.

but you closed (and want to keep closed, I assume) this one, as an example that in general, "Report all related errors in one go" is too broad and upcoming 4.1 has #2285 coming.

Am I right?

I mean, unfortunately, I think I would open the issue and leave it stale (if it picks up steam in the community), as my FOSS coding this year is at an all-time low.

**Comment by pekkaklarck** [comment]
I closed this issue because "Report all related errors in one go" is way too broad. The description is more detailed so instead of opening a new issue the title could be updated and this issue re-opened.

Incidentally all syntax problems in user keyword arguments are likely to be reported in one go as part of #3946. The idea of that issue is handling error detection in that particular case already in the parser and thus we already know about all of them when constructing the executable keyword. Same approach is already used, for example, with errors in FOR loops and IF/ELSE blocks. Unfortunately that enhancement won't help with the exact problem in the description because non-existing variables in default values cannot be detected during parsing.
