### ISSUE TITLE
Log generation fails if using `--expandkeywords` and test contains `ELSE` branch

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#4036]
The --expandkeywords do not have support for the new native IF/ELSE syntax:

![grafik](https://user-images.githubusercontent.com/20930315/124711696-af5b7c80-defe-11eb-83ea-5f18348a28a2.png)

**Remark:** In my sample is a missing space in the **ELSE IF True** branch, thus the last **ELSE** branch is taken and **ELSE IF True** becomes a skipped keyword in branch *IF  False*. Due to indentation maybe it's possible to report a parser warning in such a case?

*Versions:*
Windows 10
python 3.9.6
robotframework-pabot 2.0.0
robotframework 4.0.3

**Comment by pekkaklarck** [comment]
Thanks for the report. Just in time before RF 4.1 release candidate planned to be released tomorrow. It seems this bug occurs only when you have `ELSE` branch, not when there's only `IF` or `IF` and `ELSE IF`.

Parser could try detecting invalid usages like `ELSE IF True` where a space is missing, but checking something like this with all keywords/settings/etc. would add lot of code and, more importantly, slow down parsing unnecessarily. I thus don't think that's a good idea, but there are enhancements that could be considered:
1. When a keyword isn't found, check does its name start with `ELSE IF`, `IF` or some other special marker and report such cases separately. Notice that in this case this error wouldn't occur because that `ELSE IF True` "keyword" isn't executed at all. It would nevertheless help in cases where that "keyword" is run, including `--dryrun`, and could be useful. A separate issue should be submitted about it.
2. New external RoboTidy -tool and/or RoboCop -linter could check for errors like this. This would require issues to their respective trackers.
