### ISSUE TITLE
Variables in unexecuted FOR loops overwrite local variables

### ISSUE THREAD

**Issue by MoreFamed** [robotframework/robotframework#4047]
```
*** Test Cases ***
Test
    ${a}  Set Variable  abc
    IF  '${a}' == ''
        FOR  ${a}  IN  def  ghi
            Log  ${a}
        END
    ELSE
        Log To Console  ${a}
    END
```
This test logs ```${a}``` to the console instead of ```abc``` as I would expect. The problem is in reusing variable ```a``` in the FOR-cycle. When I use another variable instead, like ```FOR  ${x} IN ...```, then ```abc``` is written correctly. Seems as a bug to me.

RF v. 4.0 and 4.0.3, Python 3.7.4

**Comment by miktuy** [comment]
@MoreFamed @pekkaklarck Guys! I think I have fixed this problem in https://github.com/robotframework/robotframework/pull/4055

**Comment by miktuy** [comment]
uups. Another tests are broken((((

**Comment by pekkaklarck** [comment]
The reason for the problem is this:
1. We go through keywords and control structures in unexecuted IF branches to get them listed in the log file.
2. When going through FOR loops, we assign variables used in the loop to a dummy value.
3. In the above case variable `${a}` gets overwritten by the dummy value.

Fixing this shouldn't be overly complicated. Alternatives:
- Create a new temporary variable scope for when going through unexecuted FOR loops.
- Don't set variables when going through unexecuted FOR loops. This probably has problems with the log file.
- Restore original variable values after going through unexecuted FOR loops. This is probably the easiest solution but I haven't tested it myself yet.

**Comment by pekkaklarck** [comment]
Turned out creating a temporary variable context was the easiest solution to fix this.
