### ISSUE TITLE
With latest robot framework 4.1 there is increase in execution time where for loop is in place 

### ISSUE THREAD

**Issue by pmishra2605** [robotframework/robotframework#4053]
Execution time of around 135 test cases increased drastically by 4 times . On further debugging , we found out that wherever For loop is used, execution time has increased.

**KW Execution time in RF 4.1**

![image](https://user-images.githubusercontent.com/77602464/128471758-0f0c34a3-f9cc-47cb-b6ba-5ca00e2b346d.png)

**KW Execution time old RF version**

![image](https://user-images.githubusercontent.com/77602464/128471808-414949f9-29c8-4639-aa2b-32808efe95b5.png)

**Comment by pekkaklarck** [comment]
I did some simple tests with for loops and didn't notice any real performance difference between RF 4.1, 4.0.4 and 3.2.2. Could you please create a simple example demonstrating the performance degradation? Something simple that I can easily run locally without installing any external library. Could you also tell what exact RF version you mean with "old RF version"?

**Comment by pmishra2605** [comment]
Hi pekka,

I run below script . latest **4.1** release takes twice  more time  then robot framework 3.0

### 4.1  
### Time Taken : 39 Seconds


```

*** Settings ***
*** Variables ***
*** Test Cases ***
running same test case with multiple time
    [Documentation]   Performance Check
    print the name

*** Keywords ***
print the name
    log  'this will run multiple times with for loop'
    FOR  ${I}  IN RANGE  0  10000
        log to console  ${I}
        ${status}  Run Keyword And Return Status  should be equal as strings  ${I}  9999
    END

```

### 3.0.0
### Time Taken : 20 Seconds
 
```
*** Settings ***
*** Variables ***
*** Test Cases ***
running same test case with multiple time
    [Documentation]   This test case will run multiple times without using any loop or template
    print the name

*** Keywords ***
print the name
    log  'this tc will run multiple times without for loop'
    :FOR  ${I}  IN RANGE  0  10000
    \   log to console  ${I}
	\   ${status}  Run Keyword And Return Status  should be equal as strings  ${I}  9999  
   


```
Hope that helps.

**Comment by pekkaklarck** [comment]
I tested a variation of the above example locally and was able to reproduce performance getting worse. These are average times I got with different versions:

RF 3.0: 6.0 s
RF 3.1: 6.4 s
RF 3.2: 6.8 s
RF 4.0: 7.3 s
RF 4.1: 8.1 s

Somewhat steady decline and surprisingly big drop between RF 4.0 and 4.1. This last drop is especially strange because RF 4.1 was a pretty small release and I don't remember FOR loops being touched much. Could be that there has been some small slow down with keyword execution in general. This example runs tens of thousands of keywords and thus even a small change can cause this kind of difference.

I'll investigate this a bit further by running the example in a profiler. If there's something simple that can be done, I'll do that in RF 4.1.1. If not, possible changes need to wait for later releases.

Notice that if you want better performance, you should try moving the logic from RF side to Python. It can run for loops much faster and your output.xml and log.html sizes won't be so big either.

**Comment by pekkaklarck** [comment]
Profiling didn't reveal anything that would have been easy to fix. I also looked at changes between RF 4.0 and 4.1 and changes related to execution were mostly limited to checking should execution continue after a failure (#2285). I changed the example so that instead of using

    ${status} =    Run Keyword And Return Status    should be equal as strings    ${I}    9999

it uses

    ${status} =    Run Keyword And Return Status    Log    ${I}

where the main difference is that there's no failure. Sure enough that dropped the execution time considerably. After that I rerun the test with different versions:

RF 3.0: 4.2 s
RF 3.1: 4.4 s
RF 4.0: 5.2 s
RF 4.1: 5.1 s

There's still a clear difference between RF 3.0 and 4.1 but it's quite a bit smaller than earlier. More importantly, there's no performance drop after RF 4.0, in fact RF 4.1 is a tiny bit faster.

Due to the biggest problem occurring if there are lot of failures (9999 in the original case), I don't think this issue has high priority. Should definitely look at performance again once we start RF 5.0 development and can do bigger changes. That's especially important after we've drop Python 2 support and can remove lot of code that's not needed anymore.

**Comment by pekkaklarck** [comment]
I don't consider handling failures in RF 4 series being a bit slower than in RF 3 series a big enough problem to keep this issue open. We anyway have #3950 about performance issues. Notice also that memory usage enhancements in RF 4.1.2 may affect performance positively as well.

**Comment by simplyviks** [comment]
![RF-4 1 2-FOR-Performace-Issue-Screenshot 2022-05-13 123837](https://user-images.githubusercontent.com/11870725/168230261-21c673a0-54b3-47ae-969f-aedf98ebc930.jpg)

Definitely there is performance issue overall in 4.1.2 , for which we have a ticket #3950,attaching the screen shot for FOR loop issue here , you can notice the time of each iteration doesnt adds up to overall 32mins , my question is what is the hidden executions that take some time.?
