### ISSUE TITLE
Click "Link To This Keyword" link, the keyword after current focused keyword will be expanded

### ISSUE THREAD

**Issue by dbdlahd1027** [robotframework/robotframework#4057]
[INFO]
Robot Framework 4.1
[Symptom]
Executing robot with --loglevel TRACE, click "Link To This Keyword" and the keyword after it will be expanded.
![image](https://user-images.githubusercontent.com/43832506/128651560-7a2b1dd4-052f-4fb5-af04-c6248a0b9b9f.png)

**Comment by dbdlahd1027** [comment]
The root cause might as same as #4056

**Comment by pekkaklarck** [comment]
As I commented #4056, I can reproduce the issue with keywords getting different internal id when executing tests using the trace level. I first though this issue was about that causing expand/collapse buttons to not work, but after testing this myself noticed that the problem is with the link button instead. Apparently the algorithm for generating the id on Python side when Robot is generating the log file doesn't in that case match the logic on Javascript side when log is actually viewed.

**Comment by pekkaklarck** [comment]
The problem was in generating keyword ids when the parent keyword had both keywords and messages. That's not too common, but happens when running tests with the trace level and also in some other special cases. The bug was introduced when messages and keywords were stored in same lists to allow preserving their order (#2086).
