### ISSUE TITLE
no error when passing wrong type to keyword that takes a bool

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#4060]
```robot
*** Settings ***
Library           Sandpit.foo

*** Test Cases ***
test adsf
    foo   asdfasdf
```
```py
from robot.api import deco

@deco.keyword
def foo(value: bool):
    ...
```

the dry run doesn't pick this up, and at runtime the value doesn't get converted to a bool either:
![image](https://user-images.githubusercontent.com/57028336/129288723-f951897c-e52e-466b-ae14-f548f4d94b82.png)

**Comment by pekkaklarck** [comment]
This is by design and [explained in the User Guide](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#supported-conversions):

> Strings TRUE, YES, ON and 1 are converted to True, the empty string as well as FALSE, NO, OFF and 0 are converted to False, and the string NONE is converted to None. Other strings and all non-string arguments are passed as-is, allowing keywords to handle them specially if needed. All string comparisons are case-insensitive.

I personally consider this design fine and due to backwards compatibility reasons it couldn't really be changed anyway. We have been planning to add support for custom argument converters and that would allow implementing more strict conversions when needed.
