### ISSUE TITLE
variable is still keep when string is start with @ and &

### ISSUE THREAD

**Issue by nixuewei** [robotframework/robotframework#4083]
```
*** Test Cases ***
111
    Set Global Variable    ${aaa}    @123
    log    ${aaa}

222
    log    ${aaa}
    ${type1}    Evaluate    type($aaa)
    Set Global Variable    ${aaa}    @456
    log    ${aaa}
```
${aaa} is still @123 not @456

**Comment by pekkaklarck** [comment]
You actually end up creating variable `@{123}` in the latter case and that's even by design. The reason for this seemingly strange behavior is that Robot replaces the argument `${aaa}` with its value (when it exists) and sets variable based on that.  This is what happens in detail:

1. You create variable so that the name is specified as `${aaa}` and the value is `@123`. No variable `${aaa}` exists so it's created.
2. You again create variable so that the name is specified as `${aaa}`. Now variable `${aaa}` exists and Robot actually tries to create variable `@123`.
3. Setting variable with name `@123` works because in this context it's possible to use variable names without `{` and `}` decoration.
4. If the value of variable `${aaa}` wouldn't start with `$`, `@` or `&`, Robot would notice that the value isn't intended to be variable name and would set `${aaa}` instead.

As you may have already guessed, the workaround is using `$aaa` instead of `${aaa}` with `Set Global Variable`. That's actually not really even a workaround because this is the preferred format. You can read more about that from the keyword documentation.

Although this is a confusing situation, there isn't much we can easily do to help with it. We absolutely need to make it possible to create variables dynamically so that

    Set Global Variable    ${name}    value

sets variable based on what `${name}` actually contains. We could possibly make it so that it's an error to use this syntax when `${name}` doesn't initially exist or when its value isn't a variable itself. It could also just be a warning at least in the beginning. Either way, the change is backwards incompatible.

**Comment by tzmgit** [comment]
I am hitting the same issue with value starting with $:
```
test var
    ${v}=   Set Variable    $abc
    Log     ${v}
    ${v1}=  Get Variable Value    ${v}
    ${v2}=  Get Variable Value    $v
    Log Many  ${v1}  ${v2}
```
result in logs is:
v: ``$abc``
v1: ``None``
v2: ``$abc``

**Comment by pekkaklarck** [comment]
Yeah, what you encountered @tzmgit is a variation of the same issue. It's always safer to use `$var` syntax in this context. I'm starting to think we should actually emit a warning when using `${var}` syntax in these cases. Unfortunately that syntax is likely very widely used and there would be lot of those warnings. Anyway, that would require its own issue. This we can close.
