### ISSUE TITLE
Problem with keyword Write Until Expected Output (Telnet library)

### ISSUE THREAD

**Issue by JoonaMartinkauppi** [robotframework/robotframework#4101]
Keyword is trying to find written text from output, instead of expected. 

Commenting line 828, self.read_until(text, loglevel), seems to fix the problem.

**Comment by pekkaklarck** [comment]
Could you please clarify?

**Comment by JoonaMartinkauppi** [comment]
Sure, sry

Plain robot file for testing keyword:
![code](https://user-images.githubusercontent.com/61461699/135705828-d07e3e07-b73b-430b-a6f7-398a45885dab.png)

Log file after first attempt:
![log1](https://user-images.githubusercontent.com/61461699/135705899-393ab4d7-8756-4a6b-b782-870dcde84933.png)

After commenting line mentioned ealier:
![log2](https://user-images.githubusercontent.com/61461699/135705916-4aca5558-1c9e-4d0e-aa18-4a71c2e40b16.png)

**Comment by pekkaklarck** [comment]
It seems to me that the code tries to first consume output until the initially written text to be able to start to wait for the expected output from a correct place. I can see that if the written text isn't echoed back then this won't work.

I would assume this functionality is there on purpose, but I could be wrong and possibly it could be removed. Doing that in a patch release like RF 4.1.2 certainly isn't safe, though, so this would need to wait for RF 5.0.

This behavior could also be made configurable with an optional argument. Adding an argument like `consume_written_text=True` (shorter argument name would be nicer) ought to be safe and then `consume_written_text=False` could be used in data if this behavior isn't desired. I don't like adding new functionality in a patch release like RF 4.1.2, but features allowing workaround for problems could be accepted. We already made such an exception and added `stdin` argument to Process library keywords (#4065).

If you @JoonaMartinkauppi are interested to create a PR adding an argument to control this behavior I could still merge it before 4.1.2. I don't have time for that myself and you could then also test that the solution works in your environment. In addition to pretty trivial code changes the docs would need to be updated and acceptance tests added. Adding tests is likely the biggest task because it requires setting up test environment. See [atest/README.rst](https://github.com/robotframework/robotframework/blob/master/atest/README.rst) for details about our acceptance test system in general. There you also find a link to details about setting telnet test environment. If you have any questions, you can ask here or on the #devel channel on our Slack.

Notice that I'll create RF 4.1.2 rc 1 today with a plan to release the final version next Monday. We'd thus need the PR pretty soon or otherwise it needs to wait for RF 5.0.

Finally, I'd believe it would be best to move Telnet to be an external library. Then it wouldn't need to be tied to RF release schedule and could also otherwise be developed further freely.

**Comment by pekkaklarck** [comment]
Are you @JoonaMartinkauppi, or anyone else, interested to add `consume_written_text` option to control this behavior? Or do you have other ideas how to fix this?

**Comment by JoonaMartinkauppi** [comment]
> Are you @JoonaMartinkauppi, or anyone else, interested to add `consume_written_text` option to control this behavior? Or do you have other ideas how to fix this?
I´v been pretty busy finishing my studies, it's gonna take at least couple months until I got time for additional projects. However, after I'm done with my thesis and couple other projects, I'll try to find time for this as well.

**Comment by pekkaklarck** [comment]
There hasn't been updates in over two years so I'll close this issue.
