### ISSUE TITLE
Case is skipped status rather than Failed if the main case is skip and [Teardown] fails

### ISSUE THREAD

**Issue by mythure** [robotframework/robotframework#4106]
The following is my case
-------------------------------
```
Test Skip and Teardown
    Log To Console    This is the main Case
    Skip
    [Teardown]    Run Keywords    Fail    AND    Log    Teardown    level=ERROR
```
-------------------------------
In the main case, i skip the case, and then should execute the teardown keyword.
The case status now is Skipped, which i think should be Failed.

Then i run the following case
-------------------------------
```
Test Fail in the Teardown
    Log To Console    This is the main Case
    [Teardown]    Run Keywords    Fail    AND    Log    Teardown    level=ERROR
```
-------------------------------
The case status is failed, if the priority of the Teardown is lower, then this case status should be success.
Or may i say that the priority of Skipped status is higher than Failed or Success Status? 
Thanks

**Comment by pekkaklarck** [comment]
We made a design decision that if you explicitly skip a test, it's status won't change even if teardown fails. Could work the other way as well, but this felt better for us.

This could be changed, but because the change would be backwards incompatible we needed _very_ strong reasons to do so. Do you have some concrete examples where the current behavior causes problems?

This could be made configurable, but I honestly don't believe it is worth the effort.

**Comment by mythure** [comment]
OK I just wanna know this becasue i checked the user guide and didn't get the answer.
Thank you. The RF is great and very useful. Looking forward the RF5.0 Release~
