### ISSUE TITLE
"Get Time" keyword doesn't return accurate time delta if range includes daylight savings change

### ISSUE THREAD

**Issue by chris-from-the-coast** [robotframework/robotframework#4143]
The following test case demonstrates the issue. If `now - <days>` includes a daylight savings change the test will fail.

**Failing test case for 91 days
      ${current_time}=  Get Time  time_=now
      ${past_time}=  Get Time  time_=now - 91 day
      ${time_delta}=  Subtract Date From Date	${current_time}  ${past_time}  verbose
      Should Be Equal  ${time_delta}  91 days**

We expect that `now - 91 day` will equal 91 days exactly but are currently getting 90 days and 23 hours.

Tested on Robot Framework 4.0 and 3.0.2
CPython 3.7
MacOS Catalina

The code to fix this is in robottime.py on line 214 `timetuple = time.localtime(time_)`. This should be changed to `timetuple = time.**_gmtime_**(time_)` to allow for a correct time delta regardless of daylight savings changes.

I'm happy to put in a PR but I'm not sure what the guidelines or flow is. Also, can we still add fixes to 3.x.x releases?

Best,
Chris

**Comment by pekkaklarck** [comment]
I can reproduce the problem and the proposed fix looks good as well. Good news is that although `Get Time` doesn't handle DST correctly, newer `Get Current Date` from the DateTime library works fine. I tested that this example works fine
```robotframework
*** Test Cases ***
Passing test case for 91 days
    ${current_time}=    Get Current Date
    ${past_time}=    Get Current Date    increment=-91 days
    ${time_delta}=    Subtract Date From Date    ${current_time}    ${past_time}    verbose
    Should Be Equal    ${time_delta}    91 days
```

The bug definitely needs to be fixed and it's great that you are interested to provide a PR. We have contribution guidelines that ought to be linked when you, for example, submit an issue that ought to get you started. In this case we just need the actual fix and tests. Not sure what's the best way to test this so that times are guaranteed to be on different sides of the DST boundary. Possibly so that in a single test you validate this with 90, 180 and 270 days. Tests itself should probably go to `get_time.robot` files. Notice that there's the actual test case using `Get Time` on `atest/testdata` side and then runner on `atest/robot` side. You can learn more about our acceptance test system in `atest/README.rst` file.

Due to there being an easy workaround I don't think there's a need to backport the fix to earlier versions. We haven't actually done that in general so now that we are already working with RF 5.0 the fix would be only in that version. We are, however, going to create RF 4.1.3 due to 4.1.2 having an unfortunate regression and RF 5.0 not anymore supporting Python 2. Adding this fix into RF 4.1.3 would be so easy that it can be done if you need it.

**Comment by chris-from-the-coast** [comment]
Thanks Pekka. I made the fix and ran the AC tests and some are failing now.

I'll carve out some time to dig into it further.

**Comment by pekkaklarck** [comment]
You fixed Get Time in Robot's code base and some of our tests are failing? Or you took Get Current Date into use in your project and tests are failing there? Hope you can sort out the problems either way!

**Comment by chris-from-the-coast** [comment]
> You fixed Get Time in Robot's code base and some of our tests are failing?
Yes

**Comment by pekkaklarck** [comment]
What's the status of the fix? Did you @chris-from-the-coast get tests fixed? I can take a look at this myself as well if you don't have time.

**Comment by pekkaklarck** [comment]
The proposed fix actually didn't work. Using `time.gmtime()` instead of `time.localtime()` would mean that time is always returned in UTC. This fixes the DST bug because UTC isn't affected by DST, but that's not a big win when the functionality is otherwise broken.

Good news is that I was able to fix this by checking has there been DST change between the current time and the requested time. If there is, the DST difference needs to be added to the result.

We'll also soon create RF 5.0 alpha 1. Assuming we get this fixed, it would be great if you @chris-from-the-coast could test the preview release and verify the fix in your environment.

**Comment by pekkaklarck** [comment]
There's still a small problem even after my fix. If the keyword is run so that the "other end" happens to be in that time span that's affected by the DST (I guess it's called "fold"), the time is still one our off. I noticed this when the new test failed when it was run between 3-4am. The test increments an decrements days of the year and is thus bound to encounter this corner case if it is run during that "fold" period. I don't consider this problem severe enough to think could it still somehow be handled. Instead I'll change that test to not check all dates. In the future it thus will only fail if run on certain few days between 3-4am.

Notice also that `Get Current Date` is immune also to this fold problem. I would even more strongly recommend using that instead of `Get Time`.
