### ISSUE TITLE
New User Guide styles

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4149]
Would be nice, if the UserGuide would look a little less 90th...

This Issue is not for changing everything to Sphinx. Just tuning the CSS a bit.
Could be nice for 4.1.3 already.

**Comment by pekkaklarck** [comment]
Changing just CSS to make the UG look better is a good idea and I agree we can back port them to RF 4.1.3 that we anyway need to create at some point.

Bigger changes are probably best done by converting the UG to use [Sphinx](https://www.sphinx-doc.org/) that then makes it easy to host at [Read the Docs](https://readthedocs.org/).

**Comment by pekkaklarck** [comment]
There were some reports related to problems on OSX using Chrome. Could be that problems were caused by environment configuration, but it's safer to not change anything anymore in RF 4.1.x maintenance branch. Changes can land to master and then be part of RF 5.0. Online version of the User Guide can be patched inplace separately.

**Comment by pekkaklarck** [comment]
This was done in #4283. Thanks @Snooz82 for contribution!
