### ISSUE TITLE
Create basic project structure for Web application tests

### ISSUE THREAD

**Issue by manykarim** [robotframework/robotframework#4152]
As a User, I want to create a basic project structure for a new test automation project (e.g. of a web application), so that I can start writing test cases easily and in a maintainable way.

Every test automation project is different. But there are some good practices that we can follow when setting up new test automation projects. Like a separation of test cases, test data, keyword files and locators.
It would be great if all Robot Framework users could easily follow such practices and create a basic project structure from the scratch easily via a single command.

I'm aware that this could be done by creating a project structure on GitHub and just clone it locally. But I thought it would be easier for users if it's directly embedded into Robot Framework and can be created from the command line.
Maybe prompt the users for some default values, like the project name, main URL, test environments and users so that data can be populated in the project.
Maybe even create resource files for different components/pages of the app, based on the entered information.

**Comment by pekkaklarck** [comment]
This is a great idea and something I've been thinking as well. I don't think it should be part of Robot Framework core project, though. There could instead be a separate project like `robot-quickstart` that you could pip-install. Running the command should then prompt about project name, desired libraries, etc. It could then create a project structure, install Robot and everything else needed into a venv, create start-up scripts, etc.

There are several reasons why I believe this should be a separate project from the core:
- It doesn't have any direct requirements towards RF core nor does it benefit from that.
- Separate projects can have their independent release schedules.
- It's in general good to keep the core as small as possible.

So a bit :+1: for the overall idea but :-1: for including it into this project. The latter is the reason I think this issue here should be closed, but I leave it now open for a while to get comments from others. I believe the way forward would be creating a project at the MarketSquare. I'm sure others would be interested to contribute as well. The project would probably also have some overlap with Tidy and RoboCop.

**Comment by manykarim** [comment]
You're right @pekkaklarck .
I just wanted to avoid any barriers for the users and hopefully mention it in the user guides/getting started.
But that can also be done via a separate project at MarketSquare, you're right. Issue can be closed.

**Comment by pekkaklarck** [comment]
If/when such a project is ready for any wider use, it definitely needs to be mentioned in the User Guide and obviously listed at robotframework.org as well. Anyway, the tool won't be part of the core so I close this issue.
