### ISSUE TITLE
Add new builtin tags `robot:exclude`, `robot:skip` and `robot:skip-on-failure`

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4161]
Having a permanent skipping/exclusion of the tags `robot:skip` and `robot:exclude` would ease the marking of testcases that are temporarily excluded from execution.

For example tests, that has to be maintained, due to changed test object or in a concrete request of a user, to mark DataDriven Tests as skip for a certain use-case.

That would add the comfort, that users do not have to add `--skip robot:skip` and `--exclude robot:exclude` to the command line.

Would be nice for 5.0, because there is a real request for this. see [DataDriver Issue 68](https://github.com/Snooz82/robotframework-datadriver/issues/68)

[Slack discussion](https://robotframework.slack.com/archives/CJSNFRZMK/p1638581281028000)

**Comment by pekkaklarck** [comment]
Sounds good to me. Should also add `robot:skip-on-failure` at the same time.

**Comment by makeevolution** [comment]
@pekkaklarck would you mind if I try this out? I also would like to join the slack channel, but it requires an talousverkko.fi email address. Do you know how can I make one?

**Comment by pekkaklarck** [comment]
Go ahead @makeevolution! No special email should be needed to join the Slack community. You can get an invite at https://rf-invite.herokuapp.com/.

**Comment by nick-grout1** [comment]
Hi @makeevolution , I was wondering what the status of this was - I would be happy to pick this up if you're unable to work on this at the moment.

Just let me know if I can take this on, thank you!

**Comment by makeevolution** [comment]
Hey @nick-grout1 thanks for the offer but I'm still actively working on it, already made pull requests and working on the feedback now

**Comment by tw39124-1** [comment]
Upvote for a `robot:skip-on-failure` tag. I'm using `--skiponfailure` at the moment but it's hard to only apply to a subset of test cases. Being able to use a tag to do it would be great.

**Comment by pekkaklarck** [comment]
This was implemented in PR #4172 by @makeevolution. Thanks for contribution!

**Comment by pekkaklarck** [comment]
I just noticed that if you all tests in a suite are excluded with `robot:exclude`, the suite itself is still executed without any tests. This is different compared to when using `--exclude` because then empty suites are pruned automatically. The problem is due to `robot:exclude` being inspected only at execution time when the suite has already been started. Filtering using `--exclude` and other such options is done already before the whole execution starts and thus empty suites can be removed.

I tested handling `robot:exclude` earlier, but it turned out to be a bit problematic. Always going through the whole suite structure before execution to find automatically excluded tests could also add some overhead. Due to these problems I decided not to change anything at least now before RF 5.0. Another reason was that I don't see why someone would exclude all tests like this in the first place. Anyway, we can return to this if it becomes a real problem.
