### ISSUE TITLE
`Set Test/Suite/Global/Local Variable`: Recommend using `$name`, not `${name}` more strongly

### ISSUE THREAD

**Issue by rmccarth-bosch** [robotframework/robotframework#4177]
My company has a Robot Test that generates a random string consisting of alphabetical, numerical or symbolic characters and sets it as a suite variable. It appears that using a string starting with '@', '&' or '$' and setting as a suite variable breaks RF4.1.3.
Consider the sample test below (test.robot):
```
*** Test Cases ***
Set Suite Variable Starting with Alphabetical
    [Documentation]  Passes
    ${var} =  Set Variable  test
    Set Suite Variable  ${var}

Set Suite Variable Starting with Numerical
    [Documentation]  Passes
    ${var} =  Set Variable  123test
    Set Suite Variable  ${var}

Set Suite Variable Starting with Symbol
    [Documentation]  Passes
    ${var} =  Set Variable  ,test
    Set Suite Variable  ${var}

Set Suite Variable Starting with '$' (Built-in Var Syntax)
    [Documentation]  Fails
    ${var} =  Set Variable  $test
    Set Suite Variable  ${var}

Set Suite Variable Starting with '@' (Built-in List Syntax)
    [Documentation]  Fails
    ${var} =  Set Variable  @test
    Set Suite Variable  ${var}

Set Suite Variable Starting with '&' (Built-in Dict Syntax)
    [Documentation]  Fails
    ${var} =  Set Variable  &test
    Set Suite Variable  ${var}
```
All failures cases occur at `Set Suite Variable` and have the following error string: 
```
Variable '${test}' not found. Did you mean:
    ${TEST_TAGS}
    ${TEST_NAME}
```

**Comment by hello2ray** [comment]
@rmccarth-bosch, Can you please try within single quotes or double quotes as  "$", "@", and "&" are built-in keywords,

**Comment by rmccarth-bosch** [comment]
Hi @hello2ray, I am aware of that syntax already but the problem is that it will literally include the single or double quotes in the string variable. I updated the test cases and the resulting test 'passed' but now has the extra " or ' contained in the variable value. "$", "@" or "&" should also need braces `{<some value>}` after the built-in start as well. I would expect Robot to be smart enough to recognize the '$', '@' or '&' to be used as a string and not the built-in use in this case. For laughs, I tried escaped- syntax and I got the same failure as originally described.

**Comment by hello2ray** [comment]
@rmccarth-bosch, anything starts with "$", "@" and "&", Robot Framework will consider as variable. Single Quotes or Double Quotes is only option. 
FYI..
escaped-syntax is for
 *NOTE:* If the variable has value which itself is a variable (escaped
        or not), you must always use the escaped format to set the variable:

**Comment by rmccarth-bosch** [comment]
@hello2ray Thanks for the further explanation but can you please point me to where in the Documentation this is described explicitly? Robot Framework enforces the user to use "" or '' but in the process ends up changing the value of the string -- this does not seem right.  In this case, it's as simple as `"$test" != $test`.  If I wanted to use value for variable `test`, it would simply be `${test}`. String for dollar sign plus test would be `$test`. There are other work arounds for when a user intends to run a keyword vs string.  Like, `Run Keyword If` or `Run Keyword and Continue on Failure`. I don't think this is intended, hence why all $, @, & all require the use of braces.

**Comment by pekkaklarck** [comment]
The problem is that when you use, for example, `Set Suite Variable  ${x}  Value` Robot cannot know do you want to set variable `${x}` or does the variable `${x}` contain the name of the variable you actually want to set. It tries to be clever and does the following:
1. Checks does variable `${x}` exist. If not, you clearly want to create it.
2. If it exists, it checks its value. If the value isn't itself a variable, you apparently want to set `${x}` again so that the new value overrides the old one.
3. If variable `${x}` exists and its value is a variable, Robot sets _that_ variable and `${x}` isn't affected.

Because there can be such surprises, `Set Suite Variable` accepts the variable to set in a special format without `{}` decoration. This means that if you use `Set Suite Variable  $x  Value`, it knows you want to set variable `${x}`. That's handy, but it unfortunately makes the above algorithm to check how to handle a variable specified like `${x}` even more error prone. In the step 3. when it checks is the value of `${x}` a variable, it considers it a variable both if it uses format `${y}` and format `$y`.

In one of your example you had this:
```
    ${var} =  Set Variable  $test
    Set Suite Variable  ${var}
```
This is how the above is interpreted:
- `${var}` is created with value `$test`.
- `Set Suite Variable` is used with variable name `${var}`.
- Robot sees that `${var}` has value `$test` and assumes you want to create variable `${test}`.
- `Set Suite Variable` doesn't get variable value, so Robot assumes you want to use the existing value of the variable `${test}`.
- `${test}` variable doesn't exist.

To test this, you can chance the above to
```
    ${var} =  Set Variable  $test
    Set Suite Variable  ${var}  value
    Log many    ${test}    ${var}
```
and you'll see that `${test}` variable now has value `value` and `${var}` still contains `$test`.

As you probably have already realized, a way to avoid these problems is using `Set Suite Variable` with the `$var` syntax unless you actually want to pass in the variable to set as a variable. In other words, changing your example to
```
    ${var} =  Set Variable  $test
    Set Suite Variable  $var
```
ought to solve the problem for good.

**Comment by pekkaklarck** [comment]
This functionality definitely works strangely and you aren't the first one to have problems with it. See #3233 for another example. This stuff is explained in the documentation of [Set Suite Variable](file:///home/peke/Devel/robotframework/doc/libraries/BuiltIn.html#Set%20Suite%20Variable), but perhaps docs should be changed to make it more clear that `$name` syntax, not `${name}`, should typically be used.

We could also consider enforcing using `$name` and allow `${name}` _only_ when that variable exists and contains a variable name to actually set. `Set Suite Variable` and its variables `Set Test/Global/Local Variable` are used so much that outright changing the behavior would not be a good idea and a deprecation period would be needed. I'm not sure should we even emit a deprecation warning in the beginning. It would probably be safest to first update documentation to tell `$name` should be used and to mention this in release notes. Then in some later release we could start emitting those deprecation warnings and even later we could really enforce `$name` syntax. In the comments of #3233 I wrote that I don't think this is worth the effort, but I'm starting to change my mind.

**Comment by rmccarth-bosch** [comment]
@pekkaklarck Wow! Thank you for the **very** thorough explanation of how this works. I did not realize the complex nature that  existed within `Set <Level> Variable`. I would be a fan of your second comment's path forward and agree a good starting place would be updating the documentation and slowly enforcing the `${name}` syntax only when the var exists.

Even in your `ought to solve the problem for good` case, I still have one small problem...
Typically, the first character in the string for `Set Suite Variable` will be an otherwise valid string, integer or symbol **not** `@ & $`. The start of `@ $ &` is an edge case, so I cannot just do this generically every time. This complicates things because in my actual test code, a keyword is responsible for generating the random string. I was trying to work around this with all built-in functionality. A quick helper to not allow `@ $ &` for randomly generated strings will work for me for now, not sure if you had any other ideas...

**Comment by pekkaklarck** [comment]
If you use pattern
```
    ${var} =  Set Variable  <text>
    Set Suite Variable  $var
```
it shouldn't matter that `<text>` contains. The key is using `$var`, not `${var}`, with `Set Suite Variable`.

I'll leave this issue open as a reminder to at least updated documentation of `Set Suite Variable` to explain this a bit more thoroughly and to recommend using the `$name` format.

**Comment by pekkaklarck** [comment]
Need to still think should we really deprecate using `${name}` format. If yes, this issue needs to get `deprecation` label so that we remember to mention that in the release notes. As I wrote earlier, we shouldn't emit actual deprecation warnings in RF 5.0 yet anyway.

**Comment by pekkaklarck** [comment]
Decided not to deprecate the normal `${name}` syntax because it would require changes to so many tests. Instead the `$name` syntax is now recommended strongly in documentation. If we come up with nice syntax to create local variables (#3761) that can also be extended to other scopes, possibly we can then very slowly deprecate and remove these keywords altogether.
