### ISSUE TITLE
Parsing Argument Setting of Keywords with line continuation and no argments, throws an IndexError

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4181]
When I run this piece of code:

```robotframework
*** Keywords ***
test
    [Arguments]  
    ...    
```

robot crashes with an:

```
[ ERROR ] Unexpected error: IndexError: string index out of range
Traceback (most recent call last):
 File "c:\develop\robot\robotframework\src\robot\utils\application.py", line 83, in _execute
    rc = self.main(arguments, **options)

...
  File "c:\develop\robot\robotframework\src\robot\running\arguments\argumentparser.py", line 118, in parse
    elif self._is_kwargs(arg):
  File "c:\develop\robot\robotframework\src\robot\running\arguments\argumentparser.py", line 215, in _is_kwargs
    return arg[0] == '&'
```

this is happening with RF 4.1.3 and with the current main branch

Tried to investigate what happens and stumbled upon this line:

https://github.com/robotframework/robotframework/blob/ac4803649702ada9d18c5357ad7fcbbebcd0fb89/src/robot/parsing/lexer/tokenizer.py#L80

If I comment out this line, everything works fine, some testcases are broken, those that wanted to have these extra token in it. But there is no testcase that explicitly test this extra token.

The problem is, that `_is_kwargs` Method (see traceback) get's an empty string as argument, and throws an error, because there this extra empty token is added by `_ensure_data_after_continuation` Method and later then, it is converted to an ARGUMENT token.

Is adding this extra token after a line continuation really nessessary?

I can provide a PR, but wanted to ask first for other opinions.

**Comment by pekkaklarck** [comment]
Good catch! Adding the extra token is done to make use lines with only `...` aren't ignored in cases like

```
*** Settings ***
Documentation    First paragraph with only one line.
...
...              Second paragraph with multiple
...              source lines that are joined together.

*** Test Cases ***
Example
    Keyword
    ...    with
    ...    multiple
    ...
    ...    arguments
```

Handling these cases otherwise would be complicated because tokenizer at that point doesn't have context information and doesn't know what it is tokenizing. I think it would be best to just enhance that `_is_kwargs` to handle case where the argument is an empty string.

**Comment by pekkaklarck** [comment]
The current code looks like this:
```python
def _is_kwargs(self, arg):
    return arg[0] == '&'
```

A natural fix would be
```python
def _is_kwargs(self, arg):
    return arg and arg[0] == '&'
```
but also
```python
def _is_kwargs(self, arg):
    return arg[:1] == '&'
```
works. The latte probably has a bit better performance but I seriously doubt it matters here.

This obviously needs tests. I guess `parsing/line_continuation.robot` is the best place. An alternative would be `parsing/user_keyword_settings.robot` and adding test to both is ok as well.

**Comment by d-biehl** [comment]
I have tried a little bit around:

ok, this:

```robotframework
*** Settings ***
Documentation    First paragraph with only one line.
...
...              Second paragraph with multiple
...              source lines that are joined together.
```

works as expected....


but

```robotframework
*** Test Cases ***
first
    Log
    ...
    ...    hello
```

gives me an error `Invalid log level 'hello'.`

and this
```robotframework
*** Test Cases ***
first
    Log
    ...    hello
    ...    
    ...    INFO
```

an `Invalid log level ''.` error.

same with:

```
*** Test Cases ***
first
    Log
    ...    hello
    ...  
```

and playing arround with the example in the documentation [Dividing data to several rows](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-246)

if I uncomment the above line with `_ensure_data_after_continuation` everything works fine except multiline documentation and multiline strings...

so what does the "..." means? 

I think, that adding this additional token, puts data into the token stream that was not written by the user. And we have to write "checks" for these extra token, instead to handle special "non standard line continuation" i.e Multiline Docs or Multiline strings variables.

what do you think?

**Comment by pekkaklarck** [comment]
Let's look a this example:
```robotframework
*** Test Cases ***
first
    Log
    ...
    ...    hello
```

The above is same as
```robotframework
*** Test Cases ***
first
    Log
    ...    ${EMPTY}
    ...    hello
```
which obviously is same as
```robotframework
*** Test Cases ***
first
    Log    ${EMPTY}    hello
```

I consider that fine. At least it's better than the original example being same as
```robotframework
*** Test Cases ***
first
    Log
    ...    hello
```
which then would be equal to
```robotframework
*** Test Cases ***
first
    Log    hello
```

Even if we'd come up with better semantics for this example, changes would be backwards incompatible. Most likely it's best to leave it as it is. Good news is that this kind of syntax is very rare, outside of documentation, and you can always add `${EMPTY}` to make the syntax easier to understand.

Typically a line with `...` alone being considered the same as `...    ${EMPTY}` isn't a problem because empty values in general are handled just fine. You just happened to find out one place where the value is indexed without checks. That is very easy to fix and even if there were other cases like this they'd be easy to fix as well.

Looking at the history, it seems this initially worked fine with the new parser introduced in RF 3.2, but it was broken in 4cb35cbb4880c1190d5829630de31f0702b76b70 to fix #3514 even before RF 3.2 was released in April 2020.

**Comment by d-biehl** [comment]
ok, that makes sense for me.

But it's not really clearly described in the documentation. Thought it worked like the line continuation in python (the backslash at the end of a line ;-)

I started a pull request.

For me it's now the correct handling that robot reports an error "Invalid argument syntax".
Is it ok for you?

I have to find out where I put the test cases...

**Comment by pekkaklarck** [comment]
Yea, reporting an error about invalid arguments is the way to go. See my earlier [comment](https://github.com/robotframework/robotframework/issues/4181#issuecomment-1014634286) about where to possibly add the test.

Do you have ideas how to improve docs?

**Comment by pekkaklarck** [comment]
Have you had time to look at the tests @d-biehl? I'd like to get this issue closed and can create the test myself as well if you are busy.

**Comment by d-biehl** [comment]
just pushed the testcase, hope it is good enough ;-)

**Comment by d-biehl** [comment]
but it PR failes with "`GITHUB_TOKEN` variable is not set."

**Comment by pekkaklarck** [comment]
Not sure why that GITHUB_TOKEN thing fails, but if you look at the actual test run there's a test failure related to this as well:

> FAIL: Robot.Parsing.User Keyword Settings.Invalid empty line continuation in arguments should throw an error
> Wrong log message: 'Error in file '/home/runner/work/robotframework/robotframework/atest/testdata/parsing/user_keyword_settings.robot' on line 206: Creating keyword 'Invalid empty line continuation in arguments should throw an error' failed: Invalid argument specification: Invalid argument syntax ''.' does not match 'Error in test case file '/home/runner/work/robotframework/robotframework/atest/testdata/parsing/user_keyword_settings.robot': Creating keyword 'Invalid empty line continuation in arguments should throw an error' failed: Invalid argument specification: Invalid argument syntax ''.'

That error seems to be due to me just changing the error message that's used when creating a user keyword fails as part of #4201. Now this error is uniform with other similar errors and you can use the existing `Error In File` keyword for validating it, no need to create new ` Error in test case file`. Otherwise the test looks fine.

There's also another failing test in the test run but that's our mistake and ought to be now fixed.

**Comment by d-biehl** [comment]
created a new PR #4206

**Comment by pekkaklarck** [comment]
Fixed in PR #4206 by @d-biehl. Thanks for contribution!

**Comment by pekkaklarck** [comment]
Although crashes are always severe, this is such a rare special case that decided to lower the priority.

**Comment by pekkaklarck** [comment]
After thinking a bit more, high priority is better. Sorry for noise....
