### ISSUE TITLE
Library keywords accepting embedded arguments cannot be called `@{list}` and `&{dict}` variables

### ISSUE THREAD

**Issue by yggdr** [robotframework/robotframework#4207]
As reported here: https://forum.robotframework.org/t/embedded-arguments-with-dictionary-variable-not-working/3145

If I define a keyword with embedded variables in python like so:
```
@keyword(name='Some Test "${var1:[^"]+}" Bla "${var2}"')
def some_test(self, var1: str, var2: dict):
    ...
```

They cannot be called with the syntax `Some Test "${SOME_VAR}[test][etc]" Bla "&{data}"`. The error it throws is `Keyword 'Some Test […]' expected 2 arguments, got 1.`

In the old form where the arguments where not embedded it worked when called with `&{data}`.

**Comment by pekkaklarck** [comment]
Using `&{var}` when calling a keyword generally means unpacking the dictionary so that its items are passed to the keyword as named arguments. This is similar to how `**var` works in Python when calling a function. If you'd use the same dictionary as `${var}`, you'd pass that dictionary forward as a whole. The latter format works fine with embedded arguments as well and replacing `&{data}` with `${data}` when calling the keyword fixes the problem. I'm not actually sure should we even support `&{var}` syntax in this case, but it would have a benefit that Robot would validate that the variable is a dictionary. Anyway, the current error message is _so_ strange that I consider that alone a bug that's definitely worth fixing. It just could be that the fix is explicitly prohibiting `&{var}`. One deciding factor will be how `@{var}` syntax is handled.

**Comment by pekkaklarck** [comment]
The `@{var}` syntax didn't work any better. For example, calling keyword
```python
@keyword('Example ${arg}')
def kw(arg):
    pass
```
like
