### ISSUE TITLE
Enhance error detection at parsing time

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4210]
Robot's parser detects many errors already at the parsing time, but there are also many syntax errors that are only detected at the execution time. A problem with detecting errors only at the execution time is that they aren't reported to tools like editor plugins that use Robot's parser. We should thus move error detection to parser as much as possible. This includes at least these cases:

- Empty test and keyword.
- `END`, `ELSE`, `ELSE IF`, `EXCEPT` or `FINALLY` when there is no matching parent element like `IF` or `TRY`.
- ~`RETURN` used in test.~ Fixed already in RF 5.0.
- ~`BREAK/CONTINUE` outside loops.~ Fixed already in RF 5.0.
- ~`RETURN/BREAK/CONTINUE` in `FINALLY`.~ Fixed already in RF 5.0.

We also have a similar problem that some of the error situations detected by the parser are not detected as early as they could be. For example, having `IF` with more than one condition is detected by the parser when the parsing model is validated, but the underlying tokens do not get `ERROR` type. This is a problem if only using tokens (i.e. when using `get_tokens`, not `get_model`) and also when using the model it would be more convenient if invalid tokens could be easily detected. This problem occurs at least in these cases:

- `IF`, `ELSE IF` and `WHILE` with more than one condition.
- `ELSE`, `END`, `BREAK`, `CONTINUE`, `TRY` and `FINALLY` with values.
- `AS` with invalid variable or with more than one variable.

Because these latter errors are detected by the parser, only a bit late, I don't consider this limitation as bad as the problem with the earlier errors.

**Comment by yanne** [comment]
These three points are covered already in 5.0:

- RETURN used in test.
- BREAK/CONTINUE outside loops.
- RETURN/BREAK/CONTINUE in FINALLY.

**Comment by pekkaklarck** [comment]
After ffa0d4e65795d2392bf3166b33eb7ff9800e27c9 syntax errors are reported during execution using `raise DataError(msg, syntax=True)`. All these could be detected already at parsing time.

**Comment by pekkaklarck** [comment]
Need to take a closer look at this and submit concrete issues about errors that could be detected earlier.

**Comment by yanne** [comment]
Fixed empty name and keyword validation #4376e59

**Comment by yanne** [comment]
We decided to leave this part for a later stage:

`We also have a similar problem that some of the error situations detected by the parser are not detected as early as they could be. For example, having IF with more than one condition is detected by the parser when the parsing model is validated, but the underlying tokens do not get ERROR type. This is a problem if only using tokens (i.e. when using get_tokens, not get_model) and also when using the model it would be more convenient if invalid tokens could be easily detected. This problem occurs at least in these cases:

IF, ELSE IF and WHILE with more than one condition.
ELSE, END, BREAK, CONTINUE, TRY and FINALLY with values.
AS with invalid variable or with more than one variable.
Because these latter errors are detected by the parser, only a bit late, I don't consider this limitation as bad as the problem with the earlier errors.`

Other enhancements listed in the original post are now fixed.
