### ISSUE TITLE
Options passed to `robot.run` and `robot.rebot` are not verified

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4212]
I noticed that the `run` python API does not verify the optional/extra arguments, it seems to silently ignore them. Is this expected behaviour? 

```
>>> import robot
>>> robot.run('/tmp/test.robot', this_option_is_illegal='bar')
==============================================================================
Test
==============================================================================
test                                                                  | PASS |
------------------------------------------------------------------------------
Test                                                                  | PASS |
1 test, 1 passed, 0 failed
==============================================================================
Output:  /Users/oboehmer/Documents/Test-Automation/robotframework-fork/output.xml
Log:     /Users/oboehmer/Documents/Test-Automation/robotframework-fork/log.html
Report:  /Users/oboehmer/Documents/Test-Automation/robotframework-fork/report.html
0
>>> robot.run('/tmp/test.robot', this_option_is_illegal='bar', quiet=True)
0
```

We have a use case here where we invoke robot runs via a python executable which, after some local initialization stuff, invokes robot via robot.run(...).. So if the user passes extra robot args on the command line, illegal args aren't flagged..

**Comment by pekkaklarck** [comment]
This is certainly strange. I don't remember there being any use case for this so let's change it. Changing is backwards incompatible but ok in a major release. I already implemented a fix and it was pretty trivial. Testing it turned out to be harder because related unit tests handled outputs in a bit strange way and, more importantly, because if there were errors in parsing options, possible custom `stdout` and `stderr` were ignored. I'll submit a separate bug about that.

**Comment by oboehmer** [comment]
Thanks for the quick fix, Pekka!

**Comment by pekkaklarck** [comment]
Thanks for the report!
