### ISSUE TITLE
Do not expland `NOT RUN` keywords even if they match `--expandkeywords`

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#4214]
Using RF 5.0a1 skipped keywords gets expanded. This is a problem for huge logs with many matching skipped keywords and results in browser crash.

![grafik](https://user-images.githubusercontent.com/20930315/152114894-ef655789-8560-44c5-89a7-89bb2ca1a6c1.png)

**Comment by pekkaklarck** [comment]
Is this limited to RF 5.0a1 or did it happen also earlier?

**Comment by DirkRichter** [comment]
It occurs on earlier versions, too. E.g. if IF-ELSE contruct is avoided. Problem seems to be introduced with NOTRUN/SKIPPED keywords in result loh.html.

In RF 5.0a1 it became problematic for us, because expansion now works correctly (in RF 4 most of our skipped/notrun keywords did not match due to invalid id and was not expanded)

**Comment by pekkaklarck** [comment]
I see. There are two ways how keywords can get `NOT RUN` status:
- They are in an unexecuted IF/ELSE branch.
- There is an earlier failure.

The former is likely a much more common scenario, but due to #4195 these keywords weren't earlier correctly expanded and thus the problem wasn't so big in earlier versions. Since the problem anyway occurred also earlier this isn't a regression. I'll update the title accordingly and add this into RF 5.0 scope.

Notice that the `SKIP` status is unlikely to cause problems. Keywords only get that status if they explicitly skip a test. That's pretty rare and being able expand such keywords could be useful.

**Comment by pekkaklarck** [comment]
As a reference, `--expandkeywords` was added in RF 3.2 (#2698) and the `NOT RUN` status in RF 4.0 (#3842).

**Comment by pekkaklarck** [comment]
The PR looks good but still needs a test. We are planning to create alpha 2 (or possibly beta 1) pretty soon. If you can create a test, we can include this fix into that release as well.

**Comment by pekkaklarck** [comment]
@DirkRichter, I'd like to merge PR #4215 to get it into the beta release but it needs tests. If you don't have time to create them, I can look at that myself as well.

**Comment by DirkRichter** [comment]
Thanks, i'm busy with other stuff.

**Comment by pekkaklarck** [comment]
Ok, no problem. Fixed now.
