### ISSUE TITLE
XML: `Set Elements Text` and other "plural variants" do not return modified XML

### ISSUE THREAD

**Issue by msieurtoph** [robotframework/robotframework#4242]
Hi,

As the `XML.Get Element`, `XML.Set Element Text` accept `source` to be "a path to an XML file, a string containing XML, or an already parsed XML element."

According to documentation, `XML.Set Elements Text` works like `XML.Set Element Text`.
But I figured out it ONLY accepts parsed XML. It fails if you supply a path to an XML file.

So you can do 
```
    ${out}    XML.Set Element Text    path/to/my/xml    text=xxx    xpath=//xxx/xxx
```

But you have to do a parse first when using `XML.Set Elements Text`
```
    ${xml}    XML.Parse Xml    path/to/my/xml
    ${out}    XML.Set Elements Text    ${xml}    text=xxx    xpath=//xxx/*
``` 

IMO, `XML.Set Elements Text` should accept the same inputs as `XML.Set Element Text` or `XML.Get Element` and take the parsing instruction in charge, if needed.

**Comment by pekkaklarck** [comment]
The problem is that `Set Elements Text` doesn't return the source like `Set Element Text` does. The same is true also with other "plural variants" like `Set Elements Attribute`. In practice if you pass the source as a path to an XML file to them, they will parse the XML, modify it, but because they don't return the modified XML changes aren't actually seen anywhere.

This is easy to fix. Currently, for example, `Set Elements Text` implementation looks like this:
```python
    def set_elements_text(self, source, text=None, tail=None, xpath='.'):
        for elem in self.get_elements(source, xpath):
            self.set_element_text(elem, text, tail)
```
Simply returning `source` at the end wouldn't work, because it would be whatever is passed to this keyword, not necessarily the actual XML element. We could change the implementation to following to make sure the source is parsed when needed and then return it at the end:
```python
    def set_elements_text(self, source, text=None, tail=None, xpath='.'):
        source = self.get_element(source)
        for elem in self.get_elements(source, xpath):
            self.set_element_text(elem, text, tail)
        return source
```

Just updating all affected keywords isn't enough, tests would need to be added for this functionality as well. There aren't that many keywords so this isn't a too big task. Would someone be interested to do that? Since this can be considered a bug, the behavior doesn't really match documentation, I guess I could fix it myself before RF 5.0 as well.

**Comment by msieurtoph** [comment]
@pekkaklarck 
Thx for quick update.
I was working on a PR but you beat me to it.
I am very new to RF and kind of busy all day, so very slow...

Looking at the changes, I saw you only wrote tests to check that keywords return the sources but not to check they can accept xml or path to xml. Weren't they mandatory ?

And I noticed also, you let this line 
https://github.com/robotframework/robotframework/commit/639776ef2279dd24cec59a7fccfda9976dd3756c#diff-224595a703ea03cd5e7f223dd688c7c46b4b5d3e825292e851882e2cb903f78aR24
I thought parsing was not necessary anymore ... but maybe, I missed something.

**Comment by pekkaklarck** [comment]
Didn't know you were working with a PR so decided to fix this quick so that it still makes it to RF 5.0.

All these keywords were already tested using other inputs. They also all use `get_elements` which is thoroughly tested with different inputs separately. The test you explicitly referred to actually validates that you can use an already parsed XML as an input and in those cases the XML document is modified. New tests just validate that the keywords return the root element of the passed in source.
