### ISSUE TITLE
Remove Python 2, Jython, IronPython and Java references from User Guide

### ISSUE THREAD

**Issue by rikerfi** [robotframework/robotframework#4257]
There are examples that are made for python2 but fail python3. See e.g. https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#toc-entry-603 
`raw_input` should go `input` at least 2 examples.

```
"""Listener that stops execution if a test fails."""

ROBOT_LISTENER_API_VERSION = 3

def end_test(data, result):
    if not result.passed:
        print('Test "%s" failed: %s' % (result.name, result.message))
        raw_input('Press enter to continue.')
```

**Comment by pekkaklarck** [comment]
Yeah, we haven't yet updated the User Guide to remove Python 2, Jython, IronPython and Java references. The plan is to do that after we have RF 5.0 rc 1 out. We left #3457 open because this and some other related task weren't done. I guess we could use this issue to track the User Guide updates instead.

**Comment by yanne** [comment]
This was done in #4271
