### ISSUE TITLE
Libdoc does not support specifying argument types using new `arg: X | Y` syntax

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#4275]
originally raised here: https://github.com/robocorp/robotframework-lsp/issues/602

### files
`Sandpit/test.py`:
```py
def foo(src: str | None) -> None:
    ...
```
`Sandpit/test.robot`:
```robot
*** Settings ***
Library     Sandpit.test
```
### command & output
```
> python -m robot.libdoc Sandpit.test Sandpit.test.libspec    

Building library 'Sandpit.test' failed: KeyError: typing.Union

Try --help for usage information
```

### environment
 - OS: windows 10
 - Robot Framework Version: 5.0b1
 - python version: 3.10

**Comment by pekkaklarck** [comment]
I reproduced the problem. Apparently when the support for the `arg: X | Y` syntax was added in RF 4.1.1 (#4075), no tests were added for Libdoc. Probably it was assumed that type conversion related code that also Libdoc uses would handle this syntax like it handles `typing.Union`. It also requires a bit extra work to use syntax that only some Python versions supports in tests.

I tested that there are no errors using this syntax with Libdoc with RF 4.1.1. Results are a bit different compared to using `typing.Union` but look ok anyway. Probably this has thus been tested manually with Libdoc when the support for the syntax was added.

Good news is that fixing the problem is very easy. This time I'll those missing tests as well. Because this is a regression in RF 5.0 that hasn't yet been officially released, I'll change the type from `bug` to `task` to avoid this issue being listed in RF 5.0 release notes.

Big thanks testing RF 5.0 and reporting the issue!
