### ISSUE TITLE
And IF is failing in 5.0

### ISSUE THREAD

**Issue by p74** [robotframework/robotframework#4297]
Using gherkin with an IF statement  

When i use "And IF", robot framework complains that IF is a reserved keyword and it need to be written in upper case. however i did write IF in upper case:

And IF    ${foo}    keyword

Report: 
If' is a reserved keyword. It must be an upper case 'IF' when used as a marker. 

Greetings Ruud.

**Comment by pekkaklarck** [comment]
The reason is that `IF` and other such syntax is already detected by the parser. When you use it like `And IF`, it isn't detected. Later when `And IF` is executed, Robot tries to find a keyword matching `IF` and finds one from the Reserved library that exists there to warn about reserved syntax. When that keyword is run, it doesn't know it was actually part of `And IF` and thus the error message is confusing.

This could be fixed by actually allowing using `IF` and other syntax with these Gherkin prefixes, but I don't think that makes any sense. The point of the Gherkin syntax is being able to write very easy to understand and non-technical tests/requirements. Mixing that syntax with very technical `IF` or `FOR` syntax just feels strange.

Another problem would be that detecting `IF` and other such syntax when used with BDD prefixes would slow down parsing. We currently can just compare values directly, all this syntax is case-sensitive, and checking possible case-insensitive prefixes would be slow.

Although I pretty firmly believe supporting `And IF` constructs isn't a good idea, I do agree that the error message is bad. Need to think could we enhance it somehow. Alternatively we could just remove the whole Reserved library. It's not that useful anymore.

**Comment by emanlove** [comment]
With regards to the Reserved library, the error message reminds me of issue #4225 for better error reporting. Does the underlying structure of the reserved library provide "helpful hints"?

**Comment by pekkaklarck** [comment]
The Reserved library contains keywords `For`, `While`, `Break`, `Continue`, `End`, `If`, `Else`, `Elif`, `Else If`, and `Return`. Using them fails with a message telling that the keyword is reserved. With some of them there's also some extra help like instructing to use upper case variants.  You can see the exact error messages in the [source code](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/Reserved.py).

If we'd remove the Reserved library, there would be just an error like `No keyword with name 'Return' found.` if you'd use any of these keywords. I consider that good enough and that error would also be better in this particular context than what there's currently.

We added the Reserved library ages ago to avoid problems if new syntax is added. Now all the syntax there (and more!) has been added so there's no need to reserve anything. When we finally added `IF` (`FOR` had existed but was written like `:FOR` and was case-insensitive), we made a decision to require all syntax to be upper case. That makes it mostly unnecessary to reserve possible new syntax because even if we'd add something like `CASE`, there would be no problem using keyword `Case`.

**Comment by p74** [comment]
I agree with your statement @pekkaklarck 

"This could be fixed by actually allowing using IF and other syntax with these Gherkin prefixes, but I don't think that makes any sense. The point of the Gherkin syntax is being able to write very easy to understand and non-technical tests/requirements. Mixing that syntax with very technical IF or FOR syntax just feels strange." 

its indeed a bit mixed up gherkin with an if statement/keyword syntax so i removed already all the gherkin out of the resource files. So maybe its even good not to accept this kind of statements in gherkin but the error should be clear about it. 

What i also often as see is something like a mix between gherkin syntax and keywords syntax. 
but I think it would be nice for the further if there are more restriction in this area when using gherkin syntax in general, but that's just an idea.

Thx for the feedback 

Ruud

**Comment by pekkaklarck** [comment]
I submitted #4302 about removing the Reserved library. I don't think there's need to do anything else to this issue.
