### ISSUE TITLE
Conflict between -t and -N options

### ISSUE THREAD

**Issue by lduretz** [robotframework/robotframework#4298]
Using this poc.robot code :
```
**Test Cases**
Start One Test
    No Operation

Start Another Test
    No Operation

Play One Test
    No Operation

Play Another Test
    No Operation
```

Command line **robot -t "Start * Test" -N Start poc.robot** plays 4 tests instead 2 tests called "Start ..."
Same behaviour with command command line **robot -t "Play * Test" -N Play poc.robot**

Bug produced with :

- Robot Framework 5.0 (Python 3.6.4 on cygwin)
- Robot Framework 3.1.2 (Python 2.7.15 on win32)

**Comment by pekkaklarck** [comment]
The reason is that `--test` matches both the "short name" of the test, like "Start One Test", and the "long name" of the test that contains the parent suite name in it. When the parent suite name is "Start", using `--test "Start * Test"` ends up executing all tests that end with "Test". This is somewhat unfortunate but the design really cannot be changed. Easiest way to avoid the problem is always including the parent suite name like `--test "Start.Start * Test"`. Another would be creating a custom `--prerunmodifier` that does filtering exactly as you want.
