### ISSUE TITLE
Keyword visibility modifiers for resource files

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#430]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=430) by tookko on 19 Nov 2009_

Complicated user keywords in resource files are typically built by 
breaking the desired functionality into smaller, lower level user keywords 
which are then used by the higher level user keyword. For maintainability 
purposes it's often desirable that the lower level keywords are not used 
directly from test cases, but only the higher level ones.

While this can be tackled softly by usage of documentation tags, it would 
be useful to have a [Private] modifier for keywords, which would make it 
not possible to use the keyword from outside the same resource file.

**Comment by pekkaklarck** [comment]
Unfortunately no time for this in 2.9.

**Comment by RedTea14** [comment]
What is the status of this problem? Will we include this in a future release?

**Comment by pekkaklarck** [comment]
Hopefully this is implemented at some point, but I cannot make any promises when. At least I won't have time to look at this before RF 3.1 and we don't even have plans when to start RF 3.2 development. If this is important for you and you have resources to look at implementing this yourself, I can help you get started and review pull requests.

**Comment by tw39124-1** [comment]
I'd like to upvote this for a future release, as it would enable proper encapsulation of resource files. However, I agree with @spooning when he says that explicitly preventing someone from calling a keyword that they find useful is probably not helpful, and goes against the Robot ethos.
As an alternative, how about modifying the "Resource" import statement to add a [Private] option so that it only brings into the current namespace those keywords that are _directly defined_ in the imported resource file? The current behaviour is that _all_ keywords in the recursive import chain are also brought into the namespace.
Adding a [Private] option would allow "lower-level" keywords to be moved to a lower resource file and thus kept hidden. Developers can still access the lower-level keywords directly by importing that .robot file if they want to. This would also be fully backwards compatible as the default would be a [Public] import, and so the behaviour with existing test suites would remain the same.

**Comment by efgruber** [comment]
definitely a upvote for this enhancement!

**Comment by ukostas** [comment]
+1

**Comment by Anilkumar-Shrestha** [comment]
Upvote for this feature +1

**Comment by kaposh** [comment]
+1

**Comment by Alpa-1** [comment]
+ Upboat

**Comment by robinmatz** [comment]
Hi @pekkaklarck , I am interested in contributing to this issue. From what I've gathered from this thread, these are the features:
* User Keywords starting with underscore "_Keyword Name" should be treated as private, and thus not be imported
* User Keywords having a [PRIVATE] tag should also be treated as private, and thus not be imported.
* There should also be the possibility to tag User Keywords as [PUBLIC], however, this is would be the default

For the tag option, I am not sure where the tag should be placed: In the keyword name itself ``[PRIVATE] User Keyword``, or as a tag like
```
User Keyword
    [PRIVATE]
    ...
```
?

**Comment by pekkaklarck** [comment]
We discussed this with @robinmatz at RoboCon sprints today. We agreed that using `robot:private` tag is the best way to mark keywords private because it is explicit, requires no parser changes, and we already use similar tags like `robot:continue-on-failure` and `robot:no-dryrun`. Basically you could use it like this:

```robotframework
*** Keywords ***
Private keyword
    [Tags]    robot:private
    Log    Hello!

Keyword
    Private keyword    # this is valid call because the private keyword is in the same file
```

We also discussed what should happen if you try to call a private keyword outside the file where it is created. That could either be an error or there could only be warning. We didn't see much benefits in making it an error so decided to go with a warning.

Another thing we discussed was how Libdoc should handle this. We agreed that HTML outputs shouldn't have private keywords listed at all, but we think it probably is best to include them in spec files. The reason for having them in specs is that then editors using specs know about them and can propose completion in the file where they are created.

After all the design discussion we decided to prototype this and it turned out that implementation isn't too complicated. There were so little changes that instead of creating a branch I just include the diff here. @robinmatz promised to continue from there by cleaning up the code, adding tests, and writing documentation. He may have something done already at the end of the sprints!

```diff
diff --git a/src/robot/libdocpkg/htmlwriter.py b/src/robot/libdocpkg/htmlwriter.py
index df025a2a8..e17951d49 100644
--- a/src/robot/libdocpkg/htmlwriter.py
+++ b/src/robot/libdocpkg/htmlwriter.py
@@ -33,4 +33,4 @@ class LibdocModelWriter(ModelWriter):
         self.output.write('<script type="text/javascript">\n'
                           'libdoc = %s\n'
                           '</script>\n'
-                          % self.libdoc.to_json())
+                          % self.libdoc.to_json(include_private=False))
diff --git a/src/robot/libdocpkg/model.py b/src/robot/libdocpkg/model.py
index 90d023c65..f91549d5f 100644
--- a/src/robot/libdocpkg/model.py
+++ b/src/robot/libdocpkg/model.py
@@ -108,7 +108,7 @@ class LibraryDoc:
                 type_doc.doc = formatter.html(type_doc.doc)
         self.doc_format = 'HTML'
 
-    def to_dictionary(self):
+    def to_dictionary(self, include_private=True):
         return {
             'specversion': 1,
             'name': self.name,
@@ -122,7 +122,8 @@ class LibraryDoc:
             'lineno': self.lineno,
             'tags': list(self.all_tags),
             'inits': [init.to_dictionary() for init in self.inits],
-            'keywords': [kw.to_dictionary() for kw in self.keywords],
+            'keywords': [kw.to_dictionary() for kw in self.keywords
+                         if include_private or not kw.private],
             # 'dataTypes' was deprecated in RF 5, 'typedoc' should be used instead.
             'dataTypes': self._get_data_types(self.type_docs),
             'typedocs': [t.to_dictionary() for t in sorted(self.type_docs)]
@@ -136,8 +137,8 @@ class LibraryDoc:
             'typedDicts': [t.to_dictionary(legacy=True) for t in typed_dicts]
         }
 
-    def to_json(self, indent=None):
-        data = self.to_dictionary()
+    def to_json(self, indent=None, include_private=True):
+        data = self.to_dictionary(include_private)
         return json.dumps(data, indent=indent)
 
 
@@ -171,6 +172,10 @@ class KeywordDoc(Sortable):
     def shortdoc(self, shortdoc):
         self._shortdoc = shortdoc
 
+    @property
+    def private(self):
+        return 'robot:private' in self.tags
+
     @property
     def deprecated(self):
         return self.doc.startswith('*DEPRECATED') and '*' in self.doc[1:]
diff --git a/src/robot/running/context.py b/src/robot/running/context.py
index 67d52b1bf..b9bb033a4 100644
--- a/src/robot/running/context.py
+++ b/src/robot/running/context.py
@@ -108,6 +108,12 @@ class _ExecutionContext:
             self.namespace.end_user_keyword()
             self.user_keywords.pop()
 
+    def warn_on_invalid_private_call(self, handler):
+        if 'robot:private' in handler.tags:
+            parent = self.user_keywords[-1] if self.user_keywords else None
+            if not parent or parent.source != handler.source:
+                self.warn('private!')
+
     @contextmanager
     def timeout(self, timeout):
         self._add_timeout(timeout)
diff --git a/src/robot/running/userkeywordrunner.py b/src/robot/running/userkeywordrunner.py
index 7516e2f47..21ad6752d 100644
--- a/src/robot/running/userkeywordrunner.py
+++ b/src/robot/running/userkeywordrunner.py
@@ -52,6 +52,7 @@ class UserKeywordRunner:
         assignment = VariableAssignment(kw.assign)
         result = self._get_result(kw, assignment, context.variables)
         with StatusReporter(kw, result, context, run):
+            context.warn_on_invalid_private_call(self._handler)
             with assignment.assigner(context) as assigner:
                 if run:
                     return_value = self._run(context, kw.args, result)
```

**Comment by xylix** [comment]
I would vote for this to be an error instead of a warning.

**Comment by tw39124-1** [comment]
Part of the main benefit of having 'private' keywords is to avoid polluting the global namespace with keywords that are intended to be used only within file where they are defined.  What happens if there is both a 'private' and a 'public' keyword with the same name in the current scope, and that keyword name is invoked? Would Robot always dispatch the public one rather than the private one?

**Comment by robinmatz** [comment]
> If we still allow private keywords to be called from outside the file in which they are defined, what happens if there is both a 'private' and a 'public' keyword with the same name in the current scope, and that keyword name is invoked? Would Robot always dispatch the public one rather than the private one?

@tw39124-1 I have talked to @pekkaklarck at the RoboCon sprint, and we agreed that it would make sense for Robot Framework to execute the public keyword in that case.

I have just modified my PR to do exactly that.

**Comment by robinmatz** [comment]
Somehow, I am not satisfied with the current implementation. Having played around with the solution, I think the end user might find it rather strange that Robot Framework would just run the public keyword. Especially if the private keyword with the same name is nested in public keyword.

Given the following example
```robot
# resource_a.resource
*** Keyword ***
Public Keyword
    Same Name

Same Name
    [Tags]    robot:private
    No Operation
```

```robot
# resource_b.resource
Same Name
    No Operation
```

```robot
# test_suite.robot
*** Settings ***
Resource    resource_a.resource
Resource    resource_b.resource

*** Test Cases ***
Test
     Public Keyword     # Public Keyword contains a keyword with the name 'Same Name'
                                   # Since there are two keywords with the name 'Same Name', 
                                   # resource_a.Same Name being private and resource_b.Same Name being public,
                                   # with my current implementation, Robot Framework will execute the public one, 
                                   # i.e. resource_b.Same Name.    
```
As you can see, this behavior is rather inconvenient. Therefore, I would suggest, that we leave the behavior as it currently is,
i.e. Robot Framework throwing an error and asking the user to specify which keyword to run by using its long name.

I am open to other ideas/suggestions.

**Comment by tw39124-1** [comment]
Hmm. The whole point of "private" keywords is that you, as a developer, are
telling Robot: "This keyword is a 'helper' for other keywords in this
resource file only, and I don't really want it to be used from outside this
file".

If we do allow private keywords to be called from outside the file, then
the name of that keyword is effectively in the global namespace and will
clash with any other public keyword with the same name. That partially
defeats the whole purpose of having private keywords in my opinion.

A possible solution could be to modify the previous suggestion slightly so
that keyword calls which are 'unqualified' (I.e. do not include the full
resource/library name) always bind to the 'closest' definition. Taking your
example above, the call to 'Same Name' _inside_ resource_a would dispatch
to the private keyword, whereas any call to 'Same Name' from _outside_
resource_a would dispatch to the public keyword. If resource_a wants to
call the public keyword instead of the public one then it must fully
qualify it using the long name. This is effectively how native Python
behaves - closest scope wins unless the fully module path is specified.

Thanks for your work on this, hopefully we can arrive at a solution which
works for all.

**Comment by robinmatz** [comment]
Having thought about it a little longer, there are at least the following scenarios to be respected:
```
2 or more public keywords with same name --> raise multiple keywords found

1 public and 1 private keyword with same name --> run public and warn

2 or more private keywords with same name
  - if private is nested --> resolve to parent keyword and warn
  - if private is not nested --> raise multiple keywords found

1 public and 1 ore more private keywords with same name
  - if nested --> resolve to parent keyword and warn
  - if not nested --> run public and warn

2 public keywords and 1 or more private keywords with same name
  - if nested --> resolve to parent keyword and warn
  - if not nested --> raise multiple keywords found
```

Which got me thinking that from the conceptional point of view, having private keywords only be available as nested keyword within their respective .resource or .robot file seems a lot more straight forward.

**Comment by pekkaklarck** [comment]
I do agree that it's problematic if we always call the public keyword when there are public and private keywords with same name. That's obviously fine if you were planning to use the public one, but if you were planning to use the private one then this is a lot worse than failing due to multiple matching keywords.

It would probably be best if local keywords would always have precedence so that if you have

```
*** Keywords ***
Keyword 1
    Keyword 2

Keyword 2
    Keyword 3

Keyword 3
    [Tags]    robot:private
    No Operation
```

`Keyword 1` would always call `Keyword 2` and `Keyword 2` would always call `Keyword 3`. I think that should be done even if this file would import a resource file with same keywords but it certainly should occur if some other file does the import. I haven't looked at the code, and don't have time for that right now, but I believe the code handling the situation with multiple matching keywords knows about sources and could give precedence to keywords having the same source as the caller.

**Comment by pekkaklarck** [comment]
Sorry also for not reviewing the PR yet. Haven't had as much time for PRs as I hoped and there were others that had been submitted earlier that I wanted to look first.

**Comment by pekkaklarck** [comment]
Some more ideas related to this:

1. We could do it so that if there are public and private keywords matching same name, we use the public one but emit a warning. 
2. Local keywords having precedence over imported keywords should get its own issue. It would affect all keywords, not only private ones. Then this issue could then fully concentrate on private keyword.
3. Local keywords already nowadays win over imported ones when we talk about local keyword in the test case file. Local keywords winning also in resource files would thus be consistent with this old behavior.

**Comment by robinmatz** [comment]
I implemented the emission of a warning when there are two keywords with the same name, one being public one private and robotframework choosing the public one accordingly to the structure from ``LibraryKeywordRunner``. The PR is still missing atests which I hope I will get to the next couple of days.

**Comment by pekkaklarck** [comment]
Sounds great! The functionality could be enhanced still to support a situation where there's a public keyword and multiple private keywords. That ought to be a pretty rare case and not too relevant, but I would assume that implementation would be pretty trivial. There should still be an error if there's more than one public keyword and the error should probably list all available keywords.

I can submit a separate issue about local keywords having precedence over imported ones. We can tackle that when this issue is done.

**Comment by robinmatz** [comment]
I just pushed my latest changes. Now situations where there is one public keyword and multiple private keywords are also handled.

Atests are ready, so from my point of view, everything is ready for the code review.

**Comment by pekkaklarck** [comment]
Thanks for an awesome PR @robinmatz!

There are few things to be still done before this issue can be totally done:
1. Speed up checking are use keywords private. I added a comment about this to the PR already and based on my quick testing the `robot:private in handler.tags` check adds a measurable performance penalty. It can be easily be avoided in the common case where keywords don't have tags by using `bool(handler.tags and 'robot:private' in handler.tags)` and that needs to be done in the context of this issue. I plan to look at making it faster to check for this kind of special tags in general afterwards as well.
2. Small code cleanup. I mentioned this in the PR comments as well.
3. Mention the new `robot:private` tag in the list of reserved tags that I added to the User Guide a little time ago. I'll probably move that list to a separate appendix.

**Comment by pekkaklarck** [comment]
Everything I mentioned in by previous comment is now done and I consider this issue done as well. This has been the oldest issue in this issue tracker for some time and it's great to finally get it closed!

I'll look at #4366 next to avoid warnings if there are public and private keywords with same name in different files. Another thing related to this issue is making it faster to check do keywords and test have special tags.

**Comment by pekkaklarck** [comment]
Above commit added `private` info to Libdoc spec files to make it easier for external tools to check are keywords private. The info is added only if a keyword is private similarly as we only only `deprecated` when keywords are actually deprecated (#4387).

**Comment by pekkaklarck** [comment]
Still more changes to private keywords in the above commits. Now that local keywords in resource files have precedence over imported keywords (#4366), it was possible to remove the warning if there are public and private keywords with the same name. If the private keyword is a local keyword, it can be safely used. Same way if both keywords are imported, it is safe to ignore the private keyword and use the public one without a warning. There is still a warning if there's only one match and that is an imported private keyword.

**Comment by BCGST** [comment]
I am curious about @tw39124-1's [suggestion](https://github.com/robotframework/robotframework/issues/430#issuecomment-559094004) about import modifiers for resource files. I have recently switched to VS Code to try Robocorp's Language Server and using it has helped me realize that the recursive importation and access to resources can be very unwieldy. All of this to say: Is this a possibility and/or are there existing conversation on "private" importation of resources?

**Comment by pekkaklarck** [comment]
There has beennsome discussion about limiting what's imported but nothing concrete yet. Would you like to start a new thread on our Slack or Forum about this? If you have a concrete proposal, you can also submit a new issue.
