### ISSUE TITLE
Functions named `__init__` are exposed as keywords with name `__init__`, not `Init`

### ISSUE THREAD

**Issue by oboehmer** [robotframework/robotframework#4305]
I noticed robotframework 5.0 exposes the `__init__` method as keyword for https://github.com/guykisel/robotframework-faker/tree/master/robotframework-faker library. This is not happening with 4.1.3:

## with robot 5.0

```
$ pip freeze|grep robotframework-faker
robotframework-faker==5.0.0
$ pip freeze|grep robotframework=
robotframework==5.0
$ python -m robot.libdoc FakerLibrary list | grep init
__init__
$ 
```

## downgrading to 4.1.3

```
$ pip freeze|grep robotframework=
robotframework==4.1.3
$ python -m robot.libdoc FakerLibrary list | grep init
$

**Comment by pekkaklarck** [comment]
Looks strange. Need to debug why this occurs.

**Comment by oboehmer** [comment]
I wonder if it is the library's responsibility to return the _right_ keywords in their `get_keyword_names()` method, i.e. filter out dunder methods and other stuff on the library's end?

**Comment by pekkaklarck** [comment]
It turned out that also earlier Robot versions expose `__init__` but with them its name is `Init`:
```
$ python -m robot --version
Robot Framework 4.1.3 (Python 3.8.10 on linux)
$ python -m robot.libdoc FakerLibrary list init
Init
```
The name was changed as part of 44e6e7b527ae06a964602040409402b7b1ddc8a3 (scroll to the end to the file `src/robot/running/handlers.py). I think the idea was to change the name of the init methods listed under `inits` in libdoc spec files from `Init` to `__init__` that is their real name. Unfortunately the change also affects all keywords that happen to have name `__init__`. This ought to be easy to fix.

It's a separate question should FakerLibrary itself expose that `__init__` in the first place. I would assume it shouldn't, but I don't know could it actually be used for something. If it shouldn't be exposed, it could be filtered out in [get_keyword_names](https://github.com/guykisel/robotframework-faker/blob/master/robotframework-faker/FakerLibrary/keywords.py#L46).
