### ISSUE TITLE
Add project URLs to PyPI

### ISSUE THREAD

**Issue by pekkaklarck** [robotframework/robotframework#4312]
It's possible to add [project URLs](https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#project-urls) that are shown on PYPI. Possible URL include links to source code, issue tracker, Twitter, Slack, and so on. On PyPI these URLs are shown under "Project links" as seen, for example, at https://pypi.org/project/PyScaffold/. We already have PR #4248 about adding the GitHub URL, but I believe we should add also other URLs. Just need to decide what URLs to use!

**Comment by pekkaklarck** [comment]
GitHub URL was added by PR #4248. Thanks @andriyor for the PR and the idea in general! I'll check what other URLs we could add.

**Comment by emanlove** [comment]
Assuming Tracker is bugs/issues tracking. I was thinking about this link and asking what do we want to accomplish with it. For example I like the term Issues better. But to me that seems like an invitation for any looking for help to post there when instead I think for most items, if not all, we want people to come into Slack to talk about issues or even feature requests. So to avoid filling up issues with support questions I would not call it Issues nor would I put in the Tracker url. Something similar though which might be of interest is what is coming in the next release or milestones. And possible older releases or a change log. It would be great if those were one project url but I don't think Github combines those together.

I would add one for documentation going to http://robotframework.org/robotframework/. Not sure if the current url for Download is of any use since it goes back to the same pypi listing. It doesn't make sense to me to link to the pypi download files url - https://pypi.org/project/robotframework/#files - but instead I think maybe the instruction for installation in the README - https://pypi.org/project/robotframework/#installation.

**Comment by emanlove** [comment]
As for the Slack link, I think it would be helpful on Slack if the invite was combined with the main page. But that would be a feature request to Slack which who knows if that would ever be done. How about a link to the community section on rf dot org instead?

**Comment by pekkaklarck** [comment]
1. Yes, "Tracker" that I added refers to the issue tracker. Probably "Issues" would be better but it's also a good point that we only want actual bugs and enhancements requests reported there and most of the "issues" people have are actually questions that should be asked on Slack, Forum, or elsewhere. Should it be "Bug Tracker" to make it more explicit it's for bugs? Or should we just omit it altogether? There's a link to GitHub already and most users know GitHub projects have issue trackers.
2. "Change Log" link would be nice. It either needed to be updated automatically to link to the correct release notes or we needed to have a README at https://github.com/robotframework/robotframework/tree/master/doc/releasenotes to make it possible to have a static link there. That README would need to be updated to contain links to actual release notes. Automatically updating the release notes link isn't any more work than that so perhaps I should do that.
3. Link to http://robotframework.org/robotframework/ could be added and labeled "Documentation".
4. The "Download" link is got directly from setup.py `download_url`. That's kind of a mandatory field and we cannot affect how PyPI handles it. I don't see it pointing back to PyPI too big a problem.
5. One way to handle "Slack" would be linking to https://rf-invite.herokuapp.com/ and having there a link forward to https://robotframework.slack.com/ for those who already have an account. Do you @emanlove remember who set that invitation page up? We could ask them to update it.

**Comment by pekkaklarck** [comment]
URLs at https://pypi.org/project/robotframework/5.1a1/ look good to me. New can obviously be still added, and existing modified, but I think this issue can be closed.
