### ISSUE TITLE
Document that `EXCEPT` does not catch syntax errors

### ISSUE THREAD

**Issue by UliSei** [robotframework/robotframework#4314]
There are 2 places where the TRY-Except syntax is explained.
1) When I read the **Release notes for 5.0** line 123 ...
"It is also possible to have an `EXCEPT` without messages, in which case it matches **any error**."
... I thought every error would be handled by EXCEPT.
So I made two test cases ...

```
Catch any exception from keyword Fail
    TRY
        Fail    # AssertionError
    EXCEPT
        Log    EXCEPT with no arguments catches any exception.
    END

Catch any exception from keyword Log
    TRY
        Log    \nLog keyword runs on error    INFOx    # Invalid log level 'INFOx'.
    EXCEPT
        Log    EXCEPT with no arguments catches any exception.
    END
```

... and wondered why the first one passed and the second one failed.

So I'd suggest to change the note:
"It is also possible to have an `EXCEPT` without messages, in which case it matches
any error except those which are caused by wrong keyword syntax."

2) I also had a look to the [User Guide, 2.9.5](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#try-except-syntax):
"If the keyword fails with a message Error message (case-sensitive), the EXCEPT branch is executed."
Maybe it would help other users to see known examples where the Error message is not catched which is the case for
a) keywords with false syntax
b) keywords used in teardown #4293

**Comment by pekkaklarck** [comment]
EXCEPT not catching syntax errors is by design but clearly not adequately documented. Need to fix that in RF 5.0.1.

I don't think using invalid log level should really be a syntax error. I'll submit a separate issue about changing it to a normal error. It's a functional change so better to wait until RF 5.1 with it.

Finally, need to make sure we have adequate tests for syntax errors with TRY/EXCEPT. Should also test how they work with TRY/FINALLY.
