### ISSUE TITLE
Robot Framework fails to identify the test Cases based on tags if the suite file contains any Polish/German characters 

### ISSUE THREAD

**Issue by singhbhanupratap33** [robotframework/robotframework#4330]
Below is Test Suite which I tried to execute =>

```
*** Settings ***
Library    SeleniumLibrary


*** Test Cases ***
Test Case for Testing Special character support in Tags
    [Tags]    TestüCharacter
    Log    Hello Robot
    
Test Case for Testing Special character support in Keywords parameter
    [Tags]    TestCharacter
    Log    Hello Robot ü

    
```
    
Below is the error log =>

```
Command: C:\jython2.7.1b3\bin\jython.exe -J-Dpython.path=C:\jython2.7.1b3\Lib\site-packages -J-cp . -m robot.run  --listener  C:\Users\BHANUP~1.SIN\AppData\Local\Temp\RobotTempDir17085307713543368512\TestRunnerAgent.py:52548 --argumentfile C:\Users\BHANUP~1.SIN\AppData\Local\Temp\RobotTempDir17085307713543368512\args_eef814f4.arg D:\TestRobotWS
Suite Executor: Robot Framework 3.0 (Jython 2.7.1b3 on java1.8.0_281)
[ ERROR ] Suite 'TestRobotWS' contains no tests named 'TestRobotWS.TestSpecialCharacter.TestSuites.SuiteA.test case for testing special character support in tags' in suite 'TestRobotWS.TestSpecialCharacter.TestSuites.SuiteA'.


Try --help for usage information.
```

NOTE -
The issue is occuring in both the cases -
**_Case 1_** - Tags contain German/Polish Characters
**_Case 2_** - Keywords Arguments contain German/Polish Characters

Please help get this issue fixed.

**Comment by pekkaklarck** [comment]
I cannot reproduce this problem. The original example didn't show how tests were actually run (please try to make examples [short and self-contained](http://www.sscce.org/)) but I tested that if I have a file like

```robotframework
*** Test Cases ***
ä
    [Tags]    ä
    Log To Console    ä

🤖
    [Tags]    🤖
    Log To Console    🤖
```

using `--include ä` and also `--include 🤖` works as expected. I did my testing on Linux but I expect this to work on Windows as well except perhaps for using  🤖 because the terminal may not like it.

**Comment by pekkaklarck** [comment]
I did my testing using the latest Robot code on Python 3.8. The problem was demonstrated using RF 3.0 on Jython 2.7 and that combination certainly can have problems like this. It's possible that RF 3.0 doesn't work correctly and even more likely that Jython 2.7, especially on Windows, doesn't handle non-ASCII characters correctly. RF 3.0 is a pretty ancient release and hasn't been supported for years. Unfortunately we don't anymore support Jython either, but you can upgrade to RF 4.1.3 that still supports it.

**Comment by pekkaklarck** [comment]
Any new info related to this?
