### ISSUE TITLE
Invalid IF or WHILE conditions should not cause errors that don't allow continuation

### ISSUE THREAD

**Issue by adiralashiva8** [robotframework/robotframework#4348]
Following code caused this failure:

```
*** Test Cases ***
Create An Item
    # create item and set ${STATUS} test variable
    [Teardown]    Delete An Item

*** Keywords ***
Delete An Item
    IF    ${STATUS} != 'Close'
        Delete Record
    END
    Close All Browsers
```

Due to app issue `${STATUS}` is not set in code. In teardown due to missing of `${STATUS}` variable `IF` block got failed and `Close All Browsers` keyword not executed

RF Version: 5.0

**Comment by pekkaklarck** [comment]
I was able to reproduce the issue. The same problem occurs also if the expression is invalid.

**Comment by oboehmer** [comment]
Looks syntax errors takes preference over teardown context in can_continue()?

**Comment by pekkaklarck** [comment]
Same problem occurs also with WHILE loops. The root cause is that we use the `DataError` exception for signaling problems in data and also consider such exceptions to denote syntax errors that shouldn't be allowed to be caught. We have already introduced separate `DataError` subclasses for reporting errors related to variables and missing keywords to make it possible to catch those errors, but these exceptions aren't used when evaluating expressions. We could introduce another subclass for this purpose, but I believe it's better to redesign this. Instead of `DataError` being considered a syntax error by default and special cases added for less severe errors, we could make `DataError` a normal catchable error and introduce some other way to report actual syntax errors. That's a bigger task than just fixing IF and WHILE, but I believe it's better to fix the root cause to avoid these problems in the future.

One alternative how to fix this is adding a new exception like `SyntaxError` that's used with actual syntax errors that we don't want to be caught. Then we could make `DataError` a normal catchable error. An alternative would be adding an optional argument like `syntax=False` to `DataError` to allow configuring how it should be handed. Yet another alternative would be allowing to catch all errors, but that would affect also things like TRY/EXCEPT and there's a risk real syntax errors are silenced.

We should also enhance the parser to detect all syntax errors so that IDEs and other tools using it can report these errors to users without tests being run. We already have #4210 about that.

**Comment by pekkaklarck** [comment]
A related problem is that errors caused by invalid IF and WHILE conditions cannot be caught by TRY/EXCEPT.

**Comment by pekkaklarck** [comment]
I decided to make `DataError` a normal catchable error by default and add `syntax=False` argument to it to allow turning it into a syntax error. In addition to IF and WHILE conditions, this change affects at least the case where a keyword is used with invalid number of arguments. I think make that exception catchable is fine as well, because we already handle the situation that a keyword isn't found similarly (#2792).

Making errors catchable is potentially backwards incompatible change. For example, if using `TRY/EXCEPT` or `Run Keyword And Ignore/Expect Error`, earlier these exceptions have always passed through but can now be caught. I doubt there are existing tests/tasks that currently would be failing on purpose so this change ought to be safe even in a non-major version. Fixing the reported bug that IF/WHILE condition errors aren't catchable would change the behavior anyway.

**Comment by pekkaklarck** [comment]
I cannot actually think any case where this change would cause backwards incompatibility problems.
