### ISSUE TITLE
Libdoc can give bad error message if library argument has extension matching resource files

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#4351]
This problem was initially seen at:

https://github.com/robocorp/robotframework-lsp/issues/608

The language server tried to generate a libspec with a command line such similar to:

`python -m robot.libdoc test_lib::path\to\x.txt out.libspec`

and the error given was: 

`Resource file 'test_lib::d:\foo\x.txt' does not exist.`

The same could happen if dealing with a library with a module which ends with `.resource` or `.txt` or `.rest` (libdoc tries to guess, but in this particular case, where the language server knows that it's dealing with a library import, the error for the `Resource does not exist` is always wrong).

**Comment by pekkaklarck** [comment]
Isn't it so that 

    python -m robot.libdoc test_lib::path\to\x.txt out.libspec

works if `test_lib` can be imported? If it cannot, then Libdoc thinks the whole `test_lib::path\to\x.txt` is actually a resource file and reports a misleading error because importing it fails?

**Comment by fabioz** [comment]
Yes, that's correct. The error is just related to the misleading message -- on the happy path things work as intended ;)

**Comment by pekkaklarck** [comment]
Are you @fabioz fine with only fixing the problem that libraries with the last parameter having a valid resource file extension being detected wrong? That's easy and creating a test isn't hard either. I can do all this myself.

PR #4285 contains also a change that if we first try importing something as a library and then as a resource and neither works, we report both errors. That's a bit more complicated change and harder to test. I personally don't think it's worth the effort as long as the detection that is something a library or a resource isn't faulty. I actually think reporting both errors can be confusing and slightly prefer the current behavior. I don't mind changing it, though, but then the PR #4285 should be finished so that I can merge it.

**Comment by pekkaklarck** [comment]
I want to get this issue closed so I decided to fix this myself.
