### ISSUE TITLE
Parsing model: `Variable.from_params` doesn't handle list values properly

### ISSUE THREAD

**Issue by osrjv** [robotframework/robotframework#4359]
This is an issue originally reported in #4357.

The `Variable` token for suite variables is a bit broken (in my opinion) for values in general. It has a property `value` for getting its value, but for list/dict type values it will return a tuple. The matching `from_params` assumes it will only ever be a single scalar value, but that's not true for the aforementioned types.

Here's an example of a tokenized list variable:
```python
Variable(tokens=[
    Token(VARIABLE, '@{LIST}', 3, 0),
    Token(SEPARATOR, '           ', 3, 7),
    Token(ARGUMENT, '${1}', 3, 18),
    Token(SEPARATOR, '    ', 3, 22),
    Token(ARGUMENT, '${2}', 3, 26),
    Token(SEPARATOR, '    ', 3, 30),
    Token(ARGUMENT, '${3}', 3, 34),
    Token(EOL, '\n', 3, 38)]
)
```
Which is not compatible with [this method](https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/model/statements.py#L523). And lists/dicts are not covered in [the unittests](https://github.com/robotframework/robotframework/blob/master/utest/parsing/test_statements.py#L223).

**Comment by pekkaklarck** [comment]
As discussed above, `Variable.value` is a tuple by design and thus it's pretty inconsistent that when using `Variable.from_params` the value must be a string. That also makes it impossible to create variables with more that one value which is definitely a bug. In this particular case I believe it's best to accept the value both as a list and as a list/tuple of strings. That is backwards compatible and also convenient.
