### ISSUE TITLE
invalid timestamp format in xunit reports

### ISSUE THREAD

**Issue by cladstrife911** [robotframework/robotframework#4378]
Hello,

Robot Framework 5.0 
Python 3.6.8 on linux

I tried to import the xunit file generated by robot in a Polarion (Siemens) instance and reported an error on the timestamp format:
```
2022-06-22 11:26:54,985 [Worker-1: Import of test results to Test Run 0 -non-reg | u:a.m | job: xUnitFileImport] ERROR root  - Sorry, there was an error processing xUnit file unit.xml: java.text.ParseException: Unparseable date: "2022-06-21T12:51:45.440000+0000"
java.lang.RuntimeException: java.text.ParseException: Unparseable date: "2022-06-21T12:51:45.440000+0000"
	at com.polarion.alm.tracker.internal.testing.XUnitFileProcessor$CreateHandler.startElement(XUnitFileProcessor.java:205)
```

Here is the guilty xunit report generated:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="No Regression Test" tests="2" errors="0" failures="1" skipped="0" time="630.511" timestamp="2022-06-21T12:51:45.440000">
<testcase classname="No Regression Test" name="MCP Launch Test" time="43.995">
</testcase>
<testcase classname="No Regression Test" name="SCP Launch Test" time="209.313">
<failure message="IsADirectoryError: [Errno 21] Is a directory: '/backend/workspacerunner/'" type="AssertionError"/>
</testcase>
</testsuite>
```

Here the fixed version:
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="No Regression Test" tests="2" errors="0" failures="1" skipped="0" time="630.511" timestamp="2022-06-21T12:51:45">
<testcase classname="No Regression Test" name="MCP Launch Test" time="43.995">
</testcase>
<testcase classname="No Regression Test" name="SCP Launch Test" time="209.313">
<failure message="IsADirectoryError: [Errno 21] Is a directory: '/backend/workspacerunner/'" type="AssertionError"/>
</testcase>
</testsuite>
```

I'm not sure weither the issue is caused by the Polarion or by the robot but I can propose a pull request to bypass it in the src/robot/reporting/xunitwriter.py

**Comment by pekkaklarck** [comment]
This seems to be a bug in Polarion rather than in Robot. When timestamps were added in RF 5.0 (#4074), we decided to use the same `2021-11-01T10:02:24.107000` format that [PyTest](https://pytest.org) uses and that is also [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) compatible. Could you report this to Polarion and see what they think about it? I'm sure there are also other tools out there than Robot Framework and PyTest that they aren't compatible with if they don't support ISO-8601.

The real root cause for this issue is the fact that there is no official standard for the xUnit file format.

**Comment by cladstrife911** [comment]
Yes thx for your feedback and tips.
I'll report to Polarion and probably create my own xunit file.

**Comment by rikerfi** [comment]
Hi @cladstrife911,
I am writing xunit modifier which tackles problems like this. It is soon ready for publication. If you are interested, I could invite you to try it. Just let me know.

**Comment by cladstrife911** [comment]
Thx I wll have a look.

**Comment by rikerfi** [comment]
Hi,
Polarion is referring to [JUnit schema](http://windyroad.com.au/dl/Open%20Source/JUnit.xsd) which is maintained [here](https://github.com/windyroad/JUnit-Schema).

```xml
<xs:simpleType name="ISO8601_DATETIME_PATTERN">
	<xs:restriction base="xs:dateTime">
		<xs:pattern value="[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}"/>
	</xs:restriction>
</xs:simpleType>
...
<xs:attribute name="timestamp" type="ISO8601_DATETIME_PATTERN" use="required">
	<xs:annotation>
		<xs:documentation xml:lang="en">when the test was executed. Timezone may not be specified.</xs:documentation>
	</xs:annotation>
</xs:attribute>
```

Seems that timezone information is not favored. I think, to tackle this problem I could write the `Polarion` variant of `xunit output modifier`. @cladstrife911 would you like to test that?

**Comment by pekkaklarck** [comment]
The restricting regexp is buggy because it doesn't accept fractions of seconds or timezone which are both part of the ISO-8601 that it claims to support. The problem is, again, that there's no official xUnit XML standard.

When such a standard is missing, it's especially important that tools follow the [robustness principle](https://en.wikipedia.org/wiki/Robustness_principle) and "be liberal in what you accept". It could be argued that Robot (and PyTest) should "be conservative in what they do", but not including a fractions of seconds would loose information and I don't think that's a good idea.

**Comment by cladstrife911** [comment]
Polarion added a ticket to their backlog to fix this issue.
