### ISSUE TITLE
Confusing resource file relative path import

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/robotframework#4392]
The project structure is like this:
```
Resources
         --> test.resource
TestSuites
         --> test1.robot
         --> test2.robot
```
test.resource
```
*** Keywords ***
My Keyword
    Log     outer
```
test1.robot
```
*** Settings ***
Resource  Resources/test.resource
*** Test Cases ***
my test
    My Keyword
```
test2.robot
```
*** Settings ***
Resource  ../Resources/test.resource
*** Test Cases ***
my test
    My Keyword
```

Because robot will search resource relative path from the location of suite file, so test1.robot should not find test.resource

when running `robot TestSuites`, the result is as expected

when running `python -m robot TestSuites`, test1.robot can find the resource file due to the os.getpwd is added into the sys.path automatically.

this is very confusing, usually we consider the relative path is based on the os.getpwd, but in robot: `the resource file is first searched relatively to the directory where the importing file is located`, is it a good idea?

**Comment by pekkaklarck** [comment]
Robot first searches a relatively imported resource file so that they are relative to the directory where the importing file is located. If that fails, it searches resource files relatively from directories in PYTHONPATH (i.e. `sys.path`). I believe the latter happens in this case when using `python -m robot`. This behavior is by design and cannot be changed.
