### ISSUE TITLE
Error when `--doc` or `--metadata` value matches an existing directory

### ISSUE THREAD

**Issue by lesnake** [robotframework/robotframework#4394]
Let say that I have a directory named pekka, running 
`robot --metadata dev:pekka any.robot `
will fail with message  :
`[ ERROR ] Reading documentation from an external file failed: [Errno 21] Is a directory: 'pekka'`

The same happens with -D pekka

I think the issue comes from this line :
`if os.path.exists(value):`
line 143 in src/robot/conf/settings.py, which should be :
`if os.file.exists(value):`
which will filter out directories to reach the failing open/read.

Issue related for sure with #4008

**Comment by pekkaklarck** [comment]
Yeah, should use `os.path.isfile` instead of `os.path.exists`.

**Comment by pekkaklarck** [comment]
This isn't too severe because with documentation it's unlikely your doc is only a directory name and with metadata there's a possibility to use any path as a value if there's a [space after the colon](http://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#setting-free-metadata) like `-metadata dev: pekka`. Definitely worth fixing anyway.
