### ISSUE TITLE
Adding Tags `robot:remove`, `robot:flatten` & `robot:expand`

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4420]
It would be nice to add keywords tags for flatten, remove and for consistency also expand, however i personally had never a use for expand.

We do now add `robot:private' and i had the need of generally flatten some keyword always.
It is about keywords that are kind of complex but do not add any value in the logs.

For example in SeleniumLibrary you can register a keyword as locator strategy. That keyword is always executed, when a locator is used. That kind of blows the logs.
With the new `Keyword Tags` we could tag a resource file and mark all keywords in there as "flatten" so that sub-keywords are not in the logs.

Also in Browser you can register a Keyword to run on failure, but for some users that should not appear in the logs as an own keyword.

**Comment by Snooz82** [comment]
Example in Browser library with a failure keyword:

Unflattened Content:
<img width="1047" alt="image" src="https://user-images.githubusercontent.com/41592183/181905177-5d9a72e0-75de-4162-92af-7b32415f07a3.png">

Flattened Content:
<img width="940" alt="image" src="https://user-images.githubusercontent.com/41592183/181905185-0de3ff30-93a4-47a1-a40c-dd298556d866.png">

**Comment by Snooz82** [comment]
That would not only be handy for Resource files that should only contain "Atomic" Keywords, but also for Libraries that use internally `BuiltIn().run_keyword()` function which normally cause to have more keyword layer in the log.html.

**Comment by Snooz82** [comment]
At the same time we should consider to remove **Tags** with the prefix `robot:`  from libdoc.
so when all keywords in a Library are tagged as `robot:flat` or `robot:flatten` it should not show up in the tag drop down.

<img width="232" alt="image" src="https://user-images.githubusercontent.com/41592183/181905352-3dcbde2a-708c-405c-81c9-9d2d10086bfb.png">

**Comment by pekkaklarck** [comment]
:+1: for `robot:remove`, `robot:flatten` and `robot:expand`. Not showing `robot:*` tags in Libdoc HTML output is probably a good idea as well (but they should be included in spec files). These enhancements aren't totally related, though, and implementation will be different. It would thus probably be better to have separate issues for each enhancement. That would mean we'd have dedicated place for possible design discussions and it's also possible we implement only some of the features in one release and others later.

**Comment by pekkaklarck** [comment]
`robot:expand` would probably be pretty trivial to implement because we only needed to hook it up with the current `--expandkeywords` functionality (#2698). Could definitely be included in RF 5.1.

Not showing `robot:*` tags in Libdoc HTML outputs is trivial as well. Needed to decide do we want to exclude all such tags or are the tags that would be good to show. Possibly Libdoc could get new CLI option to control that tags to show as well.

`robot:remove` ought to be pretty easy to implement because we just needed to replace the logger responsible on writing output.xml with a logger that does nothing. This is a bit risky feature, though, because it means there are absolutely no traces left and debugging possible problems is hard. Obviously you need to explicitly set the tag for that to happen, and it can be easily removed if needed, so probably that's fine.

`robot:flatten` would probably be the most useful enhancement of all these and shouldn't be overly complicated to implement either. It would basically require enhancing the current output.xml writer so that it can be configured to not do anything when a keyword starts and ends.

Do you @Snooz82 have time and interest to look at implementing any of these? They ought to all be possible still in RF 5.1 time frame, but I don't think it's mandatory to have them all in that release.

**Comment by pekkaklarck** [comment]
I also agree that using `robot:flatten` with all keywords in a resource file would be a good use case for the new `Keyword Tags` setting (#4373).

**Comment by Snooz82** [comment]
@pekkaklarck by looking into the Result classes, i saw there is that "flatten pattern" or so, that is constructed by iterating over all cli arguments to that cli option. 

Would that be the right place to just add the tag `robot:flat` or `robot:flatten` tag?

seems to be trivial.

**Comment by Snooz82** [comment]
What would you prefer  flat or flatten

**Comment by pekkaklarck** [comment]
Extending the existing flattening functionality probably isn't a good idea. It works by omitting certain elements when parsing output.xml. A better solution would be not writing those elements into output.xml in the first place. That would save disk space, avoid unnecessary file input, and make parsing output.xml faster when there would be no elements to omit.

A different question is, should `--flattenkeywords` when used with `robot` also work so that matching elements aren't written to output.xml at all. I guess it should.

`robot:flatten` sounds a bit better than `robot:flat` for me. It's also consistent with `--flattenkeywords`.

**Comment by pekkaklarck** [comment]
A nice thing with flattening is that messages are preserved so debugging problems shouldn't be more complicated than normally. Not needing to expand various keywords could even make it easier. This is the reason we could flatten already during execution.

A problem with removing keywords altogether is that everything is removed. `--removekeywords` avoids that problem by not removing keywords if they contain failures or warnings, but that's not something we can do during execution. When a keyword starts and we are about to write the opening `<kw>` element, we cannot know will the keyword fail or emit a warning. If we add `robot:remove`, we need to decide should we handle that after execution as well.

**Comment by Snooz82** [comment]
Need to be split in separate issues.

**Comment by Snooz82** [comment]
Note to consider:

a tag that changes the loglevel of a keyword context and revert that when the keyword ends.

`robot:log_level:ERROR`

**Comment by Snooz82** [comment]
At the moment flatten and removing happens in resultwriter.
It should be considered that `robot:remove` and `robot:flatten` could already be processed during execution and therefore already reduces the size of consumed memory and size of output.xml.

**Comment by pekkaklarck** [comment]
Yes, flattening should definitely happen at the execution time. As I've commented above, it's a pretty safe operation as all log messages are preserved. Removing keywords is more problematic in that regard and it's not as useful as flattening either.

One good reason to split this into multiple issues is that we can make decisions about each feature separately. The proposed approach to control log level sounds good too but also it needs a separate issue.

**Comment by pekkaklarck** [comment]
New #4584 now covers flattening. I don't consider others too important and won't submit issues for them at least now. `robot:remove` may also be hard to implement safely, but `robot:expand` would be easy.
