### ISSUE TITLE
TRY/EXCEPT not working in Teardown

### ISSUE THREAD

**Issue by DirkRichter** [robotframework/robotframework#4422]
Failing keywords in teardown are not handled with TRY/EXCEPT:

Sample robot file:
```
*** Settings ***
Test Teardown  TeardownKW

*** Keywords ***
TeardownKW
    TRY
        Fail  1
        Fail  2
        RETURN
    EXCEPT
        Log  err handled
    END

*** Test Cases ***
DraftTest
    Log  This test is used for experiments.
```

Results in:
![grafik](https://user-images.githubusercontent.com/20930315/183032104-2ee98a53-7e2c-4e76-8c2c-a7004aa16064.png)

**Expected**: Keywords **Fail 2** and **RETURN** should _not_ be executed due to **Fail 1** is failing.

Tested in RF version 5.0 and 5.1a2

**Comment by pekkaklarck** [comment]
Failures don't stop execution in teardown because we want all cleanup activities to be done. That means TRY/EXCEPT structures work differently in teardowns than elsewhere and this was already reported as #4293. As you can see in the comments of that issue, we decided not to change this because teardown behavior changing inside TRY/EXCEPT would have been strange and also complicated to implement. We instead decided to make it possible to explicitly disable the continue-on-failure mode that's automatically on in teardowns. For more details about that see #4303.

**Comment by alainsiroishw** [comment]
Hello @pekkaklarck 

Would you consider the below best practice: prioritzing `robot:recursive-stop-on-failure` over `robot:stop-on-failure` in teardown?

We could add this to the Robot Framework User Guide.

```robot
*** Settings ***
Documentation    I am MyResource.resource


*** Keywords ***
Common Complex Operation Used In Many Tests
    # [Tags]    robot:stop-on-failure
    # We want to avoid putting the above tag in many kewords
    TRY
        Log    I am an operation that succeeds or fails 50/50 of the time
        RETURN    ${True}
    EXCEPT
        RETURN    ${False}
    END
```

```robot
*** Settings ***
Documentation    I am a Robot file with a test
Resource    MyResource.resource
Test Teardown    Teardown After Every Test


*** Test Cases ***
Test One
    Log    I am checking something in Test One


*** Keywords ***
I Am Required In Teardown
    [Tags]    robot:recursive-stop-on-failure
    # Best way is to put this recursive tag here, where the behavior is required.
    Common Complex Operation Used In Many Tests

I Am Also Required In Teardown Please
    Log    Doing some teardown stuff

Teardown After Every Test
    I Am Required In Teardown
    I Am Also Required In Teardown Please
```
