### ISSUE TITLE
All iterations of templated tests should be executed even if one is skipped

### ISSUE THREAD

**Issue by David-Lannion** [robotframework/robotframework#4426]
In the documentation, it is written that :

> Templated tests are also special so that all the rounds are executed even if one or more of them fails. It is possible to use this kind of [continue on failure](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#continue-on-failure) mode with normal tests too, but with the templated tests the mode is on automatically.

In particular : `all the rounds are executed even if one or more of them fails`
However, if one is skipped, none the following rounds are not executed.
I don't know if it was intended or not but it caused some problems on my tests.

Example:
```
*** Test Cases ***
Eat yellow fruits
    [Documentation]    Eat only yellow fruits, Fails if item given is a fruit which is not yellow and skip if item is not a fruit
    [Template]    Check fruit and eat it
    red_apple       # FAIL
    banana          # PASS
    plane           # SKIP => not a fruit
    lemon           # should be PASS but is not executed 
```

**Comment by pekkaklarck** [comment]
The documentation is from the time when the SKIP status didn't exist. I believe we didn't really think about this when implementing SKIP, but I have a vague feeling this has been discussed at least once afterwards. I kind of agree it would make sense to run all iterations in this case, but then again explicitly skipping an iteration can be considered to mean "skip remaining iterations".

If we agree to run all iterations also after SKIP, we need to decide what status the test should have if some iterations FAIL. Nowadays an iteration ending with SKIP after an iteration with FAIL gives the test the SKIP status. I believe FAIL after SKIP should behave the same way, but we could also consider changing the overall logic so that any failed iteration gives the test the FAIL status. That would match how any failed test gives a suite the FAIL status regardless of the status of the other tests. Then again, SKIP in test teardown overrides possible earlier FAIL.

I think it would be good to hear opinions from others regarding to these semantics. I'll start a thread about this on the #robotframework channel on our Slack.

**Comment by pekkaklarck** [comment]
If we'd change semantics so that tests get the FAIL status if any iteration fails, regardless are some iterations skipped or not, we should also decided how to handle a case where some iterations pass and some are skipped. I think logically then the test status should be PASS. The test would then get the SKIP status only if all iterations are skipped. This is the same logic we use when deciding the suite status.

**Comment by olesz** [comment]
Hi,

Is there any update on this?
Is this going to be implemented in the near future?

Thanks!

**Comment by olesz** [comment]
@pekkaklarck How can I ask any of the maintainers to check the pull request I created on this enhancement? (https://github.com/robotframework/robotframework/pull/5244)

**Comment by pekkaklarck** [comment]
PR #5244 by @olesz looks so promising that I added this to RF 7.2 scope. The change is backwards incompatible, because earlier a SKIP in an iteration after a failed iteration causes the test to be skipped, but after the change the test will fail. I don't think this is so severe that the change needed to wait for a major release, though. Although this issue is now labeled as an enhancement, the current behavior where iteration failures are masked by skips could also be considered a bug.

**Comment by pekkaklarck** [comment]
Implemented in PR #5244 by @olesz. Big thanks for the contribution!

**Comment by pekkaklarck** [comment]
I tested how this works with templates using IF and FOR. To my small surprise everything mostly worked well, but there were problems at least with error reporting when using FOR. I'll reopen this, investigate problems and fix them.

**Comment by olesz** [comment]
Do you want me to do the debugging? If you share what you've found maybe I can help finding the root cause.

**Comment by pekkaklarck** [comment]
I already found the root cause and I'm working with the fix. I just noticed another issue (#5276) and fix that first.

**Comment by pekkaklarck** [comment]
This example demonstrates the problem:
```robotframework
Example
    [Template]    Run Keyword
    FOR    ${x}    IN    a    b    c
        Skip    ${x}
    END
```

**Comment by pekkaklarck** [comment]
The following changes seem to fix the issue. I'm not sure is this the best fix yet, but I'll think about that more after lunch.

```diff
--- a/src/robot/running/bodyrunner.py
+++ b/src/robot/running/bodyrunner.py
@@ -56,18 +56,19 @@ class BodyRunner:
                 self._run = exception.can_continue(self._context, self._templated)
         if passed:
             raise passed
-        if errors and self._templated:
+        if errors and self._templated and any(e.skip for e in errors):
             errors = self._handle_skip_with_templates(errors, result)
         if errors:
             raise ExecutionFailures(errors)
 
     def _handle_skip_with_templates(self, errors, result):
-        if len(result.body) == 1 or not any(e.skip for e in errors):
+        if len(result.body) == 1 and not result.body[0].type == 'FOR':
             return errors
         if all(item.skipped for item in result.body):
             raise ExecutionFailed('All iterations skipped.', skip=True)
         return [e for e in errors if not e.skip]
 
+
 class KeywordRunner:
```

**Comment by LucianCrainic** [comment]
Hello @pekkaklarck, i just noticed that on a template if i want to skip a specific input case it skips the whole test and does not continue with the other input cases. 

Example of what i am talking about below,

```robotframework
*** Test Cases ***
Eat yellow fruits
    [Documentation]    Eat only yellow fruits, Fails if item given is a fruit which is not yellow and skip if item is not a fruit
    [Template]    Check fruit and eat it
    plane             # SKIP
    banana          # should be PASS but is not executed
    lemon            # should be PASS but is not executed 
```

**Comment by pekkaklarck** [comment]
It seems that the issue with FOR loops is best handled with `ForRunner`. It's even simpler than what I proposed earlier. I created plenty of new tests that all now pass. I'll run all acceptance tests locally and commit changes if there are no regressions.
