### ISSUE TITLE
`Get Time` returns current time if it is given input time that matches epoch

### ISSUE THREAD

**Issue by spu06th** [robotframework/robotframework#4438]
To reproduce in master:
```
*** Test Cases ***
Get Time at epoch
    ${get_time_val}=    Get Time    format=epoch    time_=1970-01-01 00:00:00
    Should Be Equal As Strings    ${get_time_val}    0    Time strings are not equal
```
Running the above test results in:
```
FAIL: Get Time.Get Time at epoch
Status of 'Get Time at epoch' should have been PASS but it was FAIL.

Error message:
Time strings are not equal: 1660728200 != 0
```

It looks like in line 3327 of [builtin.py](https://github.com/robotframework/robotframework/blob/edcf6e79c63da2edf6bcc01ec986aa70b1868854/src/robot/libraries/BuiltIn.py#L3327) that `parse_time` returns 0 (expected I assume), and that when `0` is provided as  `time_` argument to `get_time` ([robottime.py line 200](https://github.com/robotframework/robotframework/blob/edcf6e79c63da2edf6bcc01ec986aa70b1868854/src/robot/utils/robottime.py#L217)), the following line returns `time.time()`:
```time_ = int(time_ or time.time())```

**Comment by pekkaklarck** [comment]
I tested the provided example locally and it failed with this error:
> Time strings are not equal: -7200 != 0

That 7200 means two hours which is kind of logical because I'm in Finland which is UTC+2. That said, DST is now active so I'm not sure should it be actually three hours. Anyway, the value is totally different than 1660728200 that you got. Which time zone are you?

Could you test what you get with the following example using DateTime? In my case it also fails with `-7200.0 != 0` so these two keywords agree.

```robotframework
*** Settings ***
Library       DateTime

*** Test Cases ***
DateTime
    ${x} =    Convert Date    1970-01-01 00:00:00    result_format=epoch
    Should Be Equal    ${x}    ${0}
```

**Comment by spu06th** [comment]
That's interesting. I am currently British Summer Time (UTC+1).

Running the suggested passes for me.

**Comment by pekkaklarck** [comment]
There's clearly a bug in the code. `time_ = int(time_ or time.time())` uses the current time if `time_` is zero. It's default is `None` so it should be something like `time_ = int(time.time() if time_ is None else time_)`. That `int` conversion looks a bit strange as well and I may change that too, but ti's not related to this issue.

**Comment by pekkaklarck** [comment]
The reason the original example as well as the example I provided both fails when I run them like `-7200.0 != 0` is that `1970-01-01 00:00:00` is considered a local time and we were UTC+2 then. `-7200` is thus just right. My example succeeds if you are somewhere that was in UTC+0 when that  local time occurred. And due to the bug in our code the original example fails in that case. Luckily the bug is easy to fix.

**Comment by pekkaklarck** [comment]
The original example fails the same way as in the original description here in Finland if the timestamp is changed to `1970-01-01 02:00:00`.

**Comment by spu06th** [comment]
Nice, thank you.
