### ISSUE TITLE
`Run Keywords`: Execution is not continued in teardown if keyword name contains non-existing variable

### ISSUE THREAD

**Issue by peerasut** [robotframework/robotframework#4453]
When I have 2 keywords: the first one is embedded keyword, the second one is either embedded or normal keyword. I use these 2 keywords within `[Teardown]` and with using `Run Keywords` keyword. If the first keyword fails because it could not find embedded argument, it fails and does not continue to execute the second keyword.

For example:
```
*** Test Cases ***
TC teardown fail
    ${var}    Set Variable    1
    [Teardown]    Run Keywords    Embbedded Kw ${b}
    ...    AND   Log  ${var}

*** Keywords ***
Embbedded Kw ${x}
    Log    ${x}
```

The result: `Embbedded Kw ${x}` fails because arg `${b}` is not found. But it does not continue to execute ` Log  ${var}`.
<img width="712" alt="image" src="https://user-images.githubusercontent.com/68002612/188796839-7ea5c3ff-93c0-4dd3-9b07-a3cc1f0e08c0.png">

As stated in [documentation](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#test-setup-and-teardown) that `Teardown` has ability to continue on failure. So, I think that in case of embedded keyword it should continue to execute event it could not find the embedded argument.
<img width="970" alt="image" src="https://user-images.githubusercontent.com/68002612/188797470-11b62976-18f3-473c-b7d3-917778c2c237.png">

As I have been in this community for a while, I could implement this one if it's not too complex.

Note: I used Robot Framework 5.0.1

**Comment by pekkaklarck** [comment]
I can reproduce the problem, but the problem isn't actually with embedded arguments but with `Run Keywords`. The same problem occurs if you use `Run Keywords` in teardown so that the keyword name is a variable. For example, here the second keyword isn't run:

```robotframework
*** Test Cases ***
Example
    No Operation
    [Teardown]    Run Keywords    ${bad}    AND    Fail 
```

Embedded arguments work fine in teardowns if you use them inside a normal keyword like here:
```robotframework
*** Test Cases ***
Example
    No Operation
    [Teardown]    Keyword

*** Keywords ***
Keyword
     Embbedded Kw ${bad}
     Fail    This is run
```

The problem with `Run Keywords` is pretty easy to fix. The fix also gives be an idea how we possibly could fix #1595 that affects embedded args when used with `Run Keywords` or other keywords running keywords internally.
