### ISSUE TITLE
Libdoc: Type hints aren't shown for types with same name as Javascript variables available in browser namespace

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4464]
Because `Proxy` is a valid variable name in the browser, it tries to show the function `Proxy()` instead of the node with the id Proxy.

That effect is visible with Browser Library [New Browser](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser) Keyword.

Just click <Proxy> in the arguments

**Comment by pekkaklarck** [comment]
The example makes it clear there's a problem but I don't understand what causes it. Could you please clarify? Is that `Proxy()` as function in Browser, Libdoc or JavaScript?

**Comment by pekkaklarck** [comment]
The issue was that `Proxy` is a variable in Javascript namespace used by browsers and Libdoc wasn't able to show type hints for types with that name. There are various other such Javascript variables so conflicts can occur easily when people start using custom argument converters more. The issue only affected Libdoc's HTML outputs and it was fixed in PR #4465 by @Snooz82 .
