### ISSUE TITLE
ExecutionStatus error may have attribute like full_message before cut off long one.

### ISSUE THREAD

**Issue by dbdlahd1027** [robotframework/robotframework#4467]
![image](https://user-images.githubusercontent.com/43832506/191143251-3cda4737-5afb-4327-9252-1cc662b98e43.png)

**Comment by pekkaklarck** [comment]
You propose that we add separate `full_message` that contains the original message? What would be the use case for it?

**Comment by dbdlahd1027** [comment]
I created the function to add fail messages to the buffer and raise them all together.
And then I found that some fail messages might be too long to show.

```
# add to buffer function
        try:
            values = Builtin().run_keyword(kw_name, *kw_args)
        except (HandlerExecutionFailed, ExecutionFailed) as err:
            if is_truthy(fatal_error) and bool(err.dont_continue):
                raise err
           # add full message to buffer
            full_message += ....
```
Fail added to buffer might be HTML, full buffer message will be cut and disappear for HTML tag unclosed.

![image](https://user-images.githubusercontent.com/43832506/191881526-1af8d2de-503d-46ae-ad05-a0e521a68aa3.png)

![image](https://user-images.githubusercontent.com/43832506/191899163-ef18ae97-d9c0-4e2e-90c2-8877baade026.png)

**Comment by pekkaklarck** [comment]
Sorry, but I still don't fully understand what you want. Do you want exceptions to have a new attribute `full_message` that libraries and possibly other external tools could use? Or do you propose that messages wouldn't be cut in the first place? Or something else?

Adding `full_message` is something we can consider, we'd need to know which exceptions would need that new attribute to be useful. If this is what you want, perhaps you could create a PR with changes that you'd need?

Not cutting the message by default isn't an option, because they can otherwise be so big that they mess up logs and reports. You can, however, use the `--maxerrorlines` command line option to configure or even disable it.

**Comment by pekkaklarck** [comment]
No updates, closing.
