### ISSUE TITLE
BuiltIn: `Call Method` loses traceback if calling the method fails

### ISSUE THREAD

**Issue by kbogineni** [robotframework/robotframework#4476]
I see the below call is not logging traceback on failure and throwing the error message instead.
Call method   ${obj}  ${method}  ${args} 

It would be great to log the traceback incase of any failure, it will be helpful to identify the issue soon.

Need the fix in version 4.1

**Comment by kbogineni** [comment]
@pekkaklarck

**Comment by pekkaklarck** [comment]
Could you please clarify the problem?

**Comment by kbogineni** [comment]
> Could you please clarify the problem?

if call_method is failing with an error then we are not getting trace back of the failure, we are just getting the failure message and it is hard to debug such failures

**Comment by pekkaklarck** [comment]
Do you mean `BuiltIn.call_method` or something you created? Have you tried running tests with `--loglevel debug`?

**Comment by kbogineni** [comment]
> Do you mean `BuiltIn.call_method` or something you created? Have you tried running tests with `--loglevel debug`?

It is with call_method and I tried with `--loglevel debug` also but no use

**Comment by kbogineni** [comment]
call_method is raising the exception but  logging the traceback as None

**Comment by pekkaklarck** [comment]
It's true that if I have something like
```robotframework
*** Test Cases ***
Example
   Call method    string    upper    bad
```
the traceback is just this:
```
Traceback (most recent call last):
  None
RuntimeError: Calling method 'upper' failed: TypeError: upper() takes no arguments (1 given)
```

I don't think there could be any traceback to show in this case, though. You don't get anything more if you run same thing directly in Python:
```python
>>> 'string'.upper('bad')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: str.upper() takes no arguments (1 given)
```

Do you have a concrete example where there should be a traceback but isn't?

**Comment by kbogineni** [comment]
Yes, Assume that we have one python module and I have called a method and want to see the at which line of the code the failure appeared?? how to see at which line it is failed

**Comment by kbogineni** [comment]
> 

If you see the above example the traceback is given(if you execute python directly)

**Comment by pekkaklarck** [comment]
Yeah, there's problem if the exception occurs somewhere else. The reason is that the original traceback is lost because we raise a new `RuntimeError` if calling the method fails. Python 3 makes it possible to attach context information to the exception like `raise NewError from old` but it seems that our traceback formatting code needs to be enhanced slightly as well. Fixing this is so easy that I can still include it into RF 5.1.

Notice that the fix won't be backported to RF 4.1 or any other older version. If you need to use older versions and must have a fix, you need to patch your installation yourself. Alternatively, and probably better, you should change your code into a library and call those methods as keywords.

**Comment by pekkaklarck** [comment]
A trivial fix would be just reraising the original exception, but then the error message would change and that could cause backwards compatibility problems. Better enhance the code so that traceback is preserved.

**Comment by pekkaklarck** [comment]
It would actually be enough to fix only the traceback formatting code to get the original traceback included. The problem there is that if the exception has no normal traceback to show, traceback of the original exception isn't shown either. This was a mistake made when adding support for chained exceptions in general in RF 5.0 (#4039). I decided to add `from err` to `call_method` anyway because it makes the resulting error a bit better.

**Comment by kbogineni** [comment]
Thanks
