### ISSUE TITLE
[Question] Robotframework Grammar

### ISSUE THREAD

**Issue by ALX99** [robotframework/robotframework#4495]
Hello team,

I'm thinking about writing a treesitter grammar for the robotframework syntax and was wondering if there is a grammar or spec defined for it somewhere? Something similar to what [Go](https://go.dev/ref/spec) or [Python](https://docs.python.org/3/reference/grammar.html) provides for example.

This would be helpful in creating the parser as opposed to trying to come up with it yourself from the User Guide.
Would be great if anyone could help me out if something like this exists.

Keep up the great work with the framework :)

**Comment by pekkaklarck** [comment]
First of all, a [tree-sitter](https://tree-sitter.github.io/tree-sitter/) based parser for Robot Framework would be awesome! Unfortunately there's no official grammar spec for Robot and due to the nature of our grammar creating one would be somewhat complicated. One big problem is that we support both space and pipe separated data, but the latter is so little used that you can probably ignore it. We should actually consider deprecating and removing it altogether.

There was a similar question about the grammar, for the exact same purpose, on [Twitter](https://twitter.com/NorwegianHubro/status/1518556579053850625) some time ago. If I got it right, the person asking it was @Hubro here on GitHub and he seems to have done at least something in his [tree-sitter-robot](https://github.com/Hubro/tree-sitter-robot) repository. Perhaps it would be possible to collaborate? There could also be others in our community interested on this.

One person I suspect is interested on this is @Snooz82 who was recently talking about updating our Pygments lexer. That's something we definitely need to do, but a tree-sitter parser would allow syntax highlighting etc. also outside Python world.

**Comment by pekkaklarck** [comment]
A formal grammar for Robot would be useful in general even if it wouldn't be able to cover all special cases we have. If that's needed for a tree-sitter, I'd be happy to help creating one.

**Comment by ALX99** [comment]
Thank you very much for your help.

I don't think it currently would be worth your time to create a formal spec/grammar for it just for this single case of me trying to create a TS grammar for it. Although I think a grammar/spec is always a nice thing to have to so that one has defined what is allowed and what is not.

I've had a look in @Hubro's repo and forked it and have began expanding it & fixing issues. Work on it may be a bit slow since I have a day job to attend to and since it's my first time writing any kind of grammar. The generous syntax for robot files is not helping either, but I'll see what I can do and try to support the most common features.

On another note, when exploring the syntax I created the following file:
```robot
*** Test Cases ***
Test
    # None of these work
    hi a
    \ hi a
     hi a

*** Keywords ***
 ${arg} a
    Log To Console  Called with ${arg}
```

But I can't seem to be able to ever call this keyword. Just thought it was an interesting find, or maybe missing something.

**Comment by Hubro** [comment]
I worked on the tree-sitter parser for a couple of weekends for the purpose of improving syntax highlighting of Robot files in my editor. I got it to a point where syntax highlighting worked pretty much perfectly in the repositories I work in, so the incentive to keep working on it disappeared :smile:

One thing in particular I never added support for is conditional (`IF/ELSE`) blocks, but we don't have any instances of those at my job so it hasn't bothered me.

If you're interested in the syntax highlighting, these are the queries I'm using:

```
(comment) @comment
(ellipses) @punctuation.delimiter

(section_header) @keyword
(extra_text) @comment

(setting_statement) @keyword

(variable_definition (variable_name) @variable)

(keyword_definition (name) @function)
(keyword_definition (body (keyword_setting) @keyword))

(test_case_definition (name) @property)

(keyword_invocation (keyword) @function)

(argument (text_chunk) @string)
(argument (scalar_variable) @string.special)
(argument (list_variable) @string.special)
(argument (dictionary_variable) @string.special)
```

**Comment by pekkaklarck** [comment]
This is a great example of scratching your own itch! 😃

For the wider audience, it would be great if the results were made more publicly available and so that others in the community could contribute as well. One possible step to that direction would be moving the repo to [MarketSquare](https://github.com/MarketSquare). If you are interested on that, @emanlove ought to be able to help if needed.

**Comment by pekkaklarck** [comment]
@ALX99, is there a space before the `${arg} a` keyword definition? Need to investigate this.

**Comment by bollwyvl** [comment]
Semi-related: To support CodeMirror 6 in [jupyterlab_robotmode](https://github.com/MarketSquare/jupyterlab_robotmode) we'll eventually need one that worked with lezer... though perhaps it may be possible to map [treesitter to lezer]( https://discuss.codemirror.net/t/mapping-tree-sitter-trees-to-lezer-trees/2362/4).

Either way: having a repo of grammars that can be pitted against each other, and the source of truth in this repo, would be a possible direction, which specific editor implementations could reuse.

**Comment by Hubro** [comment]
@ALX99 @pekkaklarck 

Quick update in case you're interested. Over the last month I finished my tree-sitter parser for Robot: https://github.com/Hubro/tree-sitter-robot

It's now included in Neovim and Helix by default and it has queries for syntax highlighting, indentation and folding.

**Comment by ALX99** [comment]
Awesome work @Hubro!
