### ISSUE TITLE
Using settings valid in Settings section with tests or keywords (e.g. `[Metadata]`) causes confusing error message

### ISSUE THREAD

**Issue by kamil-kasprzak** [robotframework/robotframework#4527]
When [Metadata] setting is added to test case file, error message is wrong.

Steps to reproduce:
1. Create test case file.
2. Add [Metadata] setting to the test case in test case file.
3. Run test case file.

Actual results:
_The error is returned: [ ERROR ] Error in file (...) on line ...: Setting 'Metadata' is not allowed in **suite initialization file**._

Expected:
While test case file is exectuted (not test suite init file), error message should be different.

Env:
RF 6.0

**Comment by pekkaklarck** [comment]
I was able to reproduce this with the following test:
```robotframework
*** Test Cases ***
Example
   [Metadata]   not supported
   [Bad]        value
   No Operation
```

**Comment by kamil-kasprzak** [comment]
@pekkaklarck , I checked all settings available in the Settings section but not supported for test cases in Test Cases settings.

*** Test Cases ***
Example
   [Library]           setting not supported
   [Resource]          setting not supported
   [Variables]         setting not supported
   [Documentation]     setting not supported
   [Metadata]          setting not supported
   [Suite Setup]       setting not supported
   [Suite Teardown]    setting not supported
   [Test Tags]         setting not supported
   [Force Tags]        setting not supported
   [Default Tags]      setting not supported
   [Keyword Tags]      setting not supported
   [Test Setup]        setting not supported
   [Test Teardown]     setting not supported
   [Test Template]     setting not supported
   [Test Timeout]      setting not supported
   [Task Setup]        setting not supported
   [Task Teardown]     setting not supported
   [Task Template]     setting not supported
   [Task Timeout]      setting not supported
   [Bad]        non-existing setting
   No Operation

For each above not supported settings it returned error message that setting "is not allowed in suite initialization file.".  Error message should point that given setting is not allowed for the test case in test cases file.

**Comment by pekkaklarck** [comment]
It's pretty easy to fix this so that `[Metadata]`, or any other setting that's valid in a test case file but not with a test, is reported like `Non-existing setting 'Metadata'.` the same way as we handle totally invalid settings like `[Bad]`.

If we wanted to, we could also use a different message like `Setting 'Metadata' not allowed with a test.` in this case similarly as we do if you try to use, for example, `Metadata` in a resource file. That's not overly complicated but I'm still not certain is that worth the effort.

If we do use a different metadata with settings that are valid in a test case file but not with an individual test, we absolutely should also handle a situation where you use a setting that's valid with a keyword like `[Arguments]` but not with a test. Obviously also settings valid with tests like `[Template]` but not with keywords should get a special treatment. This isn't too hard either but adds to the overall effort.

Instead of handling all these cases separately, we could also simply change the normal error message to something more context specific like `Tests do not have have setting 'Metadata'.`

**Comment by pekkaklarck** [comment]
Fixed this so that with all settings that are valid somewhere are reported differently than totally invalid settings.
