### ISSUE TITLE
[Yaml file] When yaml file contains nested dict/list that has key = `items` it can't be accessed the dict/list with dotDict method

### ISSUE THREAD

**Issue by peerasut** [robotframework/robotframework#4558]
Yaml file (dotdict.yaml)

```
data:
  item: 123
  items: 456
  other_key: 789
```

Robot file

```
*** Settings ***
Variables    dotdict.yaml

*** Test Cases ***
TC dotdict
    Log    ${data}
    Log    ${data['item']}
    Log    ${data}[item]
    Log    ${data.item}
    Log    ${data['items']}
    Log    ${data}[items]
    Log    ${data.items}
```

When running `TC dotdict` test case, I got the following log
![image](https://user-images.githubusercontent.com/68002612/206360798-cc550a43-e881-4c20-9637-eb219d12ba39.png)

**Version:**
- RF 6.0.1
- Python 3.10.5

**Comment by pekkaklarck** [comment]
The reason is that our `DotDict` is based on `dict` and `dict` has `items()` method:
```python
>>> d = {'a': 1, 'b': 2}
>>> list(d.items())
[('a', 1), ('b', 2)]
```
Same issue occurs also with other `dict` attributes like `copy` or `__eq__`. Unfortunately I don't think we can do anything to this. If we'd allow `DotDict` items to mask `dict` methods, you couldn't use `DotDict` instances as normal dictionaries in all cases. That would probably cause bigger problems than this one and would also be a backwards incompatible change. The way to avoid this issues is using the `${var}[key]` syntax as you discovered.

**Comment by peerasut** [comment]
> The reason is that our `DotDict` is based on `dict` and `dict` has `items()` method:
> 
> ```python
> >>> d = {'a': 1, 'b': 2}
> >>> list(d.items())
> [('a', 1), ('b', 2)]
> ```
> 
> Same issue occurs also with other `dict` attributes like `copy` or `__eq__`. Unfortunately I don't think we can do anything to this. If we'd allow `DotDict` items to mask `dict` methods, you couldn't use `DotDict` instances as normal dictionaries in all cases. That would probably cause bigger problems than this one and would also be a backwards incompatible change. The way to avoid this issues is using the `${var}[key]` syntax as you discovered.

Thanks for the explaination. So, I think we could close this issue.
