### ISSUE TITLE
Run Keyword in custom lib init  cause "Incompatible child element 'kw' for 'robot'" issue

### ISSUE THREAD

**Issue by jiangliangnihao2022** [robotframework/robotframework#4582]
1  Test3.py init use run keyword to invoke an external KW
```Python
#!/usr/bin/python3
from robot.libraries.BuiltIn import BuiltIn

class Test3:
    def __init__(self):
        self.name = "Test3"
        self.builtin = BuiltIn()
        self.builtin.run_keyword("Print Log", self.name)
    def test_kw(self):
        return self.name

```
2 Test Case
```
*** Settings ***
Library     ../lib/Test3.py

*** Test Cases ***
001 Run Keyword In Lib Init Issue
    [Tags]    Priority
    ${res}=    Test3.test_kw
    Should Be Equal    ${res}    Test3

*** Keywords ***
Print Log
    [Arguments]    ${msg}
    Log To Console    \n****------****\n\n${msg}\n
```
When execute this robot file, case would pass but reporting errors while generating reports 
```
C:\Users\ellgjjg\Documents\work\git\trainning\training\robot\issue>robot 1__init_run_keyword.robot

****------****

Test3

==============================================================================
Init Run Keyword :: Variable priorities.
==============================================================================  
001 Run Keyword In Lib Init Issue
****------****

Test3

001 Run Keyword In Lib Init Issue                                     | PASS |  
------------------------------------------------------------------------------  
Init Run Keyword :: Variable priorities.                              | PASS |  
1 test, 1 passed, 0 failed
==============================================================================  
Output:  C:\Users\ellgjjg\Documents\work\git\trainning\training\robot\issue\output.xml
[ ERROR ] Reading XML source 'C:\Users\ellgjjg\Documents\work\git\trainning\training\robot\issue\output.xml' failed: Incompatible child element 'kw' for 'robot'.

Try --help for usage information.

C:\Users\ellgjjg\Documents\work\git\trainning\training\robot\issue>
```
[output.zip](https://github.com/robotframework/robotframework/files/10334342/output.zip)

I think there some issue to parse the output.xml,More importantly, the KW "Print Log" is executed twice, please help to look on this issue, We have some requirements that call external KW when lib is initialized. Thanks!

**Comment by pekkaklarck** [comment]
The problem is that running a keyword like that causes `<kw>` elements to be written to the output.xml into place where they aren't allowed. Library `__init__` is called when the library is imported to see what keywords it contains and suite execution hasn't started at that point yet. For libraries with test (default) and suite scope it's called again when a new test or suite starts causing the executed keyword to be run multiple times. Trying to make all this work would be a really big task and I don't think it's worth the effort.

Typically you should use setups and teardowns for initialization like this. If you really need to do that within a library, you can use library listeners. Then you can get a notification when a suite starts and can run a keyword at that point.
