### ISSUE TITLE
`Path.resolve()` being used when it shouldn't

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#4600]
`Path.resolve()` in Python will resolve symlinks and substs, and in general that's not something wanted (you want to keep in the same structure that was asked).

i.e.: if you run something starting in a subst in windows, say: `X:` which points to `c:\drive_x`, if you resolve the subst for something it'll actually point to `c:\drivex` and not `x:` anymore.

The following are all bad usages of `path.resolve()`. What you want is usually `path.absolute()`.

https://github.com/robotframework/robotframework/blob/master/tasks.py#L12
https://github.com/robotframework/robotframework/blob/master/utest/running/test_builder.py#L9
https://github.com/robotframework/robotframework/blob/master/utest/running/test_builder.py#L13
https://github.com/robotframework/robotframework/blob/master/utest/model/test_testsuite.py#L50
https://github.com/robotframework/robotframework/blob/master/utest/testdoc/test_jsonconverter.py#L7
https://github.com/robotframework/robotframework/blob/master/src/robot/parsing/suitestructure.py#L96
https://github.com/robotframework/robotframework/blob/master/utest/result/test_resultbuilder.py#L12

The only good usage for `path.resolve()` is getting the canonical representation (if you want to create some cache for a given inode, in general just making the paths absolute is what's wanted).

**Comment by fabioz** [comment]
i.e.: if I start to run something from `x:\`, I don't expect to see `c:\drive_x` in sources given by RF.

**Comment by pekkaklarck** [comment]
Good point. I wanted to use `Path.resolve()`, instead of `Path.absolute()`, because the latter doesn't normalize paths, but resolving symlinks is likely not a good idea. Apparently the reason `Path.absolute()` doesn't normalize the path is that also that is problematic with symlinks. And apparently that's also the reason there doesn't seem to be any method for normalizing paths in `pathlib` in general.

I would say that with tests using `Path.resolve()` is fine, unless that usage prevents someone from running tests, but need to look at the usages in the code.
