### ISSUE TITLE
Make Robot Framework compatible with `zipapp`

### ISSUE THREAD

**Issue by franzhaas** [robotframework/robotframework#4613]
Hi,

as just shown at the open space after applying some small changes, we can have zipapps that do contain a viable robotframework installation.

There is a pull request for this feature.

https://github.com/robotframework/robotframework/pull/4612

Best regards,
Franz

**Comment by pekkaklarck** [comment]
It would be great if Robot Framework was compatible with the [zipapp](https://docs.python.org/3/library/zipapp.html) module. We can then later decide should we also publish zipapp distribution ourselves, but that's not part of this issue.

There is PR #4612 adding the zipapp support and it looks pretty good. I'll add this to RF 6.1 scope so that we don't forget about it.

**Comment by pekkaklarck** [comment]
This was implemented by @franzhaas in PR #4612. Thanks for contribution!

**Comment by pekkaklarck** [comment]
I decided to remove the new Zipapp section from the installation instructions in the end. The reason is that creating Zipapps is more about distribution than installations. It could be documented somewhere in the User Guide if considered useful, though, but then the instructions should be a bit more detailed. A separate project for Zipapp related stuff is probably a better idea.
