### ISSUE TITLE
Dialogs created by `Dialogs` should bind `Enter` key to `OK` button

### ISSUE THREAD

**Issue by maxgerhardt** [robotframework/robotframework#4619]
When creating a popup dialog asking the user for an input, the dialog already nicely auto-focuses into the textbox, allowing immediate keyboard input. However, then pressing the Enter key does nothing. I would have expected it to to be the same as pressing the left "OK" button. It would be very useful to have that so that users don't have to use the mouse to press that button.

Example:
```robot
*** Settings ***
Library    Dialogs

*** Test Cases ***
Get Device Number
  [Documentation]  Grab the device number from the user
  [Tags]           production
  ${dev_num_usr}=  Get Value From User  Input the number of the device (on the label)  invalid
```

![image](https://user-images.githubusercontent.com/26485477/214284763-c384356d-e07d-47f5-b034-09578c47483a.png)

I'm on Ubuntu Budgie 22.04.

The code for it might be [here](https://github.com/robotframework/robotframework/blob/15e11c63be0e7a4ce8401c7d47346a7dc8c81bf5/src/robot/libraries/dialogs_py.py#L51-L58).

**Comment by pekkaklarck** [comment]
You can press the Ok button by first using Tab to change the focus to it and then pressing Space. I think this is the default Tkinter behavior. We have, however, bound Esc to close the dialog and binding Enter to press the left button ought to be fine as well. If we do that, we should also think should Esc press the right button instead of just closing the dialog. That would probably make a difference only with the PASS/FAIL dialog.

**Comment by pekkaklarck** [comment]
This is easy to implement so let's do it. I have also done some other enhancements to Dialogs seen above. Especially giving dialogs focus also on Windows is convenient.

**Comment by pekkaklarck** [comment]
<Enter> will be bind to the left button on all dialogs. It's typically OK, but on the PASS/FAIL dialog it's PASS. <Esc> will continue closing the dialog, not pressing the right button. That means on that on the PASS/FAIL dialog it won't press FAIL.
