### ISSUE TITLE
Automatic argument conversion and validation for `Literal`

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#4633]
Look at this moment:
```py
def foo(a: Literal[1, 2, 3]): ...
```
```robot
Something
    foo    1
```

Currently, robot will send a `"1"` to this function, which is invalid, I would expect robot to convert the string to an int.

- #4630

**Comment by pekkaklarck** [comment]
Quick intro about `Literal` for those who don't know about it. It's a Python 3.8 feature that allows typing like this:

```python
from typing import Literal

def open_something(mode: Literal['r', 'w']):
    ...
```

Type checkers then validate that you only can use `open_something` with literal values `'r'` and `'w'`. This means you cannot even use a variable:

```python
open_something('r')     # ok
open_something('a')     # fail
mode = 'r'
open_something(mode)    # fail
```

For more details see https://peps.python.org/pep-0586/.

**Comment by pekkaklarck** [comment]
If we'd add support for `Literal` conversion, we needed to first decide how it should behave. Alternatives below.

1. Make it work like in Python so that we validate the keyword is only used with a literal value, not using a variable. This would be complicated to implement simply because Robot's argument converters are used after variables have already been processed. We certainly could add special checking with literals, but I'm afraid it would be lot of work. I personally don't consider this behavior so important and actually consider not being able to use variables with literals pretty annoying in Python as well. Anyway, we need to make a decision and the behavior needs to be documented in the User Guide.

2. Only convert the value but don't validate it. For example, if you use `a: Literal[1, 2, 3]`, like in the description, arguments would be converted to integers. This seems to be what PR #4630 does. Personally I would find this pretty strange, because it would allow calling the keyword with _any_ value that is of the accepted type, not only with the explicitly listed values. We obviously could do that, but we'd be so far away from Python behavior that I honestly don't think it's a good idea. I also fails to see the benefit of this in Robot context, because you could just specify the type directly like `a: int`.

3. Do conversion and validation. This would mean that if you use `a: Literal[1, 2, 3]`, using argument `4` would cause a failure. I consider this a much better behavior than the above. I'm still not sure would this be that useful addition, though, because you can already now use `Enum` and `IntEnum` to get the same behavior.

Could you @KotlinIsland explain your use case for `Literal` conversion? How would it be better than using using normal type conversion (e.g. `a: int`) or, if you want to limit the allowed values, better than using enums?

**Comment by pekkaklarck** [comment]
Implementing `Literal` conversion wouldn't be too complicated, but there are few extra challenges:

- `Literal` is new in Python 3.8 but we still support Python 3.6 and 3.7. It MUST be possible to keep using Robot with those versions without installing `typing_extensions` that contains a backport.
- [PEP 586 explicitly states](https://peps.python.org/pep-0586/#legal-parameters-for-literal-at-type-check-time) that `Literal` only accepts ints, byte and unicode strings, bools, Enum values and `None`, but this is not enforced. You can, for example, use `Literal[{}, 3.14, object]` and there's no exception. To avoid surprises, our code needed to validate that values have accepted types.

**Comment by KotlinIsland** [comment]
> Make it work like in Python so that we validate the keyword is only used with a literal value, not using a variable. 

This isn't how python works, confusing I know, but `Literal` can be a variable, as long as that variable has the type of the literal:
```py
a: Literal[1] = 1
b: Literal[1] = a
```
This code is valid and correct usage of `Literal`.

**Comment by KotlinIsland** [comment]
> explain your use case for Literal conversion?

`Literal` is pythonic and much more natural and easier to write than using `IntEnum` (I didn't even know you could use `IntEnum` here for this).

**Comment by KotlinIsland** [comment]
>You can, for example, use Literal[{}, 3.14, object] and there's no exception. To avoid surprises, our code needed to validate that values have accepted types.

I disagree with this. The pep does not specify what these denotions would mean, so we would have to invent it ourselves.

**Comment by pekkaklarck** [comment]
Python/Mypy considers this wrong:
```pyhton
def fun(arg: Literal[1, 2]):
    ...

var = 1
fun(var)    # fails typecheck
```

It would be thus somewhat odd if you could use that function as a keyword like this:
```robotframework
*** Variables ***
${VAR}    1

*** Test Cases ***
Example
    Fun    ${VAR}
```
If we wanted to be true to how Python/Mypy handles `Literal`, we needed to only allow using literal values like `Fun    1`. Alternative we could add some special syntax to tell that `${VAR}` contains literal value `1` like you can do in Python:

```python
var: Literal[1] = 1
fun(var)    # typechecks
```

I personally feel the need to use `var: Literal[1] = 1` instead of `var = 1` super annoying and would be fine accepting just `Fun    ${VAR}` assuming the value of the variable is valid. That would anyway deviate from Python/Mypy behavior and needed to be documented.

Notice also that although Python itself allows using `Literal[3.14]`, it yields an error with Mypy. Robot accepting it would be _really_ strange in my opinion.

Finally, it would be great if you could explain what's your actual use case for `Literal` conversion. Is it just type conversion or is the plan to also validate the actual value?

**Comment by KotlinIsland** [comment]
The difference between the two is that robot doesn't have any static type checking, it has runtime typechecking.

Consider the following, the current behavior of converting from `str` to `int` differs from mypy in the exact same way that the conversion from `str` to `Literal[1]` does. Therefor the proposed functionality is expected, correct and understandable. 
```py
def fun(arg: Literal[1, 2]): ...
def bar(arg: int): ...

var: object = 1

fun(var)    # fails typecheck
bar(var)    # fails typecheck
```
```robot
*** Variables ***
${VAR}    1

*** Test Cases ***
Example
    Fun    ${VAR}    # does not fail conversion
    Bar    ${VAR}    # does not fail conversion
```


It's also possible to use `Final` to infer the type as a literal.
```py
var: Final = 1
```

**Comment by pekkaklarck** [comment]
As I've written earlier, I don't have problems with Robot's variables being usable if an argument has `Literal` as a type. It's nevertheless against the main use case of `Literal` in Python and I believe this deviation should be documented.

Could you clarify what concrete use case you you have for `Literal` conversion? You clearly don't want to require users to actually use literal values, so I assume you are interested in type conversion and possibly value validation. For type conversion you can already use `arg: int` or `arg: int|str` without being limited to just few types like with `Literal`. For value validation you can already use enums which, in my opinion, are more convenient and safer in Python code than using strings (e.g. `if arg is Direction.UP` vs. `arg == 'UP'`). I can see that using just `Literal['UP', 'DOWN']` requires less code than creating an enum, though.

**Comment by pekkaklarck** [comment]
Runtime implementation of `Literal` conversion isn't too complicated, but how to represent them with Libdoc isn't obvious for me. Storing this type info to Libdoc specs as a string like `Literal['UP', 'DOWN']` would be easy, but it wouldn't make the information about actual values available to editors or other spec users. With unions we store the nested types separately for exact this reason, and we are right now planning how to handle parameterized generics like `list[int]` (#4538). With `Literal` we needed to store both the value and its type, so it would likely need some additional spec changes. Have you thought how you'd like `Literal` to work in this regard?

**Comment by KotlinIsland** [comment]
> It's nevertheless against the main use case of Literal in Python and I believe this deviation should be documented.

I don't understand what you mean by this, how is this not the primary use case for `Literal`? Despite the fact that a value is being converted, to me this seems completely normal and consistent with the entire typing landscape and existing type converters.

Type converters are not type-checking the code, they are converting something from the wrong type to the correct one, and raising an exception when they are unable. To me, if something is annotated as `Literal[1]` and `2` is passed into the type converter, it should fail stating that it is impossible to convert the input to the specified type.

> You clearly don't want to require users to actually use literal values

I think there is a point of confusion here, `Literal` does not mean 'literal' value. the expression `'a' + 'b'` has the type `Literal['ab']`, yet there was no string literal `'ab'` denoted at any time. `Literal[True]` really just means a more restricted form of `bool`:

```py
from typing import Literal

a: bool
b: Literal[True, False]

a = b  # no error
b = a  # no error
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=338d654f7b90a5dfab656f7e24063559) Here we can see that `Literal[True, False]` is _identical_ to `bool` in every way, because `Literal[True]` is just a restricted `bool` and when combined with `Literal[False]` it equates to every possible instance of `bool`.

I think this pretty clearly demonstrates my point, if `Literal[True, False]` is identical to `bool` then I would expect robot type converters to treat the following two parameters exactly the same:
```py
def foo(a: bool, b: Literal[True, False]): ...
```
(Although due to #4060, I think this would actually work substantially better than the current `bool` converter)

Another demonstration:
```py
a: bool = 1 > 0
if a is True:
    reveal_type(a)  # Revealed type is "Literal[True]"

b: bool = 1 > 0
assert b is True
reveal_type(b)  # Revealed type is "Literal[True]"
```
[playground](https://mypy-play.net/?mypy=latest&python=3.11&gist=05bf040f77fa3ba8b7c2caf400326628) This is showing that `Literal` does not mean 'literal', in this case mypy can determine a more narrow('restricted') type for the variable that was annotated with `bool`.

So given that, I don't want users to use literal values, I want users to use `Literal` types. I want the values passed to be converted to values conforming to the `Literal` types I have specified.

> I assume you are interested in type conversion and possibly value validation

Yes this is exactly what I want, and I believe this is exactly consistent with other type converters behavior.

> use enums

I did respond to this earlier, regarding adding type annotations to code, I have never seen a usage of `IntEnum` to represent a literal (or at all actually), so to me it feels very out of place. Also this makes interactions between normal code and functions for robot keywords much more clunky (mypy not understanding things like it would with `Literal`s).

> Have you thought how you'd like `Literal` to work in this regard?

The way they currently show seems perfect. Although I suppose it would be good to have a help doc linked like `int` does.

![image](https://user-images.githubusercontent.com/65446343/219541404-06895623-9d8e-4352-8bfb-0f20ff02d51d.png)

**Comment by pekkaklarck** [comment]
My understanding is that `Literal` really means a literal value. For example, if I have
```python
from typing import Literal

def fun(a: Literal[1, 2]):
    pass

fun(1)      # ok
fun(1+1)    # fail (line 7)
a = 1
fun(a)      # fail (line 9)
```
I get these errors with Mypy:
```
example.py:7: error: Argument 1 to "fun" has incompatible type "int"; expected "Literal[1, 2]"  [arg-type]
example.py:9: error: Argument 1 to "fun" has incompatible type "int"; expected "Literal[1, 2]"  [arg-type]
```
If I got the above right, `1` matches `Literal[1, 2]` while `1+1` and `a` that contains `1` don't. I personally consider both of these failures stupid, and would be totally fine allowing
```
Fun    ${var}
```
with Robot as long as `${var}` contains `1` as a string or as an integer. The behavior would nevertheless be inconsistent with Mypy behavior.

**Comment by pekkaklarck** [comment]
If we don't want to mandate using actual literal values, then implementing this is pretty straightforward. I see two open design decisions, though:
- Should strings be allowed in case-insensitive manner? For example, if you have `Literal['yes', 'no']`, should we accept `YES` and convert it to lower case? Our enum conversion is case-insensitive and that is pretty convenient, but it could be argued that we should be more strict with "literal" values.
- How to handle documentation. We already now show the type as `<Literal[1, 2]>` in Libdoc's HTML output but because there's no converter that's just a string and there's no documentation link as with `<int>`. We could easily make the whole `Literal[1, 2]` part a link to generic documentation about literal conversion. Is that enough or should we also link each value (`1` and `2` in the previous example) to separate type/value specific documentation? The latter is something we plan to do in the future with parametrized types like `list[int]`(#4538)`.

**Comment by pekkaklarck** [comment]
> The mypy docs state that `Literal`s are just equal to a certain value and do not mandate 'literal denotation'.

Are you certain about that? Why then in the [docs you referenced](https://mypy.readthedocs.io/en/stable/literal_types.html#literal-types) they have the last overload?

```python
@overload
def fetch_data(raw: Literal[True]) -> bytes: ...
@overload
def fetch_data(raw: Literal[False]) -> str: ...

# The last overload is a fallback in case the caller
# provides a regular bool:

@overload
def fetch_data(raw: bool) -> Union[bytes, str]: ...

def fetch_data(raw: bool) -> Union[bytes, str]:
    # Implementation is omitted
```

`bool` can only have values `True` and `False`, so `raw: Literal[True]` and `raw: Literal[False]` in first two overloads cover _all_ possible values. My understanding is that the last overload with just `raw: bool` is there to make it possible to have like

**Comment by KotlinIsland** [comment]
The example you are using here is an edge case where mypy is not behaving correctly, I've raised an issue against it https://github.com/python/mypy/issues/14764.

It's easy to demonstrate that this isn't the case:
```py
def func(a: Literal[True] | Literal[False]):
    pass

a: bool
func(a) # no error, despite the fact that `a` is not a literal
```
I think this clearly demonstrates my point, and can't be ignored. If `Literal` in _any_ way was more specialized than just 'equal value', then this exaple would violate Liskov Substitution Principle.
</br>
>Core behavior
>Literal types indicate that a variable has a specific and concrete value. For example, if we define some variable foo to have type `Literal[3]`, we are declaring that foo must be exactly equal to `3` and no other value.

- https://peps.python.org/pep-0586/#core-behavior

The pep for `Literal` states that the variable must have a value equal to it's parameter. **Nowhere** in the pep does it mention that the value has to be literally denoted.

> It's nevertheless against the main use case of Literal in Python and I believe this deviation should be documented.

I can understand that you think this is the scenario, I used to think the exact same thing you are saying. But what would be the use case of such a restriction? I think that `Literal`s naming is confusing, and that a much more understandable name would have been `Value`.

**Comment by pekkaklarck** [comment]
Do you mean that the reason Mypy complains about by [earlier example](https://github.com/robotframework/robotframework/issues/4633#issuecomment-1435177943) is that it's buggy? That would be surprising but I guess it's possible. Being able to use variables, not only literal values, would make `Literal` a lot more useful in Python typing in my opinion. On the other hand, Mypy not handling something this simple wouldn't give me too big trust in Mypy in general.

**Comment by KotlinIsland** [comment]
> Mypy is not perfect in regards to type narrowing and type inference. It uses heuristics to determine what and when a type will change.

\- [here](https://github.com/robotframework/robotframework/issues/4633#issuecomment-1435476820)

In [that example](https://github.com/robotframework/robotframework/issues/4633#issuecomment-1435177943) mypy is not narrowing to a `Literal` (typescript does the [same thing](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMAFAQwFyIIwEpEDeiAvgLABQFANgKZSIBuiAvDhag7hUA)). This is likely due to potential non-local mutation:
```py
def a(x: Literal[1]): ...
def b():
    nonlocal v
    v = 2

v = 1
b()
a(v)
```

Mypy has many bugs, and even more limitations (like [this](https://mypy.readthedocs.io/en/stable/literal_types.html#limitations)).

> Mypy not handling something this simple wouldn't give me too big trust in Mypy in general.

Yeah, I know right. This reason is why I started basedmypy.

**Comment by pekkaklarck** [comment]
I've been thinking about this a bit lately and believe we should try to get this done in RF 7. This is why:
- Although enums are really convenient, in simple cases something like `Literal['yes', 'no']` is often good enough and doesn't require creating a separate class.
- Enums don't work over the remote interface because we'd need the actual type. Once #4711 is implemented, literal definitions can be sent over the XML-RPC channel as strings and parsed by Robot.
- RF 7 requires Python 3.8 or newer. All supported versions thus support `Literal` natively.

There are some design decisions still to be agreed, but nothing too complicated. The converter code is also currently in a flux due to #4711. It needs to be finished before this can be implemented.

**Comment by pekkaklarck** [comment]
Changes to type conversion in RF 7.0 had caused a regression using `Literal`. Fixing that (see f60af34397ee4c3926c27680f6837fec6e958058) required enhancing `TypeInfo` so that it takes `Literal` into account. That was already so big step towards supporting literal conversion and validation that I decided to do a quick prototype. The prototype was successful and now I have this functionality implemented.

**Comment by pekkaklarck** [comment]
I never learn. Although the prototype worked well, getting Literals to work properly with Libdoc required some more work. Part of that was due to `TypeInfo` behaving and being used badly. Had I known how much time all this takes, I wouldn't have re-added this to RF 7.0 scope. Anyway, now everything ought to be ready. Hopefully `Literal` conversion turns out to be useful!
