### ISSUE TITLE
(:lady_beetle:) Using bare `Union` as annotation is not handled properly

### ISSUE THREAD

**Issue by KotlinIsland** [robotframework/robotframework#4638]
```py
from typing import Union
def foo(a: Union): ...
```
```robot
Tc
    foo    1
```

```
👉 python -m robot.run test.robot
==============================================================================
Test                                                                          
==============================================================================
Tc                                                                    | FAIL |
AttributeError: __args__
------------------------------------------------------------------------------
```

**Comment by pekkaklarck** [comment]
The reason for this issue is that when you have `a: Union`, our code recognizes it as union but unlike `Union[...]` the plain `Union` doesn't have `__args__`. That's easy to fix by changing `union.__args__` to `getattr(union, '__args__', ())` and after that the failure changes to same as if you use `a: ()` (#4646). It's clearly not valid to have a union without any types and we could make it an explicit error. Alternatively we could just return the value as-is in this case, but I believe failure is better.
