### ISSUE TITLE
Add public API to query is Robot running and is dry-run active

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#4666]
For libraries it would be helpful to know if RF is running, or if a library is just imported as python package or by libdoc, which also would be the case when language servers would analyze them.

https://robotframework.slack.com/archives/C0K0240NL/p1677318363986369

Proposal would be two boolean properties either in BuiltIn or robot.api?!

`robot_running` or `robot_is_running` would be True if there is an execution context.
`dry_run_active` or `dryrun_is_active` would be True if there is a running context and the dryrun is ongoing.

**Comment by pekkaklarck** [comment]
This is related to execution context handling which is a part that will require redesign and rewrite in the future. Because the code is likely to change, getting the information via internal APIs isn't safe and adding a public API is thus a good idea. Probably easiest to add the proposed propertys to BuiltIn now. When context handling is redesigned, we may expose the whole context via `robot.api` somehow.

**Comment by pekkaklarck** [comment]
`dru_run_active` won't be useful for keywords because library keywords aren't even run in the dry-run mode. It is, however, available in library `__init__` and also for listeners. We may also in the future allow running library keywords in dry-run. We already have `robot:no-dryrun` that user keywords can use for disabling execution in dry-run.
