### ISSUE TITLE
Unable to pass the test case name as part the the request object

### ISSUE THREAD

**Issue by kpattar** [robotframework/robotframework#4725]
I need to pass the test case name also as a header, but there is not provision to edit the header even in listener

**Comment by pekkaklarck** [comment]
Could you please clarify.

**Comment by kpattar** [comment]
Below is my sample test case 
Subtraction Test
    [Tags]    web
    Open Browser    http://localhost:8080/add/sub/    headlesschrome
    Input Text    id=num1    10
    Input Text    id=num2    5
    Click Button    submit
    Wait Until Page Contains    5

    Close Browser
    Here  I need to pass the test case name which is "Subtraction Test" along with the params to the url as headers so that I can access the name of the test case from the API end

**Comment by pekkaklarck** [comment]
I still don't understand what you try to do. Your example shows a simple web test but your issue is related to sending something to an API. Please explain this more thoroughly so that others who don't know anything about your use case can understand it.

Make also sure that the formatting is good, in the current form the above comment is hard to read and requires horizontal scrolling. There's a link to formatting instructions when you write or edit a comment. I include it here as well in case you haven't noticed it:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

Finally, notice that this issue tracker is for bug reports and enhancement requests. If you are just asking for help, please use Slack, Forum, or other such support forums instead.
