### ISSUE TITLE
The usage of `pythonpathsetter` is breaking calls such as `python -m robot.libdoc`.

### ISSUE THREAD

**Issue by fabioz** [robotframework/robotframework#4734]
In the language server usually I run robotframework tools as:

`python -m robot.libdoc`

Now this no longer works because of the error:

```
  File "X:\robocorpws\robotframework\src\robot\libdoc.py", line 41, in <module>
    import pythonpathsetter
  ModuleNotFoundError: No module named 'pythonpathsetter'
```

This happens because the `robot` folder itself is not (and should not be) in the pythonpath.

The usual way of doing this would be an idiom such as:

```
import sys
import os
try:
    import robot
except ImportError:
    sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    import robot
```

i.e.: Using the pythonpathsetter as a module you need to import where you need the pythonpath to be set in a way for it to work (to then fix the pythonpath) isn't the ideal solution...

**Comment by pekkaklarck** [comment]
I can reproduce the issue and know why it occurs. When we added zipapp support (#4613), `pythonpathsetter` looked like it would cause issues and although it didn't (it simply wasn't used with zipapps), I decided to simplify it a bit and add better documentation why it's needed and what it does. As part of that (see commit 9a87af3b7414a48a8d618109851d08dc04310d9e) I simplified it's usage in entry points so that

```python
if 'robot' not in sys.modules and __name__ == '__main__':
    import pythonpathsetter
```
was changed to
```python
if __name__ == '__main__':
    import pythonpathsetter
```
and `if 'robot' not in sys.modules` check was done in `pythonpathsetter` itself. That worked in other cases but clearly not when using `python -m robot.libdoc` approach.

I'll fix this right away to that entry points use the old approach. I still believe it's better to preserve `pythonpathsetter` because it allows having documentation in a single place. Instead of the module import directly modifying `sys.path`, we could consider changing the usage to something like `from pythonpathsetter import set_pythonpath; set_pythonpath()`, but I'm not sure would it be that much better.



Does this happen for you with RF 6.0, RF 6.1a1, or only with the latest code? I can reproduce this with the latest code

**Comment by pekkaklarck** [comment]
This ought to be now fixed. Can you @fabioz test the fix in your environment?

**Comment by fabioz** [comment]
It seems to be working now.

**Comment by pekkaklarck** [comment]
Thanks for testing and for reporting the issue!
