### ISSUE TITLE
Add tags, test setup/teardown/template/timeout to TestSuite model 

### ISSUE THREAD

**Issue by luv-deluxe** [robotframework/robotframework#4737]
`robot.api.TestSuite` allows to load ROBOT into model from either JSON, dictionary or local file.

If one uses `Force Tags` or `Default  Tags` or `Test Tags`, these item are not added to the model, and eventually are not dumped with e.g. `TestCase().to_json()` method. Tags go directly to `TestCase().all_tests` attribute (or into `tests` field in JSON) so it's hard to recreate it back.

I am working on a reciprocal method, that saves model into `*.robot` file with provided separator. Ultimate goal here is to dynamically alter model and dump it as a ROBOT.

If would be cool if, if tags were added as model attributes, as e.g.:

```python
class TestSuite:
    tags = {
        "default": ["tag1", "tag2"],  # to be deprecated in RF 7.x
        "force": ["tag1", "tag2"],    # to be deprecated in RF 7.x
        "test": ["tag1", "tag2"]      # new defaults
    }
```
This way one can distinguish what tags are "suite-wide" and which are "test-specific".

Or maybe I'm missing tags location, but went thru `6.1a1` source and haven't seen any tag attribute other than for test cases.

**Comment by pekkaklarck** [comment]
Tags related settings in the Settings section, the same way as `Test Setup/Teardown/Template/Timeout`, are just a way to specify metadata for all tests in the whole suite without duplication. They are stored in the parsing model that represents files in the file system, but they aren't needed anymore in the executable `TestSuite` model.

Not having these settings in the executable model obviously makes it harder to save that model to a file. It's shouldn't be too hard, though. In the simplest case all saved tests could simply get whatever metadata they have, and it wouldn't be much harder to move metadata that all tests share to Settings. Some algorithm could also be deviced to handle cases where most, but not all, test share e.g. a setup. In all these cases the saved file could look different than the original file, but there's not enough information about the syntax (e.g. positions and comments are missing) in the running model to recreate the original file anyway. If that's important for you, use the parsing model that preserves everything and is also otherwise designed for this usage.

**Comment by pekkaklarck** [comment]
Having both test related settings from the Settings section and the actual settings tests have in the running model would make it harder to edit tests. You needed to take both settings into account or otherwise results would be unexpected.  This could potentially break existing tools. Other problems include more complicated API in general and increased size and complexity of the JSON model.

Due to problems being big and benefits small, I close this issue. Being able to save a running model into files would nevertheless be convenient in some cases, but I believe it can be done well enough also without this change.
