### ISSUE TITLE
Make library imported using `Import Library` available for the rest of the suite

### ISSUE THREAD

**Issue by oborichkin** [robotframework/robotframework#4748]
I am calling `Import Library` keyword in the `__init__.robot:Suite Setup` (Not the `Settings.Library` because I'm getting library address only at runtime):
```robot
*** Settings ***
Suite Setup  Global Suite Setup

*** Keywords ***
Global Suite Setup
    Import Library  Remote  ${addr}:${port}  WITH NAME  MyLib
    MyLib.My Method  # <- this works
```
However, when I'm trying to access library from test cases inside this suite, it's not available:
```
tests/
  __init__.robot
  01__Basic.robot
```
**01__Basic.robot**:
```robot
*** Test Cases ***
Basic Test Case
    MyLib.My Method  # <- Gets error
```

Is this intended? Can I make my library available to whole suite and all nested suites?

**Comment by pekkaklarck** [comment]
It's a design decision that imports in init files aren't seen by child suites. It's the same with normal imports and with `Import Library`. The reason is that otherwise changes to init files could have undesirable effects to child suites and we believe it's better to have explicit imports. Imports being seen by child suites would have some benefits, but I believe the problems, including backwards incompatibility problems, would be bigger.

If you always run the whole directory, you can use `Set Global Variable` in your init file and then import the library normally in child suites.
