### ISSUE TITLE
jquery-tmpl JS library used in log.html is not maintained anymore

### ISSUE THREAD

**Issue by tsrinivas7** [robotframework/robotframework#4750]
We had hit issue where if a Keyword prints about 10k lines the Chrome/Edge browser mainly with Windows OS doesn't load the content and it simply crashes!, we realize its to do with JS library which loads the content. We also tried --split log option, its same behaviour with that too. Its also suggested on the jquery-tmpl repo to try jsRender.
I'm creating this ticket to track the migration of JS library. 
I had tried with Robot framework 4.2.1. Please let me know if this is already addressed in newer version.

**Comment by pekkaklarck** [comment]
We have issue #4304 about replacing the jquery-tmpl and rewriting the HTML outputs in general. I hope we could do that in RF 7 later this year, but that's a rather big task and it's unsure do we have resources for that.

If your log file is so big that browsers fail to load it, there's a good change changing the underlying tech doesn't help much. I'd recommend you to enhance the tests or the underlying libraries so that there's logging and/or nested keyword structures. For example, instead of logging 10k individual messages, try logging few bigger ones.
