### ISSUE TITLE
[Bug] Suite with new "Name" setting cannot be selected by "--suite" option

### ISSUE THREAD

**Issue by d-biehl** [robotframework/robotframework#4758]
Tried a little bit with new feature of RobotFramework 6.1b, think I found an error:

Given this simple suite file with name `Suite with Custom Name.robot`, where I use the new "Name" setting to override the name of the suite:

```robot
*** Settings ***
Name    Suite with Custom Name

*** Test Cases ***
First
    Log    First Test
```

when I want to execute only the suite with this name and select the suite via "--suite" option from command line, like:

```
robot -d .\results\ --suite "Dummy-Blah.Tests.Suite with Custom Name" .
```

I only get:

```
[ ERROR ] Suite 'Dummy-Blah' contains no tests in suite 'Dummy-Blah.Tests.Suite with Custom Name'.
```

Also when I use the original suite name "Dummy-Blah.Tests.Suite with Name" I get the same error.

**Comment by otemek** [comment]
I'll be glad to help fix this issue, but I need some clarification, probably from the maintainers:
1. What name should be considered as the "proper" one while passing to the `suite` parameter? The real filename or the argument for the `Name` setting in `*** Settings ***` section?

**Comment by pekkaklarck** [comment]
We noticed this issue when adding support for the `Name` setting (#4583) and I wrote a [comment about that](https://github.com/robotframework/robotframework/issues/4583#issuecomment-1468070648). As I explain in that comment, the reason is that there's a performance enhancement with `--suite` to avoid parsing files that don't match it but that doesn't work anymore now that suite name isn't always got from the file name. In adding to to the new `Name` setting possibly changing it, custom parsers (#1283) can also create suites with whatever names.

Making it possible to parser only certain files when executing a directory is a valid use case, but it should be separated from the `--suite` option. I have submitted #4687 a new command line option to limit parsing and initially added it to RF 6.2 scope to keep RF 6.1 smaller. I also submitted #4688 about not excluding files when using the `--suite` option. I added it to RF 7.0 scope, because the change can be considered backwards incompatible and there isn't yet alternatives for it.

After submitting the aforementioned issues two things have happened:
- We got great PR #4735 implementing #4687. As the result that issue is now in RF 6.1 scope.
- We got this issue about the current `--suite` functionality causing real problems.

After situation changing, I now believe we should change `--suite` behavior already now in RF 6.1. The change can still be considered backwards incompatible, but users dependent on it will have a new option they can use instead. That basically means I'll move #4688 into RF 6.1 scope. I'll also close this issue as its duplicate.
