### ISSUE TITLE
performance drop for remote libraries

### ISSUE THREAD

**Issue by karniemi** [robotframework/robotframework#4759]
**The problem**
We are just upgrading from 3.x to 6.0.2. We experienced a drop in performance. Running the test started taking a lot longer: from ~2:30h to ~2:50, from 1:05 to 1:15.

**Analysis**
We have narrowed down the problem to the start-phase of tests suites - and specifically to setting up the remote libraries. The tests themselves seem to be running at the same speed as earlier. In log.html, we see that there's a long delay between the start time of the suite and the start time of the suite setup. In robot syslog, we can see that the "Creates keyword"-entries are running for 10s of seconds and even minutes for remote libraries.

We are using jrobotremoteserver. We upgraded from 3.0 to 4.1.0 - with no effect. Only the spurious error messages changed from "_No such handler: get_keyword_tags_" to "_Failed to invoke method get_library_information in class org.robotframework.remoteserver.servlet.ServerMethods: Duplicate key stop_remote_server_"

**During the suite setups, we noticed  load spikes in the nodes running the jrobotremoteserver:**
CPU( greenish=Priviledged, brownish=User) - note that the spikes are on the Priviledged side:
![image](https://user-images.githubusercontent.com/5871676/237040489-bcd93cf7-cf76-415f-9cfd-16017a00e782.png)

Network packets ( grid-lines are for 5Kp/s, 10Kp/s,15 Kp/s,  greenish=Received, brownish=Sent):
![image](https://user-images.githubusercontent.com/5871676/237041261-e87ef37f-3356-481b-84df-5025be899feb.png)

We have not captured network traffic, but from the figures and metrics, it would seem that the new version of robot framework bombards the remote server for some reason. 

We found out that this issue has probably been found out in these tickets:
* https://github.com/robotframework/jrobotremoteserver/issues/58
* https://github.com/d-biehl/robotcode/issues/24

**Workaround**
We also found out that in one ticket, someone has published a forked version of jrobotremoteserver, which fixes the "duplicate key stop_remote_server"-error: https://github.com/robotframework/jrobotremoteserver/pull/66. We gave that version a go -and the performance issue was resolved, the run times are now back to what they used to be and also the metrics are no more showing the spikes:
![image](https://user-images.githubusercontent.com/5871676/237047220-1e80b0a9-afc9-42c8-b6af-cb8c3fd00706.png)
![image](https://user-images.githubusercontent.com/5871676/237047367-f901e448-446b-4138-acf3-186130de4240.png)

**Conclusions**
I'm reporting this to robot framework instead of jrobotremoteserver - because it would seem that robot framework is doing some bombarding and causes the problem in the jrobotremoteserver. Of course, the issue might be resolved - or rather hidden - when the jrobotremoteserver gets a new release with the seemingly unrelated(?) "Duplicate key stop_remote_server_"-issue resolved.

**Comment by pekkaklarck** [comment]
This is most likely due to the remote API getting several new optional methods. As the result Robot does lot more querying for keyword information than earlier and that slows down taking the library into use. For more details see #3362.

The solution for the issue discussed in #3362 was to add a new `get_library_information` to the remote API to make it possible to query all information in one go. It works well, but unfortunately generic remote servers aren't too actively maintained and it hasn't been taken into wider use. Even the Python RemoteServer that acts as a reference implementation [lacks it](https://github.com/robotframework/PythonRemoteServer/issues/75).

Although the main issue is now solved on Robot side, it's certainly possible that the Remote library itself calls unimplemented methods unnecessarily. It needs to call them once to see are methods available (unless XML-RPC supports method discovery and we could see which methods actually are available), but it could stop calling methods that fail. Do you @karniemi have time and interest to study this?

**Comment by pekkaklarck** [comment]
No updadtes. Closing.

**Comment by karniemi** [comment]
@pekkaklarck ... ok, sorry for not coming back to this. It seems I did not have the time for it.

**Comment by pekkaklarck** [comment]
No worries. This issue can be reopened, or new created, if someone starts looking at the problem again.
