### ISSUE TITLE
Suite-level scoped class (same-name lib) imported initialized twice

### ISSUE THREAD

**Issue by shaoerkuai** [robotframework/robotframework#4763]
base.robot

> *** Settings ***
> Library     tb3.py
> *** Test Cases ***
> CASE1
>     log     abc
>     get_signal

tb3.py

![image](https://github.com/robotframework/robotframework/assets/117460332/1375c6e4-ac98-4f24-ae29-b5411c28ffc4)

logs:

![image](https://github.com/robotframework/robotframework/assets/117460332/4241604b-48ef-4bcf-8bb4-0eca1c48dc26)

How to make the Library not instantiate the Class until I call the keyword in the class in the test case?
Or when the keyword is called from a test case for the first time in a class, it won't be instantiated again?

**Comment by gueszo** [comment]
I had the exact same problem and used following workaround:

`from robot.running.context import EXECUTION_CONTEXTS`

and in `__init__`:

`if not EXECUTION_CONTEXTS.current.test: return`

The instance with EXECUTION_CONTEXTS.current.test set to None seems not to be used, so it should be safe to return early.

I'm curious if there is a solution where this instantiation doesn't take place at all.

**Comment by shaoerkuai** [comment]
> I had the exact same problem and used following workaround:
> 
> `from robot.running.context import EXECUTION_CONTEXTS`
> 
> and in `__init__`:
> 
> `if not EXECUTION_CONTEXTS.current.test: return`
> 
> The instance with EXECUTION_CONTEXTS.current.test set to None seems not to be used, so it should be safe to return early.
> 
> I'm curious if there is a solution where this instantiation doesn't take place at all.
Thanks for your answer, EXECUTION_CONTEXTS is the part I haven't covered yet

Currently, I set a variable via BuildIn for something that cannot be instantiated repeatedly, and then first check that variable has a value each time in __init___.
I don't want to introduce too many variables in the execution., so I will check this after a while

I think there should be decorators such as @TestLibraryInitialize(exclude_import=True).

Hope there is a better solution.

**Comment by gueszo** [comment]
> `from robot.running.context import EXECUTION_CONTEXTS`
> 
> and in `__init__`:
> 
> `if not EXECUTION_CONTEXTS.current.test: return`
> 
> The instance with EXECUTION_CONTEXTS.current.test set to None seems not to be used, so it should be safe to return early.

I have to correct myself. Checking for `EXECUTION_CONTEXTS.current.test` doesn't work if the library is used in the suite setup.

I now have:

`if not EXECUTION_CONTEXTS.current or not EXECUTION_CONTEXTS.current.step_types: return`

I'm checking for `EXECUTION_CONTEXTS.current` first because it is None if you generate the library documentation with libdoc.

**Comment by pekkaklarck** [comment]
Libraries implemented as classes are always initialized once after they have been imported to be able to query what keywords they contain. Libraries using test or suite scope will be instantiated again whenever a suite or a test starts. With libraries using the global scope we know that the same instance should be used with all tests and we preserve the original instance.

I believe it would be fine to preserve also suite scoped libraries, but that cannot currently be done due to how we cache libraries. That's not a good idea in general and we have #2106 about changing that. I merge this issue with it, but cannot give promises when it is fixed. Until that you can use globally scoped libraries if you want instances to be created just once.
