### ISSUE TITLE
XML with --xunit Cmd-Line does not create the correct FAILURE Node

### ISSUE THREAD

**Issue by stevereiss** [robotframework/robotframework#4788]
I have been using Robot Framework for a number of years now... I recently changed my running CMD-Line params to use the --xunit so that the XML output would be in the correct format to exchange data with the Zephyr program from SmartBear Software.

The Generated XML file has "a wrong format" for a Failure Node when it is imported into Zephyr.  The Failure Node is NOT seen as a Failure - proceeds to Success in Zephyr.

See the code examples below : 

**Issue when using  --xunit  cmd-line (to generate a JUnit XML file - used to pass data to Zephyr - the Pass/Fail test results)**

Original Test Case Failure : 

```
<testcase classname="Apps Testing" name="Test Apps In New Tab" time="148.878">
 <failure message="Incorrect NEW Browser TAB APP Title" type="AssertionError"/>
</testcase>
```

** ^^ Above ^^  - Does NOT show up as a Failure when imported into Zephyr **

This patched XML will show the failure correctly in Zephyr : 

```
<testcase classname="Apps Testing" name="Test Apps In New Tab" time="148.878">
 
 <failure message="Incorrect NEW Browser TAB Title" type="failure">
  Incorrect NEW Browser TAB Title
  </failure>

</testcase>
```

For Reference : JUnit Format From : https://llg.cubic.org/docs/junit/
```
 <failure message="" 		<!-- The message specified in the assert. -->
	       type=""    		<!-- The type of the assert. -->
	       >
 failure description

</failure>
```
Version Info : 

Python 3.9.10

robotframework                      6.0.2
robotframework-pythonlibcore        4.1.2
robotframework-requests             0.9.4
robotframework-selenium2library     3.0.0
robotframework-seleniumlibrary      6.0.0

**Comment by pekkaklarck** [comment]
There are two problems here:

1. There's no official standard for jUnit/xUnit format. Our xUnit outputs have been originally created based on [this schema](https://marc.info/?l=ant-dev&m=123551933508682) and then enhanced in RF 5.0 after discussions in #2982, #4074 and #4199. 
2. Zephyr is overly strict with what it accepts. For example, the aforementioned #2982 caused issues with it explained in #4444. Have you encountered that issue?

If I got the description right, Zephyr doesn't like `<failure message="msg" ... />` but accepts `<failure message="msg" ... >msg</failure>`. I would say that's a bug in Zephyr more than anything else, especially when other xUnit consumers are fine also with the former. That said, I don't see problems with adding the message as the element text in addition to using the `message` attribute if it works with Zephyr and doesn't cause issues otherwise.

Notice that there exists a [project](https://github.com/rikerfi/robotframework-xunitmodifier) by @rikerfi for experimenting xUnit file formats. This change could possibly be done there first and, if it works fine, incorporated to Robot itself.

**Comment by pekkaklarck** [comment]
Now that I read this again, I believe we shouldn't make the proposed change. According to the referenced documentation, the failure message should be specified using the `message` attribute and the text of the `<failure>` element should be used for stacktrace or other such details. If Zephyr doesn't understand `message`, it's a bug in it and I don't think we should try to workaround its bugs. We also may want to use the `<failure>` element text for other purposes in the future.
