### ISSUE TITLE
TypeError: WebDriver.init() got an unexpected keyword argument 'service_log_path'

### ISSUE THREAD

**Issue by rogerl1972** [robotframework/robotframework#4789]
I've done all the installations and have a test robot that simply tries to open Chrome. Every time I run it, I get the following error...

Here are my installed environment
- Macbook M1 Pro
- Chrome Version 114.0.5735.106 (Official Build) (arm64)
- Python 3.11 PyCharm 2023.1.2 CE
- Robotframework 6.0.2
- robotframework-seleniumlibrary 6.1.0
- selenium 4.10.0
- chromedriver 114.0.5735.90

I understand that Selenium 4.10.0 has deprecated service_log_path, but seems that robotframework-seleniumlibrary hasn't

**Comment by leeuwe** [comment]
@rogerl1972 You should downgrade to `pip install selenium==4.9.1`.
Since this issue is related to SeleniumLibrary and not Robot Framework itself, I suggest closing this issue here.
Details about the error you encountered can be found [here](https://robotframework.slack.com/archives/C07PKKCTF/p1686168300639869)
