### ISSUE TITLE
<Bug> rebot --merge will lost .jpg in Fail keyword in log.html when outputdir is not  .jpg's parent dir

### ISSUE THREAD

**Issue by JimRevolutionist** [robotframework/robotframework#4796]
Test Env:
python 3.10.10 on Windows(64-bit) 
robotframework==6.0.2
robotframework-flaui==2.0.9

<sample.robot> 
```
*** Settings ***
Library  FlaUILibrary
Library  ./base.py

*** Test Cases ***
demo_1
    # add bug.jpg into log.html
    # you can use your local picture to replace value here
    log_screenshot_into_html  C:\\Users\\TangJim\\Desktop\\bug.jpg

    Fail  produce test*_demo_1_1.jpg

demo_2
    # add enhancement.jpg into log.html
    # you can use your local picture to replace value here
    log_screenshot_into_html  C:\\Users\\TangJim\\Desktop\\enhancement.jpg

    Fail  produce test*_demo_2_1.jpg
```

<base.py>
```
from FlaUILibrary.robotframework.robotlog import log_screenshot
def log_screenshot_into_html(filepath):
    log_screenshot(filepath)
```

![image](https://github.com/robotframework/robotframework/assets/126214844/b6c84f41-0e16-495e-81f5-22b109e0eac4)

Command:
```
robot --test demo_1 --name sample --outputdir .\results\sample\ --output 1_output.xml --log 1_log.html --report 1_report.html .\results\script\sample.robot
robot --test demo_2 --name sample --outputdir .\results\sample\ --output 2_output.xml --log 2_log.html --report 2_report.html .\results\script\sample.robot

rebot --merge --name sample --outputdir .\results\sample\ .\results\sample\*_output.xml
rebot --merge --name sample --outputdir .\results\ .\results\sample\*_output.xml
```

Test Result:
[results.zip](https://github.com/robotframework/robotframework/files/11742116/results.zip)

![image](https://github.com/robotframework/robotframework/assets/126214844/0c6b2d8d-f998-4eb0-b565-1a2c68b02e25)

you will see that .jpg in Fail keyword will lost in log.html which is produced by "rebot --merge --outputdir .\results\"

**Comment by pekkaklarck** [comment]
There's not much we can do. When you log a path to a file, it's just text to Robot so it cannot automatically update the path if the log location changes. Even if it could, you could move either the image or the log file yourself and the linking would be broken anyway. You basically have two solutions:

1. Make sure that linking doesn't break by not moving files. This is easiest if you use relative paths because then you can move files as long as you move them so that the relative path stays the same.
2. Embed images instead of linking them. Basically you can base64 encode an image and write that content to the log file. That way there's no separate image file and no risk of the linking being broken, but a downside is that the log file size grows a lot.
