### ISSUE TITLE
Add support for more test result formats (NUnit3)

### ISSUE THREAD

**Issue by 1000Reasons** [robotframework/robotframework#4811]
Azure Pipelines does not support test report attachments using JUnit (the format used by the --xunit generated report), only TRX and NUnit3. I want to be able to see e.g. screenshots taken by the test suite during failure/success to verify that everything is working as it should. 

To do this I have implemented a custom script that will automatically add the attachment to the XUnit file after it has been generated, but this does not work since the ["Publish Test Results" task in Azure Pipelines does not support test report attachments using other formats than TRX and NUnit3.](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/publish-test-results-v2?view=azure-pipelines&tabs=junit%2Cnunit3attachments%2Cclassic#attachments-support) 

Please add support to generate more types of test result xml-files and also preferably a native way to append screenshots to the XML file while it is being generated to make image attachments easier and more stable to use.

**Comment by sebastianciupinski** [comment]
@1000Reasons i do not remember details or something might change in ADO, but I was able to consume xml generated by RF just by tuning settings of ADO pipeline

**Comment by pekkaklarck** [comment]
Support for more result formats can be considered, but I believe it's better to first have an external tool for that purpose. If it gets mature enough and is considered generally useful, it can be incorporated with the core similarly as the xunit functionality. The reason why it should mature as an external project is that when something is in the core, making changes to it is harder due to backwards compatibility reasons.

I'll close this issue now. New one can be opened in the future if there's a concrete proposal what to add.
