### ISSUE TITLE
TypeError: WebDriver.__init__() got an unexpected keyword argument 'service_log_path'

### ISSUE THREAD

**Issue by ZindagiH** [robotframework/robotframework#4828]
I'm also facing the same issue
WebDriver.__init__() got an unexpected keyword argument 'service_log_path'
Python 3.11.4
Selenium Version: 4.9.1
Robot Framework Version: 6.1

**Comment by pekkaklarck** [comment]
I think issue is caused by Selenium changing APIs and SeleniumLibrary not yet being updated. Downgrading Selenium may help. This issue tracker is for Robot Framework core only, SeleniumLibrary has it's own tracker, so this issue is invalid here. You may want to submit it to SeleniumLibrary's tracker, but please check is the issue already reported first.
