### ISSUE TITLE
It's time to add an automatic replay mechanism for failed cases

### ISSUE THREAD

**Issue by TotheAnts** [robotframework/robotframework#4844]
It's time to add an automatic replay mechanism for failed cases

**Comment by pekkaklarck** [comment]
I don't believe this is as easy as having a single parameter. It could solve some needs, but most likely the functionality would need to be enhanced when more people would take it into use. Enhancing something that's in the core is hard because there aren't that frequent releases and because we need to take backwards compatibility into account.

This is best to be experimented with an external tool. It can use, for example, tags or documentation for specifying how many times to retry etc. Once a tool is mature enough and can handle all or at least most needs related to retry, we can add the same functionality to the core.
