### ISSUE TITLE
Timeout won't stop during sleeping

### ISSUE THREAD

**Issue by TruthSeekerX** [robotframework/robotframework#4849]
Hei, I've encountered a very strange issue, Robot Framework won't stop the test if Timeout during sleeping. Test just hangs/stucks for infinity.
If Test Timeout is longer than sleep it will run successfully. 

```
*** Settings ***
Test Timeout	0:03

*** Test Cases ***
Test Case
	sleep	5sec
```

Environment:
Robot Framework 4.1.3 together with IronPython 3.4

PS. 

- Robot Framework 3 with IronPython 2.7 works no problem
- I had replace the Timeout/Ironpython.py of 4.13 with RF3 version and no luck.
- Tested with customer (IronPython library), but the same result:

```
def my_wait(self, seconds):
    time.sleep(float(seconds))
```

**Comment by TruthSeekerX** [comment]
What's more:

- if Timout happened during the Sleeping, I couldn't force the test to stop by ctrl-c. The console were stuck. I needed to end the task from task manager.
![image](https://github.com/robotframework/robotframework/assets/78495830/d10e073c-de4f-46a5-bc72-a8cb94a548f6)

- If the Timeout is longer than Sleeping, during sleeping I still couldn't force the test stop by ctrl-c. The test would finish despite the ctrl-c signal were received.
![image](https://github.com/robotframework/robotframework/assets/78495830/fe95a9c2-a6a7-4dc0-832a-c8a95839cf40)

**Comment by pekkaklarck** [comment]
Timeouts are complicated technically, because they need to forcefully stop the executing keyword/function and Python doesn't provide such functionality out-of-the-box. Another problem is that not all functions can be stopped. Robot's own Sleep is implemented so that instead of sleeping the whole time in one go, it sleeps in pieces and after each small piece checks is it time to stop sleeping. This approach ought to make it possible for timeouts to work.

I don't have any idea why timeouts don't work in your case nor why they do work with earlier Robot versions. Because we don't anymore support Python 2 or IronPython, I won't investigate this any further.

**Comment by TruthSeekerX** [comment]
@pekkaklarck Thank you for taking your time to reply. It was a legacy project, and it's great we have a concrete answer by now. It helps a lot for future development.
