### ISSUE TITLE
Process: Make warning about processes hanging if output buffers get full more visible

### ISSUE THREAD

**Issue by pat0026** [robotframework/robotframework#4864]
Related to #3661,

Before finding the related issue above, my binary hung when using the `RUN PROCESS`. It has consumed a lot of my time investigating whether the robot test has found a bug or not. I found out that it is a limitation or weird behavior on RF based on the related issue. It could really help other developers to note this limitation, to avoid misunderstanding the test, and to avoid unnecessary investigation. Thank you in advance.

RobotFramework Version: 6.1.1
Actions to resolve the issue:
- [ ] Add this limitation or behavior in the Process Library Documentation
- [ ] Fix the bug ( if possible )

**Comment by pekkaklarck** [comment]
Large outputs hanging processes [is already documented](http://robotframework.org/robotframework/latest/libraries/Process.html#Standard%20output%20and%20error%20streams). Do you have concrete ideas how to enhance the documentation?

The general problem that output buffers get full cannot be fixed. We are not planning to look at that simply because redirecting outputs to files is such an easy workaround. If you have ideas how to fix the underlying issue and are willing to provide a PR doing that we certainly are interested, though.

The above said, there was an issue related to standard input configuration (#4065) that we have now fixed. We first introduced new `stdin` argument in RF 4.1.1 (#4102) to control the behavior and RF 7.0 changes the default value of `stdin` so that it shouldn't anymore cause issues (#4103). If your issue was related to `stdin`, then it's already fixed (although RF 7.0 is still under development).

**Comment by pekkaklarck** [comment]
Yeah, this could be mentioned in the Run Process and Start Process docs.
