### ISSUE TITLE
Overwrite values set in main robot file

### ISSUE THREAD

**Issue by FWDQK** [robotframework/robotframework#4871]
Hi Team,
We are trying to achieve the below :
Main.robot:

*** Variables ***
${DBHost}         localhost
*** Test Cases ***
DB check
          Set Global Variable    ${DBHost}    newvalue
         Login Application

We have created one resource file:
*** Settings ***
Resource    ../PageObjects/test.resource

*** Variables ***
${host1}     host1

***Keywords***
Login Application
        Log    ${DBHost}
        Log    ${EN_clickSignIn}
        ${DBHost}     Set Variable    ${host1}
        Set Global Variable    ${DBHost}     ${host1}
        Log    ${DBHost}
        Log    ${EN_clickSignIn}

Second resource file in different folder:
*** Settings ***
Resource    ../testdb.robot
Resource    ../Pages/test.resource

*** Variables ***
${EN_clickSignIn}               chain=**/XCUIElementTypeOther[`label == '${DBHost}'`]

But every time, the first value set in variables is also reflected in the variable used in second resource file. Base value is not getting updated via set global variable/set test variable/set suite variable

Please help to suggest how can we get updated value for '${EN_clickSignIn} '
![image](https://github.com/robotframework/robotframework/assets/111964982/46993c1b-8cc2-4255-b078-f985af668ca1)

**Comment by pekkaklarck** [comment]
When you have
```robotframework
*** Variables ***
${X}    value
${Y}    another ${X}
```
it creates variables `${X}` with value `value` and `${Y}` with value `another value`. If you later change `${X}`, it changes just `${X}`, `${Y}` isn't updated. If that would be desired, you needed to either update also `${Y}` or alternatively you could arrange the code so that `${Y}` is created only later. For example, if it is used like
```robotframework
*** Keywords ***
Example
    ${y} =    Set Variable    another ${X}
    Log    ${y}
```
changing `${X}` before that keyword is called changes the created `${y}` as well. Instead of changing suite level variables, it could be a better idea to pass the value to the keyword as an argument, though.
