### ISSUE TITLE
Set Global Variable Keyword fails when variable value begins with "@ or $" and considers the value to be a variable name

### ISSUE THREAD

**Issue by keshavvprabhu** [robotframework/robotframework#4889]
Set Global Variable fails if the variable value begins with @ or $. It seems to consider the value as a variable name instead.

```
Test Variables beginning with special characters
    ${test_variable}    Set Variable    @some_string
    Set global variable    ${test_variable}
```
 
Output
20231006 13:54:20.290 :  INFO : ${test_variable} = @some_string
20231006 13:54:20.291 :  FAIL : Variable '${some_string}' not found.

**Comment by catzilla-007** [comment]
@keshavvprabhu , correct me if I'm wrong; as far as I understand, `Set Global Variable` needs 2 inputs. one is `name`, and the other is `value`
https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Global%20Variable

![image](https://github.com/robotframework/robotframework/assets/1916652/102556d2-7750-4976-8281-6cd1cfb242c0)

I think the what you intend to do in the code would work with:

```
Test Variables beginning with special characters
        ${test_variable}    Set Variable    @some_string
        Set Global variable    ${my_global_var}  ${test_variable}
```

**Comment by pekkaklarck** [comment]
This is, somewhat unfortunately, by design and [explained in the documentation](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Using%20variables%20with%20keywords%20creating%20or%20accessing%20variables). I'm first to admit that the design is bad, but we cannot change it due to backwards compatibility concerns. Good news is that the new `VAR` syntax introduced in RF 7.0 (#3761) doesn't suffer from the same bad design. It is highly recommended over this keyword once RF 7.0 is out.
