### ISSUE TITLE
taking digits as variable names and auto type conversions

### ISSUE THREAD

**Issue by Thonuck** [robotframework/robotframework#4891]
Hello,

I have one question, if the following behaviour is intended behavior.
Let's assume we have the following python keyword library:

```
import logging
logger = logging.getLogger()

def validate_first_value(argument):
    result = ""
    for item in argument:
        result += "type({}): {}  ".format(str(item), str(type(item)))

    logger.warn(result)
```

This library is used by the following robot file:
```
*** Settings ***
Library    TestLibrary

*** Test cases ***
Check the parameter translation

    ${1}   Set Variable    1

    Log To Console   \n
    Validate first value     argument=@{${4}, ${5}}
    Validate first value     argument=@{${1}, ${2}}
    Validate first value     argument=@{${2}, ${1}}
```

Running this, we get the following output (starting from robotframewordk 3.1.2 and up to robotframework in version 6.0)
```
|| ==============================================================================
|| Test
|| ==============================================================================
|| Check the parameter translation
||
[ WARN ] type|4| <class 'int'>  type(5): <class 'int'>
[ WARN ] type|1| <class 'str'>  type(2): <class 'int'>
[ WARN ] type|2| <class 'int'>  type(1): <class 'int'>
|| | PASS |
|| ------------------------------------------------------------------------------
|| Test                                                                  | PASS |
|| 1 test, 1 passed, 0 failed
|| ==============================================================================
|| Output:  /mnt/etfiles/users/nuecker/robot_Test/output.xml
|| Log:     /mnt/etfiles/users/nuecker/robot_Test/log.html
|| Report:  /mnt/etfiles/users/nuecker/robot_Test/report.html
```

There are several things, which I don't understand. 
Why doesn't robot complain about assigning a value to a kind of integer value? 
I would have expected, that `${1}  Set Variable   1`  would produce an error. 
But robot is so kind and creates the variable `${1}` - is that really intended behaviour?

If I pass now this list construction to the Keyword, as long as the variable ${1} is in first position, its type (here string) persists:
With `@{${1}, ${2}}` the first item of the list is a string, the second an integer.
If we exchange the elements, like shown, by``@{${2}, ${1}}`, both elements become integer.
Is here some auto type conversion taking place and why is that?

As stated above, I tried this execution beginning from robotframework==3.1.2 onwards up to robotframework==6.0.

Thank You very much for any information about this,

Best Regards,
Thomas

**Comment by pekkaklarck** [comment]
First of all, allowing users to overwrite `${1}` doesn't make much sense. I believe the reason is that when number variables were introduced, we wanted to be sure that they don't break existing tests possibly using variables like `${1}`. That was a bad decision and we should change the behavior.

The reason for the strange behavior with `@{${4}, ${5}}`, and especially with `@{${1}, ${2}}` when `${1}` has been redefined to contain string `1`, is pretty interesting. This is how this syntax is evaluated:
1. Internal variables are replaced. The aforementioned examples become `@{4, 5}` and `@{1, 2}`.
2. Robot tries to find a variable with exactly these names. No such variables exist.
3. Robot checks is so called "extended variable syntax" in use. If you aren't familiar with this syntax, check the User Guide for details.
4. The first step of evaluating the extended variable syntax is is finding a potential variable name from the beginning. Names are expected to be alpha-numerical. In our examples these potential names are `4` and `1`.
5. Robot now checks are there variables with these names available. Both `${4}` and `${1}` exist. The first contains integer `4` and but the latter contains string `1`.
6. The resulting variable value is then evaluated with the remaining part of the original variable name. This means evaluating `4, 5` and `'1', 2`.
7. Both expressions are valid and create a tuple. Notice that the latter has string as the first value.

Notice that you get the same effect also by using `@{4, 5}` and `@{1, 2}` directly. These variables creating a tuples due to the extended variable syntax is pretty strange and that hadn't occurred to be earlier. I wouldn't call it a bug, though. Also redefined `${1}` works logically in this context, but being able to redefine it, as I already commented, very questionable.
`@{This is rather strange behavior, b

**Comment by pekkaklarck** [comment]
This behavior is strange but there's no bug. Closing.
