### ISSUE TITLE
feature request/suggestion: libdoc invocation sets special environment variable

### ISSUE THREAD

**Issue by suiluj** [robotframework/robotframework#4906]
Hello,

I am relatively new to robot framework and stumpled upon a problem while developing a rf library in vscode while using the robot framework lsp extension:

The lsp extension runs `libdoc` while linting/checking the code.

In my library code i check for custom environment variables on class object init. These variables are only set on real test exection but of course not while just developing the tests. This results in erros of the extension while developing.

The vscode extension runs libdoc.

As a workaround I suggest that the libdoc robot framework runs sets a special environment variable like

```
RUN_BY_ROBOT_FRAMEWORK_LIBDOC=TRUE
```

Then my code could first check this environment variable and could skip the rest of the init code to avoid robot framework lsp errors.

Does this solution make sense or is my approach wrong?

Here I described my problem in the lsp repo:

https://github.com/robocorp/robotframework-lsp/issues/988

**Comment by pekkaklarck** [comment]
Could you clarify how checking for some environment variable set by Libdoc would be better or easier that just gracefully handling the situation where the environment variables you need during execution don't exist?

**Comment by suiluj** [comment]
@pekkaklarck you were right. I found an easier solution which works in my case.

In the `__init__` of my library I just check if the code was run by libdoc and just quit in that case:

```python
if "libdoc.py" in sys.argv[0]:
    return
```

This is a simpler solution. Now I can load my environment in the init but still get the code completion in vscode.

**Comment by d-biehl** [comment]
Not sure how I got here ;-)

But, I also regularly get such requests for [robotcode ](https://github.com/d-biehl/robotcode) that the keywords for some library cannot be loaded correctly or dead processes remain when the library is loaded in robotcode, or ... or ... or ...  because people don't know that their library has to be instantiated correctly when creating a libdoc to get the keywords and that the code has to be executed in the constructor of the library. 
This is why the property `BuiltIn().robot_running` was introduced in one of the last Robot Framework versions. With this property you can query exactly this behaviour and only initialize your library/variable file correctly if Robot is actually running, which is not the case when generating the LibDoc.
The property `BuiltIn().dry_run_active` should also be mentioned.

For older RobotFramework versions I always refer to the undocumented check `EXECUTION_CONTEXTS.current is not None` which corresponds to the check of `robot_running`.

Both properties are not really described anywhere. Wouldn't that be a topic for the UserGuide?

**Comment by d-biehl** [comment]
This is the issue for creating these properties #4666

**Comment by pekkaklarck** [comment]
Mentioning these properties in the User Guide is a good idea. That should have been done already as part of #4666. I'm on mobile but try to remember to do that later. If you want to make sure it's not forgotten, please submit an issue.

**Comment by suiluj** [comment]
@d-biehl thanks for your hint to these `BuiltIn()` methods. I will change my code to use them instead of my hacky version. ;)

**Comment by d-biehl** [comment]
@pekkaklarck did you allready create an issue about this? if not I can create one.

**Comment by pekkaklarck** [comment]
@d-biehl I didn't submit an issue so please go ahead and submit one. Even better if you can take a look where to add this information in the User Guide.
