### ISSUE TITLE
BuiltIn Keyword 'Run Process' does not respect the globally set loglevel.

### ISSUE THREAD

**Issue by richardstone** [robotframework/robotframework#4919]
I'm trying to have as clean HTML log as possible so anyone can understand what is going on during my test execution by reading the log. I'm executing a lot of commands from robot via the builtin Run Process keyword. The issue is that this keyword is very talkative - at least to my standards, hence it fills up my HTML log with a lot of messages like these:
```
Starting process: XYZ
Waiting for process to complete.
Process completed.
```
I have tried to suppress this by issuing the "Set Log Level    NONE" keyword before calling Run Process, but after checking the code of Process.py I realised that logging inside this class is directly tied to loglevels (see: https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/Process.py#L418C23-L418C23).

I have seen other builtin classes where the globally set loglevel is respected by using _logger.log(level, msg)_ instead of _logger.info(msg)_. I'd really welcome this in Process.py as well.

**Comment by pekkaklarck** [comment]
Setting log level before Run Process is executed to NONE or DEBUG ought to disable INFO level logging. Setting and then resetting the level isn't that convenient, though, and Run Process certainly could get a separate `log_level=INFO` argument. Anyone interested to implement it?

**Comment by richardstone** [comment]
When I set LogLevel to NONE before Run Process, I only got the message "Log level changed from INFO to NONE." logged, then INFO logs still appeared from Run Process like usual, unfortunately.

**Comment by pekkaklarck** [comment]
That should not happen.

**Comment by richardstone** [comment]
Here is my output:
<img width="438" alt="image" src="https://github.com/robotframework/robotframework/assets/22618286/a231e48d-7019-4a53-b4cf-5abc02405c56">

**Comment by richardstone** [comment]
I have tried a few different things and it turned out that if I add the "robot:flatten" tag to the keyword in which I execute the Run Process, then the --RemoveKeywords 'name:* = BuiltIn.Run Process' gets ignored and logs from the Run Process will exist in the HTML log.

Is this the intended behaviour that removed keywords appear when a parent keyword is flattened?

I'm using Robot Framework v6.1

**Comment by pekkaklarck** [comment]
I noticed you asked about this on Slack as well and there you mentioned you were flattering keywords. That is important information, because if you use the `robot:flatten` tag then the actual XML writer is different than normally and it could be buggy in this regard. I couldn't reproduce the issue even that way, though, but I noticed some odd behavior and need to investigate this further.

Could you create a simple example demonstrating the issue that I could run? The command you run with `Run Process` shouldn't matter and in fact using just `Log` ought to work the same way. Tell also what command line options you are use and what Robot version you have.

**Comment by pekkaklarck** [comment]
Also, `robot:flatten` effectively removes the executed keywords, other than their messages, so there's nothing `--removekeywords` can remove. Because `--flattenkeywords` affects output.xml processing, it has a huge performance effect, using that and `--removekeywords` at the same time doesn't work either. Using Rebot first with `--removekeywords` and then again with `--flattenkeywords` could work, though. That gets somewhat complicated, so creating a custom `--pre-rebot-modifier` could be a simpler solution and it would also allow full control on that's there in the log file. You could even add new messages or keywords if you wanted to.

**Comment by richardstone** [comment]
I'm executing Robot with this additional argument: "--removekeywords tag:kwtoremove"
My keywords look like this:
```
Run Process Without Logging
    [Tags]    kwtoremove
    [Arguments]    ${command}    ${timeout}=0    ${on_timeout}=Terminate
    ${result} =    Run Process
    ...    ${command}
    ...    shell=yes
    ...    timeout=${timeout}
    ...    on_timeout=${on_timeout}
    RETURN    ${result}

Execute shell command
    [Tags]    robot:flatten
    [Documentation]
    ...    Executes a command in a shell with arguments.
    ...    Returns a result object which contains (rc, stderr, stdout).
    ...    Optionally the return code check can be disabled by setting "ret_check" parameter to False
    [Arguments]    ${command}    ${timeout}=0    ${on_timeout}=Terminate    ${msg_on_fail}=""    ${ret_check}=True
    Log    Run command: ${command}    level=INFO
    ${result} =    Run Process Without Logging
    ...    ${command}
    ...    timeout=${timeout}
    ...    on_timeout=${on_timeout}
    Log    Returned output:\n${result.stdout}   level=INFO
    Log    Returned error:\n${result.stderr}     level=DEBUG
    Log    Returned RC: ${result.rc}    level=DEBUG
    IF    ${ret_check} != False
        Should Be Equal As Integers    ${result.rc}    ${0}    msg="${msg_on_fail}"
    ELSE
        Log    Return check is disabled for this execution    level=DEBUG
    END
    RETURN    ${result}
```

I get this result:
<img width="1243" alt="image" src="https://github.com/robotframework/robotframework/assets/22618286/6fef486b-07b3-49b6-b4b9-bf5dfa075300">

But according to your latest comment, this makes sense that it's not working. Then I see that my options are to add the loglevel option to the builtin Run Process keyword, or to write my own keyword in python as an external library where I can specify my own loglevels for the process execution.

**Comment by pekkaklarck** [comment]
That example doesn't seem to use `Set Log Level` but instead the idea is to remove the whole `Run Process Without Logging`, right? That's a clever idea, but unfortunately doesn't work, because flattening already removes that keyword but leaves messages. Using `Set Log Level` inside that keyword works, though, and you then you don't need to remove the keyword anymore.

The recommended way to temporarily disable logging is using something like this:
```
Run Process Without Logging
    [Arguments]    ...
    ${old} =    Set Log Level    NONE
    ${result} =    Run Process    ...
    RETURN    ${result}
    [Teardown]    Set Log Level    ${old}
```

The problem with the above is that unfortunately `robot:flatten` doesn't work properly with log levels. As I mentioned in an earlier comment, there's a different XML logger in use when flattening and I was right that there's a bug. That logger has TRACE as the default level instead of INFO or whatever is set from the command line. That means that after running the above example the level would be TRACE. An easy fix is using
```
    [Teardown]    Set Log Level    INFO
```
but that then overrides whatever was from from the cli.If you are only using INFO, that shouldn't matter.

I'll submit a separate issue about `robot:flatten` and log levels and that issue will be fixed in RF 7.0. After that also the recommended approach will work.

**Comment by pekkaklarck** [comment]
Temporarily altering log levels with `Set Log Level` is somewhat inconvenient. We could consider adding a tag like `robot:log-level=<level>` that could be used to control that. If you'd find it useful, please submit an issue. Unless you or someone else is interested to provide a PR, there's no time to get it done before RF 7.0, though.

**Comment by richardstone** [comment]
Yeah what I pasted above is a next iteration where I tried to solve the issue. 
So you could reproduce the Set Log Level not affecting the keywords when using flatten? Is this what you're fixing?
My problem with that is even if that would work, then I'd see a lot of "Log level changed from X to Y" messages in the log, which will cause it to be a pain to read between the command executions.

**Comment by pekkaklarck** [comment]
Yes, I was able to reproduce the problem with levels and `robot:flatten`. I'll submit a separate issue about that. Setting level first to NONE and then INFO ought to mostly workaround the problem.

I agree that the level changing message is somewhat annoying in this context. I don't want to remove it altogether, but we could change its level to DEBUG. Having some more convenient way than `Set Log Level` to alter the level would be nice but lot more work.

**Comment by pekkaklarck** [comment]
The issue with `robot:flatten` and log levels is now fixed and I also changed `Set Log Level` message level to DEBUG.

I think you should change your keyword to use `Set Log Level` to disable logging before `Run Process` and then set the level to INFO afterwards. You shouldn't even need to have a separate keyword for that, you could do all this directly in `Execute shell command`. This ought to work now and with RF 7.0 it will work even better.

If using hard-code INFO when resetting the level is a problem, you could store the original log level to a variable and use that:
```robotframework
*** Varibles ***
${ORIG LOG LEVEL}    ${LOG LEVEL}
```
`${LOG LEVEL}` is a built-in variable that is set based on the `--logleve` option and changed automatically when `Set Log Level` is used.

**Comment by pekkaklarck** [comment]
Is there still something unclear regarding to this issue? If not, I guess it can be closed. If you'd want `Run Process` to have `log_level` argument to control its logging, please submit a new issue.

**Comment by richardstone** [comment]
Thanks I have submitted the feature request: https://github.com/robotframework/robotframework/issues/4929
Sorry for my late reply, and many thanks for your assistance!

**Comment by pekkaklarck** [comment]
Another related idea I got is adding a new keyword `Reset Log Level` that would always reset the level to the level set with `--loglevel` or to INFO if not set. That would simplify setting and resetting the level, because you didn't need to store rhe original level to a variable.

**Comment by richardstone** [comment]
Hmm yeah, that would be cool! I really welcome this idea!

**Comment by pekkaklarck** [comment]
Can you submit an issue about that as well? Even better if you are interested to create a PR.
