### ISSUE TITLE
BuiltIn: New `Reset Log Level` keyword for resetting the log level to the original value

### ISSUE THREAD

**Issue by richardstone** [robotframework/robotframework#4930]
_Opened this request after the discussion under https://github.com/robotframework/robotframework/issues/4919_

I'd like to request adding a new keyword `Reset Log Level` that would always reset the log level to the one set with `--loglevel` argument to robot, or to `INFO` if not set.

It would ease the work as now if I want to revert to the previous log level after a `Set Log Level` keyword, I need to store the previous keyword in an extra variable.

**Comment by pekkaklarck** [comment]
Yeah, avoiding storing the previous level to a variable would be convenient in general and especially if the level is set and then reset in different keywords.

The only design question I see is should this keyword reset to the _previous_ level or to the _original_ level set using the `--loglevel` option. We could also support both with an optional argument. Or, possibly better, we could enhance the current `Set Log Level` keyword so that it accepts pseudo log levels PREVIOUS and ORIGINAL.
