### ISSUE TITLE
	AttributeError: 'str' object has no attribute 'copy' 

### ISSUE THREAD

**Issue by shruti729** [robotframework/robotframework#4950]
Hi Team,
I am facing issue while running post request using RequestLibrary
	**AttributeError: 'str' object has no attribute 'copy**' 

python version:3.10.11
robot framework version: 5.0.1
requests==2.23.0

Kindly suggest on this issue

**Comment by pekkaklarck** [comment]
Does the situation change with different Robot Framework versions? If not, then the problem is most likely in your data or in RequestLibrary. My guess is that you are passing a string to a place where a dictionary is expected. If you suspect that this issue is related to Robot Framework core, please provide more information about the problem. If you believe the issue in RequestLibrary, please submit an issue to its tracker. If you are just looking for help, please use our Slack or other support forums listed at robotframework.org. This issue tracker is only for bug reports and enhancement requests related to Robot Framework core.
