### ISSUE TITLE
Recognize library class from module regadless its name if it is decorated with the `@library` decorator

### ISSUE THREAD

**Issue by jnhyperion** [robotframework/robotframework#4959]
project structure:
``` shell
my_module
    sub_module
        lib.py
        __init__.py
    __init__.py
test.robot
```
`lib.py`
``` python
from robot.api.deco import library, keyword

@library(scope="GLOBAL")
class lib:

    @keyword
    def my_py_kw(self):
        print("foo")
```

`test.robot`
``` robot
*** Settings ***
Library    my_module.sub_module.lib

*** Test Cases ***
example
    my py kw
```

when I change the lib class from `class lib` to `class Foo`, the kw `my_py_kw ` will not be recognized anymore.

I think once I used the deco `@library` for a lib class, robot should use this deco to detect lib class instead of only using the name.

**Comment by pekkaklarck** [comment]
Sounds like reasonable. This would require inspecting all module attributes to check are they classes that have the special `ROBOT_AUTO_KEYWORDS` attribute set. It wouldn't be hard and I believe it shouldn't take too much time either.

**Comment by pekkaklarck** [comment]
Some further comments about design:
- It should be an error if there are multiple classes with `ROBOT_AUTO_KEYWORS`.
- We shouldn't search for library classes if the module itself has `ROBOT_AUTO_KEYWORS` set.
- We could consider adding a new attribute like `ROBOT_LIBRARY` that could be used as a marker instead of `ROBOT_AUTO_KEYWORDS`. It would be a topic for another issue, though.

**Comment by Snooz82** [comment]
This could cause incompatibility PythonLibCore.

If the module level class that has the same name but has no @library decorator.
Should be checked really carefully if this introduces backwards incompatibility.

**Comment by pekkaklarck** [comment]
I'm not sure about all PythonLibCore usages, but in general the `@library` decorator should only be used with the main library and even with that it's optional. Do you @Snooz82 have examples where `@library` is used multiple times?

The only backwards incompatibility I see is that if you have a module `x` that you use as a library and that module also has a class `Y` that you also use as a library, using `Library    x` would start using the class `x.Y` instead of the module `x`. I would consider such usage pretty strange. Having a module `x` with library classes `x.Y` and `x.Z` sounds much more likely, but that usage wouldn't be affected by this change.

The only thing I'm really concerned is that looking for classes in the module will have a performance effect. I doubt the effect is too big in general, but that needs to be tested with some really big modules having log of classes and other attributes.

**Comment by pekkaklarck** [comment]
This seems to be somewhat controversial feature. I still believe it's a good idea, but let's anyway move it from RF 7.1 scope to RF 7.2 to have more time to discuss it.

**Comment by Snooz82** [comment]
I have a UseCase at a customer, where we design multiple libraries, which are classes in submodules.

```
a/
a/__init__.py
a/b/__init__.py
a/c/__init__.py
```

`a.b` has a class `b` that has a library decorator because it can be used separately.
`a.c` same.

`a` has a class `a`, is a DynamicCore and imports `a.b` and `a.c` 

so you can use `Library  a` and get all the keywords together or you can import `Library   a.b` and only get a part of it.

so because a.b is imported into a and also has a @library decorator would that be affected?

**Comment by pekkaklarck** [comment]
Interesting design. I don't think it would be affected by this change.

**Comment by pekkaklarck** [comment]
I got this implemented and will push changes shortly. I consider this a pretty useful enhancement and raised the priority to get it listed in the release notes.

I made the following design decisions when implementing this:

1. A class decorated with `@library` is automatically used as a library only if it is implemented in the module, not if it is imported to it. This is different to how we handle classes with the same name as the module, because they can also be imported. The reason I decided to handle decorated classes differently was that otherwise importing a decorated class, for example, to be used as a base class would cause problems.
2. If a module contains multiple decorated classes, the module itself is used as a library. This situation could alternatively be considered an error, but I considered using the module as a library a bit better in general and also safer from backwards compatibility point of view.

The above design decisions ought to make introducing this new functionality pretty safe, but they don't make it fully backwards compatible. If someone has used a module as a library and the module also contains a class decorated with `@library`, the behavior will obviously change. I doubt anyone is affected by that, but if someone is and they cannot change their design, adding a dummy class decorated with `@library` is a simple workaround.

I was slightly worried about a performance penalty of looking for decorated classes from a module based library with lot of keywords, but in my tests with a library having 1000 keywords there was no real difference. Bigger libraries are also likely to be implemented as classes and they aren't affected at all.
