### ISSUE TITLE
Wrap 'xunit' output in 'testsuites' tag

### ISSUE THREAD

**Issue by MP-StefanKraus** [robotframework/robotframework#4973]
Hello, 

I am currently working with robot framework and noticed that the generated xunit reports do not wrap a single 'testsuite' into a 'testsuites' tag.

The referenced link in ./src/robot/reporting/xunitwriter.py (https://marc.info/?l=ant-dev&m=123551933508682) describes that normally, testsuites is the high-level tag containing multiple testsuites first, even though in case of a single testsuite, it seems like some tools omit it. Some tools like 'sphinx-test-report' expect and want always a testsuite.

I would therefore ask if one always wants to omit a 'testsuites' tag for xunit.

I would also be willing to implement this and create a PR for this.

**Comment by pekkaklarck** [comment]
We discussed about this as part of #2982, but decided to omit `<testsuites>` for the following reasons:
- We always have exactly one root suite.
- Docs clearly state that `<testsuites>` is optional. We used https://llg.cubic.org/docs/junit/ as the reference.
- Adding `<testsuites>` could potentially break tools that handle the current format.

I don't think the situation has really changed, and I still believe it's better not to add `<testsuites>`. If there are tools that require it, I would recommend submitting an issue to their tracker about making it optional, but if there are several such tools, we can also consider changing our outputs.

The change itself would be trivial, but the problem is testing does the change work with various tools processing xunit files. Someone basically needed to test both the current format and a format with `<testsuites>` and see how they work. There are so many tools processing these files that it's a lot of work and could be best done as a community effort.

This whole mess is due to the fact that there's no official or even generally accepted de-facto standard for xunit files. One way to tackle that problem would be making Robot's xunit file structure configurable, but I wouldn't like to add various command line options for just this usage. An external tools is a much better solution and we [already have one](https://github.com/rikerfi/robotframework-xunitmodifier).

**Comment by MP-StefanKraus** [comment]
Hey,

thanks for your response! I agree that especially the danger of breaking tools is pretty high, and it is a pity that this format is not specified properly.

I did not saw this external tool, but it looks promising! Thanks a lot for your work

Bests
