### ISSUE TITLE
Log with console=True and level=ERROR displays in the console twice

### ISSUE THREAD

**Issue by manosnoam** [robotframework/robotframework#4974]
When calling for example:
`Log    Cluster deployment had errors: ${result.stdout}    console=True    level=ERROR`

The console prints the output twice:
```
Cluster deployment had errors: ...
...
Cluster deployment had errors: ...
...
```

Robot Framework version: 6.1.1

**Comment by pekkaklarck** [comment]
This is as expected. You are explicitly using `console=True` and that causes the message to be logged to the standard *output* stram. You are also explicitly using a level higher than INFO that causes the message to be logged to the standard *error* stream (and written to output.xml separately). Not writing a message to the stdout when `console=True` is used would be odd in my opinion regardless to what is written to the stderr. If that is a problem in your case, you need to change the usage so that you don't use `console=True` with log levels higher than INFO.
