### ISSUE TITLE
Empty variable name in VAR crashes execution

### ISSUE THREAD

**Issue by bhirsz** [robotframework/robotframework#4995]
Following example:

```
*** Test Cases ***
Test
    VAR
    ...

```

will stop robot execution and throw:

```
options = ['scope', 'separator'] if name.value[0] == '$' else ['scope']
E           IndexError: string index out of range
```

instead of invalid variable name error (in case variable name is in the same line, ie just ``VAR``

**Comment by pekkaklarck** [comment]
The problem is that variable name ends up being an empty string in this special case and then `name.value[0]` causes an `IndexError`. This is not a common syntax, but a hard crash is always pretty bad. Anyway, this is easy to fix and it's great we get it done still before the final release. Thanks for the report @bhirsz!
