### ISSUE TITLE
"Parsing type failed"/"Type name missing" error message appears on the wrong argument

### ISSUE THREAD

**Issue by DetachHead** [robotframework/robotframework#5002]
```py
# a.py
from __future__ import annotations

from typing import Callable

def foo(a: Callable[[], None], b: asdf) -> None: ...
```
```
[ ERROR ] Error in library 'a': Adding keyword 'foo' failed: Parsing type 'Callable[[], None]' failed: Error at index 9: Type name missing.
```

removing the invalid `asdf` type annotation fixes the issue, so the error should be complaining about the `b` argument instead of the `a` argument

**Comment by pekkaklarck** [comment]
This seems to be a bug in the new `TypeInfoParser` introduced as part of #4711:
```python
>>> from robot.running.arguments.typeinfoparser import TypeInfoParser
>>> TypeInfoParser('Callable[[], None]').parse()
[snip]
ValueError: Parsing type 'Callable[[], None]' failed: Error at index 9: Type name missing.
```
Apparently the parser expects there to be a type name after the opening `[`, but now there's just another `[`. Shouldn't be hard to fix.

The reason `TypeInfoParser` ends up being used in this context is pretty interesting:
1. You use `from __future__ import annotations` which makes your signature same:
   ```python
   def foo(a: 'Callable[[], None]', b: 'asdf'): ...
   ```
2. Robot tries to get type hints from the methods using `typing.get_type_hints()`. That function tries to resolve forward references, but that fails because `asdf` isn't defined. Without `asdf` that would work and the `'Callable[...]'` string would be converted to a real `Callable` object.
3. As a fallback Robot accesses `foo.__annotations__` directly. That works but type hints are now strings.
4. Robot uses `TypeInfoParser` for parsing stringly types.
5. That fails as demonstrated above. Notice that the parser handles `'asdf'` just fine.
