### ISSUE TITLE
`Log Variables` should not consume iterables

### ISSUE THREAD

**Issue by kstine** [robotframework/robotframework#5005]
Found in Robot Framework 6.1.1 and 7.0rc2
Python 3.11

Given this example:
```
Cycle Test
    ${TEST_LIST}    Create List    beginning    1    2    3    4    end
    ${CYCLE_TEST}    Evaluate    itertools.cycle($TEST_LIST)
    Set Test Variable    ${CYCLE_TEST}
    Log Variables
```
When executing this case
Then Robot Framework will pause for a while and eventually throw a Memory Error.

This might be an uncommon situation, but would be nice to handle iterable objects.
My current workaround is to avoid assigning the itertools.cycle() to a RF variable and handle everything within a library.

**Comment by pekkaklarck** [comment]
This occurs due to the following reasons:
- `Log Variables` logs all list-like values so that all their items are logged separately.
- Robot considers all iterable objects list-like.
- `itertools.cycle()` is a never-ending iterable. Trying to log all its items is not possible.

This is pretty annoying and can be considered a bug. The same behavior causes also all iterables that are finite to be consumed.

An easy solution to this issue is changing the behavior so that we log all items only with sequences and with iterables we log the iterable itself.
