### ISSUE TITLE
Setting `PYTHONWARNDEFAULTENCODING` causes warnings

### ISSUE THREAD

**Issue by rasjani** [robotframework/robotframework#5010]
If environment variable PYTHONWARNDEFAULTENCODING is set (and at least when running on MacOS), `_get_python_system_encoding()`  from `robot/utils/encodingsniffer.py` in triggers following warning;

```
/Users/rasjani/src/duunit/energy-meter/venv/lib/python3.11/site-packages/robot/utils/encodingsniffer.py:59: EncodingWarning: UTF-8 Mode affects locale.getpreferredencoding(). Consider locale.getencoding() instead.
  return locale.getpreferredencoding(False)
```

In this example, all i did was `import Browser` in the  python repl.

**Comment by pekkaklarck** [comment]
Interesting, I didn't know about this option or [PEP 597](https://peps.python.org/pep-0597/) earlier. It makes sense to require encoding to be specified with `open()`, but I don't fully understand why this error occurs with `locale.getpreferredencoding(False)`. Anyway, it seems that it could be easily avoided by using [locale.getencoding()](https://docs.python.org/3/library/locale.html#locale.getencoding) instead. It's only available with Python 3.11, but that's also the version where this particular warning starts appearing.

Although the fix would be easy, I don't think it's a good idea to do it in RF 7.0 anymore:
- Although I tested the change on Linux and on Windows and it worked fine, changes like this are always risky. It should be done so that it's available in preview releases, not just before the final release.
- The warning doesn't occur by default.
- We use `open()` without encoding in multiple places in our code base. If we want to support `PYTHONWARNDEFAULTENCODING` properly, we need to go through them all and set explicit encoding. Depending on the case the encoding can be `UTF-8` or `locale`. The was added as part of PEP 597 in Python 3.10, but we can use `None` with earlier versions. All this is too much work for RF 7.0 at this point.

The problem is real, so let's fix it properly in RF 7.1.
