### ISSUE TITLE
run robot with multi thread has error: [ ERROR ] Reading XML source 'D:\result\output.xml' failed: Incompatible child element 'statistics' for 'kw'.

### ISSUE THREAD

**Issue by ysy1418899560** [robotframework/robotframework#5026]
robotframework: 6.1.1
python: 3.7.9

hello, when I run robot with multi thread has error: [ ERROR ] Reading XML source 'D:\result\output.xml' failed: Incompatible child element 'statistics' for 'kw'.
I start 4 threads to execute run(robot_file_path, outputdir=result_path) at the same time, i get a error message: [ ERROR ] Reading XML source 'D:\result\output.xml' failed: Incompatible child element 'statistics' for 'kw'.

![Uploading DD97FFE0-905C-417e-8E06-F68FBCB0C133.png…](output.xml)

below is my code script:

import threading

from robot import run

class MultiThreadings(object):

    def __init__(self):
        self.thread = threading

    def run(self, robot_file_path, result_path):
        run(robot_file_path, outputdir=result_path)
        threading_id_str = "thread" + str(self.thread.get_ident())

    def multi(self, robot_file_path, result_path):
        threads = []
        for i in range(0, 4):
            t = self.thread.Thread(target=self.run, args=(robot_file_path, result_path + "-" + str(i)))
            threads.append(t)
        for t in threads:
            t.start()

robot_file_path = "./01.robot"
result_path = "./result"
multi = MultiThreadings()
multi.multi(robot_file_path, result_path)
print("ok")

**Comment by Lenormju** [comment]
I've had the same problem many times. The `robot.api.logger` is not thread-safe, you should not call it from different threads, only the MainThread. I'm considering creating a monkeypatch to add a mutex over it.

**Comment by franzhaas** [comment]
This is a tricky topic, for all who are interested, there is a workshop on robocon 2025 [https://robocon.io/program#live-managing-concurrency-with-robot-framework] where solutions to this problem will be discussed and presented.

If you can sign up and come there, this will be a good opportunity to share our pains, and distribute our solutions.

**Comment by Lenormju** [comment]
I won't attend the in-person conference, but this workshop looks very interesting ! How does the keyword for concurrent logging work ? By checking the current thread, if it is not the MainThread then send the log to a Queue, else (in the MainThread) then pop all the logs from the queue ?

**Comment by test-fullautomation** [comment]
Hi @Lenormju ,
in addition to Franz's proposal you can try
RobotFramework AIO (http://robotframework-aio.org).

This uses a 6.02 robot framework core fork with a threading extension which we use at Bosch. 
In case you have issues you would get support from us (RobotFramework AIO team).
Regards,
 Thomas

**Comment by test-fullautomation** [comment]
Yes I agree. We also investigate in direction of running multiple processes instead of threads and are quite happy with this in one of our current projects.
For this we sync our Robot Framework processes with a RabbitMQ based event bus. The event bus even allows to integrate components with other programming languages.
Most likely we will provide a keyword library for such use-cases in future.

Use-cases which are not covered with this are e,g.:
You are connected to a device (e.g. serial port) and wait for a special message while the a test runs (e.g. a reset-message). If you don't poll you will still need threads for this. It's also possible to implement this with processes, but that's lot of overhead. Even serial interface is special because you can connect only once if you don't use other tools. A listener thread which deploys to other (waiting) threads is really smart for this. We do this since a decade like this with our own tools and would like to do with Robot Framework instead, too.

**Comment by test-fullautomation** [comment]
amendment:
maybe if you have a little time you can look into this pull-request for RobotFramework AIO: https://github.com/test-fullautomation/robotframework/pull/29/files
This is our idea how to realize threading in Robot Framework Core. There are many pull-requests related to threading following, but it shows the base idea.
Would be really nice to get a feedback or idea about this from you.
It's not yet stable enough that we would make a proposal based on 7.1, but If you would be interested we could increase our efforts. Of course we would also consider your findings/proposals.
I have resources where I can assign tasks.
