### ISSUE TITLE
Possible to iterate once over NoneType and empty list

### ISSUE THREAD

**Issue by kkotenko** [robotframework/robotframework#5036]
([Related report for RPA.Windows](https://github.com/robocorp/rpaframework/issues/1146))
MWE:

```
*** Settings ***
None test
    ${object_list}=  Set variable    ${None}
    FOR    ${child}     IN    ${object_list}
        Log    1    
    END

```

Expectation:

1) The for-loop does not get run (and possibly immediately produces an error)

Actual result:

1) one iteration is produced where ${child} is `None`

For what it's worth, the Python behavior is:
```python
empty_list = []
for x in empty_list:
    print(x)      
# this loop is not run

none_list = None
for x in none_list:
    print(x)
# TypeError: 'NoneType' object is not iterable
```

**Comment by kkotenko** [comment]
Same with empty list:

```
Empty test
    ${object_list}=     Create list
    FOR    ${child}     IN    ${object_list}
            Log to console    1
    END
```

**Comment by pekkaklarck** [comment]
Robot's `FOR  ${x}  IN  a  b  c` loop is same as `for x in ['a', 'b', 'c']` loop in Python. In other words, you are listing items to loop over, not giving the actual list that contains items. If you have a variable `${items}` that contains a list an use it like `FOR  ${x}  IN  ${items}`, it is same as having variable `items` and using `for x in [items]` in Python. In both cases the loop is valid, it is executed once, and on that round `${x}` in Robot or `x` in Python contains whatever the `${items}` or `items` variable contains.

Good news is that if you want your `${items}` list to be expanded so that items it in are iterated one-by-one, you can simply use `FOR  ${x}  IN  @{items}` syntax. That kind of loop is valid if `${items}` is an empty list, the loop isn't run at all, and the usage fails if `${items}` isn't a list or list-like.

**Comment by kkotenko** [comment]
Derp, I must have been really tired when I wrote that code. Thanks for the detailed explanation.
