### ISSUE TITLE
Improve handling of bytes/binary data 

### ISSUE THREAD

**Issue by WisniewskiP** [robotframework/robotframework#5041]
1. No short way to create Bytes. It is always necessary to use `Convert To Bytes`

2. there are Should be Equal as [Integers, Numbers,...] but not _as Bytes_
to compare bytes returned from keyword it is necessary to create variable using `Convert To Bytes` and then compare using `Should be equal`.
```robot
*** Keywords ***
Keyword returning bytes
    ${return} =    Convert To Bytes    \x1\x2
    [Return]  ${return}

*** Test Cases ***
Test
    ${bytes_result} =    Keyword returning bytes
    ${expected_result} =    Convert To Bytes    \x1\x2\x3
    Should be Equal   ${bytes_result}    ${expected_result}
```

3. to use `Should Contain` variable need to be created with bytes item:
```robot
Test
    ${binaryVar} =    Convert To Bytes    \x00\x01\x02\xA0\xB0
    Should Contain    ${binary1Var}    \xA0
    # Result: TypeError: a bytes-like object is required, not 'str'
```

4. Depending on the data, Fail message shows string representation of data:
```robot
Test
    ${binary1Var} =    Convert To Bytes    \x00\x01\x02\xA0\xB0
    ${binary2Var} =    Convert To Bytes    abc
    ${item} =  Convert To Bytes    \xC0

    Should Contain    ${binary1Var}    ${item}
    #Result: '☺☻\xa0\xb0' does not contain '\xc0'
   
    Should Be Equal    ${binary1Var}    ${binary2Var}
    # Result: ☺☻\xa0\xb0 != abc
```
it would be more helpful to see the raw data

**Comment by pekkaklarck** [comment]
Quick comments:
1. There's no built-in way to create other types than strings except for using variables like `${42}`. Typically conversion is done in libraries and automatic argument conversion helps. We also have plans to support conversion directly in Robot test data with something like `${x: int}` when declaring variables (including in user keyword arguments) and bytes will be supported as well. I don't think it makes sense to add something separately for bytes before that.S
2. `Should Be Equal As Bytes` could be added. I don't like type specific keywords like this too much, though, and we could alternatively enhance `Should Be Equal` so that it could get expected types as an argument like `type=bytes`.

**Comment by WisniewskiP** [comment]
thanks for explanation. I have created issues for 2-4 (#5052, #5053 & #5054)
