### ISSUE TITLE
Support argument conversion with `Should Be Equal`

### ISSUE THREAD

**Issue by WisniewskiP** [robotframework/robotframework#5053]
to compare bytes returned from keyword it is necessary to create variable using Convert To Bytes and then compare using `Should be equal`

```robot
*** Keywords ***
Keyword returning bytes
    ${return} =    Convert To Bytes    \x1\x2
    [Return]  ${return}

*** Test Cases ***
Test
    ${bytes_result} =    Keyword returning bytes
    ${expected_result} =    Convert To Bytes    \x1\x2\x3
    Should be Equal     ${bytes_result}    ${expected_result}
```
it would be easier to have possibility to have direct way to compare it directly.
It could be done by adding `Should be Equal as Bytes` similar to `Should be Equal as Numbers` or as @pekkaklarck suggested in #5041 by adding `type` argument to `Should be Equal` -> `type=bytes`

**Comment by pekkaklarck** [comment]
There are two possibilities:
- Add separate `Should Be Equal As Bytes` keyword.
- Enhance `Should Be Equal` itself so that it accepts an optional argument specifying the expected type.

I like the latter quite a bit more as it would then work also with other types. It should be possible to hook it up with our argument conversion logic so that anything the conversion supports would work. That would include usages like `type=datetime` and even `type=list[int]`.

It could also be more convenient to use this new functionality instead of the existing alternatives:
```
Should Be Equal As Integers    ${value}    42
Should Be Equal    ${value}    ${42}
Should Be Equal    ${value}    42    type=int
```

One design decision is that should both arguments be converted, should we only convert the second argument, or should we make that configurable. Current `Should Be Equal As ...` variants convert both values, but converting the value got from the system can hide problems and converting only the expected value could be better in some cases.

**Comment by pekkaklarck** [comment]
This would be a handy enhancement. Let's try to get it done already in RF 7.1.

**Comment by pekkaklarck** [comment]
We try to get RF 7.1 out soonish and I don't think we can fit this one in. I still think this is a handy enhancement and I move this to RF 7.2 scope.

**Comment by aaltat** [comment]
What was the deadline for 7.1?

**Comment by pekkaklarck** [comment]
The plan has been to get RF 7.1 out in July, but August is more realistic at this point. To get it out soonish, we have been thinking about RF 7.2 that could be done right after it.

**Comment by aaltat** [comment]
Might be possible, I will soon leave on holidays and at least first weeks are fully booked. But after that, there is time to do this

**Comment by pekkaklarck** [comment]
This is easy to implement by using `robot.running.TypeInfo`. There are, however, some design decisions to be made:

1. What should the new argument be named? I believe `type` is good as using it like `type=bytes` is pretty convenient. It hides the `type` built-in function, but only in the local scope of the keyword.
2. Should we convert both arguments or only one of them? `Should Be Equal As Integers` and others convert both, but I'm not sure is it a good idea. If, for example, you expect the value you are validating to be an integer but it is a string, converting it to an integer can hide bugs. Preserving it as a string and only converting the expected value would be safer.
3. If we convert only one argument, which one should we convert and thus consider the expected value? For me converting the latter feels more logical, and also keywords like `Should Start With` consider the first one the value to be tested and the latter the expected value. On the other hand, [jUnit's assertEquals](https://junit.org/junit5/docs/5.0.1/api/org/junit/jupiter/api/Assertions.html#assertEquals-java.lang.Object-java.lang.Object-) has arguments `expected` and `actual` in that order.
4. If we convert only one of the arguments and thus make it the expected value, should we also rename arguments to `actual` and `expected` from the current `first` and `second`. I believe it would be a good idea, but it probably should be done in a major release to avoid unnecessarily breaking usages like `second=value`. We should then also look at other similar keywords and rename their arguments consistently.
5. Should we optionally allow converting both arguments? I don't think it is that useful, but I don't have anything really against that either and it would be easy to implement. The hard part is coming up with a way to specify both types. Something like `type=(int, int)` is hard to understand and looks like a typing construct. `type=int  type2=int` would be _really_ confusing, because `type2` would actually affect an argument named `first` (unless it's renamed). Something like `actual_type` or `type_actual` would probably be ok, especially if we'd have a plan to rename arguments to `expected` and `actual` later.

**Comment by aaltat** [comment]
1. No good idea what name could be 
2. Can it be configurable?
3. If not configurable, then later
4. Renaming sounds good to me 
5. Browser or more precisely assertion engine supports conversion of received and executed values. But it’s configurable and by default only expected value is converted. Have seen needs in both cases.

**Comment by pekkaklarck** [comment]
My current favorite for configuring both types would be using arguments `type` and `type_actual`. This makes the common case like `type=bytes` convenient, but allows configuring both types. Naturally we should then rename `first` and `second` to `actual` and `expected` latest in RF 8.0.

Using `type_actual` and `type_expected` would be a bit more consistent, but that changes the common case to something like `type_expected=bytes`. That's longer than `type=bytes` and, what's worse, can give an expression that `bytes` would be the expected type.

An alternative that could work well is using `types` that can configure both types like `types=int, int`. The problem would be that configuring only one would either require something like `types=Any, bytes` or having both `type` and `types`. Neither of them feel that good for me. I guess we could also specify that `types=int` means configuring the second type, but it looks much more like a shortcut for `types=int, int`.

**Comment by pekkaklarck** [comment]
@aaltat How is conversion configured with assertion engine?

**Comment by aaltat** [comment]
Well use case is different. Because assertion happens inside of a keyword, like Get Text, users needs to set the type (or actually it’s not a type but a formatter, like strip space or lowercase) in a separate keyword and define in which keywords that is applied. Also there is a scope, meaning how long the definition lasts. And when Get Text keyword is called, with assertions, definitions are applied.

**Comment by aaltat** [comment]
Browser library solution is not optimal and adding this feature was done long after the assertion was created. Therefore creating syntax for this type of thing, without making it backwards incompatible was not easy. 

The point mainly was that with assertions, there was need, for some users, to apply the thing for both values, received and expected.

**Comment by pekkaklarck** [comment]
This is my current thinking how this should work:
1. Add `type` argument that specifies the type of the _second_ argument.
   - `type` should accept values that our normal argument conversion accepts like `int`, `list[int]`, `int | float`.
   - `type` should also accept a special value `auto` that means converting it to the type of the _first_ argument.
   - In addition to converting the _second_ argument based on the `type`, validate that the _first_ argument matches it.
2. Add `types` argument that specifies the type of both arguments.
   - `types` should accept all the same values as `type` except `auto`.
   - Convert both arguments based on it.
 3. Add separate keywords `Type Should Be` for validating that a value as an expected type and `Convert To` for converting a value to a specified type. `Should Be Equal` could use them internally, but they would be useful also on their own. These additions need a separate issue.

**Comment by JFoederer** [comment]
`Convert to` sounds a bit too generic to me. I would include a hint that it is types you are converting: `Convert to type`.

**Comment by JFoederer** [comment]
For the auto-typing there are multiple methods possible. A simple extension can be to have the type argument indicate whether it should behave left or right associative. When working with more complex (custom) types, there is often no need to convert the types. It can even be a limiting factor. Objects can implement their own `__eq__` operator and decide how the object deals in relation to other types. This includes a resolution mechanism for when only one type supports the operation and the other doesn't.

For a smarter auto convert you can also opt for a type-complexity based system. The most common type coming directly from Robot files is `str`, I would considered this the lowest complexity type in Robot context. When comparing to a higher complexity type, this new type gets precedence. For example: `"1" == 1` would evaluate to `False`, as would `1 == "1"`. But maybe you wanted to compare numbers when, for instance, the `int` comes from your SUT and the `str` directly from the Robot file. With the smart auto-convert the number-type gets precedence, so you try to convert `"1"` to the type of `1`, and then do the comparison.
