### ISSUE TITLE
Support setting values for child suites with `VAR` syntax

### ISSUE THREAD

**Issue by kstine** [robotframework/robotframework#5060]
The current VAR syntax does not support the children argument offered by the `Set Suite Variable` Keyword.

https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Set%20Suite%20Variable

```
Set Suite Variable    ${SUITE_VAR}    I can be used by child suites.    children=True
```

Syntax like this should be possible:

```
VAR    ${SUITE_VAR}    I should be usable by child suites.    scope=SUITE    children=True
```

**Comment by pekkaklarck** [comment]
This functionality of `Set Suite Variable` was overlooked when the `VAR` syntax was implemented. We can add it in RF 7.1, but we first need to agree on the syntax. Two options:
- Add a separate `children` option, as proposed above, that only works with `scope=SUITE`.
- Add a new `scope` value like `scope=SUITE WITH CHILDREN`. I'd prefer this over a new option, but I don't have any good proposals for the name.

**Comment by pekkaklarck** [comment]
As I wrote above, I think it's best to handle this by adding a new `scope` value instead of adding a new configuration option. The hard part is coming up with a good name for that new scope, but I believe `SUITES` should be fine. It's a bit problematic because It's so close to the current `SUITE`, but I doubt that's too big a problem.
