### ISSUE TITLE
Robot Framework does not run outside Windows if `signal.setitimer` is not available (affects e.g. Pyodide)

### ISSUE THREAD

**Issue by manykarim** [robotframework/robotframework#5063]
As described by @Snooz82  in Slack:

> Pyodide 0.23 and newer runs Python 3.11.2 which officially supports WebAssembly as a [PEP11 Tier 3](https://peps.python.org/pep-0011/#tier-3) platform. [#3252](https://github.com/pyodide/pyodide/pull/3252), [#3614](https://github.com/pyodide/pyodide/pull/3614)
> 
> That causes incompatibility to Robot Framework… :sob:
> RF uses setitimer and this seems not be included anymore, because it never worked on JavaScript…
> That means we can not update to Pyodide 0.23.0 from March 30 2023…
> current Version is 0.25.0
> 
> I updated it on the code playground now from 18.1 to 22.1 which caused RF 3.1 to die, due to missing python 3.10 support.
> We could refactor the code so, that depending on the selected Robot Version we do use a different Pyodide Version.
> And in the next Release of Robot Framework, we could actively check if we can support running on newest Pyodide version.
> Maybe that mean, that some timer signals are not working, but i think that would be ok.
> Pekka: if you think there is a possibility to patch robot/running/timeouts/posix.py so that RF could still live without it, this would be an option too.

When I tried Robot Framework in a Jupyter Lite Notebook using Pyodide, I received the error below:

`ImportError: cannot import name 'setitimer' from 'signal' (/lib/python311.zip/signal.py)`

**Comment by pekkaklarck** [comment]
I believe `setitimer` is only used for implementing timeouts. In that case we can workaround this issue by disabling timeouts on platforms that don't support it.

**Comment by pekkaklarck** [comment]
I was right that `setitimer` is only used by timeouts. The `signal` module is also imported to register a handler for `CTRL-C` and in the Process library. According to the [docs](https://docs.python.org/3/library/signal.html), WebAssembly platforms have emulated signals so I assume these imports are fine. Anyway, this needs to be tested once the `setitimer` issue is resolved.

It's easy to replace the normal timeout implementation with a dummy implementation if `setitimer` isn't available. We just need to decide what to do in that case if timeouts are actually used. Alternatives include:
1. Fail tests/keywords using timeouts with a message telling that timeouts are not available. This is easy to implement, but has a problem that also tests where timeouts wouldn't exceed will fail.
2. Emit a warning telling that timeouts are not available, but run keywords normally otherwise. This has a benefit that tests not hitting a timeout will succeed, but timeouts not actually being used can cause bad problems. Another problem is that this is more complicated to implement, because we probably didn't want to emit a warning with all keywords if a test timeout is used.
3. Run keywords normally without warnings. This would be easy to implement, but tests not being stopped by timeouts and there not being any warning about that doesn't sound like a good idea.

I believe the option 1. is the best. It's easy to implement and doesn't have a risk that execution would hang or there would be other problems due to keywords not being stopped when a timeout exceeds. I have this functionality implemented locally and will commit it shortly. The design can still be changed if other alternatives are considered better.

Do you @manykarim or @Snooz82 have an opinion about the above design decision? Can you test the latest code on Pyodide once the initial fix is committed?

**Comment by pekkaklarck** [comment]
No comments since February. I assume this is fine. If not, we can revisit this in future versions.
