### ISSUE TITLE
`VAR` syntax doesn't log the variable value like `Set * Variable` does

### ISSUE THREAD

**Issue by apallier** [robotframework/robotframework#5077]
The new `VAR` syntax introduced in RF7 doesn't log the variable value.

The `Set * Variable` keywords (like: `Set Variable`, `Set Test Variable`, `Set Suite Variable`, ...) automatically log the variable value and this is a nice behavior. Isn't it? :)

If the `VAR` syntax is intended to replace `Set * Variable` keywords, it would be great if the VAR syntax also performed the same logging.

Code example:

```robotframework
*** Variables ***
${VARIABLE}         ${1}
${VARIABLE_2}       ${2}

*** Test Cases ***
Test With Set Variable
    ${local_variable}=    Set Variable     ${3}
    Set Test Variable    ${VARIABLE}
    Set Suite Variable    ${VARIABLE_2}

Test With VAR Syntax
    VAR    ${local_variable}=    ${2}
    VAR    ${VARIABLE}    ${VARIABLE}    scope=TEST
    VAR    ${VARIABLE_2}    ${VARIABLE_2}    scope=SUITE
```

Log result:

![image](https://github.com/robotframework/robotframework/assets/7916922/965756b2-1281-4cb6-a887-334aa219c863)

**Comment by CorentinHache** [comment]
+1

**Comment by pekkaklarck** [comment]
Instead of writing `+1` comments, please use :+1: reaction in the original description. If you have something else to say, comments are fine, but `+1` comments are mainly noise and distraction.

The feature request itself looks fine for me and I believe we could add it in RF 7.1. If someone is against, please let us know why (and use :-1: reaction).

**Comment by pekkaklarck** [comment]
This is backwards incompatible, because logging the variable value may disclose sensitive information. That's also the reason I believe someone could be against this change.

We could consider adding a new configuration option to `VAR` that could be used like `log=False` if the value shouldn't be logged, but that makes the implementation more complicated. We also already have `--max-assign-length` command line option for controlling how much, if anything, of assigned variables are logged, so adding another configuration option may not be needed. If logging the value is implemented, we need to make sure it can be adjusted with the aforementioned command line option.

Although this is backwards incompatible, I don't consider the change so big that it needed to wait for RF 8.0.
