### ISSUE TITLE
Error Encountered When Running BDD Example (https://docs.robotframework.org/docs/testcase_styles/bdd)

### ISSUE THREAD

**Issue by josnin** [robotframework/robotframework#5133]
I encountered an error when attempting to run the BDD example provided in the Robot Framework documentation under the BDD section.

![image](https://github.com/robotframework/robotframework/assets/3206118/b6f8d3c6-e915-48ad-b095-54c7998c33b9)

**Comment by oliszymanski** [comment]
This issue should be on the RF webpages' Github project at: https://github.com/MarketSquare/robotframeworkguides

The reason behind the issue was the installation version of RF - it was a depricated version 6.0 - which was set in the config.json file. In short, config.json required version 6.0 which is an older version, while there was a newer version installed already - which of course didn't match the requirement of config.json linked below:
https://github.com/MarketSquare/robotframeworkguides/blob/main/code-examples/core/bdd-syntax/config.json

Already created a pull request in the response of your coment and the error you were encountering here:
https://github.com/MarketSquare/robotframeworkguides/pull/53 

Just waiting for the workflow approval now.

**Comment by josnin** [comment]
Thanks @oliszymanski
