### ISSUE TITLE
Document where `log-<index>.js` files created by `--splitlog` are saved

### ISSUE THREAD

**Issue by linh-eureka** [robotframework/robotframework#5155]
Currently, when using `--splitlog` command, it will generate additional JS files. When the output.xml is large, a bunch of *.js files are generated, which makes the current directory flooded.

**Needs:**
Ability to group them into a sub-folder to tidy up the directory.

E.g
`rebot --splitlog ./resource ./output.xml`

**Comment by linh-eureka** [comment]
i have found out that this one can be achieved quite easily with something like `rebot --splitlog -l ./resource/log.html ./output.xml`. But I think we need to document it more clearly for users in the https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#splitting-logs section

**Comment by catzilla-007** [comment]
@linh-eureka , I think the `-l` or `--log` command functions differently on the `--splitlog`, but so far it was also documented already (but in a separate section).

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#log-file

perhaps its possible to add a link in the `splitting-logs` section that directs to the `--log` documentation. however, it should be emphasized why we need to link that since `--log` is a totally different mechanism than `splitlog`

**Comment by pekkaklarck** [comment]
Yeah, JS files go the same directory as the log file itself and that location can be configured with the `--log` option already now. I'll update the docs to make it more explicit.

I guess someone could also want to have those JS files in a separate directory. That wouldn't probably be too complicated to implement, but it would require a new command line option and I'm not sure how often it would actually be used. Anyway, that apparently wasn't the need in this case.
