### ISSUE TITLE
Comparing paths with single keyword

### ISSUE THREAD

**Issue by aaltat** [robotframework/robotframework#5158]
Sometimes tests are run with different operating system and then comparing paths can be tricky if one operating system is Windows and others are example Linux. I know that I can do something like this:
```robotframework
    ${path} =    Get Path From Somewhere  
    ${expected_path} =    Normalize Path    ${OUTPUT_DIR}${/}foo/bar/path.txt
    Should Be Equal    ${path}    ${expected_path}
```
But Instead I would like to do something like this
```robotframework
    ${path} =    Get Path From Somewhere  
    Should Be Equal As Path    ${path}    ${OUTPUT_DIR}${/}foo/bar/path.txt
```
This should be easy to do with Python [pathlib](https://docs.python.org/3.12/library/pathlib.html) and doing:
```python
def should_be_equal_as_path(path1, path2):
    if Path(path1) != Path(path2):
        raise ValueError("Decription")
```

**Comment by pekkaklarck** [comment]
I understand the use case, but I don't think it's a good idea to add one more `Should Be Equal As X` keyword. Instead of that we should enhance `Should Be Equal` so that it can optionally do type conversion. We already have #5053 about that and, because our argument conversion supports `pathlib.Path`, it would provide the requested functionality. That issue was initially targeted for RF 7.1, but I just moved it to RF 7.2 scope. If you @aaltat are interested to help with it, getting it in already in RF 7.1 would be possible.

**Comment by pekkaklarck** [comment]
One thing to note is that `pathlib.Path` doesn't normalizing `..` components in paths:
```python
>>> Path('foo') == Path('bar/../foo')
False
```
The above paths would typically point to the same file/directory, but due to symlinks that's not guaranteed and `pathlib` doesn't want to guess. The only way to get `..` in the middle normalized is using [resolve()](https://docs.python.org/3/library/pathlib.html#pathlib.Path.resolve), but it also resolves possible symlinks and makes the path absolute which may not be desired. It's possible to use [os.path.normpath()](https://docs.python.org/3/library/os.path.html#os.path.normpath), but I'm not sure is that a good idea either. We could make this behavior configurable if we added a separate keyword for path comparison, but with the generic `Should Be Equal` that's probably not a good idea. I believe users needing to use `Normalize Path` explicitly in this case would be fine.

**Comment by aaltat** [comment]
I think I can give it a try for 7.1. We can move discussion in #5053 because it looks like better idea than having another keyword for this purpose only.

**Comment by aaltat** [comment]
Closing this one
