### ISSUE TITLE
`List Should Contain Sub List` does not detect failure if only difference is empty string

### ISSUE THREAD

**Issue by kkotenko** [robotframework/robotframework#5172]
I expect all of the following to raise AssertionError, as the second list is not a subset of the first:

```python
from robot.libraries.Collections import Collections

second = [""]
Collections().list_should_contain_sub_list(["first"], second)


second = ["first", ""]
Collections().list_should_contain_sub_list(["first"], second)


second = ["", "first"]
Collections().list_should_contain_sub_list(["first"], second)


second = ["", ""]
Collections().list_should_contain_sub_list(["first"], second)
```

However, only the last one raises the error.

**Comment by pekkaklarck** [comment]
This is due to the keyword looking for differences like
```python
diffs = ', '.join(str(item) for item in list2 if item not in list1)
```
and then reporting a failure if `diffs` isn't empty. The problem is that `diffs` is empty also if there's exactly one item that's not in the first list and that item happens to be empty. Easy to fix by first creating a list of differences, then checking is the list empty, and only after that format the error message if needed. `Lists Should Be Equal` uses similar construct, but there items in `diffs` cannot be empty and the same problem cannot occur with it. Changing it as well could be a good idea anyway.

When making changes to these keywords, it might be a good idea to change formatting the elements as well. Instead of using `', '.join(items)` we could use our `seq2str()` utility function that adds quotes around items as well as `and` between the last to items.
