### ISSUE TITLE
[BUG] allure count mismatch if the testcases are executed for multiple iteration

### ISSUE THREAD

**Issue by Praneeth20052001** [robotframework/robotframework#5173]
allure count mismatch if the testcases are executed for multiple iteration

suppose I run a testcase for multiple iteration eg : 20 iteration I need the 20 iteration report in allure 
 now if I run s single testcase multiple iteration since the testcase is not unique the allure will be showing testcase count as 1 
 but ideally we must get all the 20 iteration allure report

**Comment by Praneeth20052001** [comment]
can we have a new feature to specify the iteration like --i (iteration ) 

so that if you want to run the same testcase or testsuite for multiple iteration we can get in the log report alse 
eg:
test_case 
test_case_1
testcase_2
and so on and in alure aswell

**Comment by pekkaklarck** [comment]
This depends on how you run tests. If you run a single test 20 times from the console, you certainly get altogether 20 tests. Also, if you use `Test Template` and have 20 tests, you end up with that many tests. If, on the other hand, you use templates and have just a single test with 20 iterations in it, that is considered to be a single test by design. The design isn't going to change, but there are external tools like the DataDriver that support different approaches. You can also pretty easily create a custom solution yourself if needed.

If you have more questions, please use our Forum or Slack. If you have a concrete enhancement request, please submit a new one and explain it more thoroughly.
