### ISSUE TITLE
Given/When/Then should support other languages than English

### ISSUE THREAD

**Issue by spooning** [robotframework/robotframework#519]
> _Originally submitted to [Google Code](http://code.google.com/p/robotframework/issues/detail?id=519) by Andreas.EbbertKarroum on 30 Mar 2010_

When <a class="closed_ref" href="https://code.google.com/p/robotframework/issues/detail?id=500" title="Possibility to specify 'Test Template'  for all tests to ease data-driven testing"> issue 500 </a> is implemented, it would be nice to supply with the
[Template] keyword not only the test case that should be used, but also, in
what language that template is written. 

When I say

[Template]  User Login  en

RF will ignode prefixes "Given", "When", "Then", and "And" from keywords.
When I specify another language, like "de", then "Gegeben", "Wenn", "Dann",
and "Und". 

This has already been briefly discussed in the user group:
<a href="http://groups.google.com/group/robotframework-users/browse_thread/thread/488c5bc04ab2315d/7f81d5b118e7aa7a?lnk=gst&amp;q=german#7f81d5b118e7aa7a" rel="nofollow">http://groups.google.com/group/robotframework-users/browse_thread/thread/488c5bc04ab2315d/7f81d5b118e7aa7a?lnk=gst&amp;q=german#7f81d5b118e7aa7a</a>

**Comment by keskiju** [comment]
This would be a really useful feature. BDD tests/scenarios are basically software specifications that should be written in a domain specific language that all stakeholders understand very well. English is not always the best choice for that. Many other BDD tools already support multiple languages (cucumber, behat, etc). Hopefully we get language support also for robot framework soon.

**Comment by pekkaklarck** [comment]
Yes, this would be a nice feature. Getting it in just requires someone needing it badly enough to either provide a pull request or sponsoring the developement.

**Comment by felipecaputo** [comment]
I believe I can help with it. 

Anyone defined how it should work? maybe like [this](https://github.com/robotframework/robotframework/issues/519#issuecomment-47478667) or maybe support all of the Gherkin translations defined in any configuration

**Comment by pekkaklarck** [comment]
@felipecaputo Awesome! It's been some time since I've been thinking about this, but the comments you referred sounded pretty good still.

The most convenient solution would be able to use some command line option to specify the language to use. This would obviously require including various languages in Robot's code base, but I doubt that's a big issue. Most likely we could just use prefixes defined by Cucumber with attribution.

Open design questions:

1. What would be the name of the option? Possibilities include at least `--bddprefixes` and `--gherkinlanguage` and any combination of `bdd/gherkin` and `prefix/language`. Perhaps should look how Cucumber configures this.

2. Would we still need a way to specify custom prefixes? That would allow using languages Robot doesn't support, but perhaps we should just tell users to submit PRs with additional languages instead. My current thinking is that this functionality isn't needed. If can also be added later if there are concrete needs.

I don't expect this to be too complicated to implement and I'm willing to help if needed.

**Comment by felipecaputo** [comment]
@pekkaklarck I believe it won't be complicated.

About item 1, I believe supporting both options would be the best, I'll take a look at how Cucumber do and make it similar

About item 2, the PR would be the best, since would be great to support a lot of languages, and the community can do that very quick!

I'll try to work on this this weekend and let you know

**Comment by johnathafelix** [comment]
@pekkaklarck, I've read the comments on this issue and the proposed implementation (I'm mainly referring to your comments here) seems to be quite simple. I'm new to Python in general and I've been working with RF for the past 6 months, but I'd like to help with this if I can! 

Currently, at the company I work for, we have a workaround for this: create a "bdd_language.robot" file, then define the following keywords:

`*** Keywords ***`
`DADO QUE ${keyword}`
` Run Keyword     ${keyword}`

`QUANDO ${keyword}`
`    Run Keyword     ${keyword}`

`etc`

So we can call any keyword we've created with any of those "prefixes". It works fine, but now that the codebase is quite large, it's hard to use the IDE's functionalities (like 'Go to definition'), since the keyword is actually just a parameter to those keywords defined in the `bdd_language.robot` file. 

I've checked the RF code and apparently the ignoring-bdd-prefixes part is done in the `namespace.py` file, using a hard-coded list `['given ', 'when ', 'then ', 'and ', 'but ']`, inside the `_get_bdd_style_runner` function (please correct me if I'm mistaken).

So all we should do is just pass a list of prefixes to ignore, according to the language the user selects? I guess `--gherkin-prefixes` is a good name for the CLI option, but it leads to believe we are passing a list of prefixes as an argument, which is not very clean in my opinion. Maybe then `--gherkin-language` is a better option? We could then have a list of languages and their respective prefixes, and have languages added through PRs, as you suggested. Of course, this list could come with some predefined languages. Cucumber seems to support over 60 languages. Maybe we just add those same 60 languages at first? I guess that would satisfy the needs of most RF users. 

I just need to read the contributing guide again and check the proper way to implement this enhancement.

**Comment by pekkaklarck** [comment]
Sorry @johnathafelix for missing your comment earlier. Hope you are still interested to work on this. If yes, comment here or join #devel channel in our Slack community:
https://robotframework-slack-invite.herokuapp.com/

As you've find out, implementing this shouldn't be too complicated. About the design:

- I would also prefer being able to just give the name name of the language to use instead of listing prefixes.
- Being able to list prefixes might be useful as well.
- Should probably support multiple languages.
- Using languages supported by Cucumber, with attribution, sounds like a good idea.

We can discuss about the details separately. Slack might be best for free discussion and then we can write down decisions here.

**Comment by pekkaklarck** [comment]
Forgot to mention: This would be a great addition to RF 3.1 scope. The target is to release it in early June so there's still enough time to get this in.

**Comment by johnathafelix** [comment]
Thank you, @pekkaklarck! I'll start looking into it today. Hopefully it won't be too difficult for me :smile:

**Comment by pekkaklarck** [comment]
Awesome! I'll add this to RF 3.1 scope initially. I think the first steps should be these:

- You look at the code to see what would be a good way to pass this information from the command line to the code responsible on finding keywords. Let me know here or on the #devel channel if you got questions.

- We decide how to actually use this functionality. This includes the command line option name, should we allow giving custom prefixes or only support giving language to use, should we support multiple languages and if yes how, and so on. Related to this, you can see my [old comment](https://github.com/robotframework/robotframework/issues/519#issuecomment-383644007) that seems to be mostly valid still. Do you have opinions about these?

**Comment by johnathafelix** [comment]
Hey, @pekkaklarck! I didn't have much time to look deep into it last week, but I was looking at the Cucumber's language options and it raised some concerns: for some languages, they have multiple translations for some gherkin keywords. For example, apparently all the following sentences are valid for "given" in French:
`"Etant donné que ",
"Etant donné qu'",
"Etant donné ",
"Etant donnée ",
"Etant donnés ",
"Etant données ",
"Étant donné que ",
"Étant donné qu'",
"Étant donné ",
"Étant donnée ",
"Étant donnés ",
"Étant données "`

Do you think it's a good idea to implement this option? I don't speak French, but given its similarity with Spanish and Portuguese, I believe all these options can actually be reduced to just one and make things simpler. 

I'm now checking the code to see how to pass arguments via command line! And I'm sure I'll have a lot of questions! haha Thanks!

**Comment by pekkaklarck** [comment]
I'll de-scope this issue from RF 3.1 because I won't have time to look at it. If someone else has time and interest, I can add it back and I'm still available to help.

**Comment by andreportela** [comment]
Hi guys. Is this still a thing? 

I got really interested. Is there anyone working on it?

**Comment by pekkaklarck** [comment]
This is definitely still a thing. A thing waiting for someone interested to implement it to be more precise. The first step would be agreeing on how to configure this and design the overall functionality in general. I'm happy to help with that, either here or on out Slack, and would be happy to review PRs as well. Implementing this shouldn't be overly complicated, once we agree on the design, and could easily be included into RF 5.0 targeted for late 2021.

**Comment by boakley** [comment]
Instead of hard-coding the words, "given", "when", etc., and providing translations in different languages, I would like to see a more general-purpose solution.

My proposal is that when robot is asked to execute a keyword that doesn't exist, it calls a function to resolve the keyword. By default this keyword would see if it begins with "given", "then", etc and strips it off and returns the actual keyword just like what the core does now. 

Then, we can let a test or suite replace that implementation via a setting. They could then search for any special words that they want.
While this would be useful for automatically stripping "given", "when", "then" in any language the user wants, it could also be useful in other ways. For example, the function could be used to auto-load a library or page object. Or, it could be used to strip off leading numbers for people who want a test to look like a bulleted list. There are probably other uses as well.

It seems like this might be easy to implement. `_get_runner` already tries multiple methods to resolve a keyword, this would just add one more or maybe replace one special-purpose function with a more general-purpose function.

**Comment by andreportela** [comment]
Ok, I'll try to summarize some information here trying to narrow down the discussion and provide my thoughts as well:

## Things already suggested and my thoughts

### comment on [Jun 2014](https://github.com/robotframework/robotframework/issues/519#issuecomment-47478662)
> The workaround found by Andreas (please see comment #3) has IMHO two drawbacks:
> 
> 1. Keyword substitution clutters your log file. The built-in English BDD prefixes are eliminated silently keeping the log tidy.
> 2. Keyword substitution doesn't work smoothly with keywords from test libraries if those kw require arguments. Using such kw with the built-in English BDD prefixes is no problem.

I totally agree with those arguments. While creating a custom resource_file like the one suggested by the workaround is a nice kickoff to have users speaking their own domain language in the tests, integration with custom keywords is key to run a complex test suite and a tidy log is key to debug big suites with tons of tests. Those two benefits alone got me totally convinced that robot needs this support =)

> From this point of view a clean support of i18n BDD prefix would be preferrable.

Yep, I agree it's preferable because being able to describe a domain ubiquitous language is arguably a huge advantage the gherkin idiom can offer and domain experts who don't master English impose a hell of a challenge to implement it without their language support. Maybe full i18n support can be broken in many steps to ease implementation.

### comment on [Sep 2017](https://github.com/robotframework/robotframework/issues/519#issuecomment-326799505)
> 1. What would be the name of the option? Possibilities include at least `--bddprefixes` and `--gherkinlanguage` and any combination of `bdd/gherkin` and `prefix/language`. Perhaps should look how Cucumber configures this.

We are mostly talking about locale support for gherkin, so regardless the design I suggest something like `gherkin_locale`. 

I think the cli parameter suggestion would definitely work, but is there still room to talk about this? A test specification is implemented using a language (English, Portuguese, Spanish, etc), a mix of languages (Spanglish, Portunhol, etc) or something a bit more abstract (like a bulleted list), but once it's written, it's written using that language. It won't change unless you change the test specification. 

Ideally it should be totally possible to have multiple domain languages, multiple abstraction layers for a given high level domain language or even have a domain language composed by other domain languages. So I think it would be nice to support multiple locales in a test suite - locale support directly in the test file. I think that since the test specification should basically scream the locale(s), we could have a setting option in the .robot file instead of having a cli parameter. This way we could support working with multiple locales in a single suite run.

> 2. Would we still need a way to specify custom prefixes? That would allow using languages Robot doesn't support, but perhaps we should just tell users to submit PRs with additional languages instead. My current thinking is that this functionality isn't needed. If can also be added later if there are concrete needs.

In this context, supporting the locale by a settings parameter could be achieved by just passing a list of supported locales or providing a custom locale file in the settings section. It might be useful to think about pattern matching of some sort (regex?) to enable users to express their domain language in a flexible way.

### comment on [Apr 2018](https://github.com/robotframework/robotframework/issues/519#issuecomment-383505517)
> As you've find out, implementing this shouldn't be too complicated. About the design:
> 
> * I would also prefer being able to just give the name name of the language to use instead of listing prefixes.

Using the settings section of the test file can avoid the need for cli parameters in most cases and support running different .robot files with different locales in the same run. Arguably the same could be achieved with cli, but you would need to remember all the languages used in the whole test suite, the settings section just seems more natural and cleaner to me. BTW to ensure compatibility we could default to English if the user doesn't set this parameter in the file. So to start using a different locale, users would not need to change anything currently working, they would just need to explicit specify in the test file any locale different than the English default.

> * Being able to list prefixes might be useful as well.

For this one it might be useful to add a specific cli parameter (maybe `--help supported_gherkin_locales`?).

> * Should probably support multiple languages.

We could start very small with portuguese and spanish (languages I have easy access to), get feedback from the community and expand support later.

> * Using languages supported by Cucumber, with attribution, sounds like a good idea.

Maybe not mandatory for a first version, but surely a nice to have =)

### comment on [Apr 2018](https://github.com/robotframework/robotframework/issues/519#issuecomment-385403330)
> Hey, @pekkaklarck! I didn't have much time to look deep into it last week, but I was looking at the Cucumber's language options and it raised some concerns: for some languages, they have multiple translations for some gherkin keywords. For example, apparently all the following sentences are valid for "given" in French:
> `"Etant donné que ", "Etant donné qu'", "Etant donné ", "Etant donnée ", "Etant donnés ", "Etant données ", "Étant donné que ", "Étant donné qu'", "Étant donné ", "Étant donnée ", "Étant donnés ", "Étant données "`
> 
> Do you think it's a good idea to implement this option? I don't speak French, but given its similarity with Spanish and Portuguese, I believe all these options can actually be reduced to just one and make things simpler.

I think this is particularly important feature because it greatly helps to shape the script to the domain language and not the other way around for many locales (Portuguese included) where the context greatly influences the way people speak. Apart from the simple supported locales, it can be supported by providing a custom locale on settings section.

### comment on [Aug 2021](https://github.com/robotframework/robotframework/issues/519#issuecomment-891092739)
> Instead of hard-coding the words, "given", "when", etc., and providing translations in different languages, I would like to see a more general-purpose solution.
> 
> My proposal is that when robot is asked to execute a keyword that doesn't exist, it calls a function to resolve the keyword. By default this keyword would see if it begins with "given", "then", etc and strips it off and returns the actual keyword just like what the core does now.
> 
> Then, we can let a test or suite replace that implementation via a setting. They could then search for any special words that they want.
> While this would be useful for automatically stripping "given", "when", "then" in any language the user wants, it could also be useful in other ways. For example, the function could be used to auto-load a library or page object. 

I'm not sure if understand the proposed benefit because `_get_runner ` already tries many things to find the keyword. It can already find keywords in the test files, bdd style keywords, keywords in resource files, in libraries, it resolves keywords conflicts, etc. I'm not sure how I feel about auto-loading a library or page object that users are unable to trace from the settings section. Maybe being as explicit as possible is good thing in this case to avoid a hard to debug problem with a possible keyword conflict from something that was auto-loaded.

> Or, it could be used to strip off leading numbers for people who want a test to look like a bulleted list. There are probably other uses as well.

I like this idea because it helps to shape the script to the domain language and not the other way around. It may be necessary to start thinking in a locale gherkin pattern instead of a gherkin prefix though. Right now I don't think the implementation would be overly complicated but it might be too soon to say that.

## Suggested Design
### Reference Test Script - calculator_tests.robot
```robot
*** Settings ***
Documentation     Example test case using English default gherkin locale.
Resource    calculator.resource

*** Test Cases ***
Addition
    GIVEN calculator has been cleared
    WHEN user types "1 + 1"
    AND user pushes equals
    THEN result is "2"

Subtraction
    GIVEN calculator has been cleared
    WHEN user types "1 - 1"
    AND user pushes equals
    THEN result is "0"
```
### A Portuguese Test Script - calculator_tests_pt_br.robot
```robot
*** Settings ***
Documentation     Example test case using pt-br gherkin locale.
Resource    calculator-pt-br.resource
Gherkin Locale     pt-br

*** Test Cases ***
Adição
    DADO QUE a calculadora foi limpa
    QUANDO o usuário insere "1 + 1"
    E o usuário insere igual
    ENTÃO o resultado é "2"

Subtração
    DADO QUE a calculadora foi limpa
    QUANDO o usuário insere "1 - 1"
    E o usuário insere igual
    ENTÃO o resultado é "0"
```
### A Mixed Test Script - calculator_tests_mixed.robot
```robot
*** Settings ***
Documentation     Example test case using both en and pt gherkin locales.
Resource    calculator-pt-br.resource
Resource    calculator.resource
Gherkin Locale     pt-br, en-us

*** Test Cases ***
Addition
    GIVEN calculator has been cleared
    WHEN user types "1 + 1"
    AND user pushes equals
    THEN result is "2"

Subtração
    DADO QUE a calculadora foi limpa
    QUANDO o usuário insere "1 - 1"
    E o usuário insere igual
    ENTÃO o resultado é "0"
```
### A Custom Locale Test Script - calculator_tests_custom_locale.robot
```robot
*** Settings ***
Documentation     Example test case using a custom gherkin locale.
Resource    calculator-pt-br.resource
Gherkin Locale     amazones.locale

*** Test Cases ***
Adição
    SENDO QUE a calculadora foi limpa
    ASSIM QUE o usuário insere "1 + 1"
    E TAMBÉM o usuário insere igual
    PORTANTO o resultado é "2"

Subtração
    SENDO QUE a calculadora foi limpa
    ASSIM QUE o usuário insere "1 - 1"
    E TAMBÉM o usuário insere igual
    PORTANTO o resultado é "0"
```
### A Custom Gherkin Locale File - amazones.locale
```robot
*** Gherkin Locale Keywords ***
SENDO QUE
ASSIM QUE
E TAMBÉM
PORTANTO
```

We can have all these 4 files executed together by a single:
```shell
$ robot .
```

This way we could easily support the following use case:
### A Bulleted List Custom Locale Test Script - calculator_tests_custom_locale_bulleted_list.robot
```robot
*** Settings ***
Documentation     Example test case using a custom gherkin locale with bulleted list.
Resource    calculator.resource
Gherkin Locale     en-bulleted.locale

*** Test Cases ***
Addition
    - GIVEN calculator has been cleared
    - WHEN user types "1 + 1"
    - AND user pushes equals
    - THEN result is "2"

Subtraction
    - GIVEN calculator has been cleared
    - WHEN user types "1 - 1"
    - AND user pushes equals
    - THEREFORE result is "0"
```
### A Custom Gherkin Locale File using bulleted list - pt-br-bulleted.locale
```robot
*** Gherkin Locale Keywords ***
- GIVEN
- WHEN
- AND
- THEN
- THEREFORE
```

We can also have a cli command, so the user can check the standard supported locales:
```shell
$ robot --help supported_gherkin_locales
```

If we stretch a bit further, we could talk about simple pattern match instead of just prefix and support a use case like:
### A Pattern Match Custom Locale Test Script - calculator_tests_custom_locale_pattern_match.robot
```robot
*** Settings ***
Documentation     Example test case using a custom gherkin locale with pattern match.
Resource    calculator.resource
Gherkin Locale    en-pattern_match.locale

*** Test Cases ***
Addition
    GIVEN calculator has been cleared
    PROVIDED THAT user types "1 + 1" AND SUCCEEDS
    user pushes equals TO PERFORM THE OPERATION
    THEREFORE result is "2"
```
### A Custom Gherkin Locale File using pattern match - en-pattern_match.locale
```robot
*** Gherkin Locale Keywords ***
GIVEN @
PROVIDED THAT @ AND SUCCEEDS
@ TO PERFORM THE OPERATION
THEREFORE @
```

What you guys think about it?

**Comment by boakley** [comment]
On Tue, Aug 3, 2021 at 10:27 PM André Portela ***@***.***>
wrote:

> comment on Aug 2021
> <https://github.com/robotframework/robotframework/issues/519#issuecomment-891092739>
>
> Instead of hard-coding the words, "given", "when", etc., and providing
> translations in different languages, I would like to see a more
> general-purpose solution.
>
> My proposal is that when robot is asked to execute a keyword that doesn't
> exist, it calls a function to resolve the keyword. By default this keyword
> would see if it begins with "given", "then", etc and strips it off and
> returns the actual keyword just like what the core does now.
>
> Then, we can let a test or suite replace that implementation via a
> setting. They could then search for any special words that they want.
> While this would be useful for automatically stripping "given", "when",
> "then" in any language the user wants, it could also be useful in other
> ways. For example, the function could be used to auto-load a library or
> page object.
>
> I'm not sure if understand the proposed benefit because _get_runner already
> tries many things to find the keyword.
>

The proposed benefit is that the person or team writing the test can supply
any method they want without having to modify the core. If they need
support for a language not supported by the core they can trivially add it.
Right now the core of robot framework is very inflexible. It is going to
take a fairly large amount of effort to modify it to support
other languages in the BDD support and there's almost no way to have
coverage for every language used by the robot community.

If there had already been a mechanism to call a user-supplied function, we
wouldn't be having this conversation. The community would have already
built functions to do the bdd processing for various languages, and if they
hadn't, it would be trivial for you to write your own without requiring a
modification to the core.


> It can already find keywords in the test files, bdd style keywords,
> keywords in resource files, in libraries, it resolves keywords conflicts,
> etc. I'm not sure how I feel about auto-loading a library or page object
> that users are unable to trace from the settings section. Maybe being as
> explicit as possible is good thing in this case to avoid a hard to debug
> problem with a possible keyword conflict from something that was
> auto-loaded.
>
> Or, it could be used to strip off leading numbers for people who want a
> test to look like a bulleted list. There are probably other uses as well.
>
> I like this idea because it helps to shape the script to the domain
> language and not the other way around. It may be necessary to start
> thinking in a locale gherkin pattern instead of a gherkin prefix though.
> Right now I don't think the implementation would be overly complicated but
> it might be too soon to say that.
> Suggested Design Reference Test Script - calculator_tests.robot
>
> <a design based on one resource file per language...>
>
> ...
>
> What you guys think about it?
>
>
> Given that I'm the one that made the request for a more general-purpose
solution, I'm not a fan of this proposal. I would much rather have a
general-purpose solution. :-)

I don't see the point of hard-coding language support in the core when my
solution allows that and much more for about the same amount of effort.

**Comment by andreportela** [comment]
Could you share a small example of how could look like the overall design so I can have a better grasp of your proposal? =)

**Comment by boakley** [comment]
>  you want to expose the interface of the current keyword resolver logic (the one that strips the gherkin prefix) using dependency injection so although robot would still provide a default implementation, users could just inject their own implementation?

Yes, that's a fairly accurate description.

In short, we might add a new clause in `KeywordStore._get_runner` that is called when it can't find the keyword in the normal ways:

```
if not runner and self.custom_keyword_resolver:
    runner = self._get_runner_from_custom_resolver(name)
```

Though, it would be worth having a discussion as to whether this is called before or after all of robot's default methods. 

There would need to be a new suite setting that lets you set the resolver. That, or a built-in keyword that lets you set it at runtime. 

For example, the setting might look like this:

```
*** Settings ***
Suite Setup    set unknown keyword handler  custom resolver
```

You are then free to define `my_custom_resolver` however you wish. For example, it might look something like this:

```
import re
def custom_resolver(context, keyword):
    pattern = "((sendo que|assim que|e também|portanto) )(.*)$"
    match = re.match(pattern, keyword, re.IGNORECASE)
    if match:
        keyword = match.group(3)
        runner = context.get_runner(keyword)
        return runner

    return None
```

This could be used to search for gherkin words in any language you want, but it could also be used in other creative ways since you could do any string processing you want to remove prefixes, suffixes, or anything else.

**Comment by andreportela** [comment]
This is a very good idea, I like it =)

> Though, it would be worth having a discussion as to whether this is called before or after all of robot's default methods.

Maybe we can leave this decision up to users and provide higher flexibility if we expose the entire `KeywordStore` to be subclassed instead of adding another clause to `KeywordStore._get_runner`. We could provide one or two reference implementations that could both serve as a documentation of how to subclass it and provide default support for some given locales. This way users could even implement their own plug-ins and extensions to it.

Just one example: current `KeywordStore._get_runner` implementation tries a bunch of different ways to get a runner and before giving up, it handles it over to `KeywordStore._get_bdd_style_runner` which then tries to strip off some bdd prefixes and just calls `KeywordStore._get_runner` recursively to keep trying to get a valid runner. For this reason, this example works just fine currently:

```robot
*** Test Cases ***
Addition
    GIVEN given giVen calculator has been cleared
```

Users could provide their own faster implementation (if that's their thing) when they know the pattern of their domain language in advance.

> There would need to be a new suite setting that lets you set the resolver. That, or a built-in keyword that lets you set it at runtime.

For this solution I would prefer the suite setting from a cli parameter to avoid clutter test suites with implementation details about the configuration.

> You are then free to define `my_custom_resolver` however you wish. 

Mixing this idea with the subclassing, end users could implement a KeywordStore subclass like:
```python
from robot.running.namespace import KeywordStore

class CustomPTBRKeywordStore(KeywordStore):
    def _get_bdd_style_runner(self, keyword):
        pattern = "((sendo que|assim que|e também|portanto) )(.*)$"
        match = re.match(pattern, keyword, re.IGNORECASE)
        if match:
            keyword = match.group(3)
            runner = self._get_runner(keyword)
            return runner
        return None
```
Or tweek further the KeywordStore behavior to their own needs and finally execute the following:
```shell
$ robot --keyword_store com.company.package.CustomPTBRKeywordStore .
```
For this particular simple case, I think what we are really trying to do is just striping off some custom BDD patterns so we can find our keyword implemented somewhere else. For this, it might be possible to make the interface even cleaner using just a function like you proposed:
 ```python
import re
def my_own_pt_br_pattern_remover(keyword):
    pattern = "((sendo que|assim que|e também|portanto) )(.*)$"
    match = re.match(pattern, keyword, re.IGNORECASE)
    if match:
        result_keyword = match.group(3)
        return result_keyword
    return None
```
```shell
$ robot --keyword_pattern_remover com.company.package.my_own_pt_br_pattern_remover.
```
For flexibility and convenience we can even keep both methods available for users and provide default implementations. For instance, we could have a default locale implementation like:
 ```python
import re
def locale_bdd_pattern_remover(keyword, locale_patterns):
    for pattern, extraction_group in locale_patterns:
        match = re.match(pattern, keyword, re.IGNORECASE)
        if match:
            keyword = match.group(extraction_group)
            return keyword
    return None
```
To enable the following cli:
```shell
$ robot --keyword_pattern_remover robot.running.namespace.BDDi18nKeywordStore:en,pt-br,de .
```
I think I can work something out for a pull request with those info. What you guys think?

**Comment by boakley** [comment]
Personally, I don't want to have to subclass an internal robot class
to provide my own translations. That sounds much too heavyweight for
something as simple as translating a robot keyword.

I also don't like having to use a command-line option to use this feature.
I think the feature should be on a per-suite basis and controlled by a
setting or keyword. If I'm only doing bdd-style tests in one suite, I
shouldn't have to have this function be used in every suite. I don't see
the use of a new setting as clutter, I see it as valuable information for
understanding how the tests work.

**Comment by andreportela** [comment]
> Personally, I don't want to have to subclass an internal robot class
> to provide my own translations. That sounds much too heavyweight for
> something as simple as translating a robot keyword.

Yes, I agree that subclassing would be heavyweight for users that just want translation, that's why I proposed that convenience interface.

> I also don't like having to use a command-line option to use this feature.
> I think the feature should be on a per-suite basis and controlled by a
> setting or keyword. If I'm only doing bdd-style tests in one suite, I
> shouldn't have to have this function be used in every suite. I don't see
> the use of a new setting as clutter, I see it as valuable information for
> understanding how the tests work.

Yeah... I can relate to the cli option thing. It seemed like a good idea to avoid it at first, but when the discussion switched to enable a polymorphic keyword resolver I was not so sure that belonged to the test suite. Having said that, I totally agree with the following argument and I'm sold on a new setting.

> If I'm only doing bdd-style tests in one suite, I shouldn't have to have this function be used in every suite.

Maybe something like:
```robot
*** Settings ***
Custom Keyword Resolver    com.company.package.my_own_bdd_pt_br_keyword_resolver
```

**Comment by vokiput** [comment]
Is it in progress?
Can we use https://github.com/cucumber/gherkin-python here to get Gherkin tokens?

**Comment by pekkaklarck** [comment]
We decided to move this one and highly related multilanguage markers issue (#4096) to RF 5.1. That wasn't done because we don't consider these issues important, on the contrary, but simply because RF 5.0 already contains lot of great new features and we want to get it out as soon as possible. These translation related issues will be the highest priority issues in RF 5.1 and the plan is to start its development right after RF 5.0 has been released.

**Comment by boakley** [comment]
What's the status of this? Is robot going to adopt the custom resolver solution so that we can provide our own functions for resolving keyword names, or are translations going to be built into the core? I sure hope the more general solution is supported so we can provide our own translations fairly simply.

**Comment by MoreFamed** [comment]
Adding myself to the issue...

**Comment by pekkaklarck** [comment]
See [this comment](https://github.com/robotframework/robotframework/issues/4096#issuecomment-1135929124) for issue #4096 for a list of everything that can be translated in RF 5.1, including the BDD prefixes that are covered by this issue. With these prefixes it's probably a good idea to look at what terms [Cucumber](https://cucumber.io/) uses.

We obviously need help with translations from the community. We have decided to use the `#localization` channel on our [Slack](https://robotframework.slack.com/) as the main collaboration forum and separate channels can be created for each language there as well. If you are interested to help but haven't yet joined out Slack community, you can get an invite [here](https://rf-invite.herokuapp.com/).
