### ISSUE TITLE
Possibility of changing default log.html or report.html template route to custom one

### ISSUE THREAD

**Issue by Mao6B** [robotframework/robotframework#5190]
Previously, until Robot Framework v6.1a1, by changing [LOG](https://github.com/robotframework/robotframework/blob/v6.0/src/robot/htmldata/__init__.py) value to a custom route, i.e: C:/custom_folder/log_templates/log.html, we could change the default log.html or report.html template.

Since Robot Framework v6.1b1 this is no longer a possibility due to file [template.py](https://github.com/robotframework/robotframework/blob/v6.1b1/src/robot/htmldata/template.py) having changed and not letting any other routing options due to lines 50 and 54.

v6.1a1
![image](https://github.com/user-attachments/assets/9c123271-4231-4876-8e0c-12fdefda71e6)

v6.1b1

![image](https://github.com/user-attachments/assets/8eaacb6f-bbf5-4c2d-95b8-b01664f8f88e)

Is there any other way to change the template option or is just gone?

**Comment by pekkaklarck** [comment]
Changes that break your use case were due to zipapp support (#4613). That's unfortunate, but being able to change log and report templates have never been a supported feature. I'm fine making it possible again, especially if you can provide a pull request that does it, doesn't break existing functionality, and isn't overly complicated. Is that something you are interested it?

Even if this functionality would be available again in the future, it wouldn't be officially supported. The reason is that any custom template would depend on the syntax our log/report use and we cannot make any backwards compatibility promises to it. We are actually planning to re-implement logs and reports in the future (we are starting from Libdoc, #4304), and that would break all possible templates anyway. After the new log/report tech is in place, we can consider making it possible to customize them either by supporting custom templates or by allowing external content to be injected to them.

**Comment by Mao6B** [comment]
Okay, thanks for the response, we will wait and see what hold in the future.
