### ISSUE TITLE
Allow WHILE limit to be modified in listener V3

### ISSUE THREAD

**Issue by Blashaq** [robotframework/robotframework#5194]
Currently it is impossible to change WHILE limit settings using the listener interface- listener object is created before control is passed to attached listeners, thus modifying while body parameters related to the limit is pointless.

It might be useful to allow listeners to change this- for example, an user might want to redefine default limit behaviour for WHILE loops in case it was not explicitly defined. For example, instead of having default 10k iterations as a default, no-configuration WHILE loop would abort after 10 seconds using this feature.

**Comment by pekkaklarck** [comment]
Sounds reasonable. Let's see can we still squeeze this to RF 7.1 or does it need to wait for RF 7.2.

**Comment by pekkaklarck** [comment]
Implemented in PR #5192 by @Blashaq. Thanks for contribution!

**Comment by pekkaklarck** [comment]
One limitation of modifying the loop limit is that in `start_while` it isn't possible to modify the limit shown in the log file. The reason is that although the passed in `result` object can be modified, limit information has already been written to output.xml as the `limit` attribute of the `<while>` element. The best way to fix that would be changing output.xml writing so that it would be done only after listeners are called, but that is likely quite a big task. Alternatively we could write `limit` as a a separate element and not as an attribute, but that would feel a bit odd for me. Anyway, this isn't in the scope of this issue.
