### ISSUE TITLE
Per-fle language configuration fails if there are two or more spaces after `Language:` prefix

### ISSUE THREAD

**Issue by HelioGuilherme66** [robotframework/robotframework#5202]
[Example_localized_files.zip](https://github.com/user-attachments/files/16929400/Example_localized_files.zip)

If we have two spaces after `Language:` the language is not recognized and the test run fails.

Attached is Finnish localized test suites with and without the extra space.

Windows 10, Python 3.10,9 Robot Framework v7.1rc2.

**Comment by pekkaklarck** [comment]
This is due to spaces acting as a separator between tokens. Robot expects the language name to follow the `Language:` marker in the same token and in this case the name is in the next token. I guess we could look the name also from the following data token, but in that case we probably needed to also give that token the same `CONFIG` type than the first token has. Alternatively we could merge the tokens so that there would be only one `CONFIG` token with the combined value. I don't consider this too high priority, but it's worth fixing anyway.

**Comment by pekkaklarck** [comment]
This is easy to fix so that values from all data tokens on a line starting with `Language:` are joined together. These tokens then also need to get the `CONFIG` type as well.
