### ISSUE TITLE
downloading files in headless mode with selenium is broken

### ISSUE THREAD

**Issue by p0l1c3c4r** [robotframework/robotframework#5208]
I had some tests that downloaded files, and they broke suddenly on the 29th of August. The file is not downloaded anymore in headless mode, it is working in headed mode tho.

I tried with downloading the chrome installer from google.com/chrome with a ChatGPT generated generic script from scratch and it's not working there either.

RFW version: 7.0.1
chrome version: 1128.0.6613.138
chromedriver version: 128.0.6613.137 
OS: win server 2009 1809

**Comment by pekkaklarck** [comment]
No idea what's causing this, but the problem certainly isn't in Robot Framework itself. You don't tell what web testing library you use, but unless you have noticed updated it, it's unlikely the problem is in it either. Probably there's some change to the browser and the underlying web testing tool hasn't yet been updated. I recommend you to search have others had this issue and if that doesn't provide any info, to ask about it on our Slack or Forum.

This tracker is only for Robot Framework itself and this issue is rhus
