### ISSUE TITLE
Document that `Get Variable Value` and `Variable Should (Not) Exist` do not support named-argument syntax

### ISSUE THREAD

**Issue by Mkinen** [robotframework/robotframework#5235]
Hi,

I noticed that I am not able to pass `default` argument for `Get Variable Value` from `BuiltIn` as keyword argument. I.e. the following does not provide expected result: `${result}  BuiltIn.Get Variable Value  ${MY_VARIABLE}  default=My Default`

One would expect `${result}` to have `My Default` as return if `${MY_VARIABLE}` does not exist. Instead `default=My Default` is returned. 

![get_variable_value_example](https://github.com/user-attachments/assets/9fe63afc-67a7-4c82-811d-f63c547cac23)

I didn't find any notion of this functionality anywhere and if the keyword works as expected, I would assume that this was mentioned in the documentation.

This was tested with version 7.0.

**Comment by a-matta** [comment]
The decorator `@run_keyword_variant(resolve=0)` atop the [`get_variable_value`](https://github.com/robotframework/robotframework/blob/master/src/robot/libraries/BuiltIn.py#L1521) implementation ensures a `NullArgumentResolver` is used intead of a `NamedArgumentResolver`. Thus the entire string is handled as a value. Seems by design (I don't know). The docstring indicates correctly. 

https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Get%20Variable%20Value
![image](https://github.com/user-attachments/assets/fb879f98-60fb-45c1-a44e-4c2da0f85792)

Seems the intention is to use this without the `default=` prefix.  `¯\_(ツ)_/¯`

**Comment by pekkaklarck** [comment]
`Variable Should Exist` and `Variable Should Not Exist` have a similar situation with their `message` argument. Also some other keywords are possibly affected, but I doubt they'd in general be used with the named-argument syntax anyway.

**Comment by pekkaklarck** [comment]
As #5025 demonstrated, various other keywords had the same problem. Instead of adding a note about this to all their docs, I decided to explicitly mark these arguments positional-only. That was done also to keywords that got a note to their docs as part of this issue. Notes were preserved otherwise, but the comment about us hopefully fixing the limitation in the future was removed.
