### ISSUE TITLE
Concatenating variables containing bytes should yield bytes

### ISSUE THREAD

**Issue by WisniewskiP** [robotframework/robotframework#5259]
When joining bytes with ${x}${y} string is returned instead of bytes. 

consider following test case:
```robot
*** Test Cases ***
Join bytes
    ${destination} =    Convert To Bytes    FF FF FF FF FF FF    hex
    ${source} =         Convert To Bytes    00 80 E1 00 00 00    hex
    ${data} =           Convert To Bytes    00 01 08 00 06 04 00 01     hex
    
    ${frame} =   Set Variable    ${destination}${source}${data}
```
currently results in `${frame} -> '\\xff\\xff\\xff\\xff\\xff\\xff\x00\\x80\\xe1\x00\x00\x00\x00\x01\x08\x00\x06\x04\x00\x01'`
expected result is bytes

**Comment by pekkaklarck** [comment]
At the moment when variables are concatenated with constant strings or with other variables like `Hello, ${name}!` or `${x}${y}`, the result is always a string. I agree that when concatenating only variables like `${x}${y}` and all variables contain bytes or bytearrays, it would be more logical if the result would be bytes as well. That would make working with bytes and binary data in general simpler. Good news is that this is also pretty easy to implement.

This is related to #5052 that reports a very strange string representation that bytes have. That strange representation is actually seen also in the description where some bytes in the example result are shown like `\x00` and others like `\\x80`. I'll explain why in the aforementioned issue.

**Comment by pekkaklarck** [comment]
This change isn't backwards compatible, because the value keywords get if they are passed an argument like `${x}${y}` and all variables contain bytes changes. I don't expect this to cause problems in practice because:

- Such keywords anyway get bytes if variables are used on their own like `${x}`. They should thus handle bytes just fine.
- The current string representation you get is in practice unusable. See #5052 for more details.
