### ISSUE TITLE
Add log messages to result model that is build during execution and available to listeners

### ISSUE THREAD

**Issue by HenrikSchuette** [robotframework/robotframework#5260]
In the new ListenerV3, it would be nice if result.messages were already populated in end_test and end_keyword.
Currently, the messages have to be collected using log_message to be used in end_test and end_keyword.
An example workaround looks like this:

```
def start_body_item(self, data, result):
    self.body_items.append(result)

def log_message(self, message: Message):
    result_msg = result.Message(
        message=message.message,
        html=message.html,
        level=message.level,
        timestamp=message.timestamp,
        parent=message.parent,
    )
    if self.body_items:
        self.body_items[-1].body.append(result_msg)

def end_body_item(self, data, result):
    self.body_items.pop()
```

**Comment by pekkaklarck** [comment]
It's true that the model that's generated during execution doesn't currently contain logged messages. Prior to RF 7.0 that model didn't contain keywords or control structures either, but they were added as part of big listener v3 enhancements (#3296) to make it possible to inspect the model. Messages were left out at that point because that would have required more work (there was a _huge_ amount of work also without it) and it wasn't sure is anyone interested in messages. This issue makes it clear that there's interest, and I can investigate what adding messages would require. This can seen as a pretty big limitation with the listener API so if adding messages is easy, I add this issue to RF 7.2 scope. If it requires more work, it needs to wait for RF 7.3.

**Comment by pekkaklarck** [comment]
This seems to be pretty easy to do. I try to get it done later today. The only design decision is what messages to include. I believe filtering messages based on the normal log level the best solution. That way there are same messages available during execution that are written to output.xml and thus available afterwards.

**Comment by pekkaklarck** [comment]
As I commented earlier, implementing this particular feature wasn't too complicated. Interestingly various bigger and smaller bugs were uncovered during implementation and testing (see the referenced issues above), but now also they are all fixed.
