### ISSUE TITLE
If test is skipped using `--skip` or `--skip-on-failure`, show used tags in test's message

### ISSUE THREAD

**Issue by DanielKopp94** [robotframework/robotframework#5264]
Using the command line option `--skip` <tag> prints `Test skipped using '--skip' command line option.` It would be nice to get not just that information but instead it will be shown due to which tag the test case has been skipped.

An example would be if adding the two command line options `--skip not_ready` and  `--skip broken` the output shows something like `Test skipped due to skipped tag 'not_ready'`.

**Comment by pekkaklarck** [comment]
I've never really liked the current message and the proposed on looks much better to me. Changing it is also trivial.

There's a problem that if you use `--skip foo --skip bar`, we cannot easily determine which one matched a particular test so the message will be like `Test skipped due to skipped tags 'foo' and 'bar'`. I consider it good enough.

**Comment by pekkaklarck** [comment]
If you use the special `robot:skip` tag, the current message is `Test skipped using 'robot:skip' tag.`. I think these messages should align and thus the other message could be `Test skipped using 'no_ready' tag.`. Do you @DanielKopp94 have opinions about this? I'm fine changing both messages as long as they are consistent.

**Comment by pekkaklarck** [comment]
One more thing to take into account is that `--skip` also accepts patterns like `--skip bug:*`. In such cases `Test skipped using 'bug:*' tag.` isn't exactly correct, but I consider it good enough. Using `pattern` instead of `tag` would be a bit better in this case, but it would be pretty odd in the common case and there's no ready-made way to check are these tags constants or patterns.

**Comment by pekkaklarck** [comment]
Another, and highly related, message I don't particularly like is this one that you get if you use `robot:skip-on-failure` or `--skip-on-failure`:
> Test failed but skip-on-failure mode was active and it was marked skipped.
>
> Original failure:
> [message]

If we start changing these messages, I believe this would be a lot better:
> Failed test was skipped using 'not-ready' tag.
> 
> Original failure:
> [message]

**Comment by DanielKopp94** [comment]
I like the solution you proposed to write the messages containing the tags and the patterns. As we could have more then one tag it would be great to have all the tags in a list. 
So in general the messages could look like `Test skipped due to skipped tags ['foo', 'bar']`, `Test skipped due to skipped tags ['foo']`

In case the patterns are used it would be nice to distinguish them if possible. Something like `Test skipped due to skipped tags ['foo', 'bar'] and patterns ['bug:*']`. If this would make sense. As we are not using patterns for this case I am not sure if this would be a use case.

For the `skip-on-failure` I would suggest as you proposed the same method as this then is aligned with the other.

**Comment by pekkaklarck** [comment]
Notice that the message I used was a bit different to than what you proposed to make is possible to use it also with the special `robot:skip` tag. We also should use format `'tag1', 'tag2' and 'tag3'` instead of `['tag1', 'tag2', 'tag3']` when there are multiple tags. This is easy as we have a utility function for that. I summarize my proposals bellow.

My proposal related to `--skip`:
- Use `Test skipped using 'not-ready' tag.` if there's a single tag.
- Use `Test skipped using 'not-ready' and 'another' tags.` if there are two or more tags.
- Don't separate constant tags and patterns because that's not easy. Can be done separately later if someone is interested.

My proposal related to `robot:skip`:
- Use `Test skipped using 'robot:skip' tag.`. This is exactly the same format as above.

My proposal related to `robot:skip-on-failure` and `--skip-on-failure`:
- Use `Failed test was skipped using '<tag>' tag.\n\nOriginal failure:\n<failure>` if there's one tag.
- Change `using '<tag>' tag` to `using '<tag1>', '<tag2>' and '<tag3>' tags` if there are two or more tags.

**Comment by DanielKopp94** [comment]
I like the format you proposed. It looks nice and gives the needed information
