### ISSUE TITLE
Libdoc type hints for keywords with embedded arguments

### ISSUE THREAD

**Issue by franzhaas** [robotframework/robotframework#5280]
When i make a libdoc documentation from this code. The type hint information that n shall be an int gets lost

```python


from robot.api.deco import keyword


class a:
    @keyword("Shout ${n} cheers for")
    def hurray(self, n:int):
        """Cheer them on as much as you like!

        Example:
        | `Shout 3 cheers for` | Robot |
        """
```

With this version, this information is preserved
```python


from robot.api.deco import keyword


@keyword("Shout ${n} cheers for")
def hurray(self, n:int):
        """Cheer them on as much as you like!

        Example:
        | `Shout 3 cheers for` | Robot |
        """
```

Do you think this is intentional? What would I need to do to have the type information presented in the libdoc document even if my keyword is part of a class?

Thanks in advance,
Franz

**Comment by pekkaklarck** [comment]
Your keywords have _exactly_ the same signature `self, n: int` which is a problem because the latter one is implement as a function outside a class. Signatures also don't match the example shown in the documentation.

I assume the correct signatures should be `self, n: int, name: str`  and `n: int, name: str`, respectively. With these signatures the generated documentation is exactly the same for both of the keywords. Notice that the embedded argument `n` isn't shown separately, it's only visible in the keyword name as `${n}`. This is different to `name` that's a normal argument and shown the same way as with normal keywords. I don't think this is a huge problem, but showing `n` somehow, especially its type hint, would be nice.

Please submit a separate issue if you think embedded arguments should be shown different. I'll anyway close this issue as there the problem seems to be in the example, not in Robot.
