### ISSUE TITLE
`lineno` of keywords executed by `Run Keyword` variants is `None` in dry-run

### ISSUE THREAD

**Issue by Snooz82** [robotframework/robotframework#5282]
When executing a dryrun and having any kind of `Run Keyword` variant, the child keyword will have wrong type in ListenerV2.

`lineno` should be `int` but in that specific case it is None.
At least according to the typing of `StartKeywordAttributes` and the other situations, where a line number is not available.

Example:
```robotframework
*** Settings ***
Library    Listener.py


*** Test Cases ***
Reproduction
    Run Keyword    Log    this has the wrong lineno
```

```python
import json
from robot.api import logger

class Listener:

    def __init__(self):
        self.ROBOT_LIBRARY_LISTENER = self
        self.ROBOT_LISTENER_API_VERSION = 2

    def _start_keyword(self, name, attributes):
        logger.console(f"\nKeyword started: {name}")
        logger.console(f"    attributes: \n{json.dumps(attributes, indent=2)}")

    def kw(self):
        pass
```

**Comment by pekkaklarck** [comment]
I can reproduce the problem and know how to fix it.

We cannot guarantee the line number to be exactly correct, though. The problem is that we only know the line where `Run Keyword` itself was used and in usages like
```
Run Keyword If    ${expr}
...    Keyword    arg
```
the actual keyword is on a subsequent line. Anyway, that's much better than line number not being set at all.

**Comment by Snooz82** [comment]
on real execution it works as expected.

**Comment by pekkaklarck** [comment]
I meant that the line number of the actually executed keyword is wrong if there's a line continuation. It's always set to the line containing `Run Keyword`.

**Comment by pekkaklarck** [comment]
Even after this fix, `lineno` can be `None` if a keyword has been executed by a listener. I'll update docs accordingly as part of this issue.

**Comment by pekkaklarck** [comment]
Notice that although the example in the description uses a v2 listener, but the same problem affects also `data.lineno` when using listener API v3.

**Comment by Snooz82** [comment]
shouldn’t it then maybe 0 instead of None?

**Comment by pekkaklarck** [comment]
That was discussed on Slack some time ago. I think I personally proposed 0 or -1, but others liked None more. I guess None makes it more clear that the line number isn't known. I'm fine changing it, but there needs to be consensus because I absolutely don't want it to be changed back again.

**Comment by Snooz82** [comment]
i personally do not have a strong opinion, wether -1 or None should be used.
but if None is used the type hint should state that.
at the moment it states `int`.

**Comment by pekkaklarck** [comment]
Model object like `robot.running.Keyword` already have `lineno: int|None = None`, but `robot.api.interfaces.StartKeywordAttributes` incorrectly only have `lineno: int`. I've already got that fixed locally and also mentioned that in the User Guide, but I haven't yet pushed changed. The reason is that your example also showed that the status of `Run Keyword` was `NOT RUN` when it was supposed to be `PASS`. I investigated that, submitted #5289, and will soon push fixes for both of these issues.
