### ISSUE TITLE
Documentation incorrectly claims that `--tagdoc` documentation supports HTML formatting

### ISSUE THREAD

**Issue by SebClapie** [robotframework/robotframework#5283]
Hello,

Issue found with
$ rebot --version
Rebot 7.0.1 (Python 3.10.11 on win32)

I'm trying to use basic formatting with --tagdoc option, like
rebot --tagdoc "my_tag:\*my_doc\*" report.xml
 
But it's not interpreted like bold formatting like documentation said, same for italic formatting.

   --tagdoc pattern:doc *  Add documentation to tags matching the given
                          pattern. Documentation is shown in `Test Details` and
                          also as a tooltip in `Statistics by Tag`. Pattern can
                          use `*`, `?` and `[]` as wildcards like --test.
                          Documentation can contain formatting like --doc.
                          Examples: --tagdoc mytag:Example
                                    --tagdoc "owner-*:Original author"

Also, --doc support documentation from file, but this is not the case for --tagdoc.

Rgds
SebC

**Comment by pekkaklarck** [comment]
I can reproduce the problem and also the fact that both the `--help` text and the User Guide claim that the `--tagdoc` documentation supports HTML formatting. The strange thing is that either this has never worked or it has been broken a long time ago. I tested with old versions all the way to RF 3.0, the first version to support Python 3, and the result was the same.

It would obviously be nice to support this functionality, but that doesn't seem to be too easy. The problem is that the documentation is shown in the statistics using the `title` attribute that only supports text. Fixing this would thus require changes not only on our Python code (those changes wouldn't be too hard) but it would also require introducing some custom widget for showing the title. That's way too much work for RF 7.2 and may not be worth the effort on its own in general. We are, however, planning to re-implement log and report using a new tech in the future (we'll start from Libdoc outputs #4304) and then adding a widget for showing additional documentation is certainly possible.

I'll "fix" this issue by updating documentation so that references to HTML formatting are removed. If you think HTML formatting is a useful feature, please submit a new issue about that and we can consider it later. If you find it super important, look at creating a PR implementing.

**Comment by pekkaklarck** [comment]
Hmm, there's also a related bug handling URL. If you try `--tagdoc "example:http://example.com"`, the tag will show in statistics like `examplehttp://example.com">` where the `example` part is on bold like other tag names. The reason is that although `--tagdoc` doesn't support HTML formatting, URLs are linkified and as the result the HTML source code contains something like
```
<span title="<a href="example.com">http://example.com</a>">example</span>
```
which is invalid. There are two ways to fix this:
1. Don't linkify URLs on Python side. This would mean that the title attribute would contain just `http://example.com` that would look fine. A problem would be, that the URL wouldn't be linkified when viewing details for that particular tag in the report.
2. Linkify as nowadays, but escape HTML content in statistics. This means that the title text will show `<a href="example.com">http://example.com</a>` which isn't as nice as showing just the URL, but the URL would be a link when viewing tag details in the report.

I believe the second fix is better. I'll do that as part of fixing this issue.
