### ISSUE TITLE
`robot:skip` and `robot:exclude` tags do not support variables

### ISSUE THREAD

**Issue by simonmeggle** [robotframework/robotframework#5292]
I try to use a variable in the second test so that the resulting tag is `robot:skip`:

```robotframework
*** Variables ***
${SKIP_FLAG}    skip

*** Test Cases ***
Test One
    Log  Test One was executed.
    VAR  ${SKIP_FLAG}  skip  scope=suite

Test two
    [Tags]  robot:${SKIP_FLAG}
    Log  Test Two was executed.
```
My expectation was that I can conditionally skip other tests _completely_.
The tag gets set correctly, but the test still gets executed. 

https://robotframework.org/code/?codeProject=N4IgdghgtgpiBcIDCBXAzgFwPZRAGhABMY0BjAJwEsAHDSrMBEfEAM0oBsSEBtUdrgDlocRABUSGAMopKGGADpyWAEZYMLUg3lgNiADpgAVCYAEANQhUIKrmlMmjhgCTApAaQCSABQD6AMQAZAEEAcQBfUyjTNABrGkNDR1MJTFMkCDQSBxNDVIxTAHkwGENo00CsAHMo-KKS0wB3TNMYAA8YUhR5QgUy6PNggCUo1w8fAJCIqLiaGa1qGABeNFl5RLA6jEasfqieMQgqtABdKOU1DHgxrz8gsPC9iurayRSdppb2zu6YXpBwicCMQqAA3P7eZQAK06egw5BQMAIF3U5hg5DQ9EYiAA7AoAIwElgojDBcjHBDAcLImAAR1k5BgsF0aF4J3CQA

**Comment by pekkaklarck** [comment]
This is due to the code looking for the `robot:skip` tag from the `data` object that contains the original tag. It should be looked from the `result` object where variables are resolved. This is easy to fix, but there are two problems:
- Detecting are all tests skipped or excluded when a suite starts isn't possible (#4571). I guess that's fine in this case.
- We need to check how other special tags behave in this regard. That is a somewhat big task so better to do all this in RF 7.3.

**Comment by pekkaklarck** [comment]
I took a quick look at other related tags and they already support variables (i.e. look at the tags of the `result` object). For example, the behavior of the following tests depends on do you run them with `-v skip`, `-v continue` or `-v exit`.

```robotframework
*** Test Cases ***
First
    [Tags]    robot:${what}-on-failure
    Fail    xxx
    Fail    yyy

Second
    Log    xxx
```

Based on the above finding, it makes sense to change the behavior of `robot:skip` and `robot:exclude`. It's so easy, and the current inconsistency so annoying, that I'll do that still in RF 7.2. It probably makes sense to explicitly document that tags are looked from the result object in case someone wants to modify them dynamically using a listener.

**Comment by pekkaklarck** [comment]
Also tags matched against `--skip` have this same problem and that's easy to fix when fixing `robot:skip`.

Also `--include` and `--exclude` are affected, but because they are handled before execution even starts, fixing them is harder. In practice we needed to look them again before each test starts. It wouldn't be that complicated and shouldn't in practice have performance effects, but it's nevertheless too big a task for RF 7.2. `robot:exclude` being fixed as part of this issue also makes it possible to use tags when excluding tests.

**Comment by pekkaklarck** [comment]
It turned out that `robot:continue-on-failure` and related tags worked with variables when used with tests but not when used with user keywords. `robot:skip-on-failure`, `robot:exit-on-failure` and `robot:flatten` worked fine. I fixed all cases where variables didn't work and added tests also for those tags that didn't need fixes. See the above commit for details.

**Comment by pekkaklarck** [comment]
This change was not fully backwards compatible. Earlier listeners could skip tests dynamically by altering tags like this:

```python
def start_test(data, result):
    if some_condition:
        data.tags.add("robot:skip")
```

Now that we are looking tags from the result object, not from the data object, the above doesn't work anymore. Luckily fixing listeners is as easy as this:

```python
def start_test(data, result):
    if some_condition:
        data.tags.add("robot:skip")
        result.tags.add("robot:skip")
```

When targeting only RF 7.2 and newer, it is enough to only modify `result`, not `data`.
